Update alert-policies.md
MicrosoftDocs/microsoft-365-docs pull request #10006
Opened 2022-10-20 14:15 UTC by msbemba

Made changes to the permissions needed in Azure AD as well 

Reference https://learn.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-alert-policies?view=o365-worldwide#alert-policy-permissions

2022-10-20 14:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-20 14:15 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9985

2022-10-20 14:20 UTC, opbld30 commented
Learn Build status updates of commit _[47dcda8](https://github.com/msbemba/microsoft-365-docs/commits/47dcda8606aaf6d7067c73667925b9864b9b5d8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/alert-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1280/microsoft-365/compliance/alert-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210201415067987-10006/BuildReport?accessString=482d9a5967b6d5a6689647a7e58c364aeb74527c0c40273c24a07bf309b01e9a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 04:45 UTC, JohanFreelancer9 commented on microsoft-365/compliance/alert-policies.md
> + In addition to holding a Compliance Manager role, users also need an Azure AD role as follows:
```suggestion
   In addition to holding a Compliance Manager role, users also need an Azure AD role as follows:

```

2022-10-21 04:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/alert-policies.md
> +To create or update alert policies: the Compliance administrator, Compliance data administrator, Security administrator, or Security operator role in Azure AD
```suggestion
- To view alerts and alert policies: the Security reader role in Azure AD.
- To create or update alert policies: the Compliance administrator, Compliance data administrator, Security administrator, or Security operator role in Azure AD.
```

2022-10-21 04:53 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-21 07:26 UTC, opbld30 commented
Learn Build status updates of commit _[77d6cd9](https://github.com/msbemba/microsoft-365-docs/commits/77d6cd9d7be5c1fb264282167adb59a72d94f932)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/alert-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1280/microsoft-365/compliance/alert-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210210724246640-10006/BuildReport?accessString=5bba01314861e87ff22beb4037755cb95a3e2349ec213ab721b0f61ba65b3228).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 08:21 UTC, JohanFreelancer9 approved these changes

2022-10-21 11:36 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2022-11-01 10:48 UTC, yogkumgit commented
@robmazz Gentle reminder

2022-12-08 20:49 UTC, opbld33 commented
Learn Build status updates of commit _[38ff2c9](https://github.com/msbemba/microsoft-365-docs/commits/38ff2c97e6113d8585fe10ae5eddf79f36c0861c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/alert-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1280/microsoft-365/compliance/alert-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082046562993-10006/BuildReport?accessString=e0bf4e5ed63accfcf0f1780b15954039f593b0cb9a438a352e5299daeee1b5b5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-06-19 11:07 UTC, yogkumgit commented
Closing as per the comment in #9985

2023-06-19 11:07 UTC, closed without merging