Update bookings-in-outlook.md
MicrosoftDocs/microsoft-365-docs pull request #10034
Opened 2022-10-23 00:29 UTC by msbemba

Added cmds to controlling access to EWS

2022-10-23 00:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-23 00:30 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10002

2022-10-23 00:31 UTC, opbld31 commented
Learn Build status updates of commit _[0fbbdcd](https://github.com/msbemba/microsoft-365-docs/commits/0fbbdcd6400a5963771f9c4c10bf5b51785e3763)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1287/microsoft-365/bookings/bookings-in-outlook.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210230029520928-10034/BuildReport?accessString=2b2bfff416c55574a38e943d308042fea30e7727a683b9d8710f378c7ed38824).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 08:36 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-in-outlook.md
> +    - To turn on Bookings with me for your organization, You must set the **EwsApplicationAccessPolicy** to **EnforceAllowList** and  add **MicrosoftOWSPersonalBookings** to **EwsAllowList** by runni
```suggestion
    - To turn on Bookings with me for your organization, you must set the **EwsApplicationAccessPolicy** to **EnforceAllowList** and add **MicrosoftOWSPersonalBookings** to **EwsAllowList** by running the following command:  
```

2022-10-24 08:37 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-24 09:48 UTC, opbld33 commented
Learn Build status updates of commit _[a85ba46](https://github.com/msbemba/microsoft-365-docs/commits/a85ba461078cd60e15e62dd7bd714c9ff19e5610)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1287/microsoft-365/bookings/bookings-in-outlook.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210240944174196-10034/BuildReport?accessString=a3c8faea10ae4af2b4ce8723a428baf542246e9683d7f28e064d79522b735bb2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 16:23 UTC, JohanFreelancer9 approved these changes

2022-10-26 19:42 UTC, opbld32 commented
Learn Build status updates of commit _[6314ab3](https://github.com/msbemba/microsoft-365-docs/commits/6314ab3ad2541575aaa82c5b5c26d035d3161b88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1287/microsoft-365/bookings/bookings-in-outlook.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210261940375317-10034/BuildReport?accessString=6e5388fb20d4eb49ced4c9f0f245029545a41df5324b6b7bc5f3ebefc3d4c084).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 19:47 UTC, merged