Update enable-usage-analytics.md
MicrosoftDocs/microsoft-365-docs pull request #10035
Opened 2022-10-23 00:34 UTC by msbemba

Updated the navigation to initiate the template  for usage analytics

2022-10-23 00:34 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-23 00:34 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9999

2022-10-23 00:36 UTC, opbld33 commented
Learn Build status updates of commit _[dfb1df8](https://github.com/msbemba/microsoft-365-docs/commits/dfb1df8356c06334fa878a7b887cb6cb53f777a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1288/microsoft-365/admin/usage-analytics/enable-usage-analytics.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210230034388760-10035/BuildReport?accessString=1690388511a2657724d050fde361457fd5eeac9e0b96e715bf413164a9b4a13c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 04:41 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-24 08:39 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/enable-usage-analytics.md
> +To get started with Microsoft 365 usage analytics you must first make the data available in the <a href="https://go.microsoft.com/fwlink/p/?linkid=2024339" target="_blank">Microsoft 365 admin center<
```suggestion
To get started with Microsoft 365 usage analytics you must first make the data available in the <a href="https://go.microsoft.com/fwlink/p/?linkid=2024339" target="_blank">Microsoft 365 admin center</a>, then select **Reports** > **Usage** and initiate the template app in Power BI.
```

2022-10-24 08:39 UTC, JohanFreelancer9 approved these changes

2022-10-24 08:40 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-24 09:48 UTC, opbld31 commented
Learn Build status updates of commit _[0712abd](https://github.com/msbemba/microsoft-365-docs/commits/0712abd23ec58ab18f2ec27abb83d5239c138d27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1288/microsoft-365/admin/usage-analytics/enable-usage-analytics.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210240945592586-10035/BuildReport?accessString=09122c32c8fd391bb9b3285382aed9797ba38a04426d8ee624a395374c1c20bb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 16:15 UTC, JohanFreelancer9 approved these changes

2022-10-25 06:32 UTC, yogkumgit commented
@efrene Please merge this Pr. Thanks

2022-10-25 16:01 UTC, opbld33 commented
Learn Build status updates of commit _[d0d9e32](https://github.com/msbemba/microsoft-365-docs/commits/d0d9e32d1e183f8e55fdcdb8cc8a2ad989cd762a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1288/microsoft-365/admin/usage-analytics/enable-usage-analytics.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210251559252823-10035/BuildReport?accessString=1ad0409fbb8cfb25490bd27b1c3f52b4a6434d4eeb087fe2f3b3bbfcf2af355f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-25 16:18 UTC, opbld32 commented
Learn Build status updates of commit _[0020d5a](https://github.com/msbemba/microsoft-365-docs/commits/0020d5ac8d6a811a98ab06848b59d89ac9b71b4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1288/microsoft-365/admin/usage-analytics/enable-usage-analytics.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210251616258127-10035/BuildReport?accessString=5ed6e3ade7cf046d4935e851859090dee30f34c25e10b11c94dc3122d87e3d2b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-25 16:19 UTC, merged