Change 2nd step of Turn on cloud protection on individual clients
MicrosoftDocs/microsoft-365-docs pull request #10033
Opened 2022-10-22 20:54 UTC by viniciusornague

Change from:
2. Select the **Virus & threat protection** tile (or the shield icon on the left menu bar), and then, under **Manage settings** select **Virus & threat protection settings**. 
To:
2. Select the **Virus & threat protection** tile (or the shield icon on the left menu bar), and then, under **Virus & threat protection settings** select **Manage settings**.

2022-10-22 20:56 UTC, opbld32 commented
Learn Build status updates of commit _[0399f25](https://github.com/viniciusornague/microsoft-365-docs/commits/0399f25d1eccd67f4bb1016d1f050f2220fd286b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/viniciusornague/microsoft-365-docs/blob/patch-2/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210222054180512-10033/BuildReport?accessString=74d886c8c932cb4cb97b2249347bb70a14afb38b80c24efa120ff0c5c980b423).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 08:23 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md
> +2. Select the **Virus & threat protection** tile (or the shield icon on the left menu bar), and then, under **Virus & threat protection settings** select **Manage settings**.
```suggestion
2. Select the **Virus & threat protection** tile (or the shield icon on the left menu bar), and then, under **Virus & threat protection settings**, select **Manage settings**.
```

2022-10-24 08:24 UTC, JohanFreelancer9 requested changes
Copy review - @viniciusornague, kindly commit the minor suggested change. Many thanks.

2022-10-24 09:50 UTC, opbld31 commented
Learn Build status updates of commit _[86acffd](https://github.com/viniciusornague/microsoft-365-docs/commits/86acffdbc5e3d9549a092eccfb1936ec742728b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/viniciusornague/microsoft-365-docs/blob/patch-2/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210240948109674-10033/BuildReport?accessString=b4ab176afed2e3ff2782576cfd68bfe20ab04b4fe210f81ff6f9b3f280ee9e05).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 16:32 UTC, JohanFreelancer9 approved these changes

2022-10-24 16:44 UTC, denisebmsft approved these changes
Thank you @viniciusornague @JohanFreelancer9

2022-10-24 16:45 UTC, opbld30 commented
Learn Build status updates of commit _[c8d22ec](https://github.com/viniciusornague/microsoft-365-docs/commits/c8d22ec1c4ca0f736d40f9d7fd586ac9a3254c23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/viniciusornague/microsoft-365-docs/blob/patch-2/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210241643589921-10033/BuildReport?accessString=43a6f98a7a27b5005904ae0d25bdde3cf8154e63c05d1dcb7506444db36621d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 16:49 UTC, merged