Update streaming-api-storage.md
MicrosoftDocs/microsoft-365-docs pull request #10055
Opened 2022-10-25 15:12 UTC by msbemba

Updated the navigation to copy the resource ID

2022-10-25 15:12 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10024

2022-10-25 15:12 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-25 15:13 UTC, opbld33 commented
Learn Build status updates of commit _[ce2d918](https://github.com/msbemba/microsoft-365-docs/commits/ce2d918edf6916476cccfe614c195dd29e666c11)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender/streaming-api-storage.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1294/microsoft-365/security/defender/streaming-api-storage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210251512124678-10055/BuildReport?accessString=62f4715309bc2dc9d637c3242a93f5438e1bea8445bf757c6e3613f5117be746).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 05:16 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/streaming-api-storage.md
> +   3. To display the Azure Resource Manager resource ID for a storage account in the Azure portal, follow these steps:
```suggestion
3. To display the Azure Resource Manager resource ID for a storage account in the Azure portal, follow these steps:
```

2022-10-26 05:17 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/streaming-api-storage.md
> +1. The resource ID for the storage account is displayed at the top of the page, copy the text under **Storage Account Resource ID**.
```suggestion
   1. Navigate to your storage account in the Azure portal.
   2. On the **Overview** page, in the **Essentials** section, select the **JSON View** link.
   3. The resource ID for the storage account is displayed at the top of the page, copy the text under **Storage Account Resource ID**.
```

2022-10-26 05:32 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, kindly look at the preview to make sure that the formatting is correct. Many thanks.

2022-10-26 10:56 UTC, opbld30 commented
Learn Build status updates of commit _[71c016c](https://github.com/msbemba/microsoft-365-docs/commits/71c016c695155c0906c8a4687666efeabc658e5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender/streaming-api-storage.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1294/microsoft-365/security/defender/streaming-api-storage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210261054498580-10055/BuildReport?accessString=61514f14f58c59770aea5867f7ce98a8bc05160a802fc5f3cf68c5d85512d1c0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 10:58 UTC, opbld33 commented
Learn Build status updates of commit _[e7cf845](https://github.com/msbemba/microsoft-365-docs/commits/e7cf84542b066c8a362974997a711dfe318b0259)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender/streaming-api-storage.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1294/microsoft-365/security/defender/streaming-api-storage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210261055034725-10055/BuildReport?accessString=63bd491720562e78a6c4afaf5d996a008261fa1b498f2f6044010c2f7529542b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 11:45 UTC, JohanFreelancer9 approved these changes

2022-10-26 12:43 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-10-26 19:14 UTC, opbld30 commented
Learn Build status updates of commit _[43de864](https://github.com/msbemba/microsoft-365-docs/commits/43de8646c27e2a3fe67fb4cd11a788bdb2dfd5aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender/streaming-api-storage.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1294/microsoft-365/security/defender/streaming-api-storage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210261908308952-10055/BuildReport?accessString=0f55223c1e004184cd61148b068e76d895031d300e5f3bd113bd2ea691bdeebc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 19:19 UTC, merged