Update data-classification-content-explorer.md
MicrosoftDocs/microsoft-365-docs pull request #10056
Opened 2022-10-25 15:15 UTC by msbemba

Added a note about the delay due to crawl on Custom SIT

2022-10-25 15:15 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10023

2022-10-25 15:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-25 15:17 UTC, opbld30 commented
Learn Build status updates of commit _[2a15b32](https://github.com/msbemba/microsoft-365-docs/commits/2a15b3235626dd5d2455d22055a1d4a118840425)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1295/microsoft-365/compliance/data-classification-content-explorer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210251515277574-10056/BuildReport?accessString=ac07de8fad8943d9220d3d05c8f1235f39f81bba049ee5b7759239a4370871db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 05:40 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-content-explorer.md
> +> Custom Sensitive information types could take upto 48 hours due to crawl.
```suggestion
> Custom sensitive information types could take up to 48 hours due to crawling.
```

2022-10-26 05:46 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-26 10:56 UTC, opbld33 commented
Learn Build status updates of commit _[2038c9d](https://github.com/msbemba/microsoft-365-docs/commits/2038c9d469b576e31c9344b0487d3edb3ae9aead)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1295/microsoft-365/compliance/data-classification-content-explorer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210261054281586-10056/BuildReport?accessString=fada7785a4ee7b6af1a95a97efb563868645a7c52bd62246c7ceced38bd4798f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 11:41 UTC, JohanFreelancer9 approved these changes

2022-10-26 12:47 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-10-28 17:47 UTC, chrfox commented
confirming with PG

2022-10-31 11:36 UTC, opbld30 commented
Learn Build status updates of commit _[35baf47](https://github.com/msbemba/microsoft-365-docs/commits/35baf478e02e020d916a562c7d7e92cd13b1bdac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1295/microsoft-365/compliance/data-classification-content-explorer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210311132430726-10056/BuildReport?accessString=6688d7f7d96c15294c2222892229cb195e913f003baf351488271a820933b680).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-31 15:29 UTC, chrfox commented
The requested change is incorrect, closing without merging

2022-10-31 15:29 UTC, closed without merging