Added 3p oath TOTP apps as options
MicrosoftDocs/microsoft-365-docs pull request #10069
Opened 2022-10-26 10:26 UTC by Sammak

2022-10-26 10:28 UTC, opbld32 commented
Learn Build status updates of commit _[8defd82](https://github.com/Sammak/microsoft-365-docs/commits/8defd82b52cd218a0ae3ddc3d78fb7ca7440a03f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210261026389267-10069/BuildReport?accessString=5ee0ac644f44d53a247f216f3125c30efe717bca9878a30a92a9d34f18513c16).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 22:02 UTC, opbld31 commented
Learn Build status updates of commit _[823457d](https://github.com/Sammak/microsoft-365-docs/commits/823457dbce3ce264787600df6b3aad6c9b492812)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210262200377554-10069/BuildReport?accessString=e19d9c02ceae23168d841d7091a3465d32d54d32fba22e15d38270ba81f93779).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 22:04 UTC, opbld33 commented
Learn Build status updates of commit _[b7e2ca1](https://github.com/Sammak/microsoft-365-docs/commits/b7e2ca10e8edf268a9075ce5f09cc5af45dc1a25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210262201445891-10069/BuildReport?accessString=819556ab4cc1c540101942217eb90dc4b339ed0d33a32ab238de901d5d1cfbd9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 06:57 UTC, JohanFreelancer9 commented on microsoft-365/business-premium/m365bp-conditional-access.md
> +- Requiring all users and admins to register for MFA using the (Microsoft Authenticator app)[../authentication/concept-authentication-authenticator-app.md] or any third-party application using (OATH
```suggestion
- Requiring all users and admins to register for MFA using the [Microsoft Authenticator app](../authentication/concept-authentication-authenticator-app.md] or any third-party application using [OATH TOTP](/azure/active-directory/authentication/concept-authentication-oath-tokens#oath-software-tokens).
```

2022-10-27 07:04 UTC, JohanFreelancer9 requested changes
Copy review - @Sammak, kindly commit the suggested changes. Many thanks.

2022-10-27 13:26 UTC, Sammak commented
@JohanFreelancer9 Done, thanks!

2022-10-27 13:27 UTC, opbld30 commented
Learn Build status updates of commit _[21ffa53](https://github.com/Sammak/microsoft-365-docs/commits/21ffa536437e071deb29e8951af6c2a9d0d1c29d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md) | :warning:Warning | | [Details](#user-content-d5d012db2dbc437d8bd76c40b9bdac4f-8c519a19)

<a id="d5d012db2dbc437d8bd76c40b9bdac4f-8c519a19"></a>
### [microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md)
 - **Line 44, Column 64**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../authentication/concept-authentication-authenticator-app.md'.`````
 - **Line 44, Column 194**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../authentication/concept-authentication-oath-tokens.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210271326048256-10069/BuildReport?accessString=1d659d965503ad9ae13633ced6bc2a7c2c11a1c2cd87aca2b281613e49003f13).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 13:29 UTC, opbld32 commented
Learn Build status updates of commit _[60a3463](https://github.com/Sammak/microsoft-365-docs/commits/60a346351077f27618c7e084f473465949a07c45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md) | :warning:Warning | | [Details](#user-content-d5d012db2dbc437d8bd76c40b9bdac4f-d91ac24d)

<a id="d5d012db2dbc437d8bd76c40b9bdac4f-d91ac24d"></a>
### [microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md)
 - **Line 44, Column 64**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../authentication/concept-authentication-authenticator-app.md'.`````
 - **Line 44, Column 194**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../authentication/concept-authentication-oath-tokens.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210271326161774-10069/BuildReport?accessString=bbd30a410899be35e4ee9438c919b77e166de34175f034ea13690271488ce922).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-28 07:53 UTC, JohanFreelancer9 approved these changes

2022-10-28 18:41 UTC, opbld31 commented
Learn Build status updates of commit _[577cd3b](https://github.com/Sammak/microsoft-365-docs/commits/577cd3bf94ef1eee64b3b9901672551322678afb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210281839494778-10069/BuildReport?accessString=69687de4e4ec58f68a7b533bc9da605bc5405e0d3f55019aa44d613efd31d4d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-28 18:45 UTC, opbld33 commented
Learn Build status updates of commit _[377e022](https://github.com/Sammak/microsoft-365-docs/commits/377e02295ca38cf4179afc188d26d2ade6a898f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/Sammak/microsoft-365-docs/blob/patch-1/microsoft-365/business-premium/m365bp-conditional-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210281843374594-10069/BuildReport?accessString=6b5dc42befdb0ead03b1e49336f02b1173b694acf3737b96357654e6d040605d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-28 18:46 UTC, denisebmsft approved these changes
Thank you @Sammak and @JohanFreelancer9

2022-10-28 18:46 UTC, merged