Update linux-preferences.md
MicrosoftDocs/microsoft-365-docs pull request #10079
Opened 2022-10-27 11:09 UTC by msbemba

Added a note stating that  It is not possible to control all Microsoft Defender for endpoint communication only with proxy setting in this json.

2022-10-27 11:09 UTC, msbemba commented
@JohanFreelancer9 Please copy review

Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10038

2022-10-27 11:11 UTC, opbld30 commented
Learn Build status updates of commit _[e60aeb4](https://github.com/msbemba/microsoft-365-docs/commits/e60aeb4325a58b29675704d72c57e3b65162993b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-preferences.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1299/microsoft-365/security/defender-endpoint/linux-preferences.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210271109100522-10079/BuildReport?accessString=3cb43871ba69ed4bb2fda91010e2892749890cc9cee877a62b8bd45a52364ffe).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 11:45 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-28 07:32 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/linux-preferences.md
> +> It is not possible to control all Microsoft Defender for endpoint communication only with proxy setting in this json.
```suggestion
> It is not possible to control all Microsoft Defender for Endpoint communication with only a proxy setting in this JSON.
```

2022-10-28 07:32 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-28 09:58 UTC, opbld33 commented
Learn Build status updates of commit _[fd6c580](https://github.com/msbemba/microsoft-365-docs/commits/fd6c5806e39e4071dbe6820f6cd3240aebe6a9f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-preferences.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1299/microsoft-365/security/defender-endpoint/linux-preferences.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210280956110724-10079/BuildReport?accessString=86dcfd49b859afa60f8efe8a85e5a5872ca692eca77b7057e49746336551672e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-28 12:14 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-28 12:15 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2022-10-28 13:56 UTC, JohanFreelancer9 approved these changes

2022-11-01 07:49 UTC, opbld31 commented
Learn Build status updates of commit _[bc8d6a5](https://github.com/msbemba/microsoft-365-docs/commits/bc8d6a59d6b1edcbb5f05050ea3500854d0c0059)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-preferences.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1299/microsoft-365/security/defender-endpoint/linux-preferences.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211010736562612-10079/BuildReport?accessString=97aad1aa918a0f42c22df1f1d4ae8c05ecd6d1642473932375bce1b4c84e6ef4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-01 10:51 UTC, opbld32 commented
Learn Build status updates of commit _[889fe53](https://github.com/msbemba/microsoft-365-docs/commits/889fe53093fef8e88594cefb404342b8e7c676a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-preferences.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1299/microsoft-365/security/defender-endpoint/linux-preferences.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211011048083804-10079/BuildReport?accessString=11c832624c00fe93a2c08a56a059c95193692d6121ac6f32d4ad9186d14f772b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-01 10:52 UTC, merged