Add supporting link for final statement
MicrosoftDocs/microsoft-365-docs pull request #10147
Opened 2022-11-03 23:08 UTC by JeremyTBradshaw

The last statement on the page says to make sure to prepare the users for the changes they can expect, but there's nothing on this page that describes what to expect.  I added a sentence and link to where that info can be seen.

2022-11-03 23:10 UTC, opbld33 commented
Learn Build status updates of commit _[55e707c](https://github.com/JeremyTBradshaw/microsoft-365-docs/commits/55e707c538325cf63dd0dfe396bfeb8e69e6a917)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :warning:Warning | | [Details](#user-content-a29176b917612325eb861b29a6452462-58da5114)

<a id="a29176b917612325eb861b29a6452462-58da5114"></a>
### [microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md)
 - **Line 140, Column 249**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 140, Column 249**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 140, Column 249**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211032308198394-10147/BuildReport?accessString=87a79eff099c1e1b4b408b549739c1a0ac5fc69ba787fd0ece663774f01f1d03).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-03 23:18 UTC, opbld33 commented
Learn Build status updates of commit _[4f1445f](https://github.com/JeremyTBradshaw/microsoft-365-docs/commits/4f1445f4cd68333f4591ee1f64b7f3a8c13ecf09)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :warning:Warning | | [Details](#user-content-a29176b917612325eb861b29a6452462-a69a2c8c)

<a id="a29176b917612325eb861b29a6452462-a69a2c8c"></a>
### [microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md)
 - **Line 140, Column 249**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 140, Column 249**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 140, Column 249**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211032314233964-10147/BuildReport?accessString=8ec393c3a64d821c00e66c5e9a177c0dd0199c4950680f9461a027419607969d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-04 09:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/enable-autoexpanding-archiving.md
> +Make sure you prepare end users for the changes they can expect after enabling their mailbox for auto-expanding archives.  For a brief overview of the client experience, see the "What gets moved to t
```suggestion
Make sure you prepare end users for the changes they can expect after enabling their mailbox for auto-expanding archives.  For a brief overview of the client experience, see [What gets moved to the additional archive storage space?](https://learn.microsoft.com/microsoft-365/compliance/autoexpanding-archiving#what-gets-moved-to-the-additional-archive-storage-space).
```

2022-11-04 09:15 UTC, JohanFreelancer9 requested changes
Copy review - @JeremyTBradshaw, kindly commit the suggested change. Many thanks.

2022-11-05 01:13 UTC, opbld31 commented
Learn Build status updates of commit _[5368484](https://github.com/JeremyTBradshaw/microsoft-365-docs/commits/5368484652de7066ee8327513c3bd07f74e5631f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :warning:Warning | | [Details](#user-content-a29176b917612325eb861b29a6452462-f6a43ecb)

<a id="a29176b917612325eb861b29a6452462-f6a43ecb"></a>
### [microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md)
 - **Line 140, Column 249**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 140, Column 249**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 140, Column 249**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide#what-gets-moved-to-the-additional-archive-storage-space`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211050111294894-10147/BuildReport?accessString=b5203b8a7b6d707dd6248c9ae3036296110085cd63a807c9d3891a2e5f30c8a3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-05 01:26 UTC, opbld31 commented
Learn Build status updates of commit _[5974003](https://github.com/JeremyTBradshaw/microsoft-365-docs/commits/5974003fe0c666427a0a16722b35197e190774fa)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :bulb:Suggestion | | [Details](#user-content-a29176b917612325eb861b29a6452462-0c2a96c0)

<a id="a29176b917612325eb861b29a6452462-0c2a96c0"></a>
### [microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md)
 - **Line 140, Column 175**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/microsoft-365/compliance/autoexpanding-archiving#what-gets-moved-to-the-additional-archive-storage-space' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211050124354439-10147/BuildReport?accessString=b550b4bb13b76ec88f2cb40e68a2d240fc6aa436b0857388809b6ceaad13212b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-05 08:02 UTC, JohanFreelancer9 commented on microsoft-365/compliance/enable-autoexpanding-archiving.md
> +Make sure you prepare end users for the changes they can expect after enabling their mailbox for auto-expanding archives.  For a brief overview of the client experience, see [What gets moved to the a
```suggestion
Make sure you prepare end users for the changes they can expect after enabling their mailbox for auto-expanding archives. For a brief overview of the client experience, see [What gets moved to the additional archive storage space?](/microsoft-365/compliance/autoexpanding-archiving#what-gets-moved-to-the-additional-archive-storage-space).
```

2022-11-05 08:06 UTC, JohanFreelancer9 requested changes
Copy review - @JeremyTBradshaw, kindly commit the suggested change to remove the extra space and change the link to a relative link. Many thanks.

2022-11-05 13:04 UTC, JeremyTBradshaw commented
Done, thanks again.

2022-11-05 13:05 UTC, opbld33 commented
Learn Build status updates of commit _[b2324eb](https://github.com/JeremyTBradshaw/microsoft-365-docs/commits/b2324eba4ccb0344ab17e688fa0e69764d2e03f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211051303195165-10147/BuildReport?accessString=c4a0de5ea1949e0f1962209799f34639d359383f5b51cef2ebc342c94e923aef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-06 04:45 UTC, JohanFreelancer9 approved these changes
Thank you @JeremyTBradshaw.

2022-11-11 12:10 UTC, opbld31 commented
Learn Build status updates of commit _[e31d96a](https://github.com/JeremyTBradshaw/microsoft-365-docs/commits/e31d96ae1182ab87fd3ca8c398daa67d3c415723)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211111208044923-10147/BuildReport?accessString=8694af2d9f5349f4fb85769500780f478d6839b5ae6850e6a4e40386e9b081e3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 20:47 UTC, opbld32 commented
Learn Build status updates of commit _[8e5c30a](https://github.com/JeremyTBradshaw/microsoft-365-docs/commits/8e5c30ac945a2176f1face6542c3de637af45475)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/JeremyTBradshaw/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082046136664-10147/BuildReport?accessString=b0c1b336587a590cfaa201dbce7df47b08652a540ffb4ee287b1d343853e1f6b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 22:48 UTC, closed without merging