Update device-onboarding-overview.md
MicrosoftDocs/microsoft-365-docs pull request #10168
Opened 2022-11-07 20:08 UTC by msbemba

Updated 5. with "A supported version of Microsoft 365 Apps is installed" as Perpetual office is not supported.

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10149

2022-11-07 20:08 UTC, msbemba commented
@JohanFreelancer9 please copy review

2022-11-07 20:12 UTC, opbld32 commented
Learn Build status updates of commit _[0dcd8fe](https://github.com/msbemba/microsoft-365-docs/commits/0dcd8fe49b20aa517af8d9f933464cf940606795)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/device-onboarding-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1310/microsoft-365/compliance/device-onboarding-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211072008390336-10168/BuildReport?accessString=193e8d7935b4b13fb5ae9d69eac77d2e8fd052ecab922f1dde29a86286b894ab).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 06:32 UTC, JohanFreelancer9 commented on microsoft-365/compliance/device-onboarding-overview.md
> +5. A supported version of Microsoft 365 Apps is installed and up to date. For the most robust protection and user experience, ensure Microsoft 365 Apps version 16.0.14701.0 or newer is installed.
```suggestion
5. A supported version of Microsoft 365 Apps is installed and up to date. For the most robust protection and user experience, ensure Microsoft 365 Apps version 16.0.14701.0 or later is installed.
```

2022-11-08 06:32 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-08 07:35 UTC, opbld30 commented
Learn Build status updates of commit _[0a81c19](https://github.com/msbemba/microsoft-365-docs/commits/0a81c194c56f4375ddae875d836631af606a36f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/device-onboarding-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1310/microsoft-365/compliance/device-onboarding-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211080733137302-10168/BuildReport?accessString=d720ecc45148b90cbeff0a84249167713113d486d2a5d0c1be83658fbe3e0953).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 08:32 UTC, yogkumgit commented
@JohanFreelancer9

2022-11-08 08:32 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-11-08 11:05 UTC, JohanFreelancer9 approved these changes

2022-12-08 20:47 UTC, opbld31 commented
Learn Build status updates of commit _[ce3e317](https://github.com/msbemba/microsoft-365-docs/commits/ce3e3170f0e4ce9a1f7ae52066533b26dce24962)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/device-onboarding-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1310/microsoft-365/compliance/device-onboarding-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082046033845-10168/BuildReport?accessString=b0bd88be84ce04c8e46c2ed8fd48662f74bfd9690131f3656fd527f5eb3199ac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-04-27 23:44 UTC, merged