Update investigate-files.md
MicrosoftDocs/microsoft-365-docs pull request #10174
Opened 2022-11-08 09:35 UTC by MrOS19

Updated the changes in file page which are now GA (Oren Saban - Microsoft)

2022-11-08 09:36 UTC, opbld33 commented
Learn Build status updates of commit _[a2a5a89](https://github.com/MrOS19/microsoft-365-docs/commits/a2a5a89b7a2955eff6ab1f3f63db55bca339623f)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MrOS19/microsoft-365-docs/blob/patch-3/microsoft-365/security/defender-endpoint/investigate-files.md) | :bulb:Suggestion | | [Details](#user-content-083f4add0ed7d781cd7d5ccd36bd9dc6-838f8f2a)

<a id="083f4add0ed7d781cd7d5ccd36bd9dc6-838f8f2a"></a>
### [microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MrOS19/microsoft-365-docs/blob/patch-3/microsoft-365/security/defender-endpoint/investigate-files.md)
 - **Line 77, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````
 - **Line 84, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````
 - **Line 114, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211080935027310-10174/BuildReport?accessString=978d18be6e73a93518ea1ce4e6037285484d79998821859c934ac2558d6d1d02).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 18:49 UTC, opbld33 commented
Learn Build status updates of commit _[5c100c7](https://github.com/MrOS19/microsoft-365-docs/commits/5c100c7dfe1d5f9d648d05b5f7834bbac7b010af)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MrOS19/microsoft-365-docs/blob/patch-3/microsoft-365/security/defender-endpoint/investigate-files.md) | :bulb:Suggestion | | [Details](#user-content-083f4add0ed7d781cd7d5ccd36bd9dc6-f9cac2e6)

<a id="083f4add0ed7d781cd7d5ccd36bd9dc6-f9cac2e6"></a>
### [microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MrOS19/microsoft-365-docs/blob/patch-3/microsoft-365/security/defender-endpoint/investigate-files.md)
 - **Line 77, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````
 - **Line 84, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````
 - **Line 114, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211081847275455-10174/BuildReport?accessString=5851c2227eab92a5d8c61a39bbb118d3dd06a9dfd8abb88d06f5daab7382c13d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 18:53 UTC, opbld30 commented
Learn Build status updates of commit _[73d55f7](https://github.com/MrOS19/microsoft-365-docs/commits/73d55f71d017f10c5966c070438785c083d77fb8)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MrOS19/microsoft-365-docs/blob/patch-3/microsoft-365/security/defender-endpoint/investigate-files.md) | :bulb:Suggestion | | [Details](#user-content-083f4add0ed7d781cd7d5ccd36bd9dc6-41aad3cb)

<a id="083f4add0ed7d781cd7d5ccd36bd9dc6-41aad3cb"></a>
### [microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MrOS19/microsoft-365-docs/blob/patch-3/microsoft-365/security/defender-endpoint/investigate-files.md)
 - **Line 77, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````
 - **Line 84, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````
 - **Line 114, Column 1**: **[Suggestion: duplicate-alt-text - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'image' is duplicated. Within an article, alt text must be unique.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211081847413211-10174/BuildReport?accessString=49cb18e7b5b526fd3dc07a44fb407924ad228ca71740a54ce2461764f41522b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 09:16 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/investigate-files.md
> +The **Incidents and alerts** tab provides a list of incidents that are associated with the file, as well as the alerts  the file is linked to. This list covers much of the same information as the inc
```suggestion
The **Incidents and alerts** tab provides a list of incidents that are associated with the file, as well as the alerts the file is linked to. This list covers much of the same information as the incidents queue. You can choose what kind of information is shown by selecting **Customize columns** from the toolbar above the column headers.
```

2022-11-09 09:21 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/investigate-files.md
> +
```suggestion
```

2022-11-09 09:22 UTC, JohanFreelancer9 requested changes
Copy review - @MrOS19, kindly commit the suggested changes. Also, note that we can't link to images outside the repo.

2022-11-10 17:00 UTC, opbld33 commented
Learn Build status updates of commit _[645f160](https://github.com/MrOS19/microsoft-365-docs/commits/645f16085f109bd3c087f4901b14ea285b408331)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MrOS19/microsoft-365-docs/blob/patch-3/microsoft-365/security/defender-endpoint/investigate-files.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211101658021427-10174/BuildReport?accessString=19e85f75e54db485799741f8d34d8ebf72d8f4a008d16d298425b20ef2ccc172).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 17:02 UTC, opbld32 commented
Learn Build status updates of commit _[172c27b](https://github.com/MrOS19/microsoft-365-docs/commits/172c27b12c6ab915bd2e2d6969b611bb455b0eb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MrOS19/microsoft-365-docs/blob/patch-3/microsoft-365/security/defender-endpoint/investigate-files.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211101659597234-10174/BuildReport?accessString=bc7efbc3a8cfbffd443dfde4f44692709294313cfa9274cfe2c1dd547d55388f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 17:07 UTC, denisebmsft approved these changes
Thank you @MrOS19 @JohanFreelancer9

2022-11-10 17:07 UTC, merged