Update add-storage-space.md
MicrosoftDocs/microsoft-365-docs pull request #10185
Opened 2022-11-08 19:24 UTC by msbemba

The options have changed with NCE and the add-on shows as a subscription and there is no manage add-on option

Per Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10140

2022-11-08 19:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-08 19:28 UTC, opbld30 commented
Learn Build status updates of commit _[dfcf35e](https://github.com/msbemba/microsoft-365-docs/commits/dfcf35e321184536f72f043ddf014739f228e784)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/commerce/add-storage-space.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1315/microsoft-365/commerce/add-storage-space.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211081924054865-10185/BuildReport?accessString=fa34fd5b0c745e3c64e32650e30cc0def671a29dcb12d372b58e06bb960ca192).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 06:03 UTC, JohanFreelancer9 commented on microsoft-365/commerce/add-storage-space.md
> +3. On the product details page,  select **Buy Licenses** or **Remove Liceses** based on your requirement.
```suggestion
2. On the **Products** tab, select the subscription **Office 365 Extra File Storage**.
3. On the product details page,  select **Buy Licenses** or **Remove Licenses** based on your requirement.
```

2022-11-09 06:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 06:56 UTC, opbld33 commented
Learn Build status updates of commit _[e563e7a](https://github.com/msbemba/microsoft-365-docs/commits/e563e7a30c0b6c2a87770bcafd3a076dd19e5e24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/commerce/add-storage-space.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1315/microsoft-365/commerce/add-storage-space.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211090653185445-10185/BuildReport?accessString=2d171f0ce9a5ed2d94bc1ff32b92e0f0e755b4f520f2f5b66932e9a4ede43b8e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 08:20 UTC, JohanFreelancer9 commented on microsoft-365/commerce/add-storage-space.md
> +3. On the product details page,  select **Buy Licenses** or **Remove Licenses** based on your requirement.
```suggestion
3. On the product details page, select **Buy Licenses** or **Remove Licenses** based on your requirement.
```

2022-11-09 08:21 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2022-11-09 09:17 UTC, opbld31 commented
Learn Build status updates of commit _[988ef27](https://github.com/msbemba/microsoft-365-docs/commits/988ef2756dce53382f03af30c921a7b7fd5dfcff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/commerce/add-storage-space.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1315/microsoft-365/commerce/add-storage-space.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211090915040600-10185/BuildReport?accessString=dcb18465436ec5f062a8025e766d9853b3c2175f14e84d98e6fe023b492f33ae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 09:48 UTC, JohanFreelancer9 approved these changes

2022-11-09 10:21 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2022-11-18 18:16 UTC, cmcatee-MSFT commented
@yogkumgit , @msbemba  - We can't replace existing procedures for this or any other article with steps for the updated billing experience. We have customers who will still be using the "old" UI for a long time to come and therefore must support both. I'm working through a list of articles like this, so if issues like this get reported, please just send them directly to me. Thanks.

2022-11-18 18:16 UTC, closed without merging

2022-11-21 05:26 UTC, yogkumgit commented
@msbemba Please acknowledge, and follow these instruction for the future. Thanks

2022-11-22 18:20 UTC, msbemba commented
> @yogkumgit , @msbemba - We can't replace existing procedures for this or any other article with steps for the updated billing experience. We have customers who will still be using the "old" UI for a long time to come and therefore must support both. I'm working through a list of articles like this, so if issues like this get reported, please just send them directly to me. Thanks.

Thank you, @cmcatee-MSFT