Update indicator-manage.md
MicrosoftDocs/microsoft-365-docs pull request #10183
Opened 2022-11-08 19:03 UTC by msbemba

Added a note that Importing Indicators with specific categories requires the string to be written on Pascal Case convention

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10146

2022-11-08 19:03 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-08 19:05 UTC, opbld30 commented
Learn Build status updates of commit _[15f737f](https://github.com/msbemba/microsoft-365-docs/commits/15f737fa394a2ab613cd7e88ae13cf7c4f75d9f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/indicator-manage.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1314/microsoft-365/security/defender-endpoint/indicator-manage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211081903289471-10183/BuildReport?accessString=fd3d6f5c0a6c710df2d61ce7292f096a913fde910bd6f03a5be04f427c330013).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 05:44 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/indicator-manage.md
> +> Attempting to import Indicators with specific categories requires the string to be written on Pascal Case convention and only accepts the category list available at the portal.
```suggestion
>
> Attempting to import indicators with specific categories requires the string to be written in Pascal case convention and only accepts the category list available at the portal.
```

2022-11-09 05:44 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 05:50 UTC, opbld31 commented
Learn Build status updates of commit _[f8d6230](https://github.com/msbemba/microsoft-365-docs/commits/f8d6230acdbb54e9d46119d1b7f51d72ea025dff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/indicator-manage.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1314/microsoft-365/security/defender-endpoint/indicator-manage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211090548337495-10183/BuildReport?accessString=5dc5f18fd03c4c7c632734093fa142a09c89413bfc531fc1ff6ac252e27ba5d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 07:19 UTC, JohanFreelancer9 approved these changes

2022-11-09 10:19 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-11-17 20:39 UTC, opbld31 commented
Learn Build status updates of commit _[d4b3f6e](https://github.com/msbemba/microsoft-365-docs/commits/d4b3f6eb975604f90857bc86abe19f44df6cce84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/indicator-manage.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1314/microsoft-365/security/defender-endpoint/indicator-manage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211172035444319-10183/BuildReport?accessString=742f509b4893127b01c363113d92143b98ab8017c18f221b969a061931ba5a7c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 20:46 UTC, merged