Update create-secure-guest-sharing-environment.md
MicrosoftDocs/microsoft-365-docs pull request #10196
Opened 2022-11-09 13:19 UTC by msbemba

Updated the section Set up web-only access for guests to reduce ambiguity

per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10161

2022-11-09 13:19 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-09 13:23 UTC, opbld32 commented
Learn Build status updates of commit _[5a9d946](https://github.com/msbemba/microsoft-365-docs/commits/5a9d946ea75a4737f7bb562b83d578880751dbaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1316/microsoft-365/solutions/create-secure-guest-sharing-environment.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091319323856-10196/BuildReport?accessString=1565eb41168c531694fd8a194e9edd5d5321e12f44faa8ca18b9f2ce4e090842).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 14:08 UTC, JohanFreelancer9 commented on microsoft-365/solutions/create-secure-guest-sharing-environment.md
> +You can require guests to not access your teams, sites, and files from non-compliant devices using non-browser client applications. Instead you'd want them to use web browser only. This reduces the c
```suggestion
You might require guests to not access your teams, sites, and files from non-compliant devices using non-browser client applications. Instead, you would want them to use a web browser only. This reduces the chance that they might download sensitive files and leave them on an unmanaged device. It is also useful when sharing with environments that use shared devices.
```

2022-11-09 14:10 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 14:47 UTC, opbld33 commented
Learn Build status updates of commit _[0004426](https://github.com/msbemba/microsoft-365-docs/commits/000442626bdcc6c5cd67ae2bd1e783ce650e8217)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1316/microsoft-365/solutions/create-secure-guest-sharing-environment.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091445431470-10196/BuildReport?accessString=c495c1814ee04f9dfa33e6f27bdfdd395c46c5e173a3beba6274da07a2466149).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 05:06 UTC, JohanFreelancer9 approved these changes

2022-11-10 05:49 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2022-11-10 11:43 UTC, opbld33 commented
Learn Build status updates of commit _[fb3948b](https://github.com/msbemba/microsoft-365-docs/commits/fb3948b84187d1bf78920def25c3ba55643950a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1316/microsoft-365/solutions/create-secure-guest-sharing-environment.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211101138147789-10196/BuildReport?accessString=5f01eeda4a1fb83ddc2253547af2c7213e36405b439c800f39eaf8842a29a82a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 11:55 UTC, opbld32 commented
Learn Build status updates of commit _[2000249](https://github.com/msbemba/microsoft-365-docs/commits/2000249444c73f6ea45037944cff34792f88bbe3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1316/microsoft-365/solutions/create-secure-guest-sharing-environment.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211101153541350-10196/BuildReport?accessString=7b9d85b235bd7b73fdfb5ed435ab248120892aebea9609994c3701894b814859).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 12:05 UTC, merged