Update api-hello-world.md
MicrosoftDocs/microsoft-365-docs pull request #10199
Opened 2022-11-09 13:34 UTC by msbemba

Added URL - Documentation link to the PS script. It needs to be a complete link as it is hashed

2022-11-09 13:35 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10173

@JohanFreelancer9 Please copy review

2022-11-09 13:38 UTC, opbld31 commented
Learn Build status updates of commit _[ada27b0](https://github.com/msbemba/microsoft-365-docs/commits/ada27b0eafea03ef91ef9c584c955e95f9fd14fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/api-hello-world.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1319/microsoft-365/security/defender-endpoint/api-hello-world.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091335001997-10199/BuildReport?accessString=c6a28f18da85388669b19650e5081bcd2dfc5bc3879b4899453ad61b86ca3c40).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 14:30 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/api-hello-world.md
> +  # Read more about other query options and filters at https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-alerts
```suggestion
  # Read more about [other query options and filters](/microsoft-365/security/defender-endpoint/get-alerts)
```

2022-11-09 14:38 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/api-hello-world.md
> +  # Read more about other query options and filters at https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-alerts
```suggestion
  # Read more about other query options and filters at https://learn.microsoft.com/microsoft-365/security/defender-endpoint/get-alerts
```

2022-11-09 14:38 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 14:46 UTC, opbld32 commented
Learn Build status updates of commit _[77032a9](https://github.com/msbemba/microsoft-365-docs/commits/77032a92411f01fca84e914a851122a5cf582231)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/api-hello-world.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1319/microsoft-365/security/defender-endpoint/api-hello-world.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091444507007-10199/BuildReport?accessString=4071c3189bf73402a4817ec79d9239e6440170b50b6664a60423652d2ece8b3c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 04:47 UTC, JohanFreelancer9 approved these changes

2022-11-10 05:55 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-11-17 20:51 UTC, opbld32 commented
Learn Build status updates of commit _[7582c8a](https://github.com/msbemba/microsoft-365-docs/commits/7582c8ab821118d8fd91f7749095aa1dc884dc2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/api-hello-world.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1319/microsoft-365/security/defender-endpoint/api-hello-world.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211172048267624-10199/BuildReport?accessString=5688abdd8d9209028243a0fda999b9aef883bf16aaefe1c6721daa71960bf3aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 20:55 UTC, opbld33 commented
Learn Build status updates of commit _[14a3a50](https://github.com/msbemba/microsoft-365-docs/commits/14a3a508787f2f8402dcabd02aafe0d12798d187)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/api-hello-world.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1319/microsoft-365/security/defender-endpoint/api-hello-world.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211172048443468-10199/BuildReport?accessString=2a996644a2c8f6353c5f1a65aa590114c2fcab3e559866f4946e2822babc0cef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 20:59 UTC, merged