Update technical-reference-details-about-encryption.md
MicrosoftDocs/microsoft-365-docs pull request #10207
Opened 2022-11-09 14:21 UTC by msbemba

made changes to Support for TLS 1.0 and 1.1 deprecation

2022-11-09 14:21 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-09 14:21 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10188

2022-11-09 14:30 UTC, opbld31 commented
Learn Build status updates of commit _[cc9fa84](https://github.com/msbemba/microsoft-365-docs/commits/cc9fa8482a6718c91eb128d21dcfedc8a6b4839c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/technical-reference-details-about-encryption.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1327/microsoft-365/compliance/technical-reference-details-about-encryption.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091421157334-10207/BuildReport?accessString=6cd21edf20ef7c180278473f12f60362e398566d475f3daa0df5f5ff57841a0b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 16:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/technical-reference-details-about-encryption.md
> +Office 365 stopped supporting TLS 1.0 and 1.1 on October 31, 2018. We have completed disabling TLS 1.0 and 1.1 in GCC High, Worldwide and DoD environments. For Microsoft 365 operated by 21 Vianet, TL
```suggestion
Office 365 stopped supporting TLS 1.0 and 1.1 on October 31, 2018. We have completed disabling TLS 1.0 and 1.1 in GCC High, Worldwide, and DoD environments. For Microsoft 365 operated by 21 Vianet, TLS 1.0 and 1.1 will be disabled on June 30, 2023. 
```

2022-11-09 16:09 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 16:43 UTC, opbld31 commented
Learn Build status updates of commit _[634358a](https://github.com/msbemba/microsoft-365-docs/commits/634358a3e4e0297d5fdaf4ec2b10c3ef7bcf63a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/technical-reference-details-about-encryption.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1327/microsoft-365/compliance/technical-reference-details-about-encryption.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091641504346-10207/BuildReport?accessString=7c5d9bcc43b82815170be5eaedca9e032a9a6ce48097117f7ceae4c116789789).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 06:12 UTC, yogkumgit commented
@JohanFreelancer9

2022-11-10 06:12 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-11-10 11:38 UTC, JohanFreelancer9 approved these changes

2022-12-08 20:47 UTC, opbld32 commented
Learn Build status updates of commit _[686f13b](https://github.com/msbemba/microsoft-365-docs/commits/686f13bd5cec4cad38c5cf8f9edb6886be25a822)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/technical-reference-details-about-encryption.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1327/microsoft-365/compliance/technical-reference-details-about-encryption.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082045396220-10207/BuildReport?accessString=b493c2263d6ea4c961171d4a168e15b319c5f64cf8a539efbbd3bfb1151a49fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-06-19 11:34 UTC, yogkumgit commented
Closing as per the comment in #10188

2023-06-19 11:34 UTC, closed without merging