Update switch-to-mde-phase-3.md
MicrosoftDocs/microsoft-365-docs pull request #10204
Opened 2022-11-09 13:55 UTC by msbemba

Added more information on status of sc query windefend and how to check passive mode 

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10179

2022-11-09 13:55 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-09 13:57 UTC, opbld30 commented
Learn Build status updates of commit _[5d78791](https://github.com/msbemba/microsoft-365-docs/commits/5d787911fec9ea435a9ee44e79737bccf1752451)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1324/microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091355374092-10204/BuildReport?accessString=61bfa091593c199cc7f15788f19eb43b7474fb327d2e07ea8cf155e786ea6eba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 15:33 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md
> +|Command Prompt|1. On a Windows device, open Command Prompt.<br/><br/>2. Type `sc query windefend`, and then press Enter.<br/><br/>3. Review the results to confirm that Microsoft Defender Antivirus i
```suggestion
|Command Prompt|1. On a Windows device, open Command Prompt.<br/><br/>2. Type `sc query windefend`, and then press Enter.<br/><br/>3. Review the results to confirm that Microsoft Defender Antivirus is running in passive mode. The state of WinDefend returns **STOPPABLE** if it is in **Passive mode** and **NOT_STOPPABLE** if it is in **Active mode**.|
```

2022-11-09 15:33 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 16:44 UTC, opbld33 commented
Learn Build status updates of commit _[4dde4a2](https://github.com/msbemba/microsoft-365-docs/commits/4dde4a26453782f8fd1658bcfada217079a682f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1324/microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091642113413-10204/BuildReport?accessString=5fcd985eb5c16b76ce5fc00f835800e77a0debd09291ed7dddb82b753f2ba05d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 06:06 UTC, yogkumgit commented
@JohanFreelancer9

2022-11-10 11:00 UTC, JohanFreelancer9 approved these changes

2022-11-14 13:03 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2022-11-15 21:01 UTC, denisebmsft approved these changes
Thank you @msbemba @JohanFreelancer9

2022-11-15 21:02 UTC, opbld31 commented
Learn Build status updates of commit _[4023ca8](https://github.com/msbemba/microsoft-365-docs/commits/4023ca8e32a2b37441fe338b5934edb9ba939533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1324/microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211152100320815-10204/BuildReport?accessString=5b531fd5f174e7d0e4206f6f9601d61cf8d09f210191a61f824d1cd0e3d063a4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 21:04 UTC, opbld31 commented
Learn Build status updates of commit _[a501abc](https://github.com/msbemba/microsoft-365-docs/commits/a501abc2ae38a3223ee4d0dca836a20e431a4313)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1324/microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211152101069493-10204/BuildReport?accessString=b75895dfe8c42e7092d21f1967ef745c08fe5363b3c61af77a8ba3e87616941f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 21:05 UTC, merged