Update enable-cloud-protection-microsoft-defender-antivirus.md
MicrosoftDocs/microsoft-365-docs pull request #10205
Opened 2022-11-09 14:08 UTC by msbemba

Made changes to the navigation as the options have changed

2022-11-09 14:08 UTC, msbemba commented
@JohanFreelancer9 please copy review

2022-11-09 14:09 UTC, msbemba commented
Ticket#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10180

2022-11-09 14:10 UTC, opbld30 commented
Learn Build status updates of commit _[dbafec9](https://github.com/msbemba/microsoft-365-docs/commits/dbafec90b8ef4393c112b3fe6b433f1eac18ea9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1325/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091408282522-10205/BuildReport?accessString=de784c13422cdcb7e16593a823a18869ddeb09fe47dbe3c36f93ddfff4cf04a8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 15:37 UTC, opbld31 commented
Learn Build status updates of commit _[fb43359](https://github.com/msbemba/microsoft-365-docs/commits/fb43359570b2205fb2ce7493bd4989c64a0e5d03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1325/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211091535151685-10205/BuildReport?accessString=e1a63ba387351ddc690af8324d614d5fb110b45e11813bf3e78f8d321e412afe).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 05:28 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md
> +2. On the **Home** pane, select **Devices**> **Configuration Profiles**.
```suggestion
2. On the **Home** pane, select **Devices** > **Configuration Profiles**.
```

2022-11-10 05:30 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md
> +4. In the **Properties** section Click on **Edit** next to **Configuration settings** and click on **Microsoft Defender Antivirus**.
```suggestion
4. In the **Properties** section, select **Edit** next to **Configuration settings** and then select **Microsoft Defender Antivirus**.
```

2022-11-10 05:31 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-10 06:08 UTC, yogkumgit commented
@msbemba

2022-11-10 19:32 UTC, opbld32 commented
Learn Build status updates of commit _[1c2950c](https://github.com/msbemba/microsoft-365-docs/commits/1c2950c43f659a5ecbd4013ada9cdb6b66729f4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1325/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211101930067790-10205/BuildReport?accessString=98b208fdd8c53b593c8bb0331d1109b4c5061e48377d8b71219976cc7fb4aabf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 19:33 UTC, opbld32 commented
Learn Build status updates of commit _[26c419b](https://github.com/msbemba/microsoft-365-docs/commits/26c419b4dafc25d3bd6ef327e47784a9aae8cd7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1325/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211101930129793-10205/BuildReport?accessString=9392e08eb4a9f526425fb74e44ba6774f22174f1ec2ad36e6b8551c630c9b25f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-11 13:09 UTC, JohanFreelancer9 approved these changes

2022-11-14 13:27 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2022-11-15 20:56 UTC, denisebmsft approved these changes
Thank you @msbemba @JohanFreelancer9

2022-11-15 20:56 UTC, opbld30 commented
Learn Build status updates of commit _[0882584](https://github.com/msbemba/microsoft-365-docs/commits/08825848ec8654ef8533018ad89797422deb3bd1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1325/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211152055000444-10205/BuildReport?accessString=5428927a8d9c6a5e3f61638e77533672e0e2f9497f1be975349ad517501a8e54).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-15 21:00 UTC, merged