Update dlp-conditions-and-exceptions.md
MicrosoftDocs/microsoft-365-docs pull request #10297
Opened 2022-11-17 12:35 UTC by ancmarti

Line 88 Recipient is member of needs to be changed to reflect what we have in the DLP policy configurator. As for the Sender is member of, M365 groups are not actually supported. What we see in the EXO DLP policy configurator is:

Looks for messages sent to members of distribution groups, dynamic distribution groups, or mail-enabled security groups.

2022-11-17 12:38 UTC, opbld30 commented
Learn Build status updates of commit _[71d053e](https://github.com/ancmarti/microsoft-365-docs/commits/71d053ee0ed7b2d627a7d474ca472bde05666827)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-conditions-and-exceptions.md](https://github.com/ancmarti/microsoft-365-docs/blob/patch-4/microsoft-365/compliance/dlp-conditions-and-exceptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211171235156540-10297/BuildReport?accessString=a2b1db7d0603db3d6dc834c14d8be4251ca49086dff93f1ac84c3d2b75c312e5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 05:56 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-conditions-and-exceptions.md
> +|Sent to member of|condition: *SentToMemberOf* <br/><br/> exception: *ExceptIfSentToMemberOf*|Addresses|Messages that contain recipients who are members of the specified distribution group, mail-enab
```suggestion
|Sent to member of|condition: *SentToMemberOf* <br/><br/> exception: *ExceptIfSentToMemberOf*|Addresses|Messages that contain recipients who are members of the specified distribution group or mail-enabled security group. The group can be in the **To**, **Cc**, or **Bcc** fields of the message.|
```

2022-11-18 05:57 UTC, JohanFreelancer9 requested changes
Copy review - @ancmarti, kindly commit the suggested change. Many thanks.

2022-11-18 06:26 UTC, opbld31 commented
Learn Build status updates of commit _[77a9a7a](https://github.com/ancmarti/microsoft-365-docs/commits/77a9a7a1b42efd10bd655d0f76318f3a78d79b5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-conditions-and-exceptions.md](https://github.com/ancmarti/microsoft-365-docs/blob/patch-4/microsoft-365/compliance/dlp-conditions-and-exceptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211180624362217-10297/BuildReport?accessString=06438749ff6767405b9949692a6543a9089406bd11c6d461416c6cb770b971a8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 06:50 UTC, JohanFreelancer9 approved these changes

2022-12-08 20:47 UTC, opbld31 commented
Learn Build status updates of commit _[8ffa035](https://github.com/ancmarti/microsoft-365-docs/commits/8ffa035d0b997d0a10a6b238f9a01e18b8b4c91a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-conditions-and-exceptions.md](https://github.com/ancmarti/microsoft-365-docs/blob/patch-4/microsoft-365/compliance/dlp-conditions-and-exceptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082045123346-10297/BuildReport?accessString=d2d9ca5c913b9c01ce00a41374498a211bb2212e21c483dd4d3cacd47bbd64c8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-04-28 00:06 UTC, chrfox commented
this article will be merged into DLP policy  reference in Q4 FY23

2023-04-28 00:06 UTC, closed without merging