Update assign-licenses-to-user-accounts-with-microsoft-365-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #10314
Opened 2022-11-18 07:31 UTC by msbemba

Added another script as the previous one does work if there are multiple subscriptions and disabled plans in those subscriptions.

fixes #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10229

2022-11-18 07:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-18 07:33 UTC, opbld33 commented
Learn Build status updates of commit _[7ab95eb](https://github.com/msbemba/microsoft-365-docs/commits/7ab95eb125531020b9205a1311ef202d9905e17a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1341/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211180731110543-10314/BuildReport?accessString=4252a3554f45f2d4198f31901c4250543b4eb4f40cfea9112c19fa0e5b60d8d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 08:52 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md
> +This example updates a user with **SPE_E5** (Microsoft 365 E5) and turns off the Sway and Forms service plans, while leaving the user's existing disabled plans in all other subscriptions in their cur
```suggestion
This example updates a user with **SPE_E5** (Microsoft 365 E5) and turns off the Sway and Forms service plans while leaving the user's existing disabled plans in all other subscriptions in their current state:
```

2022-11-18 08:53 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-18 11:30 UTC, opbld32 commented
Learn Build status updates of commit _[0ed9213](https://github.com/msbemba/microsoft-365-docs/commits/0ed921343d99c4588b2b408c37c84d00430c89ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1341/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211181128207799-10314/BuildReport?accessString=f1043513c030b6e94601b3fab9085c57954669321045085e0c1b341e333c4f8b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 16:44 UTC, yogkumgit commented
@msbemba

2022-11-19 08:24 UTC, JohanFreelancer9 approved these changes

2022-11-21 05:31 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-12-05 23:53 UTC, opbld30 commented
Learn Build status updates of commit _[02f4aad](https://github.com/msbemba/microsoft-365-docs/commits/02f4aad6e412c2ff312a124c02cd4f933bf6375c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1341/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212052351434084-10314/BuildReport?accessString=d07dcbbe22fb2538a070a969d95745d78c89580d5a5add25d95db272c4f16430).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 23:53 UTC, merged