Update m365-feature-descriptions.md
MicrosoftDocs/microsoft-365-docs pull request #10312
Opened 2022-11-18 07:02 UTC by msbemba

Added information about Technical support for partners

fixes #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10301

2022-11-18 07:02 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-18 07:04 UTC, opbld31 commented
Learn Build status updates of commit _[2cedf99](https://github.com/msbemba/microsoft-365-docs/commits/2cedf99f0203ac7c03d90519885c33e0f64eef98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/m365-feature-descriptions.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1339/microsoft-365/admin/m365-feature-descriptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211180702072451-10312/BuildReport?accessString=44afbf780830a6cd45787efc30011514e0447d844101855b0038bb02879542eb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 08:44 UTC, JohanFreelancer9 commented on microsoft-365/admin/m365-feature-descriptions.md
> +**Technical support for partners:** If you're a partner and need information about specific partner support plans, see the following table. For more information, see [compare partner support plans](h
```suggestion
**Technical support for partners:** If you're a partner and need information about specific partner support plans, see the following table. For more information, see [Compare partner support plans](https://partner.microsoft.com/support/partnersupport). Partners can also escalate tickets to Microsoft. For more information, see [Escalating to Microsoft] (/partner-center/customer-support#escalating-to-microsoft).
```

2022-11-18 08:46 UTC, JohanFreelancer9 requested changes
@msbemba, you are referencing a table, but you did not include the table. Could you please include it? Many thanks.

2022-11-18 11:31 UTC, msbemba commented
@JohanFreelancer9 I have updated it now. Please copy review

2022-11-18 11:32 UTC, opbld31 commented
Learn Build status updates of commit _[0283e54](https://github.com/msbemba/microsoft-365-docs/commits/0283e54fd0cf9787dd900b89b056c375f5d4673f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/m365-feature-descriptions.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1339/microsoft-365/admin/m365-feature-descriptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211181129357790-10312/BuildReport?accessString=fabb64abe246f02114eef185f645d06ca89416598735557e50b7281f6873ed33).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 11:34 UTC, opbld33 commented
Learn Build status updates of commit _[f5c92a3](https://github.com/msbemba/microsoft-365-docs/commits/f5c92a399d64f2f950cdfd51498c3a3401e44fd6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/m365-feature-descriptions.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1339/microsoft-365/admin/m365-feature-descriptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211181131015205-10312/BuildReport?accessString=38d5e251ffcbca50b1ef53b611f96f1931435e7bf7ed976552adc6f0d3d021c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 16:36 UTC, yogkumgit commented
@msbemba

2022-11-19 08:09 UTC, JohanFreelancer9 requested changes
@msbemba, could you please include the table provided by the issue raiser? If not, the reference to the table needs to be removed. Thanks.

2022-11-19 08:13 UTC, msbemba commented
the table is available on the link.

2022-11-19 08:26 UTC, JohanFreelancer9 commented on microsoft-365/admin/m365-feature-descriptions.md
> +**Technical support for partners:** If you're a partner and need information about specific partner support plans, see [Compare partner support plans](https://partner.microsoft.com/support/partnersup
```suggestion
**Technical support for partners:** If you're a partner and need information about specific partner support plans, see [Compare partner support plans](https://partner.microsoft.com/support/partnersupport). Partners can also escalate tickets to Microsoft. For more information, see [Escalating to Microsoft](/partner-center/customer-support#escalating-to-microsoft).
```

2022-11-19 08:27 UTC, JohanFreelancer9 requested changes
@msbemba, thank you. Just one more, please.

2022-11-19 17:00 UTC, opbld30 commented
Learn Build status updates of commit _[6b91221](https://github.com/msbemba/microsoft-365-docs/commits/6b91221c802b00f201969608876b9387523a46b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/m365-feature-descriptions.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1339/microsoft-365/admin/m365-feature-descriptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211191658378426-10312/BuildReport?accessString=787f74d164d69eabd145563796ff013d4f926e221943af02479e9651645734cf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 04:03 UTC, JohanFreelancer9 approved these changes

2022-11-21 05:30 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks

2022-12-12 16:28 UTC, opbld30 commented
Learn Build status updates of commit _[f4a2ab2](https://github.com/msbemba/microsoft-365-docs/commits/f4a2ab2c7a10ccc8a53d410a545bbb787c9add65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/m365-feature-descriptions.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1339/microsoft-365/admin/m365-feature-descriptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212121626062637-10312/BuildReport?accessString=17028c5330dfab46e89b305c1cce27fddfabb20e5b6946f1e4cd3b29d12c546a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-12 17:33 UTC, opbld30 commented
Learn Build status updates of commit _[3026ecf](https://github.com/msbemba/microsoft-365-docs/commits/3026ecf4c32f577061074b3ef522db0902d258d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/m365-feature-descriptions.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1339/microsoft-365/admin/m365-feature-descriptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212121732032717-10312/BuildReport?accessString=c8cd9459276afc1ed43f91fc78621c1773f85dbd1fbcadbd50be5aa84a8a2cc0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-12 17:34 UTC, merged