Update dlp-configure-endpoint-settings.md
MicrosoftDocs/microsoft-365-docs pull request #10332
Opened 2022-11-21 17:55 UTC by edwinchan-microsoft

added required KBs for authorized groups and removed the preview sign up link due to these features moving to full public preview

2022-11-21 17:55 UTC, edwinchan-microsoft commented
@chrfox please approve PR

2022-11-21 17:58 UTC, opbld33 commented
Learn Build status updates of commit _[d41c35d](https://github.com/edwinchan-microsoft/microsoft-365-docs/commits/d41c35d1953caf52608bfad4cf53df74fa1628fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-configure-endpoint-settings.md](https://github.com/edwinchan-microsoft/microsoft-365-docs/blob/patch-12/microsoft-365/compliance/dlp-configure-endpoint-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211211755035666-10332/BuildReport?accessString=c875f61d3ed23cfd3d5677f8a1ddb86500cdad527674c6ea1555ea29a3e8b82f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-21 19:11 UTC, opbld31 commented
Learn Build status updates of commit _[9980a05](https://github.com/edwinchan-microsoft/microsoft-365-docs/commits/9980a05589c25da83b429b226251fd28ecbc7ccc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-configure-endpoint-settings.md](https://github.com/edwinchan-microsoft/microsoft-365-docs/blob/patch-12/microsoft-365/compliance/dlp-configure-endpoint-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211211909065478-10332/BuildReport?accessString=fc9ea6d1ef1e2bc1c92ab7fad9343a024fc6b99208a4c9e7229b17bd7077501c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-22 07:57 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-configure-endpoint-settings.md
```suggestion
```

2022-11-22 07:58 UTC, JohanFreelancer9 requested changes
Copy review - @edwinchan-microsoft, kindly commit the suggested change to remove the extra blank line. Many thanks.

2022-11-22 19:34 UTC, opbld33 commented
Learn Build status updates of commit _[303a3bc](https://github.com/edwinchan-microsoft/microsoft-365-docs/commits/303a3bcec2e4e606d49a1708f58557cc3cb00571)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-configure-endpoint-settings.md](https://github.com/edwinchan-microsoft/microsoft-365-docs/blob/patch-12/microsoft-365/compliance/dlp-configure-endpoint-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211221932430720-10332/BuildReport?accessString=b716a22573fd8edad6ea96e07ec02b2897ceeea14202fcb7f7412f89ef6159ae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 07:37 UTC, JohanFreelancer9 approved these changes

2022-11-29 12:19 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-12-16 09:11 UTC, cesarapascual approved these changes

2022-12-16 09:13 UTC, cesarapascual approved these changes

2023-01-13 00:11 UTC, chrfox commented
back to Edwin chan Contributor license agreement incomplete

2023-01-13 00:14 UTC, edwinchan-microsoft commented
> 
@microsoft-github-policy-service agree [company="Microsoft"]

2023-01-13 00:14 UTC, edwinchan-microsoft commented
> ```
> @microsoft-github-policy-service agree
> ```

@microsoft-github-policy-service agree

2023-01-31 17:59 UTC, merged