Update attack-simulation-training.md
MicrosoftDocs/microsoft-365-docs pull request #10341
Opened 2022-11-22 12:23 UTC by msbemba

Added a note stating that Dynamic Distribution groups cannot be used to target users.

fixes #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10328

2022-11-22 12:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-22 12:25 UTC, opbld32 commented
Learn Build status updates of commit _[2da67c3](https://github.com/msbemba/microsoft-365-docs/commits/2da67c38b1237b11e7b72914d9a1b34c85044226)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1344/microsoft-365/security/office-365-security/attack-simulation-training.md) | :bulb:Suggestion | | [Details](#user-content-bba208a122ab77ec2e3bd5e3a94af925-3902d119)

<a id="bba208a122ab77ec2e3bd5e3a94af925-3902d119"></a>
### [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1344/microsoft-365/security/office-365-security/attack-simulation-training.md)
 - **Line 197, Column 1**: **[Suggestion: code-block-indented - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211221223219086-10341/BuildReport?accessString=4947efd396ae50b772124bcfe428dacdca0a715d5ead2924822fd0b248e1075a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-22 13:32 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/attack-simulation-training.md
> +> Dynamic Distribution Groups cannot be used to target users.
```suggestion
> Dynamic distribution groups cannot be used to target users.
```

2022-11-22 13:32 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-22 16:29 UTC, opbld31 commented
Learn Build status updates of commit _[7588453](https://github.com/msbemba/microsoft-365-docs/commits/7588453fb4ff8ddaa6a70f0dea8f0b6314e815d1)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1344/microsoft-365/security/office-365-security/attack-simulation-training.md) | :bulb:Suggestion | | [Details](#user-content-bba208a122ab77ec2e3bd5e3a94af925-ae80d9cb)

<a id="bba208a122ab77ec2e3bd5e3a94af925-ae80d9cb"></a>
### [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1344/microsoft-365/security/office-365-security/attack-simulation-training.md)
 - **Line 197, Column 1**: **[Suggestion: code-block-indented - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211221626010710-10341/BuildReport?accessString=f774436d92a913df9c9c48c3fcfc3cc0e60e661c549929cd679c220285ae1b55).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 03:27 UTC, JohanFreelancer9 approved these changes

2022-11-24 19:56 UTC, opbld32 commented
Learn Build status updates of commit _[f5a699e](https://github.com/msbemba/microsoft-365-docs/commits/f5a699e78a006c3b750e1aef337aeabd6b210b53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1344/microsoft-365/security/office-365-security/attack-simulation-training.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211241954128382-10341/BuildReport?accessString=a3e021809d3efe31bb8c45750b85d5c455127e74d53adbc2bf89c13700fe7d1b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 19:58 UTC, opbld32 commented
Learn Build status updates of commit _[f77757e](https://github.com/msbemba/microsoft-365-docs/commits/f77757ed0218f25bcc632e34b6e21b9f651f1e47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1344/microsoft-365/security/office-365-security/attack-simulation-training.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211241955548982-10341/BuildReport?accessString=f0d074c179e1d76d37d09fa258e832f29e4e766da18e91215a0045ea671eda1c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-24 20:00 UTC, merged