Update deploy-manage-removable-storage-intune.md
MicrosoftDocs/microsoft-365-docs pull request #10350
Opened 2022-11-22 17:37 UTC by msbemba

Made changes to the navigation

fixes #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10321

2022-11-22 17:37 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-22 17:39 UTC, opbld32 commented
Learn Build status updates of commit _[f74d9d8](https://github.com/msbemba/microsoft-365-docs/commits/f74d9d85a6f94c1426d00d38e32a60a437b29e8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1347/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211221737317696-10350/BuildReport?accessString=d16f7a8692750db0ff055cf3c61384e998e85b06a90ae3060858d57d473ff9c9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 06:37 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md
> +Go to Microsoft Endpoint Manager admin center (<https://endpoint.microsoft.com/>) > **Devices** > **Configuration profiles** > **Create profile** > **Platform: Windows 10 and later, Profile type: Tem
```suggestion
Go to Microsoft Endpoint Manager admin center (<https://endpoint.microsoft.com/>) > **Devices** > **Configuration profiles** > **Create profile** > **Platform: Windows 10 and later, Profile type: Templates** > **Custom** > **Create**.
```

2022-11-23 06:38 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md
> +   - Under **Custom** > Enter the **Name**, **Description** and click on **Next**
```suggestion
   - Under **Custom**, enter the **Name** and **Description** and select **Next**.
```

2022-11-23 06:39 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-23 06:46 UTC, opbld33 commented
Learn Build status updates of commit _[55b0a57](https://github.com/msbemba/microsoft-365-docs/commits/55b0a57da880bfc0c64d4eb56001996090af97f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1347/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211230644132987-10350/BuildReport?accessString=da39cb34a11d5d8d0190fdc051099dc43c912f01546cc421a7035b76cbe78316).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 06:48 UTC, opbld31 commented
Learn Build status updates of commit _[88a1a74](https://github.com/msbemba/microsoft-365-docs/commits/88a1a749a35af61db475ed836534b946a5a5798a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1347/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211230644188585-10350/BuildReport?accessString=e2c885dce080815e68095c8166132375476d58b35fc5f1969b40fe93144c1540).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 08:07 UTC, JohanFreelancer9 approved these changes

2022-11-23 10:55 UTC, yogkumgit commented
@Dansimp Pleas merge this PR. Thanks

2022-12-08 20:50 UTC, opbld30 commented
Learn Build status updates of commit _[deedda2](https://github.com/msbemba/microsoft-365-docs/commits/deedda28b93c5281b39c2af77433012910ba457f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1347/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082048593554-10350/BuildReport?accessString=5a0c4d239b751c608451ec94864bfc69af89e07ce0cac34b8cb068e5c9c2e5ae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-19 11:44 UTC, yogkumgit commented
@beccarobins Please merge this PR or review and Sign off. Thanks

2022-12-19 15:37 UTC, opbld30 commented
Learn Build status updates of commit _[cf3e72a](https://github.com/msbemba/microsoft-365-docs/commits/cf3e72a87110b9185ed00dc999375d66e6b9ad71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1347/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212191535353286-10350/BuildReport?accessString=8b517c826d46aa6428bc6be11015f0a6c787ad088ea555eda3d79864ccb78918).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 17:58 UTC, opbld33 commented
Learn Build status updates of commit _[cb53676](https://github.com/msbemba/microsoft-365-docs/commits/cb5367640103429b1460a85a32171bd68795d596)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1347/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212201754434006-10350/BuildReport?accessString=b88847dfd097e811a206eabb552b778480dc13d3b6a9d7799c7f183c5d005292).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 18:24 UTC, merged