Update configure-exclusions-microsoft-defender-antivirus.md
MicrosoftDocs/microsoft-365-docs pull request #10351
Opened 2022-11-22 17:57 UTC by msbemba

Added more reference to the list-of-automatic-exclusions important note in the document

fixes #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10316

2022-11-22 17:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-22 18:01 UTC, opbld32 commented
Learn Build status updates of commit _[e0cc8ac](https://github.com/msbemba/microsoft-365-docs/commits/e0cc8ac8a4655cbf8e2b702d6cf201468243a4d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1348/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211221757139809-10351/BuildReport?accessString=bf7939bafcc9908a188fb9a6afce26a14dbfabc95ab16da8f0f5493dd7d557ac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 06:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md
> +> Microsoft Defender Antivirus includes many automatic exclusions based on known operating system behaviors and typical management files, such as those used in enterprise management, database managem
```suggestion
> Microsoft Defender Antivirus includes many automatic exclusions based on known operating system behaviors and typical management files, such as those used in enterprise management, database management, and other enterprise scenarios and situations. For more information, refer to the [list of automatic exclusions](/configure-exclusions-microsoft-defender-antivirus#the-list-of-automatic-exclusions).
```

2022-11-23 06:45 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-23 06:51 UTC, opbld31 commented
Learn Build status updates of commit _[c7bc0da](https://github.com/msbemba/microsoft-365-docs/commits/c7bc0dad48a60f7f9566366d96c2e4be27768ce9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1348/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211230648128346-10351/BuildReport?accessString=4d94e8792cef9fe9fdd213afed8d1afe673edcde04dedda3629027c5ba68e200).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-23 07:45 UTC, JohanFreelancer9 approved these changes

2022-11-23 10:57 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2022-11-28 16:54 UTC, opbld32 commented
Learn Build status updates of commit _[bacdfa6](https://github.com/msbemba/microsoft-365-docs/commits/bacdfa6cabdd12d0b81dc58129c06e6b4c86a524)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1348/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211281652481729-10351/BuildReport?accessString=d57dcee596b3f7e7ce39a8cd55dd0d7900df7187cf47c377d8e3df95eb338e8f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 16:56 UTC, opbld32 commented
Learn Build status updates of commit _[2b99f28](https://github.com/msbemba/microsoft-365-docs/commits/2b99f2848bd3ea47ec528c6dd75c29fa5d6e46fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1348/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211281653064152-10351/BuildReport?accessString=68333e5bd7d446320dd75f78dd63c21dc7c40ca02720d00828ae99210ed34a1d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 16:58 UTC, denisebmsft approved these changes
Thank you @msbemba @JohanFreelancer9

2022-11-28 17:00 UTC, opbld33 commented
Learn Build status updates of commit _[702c88d](https://github.com/msbemba/microsoft-365-docs/commits/702c88dea85ca0bad83ce92700f279cb92d1edd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1348/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211281658187129-10351/BuildReport?accessString=1266b59a4bb428f4909cb27614b63126c384b60141c95d1cadb632d4302ec4c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 17:00 UTC, merged