Update insider-risk-management-cases.md
MicrosoftDocs/microsoft-365-docs pull request #10408
Opened 2022-11-29 13:08 UTC by msbemba

added more information about Investigators having the ability to Turn off pseudonymize

fixes #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10359

2022-11-29 13:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-11-29 13:12 UTC, opbld33 commented
Learn Build status updates of commit _[539300f](https://github.com/msbemba/microsoft-365-docs/commits/539300f29fd2deb7441a7e36bce0a973dae71d36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management-cases.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1357/microsoft-365/compliance/insider-risk-management-cases.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211291308180814-10408/BuildReport?accessString=0708490d6d51f3c50f79e749b70744827435785b460b3e1bca1afc5892bc0be4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 06:35 UTC, JohanFreelancer9 commented on microsoft-365/compliance/insider-risk-management-cases.md
> +Built with privacy by design, users are pseudonymized by default. However, IRM investigators can manage pseudonymize by turning it off for the case, if the option  is enabled at the tenant level.
```suggestion
Built with privacy by design, users are pseudonymized by default. However, IRM investigators can manage pseudonymize by turning it off for a case, if the option is enabled at the tenant level.
```

2022-11-30 06:37 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-30 12:13 UTC, opbld33 commented
Learn Build status updates of commit _[125eb9c](https://github.com/msbemba/microsoft-365-docs/commits/125eb9cfe8f01f3926228a9691ff74ef711c7faa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management-cases.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1357/microsoft-365/compliance/insider-risk-management-cases.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211301211591608-10408/BuildReport?accessString=ee49783ba737b4ae1b1a764092546b7d706b0385a3f4b0941ecf74db1c7e2a51).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 12:48 UTC, yogkumgit commented
@JohanFreelancer9

2022-11-30 12:48 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2022-12-01 09:25 UTC, JohanFreelancer9 approved these changes

2022-12-08 20:51 UTC, opbld30 commented
Learn Build status updates of commit _[3a00606](https://github.com/msbemba/microsoft-365-docs/commits/3a00606a14e95513f2dbe053d74be8b57ae81b01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management-cases.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1357/microsoft-365/compliance/insider-risk-management-cases.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082049555063-10408/BuildReport?accessString=38cf41163c85881984b3f336696f863b75eeb0f3fa869de03ca65ff31897fa5d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 18:14 UTC, robmazz commented
@msbemba - thanks, I'll discuss this addition with the PG and Marketing teams about if we want to highlight this here.

2022-12-20 18:14 UTC, closed without merging