Update manage-creation-of-groups.md
MicrosoftDocs/microsoft-365-docs pull request #10418
Opened 2022-11-30 06:43 UTC by anirudhyadavMS

2022-11-30 06:45 UTC, opbld30 commented
Learn Build status updates of commit _[0fbfb8a](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/0fbfb8a8d2d74a80d3246eb18959a79f84ab0b8b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/patch-3/microsoft-365/solutions/manage-creation-of-groups.md) | :warning:Warning | | [Details](#user-content-1a1c81118b4407503de0ec06130e1489-94d9286c)

<a id="1a1c81118b4407503de0ec06130e1489-94d9286c"></a>
### [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/patch-3/microsoft-365/solutions/manage-creation-of-groups.md)
 - **Line 56, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ge Administrator cannot create from Exchange Admin center unless the user is present as part of the whitelisted users allowed to create group, PFA for more details. [Manage who can create Microsoft 365 Groups](h'`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211300643133047-10418/BuildReport?accessString=8a781292c47c74e2cdda60405f648dd37a011cb641355988bd0fe523b30dfa49).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 11:50 UTC, MikePlumleyMSFT commented
@anirudhyadavMS please note the error above. We can't use the term 'whitelist.' Also, please update the link you're adding. The current link goes to an Advanced Threat Protection security checking system. We need a direct link to the destination article.

2022-12-01 05:19 UTC, JohanFreelancer9 commented on microsoft-365/solutions/manage-creation-of-groups.md
> +> The Exchange Administrator cannot create from Exchange Admin center unless the user is present as part of the whitelisted users allowed to create group, PFA for more details. [Manage who can create
```suggestion
> The Exchange administrator cannot create Microsoft 365 Groups from Exchange admin center unless the user is part of the whitelisted users allowed to create groups. For more details, see [Manage who can create Microsoft 365 Groups](/microsoft-365/solutions/manage-creation-of-groups).
```

2022-12-01 05:20 UTC, JohanFreelancer9 commented on microsoft-365/solutions/manage-creation-of-groups.md
> +> The Exchange Administrator cannot create from Exchange Admin center unless the user is present as part of the whitelisted users allowed to create group, PFA for more details. [Manage who can create
```suggestion
> The Exchange administrator cannot create Microsoft 365 Groups from Exchange admin center unless the user is part of the whitelisted users allowed to create groups. For more details, see [Manage who can create Microsoft 365 Groups](/microsoft-365/solutions/manage-creation-of-groups).
```

2022-12-01 05:22 UTC, JohanFreelancer9 requested changes
Copy review - @anirudhyadavMS, kindly commit the suggested changes. Many thanks.

2022-12-08 20:51 UTC, opbld30 commented
Learn Build status updates of commit _[8dd2649](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/8dd264987a7753b22a0f66300def8bd2a7077723)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/patch-3/microsoft-365/solutions/manage-creation-of-groups.md) | :warning:Warning | | [Details](#user-content-1a1c81118b4407503de0ec06130e1489-95a39387)

<a id="1a1c81118b4407503de0ec06130e1489-95a39387"></a>
### [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/patch-3/microsoft-365/solutions/manage-creation-of-groups.md)
 - **Line 56, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ge Administrator cannot create from Exchange Admin center unless the user is present as part of the whitelisted users allowed to create group, PFA for more details. [Manage who can create Microsoft 365 Groups](h'`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082049589933-10418/BuildReport?accessString=bfe49b96fb6e4f98c3132b3f87a7a291b4bb09fbecc6edabda96879792041aec).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-19 11:47 UTC, yogkumgit commented
@anirudhyadavMS Gentle reminder. Thanks

2022-12-23 07:31 UTC, opbld31 commented
Learn Build status updates of commit _[75b12f5](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/75b12f5a56cc7a13a42e6640e18dfcd8086f6165)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/patch-3/microsoft-365/solutions/manage-creation-of-groups.md) | :warning:Warning | | [Details](#user-content-1a1c81118b4407503de0ec06130e1489-26702d84)

<a id="1a1c81118b4407503de0ec06130e1489-26702d84"></a>
### [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/patch-3/microsoft-365/solutions/manage-creation-of-groups.md)
 - **Line 56, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ge Administrator cannot create from Exchange Admin center unless the user is present as part of the whitelisted users allowed to create group, PFA for more details. [Manage who can create Microsoft 365 Groups](h'`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212230729220768-10418/BuildReport?accessString=6b738da534104d01b05148f7760f3e6f8999a4f49242c025e2f51858835c7709).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-23 07:35 UTC, opbld30 commented
Learn Build status updates of commit _[d245dd5](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/d245dd57a0b767fe342acf520d7d8cb4bb45132b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/patch-3/microsoft-365/solutions/manage-creation-of-groups.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212230733186169-10418/BuildReport?accessString=29117bbc6c8aebfb7da156727bc8d152cce6bc78c25fada52af0bd2dc3567ac1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-23 07:36 UTC, anirudhyadavMS commented
@MikePlumleyMSFT I have made the required changes

2022-12-23 13:55 UTC, JohanFreelancer9 approved these changes

2023-01-02 14:36 UTC, yogkumgit commented
@MikePlumleyMSFT

2023-01-03 11:57 UTC, MikePlumleyMSFT commented
@anirudhyadavMS can you clarify what the requirement is? I can't tell from the note and the link is linking back to this same article.

2023-01-16 13:38 UTC, yogkumgit commented
@anirudhyadavMS Gentle reminder

2025-10-23 16:40 UTC, v-jmathew commented
This PR has been open for an extended period of time and has conflicts. If these changes are still relevant, please re-submit them to https://github.com/MicrosoftDocs/microsoft-365-docs-pr/.

2025-10-23 16:40 UTC, closed without merging