Update configure-server-endpoints.md
MicrosoftDocs/microsoft-365-docs pull request #10429
Opened 2022-12-01 17:58 UTC by baardhermansen

Removed an extra line shift that broke a Note notation. 
Removed language specifics in URLs.
Added an escape character so `\\` is displayed as intended. 
Other very minor cleanups of markdown.

2022-12-01 18:00 UTC, opbld32 commented
Learn Build status updates of commit _[b5c6b80](https://github.com/baardhermansen/microsoft-365-docs/commits/b5c6b80db519297d947d697f05deed6eaa811894)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/baardhermansen/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/configure-server-endpoints.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212011758433015-10429/BuildReport?accessString=c56a4701b7fccf95109f6ba878d24cb1d99931cd33c4650ac9557b8587eab478).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 06:29 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-server-endpoints.md
> +- We've identified an issue with Windows Server 2012 R2 connectivity to cloud when static TelemetryProxyServer is used **and** the certificate revocation list (CRL) URLs aren't reachable from the SYS
```suggestion
- We've identified an issue with Windows Server 2012 R2 connectivity to cloud when static TelemetryProxyServer is used **and** the certificate revocation list (CRL) URLs aren't reachable from the SYSTEM account context. Ensure the EDR sensor is updated to version 10.8210.* or later (using [KB5005292](https://support.microsoft.com/topic/microsoft-defender-for-endpoint-update-for-edr-sensor-f8f69773-f17f-420f-91f4-a8e5167284ac)) to resolve the issue. Alternatively, use a different proxy option ("system-wide") that provides such connectivity, or configure the same proxy via the WinInet setting on the SYSTEM account context.
```

2022-12-02 06:30 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-server-endpoints.md
>  - Operating system upgrades aren't supported. Offboard then uninstall before upgrading. The installer package can only be used to upgrade installations that have not yet been updated with new antimal
```suggestion
- Operating system upgrades aren't supported. Offboard or uninstall them before upgrading. The installer package can only be used to upgrade installations that have not yet been updated with new antimalware platform or EDR sensor update packages.
```

2022-12-02 06:31 UTC, JohanFreelancer9 requested changes
Copy review - @baardhermansen, kindly commit the two additional suggested changes. Many thanks.

2022-12-02 14:36 UTC, opbld32 commented
Learn Build status updates of commit _[dc43f3d](https://github.com/baardhermansen/microsoft-365-docs/commits/dc43f3d740d36ddb92a15ec22cb3bb3d5186c29b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/baardhermansen/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/configure-server-endpoints.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212021434210186-10429/BuildReport?accessString=81629f9456a0449563590a6aabf1b3865c55164150bed91deb9514aa59571c4f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 14:40 UTC, baardhermansen commented on microsoft-365/security/defender-endpoint/configure-server-endpoints.md
>  - Operating system upgrades aren't supported. Offboard then uninstall before upgrading. The installer package can only be used to upgrade installations that have not yet been updated with new antimal
@JohanFreelancer9 One must both offboard (from the service) and uninstall (the client), so the suggested change will not suffice. 
At least as far as i'm aware? Might have to have that verified with someone?

2022-12-05 02:15 UTC, JohanFreelancer9 approved these changes
@baardhermansen, thank you for the clarification. I have deleted my suggestion.

2022-12-05 09:56 UTC, opbld32 commented
Learn Build status updates of commit _[08ee14b](https://github.com/baardhermansen/microsoft-365-docs/commits/08ee14be9ff2f6975599567adf1ab9f310b30b33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/baardhermansen/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/configure-server-endpoints.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212050954419345-10429/BuildReport?accessString=a93a54c566a631a9962a6c4f96d9c4b393d4d64e11bccdaaaf608f63994a93d7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 20:51 UTC, opbld31 commented
Learn Build status updates of commit _[6cd7b0b](https://github.com/baardhermansen/microsoft-365-docs/commits/6cd7b0b18f550e3a388155fa3270d3f2fd764711)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/baardhermansen/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/configure-server-endpoints.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082050044922-10429/BuildReport?accessString=71fd64e6677aef9fb9da96075db2930b5cfcbca8949c6fde835d1598a9fd0a58).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-09 12:05 UTC, opbld30 commented
Learn Build status updates of commit _[976c664](https://github.com/baardhermansen/microsoft-365-docs/commits/976c66412bfdd7ca47c3b50b130a7547c4569b59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/baardhermansen/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/configure-server-endpoints.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212091203594141-10429/BuildReport?accessString=fb8be5bb50c8ef9ad765bfe620c1a7fccace80a972c0d84e77eedfa756579f75).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-14 22:49 UTC, opbld33 commented
Learn Build status updates of commit _[8c82c93](https://github.com/baardhermansen/microsoft-365-docs/commits/8c82c9324601cab5f91b6178ba0494b28525a64c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/baardhermansen/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/configure-server-endpoints.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212142247189851-10429/BuildReport?accessString=dbb26b0a0dcd28ccc14913844e0858cbcbde59a62041333a8aeea75d62d183c1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-14 22:49 UTC, merged