Minor Grammer Fixes
MicrosoftDocs/microsoft-365-docs pull request #10447
Opened 2022-12-02 21:30 UTC by bracherp

2022-12-02 21:32 UTC, opbld31 commented
Learn Build status updates of commit _[a29e2c8](https://github.com/bracherp/microsoft-365-docs/commits/a29e2c8d70415f1ccd7b0502c0a1e279ad41e7f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md](https://github.com/bracherp/microsoft-365-docs/blob/patch-6/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212022130594013-10447/BuildReport?accessString=911b2d8116e7db1118fd39beaa09961fb217003dfec360b8240ace9a7184202d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 05:06 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md
> +Suppressing notifications prevents notifications from Microsoft Defender Antivirus from showing up in the Action Center on Windows 10 when scans are done, or remediation actions are taken. However, y
The comma is not needed here. Please revert.

2022-12-05 05:08 UTC, JohanFreelancer9 requested changes
Copy review, @bracherp, please revert one change as indicated. Many thanks.

2022-12-05 19:13 UTC, opbld30 commented
Learn Build status updates of commit _[60d7b90](https://github.com/bracherp/microsoft-365-docs/commits/60d7b90a008f2e4e3fc4c683f521a522bef3115c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md](https://github.com/bracherp/microsoft-365-docs/blob/patch-6/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212051911165298-10447/BuildReport?accessString=1ab5adf138c30d4ae71a921e9a0aab71ac9ce1b71d3051845e826b85763765be).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 19:13 UTC, denisebmsft approved these changes
Thank you @bracherp

2022-12-05 19:15 UTC, opbld31 commented
Learn Build status updates of commit _[9bbaf3c](https://github.com/bracherp/microsoft-365-docs/commits/9bbaf3c828ca6d3d7552263890cb1679741936a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md](https://github.com/bracherp/microsoft-365-docs/blob/patch-6/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212051913096616-10447/BuildReport?accessString=18e5d9fb7f9f45ce5c2c7c9caccfc893ef83cf24674a3f05c84ace489989cb64).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 19:17 UTC, opbld30 commented
Learn Build status updates of commit _[7beea55](https://github.com/bracherp/microsoft-365-docs/commits/7beea55538a414bf61f86cf006e977dc1d022858)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md](https://github.com/bracherp/microsoft-365-docs/blob/patch-6/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212051913511889-10447/BuildReport?accessString=c95a29028769fe7597a20b537233f9a9d0c8b144648561a1790aa4c02368f56d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-05 19:43 UTC, merged