Update increase-the-recoverable-quota-for-mailboxes-on-hold.md
MicrosoftDocs/microsoft-365-docs pull request #10473
Opened 2022-12-07 10:40 UTC by msbemba

Updated the URL for the deleted item retention period.

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10431

2022-12-07 10:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-12-07 10:41 UTC, opbld32 commented
Learn Build status updates of commit _[da6451f](https://github.com/msbemba/microsoft-365-docs/commits/da6451f1e7131ebcade466ec1618c29aa1ec9b0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1366/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212071040145475-10473/BuildReport?accessString=02da2858eb150a336beda8160715d05a263eac0b3ce94938a3219726ac7260ab).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 03:59 UTC, JohanFreelancer9 commented on microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md
> +    > We recommend that the retention period (defined by the  _AgeLimitForRetention_ parameter) for the Recoverable Items RPT is the same as the deleted item retention period for the mailboxes that t
```suggestion
    > We recommend that the retention period (defined by the _AgeLimitForRetention_ parameter) for the Recoverable Items RPT is the same as the deleted item retention period for the mailboxes that the RPT will be applied to. This allows a user the entire deleted item retention period to recover deleted items before they are moved to the archive mailbox. In the previous example, the retention period was set to 30 days based on the assumption that the deleted item retention period for mailboxes is also 30 days. An Exchange Online mailbox is configured to retain deleted items for 14 days, by default. But you can change this setting to a maximum of 30 days. For more information, see [Change the deleted item retention period for a mailbox in Exchange Online](/exchange/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention).
```

2022-12-08 03:59 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-08 07:39 UTC, opbld30 commented
Learn Build status updates of commit _[7d31170](https://github.com/msbemba/microsoft-365-docs/commits/7d311704e10789abb1871338ed5ce873a520da76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1366/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212080737221378-10473/BuildReport?accessString=ad0adf792102853a5c7a7912f3a682f994480ee626718be534e9c8780e8116cf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 09:47 UTC, JohanFreelancer9 approved these changes

2022-12-08 14:59 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2022-12-08 20:52 UTC, opbld33 commented
Learn Build status updates of commit _[a225bdb](https://github.com/msbemba/microsoft-365-docs/commits/a225bdb1d70ad4b24f2e1befc605cb60be228e85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1366/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082050241338-10473/BuildReport?accessString=b5ffdeabc20c3677be7428f9676498504bd329c03121bea830063790dc6f0e3d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 18:18 UTC, robmazz commented
@msbemba - thanks, updated in separate PR.

2022-12-20 18:18 UTC, closed without merging