Update enable-cloud-protection-microsoft-defender-antivirus.md
MicrosoftDocs/microsoft-365-docs pull request #10530
Opened 2022-12-18 17:05 UTC by msbemba

Removed the method to use intune to turn on cloud protection.

Fixes# https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10500

2022-12-18 17:06 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-12-18 17:07 UTC, opbld32 commented
Learn Build status updates of commit _[11ba6d9](https://github.com/msbemba/microsoft-365-docs/commits/11ba6d97023e9b639fc3a6f9ce02b88d47454d12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1374/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212181705466450-10530/BuildReport?accessString=bc30efbe83ac9727ef1e431b2bff42575c2fda0e81f9216c821cf3a99b1264fd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-19 05:48 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md
```suggestion
```

2022-12-19 05:49 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-19 09:00 UTC, opbld31 commented
Learn Build status updates of commit _[0413f07](https://github.com/msbemba/microsoft-365-docs/commits/0413f07f2c3f79ede0fab30627b1f28e9abaf015)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1374/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212190856542787-10530/BuildReport?accessString=f655f985657254850db38d3235933c5dd768ac7e0bf5dbdc62e6a3748c403507).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-19 10:05 UTC, JohanFreelancer9 approved these changes

2022-12-20 10:52 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2022-12-20 22:46 UTC, denisebmsft approved these changes
Thank you @msbemba

2022-12-20 22:47 UTC, opbld30 commented
Learn Build status updates of commit _[a8fc31a](https://github.com/msbemba/microsoft-365-docs/commits/a8fc31a017ef9cff5fa095b8648d1bd36b26a655)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1374/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212202245406954-10530/BuildReport?accessString=2c93222bc5a6becba7a754863674f9413de85f4f19932629b94f508f0b272de1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 22:49 UTC, opbld30 commented
Learn Build status updates of commit _[5434c28](https://github.com/msbemba/microsoft-365-docs/commits/5434c2848138ada33e058ea61c5f140e28fdb032)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1374/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212202246002435-10530/BuildReport?accessString=c579ea5a345cba70648f284e6547b2a5c6174158771b51d2677f947ea0fdb260).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 22:50 UTC, merged