Update search-for-content.md
MicrosoftDocs/microsoft-365-docs pull request #10558
Opened 2022-12-22 12:28 UTC by msbemba

Updated the page to remove references to SFB

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10549

2022-12-22 12:28 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-12-22 12:30 UTC, opbld30 commented
Learn Build status updates of commit _[98a28e2](https://github.com/msbemba/microsoft-365-docs/commits/98a28e23ce700867b2271507c24dcc1ff45ef9b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/search-for-content.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1382/microsoft-365/compliance/search-for-content.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212221228237804-10558/BuildReport?accessString=a0d29c73747172ab31a3454cdd7baad98bbd09a42c875c7e4113c1ff4747bd86).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 15:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-for-content.md
> +Use the Content search tool in the Microsoft Purview compliance portal to quickly find email in Exchange mailboxes, documents in SharePoint sites and OneDrive locations. You can use the content searc
```suggestion
Use the Content search tool in the Microsoft Purview compliance portal to quickly find email in Exchange mailboxes and documents in SharePoint sites and OneDrive locations. You can use the content search tool to search for email, documents, and instant messaging conversations in collaboration tools such as Microsoft Teams and Microsoft 365 Groups.
```

2022-12-22 15:28 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-23 12:07 UTC, yogkumgit commented
@msbemba

2022-12-23 12:08 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2023-01-03 18:14 UTC, cabailey commented
Retention policies continue to support this retired service for existing customers - see https://learn.microsoft.com/microsoft-365/compliance/retention-settings#configuration-information-for-skype-for-business  

Retaining without the ability to search doesn't seem to make much sense?  Deleting the reference when it was previously published would infer it's no longer supported & not sure if that was checked before creating this PR.

2023-01-04 14:19 UTC, yogkumgit commented
@msbemba

2023-01-04 15:16 UTC, msbemba commented
@cabailey Thank you for the confirmation. I will let the customer know.

Thanks
Sri

2023-01-04 15:16 UTC, closed without merging