Adding note that extension is not supported/needed on MacOS
MicrosoftDocs/microsoft-365-docs pull request #10553
Opened 2022-12-21 16:01 UTC by JeffMichelmore

This change request is prompted by a premier support case raised in which a Microsoft premier customer was using this extension on all of their macOS devices and it was causing anomalous behavior. Microsoft developer confirmed this extension is not needed on MacOS.

2022-12-21 16:03 UTC, opbld32 commented
Learn Build status updates of commit _[3754bfe](https://github.com/JeffMichelmore/microsoft-365-docs/commits/3754bfec90810ce3d07a41de86c12bef6540b199)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-chrome-get-started.md](https://github.com/JeffMichelmore/microsoft-365-docs/blob/patch-4/microsoft-365/compliance/dlp-chrome-get-started.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212211601375631-10553/BuildReport?accessString=a543b22b6677f63e6adac63018953b8f61d672a5d44ff2dd47e2dd38b44c0402).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 03:47 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-chrome-get-started.md
> +> The Microsoft Purview Extension is only applicable to Windows devices. The extension is not necessary for enforcement of data loss prevention on MacOS devices.
```suggestion
> Microsoft Purview Extension is only applicable to Windows devices. The extension is not necessary for the enforcement of data loss prevention on macOS devices.
```

2022-12-22 03:48 UTC, JohanFreelancer9 requested changes
Copy review - @JeffMichelmore, kindly commit the suggested changes. Many thanks.

2022-12-22 17:10 UTC, opbld31 commented
Learn Build status updates of commit _[aa074ba](https://github.com/JeffMichelmore/microsoft-365-docs/commits/aa074bae04084ed564847d5bd90c230506a2fdbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-chrome-get-started.md](https://github.com/JeffMichelmore/microsoft-365-docs/blob/patch-4/microsoft-365/compliance/dlp-chrome-get-started.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212221708211715-10553/BuildReport?accessString=067481d2452de6b6012a82481ca338fce82923057ba4b90dfef1446752650e75).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-23 05:17 UTC, JohanFreelancer9 approved these changes

2023-01-12 23:58 UTC, chrfox commented
checking with PG to see if this is correct

2023-01-13 00:23 UTC, merged