Update submissions-report-messages-files-to-microsoft.md
MicrosoftDocs/microsoft-365-docs pull request #10568
Opened 2022-12-26 12:51 UTC by madalenamedo

Minor change because a new tab was added in the Defender Portal page inside Submissions

2022-12-26 12:53 UTC, opbld32 commented
Learn Build status updates of commit _[cbf4781](https://github.com/madalenamedo/microsoft-365-docs/commits/cbf4781bd16240560f86b7373cd4cce359b4d737)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-4/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212261251295858-10568/BuildReport?accessString=e5898522a630ee15bb0e5bddacda113d8197e43abb361f4d88ccc82db55fa6e6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-27 05:59 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md
> +|[The Submissions page in the Microsoft 365 Defender portal](submissions-admin.md)|Admin|Admins use this method to report good (false positives) and bad (false negative) **Email**, **Email attachment
```suggestion
|[The Submissions page in the Microsoft 365 Defender portal](submissions-admin.md)|Admin|Admins use this method to report good (false positives) and bad (false negative) **Email**, **Email attachments**, **URLs**, and **Files**, including user reported messages, to Microsoft for further analysis. Available in organizations with Exchange Online mailboxes (not available in standalone EOP).|
```

2022-12-27 05:59 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md
> +|[The Submissions page in the Microsoft 365 Defender portal](submissions-admin.md)|Admin|Admins use this method to report good (false positives) and bad (false negative) **Email**, **Email attachment
```suggestion
|[The Submissions page in the Microsoft 365 Defender portal](submissions-admin.md)|Admin|Admins use this method to report good (false positives) and bad (false negative) **Email**, **Email attachments**, **URLs**, and **Files**, including user reported messages, to Microsoft for further analysis. Available in organizations with Exchange Online mailboxes (not available in standalone EOP).|
```

2022-12-27 05:59 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md
> +|[The Submissions page in the Microsoft 365 Defender portal](submissions-admin.md)|Admin|Admins use this method to report good (false positives) and bad (false negative) **Email**, **Email attachment
```suggestion
|[The Submissions page in the Microsoft 365 Defender portal](submissions-admin.md)|Admin|Admins use this method to report good (false positives) and bad (false negative) **Email**, **Email attachments**, **URLs**, and **Files**, including user reported messages, to Microsoft for further analysis. Available in organizations with Exchange Online mailboxes (not available in standalone EOP).|
```

2022-12-27 06:02 UTC, JohanFreelancer9 requested changes
Copy review - @madalenamedo, kindly commit the minor suggested change. Many thanks.

2022-12-27 08:45 UTC, madalenamedo commented
@JohanFreelancer9 done! Thank you!

2022-12-27 08:46 UTC, opbld31 commented
Learn Build status updates of commit _[74a9115](https://github.com/madalenamedo/microsoft-365-docs/commits/74a91155e12abef63afc60343f01e52d158d89dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-4/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212270844512381-10568/BuildReport?accessString=439129a0191278f691d467f8ce3954ef953e669c0a2c760689d1898ab033ad41).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-27 14:58 UTC, JohanFreelancer9 approved these changes

2022-12-27 21:36 UTC, opbld30 commented
Learn Build status updates of commit _[1e9d1c5](https://github.com/madalenamedo/microsoft-365-docs/commits/1e9d1c57661a3be4e67df9543ced64d7ca8570f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-4/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212272134396586-10568/BuildReport?accessString=37a779f60a1980266c995bcc26de4bc5eb02501e4de3558142ff1deaf811c44f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-27 21:38 UTC, opbld33 commented
Learn Build status updates of commit _[5e29985](https://github.com/madalenamedo/microsoft-365-docs/commits/5e29985f06dd523274bffdc50dba9fe3f90e70c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-4/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212272134583726-10568/BuildReport?accessString=302397e8912d027ad628910c226beb610e2feaafc3d0e261f3457d846642d4c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-27 21:41 UTC, denisebmsft approved these changes
Thank you @madalenamedo @JohanFreelancer9

2022-12-27 21:41 UTC, merged