Update upgrade-distribution-lists.md
MicrosoftDocs/microsoft-365-docs pull request #10562
Opened 2022-12-23 08:10 UTC by anirudhyadavMS

@MikePlumleyMSFT  this reflects the deprecation plan for the feature

2022-12-23 08:11 UTC, opbld31 commented
Learn Build status updates of commit _[730050e](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/730050e16fe5e317a3f169c2b4edbdca922c74f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212230810103808-10562/BuildReport?accessString=237f60aed9606dd7c76805eea0956ef319c76daf0ce32bb9315171422b6f847e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-26 09:59 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/upgrade-distribution-lists.md
> +**_NOTE:_**  This functionality is going to be deprecated by 1st Feb, 2023.
```suggestion
> [!NOTE]
> This functionality will be deprecated by February 1, 2023.
```

2022-12-26 10:00 UTC, JohanFreelancer9 requested changes
Copy review - @anirudhyadavMS, kindly commit the suggested changes. Many thanks.

2023-01-02 08:43 UTC, opbld30 commented
Learn Build status updates of commit _[81e17f0](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/81e17f025762d02cf9ff33c51a30b56719d411e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301020841469238-10562/BuildReport?accessString=c756253f9f13d3a50b71e2a2642b6f34cc94d236592e589118eba3fca3f2e82a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-02 16:19 UTC, JohanFreelancer9 approved these changes

2023-01-03 06:26 UTC, anirudhyadavMS commented
@MikePlumleyMSFT Please merge this.

2023-01-03 11:50 UTC, MikePlumleyMSFT commented
@kwekuako

2023-01-09 06:52 UTC, opbld30 commented
Learn Build status updates of commit _[d1a3404](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/d1a340495eb0a8a50c286d8da6b5fb69abbbebe2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301090650148400-10562/BuildReport?accessString=734a5492a921676c20bbf3e4def41e0a395e0dba5568505593406185a551e3f5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-09 06:54 UTC, opbld32 commented
Learn Build status updates of commit _[1bd2e6d](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/1bd2e6d9cfc0eccaba74cd5f1dca9884de7093d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301090652010394-10562/BuildReport?accessString=0309dd3347517f02eebfc207822618d35ad3a60c9a099751bdc2ba64ed5f5f56).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-09 09:18 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/upgrade-distribution-lists.md
> +> [!Important]
```suggestion
> [!IMPORTANT]
```

2023-01-09 09:26 UTC, JohanFreelancer9 requested changes
@anirudhyadavMS, kindly commit the suggested change. Many thanks.

2023-01-09 09:36 UTC, opbld32 commented
Learn Build status updates of commit _[0dfbe4b](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/0dfbe4bef359d36a0e1684550030fc50aec34478)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301090934555513-10562/BuildReport?accessString=233be4e790f5ac6385b0dcfe39612534288c285b83eb29d888ddbf1ba30bb613).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-09 09:54 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/upgrade-distribution-lists.md
> +> This functionality will be deprecated by February 1, 2023. For more information, see [Deprecating Conversion of Distribution Lists to Microsoft 365 Groups - Microsoft Community Hub](https://techcom
```suggestion
> This functionality will be deprecated by February 1, 2023. For more information, see [Deprecating Conversion of Distribution Lists to Microsoft 365 Groups - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecating-conversion-of-distribution-lists-to-microsoft-365/ba-p/3668215).
```

2023-01-09 09:55 UTC, JohanFreelancer9 requested changes
Apologies @anirudhyadavMS, one more, please.

2023-01-09 10:09 UTC, JohanFreelancer9 approved these changes

2023-01-09 10:11 UTC, opbld33 commented
Learn Build status updates of commit _[752003a](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/752003a859d5be4c400da70aca8b5141831d2aaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301091008057506-10562/BuildReport?accessString=02f7c59303fb364376f533385ce2c45e902284538afb7166abe1be90804f6f1d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-09 16:10 UTC, opbld32 commented
Learn Build status updates of commit _[86e4814](https://github.com/anirudhyadavMS/microsoft-365-docs/commits/86e481465fd2f471542e5ca74fc0727b8bdd1dbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/anirudhyadavMS/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301091608471448-10562/BuildReport?accessString=b41d80f766bc0ca491050ec5ad16aacc9f5691dbab23a5e27ef81ad1618cd34b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-09 16:11 UTC, merged