Update submissions-admin.md
MicrosoftDocs/microsoft-365-docs pull request #10567
Opened 2022-12-26 12:50 UTC by madalenamedo

The images are missing please contact me and I can provide them alias madalenamedo.
Thank you!

2022-12-26 12:52 UTC, opbld30 commented
Learn Build status updates of commit _[3416393](https://github.com/madalenamedo/microsoft-365-docs/commits/341639300d30fe661a9f8b6a838c9129a929f79f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/submissions-admin.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212261250293974-10567/BuildReport?accessString=a59e014db10d3b5f41e7a24f7b9809527669b6cd9b60666e856b349a5369430a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-26 17:08 UTC, madalenamedo commented
@microsoft-github-policy-service agree [company="Microsoft"]

2022-12-26 17:08 UTC, madalenamedo commented
@microsoft-github-policy-service agree company="Microsoft"

2022-12-27 05:38 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submissions-admin.md
> +   - **Choose the priority**: Select **Low - bulk file or file hash submission** or **Medium - standard submission** or **High - need immediate attention (3 allowed per org per day)**. If you're not
```suggestion
   - **Choose the priority**: Select **Low - bulk file or file hash submission** or **Medium - standard submission** or **High - need immediate attention (3 allowed per org per day)**. If you're not sure, use your best judgment. This option is only available if you choose the option **Files** in **Select the submission type**.
```

2022-12-27 05:39 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submissions-admin.md
> +   - **Choose the priority**: Select **Low - bulk file or file hash submission** or **Medium - standard submission** or **High - need immediate attention (3 allowed per org per day)**. If you're not
```suggestion
   - **Choose the priority**: Select **Low - bulk file or file hash submission** or **Medium - standard submission** or **High - need immediate attention (3 allowed per org per day)**. If you're not sure, use your best judgment. This option is only available if you choose the option **Files** in **Select the submission type**.
```

2022-12-27 05:41 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submissions-admin.md
> +     - **Researchedr comment**
```suggestion
     - **Researcher comment**
```

2022-12-27 05:41 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submissions-admin.md
> +     - **Researchedr comment**
```suggestion
     - **Researcher comment**
```

2022-12-27 05:45 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submissions-admin.md
> +     - **Priority**: The values **Low**, **Medium** or **High**.
```suggestion
     - **Priority**: The values **Low**, **Medium**, or **High**.
```

2022-12-27 05:50 UTC, JohanFreelancer9 requested changes
Copy review - @madalenamedo, kindly commit the suggested changes. Many thanks.

2022-12-27 08:44 UTC, madalenamedo commented
@JohanFreelancer9 done, thank you!

2022-12-27 08:44 UTC, opbld33 commented
Learn Build status updates of commit _[ac276ec](https://github.com/madalenamedo/microsoft-365-docs/commits/ac276ec165b3d9e70e9ee5b35009b2a52b3c499e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/submissions-admin.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212270842568635-10567/BuildReport?accessString=ab848e158c8bf2388ff0e677d30e4a20477532335674b9b510aaf7afeb8832ff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-27 08:46 UTC, opbld32 commented
Learn Build status updates of commit _[6e1e869](https://github.com/madalenamedo/microsoft-365-docs/commits/6e1e86935816b3ce8eb18f7a131d0a0223527bd3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/submissions-admin.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212270843042925-10567/BuildReport?accessString=c796d2a815c160886cb4b8bbd76b34a1445b029123a659968b60451af82d8c6e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-27 15:10 UTC, JohanFreelancer9 approved these changes

2022-12-27 21:39 UTC, opbld32 commented
Learn Build status updates of commit _[728eb5b](https://github.com/madalenamedo/microsoft-365-docs/commits/728eb5b88eec1f6a9756d84404be9dc0d36320e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/submissions-admin.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212272137383765-10567/BuildReport?accessString=ef7f8864cb7831aac77c44dc2f1c2d68f5f18cf3b4f261d530685c914bb82404).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-28 12:34 UTC, opbld31 commented
Learn Build status updates of commit _[41cdf35](https://github.com/madalenamedo/microsoft-365-docs/commits/41cdf35ceb1fff6d476be21da0df84c49bbdedc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/submissions-admin.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212281232580905-10567/BuildReport?accessString=49ad77970221374e0d9cfc6b5c269ead77bbf9349a6187875d7d8b5be8e869b2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-28 15:54 UTC, denisebmsft commented
Images requested. Will review and merge once they're in.

2022-12-28 22:22 UTC, opbld33 commented
Learn Build status updates of commit _[a1660d6](https://github.com/madalenamedo/microsoft-365-docs/commits/a1660d696df3f43be571dd1123af68561b0903d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/madalenamedo/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/submissions-admin.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212282220413891-10567/BuildReport?accessString=eb445bf7b3a834173b18e83f45de405a5d8fbfb79e340a0f7c0570f1a5b307b9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-28 22:28 UTC, merged