Update endpoint-dlp-learn-about.md
MicrosoftDocs/microsoft-365-docs pull request #10638
Opened 2023-01-10 05:54 UTC by arunt14

@chrfox , updated with the changes proposed. Please review

2023-01-10 05:56 UTC, opbld33 commented
Learn Build status updates of commit _[bc1cb11](https://github.com/arunt14/microsoft-365-docs/commits/bc1cb1165a4c2ed3fb542492bb95e8646888911e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/arunt14/microsoft-365-docs/blob/patch-3/microsoft-365/compliance/endpoint-dlp-learn-about.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301100554353766-10638/BuildReport?accessString=78975b3067407d7e9b88de86b68cc7605b672c4d139d6f5ba112d54e3c7dcb2f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-10 07:39 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-learn-about.md
> +
```suggestion

The list is a list of file types that are supported:

- doc, docx, xls, xlsx, ppt, pptx, pdf: Supports after the extension is changed to any file extension.
- txt, pst, msg, rtf, c, cpp, h, cs, java, tsv: Supports if the extension is changed to only supported file extensions.
```

2023-01-10 07:40 UTC, JohanFreelancer9 requested changes
Copy review - @arunt14, kindly commit the suggested changes. Many thanks.

2023-01-10 07:56 UTC, opbld30 commented
Learn Build status updates of commit _[7e3514d](https://github.com/arunt14/microsoft-365-docs/commits/7e3514df258689cd19e5e5d187432b825c054a29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/arunt14/microsoft-365-docs/blob/patch-3/microsoft-365/compliance/endpoint-dlp-learn-about.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301100754515350-10638/BuildReport?accessString=ac6dad181a24368ba8d6b76a2aa30eeb05b79b17f8384545d7af13eee14af10a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-10 12:54 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-learn-about.md
> +The list is a list of file types that are supported:
```suggestion
This is a list of file types that are supported:
```

2023-01-10 12:55 UTC, JohanFreelancer9 requested changes
Apologies @arunt14, one more, please.

2023-01-10 13:07 UTC, opbld30 commented
Learn Build status updates of commit _[b9133f7](https://github.com/arunt14/microsoft-365-docs/commits/b9133f77770052c307bf6338dd624106279e8b64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/arunt14/microsoft-365-docs/blob/patch-3/microsoft-365/compliance/endpoint-dlp-learn-about.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301101305339207-10638/BuildReport?accessString=aa935d7ebfbaeb8068b47d15baa449c3e83d8b63a3db6d86bf3292f4a9ed9e86).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-10 13:08 UTC, JohanFreelancer9 approved these changes

2023-01-12 23:52 UTC, chrfox commented
back to arunt14 for completion of contributor license

2023-01-12 23:57 UTC, chrfox commented
checking with PG to see if this is correct. also Contributor license agreement not signed

2023-01-16 13:44 UTC, arunt14 commented
@microsoft-github-policy-service agree [company="{Microsoft}"]

2023-01-16 13:45 UTC, arunt14 commented
@microsoft-github-policy-service agree

2023-01-16 13:46 UTC, arunt14 commented
@microsoft-github-policy-service agree company="Microsoft"

2023-01-19 11:20 UTC, arunt14 commented
@chrfox , can you pls let me know when the changes will be published

2023-01-19 20:43 UTC, merged