Clarify naming in Step 11
MicrosoftDocs/microsoft-365-docs pull request #10646
Opened 2023-01-10 19:00 UTC by rgsteele

The instructions use language like

> In **General** Enter the following details:
>
>    - Display name: MDATP Onboarding Contoso 200329 v100.86.92 or later

without explaining that `200329` and `v100.86.92 or later` are examples. I propose adding a note to clarify that the names should be updated to conform with your organization's naming conventions.

2023-01-10 19:02 UTC, opbld31 commented
Learn Build status updates of commit _[338a7ac](https://github.com/rgsteele/microsoft-365-docs/commits/338a7acd6fca6e34dc160e8b2357c509c65d8c41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md](https://github.com/rgsteele/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301101900140340-10646/BuildReport?accessString=8bf277f2649f7ddf3e0a8baa7eee263b9ed21e601599ffa1c014332ada0a7f27).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-11 08:34 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md
> +> In the steps below, the name of the `.pkg` file and the **Display Name** values are examples. In these examples, `200329` represents the date on which the
```suggestion
> In the steps that follow, the name of the `.pkg` file and the **Display Name** values are examples. In these examples, `200329` represents the date on which the
```

2023-01-11 08:35 UTC, JohanFreelancer9 requested changes
Copy review - @rgsteele, kindly commit the minor suggested change. Many thanks.

2023-01-11 15:38 UTC, JohanFreelancer9 approved these changes

2023-01-16 13:41 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks.

2023-01-23 18:07 UTC, merged