Update dlp-conditions-and-exceptions.md
MicrosoftDocs/microsoft-365-docs pull request #10641
Opened 2023-01-10 13:52 UTC by aamalhot

add AccessScope parameter

2023-01-10 13:52 UTC, aamalhot commented
@chrfox to review

2023-01-10 13:54 UTC, opbld31 commented
Learn Build status updates of commit _[3f3bfb1](https://github.com/aamalhot/microsoft-365-docs/commits/3f3bfb1b1c351242a8f6a439ee40e3b72909bd9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-conditions-and-exceptions.md](https://github.com/aamalhot/microsoft-365-docs/blob/patch-26/microsoft-365/compliance/dlp-conditions-and-exceptions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301101352046249-10641/BuildReport?accessString=90d308ef5d4a54336ce0c5d0f92d4e7818d42c0e66dd37133e94bbb74c6b3c4b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-11 08:17 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-conditions-and-exceptions.md
> +
```suggestion
```

2023-01-11 08:18 UTC, JohanFreelancer9 requested changes
Copy review - @aamalhot, kindly commit the suggested change to remove the additional blank line. Many thanks.

2023-01-11 09:18 UTC, ybhargav1995 commented
Approved

2023-01-12 23:13 UTC, merged