Update virtual-appointments.md
MicrosoftDocs/microsoft-365-docs pull request #10676
Opened 2023-01-12 12:43 UTC by msbemba

Made changes to the licensing requirement

fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10655

2023-01-12 12:44 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-01-12 14:44 UTC, JohanFreelancer9 commented on microsoft-365/frontline/virtual-appointments.md
> +With Microsoft 365: A3, A5, E3, E5, F1, F3, Business Basic, Business Standard, Business Premium licenses, you can use basic Virtual Appointments capabilities that make it easy to schedule and join bu
```suggestion
With Microsoft 365 A3, A5, E3, E5, F1, F3, Business Basic, Business Standard, and Business Premium licenses, you can use basic Virtual Appointments capabilities that make it easy to schedule and join business-to-customer meetings. For example, you can schedule appointments in the Bookings calendar and external attendees can [join through a browser](browser-join.md) without having to download Teams. [Teams Premium](/microsoftteams/teams-add-on-licensing/licensing-enhance-teams) (Preview) unlocks advanced Virtual Appointments capabilities that your organization can use to manage and personalize the experience. These include a queue view of scheduled and on-demand appointments, SMS text notifications, custom waiting rooms, and analytics.
```

2023-01-12 14:45 UTC, JohanFreelancer9 requested changes
Copy review.

2023-01-12 16:40 UTC, yogkumgit commented
@msbemba

2023-01-16 05:33 UTC, JohanFreelancer9 approved these changes

2023-01-16 13:06 UTC, yogkumgit commented
@LanaChin Please merge this PR. Thanks

2023-01-23 16:57 UTC, samanro commented
Updating in separate PR: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/18576

2023-01-23 16:57 UTC, closed without merging