Add warning for upcoming changes to Private CDN deprecation
MicrosoftDocs/microsoft-365-docs pull request #10673
Opened 2023-01-12 06:51 UTC by pchandoria

…tion

Private CDN configuration is going to be deprecated in near future. It is available without any configuration for all image file types. This is a forewarning until communication is sent to the customer. Afterward all references to private CDN will be removed from this document.

2023-01-12 07:12 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md
> +> Private CDN configuration is in the process of deprecation. You are no longer required to configure Private CDN. Image file types are served through Private CDN out of the box. However if private C
```suggestion
> Private CDN configuration is in the process of deprecation. You are no longer required to configure a private CDN. Image file types are served through a private CDN out of the box. However, if a private CDN is in use for other file types, like JS or CSS, we recommend using a public CDN for better performance. Going forward, non-image file types will not be supported through private CDNs.
```

2023-01-12 07:13 UTC, JohanFreelancer9 requested changes
Copy review - @pchandoria, kindly commit the suggested changes. Many thanks.

2023-01-16 13:42 UTC, yogkumgit commented
@JohanFreelancer9

2023-01-17 09:39 UTC, JohanFreelancer9 approved these changes

2023-01-17 22:58 UTC, opbld30 commented
Learn Build status updates of commit _[cec331b](https://github.com/pchandoria/microsoft-365-docs/commits/cec331bef8a64bd8d8cb4b6629e406f800f8dde3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md](https://github.com/pchandoria/microsoft-365-docs/blob/patch-2/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301172255150922-10673/BuildReport?accessString=6ed590ab95cbcf1f916628d2818b467017cae488a0d676b69720089e42c58113).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-18 00:02 UTC, opbld30 commented
Learn Build status updates of commit _[d4f2580](https://github.com/pchandoria/microsoft-365-docs/commits/d4f258088da038cd03c30ad5b9fe3ce61bc0b842)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md](https://github.com/pchandoria/microsoft-365-docs/blob/patch-2/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301172357255474-10673/BuildReport?accessString=312a54cc084a408b7c697dd92f62557e040d125cf72b92214a5d5eb38d0fb45c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-18 16:58 UTC, merged