Update compliance-easy-trials.md
MicrosoftDocs/microsoft-365-docs pull request #10693
Opened 2023-01-13 17:25 UTC by kyracatwork

Howdy! I'm a PM from the DLM & RM team. Please contact me at alias kyrachurney with any questions. 

Changes here are:
- Updating the first line of text for Records Management to be more descriptive & better match the flow of other solution wording.
- Updating the DLM section to include a first line of text and 2x bullet points to highlight features, to show more value to customers and better match the format/flow of the other solution wording.
- The terms & condition update is pushing it lower due to added content above.

2023-01-14 06:15 UTC, JohanFreelancer9 commented on microsoft-365/compliance/compliance-easy-trials.md
> +   - Adaptive policy scopes – govern data dynamically across your org by deploying retention policies and labels to groups of users, SharePoint sites, and Microsoft 365 Groups (including Microsoft Te
```suggestion
   - Adaptive policy scopes – govern data dynamically across your organization by deploying retention policies and labels to groups of users, SharePoint sites, and Microsoft 365 Groups (including Microsoft Teams) using scopes that target policies to locations against attributes and properties that you define.
```

2023-01-14 06:15 UTC, JohanFreelancer9 commented on microsoft-365/compliance/compliance-easy-trials.md
> +  For more information on the full range of features for Microsoft Purview Records Management, learn more about [Records Management](records-management.md)
```suggestion
  For more information on the full range of features for Microsoft Purview Records Management, learn more about [Records Management](records-management.md).
```

2023-01-14 06:16 UTC, JohanFreelancer9 requested changes
Copy review - @kyracatwork, kindly commit the minor suggested changes. Many thanks.

2023-01-19 14:59 UTC, yogkumgit commented
@kyracatwork Gentle reminder. Thanks

2023-01-20 19:49 UTC, LauraWi commented
@chvukosw Can you take a look and merge if acceptable?

2023-01-20 20:14 UTC, merged