Update dlp-policy-reference.md
MicrosoftDocs/microsoft-365-docs pull request #10707
Opened 2023-01-16 06:48 UTC by Pulkit-Sachan

2023-01-19 15:22 UTC, yogkumgit commented
@JohanFreelancer9

2023-01-20 06:43 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-policy-reference.md
> +- Document created by member of - Currently deprecated for customers not already using this predicate.
```suggestion
- Document created by member of (currently deprecated for customers not already using this predicate) 
```

2023-01-20 06:43 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-policy-reference.md
> +- Document name matches patterns - Currently deprecated for customers not already using this predicate.
```suggestion
- Document name matches patterns (currently deprecated for customers not already using this predicate) 
```

2023-01-20 06:43 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-policy-reference.md
> +- Document created by member of - Currently deprecated for customers not already using this predicate.
```suggestion
- Document created by member of (currently deprecated for customers not already using this predicate) 
```

2023-01-20 06:43 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-policy-reference.md
> +- Document name matches patterns - Currently deprecated for customers not already using this predicate.
```suggestion
- Document name matches patterns (currently deprecated for customers not already using this predicate) 
```

2023-01-20 06:45 UTC, JohanFreelancer9 requested changes
Copy review - @Pulkit-Sachan, kindly commit the suggested changes. Many thanks.

2023-01-21 09:23 UTC, JohanFreelancer9 approved these changes

2023-02-20 12:27 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2023-04-21 23:43 UTC, merged