Update viva-learning-activity.md
MicrosoftDocs/microsoft-365-docs pull request #10759
Opened 2023-01-20 11:31 UTC by msbemba

Added the type of user activities that are available in the report

fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10661

2023-01-20 11:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-01-21 08:46 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/viva-learning-activity.md
> +
```suggestion
- User activities – Shows you the number of user activities, such as viewed featured content, learning tabs pinned, viewed learning objects, consumed learning objects, recommendations made, and bookmarks.
```

2023-01-21 08:46 UTC, JohanFreelancer9 requested changes
Copy review.

2023-01-23 04:57 UTC, JohanFreelancer9 approved these changes

2023-02-20 12:28 UTC, yogkumgit commented
@camillepack Please merge this PR. Thanks

2023-02-22 22:01 UTC, merged