Update revoke-ome-encrypted-mail.md
MicrosoftDocs/microsoft-365-docs pull request #10788
Opened 2023-01-24 18:48 UTC by samschan-ms

Updated AAD roles that can access reovoke mail function. @KCCross to review

2023-01-26 07:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/revoke-ome-encrypted-mail.md
> +1. Using a work or school account that has global administrator, compliance administrator, Exchange administrator permissions, or other Exchange role groups with Information Right Management in your
```suggestion
1. Using a work or school account that has global administrator, compliance administrator, or Exchange administrator permissions, or other Exchange role groups with Information Right Management in your organization, [connect to Exchange Online PowerShell](/powershell/exchange/connect-to-exchange-online-powershell).
```

2023-01-26 07:49 UTC, JohanFreelancer9 requested changes
Copy review - @samschan-ms, kindly commit the suggested changes. Many thanks.

2023-01-26 08:37 UTC, JohanFreelancer9 approved these changes

2023-02-20 12:29 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2023-05-11 20:36 UTC, KCCross requested changes
Will accept "or compliance administrator" "or Exchange administrator" however, we do not need to go into detail about IRM role here. That should be discussed one time (and one time only) in roles/perms content elsewhere. Since it's the IRM role that's granting the required permission for this and other procedures. Otherwise, we'd have to bring it up in every procedure. List the least-priv role/perm first, which I believe is compliance admin, then Exchange admin, then global administrator.

2023-05-11 23:32 UTC, KCCross commented
After discussion, will merge.

2023-05-11 23:35 UTC, merged