Update double-key-encryption.md
MicrosoftDocs/microsoft-365-docs pull request #10801
Opened 2023-01-26 13:29 UTC by msbemba

Updated the version of .net core as 3.1 is deprecated.

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10754

2023-01-26 13:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-01-27 04:35 UTC, JohanFreelancer9 commented on microsoft-365/compliance/double-key-encryption.md
> +**.NET Core 7.0 SDK**. Download and install the SDK from [Download .NET Core 7.0](https://dotnet.microsoft.com/en-us/download/dotnet/7.0).
```suggestion
**.NET Core 7.0 SDK**. Download and install the SDK from [Download .NET Core 7.0](https://dotnet.microsoft.com/download/dotnet/7.0).
```

2023-01-27 04:35 UTC, JohanFreelancer9 requested changes
Copy review.

2023-01-27 11:33 UTC, JohanFreelancer9 approved these changes

2023-01-27 15:34 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-02-06 15:39 UTC, merged