Updating the authentication page
MicrosoftDocs/microsoft-365-docs pull request #10819
Opened 2023-01-27 21:59 UTC by seakim-ms

Added clarity for the 2 roles for the app.
Added clarity on the link admin account section.

2023-01-28 11:28 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/servicenow-authentication.md
> +- **x_mioms_m365_assis.insights_user** - This role is required to view the **Recommended Solutions & Articles** and **Microsoft Service Health* features in your ServiceNow instance.
```suggestion
- **x_mioms_m365_assis.insights_user**—This role is required to view the **Recommended Solutions & Articles** and **Microsoft Service Health** features in your ServiceNow instance.
```

2023-01-28 11:30 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/servicenow-authentication.md
> +- **x_mioms_m365_assis.administrator** - This role is required to escalate your ServiceNow incidents to Microsoft support using your linked Microsoft 365 admin account. Continue to the below section
```suggestion
- **x_mioms_m365_assis.administrator**—This role is required to escalate your ServiceNow incidents to Microsoft support using your linked Microsoft 365 Admin account. Continue to the following section to link your admin account in the app's settings.
```

2023-01-28 11:36 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/servicenow-authentication.md
> +If any users are provisioned with the role **x_mioms_m365_assis.administrator** and is using different Microsoft 365 accounts to manage a Microsoft 365 support case, they must set up their Microsoft
```suggestion
If any users are provisioned with the role **x_mioms_m365_assis.administrator** and are using different Microsoft 365 accounts to manage a Microsoft 365 support case, they must set up their Microsoft 365 admin email account by navigating to **Microsoft 365 support** > **Link Account**.
```

2023-01-28 11:37 UTC, JohanFreelancer9 requested changes
Copy review - @seakim-ms, kindly commit the suggested changes. Many thanks.

2023-01-30 18:58 UTC, seakim-ms commented
Committing changes suggested by @JohanFreelancer9. Thank you!

2023-01-31 10:07 UTC, JohanFreelancer9 approved these changes

2023-02-07 18:31 UTC, merged