Update priority-accounts.md
MicrosoftDocs/microsoft-365-docs pull request #10868
Opened 2023-02-01 10:32 UTC by msbemba

Made changes to the navigation to add priority accounts.

fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10811

2023-02-01 10:33 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-01 13:36 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-02-02 06:44 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/priority-accounts.md
> +2. Go to **Settings** > **Email and Collaboration** > **User Tags** > **Create**. T
```suggestion
2. Go to **Settings** > **Email and Collaboration** > **User Tags** > **Create**.
```

2023-02-02 06:44 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/priority-accounts.md
> +3. The Priority Account tag is already created for you by default. By selecting **edit** you can add users to the priority tag. Then, **Add members** > **Add** to add members to the Priority account.
```suggestion
3. The priority account tag is already created for you by default. By selecting **Edit** you can add users to the priority tag. Then, **Add members** > **Add** to add members to the priority account.
```

2023-02-02 06:48 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-14 09:04 UTC, JohanFreelancer9 approved these changes

2023-02-14 16:51 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-02-20 12:34 UTC, yogkumgit commented
@kwekuako Gentle reminder.

2023-03-28 17:04 UTC, merged