Update remove-licenses-from-users.md
MicrosoftDocs/microsoft-365-docs pull request #10913
Opened 2023-02-06 15:50 UTC by msbemba

Updated the section for searching disconnected or de-licensed mailboxes.

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10875

2023-02-06 15:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-07 09:03 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/remove-licenses-from-users.md
> +- When the license is removed, the user's mailbox is no longer searchable by using an eDiscovery tool such as Content Search or eDiscovery (Premium). For more information, see "Searching disconnected
```suggestion
- When the license is removed, the user's mailbox is no longer searchable by using an eDiscovery tool such as Content Search or eDiscovery (Premium). For more information, see "Searching disconnected or de-licensed mailboxes" in [Content Search in Microsoft 365](/microsoft-365/compliance/ediscovery-content-search-reference#searching-disconnected-or-de-licensed-mailboxes).
```

2023-02-07 09:03 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-07 11:33 UTC, yogkumgit commented
@msbemba

2023-02-09 16:51 UTC, JohanFreelancer9 approved these changes

2023-02-10 12:32 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2023-02-20 12:14 UTC, yogkumgit commented
@cmcatee-MSFT Gentle reminder

2024-01-11 18:22 UTC, cmcatee-MSFT commented
"For more information" sentence was removed from the article.

2024-01-11 18:22 UTC, closed without merging