Update data-classification-activity-explorer.md
MicrosoftDocs/microsoft-365-docs pull request #10994
Opened 2023-02-13 14:53 UTC by shadansan

@chrfox and @JohanFreelancer9 I have to make another update to this before publishing. Can you please check and let me know what is the next action? Thank you!

2023-02-14 08:33 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-24 18:22 UTC, chrfox commented on microsoft-365/compliance/data-classification-activity-explorer.md
> +Note that roles other than Global Admin and/or Compliance Admin, can only view activities and are not allowed to view the sensitive content.
@JohanFreelancer9  - Please put this in Note markdown format  > [!NOTE]

2023-02-24 18:23 UTC, chrfox commented
@JohanFreelancer9   please put this in markdown > [!NOTE] format, then send back to me for publishing

2023-02-25 08:04 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-activity-explorer.md
> +Note that roles other than Global Admin and/or Compliance Admin, can only view activities and are not allowed to view the sensitive content.
```suggestion

> [NOTE]
> Roles other than Global Admin and Compliance Admin can only view activities and are not allowed to view sensitive content.
```

2023-02-25 08:07 UTC, JohanFreelancer9 requested changes
Copy review - @shadansan, Kindly commit the revised suggested changes to incorporate @chrfox's suggestion. Many thanks.

2023-02-26 17:30 UTC, shadansan commented
Committed. Please let me know if you need anything else.
Best regards
Shadan

From: JohanFreelancer9 ***@***.***>
Sent: Saturday, February 25, 2023 12:07 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Shadan Saniepour Esfahani ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-activity-explorer.md (PR #10994)


@JohanFreelancer9 requested changes on this pull request.

Copy review - @shadansan<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshadansan&data=05%7C01%7Cshadans%40microsoft.com%7C802c47dc0d6d47b434b508db170751b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638129092452122043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B%2BCMYxuSYJ%2FGnWoqaZ6DhblxiQjLBH11zJHgbrasCq8%3D&reserved=0>, Kindly commit the revised suggested changes to incorporate @chrfox<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchrfox&data=05%7C01%7Cshadans%40microsoft.com%7C802c47dc0d6d47b434b508db170751b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638129092452278731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NzT08GlQYuF%2BOwBn8pHndirgP16lIVm1ljj5XIboHWM%3D&reserved=0>'s suggestion. Many thanks.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F10994%23pullrequestreview-1314468597&data=05%7C01%7Cshadans%40microsoft.com%7C802c47dc0d6d47b434b508db170751b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638129092452278731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yb%2B3jrhAty6t3pBEWuViJSYr8npF8kvzi8pW2kABlrU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAURCWHQRE2GJFMY7JLQKKM3WZG4TRANCNFSM6AAAAAAU2LUPB4&data=05%7C01%7Cshadans%40microsoft.com%7C802c47dc0d6d47b434b508db170751b6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638129092452278731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EhysIuoaezAQGA69HQKoqUAaaa7W0dEW6umuo9CTqxM%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-02-27 05:19 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-activity-explorer.md
> +> Roles other than Global Admin and Compliance Admin can only view activities and are not allowed to view sensitive content.
```suggestion
> Roles other than Global Admin and Compliance Admin can only view activities and are not allowed to view sensitive content.

```

2023-02-27 05:20 UTC, JohanFreelancer9 requested changes
@shadansan, one more minor change, please.

2023-02-27 14:38 UTC, JohanFreelancer9 approved these changes

2023-02-27 14:40 UTC, JohanFreelancer9 commented
@chrfox, I have put the note in markdown format as requested. Could you please check? Many thanks.

2023-03-02 17:42 UTC, merged