Update deploy-and-configure-the-report-message-add-in.md
MicrosoftDocs/microsoft-365-docs pull request #10992
Opened 2023-02-13 14:07 UTC by msbemba

Made changes to the navigation

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10938

2023-02-13 14:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-13 15:06 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in.md
> +3.  Select **User reported message settings**
```suggestion
3.  Select **User reported message settings**.
```

2023-02-13 15:07 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-13 15:24 UTC, JohanFreelancer9 approved these changes

2023-02-14 16:27 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2023-02-17 17:53 UTC, merged