Update mde-device-control-device-installation.md
MicrosoftDocs/microsoft-365-docs pull request #11003
Opened 2023-02-14 15:19 UTC by msbemba

Updated the note in the correct section

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10880

2023-02-14 15:19 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-14 15:59 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md
> +> To enable the **Allow installation of devices using drivers that match these device setup classes**, **Allow installation of devices that match any of these device IDs**, and **Allow installation o
```suggestion
> To enable the **Allow installation of devices using drivers that match these device setup classes**, **Allow installation of devices that match any of these device IDs**, and **Allow installation of devices that match any of these device instance IDs** policy settings to supersede this policy setting for applicable devices, enable the **Apply layered order of evaluation for Allow and Prevent device installation policies across all device match criteria** policy setting. Also, the allow policy won’t take precedence if the **Block Removable Storage** option is selected in Device Control.
```

2023-02-14 15:59 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-14 17:02 UTC, yogkumgit commented
@JohanFreelancer9

2023-02-15 08:06 UTC, JohanFreelancer9 approved these changes

2023-02-20 12:20 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2023-04-05 18:07 UTC, v-britweston approved these changes

2023-04-05 18:18 UTC, merged