Update onboard-windows-multi-session-device.md
MicrosoftDocs/microsoft-365-docs pull request #11092
Opened 2023-02-22 09:14 UTC by msbemba

Made changes to the license requirement 

fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11069

2023-02-22 09:14 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-22 13:45 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2023-02-22 15:02 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md
> +Note on licensing: When using Windows Enterprise multi-session, depending on your requirements, you can choose to either have all users licensed through Microsoft Defender for Endpoint (per user), Wi
```suggestion
Note on licensing: When using Windows Enterprise multi-session, depending on your requirements, you can choose to either have all users licensed through Microsoft Defender for Endpoint (per user), Windows Enterprise E5, Microsoft 365 E5 Security, or Microsoft 365 E5, or have the VM licensed through Microsoft Defender for Cloud.
```

2023-02-22 15:02 UTC, JohanFreelancer9 requested changes
copy review.

2023-02-22 15:08 UTC, JohanFreelancer9 approved these changes

2023-02-23 13:53 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2023-03-30 14:04 UTC, yogkumgit commented
@tiburd it looks like not merged yet, can you please help. Thanks

2023-03-31 20:25 UTC, tiburd commented
@Dansimp 
Hi Dan,
It looks like you intended to merge this PR, but I can't tell for sure.
Thanks!

2023-04-05 18:06 UTC, v-britweston approved these changes

2023-04-05 18:11 UTC, merged