Added missing guides
MicrosoftDocs/microsoft-365-docs pull request #11101
Opened 2023-02-22 14:15 UTC by v-troywarren

Added the following guides.
Identity Governance
Secure your cloud apps with Single Sign On (SSO)
Migrate from ADFS to Azure AD

Updated
Plan Passwordless Deployment

2023-02-23 07:55 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +||[Configure multi-factor authentication (MFA) guide](https://aka.ms/MFASetupGuide)| **Configure multi-factor authentication (MFA) guide** for customers with Azure P1 or Azure P2, we provide customiz
```suggestion
||[Configure multi-factor authentication (MFA) guide](https://aka.ms/MFASetupGuide)| **Configure multi-factor authentication (MFA) guide** for customers with Azure P1 or Azure P2. We provide customizable Conditional Access templates that include the most common and least intrusive security standards. When Azure licensing isn’t available, we provide a one-click solution to enable Security Defaults, a baseline protection policy for all users, or we provide steps to enable legacy (per-user) MFA.|
```

2023-02-23 07:56 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +||[Migrate from ADFS to Azure AD](https://aka.ms/MigrateADFStoAzure)|In **Migrate from ADFS to Azure AD** we offer custom guidance for migrating from ADFS to Azure AD. You'll first answer a few quest
```suggestion
||[Migrate from ADFS to Azure AD](https://aka.ms/MigrateADFStoAzure)|In **Migrate from ADFS to Azure AD** we offer custom guidance for migrating from Active Directory Federation Services (AD FS) to Azure AD. You'll first answer a few questions about your AD FS infrastructure. Then implement either pass-through authentication (PTA) or password hash sync (PHS) to give users a streamlined experience while accessing your organization's apps.|
```

2023-02-23 07:57 UTC, JohanFreelancer9 requested changes
Copy review - @v-troywarren, kindly commit the suggested changes. Many thanks.

2023-02-23 12:38 UTC, v-troywarren commented
@JohanFreelancer9 all suggestions committed.

2023-02-23 14:15 UTC, JohanFreelancer9 approved these changes

2023-03-11 04:34 UTC, OhanNanen-MS commented
This PR doesn't seem to include recent changes and would overwrite those. Please do not merge as is.

2023-03-30 13:09 UTC, closed without merging