Update what-if-my-subscription-expires.md
MicrosoftDocs/microsoft-365-docs pull request #11145
Opened 2023-02-24 14:38 UTC by msbemba

Updated the Note to reflect NCE and Legacy expiration date

fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11124

2023-02-24 14:38 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-24 15:51 UTC, JohanFreelancer9 commented on microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md
> +> - If a legacy Cloud Solution Provider (CSP) license is suspended, there's no 30-day Expired stage, and services are disabled immediately. Data is deleted after 90 days if the tenant isn't reactivat
```suggestion
> - If a legacy Cloud Solution Provider (CSP) license is suspended, there's no 30-day Expired stage, and services are disabled immediately. Data is deleted after 90 days if the tenant isn't reactivated by adding a new license. For New Commerce (NCE) licenses sold via CSPs, the same "expired" state as described in this article applies when subscriptions are not renewed. See [Subscription Lifecycle](/partner-center/subscription-lifecycle) for more information. When NCE licenses in CSPs are suspended, their licenses move into a disabled state until 90 days after the original subscription term end date.
```

2023-02-24 15:53 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-25 08:49 UTC, JohanFreelancer9 approved these changes

2023-02-26 05:44 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2023-03-17 14:48 UTC, yogkumgit commented
@cmcatee-MSFT Gentle reminder.

2024-09-26 23:12 UTC, cmcatee-MSFT commented
Other updates to the article addressed this.

2024-09-26 23:12 UTC, closed without merging