Update microsoft-365-compliance-center-permissions.md
MicrosoftDocs/microsoft-365-docs pull request #11144
Opened 2023-02-24 14:30 UTC by msbemba

Made changes to permissions in the Microsoft purview compliance portal section and reworded it to reduce ambiguity.

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11121

2023-02-24 14:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-02-24 15:27 UTC, JohanFreelancer9 commented on microsoft-365/compliance/microsoft-365-compliance-center-permissions.md
> +To view the **Permissions** tab in the compliance portal, users need to be a global administrator or need to be assigned the *Role Management* role (this role is assigned only to the Organization Man
```suggestion
To view the **Permissions** tab in the compliance portal, users need to be a global administrator or need to be assigned the *Role Management* role (this role is assigned only to the *Organization Management* role group by default). The *Role Management* role allows users to view, create, and modify role groups.
```

2023-02-24 15:28 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-25 11:05 UTC, JohanFreelancer9 approved these changes

2023-02-26 05:41 UTC, yogkumgit commented
@robmazz Please merge this Pr. Thanks

2023-04-18 11:34 UTC, yogkumgit commented
@robmazz Gentle reminder.

2023-06-19 11:17 UTC, yogkumgit commented
Closing as per the comment in #11121

2023-06-19 11:17 UTC, closed without merging