Update set-password-expiration-policy.md
MicrosoftDocs/microsoft-365-docs pull request #11159
Opened 2023-02-27 08:38 UTC by Speed1

The box must be unchecked if you WANT users to have to change their password.

2023-02-28 08:29 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/set-password-expiration-policy.md
> +1. If you want users to have to change passwords, uncheck the box next to **Set passwords to never expire**.
```suggestion
1. If you want users to be able to change passwords, uncheck the box next to **Set passwords to never expire**.
```

2023-02-28 08:30 UTC, JohanFreelancer9 requested changes
Copy review - @Speed1, kindly commit the suggested change. Many thanks.

2023-03-01 09:44 UTC, Speed1 commented
Hi @JohanFreelancer9,

sorry for insisting but the option to "be able to change the password" doesn't depend on this flag.

What do you think about this sentence structure?
commit d21c5c0be2046dc3fd9100ede4d5e64a0392e1a9

2023-03-01 09:45 UTC, JohanFreelancer9 approved these changes

2023-03-01 09:48 UTC, JohanFreelancer9 commented
> Hi @JohanFreelancer9,
> 
> sorry for insisting but the option to "be able to change the password" doesn't depend on this flag.
> 
> What do you think about this sentence structure? commit [d21c5c0](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/d21c5c0be2046dc3fd9100ede4d5e64a0392e1a9)

Hi @Speed1, it is absolutely fine now. Thanks very much.

2023-03-28 16:30 UTC, merged