Intune install method to use Settings Catalog
MicrosoftDocs/microsoft-365-docs pull request #11182
Opened 2023-02-28 19:58 UTC by joshuahipple

Settings Catalog can be used now to manage the Chrome extensions. Chrome ADMX ingestion (and thus custom OMA-URI) is no longer needed.

2023-02-28 20:00 UTC, joshuahipple commented
@microsoft-github-policy-service agree

2023-03-01 05:12 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-chrome-get-started.md
> +     echcggldkblhodogklpincgchnpgcdco;https://clients2.google.com/service/update2/crx
```suggestion
10. Select **Administrative Templates** > **Google** > **Google Chrome** > **Extensions**.
11. Select **Configure the list of force-installed apps and extensions**.
12. Change the toggle to **Enabled**.
13. Enter the following value for the extensions and app IDs and update URL:
     `echcggldkblhodogklpincgchnpgcdco;https://clients2.google.com/service/update2/crx`.
```

2023-03-01 05:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-chrome-get-started.md
> +Settings Catalog can be used now to manage the Chrome extensions.
```suggestion
Use the settings catalog to manage the Chrome extensions by following these steps:
```

2023-03-01 05:16 UTC, JohanFreelancer9 requested changes
Copy review - @joshuahipple, kindly commit the suggested changes if you agree with them. Many thanks.

2023-03-02 04:00 UTC, JohanFreelancer9 approved these changes

2023-03-02 17:43 UTC, chrfox commented
confirming with PM

2023-03-07 01:17 UTC, merged