Update turn-pronouns-on-or-off.md
MicrosoftDocs/microsoft-365-docs pull request #11217
Opened 2023-03-03 08:58 UTC by PollyNincevic

Added info about turning the pronouns feature on or off for your organization using MS Graph (with link) - line 62

2023-03-04 08:49 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/turn-pronouns-on-or-off.md
> +To turn the pronouns feature on or off for your organization using MS Graph, see [Manage pronouns settings for an organization using the Microsoft graph API](/graph/pronouns-configure-pronouns-availa
```suggestion
To turn the pronouns feature on or off for your organization using Microsoft Graph, see [Manage pronouns settings for an organization using the Microsoft Graph API](/graph/pronouns-configure-pronouns-availability.md).
```

2023-03-04 08:50 UTC, JohanFreelancer9 requested changes
Copy review - @PollyNincevic, kindly commit the suggested changes. Many thanks.

2023-04-18 11:32 UTC, yogkumgit commented
@PollyNincevic Please implement the suggested changes. Thanks

2023-05-03 13:48 UTC, PollyNincevic reviewed
Updated per suggestions

2023-05-03 14:11 UTC, merged

2023-05-03 14:12 UTC, PollyNincevic commented
@yogkumgit can u advise if anything else is needed? Thank u for ur time.