Update bookings-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #11313
Opened 2023-03-11 15:03 UTC by msbemba

Updated the wordings for FAq queston

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11269

2023-03-11 15:03 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-03-11 15:30 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-faq.yml
> +          Yes, you can either create separate Bookings calendars for each service, or you can go to the Services tab,  and select Service details and you'll see a URL only for that specific service u
```suggestion
          Yes, you can either create separate Bookings calendars for each service, or you can go to the Services tab and select Service details. Then you'll see a URL only for that specific service under the Service booking page. You can share that URL which will be for that specific service.
```

2023-03-11 15:32 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-11 15:43 UTC, JohanFreelancer9 approved these changes

2023-03-13 11:07 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-03-28 16:26 UTC, merged