Update remove-former-employee.md
MicrosoftDocs/microsoft-365-docs pull request #11344
Opened 2023-03-15 15:37 UTC by msbemba

Updated Step 7 

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11271#event-8730419297

2023-03-15 15:37 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-03-15 16:29 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee.md
> +|[Step 7 - Delete a former employee's user account](remove-former-employee-step-7.md)|This removes the account from your admin center. Keeps things clean. This is when the emails to the employee will
```suggestion
|[Step 7 - Delete a former employee's user account](remove-former-employee-step-7.md)|This removes the account from your admin center. Keeps things clean. Emails to the former employee's user account will _not_ be received.|
```

2023-03-15 16:30 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-16 05:19 UTC, JohanFreelancer9 approved these changes

2023-03-16 14:24 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-03-29 13:51 UTC, yogkumgit commented
@msbemba Kwekua requested to  remove the underscore in the last sentence and resubmit it, and he’ll merge?

2023-03-29 14:25 UTC, msbemba commented
@yogkumgit I dont see an underscore in the last sentence.

@JohanFreelancer9 Could you please check if there is an underscore?

2023-03-29 20:11 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee.md
> +|[Step 7 - Delete a former employee's user account](remove-former-employee-step-7.md)|This removes the account from your admin center. Keeps things clean. Emails to the former employee's user account
```suggestion
|[Step 7 - Delete a former employee's user account](remove-former-employee-step-7.md)|This removes the account from your admin center. Keeps things clean. Emails to the former employee's user account will not be received.|
```

2023-03-29 20:13 UTC, JohanFreelancer9 commented
> @yogkumgit I dont see an underscore in the last sentence.
> 
> @JohanFreelancer9 Could you please check if there is an underscore?

@msbemba, done. Please commit again.

2023-03-30 14:00 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-04-07 06:21 UTC, merged