The hardware requirements for MDE are confusing
MicrosoftDocs/microsoft-365-docs pull request #11346
Opened 2023-03-15 15:42 UTC by AntoineJo

Hi the hardware requirements shown here are the one for Windows OS and MDE on Windows does not have dedicated hardware requirements, but share the one of the OS as it's a component of the OS.

2023-03-16 08:47 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/minimum-requirements.md
> +The hardware requirements for Defender for Endpoint on devices are the same as the one of the Windows Operating System it self (meaning they are not in addition of requirements of the Operating Syste
```suggestion
The hardware requirements for Defender for Endpoint on devices are the same as the requirements for the Windows operating system itself (that is, they are not in addition to the requirements for the operating system) for supported editions.
```

2023-03-16 08:48 UTC, JohanFreelancer9 requested changes
Copy review - @AntoineJo, kindly commit the suggested changes. Many thanks.

2023-03-27 15:18 UTC, AntoineJo commented
@mjcaparas are you expecting something from me here?. I think I've commited your changes

2023-03-27 23:27 UTC, JohanFreelancer9 approved these changes

2023-03-28 20:15 UTC, merged