Update ios-configure-features.md
MicrosoftDocs/microsoft-365-docs pull request #11343
Opened 2023-03-15 14:15 UTC by msbemba

Made changes to the Note

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11338

2023-03-15 14:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-03-15 14:41 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-configure-features.md
> +> For iOS, no alerts are generated on Microsoft 365 Defender when the URL or IP set in the indicator is accessed.
```suggestion
>
> For iOS, no alerts are generated on Microsoft 365 Defender when the URL or IP set in the indicator is accessed.
```

2023-03-15 14:41 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-15 15:04 UTC, JohanFreelancer9 approved these changes

2023-03-16 13:49 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2023-03-28 21:07 UTC, merged