Update remove-former-employee-step-4.md
MicrosoftDocs/microsoft-365-docs pull request #11345
Opened 2023-03-15 15:42 UTC by msbemba

Added an important note about an unsupported scenario

Fixes#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11272

2023-03-15 15:42 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-03-15 16:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-4.md
> +
```suggestion
> In scenarios where the mailbox is inactive due to compliance reasons, mail forwarding or converting the mailbox to a shared mailbox would not work.
```

2023-03-15 16:16 UTC, JohanFreelancer9 requested changes
Copy review.

2023-03-16 05:24 UTC, JohanFreelancer9 approved these changes

2023-03-16 14:23 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-03-28 16:23 UTC, merged