minor edit in the document
MicrosoftDocs/microsoft-365-docs pull request #1139
Opened 2020-01-27 07:03 UTC by joinimran

Initial steps revision in the document as few terms have changed.

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1076

2020-01-27 07:03 UTC, joinimran commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

@mypil FYI Please

2020-01-27 16:25 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md
> +2. Navigate to the **Search** and select **Audit log search**.
```suggestion
2. Navigate to **Search** and select **Audit log search**.
```

2020-01-27 16:28 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md
> +5. Click on the result to see the details of the activity. Click **More Information** to get deatils of the activity. Check to see if IsAdminContent is set to True.
```suggestion
5. Click on the result to see the details of the activity. Click **More Information** to get details of the activity. Check to see if IsAdminContent is set to True.
```

2020-01-27 16:32 UTC, JohanFreelancer9 requested changes
Copy Review

2020-01-28 07:39 UTC, joinimran commented
@mypil Ready to go live.

2020-01-29 23:25 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #1076

Thank you.

cc: @kenwith

2020-02-05 23:42 UTC, merged