Update quarantine-email-messages.md
MicrosoftDocs/microsoft-365-docs pull request #1145
Opened 2020-01-27 23:02 UTC by ryancairnes

Tweaking the language slightly to reflect the behavior.

2020-01-29 10:18 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-01-29 13:26 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/quarantine-email-messages.md
> +> Malware, high confidence phish messages and messages quarantined by mail flow rule actions are only available in the admin quarantine. Users can access their own phish, spam, and bulk mail messages
```suggestion
> Malware, high confidence phish messages, and messages quarantined by mail flow rule actions are only available in the admin quarantine. Users can access their own phish, spam, and bulk mail messages. 
```

2020-01-29 13:26 UTC, JohanFreelancer9 requested changes
Copy Review

2020-02-01 02:56 UTC, mypil commented
@ryancairnes  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-02-04 02:12 UTC, vern7509 approved these changes

2020-02-10 21:59 UTC, merged