Updated program name to just App Assure
MicrosoftDocs/microsoft-365-docs pull request #1153
Opened 2020-01-28 21:53 UTC by ColbyHaase

Our program name has changed. We are now just App Assure. I removed the work "Desktop" and udated our aka.ms link

2020-01-29 10:20 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-01-29 12:54 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/step-1-device-and-app-readiness.md
> +Another tool to help with Windows 10 and Office 365 ProPlus app compatibility is the [App Assure](https://aka.ms/appassure) program available through the FastTrack Center. Through Desktop App Assure
### 
```suggestion
Another tool to help with Windows 10 and Office 365 ProPlus app compatibility is the [App Assure](https://aka.ms/appassure) program available through the FastTrack Center. In the event of valid application issues, a Microsoft engineer with work with you through App Assure at no additional cost to help remediate the application incompatibility.
```

2020-01-29 12:58 UTC, JohanFreelancer9 requested changes
Copy Review

2020-02-01 03:12 UTC, mypil commented
@ColbyHaase - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-02-03 18:17 UTC, ColbyHaase commented
@mypil Sorry for the hassle, but I don't use GitHub. Not sure if I did it correctly? The suggested changes are great, so we want to go with those. Please let me know if there's something else I need to do. Thank you!

2020-02-04 04:03 UTC, mypil commented
@ColbyHaase - No worries. You did the right thing. I will tag the author now for review and to get his approval to merge this PR. 

Thank you for your contribution to make the docs better! Much appreciated!

2020-02-04 04:04 UTC, mypil commented
@JGruszczyk - PR has been copy edited and is ready for final review. 


Thank you.

cc: @kenwith

2020-02-04 16:37 UTC, merged