Update view-the-dlp-reports.md with filter limitations
MicrosoftDocs/microsoft-365-docs pull request #1161
Opened 2020-01-29 20:02 UTC by telaws

We need to update the documentation around scenario where a customer may have such a large amount of DLP policies that they may encounter 500 error upon attempting to get DLP report in SCC UI. This is due to all policies being returned by default for report and when customer has a large amount of DLP policies being returned the content URL length is exceeded, causing the 500 error. Customer must use a filter in this case in which they can filter DLP policies by service or by querying a group of policies.

2020-01-29 22:27 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-01-30 00:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/view-the-dlp-reports.md
> +If your organization has a large amount of DLP policies you may have to query by group of policies or filter by DLP policy service, as by default report will return all policies unless filter or quer
```suggestion
If your organization has a large amount of DLP policies, you may have to query by group of policies or filter by DLP policy service, as the report will return all policies by default unless a filter or query is applied. This is due to the content URL length being exceeded as each policy will add to the length of the URL for DLP report and may result in a 500 server error. Improvements are planned in the future where these limits will not apply.    
```

2020-01-30 00:12 UTC, JohanFreelancer9 requested changes
Copy Review - minor edits.

2020-01-30 20:02 UTC, telaws commented
@JohanFreelancer9  @mypil, is anything else needed here?

2020-01-30 23:11 UTC, mypil commented
@telaws - No other action required from you. I will let the author review & get approval for PR merging.

2020-01-30 23:12 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. 


Thank you.

cc: @kenwith

2020-02-08 00:52 UTC, chrfox commented
I'll review this with PG and get back to this thread with the appropriate action

2020-02-12 21:06 UTC, telaws commented
@chrfox any updates on this?

2020-02-18 18:30 UTC, chrfox commented
Hi @telaws 
I ran your edits past the product team and was told that the changes you suggest do not represent a supported or desirable work around. If you are still encountering this issue, I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP.

2020-02-18 18:30 UTC, closed without merging