Update cross-tenant-onedrive-migration.md
MicrosoftDocs/microsoft-365-docs pull request #11643
Opened 2023-04-11 17:59 UTC by msbemba

Made changes to the download URL

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11624

2023-04-11 17:59 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-04-11 21:04 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-onedrive-migration.md
>  - **Turn off service encryption with Customer Key enabled.** Confirm that the source OneDrive tenant **doesn't** have Service encryption with Microsoft Purview Customer Key enabled. If enabled on Sou
```suggestion
- **Microsoft SharePoint Online Powershell**. Confirm you have the most recent version installed. [Download SharePoint Online Management Shell from the official Microsoft Download Center](https://www.microsoft.com/download/details.aspx?id=35588).

- **Turn off service encryption with Customer Key enabled.** Confirm that the source OneDrive tenant **doesn't** have Service encryption with Microsoft Purview Customer Key enabled. If enabled on the source tenant, the migration will fail. [Learn more on Service encryption with Microsoft Purview Customer Key](/microsoft-365/compliance/customer-key-overview).
```

2023-04-11 21:05 UTC, JohanFreelancer9 requested changes
Copy review.

2023-04-12 16:07 UTC, JohanFreelancer9 approved these changes

2023-04-12 16:42 UTC, yogkumgit commented
@JoanneHendrickson Please merge this PR. Thanks

2023-04-12 17:36 UTC, merged