Update advanced-hunting-urlclickevents-table.md
MicrosoftDocs/microsoft-365-docs pull request #11646
Opened 2023-04-11 18:24 UTC by msbemba

Added information about supported tenants

reference from author https://learn.microsoft.com/en-us/microsoft-365/security/defender/supported-event-types?view=o365-worldwide#hunting-tables-support-status-in-event-streaming-api

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11604

2023-04-11 18:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-04-11 21:37 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/advanced-hunting-urlclickevents-table.md
> +The `UrlClickEvents` table in the advanced hunting schema contains information about [Safe Links](../office-365-security/safe-links-about.md) clicks from email messages, Microsoft Teams, and Office 3
```suggestion
The `UrlClickEvents` table in the advanced hunting schema contains information about [Safe Links](../office-365-security/safe-links-about.md) clicks from email messages, Microsoft Teams, and Office 365 apps in supported desktop, mobile, and web apps.  UrlClickEvents is currently in public preview for Microsoft 365 Commercial customers and not available yet for GCC, GCC High, or DoD.
```

2023-04-11 21:37 UTC, JohanFreelancer9 requested changes
Copy review.

2023-04-12 16:52 UTC, JohanFreelancer9 approved these changes

2023-04-12 16:58 UTC, yogkumgit commented
@schmurky Please merge this PR. Thanks

2023-04-18 11:52 UTC, yogkumgit commented
@schmurky Gentle reminder

2023-04-20 15:51 UTC, merged