Update microsoft-365-compliance-center-permissions.md
MicrosoftDocs/microsoft-365-docs pull request #11714
Opened 2023-04-18 13:32 UTC by msbemba

removed preview from administrative units as it is out of preview

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11651

2023-04-18 13:36 UTC, msbemba commented
@JohanFreelancer9 please copy review

2023-04-19 11:18 UTC, yogkumgit commented
@JohanFreelancer9

2023-04-20 10:29 UTC, JohanFreelancer9 commented on microsoft-365/compliance/microsoft-365-compliance-center-permissions.md
> +
```suggestion
```

2023-04-20 10:30 UTC, JohanFreelancer9 commented on microsoft-365/compliance/microsoft-365-compliance-center-permissions.md
```suggestion
```

2023-04-20 10:30 UTC, JohanFreelancer9 requested changes
Copy review.

2023-04-20 10:56 UTC, yogkumgit commented
@msbemba

2023-04-21 01:05 UTC, JohanFreelancer9 approved these changes

2023-04-21 10:44 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2023-06-19 12:14 UTC, yogkumgit commented
Closing as per the comment in #11651

2023-06-19 12:14 UTC, closed without merging