Update retention-policies-sharepoint.md
MicrosoftDocs/microsoft-365-docs pull request #11790
Opened 2023-04-21 15:23 UTC by shelri

https://o365exchange.visualstudio.com/Enterprise%20Cloud/_workitems/edit/3324859/

https://answers.microsoft.com/en-us/msoffice/forum/all/do-preservation-policies-impact-storage-quota/12525d68-c058-4028-b088-34e54949dc5a

2023-04-22 10:58 UTC, JohanFreelancer9 commented on microsoft-365/compliance/retention-policies-sharepoint.md
> + > Contents preserved in the Preservation Hold library is within users’ personal site. As a result, data in the Preservation Hold Library counts against the user's available storage.
```suggestion
 > Contents preserved in the Preservation Hold library are within the user’s personal site. As a result, data in the Preservation Hold library count against the user's available storage. 
```

2023-04-22 10:58 UTC, JohanFreelancer9 requested changes
Copy review - @shelri, kindly commit the suggested change. Many thanks.

2023-04-24 14:57 UTC, JohanFreelancer9 approved these changes

2023-04-25 04:00 UTC, cabailey commented
This statement is very out of place here - we already have a statement about the Preservation Hold library requiring more storage space in the higher-level article that introduces retaining content in place - now added OneDrive to the Note callout instead: https://learn.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#how-retention-settings-work-with-content-in-place

2023-04-25 04:00 UTC, closed without merging