Update audit-log-activities.md with Microsoft Defender Experts
MicrosoftDocs/microsoft-365-docs pull request #11858
Opened 2023-04-28 21:33 UTC by hyukjinkwonMicrosoft

Added new section for Microsoft Defender Experts activities

2023-04-30 05:57 UTC, JohanFreelancer9 commented on microsoft-365/compliance/audit-log-activities.md
> +The following table lists the activities in Microsoft Defender Experts that are logged in the Microsoft 365 audit log.
```suggestion
The following table lists the activities in Microsoft Defender Experts that are signed into the Microsoft 365 audit log.
```

2023-04-30 05:58 UTC, JohanFreelancer9 commented on microsoft-365/compliance/audit-log-activities.md
> +| Defender Experts Analyst Permission Modified | DefenderExpertsAnalystPermissionModified | An administrator modified role permissions to Defender Experts analysts to investigate incidents or remedia
```suggestion
| Defender Experts analyst permission created | DefenderExpertsAnalystPermissionCreated | An administrator granted one or more role permissions to Defender Experts analysts to investigate incidents or remediate threats.|
| Defender Experts analyst permission modified | DefenderExpertsAnalystPermissionModified | An administrator modified role permissions to Defender Experts analysts to investigate incidents or remediate threats.|
```

2023-04-30 05:59 UTC, JohanFreelancer9 requested changes
Copy review - @hyukjinkwonMicrosoft, kindly commit the suggested changes. Many thanks.

2023-05-03 22:24 UTC, hyukjinkwonMicrosoft commented
Hi @JohanFreelancer9 I've committed the changes you suggested. Thank you!

Since I don't have write access to this repo, I can't merge my PR. Could you assist me with this?

2023-05-04 07:31 UTC, JohanFreelancer9 approved these changes

2023-05-10 22:02 UTC, closed without merging

2023-05-10 22:03 UTC, robmazz commented
@yogkumgit  - FYI, discussed with PM, as internal stakeholder - he is opening the content request in our ADO per our process