Update enable-exploit-protection.md
MicrosoftDocs/microsoft-365-docs pull request #11863
Opened 2023-04-30 14:17 UTC by msbemba

Made changes to step2 and 3

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11835

2023-04-30 14:17 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-04-30 15:16 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-exploit-protection.md
> +3. Name the profile, choose **Windows 10 and later**, Select **templates** for Profile type and choose **Endpoint protection** under template name.
```suggestion
3. Name the profile, choose **Windows 10 and later**, select **templates** for Profile type and choose **Endpoint protection** under template name.
```

2023-04-30 15:17 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-01 03:39 UTC, JohanFreelancer9 approved these changes

2023-05-01 13:48 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2023-05-03 23:03 UTC, denisebmsft approved these changes
Thank you @msbemba

2023-05-03 23:09 UTC, merged