Update connect-to-microsoft-365-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #11864
Opened 2023-04-30 14:37 UTC by msbemba

Updated steps to import module first

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11781

2023-04-30 14:37 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-04-30 15:26 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/connect-to-microsoft-365-powershell.md
> +   1. Run the **Import-Module MSOnline** to import the module.
```suggestion
   1. Run the **Import-Module MSOnline** command to import the module.
```

2023-04-30 15:26 UTC, JohanFreelancer9 requested changes
Copy review.

2023-04-30 15:58 UTC, JohanFreelancer9 approved these changes

2023-05-01 14:07 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2023-06-30 12:23 UTC, yogkumgit commented
@kelleyvice-msft Gentle reminder.

2023-07-03 04:59 UTC, merged