Update enable-controlled-folders.md
MicrosoftDocs/microsoft-365-docs pull request #11862
Opened 2023-04-30 14:14 UTC by msbemba

Made changes to Step 3

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/11836

2023-04-30 14:14 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-04-30 15:07 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +3. Select **Platform**, choose **Windows 10, Windows 11 and Windows Server**, and select the profile **Attack Surface Reduction rules** \> **Create**.
```suggestion
3. Select **Platform**, choose **Windows 10, Windows 11, and Windows Server**, and select the profile **Attack Surface Reduction rules** \> **Create**.
```

2023-04-30 15:07 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-01 03:45 UTC, JohanFreelancer9 approved these changes

2023-05-01 13:46 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2023-06-23 17:30 UTC, merged