Added Entra portal reference
MicrosoftDocs/microsoft-365-docs pull request #11905
Opened 2023-05-04 15:22 UTC by miguel-s-ferreira

Added the new Entra portal available to centralize identity and governance features on cloud

2023-05-04 17:11 UTC, denisebmsft commented
Hello @miguel-s-ferreira. I need to verify whether we can push this live yet. We are on hold for doc updates for Entra, and I need to confirm whether this change is included in the larger update efforts.

2023-05-05 04:55 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/portals.md
> +| Entra portal | Access and administer the [Microsoft Entra](/entra) family, to protect your business with decentralized identity, identity protection, governance and more in a multi-cloud environmen
```suggestion
| Entra portal | Access and administer the [Microsoft Entra](/entra) family to protect your business with decentralized identity, identity protection, governance, and more, in a multi-cloud environment | [entra.microsoft.com](https://entra.microsoft.com/) |
```

2023-05-05 04:56 UTC, JohanFreelancer9 requested changes
Copy review - @miguel-s-ferreira, kindly commit the suggested minor changes. Many thanks.

2023-05-05 10:40 UTC, JohanFreelancer9 approved these changes

2023-05-09 18:35 UTC, denisebmsft approved these changes
Thank you @miguel-s-ferreira

2023-05-15 15:48 UTC, denisebmsft approved these changes

2023-05-15 15:53 UTC, merged