Update virus-initiative-criteria.md
MicrosoftDocs/microsoft-365-docs pull request #11916
Opened 2023-05-04 23:55 UTC by adamoboe

Adding that the MVI program will reopen for membership applications on June 1, 2023.

2023-05-04 23:56 UTC, adamoboe commented
Please approve the change to note that MVI re-opens for new member applications on June 1, 2023.

2023-05-05 05:25 UTC, JohanFreelancer9 commented on microsoft-365/security/intelligence/virus-initiative-criteria.md
> +> The MVI Program is not currently accepting new applications for membership, but will reopen for new members application on June 1, 2023. Please contact MVI@microsoft.com for more information.
```suggestion
> The MVI Program is not currently accepting new applications for membership but will reopen for new member applications on June 1, 2023. Please contact MVI@microsoft.com for more information.
```

2023-05-05 05:26 UTC, JohanFreelancer9 requested changes
Copy review - @adamoboe, kindly commit the minor suggested change. Many thanks.

2023-05-06 04:19 UTC, JohanFreelancer9 approved these changes

2023-06-06 20:00 UTC, merged