Update windows-whatsnew.md
MicrosoftDocs/microsoft-365-docs pull request #11976
Opened 2023-05-10 22:23 UTC by v-vtrieu

@denisebmsft please review and approve for May's content.  Thank you.

2023-05-11 05:49 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/windows-whatsnew.md
> +- Support new security settings management capabilities
```suggestion
- Supports new security settings management capabilities
```

2023-05-11 05:50 UTC, JohanFreelancer9 requested changes
Copy review - @v-vtrieu, minor suggested change, please.

2023-05-11 15:31 UTC, denisebmsft commented
> Copy review - @v-vtrieu, minor suggested change, please.

Done. Thank you @JohanFreelancer9 @v-vtrieu

2023-05-12 05:22 UTC, JohanFreelancer9 approved these changes

2023-05-14 15:40 UTC, denisebmsft approved these changes
Thank you @v-vtrieu

2023-05-14 15:40 UTC, merged