added link to spoof intelligence insight
MicrosoftDocs/microsoft-365-docs pull request #1199
Opened 2020-02-06 09:32 UTC by MaratMussabekov

#1167

2020-02-06 10:23 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-02-06 13:40 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md
> +> To allow sender domain to send unauthenticated emails (bypass anti-spoofing protection), but not bypassing anti-spam and anti-malware checks, you can add it to [AllowedToSpoof safe sender list]( ht
```suggestion
> To allow a sender domain to send unauthenticated emails (bypass anti-spoofing protection), but not bypassing anti-spam and anti-malware checks, you can add it to the [AllowedToSpoof safe sender list]( https://docs.microsoft.com/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight).
```

2020-02-06 13:52 UTC, JohanFreelancer9 requested changes
Copy Review

2020-02-07 22:18 UTC, mypil commented
@MSFTTracyP - PR has been copy edited and is ready for final review. This is based on issue #1167.

Thank you.

cc: @kenwith

2020-02-10 22:25 UTC, merged