Update whats-new.md
MicrosoftDocs/microsoft-365-docs pull request #12005
Opened 2023-05-14 13:35 UTC by Yaelbiss

Added DLP for Power BI GA under the April updates.

2023-05-14 13:43 UTC, Yaelbiss commented
@chrfox Can you please review this addition? Thanks!

2023-05-15 05:10 UTC, JohanFreelancer9 requested changes
Copy review - @Yaelbiss, kindly commit the suggested changes. Many thanks.

2023-05-15 05:12 UTC, JohanFreelancer9 commented on microsoft-365/compliance/whats-new.md
> +- **General availability (GA)**: Data Loss Prevention policies in Power BI to automatically detect sensitive infromation as it is being uploaded into Power BI and take immediate remediation actions.
```suggestion
- **General availability (GA)**: Data loss prevention policies in Power BI to automatically detect sensitive information as it is being uploaded into Power BI and take immediate remediation actions. [Learn about data loss prevention policies in Power BI)](/microsoft-365/compliance/dlp-powerbi-get-started).
```

2023-05-15 14:07 UTC, JohanFreelancer9 approved these changes

2023-05-24 23:12 UTC, merged