Update dlp-conditions-and-exceptions.md
MicrosoftDocs/microsoft-365-docs pull request #12013
Opened 2023-05-15 14:53 UTC by ybhargav1995

2023-05-16 06:11 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-conditions-and-exceptions.md
> +|Attachment is password protected|condition: *DocumentIsPasswordProtected* <br/><br/> exception: *ExceptIfDocumentIsPasswordProtected*|none|Messages where an attachment is password protected (and the
```suggestion
|Attachment is password protected|condition: *DocumentIsPasswordProtected* <br/><br/> exception: *ExceptIfDocumentIsPasswordProtected*|none|Messages where an attachment is password protected (and therefore can't be scanned). Password detection works for Office documents, archive documents (such as .zip, .7z, .rar, and .tar files), and .pdf files.|
```

2023-05-16 06:11 UTC, JohanFreelancer9 requested changes
Copy review - @ybhargav1995, kindly commit the suggested change. Many thanks.

2023-05-16 07:40 UTC, JohanFreelancer9 approved these changes

2023-05-25 04:37 UTC, ybhargav1995 commented
@chrfox - Can this be merged?

2023-06-08 11:24 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2023-06-09 17:55 UTC, merged