Update tvm-software-inventory.md
MicrosoftDocs/microsoft-365-docs pull request #12042
Opened 2023-05-17 16:07 UTC by msbemba

Added more information about data freshness

Reference - https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/how-is-the-software-inventory-created-in-mdatp/m-p/1447930?lightbox-message-images-2543838=295550i8196483D27428F00

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12026

2023-05-17 16:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-05-17 16:20 UTC, siosulli commented
Thanks @msbemba - I am just double checking this accurate before I publish! 

Thanks,
Sinead

2023-05-17 16:39 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-vulnerability-management/tvm-software-inventory.md
> +The data freshness is currently 4 hours. There is currently no way to force a sync.
```suggestion
The data is updated every three to four hours. There is currently no way to force a sync.
```

2023-05-17 16:41 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-18 09:56 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2023-05-18 12:25 UTC, JohanFreelancer9 approved these changes

2023-05-18 13:57 UTC, siosulli commented
> @siosulli Please merge this PR. Thanks

Will do! I'm still confirming whether this is accurate.

2023-06-08 11:27 UTC, yogkumgit commented
@siosulli

2023-06-21 16:57 UTC, yogkumgit commented
@siosulli Kindly update. Thanks

2024-04-18 14:51 UTC, merged