Update dlp-configure-endpoint-settings.md
MicrosoftDocs/microsoft-365-docs pull request #12040
Opened 2023-05-17 15:56 UTC by msbemba

Fixed Broken link

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12018

2023-05-17 15:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-05-17 16:15 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-configure-endpoint-settings.md
> +> - Microsoft Defender [April-2023 (Platform: 4.18.2304.8 | Engine: 1.1.20300.3)](/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates?view=o365-worldwide#april-2023-platfor
```suggestion
> - Microsoft Defender [April-2023 (Platform: 4.18.2304.8 | Engine: 1.1.20300.3)](/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates#april-2023-platform-41823048--engine-11203003)
```

2023-05-17 16:15 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-18 06:56 UTC, JohanFreelancer9 approved these changes

2023-05-18 09:51 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-05-18 14:15 UTC, merged