Update ediscovery-premium-limits.md
MicrosoftDocs/microsoft-365-docs pull request #12044
Opened 2023-05-17 16:43 UTC by StefanieBier

Clear language

2023-05-18 08:38 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery-premium-limits.md
> +|Maximum number of load sets (Collection jobs) per case.|200|200|
```suggestion
|Maximum number of load sets (collection jobs) per case.|200|200|
```

2023-05-18 08:39 UTC, JohanFreelancer9 requested changes
Copy review - @StefanieBier, kindly commit the minor suggested change. Many thanks.

2023-06-08 11:28 UTC, yogkumgit commented
@StefanieBier Please implement the suggested changes. Thanks

2023-06-19 11:53 UTC, yogkumgit commented
@StefanieBier Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.

2023-06-19 11:53 UTC, closed without merging