Fixed broken link
MicrosoftDocs/microsoft-365-docs pull request #12082
Opened 2023-05-23 04:35 UTC by sangling

This link is no longer valid
https://learn.microsoft.com/microsoft-365/security/defender-endpoint/microsoft-365/security/defender/configure-email-notifications

Updated to
https://learn.microsoft.com/microsoft-365/security/defender-endpoint/configure-vulnerability-email-notifications

2023-05-23 12:36 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/endpoint-attack-notifications.md
```suggestion
```

2023-05-23 12:37 UTC, JohanFreelancer9 requested changes
Copy review - @sangling, kindly commit the suggested change to remove the extra blank lines. Many thanks.

2023-05-23 12:57 UTC, sangling commented
Ahh - so sorry about that - that was sloppy of me.

2023-05-23 14:39 UTC, JohanFreelancer9 approved these changes

2023-05-24 06:09 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-05-24 14:56 UTC, tiburd commented
@vpattnai 
Hi,
As author of the article for the proposed change in this PR, do you approve of the change?

Please @ mention me in your response.

Thanks!

2023-05-24 14:58 UTC, merged