Update ocr-learn-about.md
MicrosoftDocs/microsoft-365-docs pull request #12103
Opened 2023-05-25 11:46 UTC by pratjain523

2023-05-25 15:03 UTC, kmkoenen requested changes, later dismissed
Changes required:

Lines 60 - 64, please use the following text:

[!NOTE]
To reduce your OCR costs, images sent in email via Microsoft Exchange are scanned and billed only once per unique image across all users of the tenant. For all subsequent instances, the results of the previous scan will be reused. Furthermore, there are no additional charges, regardless of whether or not the classification results are used by multiple policies across data loss prevention, insider risk management, auto-labeling, or records management.


Line 114 as follows:
> Only stand-alone images are scanned. Scanning images embedded inside Microsoft Office files (.docx, .xlsx, .pptx) and compressed/archive files (.zip, .rar, etc.) isn't supported at this point.

2023-05-25 16:01 UTC, pratjain523 commented
@kmkoenen We will avoid rescan only for smaller images like logo and signatures. The rephrased sentence is not accurate from product point of view.

2023-05-25 16:18 UTC, kmkoenen commented
Please update content:

Changes required:

Lines 60 - 64, please use the following text:

> [!NOTE]
> - To reduce your OCR costs, small images, such as logos and signatures that are sent in email via Microsoft Exchange are scanned and billed only once per unique image across all users of the tenant. For all subsequent instances, the results of the previous scan will be reused. 
> 
> - With respect to large images, although they are rescanned, there are no additional charges with respect to the number of classification results across multiple policies, including data loss prevention, insider risk management, auto-labeling, and records management.


Line 114 as follows:
> Only stand-alone images are scanned. Scanning images embedded inside Microsoft Office files (.docx, .xlsx, .pptx) and compressed/archive files (.zip, .rar, etc.) isn't supported at this point.

2023-05-26 11:31 UTC, pratjain523 commented
> [!NOTE]
> - To reduce your OCR costs, small images, such as logos and signatures that are sent in email via Microsoft Exchange are scanned and billed only once per unique image across all users of the tenant. For all subsequent instances, the results of the previous scan will be reused. 
> 
> - Every image is charged only once, irrespective of the number of policies across data loss prevention, insider risk management, auto-labeling, and records management.

 


Line 114 as follows:
> Only stand-alone images are scanned. Scanning images embedded inside Microsoft Office files (.docx, .xlsx, .pptx) and compressed/archive files (.zip, .rar, etc.) isn't supported at this point.

2023-06-05 09:31 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ocr-learn-about.md
> +> - To reduce your OCR costs, small images, such as logos and signatures that are sent in email via Microsoft Exchange are scanned and billed only once per unique image across all users of the tenant
```suggestion
> - To reduce your OCR costs, small images, such as logos and signatures that are sent in email via Microsoft Exchange are scanned and billed only once per unique image across all users of the organization. For all subsequent instances, the results of the previous scan will be reused.
```

2023-06-05 09:31 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ocr-learn-about.md
> +> - Only stand-alone images are scanned. Scanning images embedded inside Microsoft Office files (.docx, .xlsx, .pptx) and compressed/archive files (.zip, .rar, etc.) isn't supported at this point.
```suggestion
> - Only stand-alone images are scanned. Scanning images embedded inside Microsoft Office files (.docx, .xlsx, .pptx) and compressed or archive files (such as .zip and .rar) isn't supported at this point.
```

2023-06-05 09:33 UTC, JohanFreelancer9 requested changes
Copy review - @pratjain523, kindly commit the minor suggested changes. Many thanks.

2023-06-08 11:31 UTC, yogkumgit commented
@kmkoenen Please merge this PR. Thanks

2023-06-19 11:53 UTC, yogkumgit commented
@pratjain523 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.

2023-06-19 11:53 UTC, closed without merging