Update integrate-office-365-ti-with-mde.md
MicrosoftDocs/microsoft-365-docs pull request #12113
Opened 2023-05-28 06:29 UTC by msbemba

added an important note about MDO and MDE integration

2023-05-28 06:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-05-28 08:02 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/integrate-office-365-ti-with-mde.md
> +> This setting was used when Microsoft Defender for Office 365 and Microsoft Defender for Endpoint were in different portals back in the time. After the convergence of security experiences into unifi
```suggestion
> This setting was used when Microsoft Defender for Office 365 and Microsoft Defender for Endpoint were in different portals previously. After the convergence of security experiences into a unified portal that is now called Microsoft 365 Defender, these settings are irrelevant and don't have any functionality associated with them. You can safely ignore the status of the control until it is removed from the portal.
```

2023-05-28 08:02 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-28 08:30 UTC, JohanFreelancer9 approved these changes

2023-05-29 04:36 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2023-05-29 15:24 UTC, denisebmsft approved these changes
Thank you @msbemba

2023-05-29 15:29 UTC, merged