Update office-365-u.s.-government-gcc-high-endpoints.md
MicrosoftDocs/microsoft-365-docs pull request #12129
Opened 2023-05-30 14:14 UTC by msbemba

Added a note for Cross-Cloud Join

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12098

2023-05-30 14:14 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-05-30 15:00 UTC, JohanFreelancer9 commented on microsoft-365/includes/office-365-u.s.-government-gcc-high-endpoints.md
> +  - [Office 365 U.S. Government DoD endpoints](/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints)
```suggestion
> [!NOTE]
> For  Cross-Cloud Anonymous Join to work properly, you must add these endpoints for the cloud of the target meeting to the safe senders list:
> - [Office 365 URLs and IP address ranges](/microsoft-365/enterprise/urls-and-ip-address-ranges)
> - [Office 365 U.S. Government DoD endpoints](/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints)
```

2023-05-30 15:00 UTC, JohanFreelancer9 commented on microsoft-365/includes/office-365-u.s.-government-gcc-high-endpoints.md
> +
```suggestion
```

2023-05-30 15:04 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-30 15:13 UTC, JohanFreelancer9 approved these changes

2023-05-31 13:48 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2023-06-06 20:07 UTC, merged