Update set-password-to-never-expire.md
MicrosoftDocs/microsoft-365-docs pull request #12127
Opened 2023-05-30 13:56 UTC by msbemba

Added steps to connect to MGgraph

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12049

2023-05-30 13:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-05-30 14:25 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/set-password-to-never-expire.md
> +Use the `Connect-MgGraph` command to sign in with the required scopes. You'll need to sign in with an admin account to consent to the required scopes.
```suggestion
Use the `Connect-MgGraph` command to sign in with the required scopes. You need to sign in with an admin account to consent to the required scopes.
```

2023-05-30 14:26 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-30 15:23 UTC, JohanFreelancer9 approved these changes

2023-05-31 13:41 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-05-31 15:22 UTC, merged