Update command-line-arguments-microsoft-defender-antivirus.md
MicrosoftDocs/microsoft-365-docs pull request #12151
Opened 2023-06-01 04:23 UTC by msbemba

Changed description of parameters  "ResetPlatform" and "RevertPlatform"

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12116

2023-06-01 04:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-06-01 06:09 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/command-line-arguments-microsoft-defender-antivirus.md
> +|`-ResetPlatform`| Reset platform binaries back to `%ProgramFiles%\Windows Defender`|
```suggestion
|`-ResetPlatform`| Reset platform binaries back to `%ProgramFiles%\Windows Defender`.|
```

2023-06-01 06:10 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/command-line-arguments-microsoft-defender-antivirus.md
> +|`-RevertPlatform`| Revert platform binaries back to the previous installed version of the Defender platform.|
```suggestion
|`-RevertPlatform`| Revert platform binaries back to the previously installed version of the Defender platform.|
```

2023-06-01 06:10 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-01 06:46 UTC, JohanFreelancer9 approved these changes

2023-06-01 15:47 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2023-06-06 19:19 UTC, denisebmsft approved these changes
Thank you @msbemba @JohanFreelancer9

2023-06-06 19:50 UTC, merged