Update data-classification-overview.md
MicrosoftDocs/microsoft-365-docs pull request #1217
Opened 2020-02-10 22:49 UTC by Bhavanesh

2020-02-11 02:44 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-02-11 07:04 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-overview.md
>  As a Microsoft 365 administrator or compliance administrator, you can evaluate and then tag content in your organization in order to control where it goes, protect it no matter where it is and to ens
```suggestion
As a Microsoft 365 administrator or compliance administrator, you can evaluate and then tag content in your organization in order to control where it goes, protect it no matter where it is and to ensure that it is preserved and deleted according your your organization's needs. You do this through the application of [sensitivity labels](sensitivity-labels.md), [retention labels](labels.md), and sensitive information type classification. There are various ways to do the discovery, evaluation and tagging, but the end result is that you may have very large numbers of documents and emails that are tagged and classified with one or both of these labels. After you apply  your retention labels and sensitivity labels, you’ll want to see how the labels are being used across your tenant and what is being done with those items. The data classification page provides visibility into that body of content, specifically:
```

2020-02-11 07:05 UTC, JohanFreelancer9 requested changes
Copy Review - please also add apostrophe to Line 23 as indicated.

2020-02-12 02:30 UTC, mypil commented
@Bhavanesh - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-02-20 02:18 UTC, mypil commented
@Bhavanesh - We would like to follow up on this. Can you please merge the commit on the copy/edit review done by JohanFreelancer9?

Thank you.

2020-02-20 02:21 UTC, Bhavanesh commented
Chris - did you accept this?


Sent from my phone.
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Joyce Y. <notifications@github.com>
Sent: Wednesday, February 19, 2020 6:18:05 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)


@Bhavanesh<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBhavanesh&data=02%7C01%7CBhavanesh.Rengarajan%40microsoft.com%7Cb323c1a9461c48af61a308d7b5ab1eb6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637177618879835910&sdata=Pam1ApCTHEyL7H%2F8nEjFrBsgXQm2wujejqctc9BSsoQ%3D&reserved=0> - We would like to follow up on this. Can you please merge the commit on the copy/edit review done by JohanFreelancer9?

Thank you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DANOWMJDUSPJII7BXSY27SWTRDXR53A5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMKPBKI%23issuecomment-588574889&data=02%7C01%7CBhavanesh.Rengarajan%40microsoft.com%7Cb323c1a9461c48af61a308d7b5ab1eb6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637177618879845906&sdata=ay4o1HMkMDPC690rcpoOmOytAqEypINW2w%2ByB%2Bw4Rn0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOWMJEIUO64PUPDZ4HWWHTRDXR53ANCNFSM4KSW73JA&data=02%7C01%7CBhavanesh.Rengarajan%40microsoft.com%7Cb323c1a9461c48af61a308d7b5ab1eb6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637177618879855902&sdata=6fNuF6gUUnx3c53b0ipONmDIYvPxlcj0%2BvreawF1WNk%3D&reserved=0>.

2020-02-20 16:51 UTC, Bhavanesh commented
@Meryljoyce Ypil<mailto:ypilmeryljoyce@gmail.com>

Hi Bhavy - I don't see this on my report of outstanding PR and GH issues so I have missed it.

https://msit.powerbi.com/groups/me/reports/4db881b0-ba34-401a-b1da-a2173baad7ac/ReportSection?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47

I'll look more deeply into GH to find it. Sorry for the delay

Chris



From: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com>
Sent: Wednesday, February 19, 2020 6:21 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>; MicrosoftDocs/microsoft-365-docs <reply@reply.github.com>; Christopher J Fox (OFFICE) <chrfox@exchange.microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

Chris - did you accept this?


Sent from my phone.
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Joyce Y. <notifications@github.com<mailto:notifications@github.com>>
Sent: Wednesday, February 19, 2020 6:18:05 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com>>
Cc: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)


@Bhavanesh<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBhavanesh&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552967217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=3PTn5Qvm3BGnW6WEycQKQrhbDxFGaYJVawSTsszLySU%3D&reserved=0> - We would like to follow up on this. Can you please merge the commit on the copy/edit review done by JohanFreelancer9?

Thank you.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DANOWMJDUSPJII7BXSY27SWTRDXR53A5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMKPBKI%23issuecomment-588574889&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552977166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=cAOk5LKFO6pDPiD4%2Fo%2Fzu3SiAWJtFkQcSS3%2FKn1E1kc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOWMJEIUO64PUPDZ4HWWHTRDXR53ANCNFSM4KSW73JA&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552977166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=bbTO63fyxkfhFvs19UUcqagoAT%2FN1OBhENKJUvIv1sA%3D&reserved=0>.

2020-02-20 18:32 UTC, chrfox commented
Found it.  I’ll get it reviewed and get back to you.

@Bhavanesh Rengarajan<mailto:Bhavanesh.Rengarajan@microsoft.com> it would help get the notification through faster if you @ mention me in the PR.

Thanks,

Chris

From: Bhavanesh <notifications@github.com>
Sent: Thursday, February 20, 2020 8:52 AM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

@Meryljoyce Ypil<mailto:ypilmeryljoyce@gmail.com>

Hi Bhavy - I don't see this on my report of outstanding PR and GH issues so I have missed it.

https://msit.powerbi.com/groups/me/reports/4db881b0-ba34-401a-b1da-a2173baad7ac/ReportSection?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47

I'll look more deeply into GH to find it. Sorry for the delay

Chris



From: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com>>
Sent: Wednesday, February 19, 2020 6:21 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com>>; MicrosoftDocs/microsoft-365-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; Christopher J Fox (OFFICE) <chrfox@exchange.microsoft.com<mailto:chrfox@exchange.microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

Chris - did you accept this?


Sent from my phone.
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Joyce Y. <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Sent: Wednesday, February 19, 2020 6:18:05 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com%3cmailto:microsoft-365-docs@noreply.github.com>>>
Cc: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com%3cmailto:Bhavanesh.Rengarajan@microsoft.com>>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com<mailto:mention@noreply.github.com%3cmailto:mention@noreply.github.com>>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)


@Bhavanesh<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBhavanesh&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552967217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=3PTn5Qvm3BGnW6WEycQKQrhbDxFGaYJVawSTsszLySU%3D&reserved=0> - We would like to follow up on this. Can you please merge the commit on the copy/edit review done by JohanFreelancer9?

Thank you.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DANOWMJDUSPJII7BXSY27SWTRDXR53A5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMKPBKI%23issuecomment-588574889&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552977166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=cAOk5LKFO6pDPiD4%2Fo%2Fzu3SiAWJtFkQcSS3%2FKn1E1kc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOWMJEIUO64PUPDZ4HWWHTRDXR53ANCNFSM4KSW73JA&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552977166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=bbTO63fyxkfhFvs19UUcqagoAT%2FN1OBhENKJUvIv1sA%3D&reserved=0>.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DAEO4FNHS553MRRXNJK6JM2DRD2YJJA5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMPCYYI%23issuecomment-589180001&data=02%7C01%7Cchrfox%40exchange.microsoft.com%7C2827c8a7174c4e208ba808d7b62523a3%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637178142940361657&sdata=cY%2BNWt%2FRviuaOZXSvrrUuMa%2BWXMbWqCSwT%2BavH67DdE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEO4FNEFP3BX57JO3TI65TLRD2YJJANCNFSM4KSW73JA&data=02%7C01%7Cchrfox%40exchange.microsoft.com%7C2827c8a7174c4e208ba808d7b62523a3%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637178142940361657&sdata=%2FMZ6SqTk5hNL5uijJ8phGS1k5XCMvLtD3sWuDKFm0qA%3D&reserved=0>.

2020-02-20 18:33 UTC, merged

2020-02-20 18:37 UTC, chrfox commented
Merged, should be live sometime today

From: Christopher J Fox (OFFICE)
Sent: Thursday, February 20, 2020 10:28 AM
To: 'MicrosoftDocs/microsoft-365-docs' <reply@reply.github.com>; MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>; Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

Found it.  I’ll get it reviewed and get back to you.

@Bhavanesh Rengarajan<mailto:Bhavanesh.Rengarajan@microsoft.com> it would help get the notification through faster if you @ mention me in the PR.

Thanks,

Chris

From: Bhavanesh <notifications@github.com<mailto:notifications@github.com>>
Sent: Thursday, February 20, 2020 8:52 AM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

@Meryljoyce Ypil<mailto:ypilmeryljoyce@gmail.com>

Hi Bhavy - I don't see this on my report of outstanding PR and GH issues so I have missed it.

https://msit.powerbi.com/groups/me/reports/4db881b0-ba34-401a-b1da-a2173baad7ac/ReportSection?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47

I'll look more deeply into GH to find it. Sorry for the delay

Chris



From: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com>>
Sent: Wednesday, February 19, 2020 6:21 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com>>; MicrosoftDocs/microsoft-365-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; Christopher J Fox (OFFICE) <chrfox@exchange.microsoft.com<mailto:chrfox@exchange.microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

Chris - did you accept this?


Sent from my phone.
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Joyce Y. <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Sent: Wednesday, February 19, 2020 6:18:05 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com%3cmailto:microsoft-365-docs@noreply.github.com>>>
Cc: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com%3cmailto:Bhavanesh.Rengarajan@microsoft.com>>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com<mailto:mention@noreply.github.com%3cmailto:mention@noreply.github.com>>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)


@Bhavanesh<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBhavanesh&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552967217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=3PTn5Qvm3BGnW6WEycQKQrhbDxFGaYJVawSTsszLySU%3D&reserved=0> - We would like to follow up on this. Can you please merge the commit on the copy/edit review done by JohanFreelancer9?

Thank you.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DANOWMJDUSPJII7BXSY27SWTRDXR53A5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMKPBKI%23issuecomment-588574889&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552977166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=cAOk5LKFO6pDPiD4%2Fo%2Fzu3SiAWJtFkQcSS3%2FKn1E1kc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOWMJEIUO64PUPDZ4HWWHTRDXR53ANCNFSM4KSW73JA&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552977166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=bbTO63fyxkfhFvs19UUcqagoAT%2FN1OBhENKJUvIv1sA%3D&reserved=0>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DAEO4FNHS553MRRXNJK6JM2DRD2YJJA5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMPCYYI%23issuecomment-589180001&data=02%7C01%7Cchrfox%40exchange.microsoft.com%7C2827c8a7174c4e208ba808d7b62523a3%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637178142940361657&sdata=cY%2BNWt%2FRviuaOZXSvrrUuMa%2BWXMbWqCSwT%2BavH67DdE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEO4FNEFP3BX57JO3TI65TLRD2YJJANCNFSM4KSW73JA&data=02%7C01%7Cchrfox%40exchange.microsoft.com%7C2827c8a7174c4e208ba808d7b62523a3%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637178142940361657&sdata=%2FMZ6SqTk5hNL5uijJ8phGS1k5XCMvLtD3sWuDKFm0qA%3D&reserved=0>.

2020-02-20 18:37 UTC, chrfox commented
Thanks a lot @Christopher<mailto:chrfox@exchange.microsoft.com>.

Bhavy

From: Christopher J Fox (OFFICE) <chrfox@exchange.microsoft.com>
Sent: Thursday, February 20, 2020 10:37 AM
To: MicrosoftDocs/microsoft-365-docs <reply@reply.github.com>; MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>; Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

Merged, should be live sometime today

From: Christopher J Fox (OFFICE)
Sent: Thursday, February 20, 2020 10:28 AM
To: 'MicrosoftDocs/microsoft-365-docs' <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com>>; Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

Found it.  I'll get it reviewed and get back to you.

@Bhavanesh Rengarajan<mailto:Bhavanesh.Rengarajan@microsoft.com> it would help get the notification through faster if you @ mention me in the PR.

Thanks,

Chris

From: Bhavanesh <notifications@github.com<mailto:notifications@github.com>>
Sent: Thursday, February 20, 2020 8:52 AM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com>>
Cc: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

@Meryljoyce Ypil<mailto:ypilmeryljoyce@gmail.com>

Hi Bhavy - I don't see this on my report of outstanding PR and GH issues so I have missed it.

https://msit.powerbi.com/groups/me/reports/4db881b0-ba34-401a-b1da-a2173baad7ac/ReportSection?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmsit.powerbi.com%2Fgroups%2Fme%2Freports%2F4db881b0-ba34-401a-b1da-a2173baad7ac%2FReportSection%3Fctid%3D72f988bf-86f1-41af-91ab-2d7cd011db47&data=04%7C01%7CBhavanesh.Rengarajan%40microsoft.com%7Cf4669575c52d4bf0e6b108d7b633eb30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637178206417486204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=ujSoAuWdrI7Sml1KY0ZZLuwe15RVfRDTICR1rlSR0Mw%3D&reserved=0>

I'll look more deeply into GH to find it. Sorry for the delay

Chris



From: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com>>
Sent: Wednesday, February 19, 2020 6:21 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com>>; MicrosoftDocs/microsoft-365-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; Christopher J Fox (OFFICE) <chrfox@exchange.microsoft.com<mailto:chrfox@exchange.microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)

Chris - did you accept this?


Sent from my phone.
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Joyce Y. <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Sent: Wednesday, February 19, 2020 6:18:05 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com<mailto:microsoft-365-docs@noreply.github.com%3cmailto:microsoft-365-docs@noreply.github.com>>>
Cc: Bhavanesh Rengarajan <Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com<mailto:Bhavanesh.Rengarajan@microsoft.com%3cmailto:Bhavanesh.Rengarajan@microsoft.com>>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com<mailto:mention@noreply.github.com%3cmailto:mention@noreply.github.com>>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update data-classification-overview.md (#1217)


@Bhavanesh<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBhavanesh&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552967217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=3PTn5Qvm3BGnW6WEycQKQrhbDxFGaYJVawSTsszLySU%3D&reserved=0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBhavanesh&data=04%7C01%7CBhavanesh.Rengarajan%40microsoft.com%7Cf4669575c52d4bf0e6b108d7b633eb30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637178206417496199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=uHTN2wjaPW6%2B01UWNRNsbeTZBw3cBFSlrNRs1H5ozdk%3D&reserved=0>> - We would like to follow up on this. Can you please merge the commit on the copy/edit review done by JohanFreelancer9?

Thank you.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DANOWMJDUSPJII7BXSY27SWTRDXR53A5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMKPBKI%23issuecomment-588574889&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552977166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=cAOk5LKFO6pDPiD4%2Fo%2Fzu3SiAWJtFkQcSS3%2FKn1E1kc%3D&reserved=0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DANOWMJDUSPJII7BXSY27SWTRDXR53A5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMKPBKI%23issuecomment-588574889&data=04%7C01%7CBhavanesh.Rengarajan%40microsoft.com%7Cf4669575c52d4bf0e6b108d7b633eb30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637178206417496199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=U4knYH%2FnYSJKxQVplb0L0OSI7zsdCzbtFetEWvMoooQ%3D&reserved=0>>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOWMJEIUO64PUPDZ4HWWHTRDXR53ANCNFSM4KSW73JA&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7C94de80ebb92d45c1441408d7b5ab82cd%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637177620552977166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=bbTO63fyxkfhFvs19UUcqagoAT%2FN1OBhENKJUvIv1sA%3D&reserved=0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOWMJEIUO64PUPDZ4HWWHTRDXR53ANCNFSM4KSW73JA&data=04%7C01%7CBhavanesh.Rengarajan%40microsoft.com%7Cf4669575c52d4bf0e6b108d7b633eb30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637178206417506199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=SjIaLknhc%2BljwMrkelUWe%2Bge17fUhSVMTf1KGwrY5vY%3D&reserved=0>>.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F1217%3Femail_source%3Dnotifications%26email_token%3DAEO4FNHS553MRRXNJK6JM2DRD2YJJA5CNFSM4KSW73JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMPCYYI%23issuecomment-589180001&data=04%7C01%7CBhavanesh.Rengarajan%40microsoft.com%7Cf4669575c52d4bf [...]