Update Network Protection for macOS docs
MicrosoftDocs/microsoft-365-docs pull request #12185
Opened 2023-06-05 07:43 UTC by verndrade

Add updates now that Network Protection for Mac is GA

2023-06-05 10:27 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/network-protection-macos.md
> +  - Block website categories scoped to device groups through policies created in the MDEP Portal.
```suggestion
- Custom Indicators of Compromise on Domains and IPs.
- Web Content Filtering support:
  - Block website categories scoped to device groups through policies created in the MDEP portal.
```

2023-06-05 10:28 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/network-protection-macos.md
> +- Advanced Hunting - Network Events will be reflected in the Machine Timeline, and queryable in Advanced Hunting to aid security investigations
```suggestion
- Advanced Hunting - Network Events will be reflected in the Machine Timeline, and queryable in Advanced Hunting to aid security investigations.
```

2023-06-05 10:28 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/network-protection-macos.md
> +Network Protection for macOS is now available for all Microsoft Defender for Endpoint onboarded macOS devices which meet the minimum requirements. All of your currently configured Network Protection
```suggestion
Network Protection for macOS is now available for all Microsoft Defender for Endpoint onboarded macOS devices that meet the minimum requirements. All of your currently configured Network Protection and Web Threat Protection policies will be enforced on macOS devices where Network Protection is configured for block mode.
```

2023-06-05 10:28 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/network-protection-macos.md
> +To rollout Network Protection for macOS, we recommend the following:
```suggestion
To roll out Network Protection for macOS, we recommend the following:
```

2023-06-05 10:28 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/network-protection-macos.md
> +- Evaluate the impact of Web Threat Protection, Custom Indicators of Compromise, Web Content Filtering, and Microsoft Defender for Cloud Apps enforcement policies which target those macOS devices whe
```suggestion
- Create a device group for a small set of devices that you can use to test Network Protection.
- Evaluate the impact of Web Threat Protection, Custom Indicators of Compromise, Web Content Filtering, and Microsoft Defender for Cloud Apps enforcement policies that target those macOS devices where Network Protection is in Block mode.
```

2023-06-05 10:29 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/network-protection-macos.md
> +- Microsoft Defender for Cloud Apps
```suggestion
- Microsoft Defender for Cloud Apps:
```

2023-06-05 10:30 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/network-protection-macos.md
> +  - Blocking Applications - Block entire applications (e.g Slack, Facebook) from being used in your organization
```suggestion
  - Block applications - Block entire applications (such as Slack and Facebook) from being used in your organization.
```

2023-06-05 10:33 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/network-protection-macos.md
> +- Corporate VPN in tandem or "side by side" with Network Protection.
```suggestion
- Corporate VPN in tandem or side-by-side with Network Protection: 
```

2023-06-05 10:37 UTC, JohanFreelancer9 requested changes
Copy review - @verndrade, kindly commit the suggested changes. Many thanks.

2023-06-05 14:52 UTC, verndrade commented
> Copy review - @verndrade, kindly commit the suggested changes. Many thanks.

Thanks for the review!

2023-06-05 15:43 UTC, JohanFreelancer9 approved these changes

2023-06-08 11:37 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2023-06-22 18:25 UTC, merged