Update dlp-policy-reference.md
MicrosoftDocs/microsoft-365-docs pull request #12201
Opened 2023-06-06 15:15 UTC by ybhargav1995

2023-06-07 06:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-policy-reference.md
> +- Document or attachment is password protected (PDF, Office files, .ZIP,.7z and Symantec PGP encrypted files are fully supported). This condition detects only open protected files.
```suggestion
- Document or attachment is password protected (PDF, Office files, .ZIP, .7z, and Symantec PGP encrypted files are fully supported). This condition detects only open protected files.
```

2023-06-07 06:28 UTC, JohanFreelancer9 requested changes
Copy review - @ybhargav1995, kindly commit the suggested change. Many thanks.

2023-06-07 10:39 UTC, JohanFreelancer9 approved these changes

2023-06-08 11:38 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2023-06-09 17:34 UTC, merged