Update device-onboarding-offboarding-macos-jamfpro.md
MicrosoftDocs/microsoft-365-docs pull request #12213
Opened 2023-06-07 16:23 UTC by Arkthos

This could be ambiguous, as seen in a support case recently:

"- Make sure your [macOS devices are managed through JAMF pro](https://www.jamf.com/resources/product-documentation/jamf-pro-installation-guide-for-mac/) and are associated with an identity (Azure AD joined UPN) through [JAMF Connect](https://www.jamf.com/products/jamf-connect) or Microsoft Intune."

in the sense that it could be interpreted as you go jamf + (jamf conenct OR intune)  or in the other hand as "You can go (Jamf + Jamf connect) OR Intune

something like :

"- Ensure that your macOS devices are managed through JAMF Pro and are also associated with an identity (Azure AD joined UPN). This association should be made through either JAMF Connect or Microsoft Intune."

Should eliminate that ambiguity

2023-06-08 08:05 UTC, JohanFreelancer9 commented on microsoft-365/compliance/device-onboarding-offboarding-macos-jamfpro.md
> +- Ensure that your [macOS devices are managed through JAMF pro](https://www.jamf.com/resources/product-documentation/jamf-pro-installation-guide-for-mac/) and are also associated with an identity (Az
```suggestion
- Ensure that your [macOS devices are managed through JAMF Pro](https://www.jamf.com/resources/product-documentation/jamf-pro-installation-guide-for-mac/) and are also associated with an identity (Azure AD joined UPN). This association should be made through either [JAMF Connect](https://www.jamf.com/products/jamf-connect) or Microsoft Intune.
```

2023-06-08 08:06 UTC, JohanFreelancer9 requested changes
Copy review - @Arkthos, kindly commit the suggested changes. Many thanks.

2023-06-08 16:58 UTC, JohanFreelancer9 approved these changes

2023-06-19 11:50 UTC, yogkumgit commented
@Arkthos Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.

2023-06-19 11:51 UTC, closed without merging