Update prepare-tls-1.2-in-office-365.md
MicrosoftDocs/microsoft-365-docs pull request #12247
Opened 2023-06-14 05:17 UTC by msbemba

Added a statement stating this is completed.

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12226

2023-06-14 05:17 UTC, msbemba commented
@JohanFreelancer9 please copy review

2023-06-14 09:07 UTC, JohanFreelancer9 commented on microsoft-365/compliance/prepare-tls-1.2-in-office-365.md
> +We have already completed deprecation of TLS 1.0 and 1.1.
```suggestion
We have already completed the deprecation of TLS 1.0 and 1.1.
```

2023-06-14 09:08 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-14 09:18 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-14 10:13 UTC, JohanFreelancer9 approved these changes

2023-06-14 12:55 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2023-06-14 14:11 UTC, JohanFreelancer9 approved these changes

2023-06-19 11:45 UTC, yogkumgit commented
Closing as per the comment in #12226

2023-06-19 11:45 UTC, closed without merging