Update revoke-ome-encrypted-mail.md
MicrosoftDocs/microsoft-365-docs pull request #12244
Opened 2023-06-14 04:44 UTC by msbemba

Updated the portal

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12217

2023-06-14 04:44 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-06-14 09:37 UTC, JohanFreelancer9 commented on microsoft-365/compliance/revoke-ome-encrypted-mail.md
> +1. In the Microsoft 365 Defender portal, navigate to the **Message encryption report**. For information on this report, see [View email security reports in the Security &amp; Compliance Center](../se
```suggestion
1. In the Microsoft 365 Defender portal, navigate to the **Message encryption report**. For information about this report, see [View email security reports in the Security &amp; Compliance Center](../security/office-365-security/reports-email-security.md).
```

2023-06-14 09:37 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-14 12:46 UTC, yogkumgit commented
@JohanFreelancer9

2023-06-14 12:47 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2023-06-14 14:09 UTC, JohanFreelancer9 approved these changes

2023-06-19 11:49 UTC, yogkumgit commented
Closing as per the comment in #12217

2023-06-19 11:49 UTC, closed without merging