Update mailbox-usage.md
MicrosoftDocs/microsoft-365-docs pull request #12285
Opened 2023-06-20 15:31 UTC by msbemba

added a statement about recoverable items

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12249

2023-06-20 15:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-06-21 05:47 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/mailbox-usage.md
> +The **Mailbox usage** report does not include  **Recoverable Items** as they are included in **Recoverable Items mailbox quota**
```suggestion
The **Mailbox usage** report does not include **Recoverable Items** as they are included in the **Recoverable Items mailbox quota**.
```

2023-06-21 05:48 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-21 07:00 UTC, JohanFreelancer9 approved these changes

2023-06-21 15:15 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-06-22 00:11 UTC, merged