Update download-software-licenses-csp.md
MicrosoftDocs/microsoft-365-docs pull request #12288
Opened 2023-06-20 16:00 UTC by msbemba

Added information about GA

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12275

2023-06-20 16:00 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-06-21 06:03 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/download-software-licenses-csp.md
> +> If you are a partner, you need to log in to the customer tenant with an admin account created in this tenant.
```suggestion
> If you are a partner, you need to sign in to the customer's organization with an admin account created in the organization.
```

2023-06-21 06:04 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-21 07:00 UTC, JohanFreelancer9 approved these changes

2023-06-21 15:44 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2023-06-29 14:18 UTC, oradcliffe commented
Bump - has not been updated.  Can someone please confirm this is correct, that the Global Admin account must be homed in the customer tenant (ie a CSP partner with Admin on Behalf Of into customer tenant cannot perform this task), and then update the doc accordingly?

2023-07-05 18:40 UTC, oradcliffe commented
Page is still not updated

2023-07-06 06:46 UTC, yogkumgit commented
@cmcatee-MSFT Gentle reminder. Thanks

2023-09-05 19:45 UTC, oradcliffe commented
Looking for an update.

2023-09-06 08:06 UTC, yogkumgit commented
@cmcatee-MSFT This is long pending, please review, comment or merge. Thanks

2023-09-12 08:59 UTC, msbemba commented
Fixes https://github.com/MicrosoftDocs/microsoft-365-docs-pr/issues/23702 as well

2024-01-09 21:07 UTC, merged

2024-01-11 18:52 UTC, cmcatee-MSFT reviewed
Please change the sentence to the following:

If you're a partner who's an admin on behalf of (AOBO) a customer, you must sign in to the customer's organization with an admin account created in the organization.