Update m365-dr-workload-other.md
MicrosoftDocs/microsoft-365-docs pull request #12287
Opened 2023-06-20 15:49 UTC by msbemba

Made changes to reflect Yammer vs viva engage

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12277

2023-06-20 15:49 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-06-20 17:31 UTC, denisebmsft approved these changes
Thank you @msbemba

2023-06-21 06:34 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/m365-dr-workload-other.md
> +See [Manage data for Microsoft Whiteboard | Microsoft Learn](/microsoft-365/whiteboard/manage-data-organizations).
```suggestion

See [Manage data for Microsoft Whiteboard | Microsoft Learn](/microsoft-365/whiteboard/manage-data-organizations).
```

2023-06-21 06:34 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-21 10:03 UTC, JohanFreelancer9 approved these changes

2023-06-21 15:42 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2023-08-09 15:29 UTC, yogkumgit commented
@kelleyvice-msft Gentle reminder

2025-04-15 18:41 UTC, kelleyvice-msft commented
Changes already made in another PR.

2025-04-15 18:41 UTC, closed without merging