Update activity-reports.md
MicrosoftDocs/microsoft-365-docs pull request #12295
Opened 2023-06-21 21:05 UTC by dotnvo

In my several talks with Microsoft, we've ran into pretty long delays in reporting data in several areas of teams. This document seems to cover most general reporting in Teams. These delays are seen in Graph, as well as the admin center, which makes sense, because the raw source of the data for these calls are likely the same.

I was informed by support that 48 hours is actually the SLA for this data. However it's common to have a delay of data showing up that is longer than this. Some organizations use this data frequently and it becomes a cause for concern. My suggestion her is to basically add some verbiage that gives Microsoft a little wiggle room and also so IT staff can point to a doc stating that look, it indeed can take longer. Again I've been told that the SLA is 48 hours for teams data to become available, but it's not always the case, particularly around the start of the week, the data seems to be delayed. It takes more than 48 hours often enough for a tenant to get updated info that this document (and likely others) really needs to indicate that it can take more than 48 hours for this to happen. I left it open-ended in my addition, but I welcome Microsoft to modify as needed, I just ask that something is put here to help Microsoft customers who work in IT to able to reference. I've worked with support enough on this to know they don't really have control, and I think the folks responsible for dealing with the data in teams would likely agree with my assessment here.

2023-06-22 11:59 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/activity-reports.md
> +before becoming available.
```suggestion
Reports are available for the last 7 days, 30 days, 90 days, and 180 days. Data won't exist for all reporting periods right away. The reports typically become available within 48 hours, but might sometimes take several days
to become available.
```

2023-06-22 12:00 UTC, JohanFreelancer9 requested changes
Copy review - @dotnvo, kindly commit the suggested change. Many thanks.

2023-06-23 17:02 UTC, dotnvo commented
@JohanFreelancer9 Thanks for your reply. I have implemented your suggestions , should be good to go.

2023-06-24 07:18 UTC, JohanFreelancer9 approved these changes

2023-06-30 12:28 UTC, yogkumgit commented
@camillepack Please merge this PR. Thanks

2023-07-07 18:10 UTC, merged