Update internet-facing-devices.md
MicrosoftDocs/microsoft-365-docs pull request #12383
Opened 2023-07-05 05:34 UTC by msbemba

Added defender for business to the applies to section

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12360

2023-07-05 05:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-07-05 07:33 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/internet-facing-devices.md
> +- [Microsoft Defender for Business](/microsoft-365/security/defender-business/)
```suggestion
- [Microsoft Defender for Business](/microsoft-365/security/defender-business)
```

2023-07-05 07:34 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-05 12:40 UTC, JohanFreelancer9 approved these changes

2023-07-06 06:43 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2023-07-10 16:54 UTC, denisebmsft approved these changes
Thank you @msbemba

2023-07-10 17:04 UTC, merged