Update connect-to-gcc-data-with-usage-analytics.md
MicrosoftDocs/microsoft-365-docs pull request #12458
Opened 2023-07-13 16:12 UTC by msbemba

Added a statement to reduce ambiguity on GCCH

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12435

2023-07-13 16:12 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-07-14 05:46 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/connect-to-gcc-data-with-usage-analytics.md
> +> These instructions are specifically for Microsoft 365 GCC tenants and not applicate for not GCC HIgh/DOD.
```suggestion
> These instructions are specifically for Microsoft 365 GCC tenants and are not applicate to GCC HIgh and DOD.
```

2023-07-14 05:47 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-14 07:16 UTC, JohanFreelancer9 approved these changes

2023-07-14 15:38 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2023-07-21 17:55 UTC, merged