Update add-another-email-alias-for-a-user.md
MicrosoftDocs/microsoft-365-docs pull request #12515
Opened 2023-07-24 13:45 UTC by msbemba

Added information on how to edit the alias in AD

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12479

2023-07-24 13:45 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-07-24 14:49 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/add-another-email-alias-for-a-user.md
> +If you get this error message it means that you need to add the alias in your on-premises Active Directory. Open **Active Directory** > **Right Click on the user account you would like to Edit** > **
```suggestion
If you get this error message it means that you need to add the alias in your on-premises Active Directory. Open Azure Active Directory and select the user account you would like to edit. Select **Properties** > **Attribute Editor** > **Proxyaddresses** and add the required alias, then wait for it to sync to Azure Active directory.
```

2023-07-24 14:50 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-24 15:50 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-07-24 16:29 UTC, JohanFreelancer9 approved these changes

2023-08-09 15:42 UTC, yogkumgit commented
@kwekuako Gentle reminder

2023-08-09 19:25 UTC, merged