Update cross-tenant-onedrive-migration-step5.md
MicrosoftDocs/microsoft-365-docs pull request #12516
Opened 2023-07-24 13:47 UTC by msbemba

Moved the compatibility step to the top as it needs to be checked first.

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12482

2023-07-24 13:47 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-07-24 15:27 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-onedrive-migration-step5.md
> +
```suggestion
```

2023-07-24 15:28 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-24 15:53 UTC, yogkumgit commented
@JoanneHendrickson Please merge this PR. Thanks

2023-07-24 16:16 UTC, JohanFreelancer9 approved these changes

2023-08-09 15:41 UTC, yogkumgit commented
@JoanneHendrickson Gentle reminder

2025-10-23 16:35 UTC, closed without merging

2025-10-23 16:35 UTC, v-jmathew commented
Closing as GitHub account of the submitter not found.