Update prevent-end-user-interaction-microsoft-defender-antivirus.md
MicrosoftDocs/microsoft-365-docs pull request #12525
Opened 2023-07-25 16:56 UTC by msbemba

Added UI lockdown cmdlet

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12490

2023-07-25 16:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-07-26 06:53 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/prevent-end-user-interaction-microsoft-defender-antivirus.md
> +## UI Lockdown
```suggestion
## UI Lockdown mode
```

2023-07-26 06:53 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/prevent-end-user-interaction-microsoft-defender-antivirus.md
> +Indicates whether to disable UI lockdown mode. If you specify a value of $True, Windows Defender disables UI lockdown mode. If you specify $False or do not specify a value, UI lockdown mode is enable
```suggestion
Indicates whether to disable UI Lockdown mode. If you specify a value of $True, Windows Defender disables UI Lockdown mode. If you specify $False or do not specify a value, UI Lockdown mode is enabled.
```

2023-07-26 06:54 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-26 11:43 UTC, yogkumgit commented
@JohanFreelancer9

2023-07-26 14:27 UTC, JohanFreelancer9 approved these changes

2023-07-26 15:53 UTC, denisebmsft approved these changes
Thank you @msbemba

2023-07-26 15:56 UTC, merged