Update what-is-microsoft-defender-threat-intelligence-defender-ti.md
MicrosoftDocs/microsoft-365-docs pull request #12528
Opened 2023-07-26 00:07 UTC by gichiu

Replaced the word artifact with indicator.  Made updates to 2 paragraphs.

2023-07-26 00:37 UTC, gichiu commented
@Dansimp, this is my first time editing.  Do I need to tag someone to review and approve?

2023-07-26 14:48 UTC, JohanFreelancer9 commented on defender/threat-intelligence/what-is-microsoft-defender-threat-intelligence-defender-ti.md
> +Below is a screenshot of Defender TI’s Threat Intelligence Home Page. Analysts can quickly scan new featured articles as well as begin their intelligence gathering, triage, incident response, and hun
```suggestion
Below is a screenshot of Defender TI’s Threat Intelligence Home Page. Analysts can quickly scan new featured articles as well as begin their intelligence gathering, triage, incident response, and hunting efforts by performing a keyword, indicator, or CVE-ID search.
```

2023-07-26 14:48 UTC, JohanFreelancer9 commented on defender/threat-intelligence/what-is-microsoft-defender-threat-intelligence-defender-ti.md
> +Microsoft’s Defender TI platform allows users to develop multiple project types for organizing indicators of interest and indicators of compromise from an investigation. Projects contain a listing of
```suggestion
Microsoft Defender TI platform allows users to develop multiple project types for organizing indicators of interest and indicators of compromise from an investigation. Projects contain a listing of all associated indicators and a detailed history that retains the names, descriptions, and collaborators.
```

2023-07-26 14:49 UTC, JohanFreelancer9 requested changes
Copy review - @gichiu, kindly commit the two minor additional suggested changes. Many thanks.

2023-07-26 14:55 UTC, JohanFreelancer9 approved these changes

2023-08-09 15:40 UTC, yogkumgit commented
@DulceMontemayor Please merge this PR. Thanks

2023-08-17 22:49 UTC, merged