Update servicenow-overview.md
MicrosoftDocs/microsoft-365-docs pull request #12549
Opened 2023-07-27 18:23 UTC by seakim-ms

Adding note about language support

2023-07-28 06:13 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/servicenow-overview.md
> +> This app is only supported in English.
```suggestion
>
> This app is only supported in English.
```

2023-07-28 06:14 UTC, JohanFreelancer9 requested changes
Copy review - @seakim-ms, kindly commit the suggested change. Many thanks.

2023-07-28 15:42 UTC, JohanFreelancer9 approved these changes

2023-08-09 15:38 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2023-08-09 16:09 UTC, merged