Update office-365-ti.md
MicrosoftDocs/microsoft-365-docs pull request #12547
Opened 2023-07-27 17:05 UTC by msbemba

Added All e5 licenses and an important section to the document

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12520

2023-07-27 17:05 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-07-28 07:08 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/office-365-ti.md
> +
```suggestion
> This setting was used when Microsoft Defender for Office 365 and Microsoft Defender for Endpoint were in different portals previously. After the convergence of security experiences into a unified portal that is now called Microsoft 365 Defender, these settings are irrelevant and don't have any functionality associated with them. You can safely ignore the status of the control until it is removed from the portal.
```

2023-07-28 07:09 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/office-365-ti.md
> +
```suggestion
```

2023-07-28 07:09 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/office-365-ti.md
> +This feature is only available if you have an active Office 365 E5/G5, M365 E5/G5 subscription or the Threat Intelligence add-on. For more information, see the Office 365 Enterprise E5 product page.
```suggestion
This feature is only available if you have an active Office 365 E5 or G5 or Microsoft 365 E5 or G5 subscription or the Threat Intelligence add-on. For more information, see the Office 365 Enterprise E5 product page.
```

2023-07-28 07:10 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-28 11:22 UTC, yogkumgit commented
@msbemba

2023-07-28 15:41 UTC, JohanFreelancer9 approved these changes

2023-07-31 11:40 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2023-08-09 15:39 UTC, yogkumgit commented
@MSFTTracyP Gentle reminder

2023-09-26 01:24 UTC, merged