Update shifts-connector-ukg-known-issues.md
MicrosoftDocs/microsoft-365-docs pull request #12557
Opened 2023-07-28 17:57 UTC by imarquesgil

Updated on the: A user can’t perform some actions in Shifts in the Teams web app after signing in with a different account section

2023-07-31 07:22 UTC, JohanFreelancer9 commented on microsoft-365/frontline/shifts-connector-ukg-known-issues.md
> +- Clear cookies and site data for the mykronos.com site in the browser after each user signs out of Teams web app. To learn more, see [Delete cookies in Microsoft Edge](https://support.microsoft.com/
```suggestion
- Clear cookies and site data for the mykronos.com site in the browser after each user signs out of the Teams web app. To learn more, see [Delete cookies in Microsoft Edge](https://support.microsoft.com/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09) or [Clear, enable, and manage cookies in Chrome](https://support.google.com/chrome/answer/95647).
```

2023-07-31 07:23 UTC, JohanFreelancer9 commented on microsoft-365/frontline/shifts-connector-ukg-known-issues.md
> +## A user B can’t perform some actions in Shifts after another user has signed in to Shifts through the same device
```suggestion
## A user can’t perform some actions in Shifts after another user has signed in to Shifts using the same device
```

2023-07-31 07:23 UTC, JohanFreelancer9 commented on microsoft-365/frontline/shifts-connector-ukg-known-issues.md
> +This issue can occur if multiple users, using the same device, try to connect to Teams Shifts app and require to single sign-on (SSO) in UKG Dimensions.
```suggestion
This issue can occur if multiple users use the same device to connect to the Teams Shifts app and require a single sign-on (SSO) in UKG Dimensions. 
```

2023-07-31 07:24 UTC, JohanFreelancer9 commented on microsoft-365/frontline/shifts-connector-ukg-known-issues.md
> +For example, a user A signs in to Teams, requests a time off request, and signs out. To perform the request, user A was required to introduce their AAD credentials to verify (SSO). Using the same dev
```suggestion
For example, user A signs in to Teams, requests a time off request, and signs out. To perform the request, user A was required to introduce their Azure AD credentials to verify (SSO). Using the same device, user B signs in to Teams and tries to perform another action in Shifts that requires SSO.
```

2023-07-31 07:24 UTC, JohanFreelancer9 commented on microsoft-365/frontline/shifts-connector-ukg-known-issues.md
> +In this scenario, an issue occurs in which the user B is signed in to Teams and Shifts but user A is still signed in to UKG Dimensions.
```suggestion
In this scenario, an issue occurs in which user B is signed in to Teams and Shifts but user A is still signed in to UKG Dimensions.
```

2023-07-31 07:24 UTC, JohanFreelancer9 commented on microsoft-365/frontline/shifts-connector-ukg-known-issues.md
> +- Close all the opened browser windows after each user signs out of Teams web app. This needs to happen independently of whether the user has accessed Teams web app through InPrivate window in Micros
```suggestion
- Close all the opened browser windows after each user signs out of the Teams web app. This needs to happen independently of whether the user has accessed the Teams web app through the InPrivate window in Microsoft Edge or in Incognito mode in Google Chrome.
```

2023-07-31 07:24 UTC, JohanFreelancer9 commented on microsoft-365/frontline/shifts-connector-ukg-known-issues.md
> +- Clear cookies and site data for the mykronos.com site in the browser after each user signs out of Teams web app. To learn more, see [Delete cookies in Microsoft Edge](https://support.microsoft.com/
```suggestion
- Clear cookies and site data for the mykronos.com site in the browser after each user signs out of the Teams web app. To learn more, see [Delete cookies in Microsoft Edge](https://support.microsoft.com/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09) or [Clear, enable, and manage cookies in Chrome](https://support.google.com/chrome/answer/95647).
```

2023-07-31 07:25 UTC, JohanFreelancer9 requested changes
Copy review - @imarquesgil, kindly commit the suggested changes. Many thanks.

2023-07-31 15:20 UTC, JohanFreelancer9 approved these changes

2023-08-01 15:13 UTC, daisyfell commented
I'm no longer working on frontline. Assigning to Heidi

2023-08-01 20:54 UTC, merged