Update microsoft-secure-score-improvement-actions.md
MicrosoftDocs/microsoft-365-docs pull request #12589
Opened 2023-08-03 14:24 UTC by msbemba

Fixed Typo

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12554

2023-08-03 14:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-08-03 14:42 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/microsoft-secure-score-improvement-actions.md
> +Recommended actions have a "completed" status once all possible points for the recommended action have been achieved. Completed recommended actions are confirmed though Microsoft data, and you can't
```suggestion
Recommended actions have a "completed" status once all possible points for the recommended action have been achieved. Completed recommended actions are confirmed through Microsoft data, and you can't change the status.
```

2023-08-03 14:42 UTC, JohanFreelancer9 requested changes
Copy review.

2023-08-04 06:14 UTC, JohanFreelancer9 approved these changes

2023-08-04 12:35 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-08-04 14:03 UTC, merged