Update control section
MicrosoftDocs/microsoft-365-docs pull request #12614
Opened 2023-08-10 11:29 UTC by TobiasAsk

Refer to updated method of using the Graph API to control the activation of Feed.

2023-08-15 08:52 UTC, JohanFreelancer9 commented on microsoft-365/ms-feed/m365-feed.md
> +In Microsoft 365, as a Global Tenant Admin, you can disable Microsoft Feed for your tenant through the Microsoft Graph API. See the [Graph API docs](https://learn.microsoft.com/en-us/graph/api/resour
```suggestion
In Microsoft 365, as a global admin, you can disable Microsoft Feed for your organization using Microsoft Graph API. See [microsoftApplicationDataAccessSettings resource type](/graph/api/resources/microsoftapplicationdataaccesssettings) for instructions on how to disable Microsoft Feed. 
```

2023-08-15 08:53 UTC, JohanFreelancer9 requested changes
Copy review - @TobiasAsk, kindly commit the suggested changes. Many thanks.

2023-08-15 14:12 UTC, TobiasAsk commented
Thanks for your suggestions @JohanFreelancer9, I've applied them

2023-08-15 14:55 UTC, JohanFreelancer9 approved these changes

2023-08-29 03:19 UTC, yogkumgit commented
@temanteleary Please merge this PR. Thanks

2023-09-21 15:07 UTC, yogkumgit commented
@temanteleary Gentle reminder. Thanks

2025-10-23 16:27 UTC, v-jmathew commented
This PR has been open for an extended period of time and has conflicts. If these changes are still relevant, please re-submit them to https://github.com/MicrosoftDocs/microsoft-365-docs-pr/.

2025-10-23 16:27 UTC, closed without merging