Update air-review-approve-pending-completed-actions.md
MicrosoftDocs/microsoft-365-docs pull request #12646
Opened 2023-08-17 15:26 UTC by msbemba

added note about the time frame for pending actions to expire

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12621

2023-08-17 15:27 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-08-18 06:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions.md
> +
```suggestion
```

2023-08-18 06:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions.md
> +
```suggestion
```

2023-08-18 06:13 UTC, JohanFreelancer9 requested changes
Copy review.

2023-08-18 12:19 UTC, JohanFreelancer9 approved these changes

2023-08-18 14:55 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2023-08-28 21:28 UTC, merged