Removed Azure Portal and Updated FAQs
MicrosoftDocs/microsoft-365-docs pull request #12655
Opened 2023-08-19 01:45 UTC by ByBrianGoodman

Removed Azure Portal and Updated FAQs

2023-08-19 09:39 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/idle-session-timeout-web-apps.md
> +### I am active in Azure Portal, but I am logged out of other M365 Apps for inactivity.  Why am I logged out?
```suggestion
### I am active in Azure Portal, but I am logged out of other Microsoft 365 Apps for inactivity.  Why am I logged out?
```

2023-08-19 09:40 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/idle-session-timeout-web-apps.md
> +Azure Portal supports a similar inactivity feature, but is supported by Azure Portal only. For more information, see [Azure Portal: Signing-Out + Notification](/azure/azure-portal/set-preferences#sig
```suggestion
Azure Portal supports a similar inactivity feature that is supported by Azure Portal only. For more information, see [Azure Portal: Signing-Out + Notification](/azure/azure-portal/set-preferences#signing-out--notifications).
```

2023-08-19 09:41 UTC, JohanFreelancer9 requested changes
Copy review - @ByBrianGoodman, kindly commit the suggested changes. Many thanks.

2023-08-21 14:29 UTC, ByBrianGoodman reviewed
@JohanFreelancer9 - Changes look good.

2023-08-23 17:21 UTC, merged