Update linux-install-manually.md
MicrosoftDocs/microsoft-365-docs pull request #12695
Opened 2023-08-29 08:17 UTC by msbemba

Made changes to the location of GPG Public key

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12660

2023-08-29 08:17 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-08-29 13:31 UTC, JohanFreelancer9 approved these changes

2023-09-04 11:28 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2023-09-18 23:55 UTC, narkuroki commented
@yogkumgit 
@msbemba 
Unfortunately, the command you're trying to fix fails on Debian 11 and below.
What I wanted in this request was to write instructions for both pre-Debian 11 and he for Debian 12.
It seems that my request was not conveyed correctly.
Could you please fix it again as below?

・Contents currently published in the document
━━━━━━━━━━━━━━━━━━━━
・Install the Microsoft GPG public key:
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
━━━━━━━━━━━━━━━━━━━━

・What you are currently trying to modify with "https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12695"
━━━━━━━━━━━━━━━━━━━━
・Install the Microsoft GPG public key:
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg > /dev/null
━━━━━━━━━━━━━━━━━━━━

・Real content that you want to correct
━━━━━━━━━━━━━━━━━━━━
・Install the Microsoft GPG public key:

For Debian 11 and below, run the following command.
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

For Debian 12 and above, run the following command.
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg > /dev/null
━━━━━━━━━━━━━━━━━━━━

2023-09-19 06:23 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/linux-install-manually.md
> +For Debian 11 and below, run the following command.
```suggestion
For Debian 11 and earlier, run the following command.
```

2023-09-19 06:23 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/linux-install-manually.md
> +For Debian 12 and above, run the following command.
```suggestion
For Debian 12 and later, run the following command.
```

2023-09-19 06:24 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-19 06:42 UTC, narkuroki commented
@JohanFreelancer9 
The current content is the same command for both Debian 11 and earlier and Debian 12 and later.
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/107231494/e4c98fda-001f-4449-89b1-312149918c44)

Correctly, I would like it to be written as follows.

For Debian 11 and earlier, run the following command.
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

For Debian 12 and later, run the following command.
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg > /dev/null

2023-09-19 07:25 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/linux-install-manually.md
> +  curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg  > /dev/null
```suggestion
  curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
```

2023-09-19 07:29 UTC, JohanFreelancer9 requested changes
@msbemba as per @narkuroki's request.

2023-09-19 08:34 UTC, JohanFreelancer9 approved these changes

2023-09-19 15:01 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks.

2023-09-25 11:31 UTC, yogkumgit commented
@Dansimp Gentle reminder.

2023-10-03 05:51 UTC, narkuroki commented
@yogkumgit 
@Dansimp 
Is it possible to correct the documentation regarding this matter?
Thank you for your cooperation.

2023-11-07 00:18 UTC, merged