Fix confusing note
MicrosoftDocs/microsoft-365-docs pull request #1272
Opened 2020-02-21 06:44 UTC by MaratMussabekov

#1224

2020-02-21 10:23 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-02-21 13:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/classifier-getting-started-with.md
> +> Both **Automated pattern matching** and **Trainable classifiers** are available as a condition for [auto-apply retention label policy based on a condition](labels.md#applying-a-retention-label-auto
```suggestion
> Both **Automated pattern matching** and **Trainable classifiers** are available as conditions for [auto-apply retention label policy based on a condition](labels.md#applying-a-retention-label-automatically-based-on-conditions) and [Communication compliance](communication-compliance.md).
```

2020-02-21 13:51 UTC, JohanFreelancer9 requested changes
Copy Review

2020-02-22 01:00 UTC, mypil commented
@MaratMussabekov  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-02-25 00:12 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #1224.


Thank you.

cc: @kenwith

2020-02-27 12:40 UTC, MaratMussabekov commented
replaced by  #1310

2020-02-27 12:40 UTC, closed without merging