Update cross-tenant-onedrive-migration-faqs.md
MicrosoftDocs/microsoft-365-docs pull request #12729
Opened 2023-09-04 01:21 UTC by msbemba

made changes to the onedrive site quota for migration

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12704

2023-09-04 01:21 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-09-04 08:50 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-onedrive-migration-faqs.md
> +**Answer:**  Each individual OneDrive site/account being migrated must have no more than 2 TB of storage, or 1 million items. The 1 million item limit can be any "item", including files (including ve
```suggestion
**Answer:**  Each individual OneDrive site/account being migrated must have no more than 2 TB of storage, or 1 million items. The 1 million item limit can be any "item", including files (including versions), folders, and list line entries if it is a list or library.  **IMPORTANT:** If you attempt to migrate any OneDrive site that exceeds the 2 TB quota, the transfer fails.
```

2023-09-04 08:51 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-06 08:51 UTC, JohanFreelancer9 approved these changes

2023-09-06 10:33 UTC, yogkumgit commented
@JoanneHendrickson Please merge this PR. Thanks

2023-09-21 15:03 UTC, yogkumgit commented
@JoanneHendrickson Gentle reminder. Thanks

2025-09-18 05:57 UTC, v-mathavale commented
This PR has been open for an extended period of time and has conflicts. If these changes are still relevant, please re-submit them to [microsoft-365-docs-pr](https://github.com/MicrosoftDocs/microsoft-365-docs-pr/)

2025-09-18 05:57 UTC, closed without merging