Updated fixed-reported-inaccuracies.md with Aug & Sep fixes
MicrosoftDocs/microsoft-365-docs pull request #12760
Opened 2023-09-11 13:41 UTC by v-Jagadeeshl

2023-09-12 02:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-vulnerability-management/fixed-reported-inaccuracies.md
> +| 30809 |Fixed inaccuracy in Fireeye path of Openssl| 05-Sep-23
```suggestion
| 30809 |Fixed inaccuracy in FireEye path of OpenSSL| 05-Sep-23
```

2023-09-12 02:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-vulnerability-management/fixed-reported-inaccuracies.md
> +| 30303 | MDVM doesn't currently support Lenovo thinkpad models : E15-gen 4 , L13, L490, T490, T490s, T470s| 29-Aug-23
```suggestion
| 30303 | MDVM doesn't currently support Lenovo ThinkPad models E15-gen 4, L13, L490, T490, T490s, and T470s| 29-Aug-23
```

2023-09-12 02:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-vulnerability-management/fixed-reported-inaccuracies.md
> +| 29397	| Fixed inaccuracy in Microsoft powershell|	29-Aug-23
```suggestion
| 29397	| Fixed inaccuracy in Microsoft PowerShell|	29-Aug-23
```

2023-09-12 02:47 UTC, JohanFreelancer9 requested changes
Copy review - @v-Jagadeeshl, kindly commit the suggested changes. Many thanks.

2023-09-14 08:48 UTC, JohanFreelancer9 approved these changes

2023-09-21 15:00 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2023-09-21 15:24 UTC, siosulli commented
Thanks @yogkumgit - This PR was created in the public repo by mistake and is not ready to be merged. I will actually close this one out and create one in the private repo as we are not sure when the changes will be signed off.

2023-09-25 10:36 UTC, closed without merging

2023-09-25 10:36 UTC, siosulli commented
I have created this https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/22265 in the private repo for these changes. Closing out this PR.