minor change in the content
MicrosoftDocs/microsoft-365-docs pull request #1277
Opened 2020-02-23 15:02 UTC by joinimran

There was a minor mistake that was changing the whole meaning of the information. As policy tips are required so made some adjustments. 

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1219

2020-02-23 15:02 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

@mypil FYI Please.

2020-02-23 15:32 UTC, JohanFreelancer9 commented on microsoft-365/compliance/use-notifications-and-policy-tips.md
> +For each rule in a DLP policy, you need configure policy tips to:
```suggestion
For each rule in a DLP policy, you need to configure policy tips to:
```

2020-02-23 15:34 UTC, JohanFreelancer9 requested changes
Copy Review

2020-02-23 16:22 UTC, joinimran commented
Ready to go live.

2020-02-23 16:32 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #1219.

Thank you.

cc: @kenwith

2020-03-03 18:02 UTC, chrfox commented
A change is needed, but the change made in this PR doesn't address the issue.  Closing this and making the change in a different PR.  The issue to be addressed is that when user notifications are enabled, both policy tips and email notifications are enabled simultaneously.  Email notifications cannot be enabled without policy tips being enabled and policy tips cannot be enabled without email notifications.

2020-03-03 18:02 UTC, closed without merging