Update run-analyzer-macos-linux.md
MicrosoftDocs/microsoft-365-docs pull request #12778
Opened 2023-09-12 13:26 UTC by msbemba

Made the changes as the Checksum returned by the supplied command does not match.

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12698

2023-09-12 13:26 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-09-12 14:19 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md
> +    > The current SHA256 hash of 'XMDEClientAnalyzerBinary.zip' that is downloaded from the above link is: 'E8D1B752A937E9AB305AE3C30737E31D75AE6FF9299002AB23F5C463C77DD159'
```suggestion
    > The current SHA256 hash of 'XMDEClientAnalyzerBinary.zip' that is downloaded from this link is: 'E8D1B752A937E9AB305AE3C30737E31D75AE6FF9299002AB23F5C463C77DD159'
```

2023-09-12 14:19 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-12 15:38 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2023-09-12 15:46 UTC, JohanFreelancer9 approved these changes

2023-09-21 14:58 UTC, yogkumgit commented
@mjcaparas Gentle reminder. Thanks

2023-09-27 17:10 UTC, merged