Update bookings-in-outlook.md
MicrosoftDocs/microsoft-365-docs pull request #12802
Opened 2023-09-15 13:32 UTC by msbemba

made changes to EWSenabled values to clear ambiguity

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12787

2023-09-15 13:32 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-09-15 15:43 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-in-outlook.md
> +    If the command returns "EwsEnabled:" (empty is default),  no further changes are needed then proceed to Step 2
```suggestion
    If the command returns "EwsEnabled:" (empty is default), no further changes are needed, proceed to Step 2.
```

2023-09-15 15:43 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-18 11:13 UTC, yogkumgit commented
@msbemba

2023-09-18 11:13 UTC, yogkumgit commented
@kwekuako

2023-09-27 11:21 UTC, yogkumgit commented
@msbemba Gentle reminder.

2023-09-27 13:41 UTC, JohanFreelancer9 approved these changes

2023-09-27 18:40 UTC, merged