Update testintuneapplication.md
MicrosoftDocs/microsoft-365-docs pull request #12803
Opened 2023-09-15 13:41 UTC by msbemba

Fixed Typo

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12775

2023-09-15 13:41 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-09-15 15:51 UTC, JohanFreelancer9 commented on microsoft-365/test-base/testintuneapplication.md
>  As an Intune customer who has an Intune package, which has been already onboarded to Intune portal. Customer can onboard the intunewin package (containing an app with/without dependencies of pre-inst
```suggestion
As an Intune customer who has an Intune package, which has been already onboarded to Intune portal. Customer can onboard the intunewin package (containing an app with/without dependencies of pre-install apps managed in Intune) to Test Base service (via Intune account, which has proper permission to sync the Intune app info).
```

2023-09-15 15:52 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-16 05:45 UTC, JohanFreelancer9 approved these changes

2023-09-18 11:22 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-09-19 14:40 UTC, merged