Update threat-trackers.md
MicrosoftDocs/microsoft-365-docs pull request #12811
Opened 2023-09-18 08:23 UTC by ajaj-shaikh

Added "Security Reader" role as this is by design available for sec reader role

2023-09-18 10:02 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-trackers.md
> +- Make sure that your security team has the correct roles and permissions assigned. You must be a global administrator, or have the Security Administrator, or have the Security Reader or Search and P
```suggestion
- Make sure that your security team has the correct roles and permissions assigned. You must be a global administrator, or have the Security Administrator, Security Reader, or Search and Purge role assigned in the Microsoft 365 Defender portal. See [Permissions in the Microsoft 365 Defender portal](mdo-portal-permissions.md).
```

2023-09-18 10:03 UTC, JohanFreelancer9 requested changes
Copy review - @ajaj-shaikh, kindly commit the suggested change. Many thanks.

2023-09-18 10:21 UTC, JohanFreelancer9 approved these changes

2023-09-20 06:41 UTC, ajaj-shaikh commented
@denisebmsft @MSFTTracyP can you please merge this pull request?

2023-09-25 11:38 UTC, yogkumgit commented
@MSFTTracyP Gentle reminder.

2023-09-26 00:57 UTC, merged