Update remove-former-employee-step-1.md
MicrosoftDocs/microsoft-365-docs pull request #12886
Opened 2023-09-29 12:08 UTC by msbemba

Added information on ## What you need to know about terminating an employee's email session to Step 1 Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12857

2023-09-29 12:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-09-30 09:05 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-1.md
> +Here's information about how to get an employee out of email (Exchange).
```suggestion
The following information explains how to remove an employee from the organization's email (Exchange):
```

2023-09-30 09:06 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-1.md
> +****
```suggestion
```

2023-09-30 09:06 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-1.md
> +|Terminate the session for a particular protocol (such as ActiveSync)|Disable the protocol. For example, in the Exchange admin center or using PowerShell: <p>  `Set-CASMailbox user@contoso.com -Activ
```suggestion
|Terminate a session (such as Outlook on the web, Outlook, or Exchange active sync) and force them to open a new session.|Reset password.|
|Terminate a session and block access to future sessions (for all protocols).|Disable the account, for example, in the Exchange admin center or using PowerShell: <p>  `Set-Mailbox user@contoso.com -AccountDisabled:$true`.|
|Terminate the session for a particular protocol (such as ActiveSync).|Disable the protocol, for example, in the Exchange admin center or using PowerShell: <p>  `Set-CASMailbox user@contoso.com -ActiveSyncEnabled:$false`.|
```

2023-09-30 09:07 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-1.md
> +The above operations can be done in three places:
```suggestion

These operations can be done in three different places:
```

2023-09-30 09:07 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-1.md
> +****
```suggestion
```

2023-09-30 09:07 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-1.md
> +
```suggestion
|If you terminate the session here|How long does it take|
|---|---|
|In the Exchange admin center or using PowerShell.|Expected delay is approximately 30 minutes.|
|In the Azure Active Directory admin center.|Expected delay is 60 minutes.|
|In an on-premises environment.|Expected delay is 3 hours or more.|
```

2023-09-30 09:08 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-01 07:45 UTC, JohanFreelancer9 approved these changes

2023-10-02 14:22 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2023-11-20 13:29 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2025-10-23 15:46 UTC, v-jmathew commented
This PR has been open for an extended period of time and has conflicts. If these changes are still relevant, please re-submit them to https://github.com/MicrosoftDocs/microsoft-365-docs-pr/.

2025-10-23 15:46 UTC, closed without merging