Update configure-server-endpoints.md
MicrosoftDocs/microsoft-365-docs pull request #12919
Opened 2023-10-09 12:33 UTC by msbemba

updated the heading to reduce ambiguity as the steps are used only when using installer scripts

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12885

2023-10-09 12:34 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-09 13:56 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-server-endpoints.md
> +## Apply the Microsoft Defender for Endpoint installation and onboarding packages using Group policy when performing the installation with an installer script.
```suggestion
## Apply the Microsoft Defender for Endpoint installation and onboarding packages using Group policy when performing the installation with an installer script
```

2023-10-09 13:57 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-09 15:47 UTC, JohanFreelancer9 approved these changes

2023-10-10 11:32 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2023-11-20 13:27 UTC, yogkumgit commented
@mjcaparas Gentle reminder.

2024-04-18 14:46 UTC, merged