Update defender-vulnerability-management-capabilities.md
MicrosoftDocs/microsoft-365-docs pull request #12960
Opened 2023-10-13 18:11 UTC by msbemba

Made changes to the note

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12929

2023-10-13 18:11 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-14 04:38 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities.md
>  - For new customers or existing Defender for Endpoint P1 or Microsoft 365 E3 customer the **Microsoft Defender Vulnerability Management Standalone is now generally available**. To try it, go to [Try
```suggestion
- For new customers or existing Defender for Endpoint P1 or Microsoft 365 E3 customers the **Microsoft Defender Vulnerability Management Standalone is now generally available**. To try it, go to [Try Defender Vulnerability Management Standalone](/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management#try-defender-vulnerability-management-standalone).
```

2023-10-14 04:39 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, one additional edit, please.

2023-10-16 13:08 UTC, yogkumgit commented
@JohanFreelancer9

2023-10-16 13:09 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2023-10-17 11:02 UTC, JohanFreelancer9 approved these changes

2023-11-20 13:25 UTC, yogkumgit commented
@siosulli Gentle reminder.

2024-04-18 14:51 UTC, closed without merging