Update project-activity.md
MicrosoftDocs/microsoft-365-docs pull request #12961
Opened 2023-10-13 18:52 UTC by msbemba

Fixes Projects visited(web) description
Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12928

2023-10-13 18:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-14 04:25 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/project-activity.md
> +|Projects visited (Web)| The number of Projects visited by the user in Project for the Web during the time range selected in the top right of the page.|
```suggestion
|Projects visited (Web)| The number of projects visited by the user in Project for the Web during the time range selected in the top right of the page.|
```

2023-10-14 04:25 UTC, JohanFreelancer9 requested changes
Copy reciew.

2023-10-14 05:12 UTC, JohanFreelancer9 approved these changes

2023-10-16 13:11 UTC, yogkumgit commented
@camillepack Please merge this PR. Thanks

2023-10-16 16:34 UTC, merged