Update feedback.png
MicrosoftDocs/microsoft-365-docs pull request #12970
Opened 2023-10-16 16:35 UTC by msbemba

Fixed the Screenshot for feedback

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12939

2023-10-16 16:39 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-17 10:50 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/feedback.md
> +1. From the home page of Microsoft Defender, select **Give feedback** and click on **Leave Feedback**.
```suggestion
1. From the Microsoft Defender home page, select **Give feedback** and then select **Leave Feedback**. 
```

2023-10-17 10:50 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-17 11:19 UTC, yogkumgit commented
@JohanFreelancer9

2023-10-17 11:20 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2023-10-17 13:48 UTC, JohanFreelancer9 approved these changes

2023-11-20 13:24 UTC, yogkumgit commented
@mjcaparas Gentle reminder.

2024-04-26 19:06 UTC, Dansimp commented
udpated in private PR. To be published soon.

2024-04-26 19:06 UTC, closed without merging