Update create-signatures-and-disclaimers.md
MicrosoftDocs/microsoft-365-docs pull request #12973
Opened 2023-10-16 17:24 UTC by msbemba

Added sender property details to the rule 

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12954

2023-10-16 17:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-17 10:24 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/create-signatures-and-disclaimers.md
> +1. Select ***Header** under the **Match sender address in message** drop down and click **Next** and **Finish**
```suggestion
1. Select ***Header** under the **Match sender address in message** drop-down and then select **Next** and **Finish**.
```

2023-10-17 10:25 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-17 11:09 UTC, yogkumgit commented
@JohanFreelancer9

2023-10-17 11:10 UTC, yogkumgit commented
@twernermsft Please merge this PR. Thanks

2023-10-17 13:50 UTC, JohanFreelancer9 approved these changes

2023-10-20 22:09 UTC, merged