Update what-the-sensitive-information-types-look-for.md
MicrosoftDocs/microsoft-365-docs pull request #1300
Opened 2020-02-26 17:32 UTC by msbemba

Corrected credit card format. After testing.

2020-02-26 17:32 UTC, msbemba commented
Issue# https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1268

2020-02-27 02:22 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-02-27 03:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/what-the-sensitive-information-types-look-for.md
> +14 to 16 digits which can be formatted or unformatted (dddddddddddddddd) and must pass the Luhn test.
```suggestion
14 to 16 digits which can be formatted or unformatted (dddddddddddddddd) and which must pass the Luhn test.
```

2020-02-27 03:55 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-02-28 00:36 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #1268.

Thank you.

cc: @kenwith

2020-03-03 20:47 UTC, merged