Update domains-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #13017
Opened 2023-10-24 14:14 UTC by msbemba

Made a few changes to default domain section updates

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12983

2023-10-24 14:14 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-24 15:40 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/domains-faq.yml
> +          For information on adding or replacing an onmicrosoft.com domain, please [see here](/admin/setup/add-or-replace-your-onmicrosoftcom-domain)
```suggestion
          For information about adding or replacing an onmicrosoft.com domain, see [Add or replace your onmicrosoft.com domain](/admin/setup/add-or-replace-your-onmicrosoftcom-domain).
```

2023-10-24 15:42 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/domains-faq.yml
> +          > and login credentials.
```suggestion
          > Changing the default domain affects new accounts only. This change does not impact user credentials or their access to applications or services. Removing or changing a domain on an account can impact mail, online storage, and login credentials.
```

2023-10-24 15:42 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-25 04:32 UTC, JohanFreelancer9 approved these changes

2023-10-25 13:33 UTC, yogkumgit commented
@nataliekagole Please merge this PR. Thanks

2023-10-25 14:49 UTC, JohanFreelancer9 approved these changes

2023-11-20 13:22 UTC, yogkumgit commented
@nataliekagole Gentle reminder.

2025-04-14 20:31 UTC, merged