Update cross-tenant-onedrive-migration.md
MicrosoftDocs/microsoft-365-docs pull request #13110
Opened 2023-11-07 14:39 UTC by wonderboy703

This needs to be clear. The term create can be convoluted with pre-create. The term pre-provision appears to be what they are referring to which refers to a user clicking on OneDrive or a URL pre-provisioned by script.

2023-11-07 14:44 UTC, wonderboy703 reviewed
I've tried using /sharepoint/pre-provision-accounts and this also cause the bot to error out.

2023-11-08 06:46 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-onedrive-migration.md
> +> OneDrive sites should **NOT** be created [Pre-Provisioned](https://learn.microsoft.com/en-us/sharepoint/pre-provision-accounts) before **OR** during a migration.
```suggestion
> OneDrive sites should **NOT** be created ([pre-provisioned](/sharepoint/pre-provision-accounts)) before **OR** during a migration.
```

2023-11-08 06:47 UTC, JohanFreelancer9 requested changes
Copy review - @wonderboy703, kindly commit the suggested change. Many thanks.

2023-11-08 17:49 UTC, wonderboy703 commented
#sign-out

2023-11-09 05:05 UTC, JohanFreelancer9 approved these changes

2023-11-20 13:44 UTC, yogkumgit commented
@JoanneHendrickson Please merge this PR. Thanks

2025-10-23 15:42 UTC, v-jmathew commented
Closing as GitHub account of the submitter not found.

2025-10-23 15:42 UTC, closed without merging