Update configure-email-forwarding.md
MicrosoftDocs/microsoft-365-docs pull request #13141
Opened 2023-11-14 13:15 UTC by msbemba

Fixed the related article

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/13083

2023-11-14 13:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-11-14 14:54 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/configure-email-forwarding.md
> +[Forward emails that are sent to a shared mailbox](https://learn.microsoft.com/microsoft-365/admin/email/configure-a-shared-mailbox?view=o365-worldwide#forward-emails-that-are-sent-to-a-shared-mailbo
```suggestion
[Forward emails that are sent to a shared mailbox](/microsoft-365/admin/email/configure-a-shared-mailbox#forward-emails-that-are-sent-to-a-shared-mailbox) (article)\
```

2023-11-14 14:54 UTC, JohanFreelancer9 requested changes
Copy review.

2023-11-14 15:51 UTC, JohanFreelancer9 approved these changes

2023-11-15 08:11 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-11-15 13:14 UTC, merged