Update deploy-manage-removable-storage-group-policy.md
MicrosoftDocs/microsoft-365-docs pull request #13146
Opened 2023-11-14 14:41 UTC by msbemba

added more information to the license requirements

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/13113

2023-11-14 14:41 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-11-15 06:56 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-group-policy.md
> +Before you get started with Removable Storage Access Control, you must confirm your [Microsoft 365 subscription](https://www.microsoft.com/microsoft-365/compare-microsoft-365-enterprise-plans?rtc=2).
```suggestion
Before you get started with Removable Storage Access Control, you must confirm your [Microsoft 365 subscription](https://www.microsoft.com/microsoft-365/compare-microsoft-365-enterprise-plans?rtc=2). To access and use Removable Storage Access Control through group policy, you must have a standalone Microsoft Defender for Endpoint Plan 1 or Microsoft 365 E3 which includes Microsoft Defender for Endpoint Plan 1 or Microsoft 365 E5 which includes Microsoft Defender for Endpoint Plan 1 and 2.
```

2023-11-15 06:56 UTC, JohanFreelancer9 requested changes
Copy review.

2023-11-15 08:32 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2023-11-20 13:40 UTC, yogkumgit commented
@msbemba

2023-11-22 00:51 UTC, merged