Update advanced-hunting-query-results.md
MicrosoftDocs/microsoft-365-docs pull request #13176
Opened 2023-11-16 17:51 UTC by msbemba

Updated |render syntax as it was in screenshot

fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/13161

2023-11-16 17:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-11-17 07:43 UTC, JohanFreelancer9 approved these changes

2023-11-17 12:29 UTC, yogkumgit commented
@schmurky Please merge this PR. Thanks

2023-11-20 12:52 UTC, schmurky requested changes

2023-11-20 12:52 UTC, schmurky commented on microsoft-365/security/defender/advanced-hunting-query-results.md
> +| render coloumnchart
col**o**umnchart > columnchart

Once this is changed, it should be good to go.

2023-11-20 13:17 UTC, yogkumgit commented
@msbemba

2023-11-27 01:52 UTC, msbemba commented
Thank you @schmurky . I have made the changes as per the request.

2023-11-28 14:08 UTC, schmurky approved these changes

2023-11-28 14:09 UTC, merged

2023-11-28 14:09 UTC, schmurky commented
[like]  Macky Cruz reacted to your message:
________________________________
From: Sriraman M S ***@***.***>
Sent: Monday, November 27, 2023 1:52:24 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Macky Cruz ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update advanced-hunting-query-results.md (PR #13176)


Thank you @schmurky<https://github.com/schmurky> . I have made the changes as per the request.

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13176#issuecomment-1827009641>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AP2G3G747AOX2SDP4SN5M6TYGPW5RAVCNFSM6AAAAAA7ORYLK2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRXGAYDSNRUGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>