Update live-response.md
MicrosoftDocs/microsoft-365-docs pull request #13256
Opened 2023-11-30 15:23 UTC by msbemba

Changed description for scan

Fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/13206

2023-11-30 15:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-12-01 04:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/live-response.md
> +| scan | Runs an Quick antivirus scan to help identify and remediate malware. | N | Y | Y |
```suggestion
| scan | Runs a Quick antivirus scan to help identify and remediate malware. | N | Y | Y |
```

2023-12-01 04:46 UTC, JohanFreelancer9 requested changes
Copy review.

2023-12-01 05:48 UTC, yogkumgit commented
@diannegali Please merge this PR. Thanks

2023-12-04 11:24 UTC, merged