made (or at least tried to make) description less confusing
MicrosoftDocs/microsoft-365-docs pull request #1349
Opened 2020-03-03 06:28 UTC by MaratMussabekov

#1270

2020-03-08 15:12 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-03-09 07:40 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md
> +|**Advanced phishing thresholds**|Defines the level of settings for how phishing messages are handled.  <br/> **Standard** Email suspected to be phish is handled in the standard way.  <br/> **Aggress
```suggestion
|**Advanced phishing thresholds**|Defines the level of settings for how phishing messages are handled.  <br/> **Standard**: Email suspected to be phish is handled in the standard way.  <br/> **Aggressive**: The system handles emails suspected to be phish with a high degree of confidence the same way as those suspected with very high degree of confidence.  <br/> **More aggressive**: The system handles emails suspected to be phish with a medium or high degree of confidence the same way as those suspected with very high degree of confidence.  <br/> **Most aggressive**: The system handles emails suspected to be phish with a low, medium, or high degree of confidence the same way as those suspected with very high degree of confidence.|When you want to be more aggressive in the treatment of potentially phishing messages within Office 365. For example, messages with a very high probability of being phish will have the most aggressive actions taken on them while messages with a low probability have less aggressive actions taken on them. This setting also impacts other parts of the filtering system that combine signals. This doesn't necessarily mean different actions are implemented.  Essentially you set the probability of mail being phish, to determine the (same) designated action. The chance of moving good messages increases as the level of settings increases.|
```

2020-03-09 07:55 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md
>  |**Enable mailbox intelligence based impersonation protection**|Enables or disables mailbox intelligence for impersonation protection for this policy. The important here is the control of the imperso
```suggestion
|**Enable mailbox intelligence based impersonation protection**|Enables or disables mailbox intelligence for impersonation protection for this policy. The important aspect here is the control of the impersonation for a given mailbox.|When you want to enhance impersonation results for users based on each user's individual sender map. This intelligence allows Office 365 to customize user impersonation detection and better handle false positives. When user impersonation is detected, based on mailbox intelligence, you can define what action to take on the message.|
```

2020-03-09 07:55 UTC, JohanFreelancer9 requested changes
Copy review.

2020-03-09 08:39 UTC, JohanFreelancer9 approved these changes

2020-03-09 23:09 UTC, mypil commented
@MSFTTracyP - PR has been copy edited and is ready for final review. This is based on issue #1270.

Thank you.

cc: @kenwith

2020-03-11 16:48 UTC, MSFTTracyP reviewed
Thanks

2020-03-11 16:49 UTC, merged