added reference to the Group owner field
MicrosoftDocs/microsoft-365-docs pull request #1404
Opened 2020-03-11 13:46 UTC by MaratMussabekov

#1248

2020-03-11 21:49 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-03-12 02:28 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/deploy-an-isolated-sharepoint-online-team-site.md
> +> Group owner is automatically included as site admin, therefore can manage group membership and have full access to the site.
```suggestion
> Group owner is automatically included as a site admin and can therefore manage group membership and have full access to the site. 
```

2020-03-12 02:28 UTC, JohanFreelancer9 requested changes
Copy review - only a suggestion.

2020-03-12 19:32 UTC, MikePlumleyMSFT commented
The issue actually is that the procedure should *not* include creating an Office 365 group. I have a separate PR in the queue to update the procedure.

2020-03-12 19:32 UTC, closed without merging