note addition
MicrosoftDocs/microsoft-365-docs pull request #1420
Opened 2020-03-12 11:19 UTC by joinimran

Based on user feedback, I have added a note.

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1222

2020-03-12 11:19 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-03-12 17:40 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-loss-prevention-policies.md
> +> The default behavior of a DLP policy when there is no alert configured is not to alert or trigger. This applies only with default information types. For custom information types system will alert e
```suggestion
> The default behavior of a DLP policy, when there is no alert configured, is not to alert or trigger. This applies only to default information types. For custom information types, the system will alert even if there is no action defined in the policy.
```

2020-03-12 17:42 UTC, JohanFreelancer9 requested changes
Copy review.

2020-03-13 05:21 UTC, JohanFreelancer9 approved these changes

2020-03-13 22:34 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #1222.

Thank you.

cc: @kenwith

2020-03-18 21:56 UTC, merged