Update set-up-atp-safe-links-policies.md
MicrosoftDocs/microsoft-365-docs pull request #1455
Opened 2020-03-20 21:26 UTC by msbemba

added more information on safelinks

2020-03-20 22:23 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-03-21 01:43 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md
> +With ATP Safe Links enabled, if a user clicks on a link in an email and the URL has been blocked by your organization’s custom blocked URL list or if the URL is determined to be malicious, then a war
```suggestion
With ATP Safe Links enabled, if a user clicks on a link in an email and the URL has been blocked by your organization’s custom blocked URL list or if the URL is determined to be malicious, a warning page will open.
```

2020-03-21 01:43 UTC, JohanFreelancer9 requested changes
Copy review.

2020-03-21 14:03 UTC, JohanFreelancer9 approved these changes

2020-03-21 14:27 UTC, mypil commented
@MSFTTracyP - PR has been copy edited and is ready for final review. This is based on issue #1289.

Thank you.

cc: @kenwith

2020-03-23 22:05 UTC, merged