Update customer-key-set-up.md
MicrosoftDocs/microsoft-365-docs pull request #1484
Opened 2020-03-25 00:52 UTC by brdesai

Updated licensing information based on SKU changes from Marketing. The changes to go live on April 1, 2020.

2020-03-25 22:43 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-03-25 23:59 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> +Before you get started, ensure that you have the appropriate licensing for your organization. Starting 1st April 2020, Customer Key in Office 365 is offered in M365 E5 or E5 Compliance SKU. Office 36
```suggestion
Before you get started, ensure that you have the appropriate licensing for your organization. Starting April 1, 2020, Customer Key in Office 365 is offered in M365 E5 or E5 Compliance SKU. Office 365 Advanced Compliance SKU is no longer available for procuring new licenses. Customers with existing Office 365 Advanced Compliance licenses will continue to be supported.  
```

2020-03-26 00:06 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> +To understand the concepts and procedures in this topic, review the [Azure Key Vault](https://docs.microsoft.com/azure/key-vault/) documentation. Also, become familiar with the terms used in Azure, f
```suggestion
To understand the concepts and procedures in this topic, review the [Azure Key Vault](https://docs.microsoft.com/azure/key-vault/) documentation. Also, become familiar with the terms used in Azure, for example, [Azure AD tenant](https://docs.microsoft.com/previous-versions/azure/azure-services/jj573650(v=azure.100)#what-is-an-azure-ad-tenant).
```

2020-03-26 00:07 UTC, JohanFreelancer9 requested changes
Copy review.

2020-03-31 01:39 UTC, mypil commented
@brdesai  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-04-01 19:49 UTC, brdesai commented
Suggested changes have been committed.

2020-04-02 01:50 UTC, JohanFreelancer9 approved these changes

2020-04-02 20:07 UTC, brdesai commented
@KCCross, @JohanFreelancer9  Do you want me to close the pull request or are you going to do it.

2020-04-02 23:04 UTC, brdesai commented
@KCCross, @JohanFreelancer9  I'd to make one more commit to update the list of supported SKUs based on the discussion with PMM.

2020-04-03 19:23 UTC, shilpabothra reviewed
Should we add something along the lines of: 
We will stop selling the Office 365 Advanced Compliance as a standalone subscription. When current subscriptions expire, customers should transition to one of the subscriptions above. We are not discontinuing any of the existing compliance features.

2020-04-03 23:01 UTC, KCCross requested changes
We are speaking to customers in this content so we do not say customers :) So, modify the text starting with "Starting April 1" and ending with "to be supported" as follows:

Starting April 1, 2020, Customer Key in Office 365 is offered in Office 365 E5, M365 E5, M365 E5 Compliance and M365 E5 Information Protection & Governance SKUs. Office 365 Advanced Compliance SKU is no longer available for procuring new licenses. Existing Office 365 Advanced Compliance licenses will continue to be supported.

2020-04-04 03:20 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> +Before you get started, ensure that you have the appropriate licensing for your organization. Starting April 1, 2020, Customer Key in Office 365 is offered in Office 365 E5, M365 E5, M365 E5 Complian
```suggestion
Before you get started, ensure that you have the appropriate licensing for your organization. Starting April 1, 2020, Customer Key in Office 365 is offered in Office 365 E5, M365 E5, M365 E5 Compliance, and M365 E5 Information Protection & Governance SKUs. Office 365 Advanced Compliance SKU is no longer available for procuring new licenses. Customers with existing Office 365 Advanced Compliance licenses will continue to be supported.  
```

2020-04-04 03:21 UTC, JohanFreelancer9 requested changes
Copy review - minor edit. Please add a comma as indicated.

2020-04-04 23:16 UTC, brdesai commented
@KCCross , @JohanFreelancer9 The changes have been made, take a look and do the needful to merge the changes. Thanks.

2020-04-05 00:59 UTC, JohanFreelancer9 approved these changes

2020-04-07 01:17 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review.

Thank you.

cc: @kenwith

2020-04-10 00:17 UTC, merged

2020-09-01 18:08 UTC, KCCross commented
I'm concerned at how these did not make it live after the PR was merged. Please verify the accuracy against the new service description release in June.