Update create-edit-or-delete-a-custom-user-view.md
MicrosoftDocs/microsoft-365-docs pull request #1505
Opened 2020-03-27 21:57 UTC by msbemba

Added note on scenarios for unlicensed users with exchange mailboxes

2020-03-27 21:57 UTC, msbemba commented
Issue# https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1348

2020-03-27 21:57 UTC, msbemba commented
Issue# https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1348

2020-03-27 22:26 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-03-28 00:06 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/create-edit-or-delete-a-custom-user-view.md
> +> The unlicnesed users with exchange mailboxes works under the following situaions
```suggestion
> The **Unlicensed users with Exchange mailboxes** filter works in the following scenarios:
```

2020-03-28 00:08 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/create-edit-or-delete-a-custom-user-view.md
> +1. The mailbox has been recently converted from shared to user and it has no license.
```suggestion
1. The mailbox has been recently converted from **shared** to **user** and it has no license.
```

2020-03-28 00:09 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/create-edit-or-delete-a-custom-user-view.md
> +2. The mailbox has been recently migrated to O365 but license has not been assigned.
```suggestion
2. The mailbox has been recently migrated to Office 365 but a license has not been assigned.
```

2020-03-28 00:09 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/create-edit-or-delete-a-custom-user-view.md
> +3. The mailbox has been created using powershell, and a license has not been assigned.
```suggestion
3. The mailbox has been created using PowerShell, and a license has not been assigned.
```

2020-03-28 00:15 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/create-edit-or-delete-a-custom-user-view.md
> +4. A new mailbox is provisioned for user created on-premise with New-RemoteMailbox cmdlet.
```suggestion
4. A new mailbox that has been created on-premise with a New-RemoteMailbox cmdlet is provisioned for the user.
```

2020-03-28 00:32 UTC, JohanFreelancer9 requested changes
Copy review.

2020-03-28 11:46 UTC, mypil commented
@msbemba  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-03-28 14:38 UTC, JohanFreelancer9 approved these changes

2020-03-28 14:55 UTC, mypil commented
@kwekuako - PR has been copy edited and is ready for final review. This is based on issue #1348.

Thank you.

cc: @kenwith

2020-03-28 22:51 UTC, merged