update doc to make sure mail is routed both ways
MicrosoftDocs/microsoft-365-docs pull request #1538
Opened 2020-04-01 17:22 UTC by samschan-ms

@KCCross  please review

2020-04-01 20:09 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-02 01:57 UTC, JohanFreelancer9 commented on microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md
> +> For hybrid Exchange environments, on-premises users can send and receive encrypted mail using OME only if email is routed through Exchange Online. To configure OME in a hybrid Exchange environment,
```suggestion
> For hybrid Exchange environments, on-premises users can send and receive encrypted mail using OME only if email is routed through Exchange Online. To configure OME in a hybrid Exchange environment, you need to first [configure hybrid using the Hybrid Configuration wizard](https://docs.microsoft.com/Exchange/exchange-hybrid) and then [configure mail to flow between your email server and Office 365](https://docs.microsoft.com/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail#part-2-configure-mail-to-flow-from-your-email-server-to-office-365). Once you've configured mail to flow through Office 365, you can configure mail flow rules for OME by using this guidance.
```

2020-04-02 02:00 UTC, JohanFreelancer9 requested changes
Copy review - please remove the locale from the link and remove the word "then" from the last sentence.

2020-04-05 16:36 UTC, mypil commented
@samschan-ms - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-04-06 07:12 UTC, JohanFreelancer9 approved these changes

2020-04-07 00:42 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

2020-04-07 18:30 UTC, samschan-ms commented
@KCCross  I've added one more link to setup incoming mail flow.

2020-04-29 19:52 UTC, merged