add note about 21Vianet
MicrosoftDocs/microsoft-365-docs pull request #1566
Opened 2020-04-03 16:53 UTC by VLG17

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1406

2020-04-03 20:40 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-04 04:24 UTC, JohanFreelancer9 requested changes
Copy review - please note; the asterisk is displayed as a bullet point in rich text view.

2020-04-04 08:45 UTC, VLG17 commented
> Copy review - please note; the asterisk is displayed as a bullet point in rich text view.

@JohanFreelancer9 how can i make it show as asterisk then? Could you help me with that please?

2020-04-05 01:35 UTC, JohanFreelancer9 commented on microsoft-365/admin/dns/create-dns-records-at-cloudflare.md
> +    |CNAME  <br/> |msoid*  <br/> |clientconfig.microsoftonline-p.net  <br/> |30 minutes  <br/> |
```suggestion
    |CNAME  <br/> |msoid<sup>1</sup>  <br/> |clientconfig.microsoftonline-p.net  <br/> |30 minutes  <br/> |
```

2020-04-05 01:38 UTC, JohanFreelancer9 commented on microsoft-365/admin/dns/create-dns-records-at-cloudflare.md
> +* Applies to Office 365 operated by 21Vianet.
```suggestion
<sup>**1**</sup> Applies to Office 365 operated by 21Vianet.
```

2020-04-05 01:42 UTC, JohanFreelancer9 requested changes
@VLG17  My suggestion.

2020-04-05 13:57 UTC, mypil commented
@VLG17 - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-04-06 01:40 UTC, JohanFreelancer9 commented on microsoft-365/admin/dns/create-dns-records-at-cloudflare.md
> +<sup>**1**</sup> Applies to Office 365 operated by 21Vianet.
```suggestion
     <sup>**1**</sup> Applies to Office 365 operated by 21Vianet.
```

2020-04-06 01:49 UTC, JohanFreelancer9 requested changes
Apologies @VLG17 . Please add spaces.

2020-04-07 00:23 UTC, mypil commented
@pebaum - PR has been copy edited and is ready for final review. This is based on issue #1406. 

Thank you.


cc: @kenwith

2020-04-27 19:09 UTC, pebaum commented
We've decided not to include this guidance for clarity in the global walkthrough articles based on customer and engineering feedback.

2020-04-27 19:09 UTC, closed without merging