add note containing useful link
MicrosoftDocs/microsoft-365-docs pull request #1568
Opened 2020-04-03 18:07 UTC by VLG17

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1402

2020-04-03 20:42 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-04 04:12 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/manage-creation-of-groups.md
> +> Check [this article](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/license-users-groups) for more details about how to assign Azure licenses.
```suggestion
> See [Assign or remove licenses in the Azure Active Directory portal](https://docs.microsoft.com/azure/active-directory/fundamentals/license-users-groups) for more details about how to assign Azure licenses.
```

2020-04-04 04:13 UTC, JohanFreelancer9 requested changes
Copy review.

2020-04-04 17:13 UTC, mypil commented
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #1402.

Thank you.

cc: @kenwith

2020-04-04 17:14 UTC, mypil commented
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #1402.

Thank you.

cc: @kenwith

2020-04-17 12:07 UTC, merged