Updated to clarify cloud mailbox requirements
MicrosoftDocs/microsoft-365-docs pull request #1571
Opened 2020-04-03 18:40 UTC by RossAdams

Add details that some settings require a cloud mailbox

2020-04-03 20:44 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-04 03:46 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md
> +     > These settings are only applicable to cloud based mailboxes.
```suggestion
     > These settings are only applicable to cloud-based mailboxes.
```

2020-04-04 03:53 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-04-04 17:46 UTC, mypil commented
@RossAdams  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-04-20 20:58 UTC, merged