Update restore-deleted-group.md
MicrosoftDocs/microsoft-365-docs pull request #1609
Opened 2020-04-12 05:14 UTC by msbemba

Corrected Admin to administrator

2020-04-12 05:14 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1542

2020-04-12 12:16 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-12 13:30 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/restore-deleted-group.md
>  1. Go to the admin center at [https://admin.microsoft.com](Go to the admin center at https://admin.microsoft.com).
```suggestion
1. Go to the [admin center](https://admin.microsoft.com).
```

2020-04-12 13:31 UTC, JohanFreelancer9 requested changes
Copy review.

2020-04-13 01:54 UTC, JohanFreelancer9 approved these changes

2020-04-13 21:11 UTC, mypil commented
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #1542. 

Thank you.

cc: @kenwith

2020-04-17 12:10 UTC, merged