Update delete-a-user.md
MicrosoftDocs/microsoft-365-docs pull request #1666
Opened 2020-04-18 19:02 UTC by D3Design

Fixes #1585

2020-04-18 20:36 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-19 02:38 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/delete-a-user.md
> +**IMPORTANT**: Don't delete a user's account if you've [converted it to a shared mailbox](../email/convert-user-mailbox-to-shared-mailbox.md) or if you've set up email forwarding on the account. Thos
```suggestion
> [!IMPORTANT]
> Don't delete a user's account if you've [converted it to a shared mailbox](../email/convert-user-mailbox-to-shared-mailbox.md) or if you've set up email forwarding on the account. Those functions need the account to remain. A shared mailbox does not require a user license. If you've converted the account to a shared mailbox you can [Stop paying for the license](#stop-paying-for-the-license). If you have set up email forwarding on the account, you cannot remove the license. Doing so will stop email forwarding and deactivate the mailbox.
```

2020-04-19 02:39 UTC, JohanFreelancer9 reviewed
Copy review - suggestion. Also add spaces after periods.

2020-04-19 12:11 UTC, mypil commented
@D3Design  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-04-19 15:30 UTC, mypil commented
@cmcatee-MSFT - PR has been copy edited and is ready for final review. This is based on issue #1585.

Thank you.

cc: @kenwith

2020-04-20 18:11 UTC, cmcatee-MSFT requested changes
Please update with edited paragraph as indicated. Thanks.

2020-04-20 18:11 UTC, cmcatee-MSFT commented on microsoft-365/admin/add-users/delete-a-user.md
> +> Don't delete a user's account if you've [converted it to a shared mailbox](../email/convert-user-mailbox-to-shared-mailbox.md) or if you've set up email forwarding on the account. Those functions n
> Don't delete a user's account if you've [converted it to a shared mailbox](../email/convert-user-mailbox-to-shared-mailbox.md) or if you've set up email forwarding on the account. Those functions still need the account. A shared mailbox doesn't require a license. If you've converted the account to a shared mailbox you can [stop paying for the license](#stop-paying-for-the-license). If you've set up email forwarding on the account, you can't remove the license. Doing so will stop email forwarding and deactivate the mailbox.

2020-04-20 19:04 UTC, merged