Update view-reports-for-atp.md
MicrosoftDocs/microsoft-365-docs pull request #1750
Opened 2020-04-25 07:55 UTC by ruiwensu

URL report - detail view is actually in real time, but aggregate view is not. Also, there's no need to use URL Trace since the details view provides the same capabilities that URL Trace does.

2020-04-25 11:59 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-25 13:27 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-reports-for-atp.md
> +> This is a *protection trend report*, meaning data represents trends in a larger dataset. As a result, the data in the aggregate view is not available in real time here, but the data in the details
```suggestion
> This is a *protection trend report*, meaning data represents trends in a larger dataset. As a result, the data in the aggregate view is not available in real time here, but the data in the details table view is, so you may see a slight discrepancy between the two views.
```

2020-04-25 13:27 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-04-26 12:07 UTC, mypil commented
@ruiwensu  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-04-27 07:28 UTC, JohanFreelancer9 approved these changes

2020-04-29 00:16 UTC, mypil commented
@MSFTTracyP - PR has been copy edited and is ready for final review. 


Thank you.

cc: @kenwith

2020-05-08 16:18 UTC, merged