As discussed, added clarifications on header names based on customer comments during webinar
MicrosoftDocs/microsoft-365-docs pull request #1751
Opened 2020-04-25 09:10 UTC by Esaggese

…h-based-classification.md
@chrfox

2020-04-25 11:59 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-25 13:32 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md
> +2. Structure the sensitive data in the .csv file such that the first row includes the names of the fields used for EDM-based classification. In your .csv file, you might have field names, such as "ss
```suggestion
2. Structure the sensitive data in the .csv file such that the first row includes the names of the fields used for EDM-based classification. In your .csv file, you might have field names, such as "ssn", "birthdate", "firstname", "lastname", and so on. Please note that column headers can't include spaces or underscores in their names. As an example, our .csv file is called *PatientRecords.csv*, and its columns include *PatientID*, *MRN*, *LastName*, *FirstName*, *SSN*, and more.
```

2020-04-25 13:33 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-04-26 12:08 UTC, mypil commented
@Esaggese  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-04-28 20:44 UTC, merged