Update office-365-encryption-for-skype-onedrive-sharepoint-and-exchan…
MicrosoftDocs/microsoft-365-docs pull request #1768
Opened 2020-04-28 00:02 UTC by msbemba

…ge.md

Added teams to the list with more details

2020-04-28 00:02 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1651

2020-04-28 21:31 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-29 02:59 UTC, JohanFreelancer9 commented on microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md
> +# Encryption for Skype for Business, OneDrive for Business, SharePoint Online, Microsoft Teams and Exchange Online
```suggestion
# Encryption for Skype for Business, OneDrive for Business, SharePoint Online, Microsoft Teams, and Exchange Online
```

2020-04-29 03:01 UTC, JohanFreelancer9 commented on microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md
>  description: "Summary: A description of encryption for Skype, OneDrive, SharePoint, and Exchange Online."
```suggestion
description: "Summary: A description of encryption for Skype, OneDrive, SharePoint, Microsoft Teams, and Exchange Online."
```

2020-04-29 03:17 UTC, JohanFreelancer9 commented on microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md
> +Media traffic is encrypted using Secure RTP (SRTP), a profile of Real-Time Transport Protocol (RTP) that provides confidentiality, authentication, and replay attack protection to RTP traffic. SRTP us
```suggestion
Media traffic is encrypted using Secure RTP (SRTP), a profile of Real-Time Transport Protocol (RTP) that provides confidentiality, authentication, and replay attack protection to RTP traffic. SRTP uses a session key generated by using a secure random number generator and exchanged using the signaling TLS channel. Client to client media traffic is negotiated through a client to server connection signaling but is encrypted using SRTP when going direct client to client.
```

2020-04-29 03:25 UTC, JohanFreelancer9 requested changes
Copy review.

2020-04-29 13:42 UTC, JohanFreelancer9 approved these changes

2020-04-29 23:38 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review. This is based on issue #1651.

Thank you.

cc: @kenwith

2020-05-24 19:30 UTC, mypil commented
@KCCross - We would like to follow up. Can you please assist to review and merge this PR?

Thank you.

2020-06-12 17:08 UTC, merged