Update encryption.md
MicrosoftDocs/microsoft-365-docs pull request #1769
Opened 2020-04-28 00:14 UTC by msbemba

Added Teams to the list

2020-04-28 00:15 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1650

2020-04-28 21:31 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-29 02:52 UTC, JohanFreelancer9 commented on microsoft-365/compliance/encryption.md
> +|Chats, Messages and Files in transit between recipients using Microsoft teams <br/> |Teams uses TLS and MTLS to encrypt instant messages. Media traffic is encrypted using Secure RTP (SRTP). Teams us
```suggestion
|Chats, messages and files in transit between recipients using Microsoft Teams <br/> |Teams uses TLS and MTLS to encrypt instant messages. Media traffic is encrypted using Secure RTP (SRTP). Teams uses FIPS (Federal Information Processing Standard) compliant algorithms for encryption key exchanges <br/> |[Encryption for Teams](https://docs.microsoft.com/microsoftteams/teams-security-guide#encryption-for-teams) <br/> |
```

2020-04-29 02:57 UTC, JohanFreelancer9 requested changes
Copy review.

2020-04-29 13:45 UTC, JohanFreelancer9 approved these changes

2020-04-29 23:36 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review. This is based on issue #1650.

Thank you.

cc: @kenwith

2020-05-24 19:29 UTC, mypil commented
@KCCross - We would like to follow up. Can you please assist to review and merge this PR?

Thank you.

2020-06-12 17:09 UTC, merged