- fixes typo in conditional access page
MicrosoftDocs/microsoft-365-docs pull request #1771
Opened 2020-04-28 14:57 UTC by baywet

2020-04-28 21:31 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-04-29 02:42 UTC, JohanFreelancer9 commented on microsoft-365/business/set-up-conditional-access-policies.md
> +Microsoft recommends you enable all of these baseline policies. After these policies are enabled, admins and users will be prompted to register for Azure Multi-Factor authentication.
```suggestion
We recommend you enable all of these baseline policies. After these policies are enabled, admins and users will be prompted to register for Azure Multi-Factor authentication.
```

2020-04-29 02:45 UTC, JohanFreelancer9 requested changes
Copy review - additional edit; "Microsoft recommends" should not be used.

2020-04-29 13:45 UTC, JohanFreelancer9 approved these changes

2020-04-29 23:35 UTC, mypil commented
@Sirkkuw - PR has been copy edited and is ready for final review. 


Thank you.

cc: @kenwith

2020-05-19 22:30 UTC, merged