Update incorrect licensing statement
MicrosoftDocs/microsoft-365-docs pull request #1789
Opened 2020-04-30 08:07 UTC by Weishaupt

According to Footnote 2 on the [Exchange Online Service Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#storage-limits) shared mailboxes require a license in three defined cases.

2020-04-30 21:31 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-01 02:30 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/remove-license-from-shared-mailbox.md
> +> A license is required in the following scenarios
```suggestion
> A license is required in the following scenarios:
```

2020-05-01 02:30 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/remove-license-from-shared-mailbox.md
> +> 2. The shared mailbox uses in-place archiving
```suggestion
> 2. The shared mailbox uses in-place archiving.
```

2020-05-01 02:31 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/remove-license-from-shared-mailbox.md
> +> 3. The shared mailbox is placed in litigation hold
```suggestion
> 3. The shared mailbox is placed in litigation hold.
```

2020-05-01 02:32 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-02 00:08 UTC, mypil commented
@Weishaupt - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-05-05 09:14 UTC, Weishaupt commented
> 
> 
> @Weishaupt - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

Done.

2020-05-05 13:25 UTC, JohanFreelancer9 approved these changes

2020-05-05 22:55 UTC, mypil commented
@pebaum - PR has been copy edited and is ready for final review.  

Thank you.

cc: @kenwith

2020-05-20 17:31 UTC, merged