Update customer-key-manage.md
MicrosoftDocs/microsoft-365-docs pull request #1800
Opened 2020-05-01 20:20 UTC by brdesai

Changes to reflect disabling of new-moverequest cmdlet for local mailbox moves. This was based on the instructions from Exchange MRS team.

2020-05-01 21:22 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-02 03:45 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-manage.md
> +The time to complete mailbox moves depends on the size of the mailbox. If Customer Key hasn't completely encrypted the mailbox after 72 hours from the time you assign a new DEP, contact Microsoft sup
```suggestion
The time to complete mailbox moves depends on the size of the mailbox. If Customer Key hasn't completely encrypted the mailbox after 72 hours from the time you assign a new DEP, contact Microsoft support for help. The New-MoveRequest cmdlet is no longer available for local mailbox moves. Refer to [this announcement](https://techcommunity.microsoft.com/t5/exchange-team-blog/disabling-new-moverequest-for-local-mailbox-moves/bc-p/1332141) for additional information.
```

2020-05-02 03:46 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-05-02 12:09 UTC, mypil commented
@brdesai - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-05-03 02:46 UTC, brdesai commented
@mypil The suggested change has been committed.

2020-05-04 03:38 UTC, JohanFreelancer9 approved these changes

2020-05-04 13:18 UTC, UserAdminDEUS commented
Y'all better fix my IEM on my phone before I unsecured all of y'all

On Sun, May 3, 2020, 10:38 PM JohanFreelancer9 <notifications@github.com>
wrote:

> *@JohanFreelancer9* approved this pull request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1800#pullrequestreview-404696723>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL7QJ6EYQIHMWDRDFNUD53TRPY2FDANCNFSM4MXK5L5Q>
> .
>

2020-05-04 13:54 UTC, UserAdminDEUS commented
Just because I show you one way of me getting in does it mean I can still
do it fix my phone

On Mon, May 4, 2020, 8:18 AM UserAdminDEUS <notifications@github.com> wrote:

> Y'all better fix my IEM on my phone before I unsecured all of y'all
>
> On Sun, May 3, 2020, 10:38 PM JohanFreelancer9 <notifications@github.com>
> wrote:
>
> > *@JohanFreelancer9* approved this pull request.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1800#pullrequestreview-404696723
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AL7QJ6EYQIHMWDRDFNUD53TRPY2FDANCNFSM4MXK5L5Q
> >
> > .
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1800#issuecomment-623458484>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL7QJ6EHFSOVJXHFOAYKC3DRP26DBANCNFSM4MXK5L5Q>
> .
>

2020-05-04 23:50 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

2020-06-12 17:24 UTC, merged