made a change
MicrosoftDocs/microsoft-365-docs pull request #1814
Opened 2020-05-04 19:32 UTC by faoquong

@chrisda

2020-05-04 23:52 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-05 06:01 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md
> +As a user, you can view, release, and delete quarantined messages where you are a recipient, and the message was quarantined as spam, bulk email, or (as of April, 2020) phishing(except release). You
```suggestion
As a user, you can view, release, and delete quarantined messages where you are a recipient, and the message was quarantined as spam, bulk email, or (as of April 2020) phishing (except release). You view and manage your quarantined messages in the Security & Compliance Center or (if an admin has set this up) in [end-user spam notifications](use-spam-notifications-to-release-and-report-quarantined-messages.md).
```

2020-05-05 06:02 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-05 22:19 UTC, mypil commented
@faoquong - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-05-08 16:14 UTC, merged