Update create-dns-records-at-any-dns-hosting-provider.md
MicrosoftDocs/microsoft-365-docs pull request #1869
Opened 2020-05-10 20:24 UTC by msbemba

Added a note for Teams in the Document

2020-05-10 20:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1759

2020-05-11 21:13 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-12 01:29 UTC, JohanFreelancer9 commented on microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md
> +   > For **TTL**: Set this value to **1 hour** or to the equivalent in minutes ( **60** ), seconds ( **3600** ), etc. .These records do not apply to Exchange, Lync, or Skype for Business hybrid deplo
```suggestion
   > For **TTL**: Set this value to **1 hour** or to the equivalent in minutes (**60**), seconds (**3600**), etc. .These records do not apply to Exchange, Lync, or Skype for Business hybrid deployments. 
```

2020-05-12 01:29 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-12 14:10 UTC, JohanFreelancer9 approved these changes

2020-05-12 23:36 UTC, mypil commented
@pebaum - PR has been copy edited and is ready for final review. This is based on issue #1759.

Thank you.

cc: @kenwith

2020-05-20 17:33 UTC, pebaum commented
this article is in the process of a major restructure. closing without merge but will consider feedback on new version.

2020-05-20 17:33 UTC, closed without merging