Update office-365-groups.md
MicrosoftDocs/microsoft-365-docs pull request #1871
Opened 2020-05-10 20:55 UTC by msbemba

Added a line for clarity "Group Owners cannot access data shared in the group unless they are members."

2020-05-10 20:56 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1819

2020-05-11 21:12 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-12 01:32 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/office-365-groups.md
> +- **Owners** - Group owners can add or remove members and have unique permissions like the ability to delete conversations from the shared inbox or change different settings about the group. Group ow
```suggestion
- **Owners** - Group owners can add or remove members and have unique permissions like the ability to delete conversations from the shared inbox or change different settings about the group. Group owners can rename the group, update the description or picture, and more. Group Owners cannot access data shared in the group unless they are members.
```

2020-05-12 01:32 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-12 14:11 UTC, JohanFreelancer9 approved these changes

2020-05-12 23:42 UTC, mypil commented
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #1819.

Thank you.

cc: @kenwith

2020-05-13 12:31 UTC, MikePlumleyMSFT commented
@msbemba the statement is not true. I'm not aware of any unique permissions that members have that owners do not have.

2020-05-14 13:09 UTC, msbemba commented
@MikePlumleyMSFT  The members receive emails or other items shared within the group. The owner receives it only if he is a member. There are situations when there is an admin who owns the group but doesn't really receive the messages or emails sent to the group.

Thanks
Sri

2020-05-24 19:37 UTC, mypil commented
@MikePlumleyMSFT - We would like to follow up. Can you advise how you want to proceed with this PR?

Thank you.

2020-05-26 14:47 UTC, MikePlumleyMSFT commented
Clarifying this requires further research. Will look at documenting this in a future update. Closing this for now.

2020-05-26 14:47 UTC, closed without merging