Updated the link to point to correct resource
MicrosoftDocs/microsoft-365-docs pull request #1877
Opened 2020-05-11 17:21 UTC by joinimran

Updated the link to point to the correct resource. 

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1850

2020-05-11 17:27 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

@mypil FYI Please.

2020-05-11 21:14 UTC, mypil commented
@JohanFreelancer9 - please do the copy editor review for this PR. Thanks.

2020-05-12 01:19 UTC, JohanFreelancer9 commented on microsoft-365/compliance/offering-ISO-27001.md
> +Learn about the benefits of ISO-Iec-27001 on the Microsoft Cloud: [Download the ISO/IEC 27001:2013](https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide?command=Download&downloadType=Documen
```suggestion
Learn about the benefits of ISO-IEC-27001 on the Microsoft Cloud: [Download the ISO/IEC 27001:2013](https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide?command=Download&downloadType=Document&downloadId=47d89200-b24b-491d-b657-7c523ddfb6f9&docTab=4ce99610-c9c0-11e7-8c2c-f908a777fa4d_ISO_Reports)
```

2020-05-12 01:21 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-12 18:41 UTC, joinimran commented
@mypil - Ready to go live

2020-05-13 23:37 UTC, mypil commented
@robmazz - PR has been copy edited and is ready for final review. This is based on issue #1850.

Thank you.

cc: @kenwith

2020-05-18 16:41 UTC, merged