specified role assignment
MicrosoftDocs/microsoft-365-docs pull request #1885
Opened 2020-05-12 07:21 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1763

2020-05-12 07:22 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @mypil, for your information

Thank you

2020-05-12 07:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-loss-prevention-policies.md
> +3. Assign **DLP Compliance Management** role to the role group
```suggestion
3. Assign a **DLP Compliance Management** role to the role group.
```

2020-05-12 07:57 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-12 22:27 UTC, mypil commented
@MaratMussabekov - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-05-12 22:39 UTC, UnsnappedKhan8 commented
Salt

2020-05-12 22:55 UTC, UnsnappedKhan8 commented
Global Admin

2020-05-13 14:00 UTC, JohanFreelancer9 approved these changes

2020-05-13 23:22 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #1763

Thank you.

cc: @kenwith

2020-05-14 10:59 UTC, PrasadKasireddy commented
These changes are updated in PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1891

2020-05-14 18:51 UTC, merged