Update customer-key-set-up.md
MicrosoftDocs/microsoft-365-docs pull request #1927
Opened 2020-05-15 00:25 UTC by cgill

Good afternoon, folks! I was working today to set up Customer Key and found that the FastTrack portal has changed A LOT, now showing information cards instead of the traditional offers. I have made changes to address the steps necessary to properly fulfill submitting an offer for Customer Key, and hope you agree that these are the necessary changes. Thanks in advance!

2020-05-15 22:51 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-16 00:30 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> +   - **Exchange Online and Skype for Business:** Choose **Request encryption key help for Exchange online** offer.
```suggestion
   - **Exchange Online and Skype for Business:** Choose the **Request encryption key help for Exchange online** offer.
```

2020-05-16 00:31 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> +   - **SharePoint Online, OneDrive for Business, and Teams files:** Choose **Request encryption key help for Sharepoint and OneDrive** offer.
```suggestion
   - **SharePoint Online, OneDrive, and Teams files:** Choose the **Request encryption key help for Sharepoint and OneDrive** offer.
```

2020-05-16 00:34 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-16 12:14 UTC, mypil commented
@cgill  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-05-18 01:40 UTC, JohanFreelancer9 approved these changes

2020-05-23 01:07 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review.  


Thank you.

cc: @kenwith

2020-06-12 17:35 UTC, merged