Update set-up-multi-factor-authentication.md
MicrosoftDocs/microsoft-365-docs pull request #1935
Opened 2020-05-15 14:28 UTC by msbemba

Added reference link for how to change 2fa settings

2020-05-15 14:28 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1694

2020-05-15 22:52 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-16 00:19 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md
> +All other users will be asked to perform additional authentication when needed. For more information, please visit [Two-factor verification method and settings](https://docs.microsoft.com/azure/activ
```suggestion
All other users will be asked to perform additional authentication when needed. For more information, please visit [Two-factor verification method and settings](https://docs.microsoft.com/azure/active-directory/user-help/multi-factor-authentication-end-user-manage-settings#turn-on-two-factor-verification-prompts-on-a-trusted-device).
```

2020-05-16 00:19 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-16 12:10 UTC, mypil commented
@msbemba  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-05-18 01:41 UTC, JohanFreelancer9 approved these changes

2020-05-18 21:31 UTC, mypil commented
@Sirkkuw - PR has been copy edited and is ready for final review. This is based on issue #1694.

Thank you.

cc: @kenwith

2020-06-01 22:28 UTC, merged