Update migrate-from-e3.md
MicrosoftDocs/microsoft-365-docs pull request #1985
Opened 2020-05-20 12:53 UTC by msbemba

added migration information about office installs

2020-05-20 12:53 UTC, msbemba commented
Issue# https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1781

2020-05-21 22:07 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-22 00:16 UTC, JohanFreelancer9 commented on microsoft-365/business/migrate-from-e3.md
> +- Office Applications will scale automatically.  Office 365 modern licensing will check the user’s license assignment every 72 hours and will convert Office apps to the version that matches the user
```suggestion
- Office applications will scale automatically. Office 365 modern licensing will check the user’s license assignment every 72 hours and will convert Office applications to the version that matches the user subscription.
```

2020-05-22 00:17 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-23 00:36 UTC, mypil commented
@Sirkkuw - PR has been copy edited and is ready for final review. This is based on issue #1781.

Thank you.

cc: @kenwith

2020-05-23 02:10 UTC, JohanFreelancer9 approved these changes

2020-06-01 22:29 UTC, merged