Call out ExO cmdlets when being used
MicrosoftDocs/microsoft-365-docs pull request #2000
Opened 2020-05-21 16:34 UTC by AndySDay

This is a long article and a customer has asked for us to add the need to use Exchange Online Powershell alongside SCC Powershell in the examples where ExO cmdlets are being used. The general need for ExO PS is written at the top of the article, but it would help to call-out where ExO cmdlets are being used in the examples, e.g. examples that call $DG = Get-DistributionGroup. The confusion has been that SCC also contains/contained the same PS cmdlets as ExO, but that those did not work from the SCC side.

2020-05-21 20:36 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-22 00:35 UTC, JohanFreelancer9 commented on microsoft-365/compliance/permissions-filtering-for-content-search.md
> +This example allows members of the eDiscovery Manager role group to search only the mailboxes of members of the Ottawa Users distribution group. Get-DistributionGroup in Exchange Online Powershell is
```suggestion
This example allows members of the eDiscovery Manager role group to search only the mailboxes of members of the Ottawa Users distribution group. Get-DistributionGroup in Exchange Online PowerShell is used to find the members of Ottawa Users.
```

2020-05-22 00:36 UTC, JohanFreelancer9 commented on microsoft-365/compliance/permissions-filtering-for-content-search.md
> +This example prevents any user from deleting content from the mailboxes of members of the Executive Team distribution group. Get-DistributionGroup in Exchange Online Powershell is used to find the me
```suggestion
This example prevents any user from deleting content from the mailboxes of members of the Executive Team distribution group. Get-DistributionGroup in Exchange Online PowerShell is used to find the members of the Executive Team.
```

2020-05-22 00:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/permissions-filtering-for-content-search.md
> +This example prevents any user from deleting content from the mailboxes of members of the Executive Team distribution group. Get-DistributionGroup in Exchange Online Powershell is used to find the me
```suggestion
This example prevents any user from deleting content from the mailboxes of members of the Executive Team distribution group. Get-DistributionGroup in Exchange Online PowerShell is used to find the members of the Executive Team.
```

2020-05-22 00:46 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-22 00:46 UTC, merged

2020-05-22 00:47 UTC, markjjo commented
@AndySDay PR merged. Thanks for submitting. 

@JohanFreelancer9  Thanks for editing.