Update sharepoint-site-usage.md
MicrosoftDocs/microsoft-365-docs pull request #2006
Opened 2020-05-21 19:17 UTC by JeremyEsposito

Microsoft 365 Reports in the admin center is not supported for GCC High and DoD tenants. Confirmed by SPO PG and PM's.

2020-05-21 20:54 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-22 00:27 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/sharepoint-site-usage.md
> +> You must be a global administrator, global reader or reports reader in Microsoft 365 or an Exchange, SharePoint, Teams Service, Teams Communications, or Skype for Business administrator to see repo
```suggestion
> You must be a global administrator, global reader, or reports reader in Microsoft 365 or an Exchange, SharePoint, Teams Service, Teams Communications, or Skype for Business administrator to see reports.
```

2020-05-22 00:30 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/sharepoint-site-usage.md
>  As an Microsoft 365 admin, the **Reports** dashboard shows you the activity overview across various products in your organization. It enables you to drill in to get more granular insight about the ac
```suggestion
As a Microsoft 365 admin, the **Reports** dashboard shows you the activity overview across various products in your organization. It enables you to drill in to get more granular insight about the activities specific to each product. For example, you can get a high-level view of the value you are getting from SharePoint in terms of the total number of files that users store in SharePoint sites, how many files are actively being used, and the storage consumed across all these sites. Then, you can drill into the SharePoint site usage report to understand the trends and per site level details for all sites. 
```

2020-05-22 00:32 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/sharepoint-site-usage.md
>  As an Microsoft 365 admin, the **Reports** dashboard shows you the activity overview across various products in your organization. It enables you to drill in to get more granular insight about the ac
Please also change "As an Microsoft..." to "As a Microsoft..." and "high level" to "high-level".

2020-05-22 00:32 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-23 00:38 UTC, mypil commented
@JeremyEsposito - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-06-03 23:21 UTC, merged