Update latest details about external collaboration settings
MicrosoftDocs/microsoft-365-docs pull request #2013
Opened 2020-05-22 13:11 UTC by PrasadKasireddy

#### Category
- [x] Content fix
- [ ] New article
- [ ] Example checked item (*delete this line*)

#### Related issues
 - fixes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2007

#### What's in this Pull Request?
> Update the latest details about external collaboration settings in AD

2020-05-22 20:31 UTC, denisebmsft commented
@MikePlumleyMSFT, you might need to fix the metadata section for formatting

2020-05-23 03:20 UTC, PrasadKasireddy commented
> @MikePlumleyMSFT, you might need to fix the metadata section for formatting

Thanks for your inputs, I am new to this community, could you please guide me what meta data I need to update, I can see there is a meta data for this article on top of the page

![image](https://user-images.githubusercontent.com/11626905/82720576-561c9380-9cd2-11ea-97f4-9b617cd44736.png)

2020-05-23 13:23 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-23 13:59 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +## To configure external collaboration settings:
```suggestion
## Configuring external collaboration settings
```

2020-05-23 14:00 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +To set external collaboration settings
```suggestion
To set external collaboration settings:
```

2020-05-23 14:02 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +  > Also, you can set external collaboration settings another way, click **Azure Active Directory** > **External Identities** > **External collaboration settings**.
```suggestion
  > You can also set external collaboration settings by selecting **Azure Active Directory** > **External Identities** > **External collaboration settings**.
```

2020-05-23 14:04 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +  - **Guest users permissions are limited**: This policy determines permissions for guests in your directory. Select **Yes** to block guests from certain directory tasks, like enumerating users, grou
```suggestion
  - **Guest users permissions are limited**: This policy determines permissions for guests in your directory. Select **Yes** to block guests from certain directory tasks, like enumerating users, groups, or other directory resources. Select **No** to give guests the same access to directory data as regular users in your directory.
```

2020-05-23 14:05 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +  - **Guest users permissions are limited**: This policy determines permissions for guests in your directory. Select **Yes** to block guests from certain directory tasks, like enumerating users, grou
```suggestion
  - **Guest users permissions are limited**: This policy determines permissions for guests in your directory. Select **Yes** to block guests from certain directory tasks, like enumerating users, groups, or other directory resources. Select **No** to give guests the same access to directory data as regular users in your directory.
```

2020-05-23 14:06 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +  - **Guest users permissions are limited**: This policy determines permissions for guests in your directory. Select **Yes** to block guests from certain directory tasks, like enumerating users, grou
Please remove the extra space between "as" and "regular".

2020-05-23 14:10 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +   - **Enable Email One-Time Passcode for guests (Preview)**: For more information about the one-time passcode feature, see [Email one-time passcode authentication (preview)](https://docs.microsoft.c
```suggestion
   - **Enable Email One-Time Passcode for guests (Preview)**: For more information about the one-time passcode feature, see [Email one-time passcode authentication (preview)](https://docs.microsoft.com/azure/active-directory/b2b/one-time-passcode).
```

2020-05-23 14:11 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +   - **Collaboration restrictions**: For more information about allowing or blocking invitations to specific domains, see [Allow or block invitations to B2B users from specific organizations](https:/
```suggestion
   - **Collaboration restrictions**: For more information about allowing or blocking invitations to specific domains, see [Allow or block invitations to B2B users from specific organizations](https://docs.microsoft.com/azure/active-directory/b2b/allow-deny-list).
```

2020-05-23 14:14 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-as-team.md
> +   - **Enable guest self-service sign up via user flows (Preview)**: For more information about the Guest self service sign up via user flows, see [self service sign up user flows (Preview)](https://
```suggestion
   - **Enable guest self-service sign up via user flows (Preview)**: For more information about guest self-service sign up via user flows, see [Add a self-service sign-up user flow to an app (Preview)](https://docs.microsoft.com/azure/active-directory/b2b/self-service-sign-up-user-flow). 
```

2020-05-23 14:16 UTC, JohanFreelancer9 requested changes
Copy review.

2020-05-23 14:36 UTC, PrasadKasireddy commented
> Copy review.

@JohanFreelancer9  - thanks for your inputs- I updated the changes as per your comments

2020-05-23 16:08 UTC, mypil commented
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #2007.


Thank you.

cc: @kenwith

2020-05-26 14:35 UTC, MikePlumleyMSFT commented
Primary nav should be via External Identities > External collaboration settings and screenshot should show this as in original. Also, extra details about each setting not needed. Updating via a separate PR.

2020-05-26 14:35 UTC, closed without merging