remove double wording
MicrosoftDocs/microsoft-365-docs pull request #2030
Opened 2020-05-23 13:18 UTC by bartvermeersch

2020-05-24 01:23 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-05-24 01:54 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/configure-the-connection-filter-policy.md
>  - **IP Block List**: Block all incoming messages from the source email servers that you specify by IP address or IP address range. The incoming messages are rejected, are not marked as spam, and no a
```suggestion
- **IP Block List**: Block all incoming messages from the source email servers that you specify by IP address or IP address range. The incoming messages are rejected, are not marked as spam, and no additional filtering occurs. For more information about how the IP Block List should fit into your overall blocked senders strategy, see [Create block sender lists in EOP](create-block-sender-lists-in-office-365.md).
```

2020-05-24 01:55 UTC, JohanFreelancer9 requested changes
Copy review - please merge additional edit.

2020-05-24 11:33 UTC, mypil commented
@bartvermeersch  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-05-25 14:39 UTC, JohanFreelancer9 approved these changes

2020-05-25 21:37 UTC, mypil commented
@chrisda  - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

2020-05-26 16:10 UTC, merged