Replacing outdated checklist & link. #1457
MicrosoftDocs/microsoft-365-docs pull request #2092
Opened 2020-06-01 22:33 UTC by joelbyford

Appears that the CSF checklist referenced in the document is no longer published or available.  Adding a new link to Azure docs page for similar blueprint documentation which is now using Azure Policy to enforce.

2020-06-01 22:39 UTC, mypil commented
JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-06-02 23:54 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-06-03 00:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/offering-nist-csf.md
> +- [Overview of the NIST SP 800-53 R4 blueprint sample](https://docs.microsoft.com/en-us/azure/governance/blueprints/samples/nist-sp-800-53-rev4/)
```suggestion
- [Overview of the NIST SP 800-53 R4 blueprint sample](https://docs.microsoft.com/azure/governance/blueprints/samples/nist-sp-800-53-rev4/)
```

2020-06-03 00:54 UTC, JohanFreelancer9 requested changes
Please remove the locale from the link address.

2020-06-03 03:22 UTC, JohanFreelancer9 approved these changes

2020-06-06 01:22 UTC, mypil commented
@robmazz - PR has been copy edited and is ready for final review. 

Thank you.

2020-06-18 15:35 UTC, merged