replace outdated screenshot
MicrosoftDocs/microsoft-365-docs pull request #2171
Opened 2020-06-15 04:49 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1740

2020-06-15 04:49 UTC, MaratMussabekov commented
Dear @mypil, for your information

Thank you

2020-06-15 21:04 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-06-16 01:12 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/email-apps-usage.md
>  |6.  <br/> | On the **Users** chart, the Y axis is the total count of unique users that connected to an app on any day of the reporting period.  <br/>  On the **Users** chart, the X axis is number of
```suggestion
|6.  <br/> | On the **Users** chart, the Y axis is the total count of unique users that connected to an app on any day of the reporting period.  <br/>  On the **Users** chart, the X axis is number of unique users that used the app for that reporting period.  <br/>  On the **Apps** chart, the Y axis is the total count of unique users who used a specific app during the reporting period.  <br/>  On the **Apps** chart, the X axis is the list of apps in your organization.  <br/>  On the **Versions** chart, the Y axis is the total count of unique users using a specific version of Outlook desktop. If the report can't resolve the version number of Outlook, the quantity will show as **Undetermined**.  <br/>  On the **Versions** chart, the X axis is the list of apps in your organization.  <br/> |
```

2020-06-16 01:13 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/email-apps-usage.md
>  |6.  <br/> | On the **Users** chart, the Y axis is the total count of unique users that connected to an app on any day of the reporting period.  <br/>  On the **Users** chart, the X axis is number of
Please BOLD "Undetermined" in the second last line.

2020-06-16 01:15 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/email-apps-usage.md
>  |7.  <br/> |You can filter the series you see on the chart by selectingan item in the legend. For example, on the **Users** chart, select **Mac mail** or **Outlook** ![List of email clients. Select t
```suggestion
|7.  <br/> |You can filter the series you see on the chart by selecting an item in the legend. For example, on the **Users** chart, select **Mac mail** or **Outlook** ![List of email clients. Select the email client to get more reporting data on that client.](../../media/19b9da1b-7b69-4a04-8527-38349f859e84.png) to see only the info related to each one. Changing this selection doesn't change the info in the grid table. Mac mail, Outlook for Mac, Outlook mobile, Outlook desktop, and Outlook on the web are examples of email apps you may have in your organization.  <br/> |
```

2020-06-16 01:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/email-apps-usage.md
>  |7.  <br/> |You can filter the series you see on the chart by selectingan item in the legend. For example, on the **Users** chart, select **Mac mail** or **Outlook** ![List of email clients. Select t
Please change "selectingan" to "selecting an" in the first line.

2020-06-16 01:17 UTC, JohanFreelancer9 requested changes
Copy review - please merge two additional edits.

2020-06-16 14:39 UTC, JohanFreelancer9 approved these changes

2020-06-16 23:22 UTC, mypil commented
@kwekuako - PR has been copy edited and is ready for final review. This is based on issue #1740.

Thank you.

2020-06-20 13:18 UTC, mypil commented
@Sirkkuw  - PR has been copy edited and is ready for final review. This is based on issue #1740.

Thank you.

2020-06-30 17:19 UTC, merged