Adding Show All menu option
MicrosoftDocs/microsoft-365-docs pull request #2194
Opened 2020-06-18 12:29 UTC by get-itips

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2058

2020-06-19 21:55 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-06-20 02:44 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/manage-guest-access-in-groups.md
> +1. In the admin center, go to the **Show all** \> **Settings** \> **Org settings** and on the **Services** tab, select **Microsoft 365 groups**.
```suggestion
1. In the admin center, go to **Show all** \> **Settings** \> **Org settings** and on the **Services** tab, select **Microsoft 365 groups**.
```

2020-06-20 02:45 UTC, JohanFreelancer9 requested changes
Copy review.

2020-06-20 12:29 UTC, mypil commented
@get-itips - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-06-21 03:34 UTC, JohanFreelancer9 approved these changes

2020-06-23 02:31 UTC, mypil commented
@MikePlumleyMSFT - PR has been copy edited and is ready for final review. This is based on issue #2058.

Thank you.

2020-06-23 12:31 UTC, merged