Updating steps for way number 10
MicrosoftDocs/microsoft-365-docs pull request #2229
Opened 2020-06-23 21:32 UTC by get-itips

@Sirkkuw please review
cc @mypil

2020-06-24 00:19 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-06-24 01:33 UTC, JohanFreelancer9 approved these changes

2020-06-24 23:09 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review on the additional commits of this PR. Thanks.

2020-06-25 01:00 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/secure-your-business-data.md
> +2. Under **Settings that apply to content across Office 365**, enter an URL to be blocked, such as _example.com_ and select **+**.
```suggestion
2. Under **Settings that apply to content across Office 365**, enter a URL to be blocked, such as _example.com_, and select **+**.
```

2020-06-25 01:01 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/secure-your-business-data.md
> +3. Under **Settings that apply to content except email**, select **Office 365 applications**, **Do not track when users click safe links** and **Do not let users click through safe links to original
```suggestion
3. Under **Settings that apply to content except email**, select **Office 365 applications**, **Do not track when users click safe links**, and **Do not let users click through safe links to original URL**.
```

2020-06-25 01:02 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-06-25 01:20 UTC, JohanFreelancer9 approved these changes

2020-06-27 13:59 UTC, mypil commented
@Sirkkuw - PR has been copy edited and is ready for final review. This is based on issue #2193.

Thank you.

2020-06-30 17:25 UTC, merged