Update index.yml
MicrosoftDocs/microsoft-365-docs pull request #2239
Opened 2020-06-24 22:10 UTC by 1justingilmore

@DaniHalfin

2020-06-24 23:25 UTC, mypil commented
@DaniHalfin - PR is ready for final review. This is related to the SEO project.

Thank you.

2020-07-02 21:31 UTC, samanro requested changes
This help center will enable you to learn about how to design the solution and architecture that is right for your organization and provide links to guidance and IT training.

2020-09-18 14:07 UTC, yogkumgit commented
@1justingilmore Please implement the indicated feedback. Thanks

2020-09-18 16:19 UTC, samanro approved these changes

2020-09-18 16:19 UTC, merged