Update create-a-dlp-policy-from-a-template.md
MicrosoftDocs/microsoft-365-docs pull request #2252
Opened 2020-06-25 22:57 UTC by msbemba

updated Exchange email accounts as the options show only distribution groups

2020-06-25 22:58 UTC, msbemba commented
Issue# https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2049

2020-06-26 21:26 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-06-27 04:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-a-dlp-policy-from-a-template.md
> +    To include or exclude only specific Exchange email accounts  switch the **Status** of that location on to choose specific distribution group. Based on selection, policy will target or exclude the
```suggestion
    To include or exclude only specific Exchange email accounts, switch the **Status** of that location on to choose a specific distribution group. Based on the selection, the policy will target or exclude the members of the group.
```

2020-06-27 04:29 UTC, JohanFreelancer9 requested changes
Copy review.

2020-06-27 21:18 UTC, mypil commented
@msbemba - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-06-28 00:50 UTC, JohanFreelancer9 approved these changes

2020-06-28 13:53 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #2049

Thank you.

2020-07-01 20:02 UTC, chrfox commented
suggested wording is confusing, the UI makes the functionality clear

2020-07-01 20:02 UTC, closed without merging