Update view-email-security-reports.md
MicrosoftDocs/microsoft-365-docs pull request #2259
Opened 2020-06-26 07:25 UTC by faoquong

@chrisda

2020-06-26 22:44 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-06-27 04:12 UTC, JohanFreelancer9 requested changes
Copy review.

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +This is a 'click-centric' report that has two aggregated views which shows data for the last 90 days.
```suggestion
This is a 'click-centric' report that has two aggregated views that shows data for the last 90 days.
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +The details table of the URL Threat Protection report provides a near-real-time view of all clicks that happen within the tenant for the last 7 days, and it includes investigative information such as
```suggestion
The details table of the URL Threat Protection report provides a near-real-time view of all clicks that happen within the tenant for the last seven days, and it includes investigative information such as *username*, *URL*, the *network message ID* (if the URL was clicked from an email), and other valuable pieces of information useful for investigations and analyses.
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +When the report first opens, you'll see data about encryption methods used on email messages for the past seven (7) days. You can change the date range and the details that are displayed in the repor
```suggestion
When the report first opens, you'll see data about encryption methods used on email messages for the past seven (7) days. You can change the date range and the details that are displayed in the report by clicking **Filters** in the upper right corner of the screen. The aggregate view allows for filtering for the last 90 days, while the detail view allows for filtering for 10 days. 
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +When you first open the Threat Protection Status report, the report shows data for the past seven days by default; however, you can click **Filters** and change the date range for up to 90 days of de
```suggestion
When you first open the Threat Protection Status report, the report shows data for the past seven days by default; however, you can click **Filters** and change the date range for up to 90 days of detail. (If you are using a trial subscription, you might be limited to 30 days' of data.) Note that the detail view filtering only allows for 30 days.
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +Similar to other reports, like the [Threat Protection Status report](#threat-protection-status-report), the report displays data for the past seven days by default. However, you can choose **Filters*
```suggestion
Similar to other reports, like the [Threat Protection Status report](#threat-protection-status-report), the report displays data for the past seven days by default. However, you can choose **Filters** to change the date range. The aggregate view filter allows for 90 days, while the detail view filter only allows for 10 days.
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +Below the chart, you'll see a list of detected malware and how many messages were detected as having that malware. The aggregate view filter only allows for 90 days.
```suggestion
Below the chart, you'll see a list of detected malware and how many messages were detected as having that malware. The aggregate view filter only allows for 90 days.
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +Below the chart, you'll see who the top email senders or recipients were, along with a count of messages sent or received for the given time period. note that the aggregate view only allows for 90 da
```suggestion
Below the chart, you'll see who the top email senders or recipients were, along with a count of messages sent or received for the given time period. Note that the aggregate view only allows for 90 days of filtering. 
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +Click (or tap) the report to open it in a new browser window, where you can get a more detailed view of the report. To learn more about anti-spoof protection, see [Anti-spoofing protection in Microso
```suggestion
Click (or tap) the report to open it in a new browser window, where you can get a more detailed view of the report. To learn more about anti-spoof protection, see [Anti-spoofing protection in Microsoft 365](anti-spoofing-protection.md). The aggregate view of the report allows for 90 days of filtering, while the detail view only allows for ten days of filtering. 
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +Below the chart, you'll see a list of spam items that were detected. Select an item to view additional information, such as whether the spam item was inbound or outbound, its message ID, and its reci
```suggestion
Below the chart, you'll see a list of spam items that were detected. Select an item to view additional information, such as whether the spam item was inbound or outbound, its message ID, and its recipient. To learn more about anti-spam protection, see [Office 365 email anti-spam protection](https://docs.microsoft.com/microsoft-365/security/office-365-security/anti-spam-and-anti-malware-protection). The aggregate view of the report allows for 90 days of filtering, while the detail view only allows for ten days of filtering. 
```

2020-06-27 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-email-security-reports.md
> +To learn more about email intelligence, see [Mail flow intelligence in Microsoft 365](https://docs.microsoft.com/microsoft-365/security/office-365-security/mail-flow-intelligence-in-office-365). the
```suggestion
To learn more about email intelligence, see [Mail flow intelligence in Microsoft 365](https://docs.microsoft.com/microsoft-365/security/office-365-security/mail-flow-intelligence-in-office-365). The aggregate view and the detail view of the report allows for 90 days of filtering. 
```

2020-06-28 15:52 UTC, mypil commented
@faoquong  - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-06-30 01:15 UTC, chrisda commented
Sorry; too many conflicts. Recreated in #4113

2020-06-30 01:15 UTC, closed without merging