Update view-reports-for-atp.md
MicrosoftDocs/microsoft-365-docs pull request #2260
Opened 2020-06-26 07:33 UTC by faoquong

@chrisda

2020-06-26 22:45 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2020-06-27 03:29 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-reports-for-atp.md
> +When you hover over a particular day, you can see the breakdown of types of malicious files that were detected by [ATP Safe Attachments](atp-safe-attachments.md) and [anti-spam &amp; anti-malware pro
```suggestion
When you hover over a particular day, you can see the breakdown of types of malicious files that were detected by [ATP Safe Attachments](atp-safe-attachments.md) and [anti-spam &amp; anti-malware protection](anti-spam-and-anti-malware-protection.md). The aggregate view of the report allows for 90 days of filtering, while the detail view only allows for 10 days filtering. 
```

2020-06-27 03:37 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-reports-for-atp.md
> +![ATP Message Disposition Report data for a day](../../media/68d2beb8-4b30-48c4-8ba6-5e8ab88ae456.png) the aggregate view of the report only allows for 90 days filtering, while the detial view only a
```suggestion
![ATP Message Disposition Report data for a day](../../media/68d2beb8-4b30-48c4-8ba6-5e8ab88ae456.png)
```

2020-06-27 03:37 UTC, JohanFreelancer9 requested changes
Copy review.

2020-06-28 18:02 UTC, mypil commented
@faoquong - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2020-06-29 02:42 UTC, JohanFreelancer9 approved these changes

2020-06-29 16:07 UTC, merged