Update microsoft-365-business-faqs.md
MicrosoftDocs/microsoft-365-docs pull request #2396
Opened 2020-07-21 16:19 UTC by msbemba

Correct Compatibility as this changed recently.

2020-07-21 16:20 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2390

2020-07-22 15:22 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-07-22 15:40 UTC, JohanFreelancer9 commented on microsoft-365/business/support/microsoft-365-business-faqs.md
> +Yes, Microsoft 365 Business Premium subscribers are licensed to use full Intune capabilities for iOS, Android, macOS, and other cross-platform device management. Features not available in the simplif
```suggestion
Yes, Microsoft 365 Business Premium subscribers are licensed to use full Intune capabilities for iOS, Android, macOS, and other cross-platform device management. Features not available in the simplified management console in Microsoft 365 Business Premium, like third-party app management, configuration of Wi-Fi profiles, and VPN certificates, can be managed in the full Intune console. 
```

2020-07-22 15:45 UTC, JohanFreelancer9 commented on microsoft-365/business/support/microsoft-365-business-faqs.md
> +Yes, Microsoft Defender Advanced Threat Protection is available as an Add-on to Microsoft 365 Business premium customers.
```suggestion
Yes, Microsoft Defender Advanced Threat Protection is available as an add-on to Microsoft 365 Business Premium customers.
```

2020-07-22 15:48 UTC, JohanFreelancer9 approved these changes
Copy review.

2020-07-22 15:49 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-07-23 03:55 UTC, JohanFreelancer9 approved these changes

2020-07-23 06:48 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks.

2020-07-28 15:43 UTC, Sirkkuw approved these changes

2020-07-28 15:43 UTC, merged