Adding required perm
MicrosoftDocs/microsoft-365-docs pull request #2397
Opened 2020-07-21 18:44 UTC by get-itips

Closes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2293

2020-07-24 16:30 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-07-25 03:53 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/customize-the-app-launcher.md
> +1. Log into the admin center as a Global Administrator, go to the **Settings** > **Org Settings** and choose **Organization profile** tab.
```suggestion
1. Sign in to the admin center as a Global Administrator, go to **Settings** > **Org Settings**, and choose the **Organization profile** tab.
```

2020-07-25 03:57 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-27 15:09 UTC, JohanFreelancer9 approved these changes

2020-07-28 03:57 UTC, yogkumgit commented
@twernermsft Please merge this PR. Thanks.

2020-08-03 05:04 UTC, yogkumgit commented
@twernermsft Gentle reminder. Please merge this PR. Thanks.

2020-08-03 16:10 UTC, merged