Update add-storage-space.md
MicrosoftDocs/microsoft-365-docs pull request #2403
Opened 2020-07-21 23:40 UTC by msbemba

updated the note to sort out the confusion. If the subscription was brought from VLSC or CSP the Add-on for extra storage can be purchased from them and not through microsoft.

2020-07-21 23:40 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2385

2020-07-22 15:39 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-07-22 16:12 UTC, JohanFreelancer9 commented on microsoft-365/commerce/add-storage-space.md
> +> If you bought your subscription through Volume Licensing or a CSP, you can't buy **Office 365 Extra File Storage** for your organization through MIcrosoft directly. Contact your representative or p
```suggestion
> If you bought your subscription through Volume Licensing or a CSP, you can't buy **Office 365 Extra File Storage** for your organization from Microsoft directly. Contact your representative or partner for help.
```

2020-07-22 16:21 UTC, JohanFreelancer9 reviewed
Copy review.

2020-07-22 17:13 UTC, cmcatee-MSFT requested changes
Change to "directly from Microsoft"

2020-07-22 21:02 UTC, msbemba commented
> Change to "directly from Microsoft"

I have made the changes @cmcatee-MSFT . Thank you.

2020-07-22 22:34 UTC, merged