Update add-or-remove-members-from-groups.md
MicrosoftDocs/microsoft-365-docs pull request #2404
Opened 2020-07-22 00:02 UTC by msbemba

added a note to the document to stress the fact that only global admin or group admins can make changes to a group via the 365 admin center.

2020-07-22 00:03 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2376

2020-07-22 15:51 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-07-22 16:08 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/add-or-remove-members-from-groups.md
> +> You need to be a Global admin or a Groups admin to make changes to a group in the M365 admin center.
```suggestion
> You need to be a global admin or a groups admin to make changes to a group in the Microsoft 365 admin center.
```

2020-07-22 16:10 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2020-07-23 03:59 UTC, JohanFreelancer9 approved these changes

2020-07-23 07:02 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks.

2020-07-24 17:20 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks.

2020-08-06 21:41 UTC, MikePlumleyMSFT commented
@msbemba the required permissions for the procedures in this article are already listed in the paragraph prior to the procedure.

2020-08-06 21:41 UTC, closed without merging