Update change-nameservers-at-any-domain-registrar.md
MicrosoftDocs/microsoft-365-docs pull request #2451
Opened 2020-07-27 20:32 UTC by msbemba

Corrected Step 2 in adding Custom records

2020-07-27 20:33 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2318

2020-07-27 20:33 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-07-28 03:43 UTC, JohanFreelancer9 commented on microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md
> +2. On the Domains page, Click on the domain and click on DNS Records tab.
```suggestion
2. On the **Domains** page, select the domain and choose **DNS Records**.
```

2020-07-28 03:47 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-28 14:43 UTC, JohanFreelancer9 approved these changes

2020-07-30 15:35 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks

2020-08-03 18:12 UTC, merged