Update customer-lockbox-requests.md
MicrosoftDocs/microsoft-365-docs pull request #2459
Opened 2020-07-27 22:12 UTC by msbemba

Correcting the steps to Customer lockbox on or off

2020-07-27 22:12 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2110

2020-07-27 22:13 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-07-28 02:18 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-lockbox-requests.md
> +3. Click **Services** and Click on **Customer Lockbox**, Then choose **Edit**, and then move the toggle to **On** or **Off** to turn the feature on or off.
```suggestion
3. Select **Services** > **Customer Lockbox** > **Edit**, and then move the toggle to **On** or **Off** to turn the feature on or off.
```

2020-07-28 02:19 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-28 14:41 UTC, JohanFreelancer9 approved these changes

2020-07-30 15:46 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks.

2020-08-17 22:01 UTC, merged