Update set-up-multi-factor-authentication.md
MicrosoftDocs/microsoft-365-docs pull request #2472
Opened 2020-07-28 20:22 UTC by msbemba

Added steps to Turn on Per person MFA

2020-07-28 20:22 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-07-28 20:23 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2098

2020-07-29 01:43 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md
> +### Turn On Per person MFA
```suggestion
### Turn on per-user MFA
```

2020-07-29 01:44 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md
> +If you have security defaults turned Off and donot want to turn on MFA for the entire organization
```suggestion
If you have security defaults turned off and do not want to turn on MFA for the entire organization:
```

2020-07-29 01:47 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md
> +1. In the Microsoft 365 admin center, in the left nav choose **Users** > **Active users**.
```suggestion
1. In the Microsoft 365 admin center, in the left nav, choose **Users** > **Active users**. 
```

2020-07-29 01:48 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-29 02:28 UTC, JohanFreelancer9 approved these changes

2020-07-29 11:44 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks.

2020-07-30 21:42 UTC, Sirkkuw commented
@yogkumgit - we don't want this info there. this is going to go away and PG doesn't want anyone using the per person MFA.

2020-07-30 21:52 UTC, msbemba commented
Thank you @Sirkkuw

2020-07-30 21:52 UTC, closed without merging