Update compare-groups.md
MicrosoftDocs/microsoft-365-docs pull request #2475
Opened 2020-07-28 20:45 UTC by msbemba

Added Upgrade option to the document as this document talks about comparing groups

2020-07-28 20:46 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2164

2020-07-28 20:48 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-07-29 01:28 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/compare-groups.md
> +You can upgrade distribution lists to Microsoft 365 Groups with Outlook. This is a great way to give your organization's distribution lists all the features and functionality of Microsoft 365 Groups.
```suggestion
You can upgrade distribution lists to Microsoft 365 Groups with Outlook. This is a great way to give your organization's distribution lists all the features and functionality of Microsoft 365 Groups. [Why you should upgrade your distribution lists to groups in Outlook](https://support.microsoft.com/office/7fb3d880-593b-4909-aafa-950dd50ce188).
```

2020-07-29 01:29 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/compare-groups.md
> +You can upgrade DLs one at a time, or several at the same time. For more information, See [Upgrade distribution lists to Microsoft 365 Groups in Outlook](https://docs.microsoft.com/microsoft-365/admi
```suggestion
You can upgrade distribution lists one at a time, or several at the same time. For more information, See [Upgrade distribution lists to Microsoft 365 Groups in Outlook](https://docs.microsoft.com/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide).
```

2020-07-29 01:29 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-29 02:24 UTC, JohanFreelancer9 approved these changes

2020-07-29 12:02 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2020-07-29 12:09 UTC, merged