Update give-mailbox-permissions-to-another-user.md
MicrosoftDocs/microsoft-365-docs pull request #2477
Opened 2020-07-28 21:04 UTC by msbemba

Added a note stating that permissions can be set only within the tenant and not for out of tenant users

2020-07-28 21:05 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2200

2020-07-28 21:05 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-07-29 01:23 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md
> +> The Permissions can be setup only within the current organization tenant. It is not possible to setup mailbox permissions with out of tenant Users.
```suggestion
> The permissions can be set up only within the current organization tenant. It is not possible to set up mailbox permissions with out of tenant users.
```

2020-07-29 01:25 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md
>  There are a few different ways you can access a mailbox once you've been given access. For help on this, refer to this article: [Access another person's mailbox](https://support.microsoft.com/office/
```suggestion
There are a few different ways you can access a mailbox once you've been given access. For help on this, refer to this article: [Access another person's mailbox](https://support.microsoft.com/office/A909AD30-E413-40B5-A487-0EA70B763081).
```

2020-07-29 01:25 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-29 01:53 UTC, JohanFreelancer9 approved these changes

2020-07-29 12:08 UTC, yogkumgit commented
@KwekuA Please merge this PR. Thanks.

2020-07-31 11:54 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2020-08-03 23:46 UTC, merged