Update configure-s-mime-settings-for-outlook-web-app.md
MicrosoftDocs/microsoft-365-docs pull request #2480
Opened 2020-07-28 22:15 UTC by msbemba

Added  AAD joined devices to the considerations

2020-07-28 22:15 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2411

2020-07-28 22:15 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-07-29 00:56 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app.md
> +To use S/MIME in Outlook on the web in the new [Microsoft Edge](https://www.microsoft.com/windows/microsoft-edge) web browser, you (or another admin) must set and configure the Microsoft Edge browser
```suggestion
To use S/MIME in Outlook on the web in the new [Microsoft Edge](https://www.microsoft.com/windows/microsoft-edge) web browser, you (or another admin) must set and configure the Microsoft Edge browser policy named **ExtensionInstallForcelist** to install the Microsoft S/MIME extension in the new Microsoft Edge. The policy value is `maafgiompdekodanheihhgilkjchcakm;https://outlook.office.com/owa/SmimeCrxUpdate.ashx`. And note that applying this policy requires domain-joined or Azure AD-joined devices, so using S/MIME in the new Microsoft Edge browser effectively requires domain-joined or Azure AD-joined devices.
```

2020-07-29 00:59 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app.md
> +To use S/MIME in Outlook on the web in the new [Microsoft Edge](https://www.microsoft.com/windows/microsoft-edge) web browser, you (or another admin) must set and configure the Microsoft Edge browser
Please change "in new Microsoft Edge" to "in the new Microsoft Edge", and change capitalization in the last sentence as indicated.

2020-07-29 00:59 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-29 01:52 UTC, JohanFreelancer9 approved these changes

2020-07-29 12:12 UTC, yogkumgit commented
@chrisda Please merge this PR. Thanks

2020-07-29 16:29 UTC, merged