Update release-options-in-office-365.md
MicrosoftDocs/microsoft-365-docs pull request #2490
Opened 2020-07-29 20:36 UTC by msbemba

Moved the important tag to the top with updates on Teams not available targetted release

2020-07-29 20:36 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2444

2020-07-29 20:37 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-07-30 02:53 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/release-options-in-office-365.md
> +> The Microsoft 365 updates described in this article apply to Microsoft 365, SharePoint Online, and Exchange Online. These release options are targeted, best effort ways to release changes to Micros
```suggestion
> The Microsoft 365 updates described in this article apply to Microsoft 365, SharePoint Online, and Exchange Online. These release options are targeted, best effort ways to release changes to Microsoft 365 but cannot be guaranteed at all times or for all updates. They do not apply to Skype for Business, Microsoft Teams, and related services.
```

2020-07-30 02:55 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-30 03:54 UTC, JohanFreelancer9 approved these changes

2020-07-30 07:36 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks.

2020-08-03 17:11 UTC, merged