Update customer-lockbox-requests.md
MicrosoftDocs/microsoft-365-docs pull request #2496
Opened 2020-07-29 22:24 UTC by msbemba

Added a note about using PowerShell to approve/deny customer lockbox requests

2020-07-29 22:24 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2483

2020-07-29 22:24 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-07-30 02:06 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-lockbox-requests.md
> +> Use the Set-AccessToCustomerDataRequest cmdlet to approve, deny, or cancel Microsoft 365 customer lockbox requests that control access to your data by Microsoft support engineers. For more informat
```suggestion
> Use the Set-AccessToCustomerDataRequest cmdlet to approve, deny, or cancel Microsoft 365 customer lockbox requests that control access to your data by Microsoft support engineers. For more information, see [Set-AccessToCustomerDataRequest](https://docs.microsoft.compowershell/module/exchange/set-accesstocustomerdatarequest?view=exchange-ps).
```

2020-07-30 02:10 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-lockbox-requests.md
> +> Use the Set-AccessToCustomerDataRequest cmdlet to approve, deny, or cancel Microsoft 365 customer lockbox requests that control access to your data by Microsoft support engineers. For more informat
The link also seems to be incorrect and does not work. Please check.

2020-07-30 02:11 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-lockbox-requests.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2020-07-30 02:12 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-30 02:32 UTC, JohanFreelancer9 reviewed
Please also confirm that the link is correct.

2020-07-30 03:45 UTC, msbemba commented
> Please also confirm that the link is correct.

updated the link.

2020-07-30 03:56 UTC, JohanFreelancer9 approved these changes

2020-07-30 08:04 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2020-08-17 22:02 UTC, merged