Update manage-windows-devices.md
MicrosoftDocs/microsoft-365-docs pull request #2510
Opened 2020-07-30 19:42 UTC by msbemba

Made changes to the URL as from august 1st the current Intune Azure Portal experience will be retired

2020-07-30 19:43 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-07-30 19:43 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2466

2020-07-31 03:43 UTC, JohanFreelancer9 commented on microsoft-365/business/manage-windows-devices.md
> +Go to [Endpoint Manager](https://endpoint.microsoft.com/#blade/Microsoft_Intune_Enrollment/EnrollmentMenu/overview) and On the Microsoft Intune page, select **Device enrollment** and on the **Overvie
```suggestion
Go to [Endpoint Manager](https://endpoint.microsoft.com/#blade/Microsoft_Intune_Enrollment/EnrollmentMenu/overview) and on the Microsoft Intune page, select **Device enrollment** and on the **Overview** page, make sure the **MDM authority** is **Intune**.
```

2020-07-31 03:45 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-31 07:18 UTC, JohanFreelancer9 approved these changes

2020-07-31 12:39 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks

2020-08-03 17:12 UTC, merged