Update remove-former-employee.md
MicrosoftDocs/microsoft-365-docs pull request #2511
Opened 2020-07-30 19:58 UTC by msbemba

Added Setup Call forwarding to people in your organization

2020-07-30 19:59 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-07-30 19:59 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2435

2020-07-31 03:26 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee.md
> +## Setup Call forwarding to people in your organization
```suggestion
## Set up Call forwarding to people in your organization
```

2020-07-31 03:31 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee.md
> +If you need to setup call forwarding for the terminated employees phone number, the call forwarding setting under calling policues can setup forwarding  where incoming calls can be forwarded to other
```suggestion
If you need to set up call forwarding for the terminated employee's phone number, the call forwarding setting under calling policies can set up forwarding where incoming calls can be forwarded to other users or can ring another person at the same time. For more information, see [Calling policies in Microsoft Teams](https://docs.microsoft.com/microsoftteams/teams-calling-policy).
```

2020-07-31 03:32 UTC, JohanFreelancer9 requested changes
Copy review.

2020-07-31 07:13 UTC, JohanFreelancer9 approved these changes

2020-07-31 12:54 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2020-08-03 23:47 UTC, merged