Update sp-compatible-pdf-readers-for-irm.md
MicrosoftDocs/microsoft-365-docs pull request #2527
Opened 2020-08-03 16:15 UTC by msbemba

Changed Foxit downloadable link(S)

2020-08-03 16:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-08-03 16:15 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2521

2020-08-04 04:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md
> +|Windows 8 (classic mode)  <br/> |Azure Information Protection app  <br/> Foxit Reader  <br/> NitroPDF  <br/> |[Download Azure Information Protection app](https://go.microsoft.com/fwlink/?linkid=8377
```suggestion
|Windows 8 (classic mode)  <br/> |Azure Information Protection app  <br/> Foxit Reader  <br/> NitroPDF  <br/> |[Download Azure Information Protection app](https://go.microsoft.com/fwlink/?linkid=837797) <br/> [Download Foxit Reader](https://www.foxitsoftware.com/downloads/#Foxit-PhantomPDF-Business/) <br/> [Download NitroPDF](https://www.gonitro.com/pdf-reader) <br/> |
```

2020-08-04 04:29 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md
> +|Windows 8.1  <br/> |Azure Information Protection app  <br/> Foxit Reader  <br/> NitroPDF  <br/> |[Download Azure Information Protection app](https://go.microsoft.com/fwlink/?linkid=837797) <br/> [Do
```suggestion
|Windows 8.1  <br/> |Azure Information Protection app  <br/> Foxit Reader  <br/> NitroPDF  <br/> |[Download Azure Information Protection app](https://go.microsoft.com/fwlink/?linkid=837797) <br/> [Download Foxit Reader](https://www.foxitsoftware.com/downloads/#Foxit-PhantomPDF-Business/) <br/> [Download NitroPDF](https://www.gonitro.com/pdf-reader) <br/> |
```

2020-08-04 04:29 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md
> +|Windows 10  <br/> |Azure Information Protection app  <br/> Foxit Reader  <br/> NitroPDF  <br/> |[Download Azure Information Protection app](https://go.microsoft.com/fwlink/?linkid=837797) <br/> [Dow
```suggestion
|Windows 10  <br/> |Azure Information Protection app  <br/> Foxit Reader  <br/> NitroPDF  <br/> |[Download Azure Information Protection app](https://go.microsoft.com/fwlink/?linkid=837797) <br/> [Download Foxit Reader](https://www.foxitsoftware.com/downloads/#Foxit-PhantomPDF-Business/) <br/> [Download NitroPDF](https://www.gonitro.com/pdf-reader) <br/> |
```

2020-08-04 04:29 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-04 13:53 UTC, JohanFreelancer9 approved these changes

2020-08-05 16:04 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2020-08-11 15:50 UTC, merged

2020-08-17 21:37 UTC, KCCross commented
Folks who own the original fwlink are no longer with the company. Created new fwlink. Also asked for ownership of the old fwlink to be transferred to the pubs security group for fwlinks just in case it exists elsewhere.

2020-08-17 21:37 UTC, KCCross commented
We also need to create one for Nitro

2020-08-17 21:47 UTC, msbemba commented
created a new PR # https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2631