Update managing-holds.md
MicrosoftDocs/microsoft-365-docs pull request #2530
Opened 2020-08-03 19:29 UTC by msbemba

Added a note for Enabling This feature via PS

2020-08-03 19:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-08-03 19:29 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2484

2020-08-04 02:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/managing-holds.md
> +> Custodial Holds cannot be turned ON or OFF from the Security & Compliance center Admin center. Aministrator needs to use Powershell to make this change. For more information, See [Set-CaseHoldPolic
```suggestion
> Custodian holds cannot be turned on or off from the Security & Compliance admin center. Administrators need to use PowerShell to make this change. For more information, see [Set-CaseHoldPolicy](https://docs.microsoft.com/powershell/module/exchange/set-caseholdpolicy?view=exchange-ps).
```

2020-08-04 02:58 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-04 13:50 UTC, JohanFreelancer9 approved these changes

2020-08-05 16:14 UTC, yogkumgit commented
@markjjo Please merge this PR. Thanks

2020-08-20 16:43 UTC, markjjo commented
Closing this PR. I have offline thread about this issue with support engineer who made this request and the engineering team. I will re-address this when it's determined if documentation needs to be updagted.

2020-08-20 16:43 UTC, closed without merging

2020-08-20 16:46 UTC, msbemba commented
@markjjo Thank you for the update.