Update set-up-atp-safe-links-policies.md
MicrosoftDocs/microsoft-365-docs pull request #2542
Opened 2020-08-04 21:57 UTC by msbemba

Step 3 can be used for all employees if there is a requirement to have more exceptions w.r.t email like customer rewrite URL etc. as the default policy has exceptions which has  Settings that apply to content except email. , made changes accordingly, So please review and approve.

2020-08-04 21:57 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-08-04 21:57 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2501

2020-08-05 02:07 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md
> +> ATP Safe Links policies with higher priority will take precedence. If a user is subject to two or more polices, only the higher priority policy will take effect. If you want the customer policy to
```suggestion
> ATP Safe Links policies with higher priority will take precedence. If a user is subject to two or more policies, only the higher priority policy will take effect. If you want the customer policy to take precedence, you need to raise the priority of the policy.
```

2020-08-05 02:09 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-05 15:03 UTC, JohanFreelancer9 approved these changes

2020-08-05 16:09 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks.

2020-08-12 23:17 UTC, merged