Update create-test-tune-dlp-policy.md
MicrosoftDocs/microsoft-365-docs pull request #2554
Opened 2020-08-06 17:39 UTC by msbemba

Added details about permissions to the page

2020-08-06 17:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-08-06 17:40 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2538

2020-08-07 02:01 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-test-tune-dlp-policy.md
> +3. While creating the role group, use the **Choose Roles** section to add the following role to the Role Group: **DLP Compliance Management**.
```suggestion
3. While creating the role group, use the **Choose Roles** section to add the following role to the role group: **DLP Compliance Management**.
```

2020-08-07 02:06 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-08-11 20:46 UTC, merged