Update update-dns-records-to-retain-current-hosting-provider.md
MicrosoftDocs/microsoft-365-docs pull request #2573
Opened 2020-08-10 04:18 UTC by msbemba

Corrected the steps for Updating customer records

2020-08-10 04:18 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-08-10 04:18 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2210

2020-08-10 07:41 UTC, JohanFreelancer9 commented on microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md
> +3. Under **DNS settings**, select **Custom Records**,
```suggestion
3. Under **DNS settings**, select **Custom Records**.
```

2020-08-10 07:55 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-08-10 16:14 UTC, JohanFreelancer9 approved these changes

2020-08-12 15:09 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks

2020-08-18 20:21 UTC, merged