Update apply-retention-labels-automatically.md
MicrosoftDocs/microsoft-365-docs pull request #2582
Opened 2020-08-10 16:03 UTC by msbemba

Added a line to clarify that Alias for a Managed Property cannot be used in the query; it must be the actual name of the Managed Property (e.g. RefinableString01)

2020-08-10 16:03 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-08-10 16:03 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2563

2020-08-10 16:52 UTC, JohanFreelancer9 commented on microsoft-365/compliance/apply-retention-labels-automatically.md
> +While Auto-Applying lables for searchable properties Alias for a Managed Property cannot be used in the query, it must be the actual name of the Managed Property (e.g. RefinableString01)
```suggestion
While auto-applying labels for searchable properties, an alias for a managed property cannot be used in the query. It must be the actual name of the managed property, for example, RefinableString01.
```

2020-08-10 16:54 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-11 05:01 UTC, JohanFreelancer9 approved these changes

2020-08-11 20:34 UTC, cabailey commented
#sign-off  Confirmed by engineering, merging.

2020-08-11 20:34 UTC, merged