Update remove-a-domain.md
MicrosoftDocs/microsoft-365-docs pull request #2584
Opened 2020-08-10 16:51 UTC by msbemba

Added "You get an error message when you try to remove a domain from Office 365 or if this is Still not working? Your domain might need to be manually removed."

2020-08-10 16:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-08-10 16:52 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2570

2020-08-10 16:57 UTC, JohanFreelancer9 commented on microsoft-365/admin/get-help-with-domains/remove-a-domain.md
> +You get an error message when you try to remove a domain from Office 365 or if this is Still not working? Your domain might need to be manually removed. [Give us a call](../contact-support-for-busine
```suggestion
Getting an error message when you try to remove a domain from Office 365 or this is still not working? Your domain might need to be manually removed. [Give us a call](../contact-support-for-business-products.md) and we'll help you take care of it!
```

2020-08-10 17:02 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-11 04:51 UTC, JohanFreelancer9 approved these changes

2020-08-11 08:24 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks.

2020-08-24 14:48 UTC, yogkumgit commented
@pebaum Gentle reminder, please merge this PR. Thanks

2020-09-08 17:36 UTC, pebaum commented
this edit doesn't follow product naming guidelines.

2020-09-08 17:36 UTC, closed without merging