Update data-classification-overview.md
MicrosoftDocs/microsoft-365-docs pull request #2585
Opened 2020-08-10 19:58 UTC by msbemba

Edited prerequisites based on https://opdhsblobprod04.blob.core.windows.net/contents/e0993bf6e82e4fa8ac18b48839521869/2ce5e803079c3427c011efbce08b900a?sv=2018-03-28&sr=b&si=ReadPolicy&sig=KAG1lGSeWNpMVjfNAkfb1pKjGDpk8kuCyiMNPbZE%2BpA%3D&st=2020-08-10T19%3A40%3A49Z&se=2020-08-11T19%3A50%3A49Z

2020-08-10 19:58 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-08-10 19:58 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2568

2020-08-11 04:43 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-overview.md
> +- Microsoft 365 E5 Compliance add on ( Requires Microsoft 365 E3 or Office 365 E3 + EMS E3 )
```suggestion
- Microsoft 365 E5 Compliance add-on (Requires Microsoft 365 E3 or Office 365 E3 + EMS E3)
```

2020-08-11 04:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-overview.md
> +- Microsoft 365 E5/A5 Info Protection & Governance (Requires AIP Plan 1 or EMS E3 + Exchange Online, SharePoint Online or OneDrive for business)
```suggestion
- Microsoft 365 E5/A5 Info Protection & Governance (Requires AIP Plan 1 or EMS E3 + Exchange Online, SharePoint Online, or OneDrive)
```

2020-08-11 04:48 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-11 06:50 UTC, JohanFreelancer9 approved these changes

2020-08-11 08:44 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks.

2020-08-11 20:53 UTC, chrfox commented
@msbemba - The link you included at the start of this PR is bad, I don't know where you got your information from.  I have queried the owning PM and will update as necessary

2020-08-11 20:53 UTC, closed without merging

2020-08-11 21:22 UTC, msbemba commented
Thank you @chrfox I got it from docs.microsoft.com - https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance

The link that has a PDF file for Detailed Microsoft 365 Compliance Licensing Comparison

Thanks
Sri