Update gdpr-dsr-Office365.md
MicrosoftDocs/microsoft-365-docs pull request #2609
Opened 2020-08-13 19:06 UTC by msbemba

Added yammer content search to the doc

2020-08-13 19:06 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-08-13 19:06 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2571

2020-08-14 05:18 UTC, JohanFreelancer9 commented on microsoft-365/compliance/gdpr-dsr-Office365.md
> +When looking for personal data within the larger set of data your organization creates and stores using in Office 365, you may want to first consider which applications people have most likely used t
```suggestion
When looking for personal data within the larger set of data your organization creates and stores in Office 365, you may want to first consider which applications people have most likely used to author the data you're looking for. Microsoft estimates that over 90% of an organization's data that is stored in Office 365 is authored in Word, Excel, PowerPoint, OneNote, and Outlook. Documents authored in these Office applications, even if purchased through Microsoft 365 Apps for enterprise or an Office perpetual license, are most likely stored on a SharePoint Online site, in a user's OneDrive account, or in a user's Exchange Online mailbox. That means you can use the Content Search eDiscovery tool to search (and perform other DSR-related actions) across SharePoint Online sites, OneDrive accounts, and Exchange Online mailboxes (including the sites and mailboxes associated with Microsoft 365 Groups, Microsoft Teams, EDU Assignments) to find documents and mailbox items that may be relevant to the DSR you're investigating. You can also use the Content Search tool to discover Customer Data authored in other Office 365 applications. Moreover, you can now use the Content Search tool for Yammer content if Yammer is running in native mode.
```

2020-08-14 05:21 UTC, JohanFreelancer9 commented on microsoft-365/compliance/gdpr-dsr-Office365.md
> +When looking for personal data within the larger set of data your organization creates and stores using in Office 365, you may want to first consider which applications people have most likely used t
```suggestion
When looking for personal data within the larger set of data your organization creates and stores in Office 365, you may want to first consider which applications people have most likely used to author the data you're looking for. Microsoft estimates that over 90% of an organization's data that is stored in Office 365 is authored in Word, Excel, PowerPoint, OneNote, and Outlook. Documents authored in these Office applications, even if purchased through Microsoft 365 Apps for enterprise or an Office perpetual license, are most likely stored on a SharePoint Online site, in a user's OneDrive for Business account, or in a user's Exchange Online mailbox. That means you can use the Content Search eDiscovery tool to search (and perform other DSR-related actions) across SharePoint Online sites, OneDrive for Business accounts, and Exchange Online mailboxes (including the sites and mailboxes associated with Microsoft 365 Groups, Microsoft Teams, EDU Assignments) to find documents and mailbox items that may be relevant to the DSR you're investigating. You can also use the Content Search tool to discover Customer Data authored in other Office 365 applications. Moreover, you can now use the Content Search tool for Yammer content if Yammer is running in native mode.
```

2020-08-14 05:22 UTC, JohanFreelancer9 commented on microsoft-365/compliance/gdpr-dsr-Office365.md
> +When looking for personal data within the larger set of data your organization creates and stores using in Office 365, you may want to first consider which applications people have most likely used t
Please remove the word "using" from the first line. Also, change the last line as indicated.

2020-08-14 05:22 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-14 13:17 UTC, JohanFreelancer9 approved these changes

2020-08-14 15:58 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2020-08-24 14:51 UTC, yogkumgit commented
@robmazz Gentle reminder, please merge this PR. Thanks

2020-08-25 17:14 UTC, robmazz commented
@msbemba - thanks for the feedback. All updates to GDPR content must be approved by MS CELA and the frontline CELA reps for each workload. Closing this PR, but will forward recommendation to CELA contacts for review.

2020-08-25 17:14 UTC, closed without merging