Update create-retention-policies.md
MicrosoftDocs/microsoft-365-docs pull request #2610
Opened 2020-08-13 19:25 UTC by msbemba

added a line to the configuration information for microsoft 365 groups that the only way to manage teams conversations is to apply policy on teams conversations location and not on m365 groups.

2020-08-13 19:25 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-08-13 19:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2601

2020-08-14 05:03 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-retention-policies.md
> +A retention policy applied to a Microsoft 365 group includes both the group mailbox and site. A retention policy applied to a Microsoft 365 group protects the resources created by a Microsoft 365 gro
```suggestion
A retention policy applied to a Microsoft 365 group includes both the group mailbox and site. A retention policy applied to a Microsoft 365 group protects the resources created by a Microsoft 365 group, which includes files in Microsoft Teams. However, the only way to manage Teams conversations is through the Teams Conversations location.
```

2020-08-14 05:03 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-08-14 23:26 UTC, cabailey commented
Updated with more accurate wording, closing.

2020-08-14 23:26 UTC, closed without merging

2020-08-14 23:30 UTC, msbemba commented
Thank you @cabailey