Update cortana-integration.md
MicrosoftDocs/microsoft-365-docs pull request #2616
Opened 2020-08-14 21:26 UTC by msbemba

Added method to find out usage location - Reference https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-user-accounts-with-microsoft-365-powershell?view=o365-worldwide#view-additional-property-values-for-accounts

2020-08-14 21:26 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-08-14 21:26 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2594

2020-08-15 01:40 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/cortana-integration.md
> +- New Microsoft 365 experiences, such as the Briefing email and Play My Emails, will be enabled using Cortana enterprise services and fully comply with those promises. These features are currently av
```suggestion
- New Microsoft 365 experiences, such as the Briefing email and Play My Emails, will be enabled using Cortana enterprise services and fully comply with those promises. These features are currently available in the English (United States) market for users with mailboxes in the US geo, and for employees of multi-national corporations with US-based mailboxes. For more information on finding the usage location, Please visit [View additional property values for accounts](https://docs.microsoft.com/microsoft-365/enterprise/view-user-accounts-with-microsoft-365-powershell?view=o365-worldwide#view-additional-property-values-for-accounts).
```

2020-08-15 01:41 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/cortana-integration.md
> +- New Microsoft 365 experiences, such as the Briefing email and Play My Emails, will be enabled using Cortana enterprise services and fully comply with those promises. These features are currently av
Please add a period after the link.

2020-08-15 01:44 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-16 15:56 UTC, JohanFreelancer9 approved these changes

2020-08-17 13:46 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2020-08-17 19:06 UTC, merged