Update investigate-malicious-email-that-was-delivered.md
MicrosoftDocs/microsoft-365-docs pull request #2655
Opened 2020-08-20 13:47 UTC by msbemba

Corrected Link in the note and related topics for remediating malicious email delivered in office 365. This action was taken as the previous links were broken.

2020-08-20 13:47 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-08-20 13:47 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2642

2020-08-21 04:26 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md
> +> Jump to the remediation article [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365?view=o365-worldwide).
```suggestion
> To learn more about remediation, see [Remediate malicious email that was delivered in Office 365](https://docs.microsoft.com/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365?view=o365-worldwide).
```

2020-08-21 04:26 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-24 13:11 UTC, yogkumgit commented
@JohanFreelancer9 please copy review. Thanks

2020-08-24 16:40 UTC, JohanFreelancer9 approved these changes

2020-09-03 16:25 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2020-09-03 18:59 UTC, MSFTTracyP requested changes
Please don't make the article more dry than it has to be. Leave the phrasing on line 29. I have no problem with the 269 edit. Thanks for that. I really appreciate your work on the links. But please retain the action verbs where we can sneak them in.

2020-09-04 06:54 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md
> +> To learn more about remediation, see [Remediate malicious email that was delivered in Office 365](https://docs.microsoft.com/microsoft-365/security/office-365-security/remediate-malicious-email-del
```suggestion
> Jump to the remediation article [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365?view=o365-worldwide).
```

2020-09-04 06:56 UTC, JohanFreelancer9 requested changes
Copy review -as per @MSFTTracyP's request.

2020-09-04 15:28 UTC, JohanFreelancer9 approved these changes

2020-09-07 12:35 UTC, yogkumgit commented
@MSFTTracyP The PR is ready to be merged. Kindly merge it. Thanks.

2020-09-16 20:27 UTC, merged