Update secure-your-business-data.md
MicrosoftDocs/microsoft-365-docs pull request #2668
Opened 2020-08-21 16:56 UTC by msbemba

Setting the "Notify" action for the transport rule "Anti-ransomware rule: warn users" results in double-up emails that confuse recipients and do not provide a clear message about the action required. Instead changed it to '"Prepend a Disclaimer" so that the warning is stamped onto the original email message, making it clear what content the warning applies to, and providing a more familiar experience to the user.

2020-08-21 16:57 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2643

2020-08-21 16:59 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-08-22 03:17 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/secure-your-business-data.md
> +|Do the following . . .  <br/> |Prepend a Disclaimer  <br/> |Block the message . . . reject the message and include an explanation  <br/> |
```suggestion
|Do the following . . .  <br/> |Prepend a disclaimer  <br/> |Block the message . . . reject the message and include an explanation  <br/> |
```

2020-08-22 03:19 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-23 01:08 UTC, JohanFreelancer9 approved these changes

2020-08-24 13:04 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks.

2020-09-03 19:07 UTC, merged