Update transfer-data-manually.md
MicrosoftDocs/microsoft-365-docs pull request #2669
Opened 2020-08-21 18:32 UTC by msbemba

added links on moving One note files

2020-08-21 18:33 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2644

2020-08-21 18:33 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-08-22 03:12 UTC, JohanFreelancer9 commented on microsoft-365/admin/get-help-with-domains/transfer-data-manually.md
> +Ask users to [Backup Onenote](https://support.microsoft.com/office/back-up-notes-f58b34b0-611d-435e-87fa-7942a1767af4?ui=en-us&rs=en-us&ad=us) and [Restore notes from a backup](https://support.micros
```suggestion
Ask users to [Back up OneNote](https://support.microsoft.com/office/back-up-notes-f58b34b0-611d-435e-87fa-7942a1767af4?ui=en-us&rs=en-us&ad=us) and to [Restore notes from a backup](https://support.microsoft.com/en-us/office/restore-notes-from-a-backup-5daf9cb0-6769-4998-a5de-f044fdd0d831?ui=en-us&rs=en-us&ad=us) to their new subscriptions.
```

2020-08-22 03:13 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-23 00:57 UTC, JohanFreelancer9 approved these changes

2020-08-24 13:07 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks.

2020-09-08 17:33 UTC, merged