Update ipv6-support.md
MicrosoftDocs/microsoft-365-docs pull request #2711
Opened 2020-08-27 22:09 UTC by msbemba

Added MS Teams to the document

2020-08-27 22:09 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-08-27 22:09 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2693

2020-08-28 05:40 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ipv6-support.md
> +### MS Teams and IPV6
```suggestion
### Microsoft Teams and IPV6
```

2020-08-28 05:43 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ipv6-support.md
> +MS Teams Support IPV6. If you want to control communications to MS teams, use the IP address ranges in  [Office 365 URLs and IP address ranges](urls-and-ip-address-ranges.md
```suggestion
Microsoft Teams supports IPV6. If you want to control communications to Microsoft teams, use the IP address ranges in [Office 365 URLs and IP address ranges](urls-and-ip-address-ranges.md).
```

2020-08-28 05:43 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-28 07:30 UTC, rdekramer commented
Thanks! To refine it further: could we add that Direct Routing only supports IPv4? The teams service and client supports both ipv4 and ipv6.

2020-08-28 10:02 UTC, msbemba commented on microsoft-365/enterprise/ipv6-support.md
> +MS Teams Support IPV6. If you want to control communications to MS teams, use the IP address ranges in  [Office 365 URLs and IP address ranges](urls-and-ip-address-ranges.md
Making some more changes.. Will request copy review again

2020-08-28 10:04 UTC, msbemba commented on microsoft-365/enterprise/ipv6-support.md
> +### MS Teams and IPV6
Made the change

2020-08-28 10:05 UTC, msbemba commented
@JohanFreelancer9  Can you copy review?

2020-08-28 14:03 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ipv6-support.md
> +MS Teams Direct Routing only supports IPv4. MS Teams service and client supports both ipv4 and ipv6. If you want to control communications to MS Teams, use the IP address ranges in  [Office 365 URLs
```suggestion
Microsoft Teams Direct Routing only supports IPv4. Microsoft Teams service and client support both IPv4 and IPv6. If you want to control communications to Microsoft Teams, use the IP address ranges in [Office 365 URLs and IP address ranges](urls-and-ip-address-ranges.md).
```

2020-08-28 14:05 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-28 14:08 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-29 03:38 UTC, JohanFreelancer9 approved these changes

2020-09-01 13:30 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2020-09-08 13:58 UTC, yogkumgit commented
@kelleyvice-msft Gentle reminder, please merge this PR. Thanks

2020-09-18 14:21 UTC, yogkumgit commented
@kelleyvice-msft  Gentle reminder, Please merge this PR. Thanks.

2020-09-23 13:46 UTC, yogkumgit commented
@kelleyvice-msft This is pending almost for a month now, Please merge this PR. Thanks.

2020-09-23 13:50 UTC, merged

2020-09-23 13:50 UTC, kelleyvice-msft commented
Apologies. Notifications for this PR were being inadvertently filtered into a subfolder.