Update allowselfservicepurchase-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #2718
Opened 2020-08-28 18:40 UTC by msbemba

Added syntax to update service point manager security protocol to TLS1.2 (tested)

2020-08-28 18:40 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2681

2020-08-28 18:40 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-08-29 02:26 UTC, JohanFreelancer9 commented on microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md
> +You can also Upgrade to TLS 1.2, See more  [How to enable TLS 1.2?](https://docs.microsoft.com/mem/configmgr/core/plan-design/security/enable-tls-1-2)
```suggestion
You can also upgrade to TLS 1.2. For details, see [How to enable TLS 1.2?](https://docs.microsoft.com/mem/configmgr/core/plan-design/security/enable-tls-1-2)
```

2020-08-29 02:30 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-29 16:06 UTC, JohanFreelancer9 approved these changes

2020-08-31 14:41 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks.

2020-08-31 18:18 UTC, cmcatee-MSFT commented
@yogkumgit I'm waiting on confirmation from the PM before I approve this PR.

2020-09-18 14:23 UTC, yogkumgit commented
@cmcatee-MSFT  Have we got any update, Please merge this PR. Thanks.

2021-01-18 13:48 UTC, yogkumgit commented
@cmcatee-MSFT Gentle reminder.

2021-08-19 20:58 UTC, merged