Update prerequisites.md
MicrosoftDocs/microsoft-365-docs pull request #2822
Opened 2020-09-13 01:36 UTC by msbemba

removed - Enterprise Mobility + Security E3 from Azure AAD p2

2020-09-13 01:36 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-09-13 01:36 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2783

2020-09-14 01:59 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/get-ready/prerequisites.md
> +|Azure Active Directory Premium P2     |- Microsoft 365 E5<br>- Microsoft 365 E3 + Microsoft 365 *E5* Security Add-on<br>- Enterprise Mobility + Security E5<br><br>- Azure Active Directory Premium P2
```suggestion
|Azure Active Directory Premium P2     |- Microsoft 365 E5<br>- Microsoft 365 E3 + Microsoft 365 *E5* Security Add-on<br>- Enterprise Mobility + Security E5<br><br>- Azure Active Directory Premium P2|  Provides access to Microsoft cloud services; allows AutoPilot to register devices      |
```

2020-09-14 02:02 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-14 15:02 UTC, JohanFreelancer9 approved these changes

2020-09-14 15:57 UTC, jaimeo commented
@siavoi can you confirm this edit is accurate?

2020-09-17 16:17 UTC, jaimeo commented
Per the SME, this edit is not valid. SME is providing a comprehensive update to this article shortly.

2020-09-17 16:28 UTC, msbemba commented
Thank you, Jaimeo. Will wait for the update from SME.

2020-09-17 16:28 UTC, closed without merging