Update microsoft-365-vpn-implement-split-tunnel.md
MicrosoftDocs/microsoft-365-docs pull request #2837
Opened 2020-09-14 22:07 UTC by msbemba

Added a question Faq on Teams support scenario with browser and desktop client.

2020-09-14 22:08 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2784

2020-09-14 22:08 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-09-15 03:52 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md
> +### Does split-tunnel configuration  works for  Teams running in a browser?
```suggestion
### Does split-tunnel configuration work for Teams running in a browser?
```

2020-09-15 03:55 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md
> +**No**, It does not. It works only on  Microsoft Teams client version 1.3.00.13565 or greater. This version includes improvements in how the client detects available network paths.
```suggestion
**No**, it does not. It works only on Microsoft Teams client version 1.3.00.13565 or greater. This version includes improvements in how the client detects available network paths.
```

2020-09-15 03:56 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-15 15:58 UTC, JohanFreelancer9 approved these changes

2020-09-17 08:02 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks.

2020-09-28 15:35 UTC, merged