Update threat-explorer.md
MicrosoftDocs/microsoft-365-docs pull request #2915
Opened 2020-09-21 22:30 UTC by andypunt

Updated real-time detections with Real-time detections

2020-09-25 15:30 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-09-26 03:49 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer.md
>  > Network Message ID maps the click back to specific mails when you search through Explorer or associated 3rd party tools via Network Message ID. Searching through the Network Message ID will give ad
```suggestion
> Network Message ID maps the click back to specific mails when you search through Explorer or associated third-party tools via Network Message ID. Searching through the Network Message ID will give admins the specific email associated with a click result. On export, having the correlating identification of Network Message ID makes for quicker and more powerful analysis.
```

2020-09-26 03:50 UTC, JohanFreelancer9 requested changes
Copy review - two additional minor edits, please.

2020-09-28 13:17 UTC, yogkumgit commented
@andypunt Please implement the review comments. Thanks.

2020-09-29 04:05 UTC, JohanFreelancer9 approved these changes

2020-10-23 21:31 UTC, MSFTTracyP approved these changes
Update

2020-10-23 21:44 UTC, merged