Update collaborate-in-site.md
MicrosoftDocs/microsoft-365-docs pull request #2929
Opened 2020-09-22 19:03 UTC by msbemba

Changed from Azure org settings to External collaboration settings

2020-09-22 19:03 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2921

2020-09-22 19:04 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-09-23 02:34 UTC, JohanFreelancer9 commented on microsoft-365/solutions/collaborate-in-site.md
> +## Azure External Collaboration settings
```suggestion
## Azure external collaboration settings
```

2020-09-23 02:37 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-23 23:22 UTC, JohanFreelancer9 approved these changes

2020-09-25 13:38 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2020-09-25 13:50 UTC, merged