Update migrate-from-e3.md
MicrosoftDocs/microsoft-365-docs pull request #2933
Opened 2020-09-22 19:33 UTC by msbemba

Added section for mailbox size as they are downgrading from 100Gb to 50Gb

2020-09-22 19:33 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2911

2020-09-22 19:33 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-09-23 02:25 UTC, JohanFreelancer9 commented on microsoft-365/business/migrate-from-e3.md
> +Microsoft 365 Business premium has 50Gb storage limit as it uses Exchange Online Plan 1. While Migrating to Microsoft 365 Business Premium, If any of your users are exceeding 50GB mailbox storage  it
```suggestion
Microsoft 365 Business Premium has a 50 GB storage limit as it uses Exchange Online Plan 1. While migrating to Microsoft 365 Business Premium, if any of your users exceed 50 GB of mailbox storage, it is recommended that you assign this user an Exchange Online Plan 2 and remove the Exchange Online Plan 1 as it's not feasible to assign both.
```

2020-09-23 02:25 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-23 23:21 UTC, JohanFreelancer9 approved these changes

2020-09-25 13:47 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks.

2020-09-28 16:25 UTC, merged