Update convert-user-mailbox-to-shared-mailbox.md
MicrosoftDocs/microsoft-365-docs pull request #2952
Opened 2020-09-24 11:36 UTC by msbemba

option to convert the user mailbox to a shared mailbox is no longer available in the m365 admin center.

2020-09-24 11:36 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-09-24 11:36 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2833

2020-09-24 13:51 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md
>  If the mailbox is smaller than 50 GB, you can [remove the license from the user](../manage/remove-licenses-from-users.md), and stop paying for it. Don't delete the user's old mailbox. The shared mail
```suggestion
```

2020-09-24 13:52 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md
>  If the mailbox is smaller than 50 GB, you can [remove the license from the user](../manage/remove-licenses-from-users.md), and stop paying for it. Don't delete the user's old mailbox. The shared mail
This is duplication of Number 4 above, and I would suggest removing it.

2020-09-25 04:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md
>     > It's not required to reset the user's password during mailbox conversion. However, if the password is not reset, **the original username and password continue to work** after the mailbox convers
```suggestion
> It's not required to reset the user's password during mailbox conversion. However, if the password is not reset, **the original username and password continue to work** after the mailbox conversion is finished.
```

2020-09-25 04:16 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-26 04:12 UTC, JohanFreelancer9 approved these changes

2020-09-26 04:25 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md
```suggestion
```

2020-09-26 04:27 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md
Please just remove the extra blank line.

2020-09-28 15:36 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2020-10-02 00:19 UTC, merged