Update office-365-groups.md
MicrosoftDocs/microsoft-365-docs pull request #2960
Opened 2020-09-24 21:23 UTC by msbemba

The options have changed, added steps reflecting the new options to access groups activity

2020-09-24 21:24 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2932

2020-09-24 21:24 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-09-25 04:09 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/office-365-groups.md
> +2. From the options, Select **View more** under **Active users - Microsoft 365 Services****, then Select a report** drop-down, select **Office 365** \> **Groups activity**.
```suggestion
2. From the options, select **View more** under **Active users - Microsoft 365 Services**.
3. From the **Select a report drop-down**, select **Office 365** \> **Groups activity**.
```

2020-09-25 04:09 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-26 04:08 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/office-365-groups.md
> +3. From the **Select a report drop-down**, select **Office 365** \> **Groups activity**.
```suggestion
3. From the **Select a report** drop-down, select **Office 365** \> **Groups activity**.
```

2020-09-26 04:08 UTC, JohanFreelancer9 reviewed
Copy review - one more, please.

2020-09-28 16:23 UTC, merged