Update data-move-faq.md
MicrosoftDocs/microsoft-365-docs pull request #2982
Opened 2020-09-25 23:33 UTC by andybergen

SFB and signup changes.

2020-09-28 15:40 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-09-29 07:07 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/data-move-faq.md
> +Teams files are stored in SharePoint Online and Teams chat files are stored in OneDrive for Business.  Voicemail, calendar, chat history, and contacts are stored in Exchange Online.  In many cases, E
```suggestion
Teams files are stored in SharePoint Online and Teams chat files are stored in OneDrive for Business.  Voicemail, calendar, chat history, and contacts are stored in Exchange Online.  In many cases, Exchange Online, SharePoint Online, and OneDrive for Business are already used by the customer in the local datacenter geo and are also part of the Microsoft 365 migration program for eligible customer countries.
```

2020-09-29 07:08 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/data-move-faq.md
> +completed until both services are migrated.  Exchange Online and SharePoint Online/OneDrive for Business often migrate at separate times and independently from one another.  Customer tenant admins re
```suggestion
completed until both services are migrated.  Exchange Online and SharePoint Online/OneDrive for Business often migrate at separate times and independently from one another. Customer tenant admins receive confirmation in Message Center when each service migration is completed and can view the data location card in the Admin Center at any time to confirm the core customer data at rest location for 
```

2020-09-29 07:18 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/data-move-faq.md
> +365 customer data on the [Microsoft 365 interactive datacenter maps ](https://office.com/datamaps) as a reference for the current default core customer data at rest locations for new tenants.  You ca
```suggestion
365 customer data on the [Microsoft 365 interactive datacenter maps](https://office.com/datamaps) as a reference for the current default core customer data at rest locations for new tenants.  You can verify the location of your customer data at rest via the Data Location section under your Organization Profile in the Microsoft 365 Admin Center.  
```

2020-09-29 07:20 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/data-move-faq.md
> +Physical proximity to a Microsoft 365 datacenter is not a guarantee for a better networking performance. There are many factors and components that affect the network performance between the end-user
```suggestion
Physical proximity to a Microsoft 365 datacenter is not a guarantee for a better networking performance. There are many factors and components that affect the network performance between the end-user and the Microsoft 365 service. For more information about this and performance tuning, see [Network planning and performance tuning for Microsoft 365](network-planning-and-performance.md).
```

2020-09-29 07:23 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/data-move-faq.md
> +SharePoint Online and OneDrive for Business cannot migrate to the new datacenter geo at the tenant level through this program.  The customer administrator can configure OneDrive for Business shares t
```suggestion
SharePoint Online and OneDrive for Business cannot migrate to the new datacenter geo at the tenant level through this program. The customer administrator can configure OneDrive for Business shares to move to any available region using Multi-Geo, but the default location for the tenant cannot be changed once Multi-Geo has been configured for a tenant.
```

2020-09-29 07:36 UTC, JohanFreelancer9 requested changes
Copy review - a few minor edits.

2020-10-01 14:10 UTC, merged