Update insider-risk-management-configure.md
MicrosoftDocs/microsoft-365-docs pull request #2984
Opened 2020-09-26 03:20 UTC by msbemba

Added a note to mention that these role groups on PIM

2020-09-26 03:20 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-09-26 03:20 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2941

2020-09-26 03:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/insider-risk-management-configure.md
> +>[!Note]
```suggestion
> [!NOTE]
```

2020-09-26 03:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/insider-risk-management-configure.md
> +>These Role groups are currently not supported on Privileged Identity Management (PIM). To Learn more about PIM, See [Azure AD roles in Privileged Identity Management](https://docs.microsoft.com/en-u
```suggestion
> These role groups are currently not supported on Privileged Identity Management (PIM). To learn more about PIM, see [Assign Azure AD roles in Privileged Identity Management](https://docs.microsoft.com/azure/active-directory/privileged-identity-management/pim-how-to-add-role-to-user).
```

2020-09-26 03:57 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-29 05:09 UTC, JohanFreelancer9 approved these changes

2020-09-29 15:30 UTC, merged