Update update-phone-number-and-email-address.md
MicrosoftDocs/microsoft-365-docs pull request #3058
Opened 2020-10-02 20:03 UTC by msbemba

Changed the navigation to Correct alternate phone/email address

2020-10-02 20:03 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-02 20:03 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3030

2020-10-03 02:00 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/update-phone-number-and-email-address.md
> +3. In the **Privacy** Tab under  **Contact Preferences** section, select **Contact preferences for admins only**. Update your mobile, phone, and alternate email address. Make sure you use something d
```suggestion
3. In the **Privacy** tab under **Contact Preferences**, select **Contact preferences for admins only**. Update your mobile, phone, and alternate email address. Make sure you use something different from your Microsoft email address for your alternate email address.
```

2020-10-03 02:01 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-03 13:47 UTC, JohanFreelancer9 approved these changes

2020-10-05 12:32 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2020-10-13 18:46 UTC, merged