Update bookings-overview.md
MicrosoftDocs/microsoft-365-docs pull request #3081
Opened 2020-10-06 18:59 UTC by msbemba

Added steps to connect bookings to Facebook as the Bookings Page redirects users to this document when they are trying to connect to Facebook

2020-10-06 19:00 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-06 19:00 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3029

2020-10-07 07:20 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-overview.md
> +## Connect Microsoft Bookings to Facebook Page.
```suggestion
## Connect Microsoft Bookings to a Facebook page
```

2020-10-07 07:22 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-overview.md
> +1)To remove or connect Microsoft Bookings and Facebook page, open your business Facebook page.
```suggestion
1. To remove or connect Microsoft Bookings and a Facebook page, open the Facebook page of your organization.
```

2020-10-07 07:23 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-overview.md
> +2)Select **Settings** from the upper right corner and chose **Partner Apps and Services** option from the left panel.
```suggestion
2. Select **Settings** from the upper right corner and chose the **Partner Apps and Services** option from the left panel. 
```

2020-10-07 07:27 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-overview.md
> +3)Next hit the **Add Service** button, select **Microsoft Bookings** and click **Add Service** option.
```suggestion
3. Next, click the **Add Service** button, choose **Microsoft Bookings**, and select the **Add Service** option.
```

2020-10-07 07:30 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-overview.md
> +4)Instantly, a new tab will open. When it is visible, sign into your Office 365 account and find your booking calendars. Here, select the calendar you want to connect to your Facebook page and choose
```suggestion
4. A new tab will open instantly. When it is visible, sign in to your Office 365 account and find your Booking calendars. Select the calendar you want to connect to your Facebook page and choose the **Connect** option.
```

2020-10-07 07:32 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-overview.md
> +5)Once you complete the above step, the tab will close, and you’ll return to Facebook. Now you’re all set to receive Bookings through your Facebook page.
```suggestion
5. Once you've completed the previous step, the tab will close and you’ll be returned to Facebook. Now you’re all set to receive Bookings through your Facebook page.
```

2020-10-07 07:37 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-overview.md
> +6)If you would like to remove Microsoft Bookings and Facebook page, simply select Remove Service on the Page Action button in the Microsoft Bookings tab.
```suggestion
6. If you would like to remove Microsoft Bookings from your Facebook page, simply select **Remove Service** on the **Page Action** button in the Microsoft Bookings tab.
```

2020-10-07 07:40 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-12 16:16 UTC, JohanFreelancer9 commented
@msbemba Please look at the rich diff. The numbering is not formatted correctly.

2020-10-12 16:24 UTC, JohanFreelancer9 approved these changes

2020-10-23 14:49 UTC, yogkumgit commented
@kwekuako Gentle reminder please merge this PR. Thanks.

2020-11-26 16:43 UTC, closed without merging