clarify remove encryption for different OME ver
MicrosoftDocs/microsoft-365-docs pull request #3093
Opened 2020-10-08 05:28 UTC by samschan-ms

@KCCross  please review this

2020-10-08 12:46 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-10-08 15:59 UTC, JohanFreelancer9 commented on microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md
> +You can define mail flow rules for triggering remove message encryption with the new OME capabilities by using the EAC or Windows PowerShell cmdlets.  When your email users send encrypted messages, y
```suggestion
You can define mail flow rules for triggering remove message encryption with the new OME capabilities by using the EAC or Windows PowerShell cmdlets.  When your email users send encrypted messages, you can define these rules to decrypt messages that are from within your organization.  You cannot decrypt encrypted messages originating from outside your organization.
```

2020-10-08 16:00 UTC, JohanFreelancer9 commented on microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md
> +You can define mail flow rules for triggering remove message encryption without the new OME capabilities by using the EAC or Windows PowerShell cmdlets.  When your email users send encrypted messages
```suggestion
You can define mail flow rules for triggering remove message encryption without the new OME capabilities by using the EAC or Windows PowerShell cmdlets.  When your email users send encrypted messages, you can define these rules to decrypt messages from within your organization. You cannot decrypt encrypted messages originating from outside your organization.
```

2020-10-08 16:01 UTC, JohanFreelancer9 commented on microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md
> +When your email users send encrypted messages without the new OME capabilities, recipients of those messages need to sign in to the encryption portal to view and respond the encrypted replies. You ca
```suggestion
When your email users send encrypted messages without the new OME capabilities, recipients of those messages need to sign in to the encryption portal to view and respond to the encrypted replies. You can create mail flow rules to automatically remove encryption from replies so email users in your organization can view the replies directly in the mail client.
```

2020-10-08 16:02 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-09 04:32 UTC, JohanFreelancer9 approved these changes

2020-10-09 07:40 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks.

2020-10-23 23:13 UTC, KCCross commented
Samson, we need to talk about this. I'm pretty sure we covered this elsewhere in several other ways.

2020-10-23 23:13 UTC, closed without merging