Update about-admin-roles.md
MicrosoftDocs/microsoft-365-docs pull request #3095
Opened 2020-10-08 11:14 UTC by msbemba

Updated service admin to Service Support Admin

2020-10-08 11:14 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-08 11:14 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3090

2020-10-08 17:06 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/about-admin-roles.md
> +|Service Support Admin   |   Assign the Service Support Admin role as an additional role to admins or users whose role doesn't include the following, but still need to do the following: <br> - Open a
```suggestion
|Service Support admin   |   Assign the Service Support admin role as an additional role to admins or users whose role doesn't include the following, but still need to do the following: <br> - Open and manage service requests <br> - View and share message center posts   |
```

2020-10-08 17:07 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-09 14:19 UTC, JohanFreelancer9 approved these changes

2020-10-12 03:06 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2020-10-13 00:06 UTC, merged

2020-10-15 18:40 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3003