Update search-the-audit-log-in-security-and-compliance.md
MicrosoftDocs/microsoft-365-docs pull request #3107
Opened 2020-10-08 22:09 UTC by SheaAhna

In response to frequent customer inquiries regarding the interplay of thumbnail fetching and file previewed and file accessed events in the audit log we'd like to add an FAQ addressing the questions that the field regularly receives.

2020-10-12 08:10 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-10-12 09:38 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +<b>Frequently asked questions regarding the “File Previewed” and “File Accessed” events</b> <br>
```suggestion
<b>Frequently asked questions regarding the “File Previewed” and “File Accessed” events</b> <br>

```

2020-10-12 09:40 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +A: We are not aware of scenarios where non-user actions generate events like the above. User actions like opening a user profile card by clicking their name or email address from OWA would generate s
```suggestion
A: We are not aware of scenarios where non-user actions generate events like these. User actions like opening a user profile card by clicking their name or email address from OWA would generate similar events. <br>
```

2020-10-12 09:41 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +<b>Q: Are calls the OneDriveMpc-Transform_Thumbnail always intentionally being triggered by the user? </b><br>
```suggestion
<b>Q: Are calls to the OneDriveMpc-Transform_Thumbnail always intentionally being triggered by the user? </b><br>
```

2020-10-12 09:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +A: Both preview and Access indicate that a user’s call led to a read of the file (or a read of a thumbnail rendering of  the file); while the events are intended to align with preview versus access i
```suggestion
A: Both preview and access indicate that a user’s call led to a read of the file (or a read of a thumbnail rendering of the file); while the events are intended to align with preview versus access intention, the event distinction isn’t a guarantee of the user’s intent.<br><br>
```

2020-10-12 09:56 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +<b>Q: Could any non-user action trigger log entries with Event Name = "File Previewed" and user-agent like "OneDriveMpc-Transform_Thumbnail"? </b> <br>
```suggestion
<b>Q: Could any non-user action trigger log entries with Event Name = "File Previewed" and user-agent like "OneDriveMpc-Transform_Thumbnail"?</b>
```

2020-10-12 09:57 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +A: No, similar events can be logged to a browser pre-fetch. <br>
```suggestion
A: No, similar events can be logged to a browser pre-fetch.
```

2020-10-12 09:57 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +<b>Q: If we see a "File Previewed" event coming from a Microsoft registered IP address, does that mean that the preview has been shown on the screen of the device of the end user? </b> <br>
```suggestion
<b>Q: If we see a "File Previewed" event coming from a Microsoft registered IP address, does that mean that the preview has been shown on the screen of the device of the end user?</b>
```

2020-10-12 09:58 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +A: No, it could have been due to a browser pre-fetch. <br>
```suggestion
A: No, it could have been due to a browser pre-fetch.
```

2020-10-12 09:59 UTC, JohanFreelancer9 commented on microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md
> +<b>Q: Are there scenarios where a user previewing a document generates "File Accessed" events? </b> <br>
```suggestion
<b>Q: Are there scenarios where a user previewing a document generates "File Accessed" events?</b>
```

2020-10-12 10:02 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-12 22:03 UTC, merged

2020-10-13 19:30 UTC, markjjo commented
@SheaAhna Heads up that your FAQs have been published: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#frequently-asked-questions-about-fileaccessed-and-filepreviewed-events

Thanks for adding these. I did some editing. Please submit another PR if you need to update my revisions. Thanks!