Fixing order of items in the table
MicrosoftDocs/microsoft-365-docs pull request #3136
Opened 2020-10-13 19:38 UTC by RossAdams

Order of items was incorrect fixing that so that user and domain impersonation come before spam and swapping their order.

2020-10-16 02:33 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-10-16 05:14 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md
>    |
```suggestion
```

2020-10-16 05:16 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md
>    |
Please also remove blank line 47.

2020-10-16 05:17 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-19 09:26 UTC, yogkumgit commented
@RossAdams Please update the document with suggested changes. Thanks

2020-10-19 16:12 UTC, RossAdams commented
> @RossAdams Please update the document with suggested changes. Thanks

Not sure what you are asking me to do here.  I already updated the doc?

2020-10-19 20:34 UTC, chrisda approved these changes

2020-10-19 20:34 UTC, merged