Update prepare-for-directory-synchronization.md
MicrosoftDocs/microsoft-365-docs pull request #3140
Opened 2020-10-13 22:41 UTC by msbemba

Made changes to the UPN invalid characters with "Letters with diacritical marks are invalid characters, such as umlauts, accents, and tildes." as it is not just umlauts it is also accents and tildes.

2020-10-13 22:41 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-13 22:41 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3100

2020-10-14 01:46 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/prepare-for-directory-synchronization.md
> +  - Letters with diacritical marks are invalid characters, such as umlauts, accents, and tildes.
```suggestion
  - Letters with diacritical marks, such as umlauts, accents, and tildes, are invalid characters.
```

2020-10-14 01:49 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-14 15:09 UTC, merged