Update tls-1.0-and-1.1-deprecation-for-office-365.md
MicrosoftDocs/microsoft-365-docs pull request #3155
Opened 2020-10-14 23:49 UTC by WorkShay

Specifying the staged implementation of the rollout.

2020-10-16 02:35 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-10-16 05:08 UTC, JohanFreelancer9 commented on microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md
> +> We temporarily halted deprecation enforcement of TLS 1.0 and 1.1 for commercial customers due to covid-19, but as supply chains have adjusted and certain countries open back up, we are resetting th
```suggestion
> We temporarily halted deprecation enforcement of TLS 1.0 and 1.1 for commercial customers due to covid-19, but as supply chains have adjusted and certain countries open back up, we are resetting the TLS enforcement to begin Oct 15, 2020 and rollout will continue over the following weeks and months. 
```

2020-10-16 05:09 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-17 05:49 UTC, JohanFreelancer9 approved these changes

2020-10-19 09:24 UTC, yogkumgit commented
@WorkShay Please merge this Pr. Thanks.

2020-10-19 15:37 UTC, WorkShay commented
Hi Yogesh,

I don’t have the permissions to do this. @KC<mailto:KC.Cross@microsoft.com> or someone else does.

Shayna

From: Yogesh Kumar <notifications@github.com>
Sent: Monday, October 19, 2020 2:25 AM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Shayna Mehta <Shayna.Mehta@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update tls-1.0-and-1.1-deprecation-for-office-365.md (#3155)


@WorkShay<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWorkShay&data=04%7C01%7CShayna.Mehta%40microsoft.com%7C7bd17fee3e3744a401dd08d87410dfb4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637386963107693511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qt6en2GAeMhkHZmiXz4XaJbU8y4d0xzizW%2Fk8QAGZ8E%3D&reserved=0> Please merge this Pr. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F3155%23issuecomment-711903992&data=04%7C01%7CShayna.Mehta%40microsoft.com%7C7bd17fee3e3744a401dd08d87410dfb4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637386963107703470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pd74MJAsiy4r0gqRq1esVO5lFMTpJ3OgGTEW6oG8jB8%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQJPS6ZTZAAX6QWVP7K2XWLSLQAXLANCNFSM4SRIG74Q&data=04%7C01%7CShayna.Mehta%40microsoft.com%7C7bd17fee3e3744a401dd08d87410dfb4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637386963107703470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YxDhJWKIcau0DPm%2FEjrH3RQEUTzCerFchKcFNpURqDc%3D&reserved=0>.

2020-10-20 03:42 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks.

2020-10-22 01:13 UTC, merged