Update enable-the-report-message-add-in.md
MicrosoftDocs/microsoft-365-docs pull request #3166
Opened 2020-10-15 15:07 UTC by msbemba

Corrected the navigation to deploy add-in as it has changed in the new admin center.

2020-10-15 15:07 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3148

2020-10-15 15:08 UTC, msbemba commented
@JohanFreelancer9 please copy review

2020-10-15 16:37 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/enable-the-report-message-add-in.md
> +1. In the Microsoft 365 admin center, go to the **Settings**, **integrated Apps** & **Add-ins** page at https://admin.microsoft.com/AdminPortal/Home#/Settings/AddIns, and then click **Deploy Add-In**
```suggestion
1. In the Microsoft 365 admin center, go to the **Settings, integrated Apps & Add-ins** page at https://admin.microsoft.com/AdminPortal/Home#/Settings/AddIns, and then click **Deploy Add-In**.
```

2020-10-15 16:37 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-16 06:23 UTC, JohanFreelancer9 approved these changes

2020-10-19 08:37 UTC, yogkumgit commented
@chrisda Please merge this PR. Thanks.

2020-10-19 20:30 UTC, merged