Update siem-integration-with-office-365-ti.md
MicrosoftDocs/microsoft-365-docs pull request #3168
Opened 2020-10-15 15:26 UTC by msbemba

Corrected SIEM from security incident and event management to  Security Information and Event Management

2020-10-15 15:26 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-15 15:26 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3145

2020-10-15 16:28 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/siem-integration-with-office-365-ti.md
> +If your organization is using a Security Information and Event Management (SIEM) server, you can integrate Office 365 Advanced Threat Protection (Office 365 ATP) with your SIEM server. You can set up
```suggestion
If your organization is using a security information and event management (SIEM) server, you can integrate Office 365 Advanced Threat Protection (Office 365 ATP) with your SIEM server. You can set up this integration by using the [Office 365 Activity Management API](https://docs.microsoft.com/office/office-365-management-api/office-365-management-activity-api-reference). 
```

2020-10-15 16:31 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-16 06:19 UTC, JohanFreelancer9 approved these changes

2020-10-19 08:47 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks.

2020-10-19 20:30 UTC, merged