Update create-sharepoint-sites-and-add-users-with-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #3170
Opened 2020-10-15 18:15 UTC by msbemba

Added a note to the document stating that the resource quota works only on classic sites and not on modern sites.

2020-10-15 18:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-15 18:15 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3126

2020-10-16 06:14 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/create-sharepoint-sites-and-add-users-with-powershell.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2020-10-16 06:15 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/create-sharepoint-sites-and-add-users-with-powershell.md
> +> The resource quota parameter works only on Classic sites. If you use this parameter on a modern site, you may receive a warning message that it has been deprecated.
```suggestion
> The resource quota parameter works only on classic sites. If you use this parameter on a modern site, you may receive a warning message that it has been deprecated. 
```

2020-10-16 06:16 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-16 15:13 UTC, JohanFreelancer9 approved these changes

2020-10-19 08:56 UTC, yogkumgit commented
@JoeDavies-MSFT Please merge this PR. Thanks.

2020-10-19 15:03 UTC, merged