Update update-phone-number-and-email-address.md
MicrosoftDocs/microsoft-365-docs pull request #3203
Opened 2020-10-18 09:39 UTC by msbemba

Corrected the navigation path for Editing alternate email, phone, and alternate phone

2020-10-18 09:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-18 09:40 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3112

2020-10-18 14:34 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/update-phone-number-and-email-address.md
> +## To update your phone number, and email address
```suggestion
## To update your phone number and email address
```

2020-10-18 14:35 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/update-phone-number-and-email-address.md
> +Use the **Security Info** page to change your name, mobile phone number, and alternate email address. The alternate email address is used for important notifications, such as resetting your admin pas
```suggestion
Use the **Security Info** page to change your mobile phone number and alternate email address. The alternate email address is used for important notifications, such as resetting your admin password (not your computer admin password). 
```

2020-10-18 14:44 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/update-phone-number-and-email-address.md
> +3. In the **Security info** tab Click **Add Method**, select **Phone**, **Alternate Phone**, Or **Email** to add details. To Update your mobile, phone, and alternate email address you can edit them b
```suggestion
3. In the **Security info** tab, select **Add Method** \> **Phone** \> **Alternate Phone** or **Email** to add details. To update your mobile, phone, and alternate email address details, select **Change**. Make sure you use something different than your Microsoft email address for your alternate email address.
```

2020-10-18 14:48 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-19 02:31 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/update-phone-number-and-email-address.md
> +3. In the **Security info** tab, select **Add Method** \> **Phone** \> **Alternate Phone** or **Email** to add details. To update your mobile, phone, and alternate email address details, select **Cha
```suggestion
3. In the **Security info** tab, select **Add Method** \> **Phone** \> **Alternate Phone** or **Email** to add details. To update your mobile, phone, and alternate email address details, select **Change**. Make sure you use something other than your Microsoft email address for your alternate email address.
```

2020-10-19 02:32 UTC, JohanFreelancer9 requested changes
Apologies Sri, one more please.

2020-10-19 04:12 UTC, JohanFreelancer9 approved these changes

2020-10-19 09:04 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2020-10-23 14:52 UTC, yogkumgit commented
@kwekuako Gentle reminder please merge this PR. Thanks.

2020-11-17 02:14 UTC, merged