Update use-spam-notifications-to-release-and-report-quarantined-messa…
MicrosoftDocs/microsoft-365-docs pull request #3205
Opened 2020-10-18 10:16 UTC by msbemba

…ges.md

Added a note about the blocked sender and what happens after we block them

2020-10-18 10:16 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3143

2020-10-18 10:16 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-18 14:23 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md
> +> A blocked sender can still send you mail, but if anything from his or her email address makes it to your email account, it’s immediately moved to the Junk Email folder. Future messages from this se
```suggestion
> A blocked sender can still send you mail, but if anything from his or her email address makes it to your email account, it’s immediately moved to the Junk Email folder. Future messages from this sender will go to your Junk Email folder or to end-user quarantine. If you would like to delete these messages on arrival and don't want them to be quarantined, use [Mail flow Rules](https://docs.microsoft.com/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules) to purge them on arrival.
```

2020-10-18 14:24 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-19 02:08 UTC, JohanFreelancer9 approved these changes

2020-10-19 20:25 UTC, merged