Update manage-industry-news.md
MicrosoftDocs/microsoft-365-docs pull request #3224
Opened 2020-10-20 14:34 UTC by msbemba

Corrected Typos and dupes

2020-10-20 14:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-20 14:35 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3169

2020-10-21 07:32 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-industry-news.md
> +Signed-in users that come to the Bing homepage will see your industry news feed under the personalized info from your organization. 
```suggestion
Signed-in users who go to the Bing homepage will see your industry news feed under the personalized info for your organization.  
```

2020-10-21 07:36 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-21 15:18 UTC, JohanFreelancer9 approved these changes

2020-10-22 07:23 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks

2020-11-30 16:03 UTC, merged