Update configure-atp-anti-phishing-policies.md
MicrosoftDocs/microsoft-365-docs pull request #3230
Opened 2020-10-20 20:24 UTC by urgandhi

Added notes for the limits supported for users and domains.

2020-10-21 13:08 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-10-21 15:09 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies.md
> +       **Note**: In the Security & Compliance Center, you can enter a maximum of 60 users. In Exchange Online PowerShell, you can enter a maximum of 60 users.
```suggestion
  > [!NOTE] 
 > In the Security & Compliance Center and in Exchange Online PowerShell you can enter a maximum of 60 users.
```

2020-10-21 15:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies.md
> +       **Note**: In the Security & Compliance Center, you can enter a maximum of 50 domains. In Exchange Online PowerShell, you can enter a maximum of 50 domains.
```suggestion
  > [!NOTE]
  > In the Security & Compliance Center and in Exchange Online PowerShell, you can enter a maximum of 50 domains.
```

2020-10-21 15:13 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-22 06:32 UTC, yogkumgit commented
@urgandhi Please implement the suggested changes. Thanks.

2020-10-22 18:45 UTC, urgandhi commented
> @urgandhi Please implement the suggested changes. Thanks.

Done

2020-10-23 08:20 UTC, JohanFreelancer9 approved these changes

2020-10-26 04:34 UTC, yogkumgit commented
@chrisda Please merge this PR. Thanks.

2020-10-26 15:46 UTC, merged