Create azure-ad-conditional-access-client-mobile-new.PNG
MicrosoftDocs/microsoft-365-docs pull request #3237
Opened 2020-10-21 22:17 UTC by msbemba

Client apps are no longer in preview and the options have changed

2020-10-21 22:20 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-21 22:21 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3219

2020-10-22 01:27 UTC, JohanFreelancer9 commented on microsoft-365/solutions/create-secure-guest-sharing-environment.md
> +12. On the **Client apps** blade, click **Yes** for **Configure**, and then select the **Mobile apps and desktop clients** settings.</br>
```suggestion
12. On the **Client apps** blade, click **Yes** for **Configure**, and then select the **Mobile apps and desktop clients** setting.</br>
```

2020-10-22 01:33 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-10-22 04:27 UTC, JohanFreelancer9 approved these changes

2020-10-22 06:59 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks.

2020-10-22 14:59 UTC, MikePlumleyMSFT commented
@msbemba, file names all need to be lower case. Please update the .PNG file to .png. Also, no need to change the filename. Let's keep azure-ad-conditional-access-client-mobile.png. Thanks.

2020-10-22 15:09 UTC, msbemba commented
@MikePlumleyMSFT I have renamed the file to .png and retained the same file name. Let me know if it looks good now.

2020-10-22 15:12 UTC, MikePlumleyMSFT commented
@msbemba, looks good, thanks.

2020-10-22 15:12 UTC, merged