Update m365-campaigns-conditional-access.md
MicrosoftDocs/microsoft-365-docs pull request #3238
Opened 2020-10-21 22:39 UTC by msbemba

Preview policies are no longer available under conditional access and the customers are to create their own.

2020-10-21 22:39 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-21 22:39 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3213

2020-10-21 22:40 UTC, msbemba commented
@Sirkkuw these options have changed on the conditional access page and the preview policies no longer exist. So I have a few changes, let me know if there is anything that needs to be modified here.

2020-10-22 01:11 UTC, JohanFreelancer9 commented on microsoft-365/campaigns/m365-campaigns-conditional-access.md
> +1. Go to [Azure portal](https://portal.azure.com), and then navigate to **Azure Active Directory** \> **Conditional Access** to create a new **Policy**
```suggestion
1. Go to the [Azure portal](https://portal.azure.com), and then navigate to **Azure Active Directory** \> **Conditional Access** to create a new **Policy**.
```

2020-10-22 01:11 UTC, JohanFreelancer9 commented on microsoft-365/campaigns/m365-campaigns-conditional-access.md
> +See the following specific instructions for each policy
```suggestion
See the following specific instructions for each policy:
```

2020-10-22 01:20 UTC, JohanFreelancer9 commented on microsoft-365/campaigns/m365-campaigns-conditional-access.md
> +> The Preview Policies no longer exists and the customer will need to create their own policy.
```suggestion
> Preview policies no longer exist and users will need to create their own policies.
```

2020-10-22 01:23 UTC, JohanFreelancer9 commented on microsoft-365/campaigns/m365-campaigns-conditional-access.md
>      - [Require MFA for admins](https://docs.microsoft.com/azure/active-directory/conditional-access/howto-baseline-protect-administrators)
```suggestion
    - [Require MFA for admins](https://docs.microsoft.com/azure/active-directory/conditional-access/howto-baseline-protect-administrators) <br>
```

2020-10-22 01:24 UTC, JohanFreelancer9 commented on microsoft-365/campaigns/m365-campaigns-conditional-access.md
>      - [Require MFA for users](https://docs.microsoft.com/azure/active-directory/conditional-access/howto-baseline-protect-end-users)
```suggestion
    - [Require MFA for users](https://docs.microsoft.com/azure/active-directory/conditional-access/howto-baseline-protect-end-users) <br>
```

2020-10-22 01:24 UTC, JohanFreelancer9 commented on microsoft-365/campaigns/m365-campaigns-conditional-access.md
>      - [Block legacy authentication](https://docs.microsoft.com/azure/active-directory/conditional-access/howto-baseline-protect-legacy-auth)
```suggestion
    - [Block legacy authentication](https://docs.microsoft.com/azure/active-directory/conditional-access/howto-baseline-protect-legacy-auth) <br>
```

2020-10-22 01:25 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-22 04:26 UTC, JohanFreelancer9 approved these changes

2020-10-22 07:04 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks.

2020-11-13 18:08 UTC, merged