Update external-email-forwarding.md
MicrosoftDocs/microsoft-365-docs pull request #3259
Opened 2020-10-23 20:23 UTC by SignorelliDenis

Adding information that disabling forward through this feature will affect the "ForwardingAddress" which is configured by admins. Customers should be aware about this because all the possibilities that we had before the release of this feature never used to block "ForwardingAddress", just forward configured by users.

2020-10-27 13:24 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-10-27 14:06 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/external-email-forwarding.md
> +- Disabling automatic forwarding will also disable forwarding performed by administrators through EAC or powershell to external addresses.
```suggestion
- Disabling automatic forwarding will also disable forwarding performed by administrators through the Exchange admin center or PowerShell to external addresses.
```

2020-10-27 14:06 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-28 01:54 UTC, JohanFreelancer9 approved these changes

2020-10-28 04:10 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks.

2020-10-29 20:49 UTC, merged