Update mailbox-usage.md
MicrosoftDocs/microsoft-365-docs pull request #3264
Opened 2020-10-25 13:37 UTC by msbemba

The reports show up only when you click on view more, Hence made changes to the navigation.

2020-10-25 13:38 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-25 13:38 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3247

2020-10-26 01:50 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/mailbox-usage.md
> +2. Click on **View More**, From the **Select a report** drop-down, select **Exchange** \> **Mailbox usage**.
```suggestion
2. Select **View More**.
3. From the **Select a report** drop-down, choose **Exchange** \> **Mailbox usage**.

```

2020-10-26 01:50 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-26 05:19 UTC, JohanFreelancer9 approved these changes

2020-10-26 05:55 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2020-11-20 12:53 UTC, yogkumgit commented
@kwekuako Conflict resolved, please merge this PR. Thanks.

2020-12-02 20:03 UTC, merged