Update configure-the-outbound-spam-policy.md
MicrosoftDocs/microsoft-365-docs pull request #3317
Opened 2020-10-30 04:17 UTC by msbemba

Added a note about the NDR's that get generated when automatic forwarding is disabled

2020-10-30 04:17 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-10-30 04:17 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3284

2020-10-30 09:19 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md
> + > When Automatic Forwarding is disabled, For external senders sending to a mailbox that has forwarding in place, The recipient will get an NDR that they are not allowed to forward. For internal send
```suggestion
 > When Automatic Forwarding is disabled, the recipient will receive a non-delivery report (NDR) if external senders send email to a mailbox that has forwarding in place. If the email is sent by an internal sender, the sender will get the NDR.
```

2020-10-30 09:20 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-31 09:22 UTC, JohanFreelancer9 approved these changes

2020-11-02 04:38 UTC, yogkumgit commented
@chrisda Please merge this PR. Thanks.

2020-11-02 16:03 UTC, merged