Update endpoint-dlp-learn-about.md
MicrosoftDocs/microsoft-365-docs pull request #3329
Opened 2020-11-02 07:50 UTC by omriamdursky

Added additional file types that were missing.
Rephrased the note for default auditing that wasn't clear, I got several complaints from customers / field asking what it means, I hope this one is better.
@chrfox

2020-11-03 04:41 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-11-03 06:03 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-learn-about.md
> +> Endpoint DLP evaluate files of all the above types against the DLP policy and applies protection actions accordingly. All files that match a DLP policy are audited for all supported actions, even i
```suggestion
> Endpoint DLP evaluates files of all the above types against the DLP policy and applies protection actions accordingly. All files that match a DLP policy are audited for all supported actions, even if they aren't blocked. In addition, file activity performed on any Word, PowerPoint, Excel, PDF, and .csv file is audited by default, independent of whether a DLP policy exists or matches these files.
```

2020-11-03 06:04 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-04 11:54 UTC, yogkumgit commented
@omriamdursky Please implement the suggested changes. Thanks.

2020-11-04 14:54 UTC, JohanFreelancer9 approved these changes

2020-11-05 06:10 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2020-11-05 19:59 UTC, merged