Update ome-faq.md
MicrosoftDocs/microsoft-365-docs pull request #3337
Opened 2020-11-02 23:50 UTC by samschan-ms

@KCCross we updated the message size limit together.

2020-11-03 04:44 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-11-03 05:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.md
> +Yes. The maximum message size you can send with OME, including attachments, is 25 MB. For more information, see [Message limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchang
```suggestion
Yes. The maximum message size you can send with OME, including attachments, is 25 MB. For more information, see [Message limits](https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits-1).
```

2020-11-03 05:50 UTC, JohanFreelancer9 requested changes
Copy review - please remove locale from the link.

2020-11-04 04:00 UTC, JohanFreelancer9 approved these changes

2020-11-04 11:51 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks.

2020-12-15 23:13 UTC, merged