Update customer-key-overview.md
MicrosoftDocs/microsoft-365-docs pull request #3347
Opened 2020-11-03 21:42 UTC by msbemba

Added a line to the SPO and ODB requirements saying the accounts need to have the appropriate licenses to assign DEP.

2020-11-03 21:42 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-03 21:42 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3323

2020-11-04 02:38 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-overview.md
> +**SharePoint Online, OneDrive for Business, and Teams files** If you're using the multi-geo feature, you can create up to one DEP per geo for your organization. You can use different Customer Keys fo
```suggestion
**SharePoint Online, OneDrive for Business, and Teams files** If you're using the multi-geo feature, you can create up to one DEP per geo for your organization. You can use different Customer Keys for each geo. If you're not using the multi-geo feature, you can only create one DEP per tenant. When you assign the DEP, encryption begins automatically but can take some time to complete. Each user must have appropriate licenses in order to assign a DEP. Refer to the details in [Set up Customer Key](customer-key-set-up.md).
```

2020-11-04 02:39 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-11-04 04:39 UTC, JohanFreelancer9 approved these changes

2020-11-04 12:29 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2020-12-28 22:23 UTC, KCCross commented
This doesn't read clearly. Licenses are discussed elsewhere. Are you modifying this in response to customer request? The way it reads now, it sounds like users assign DEPs.

2020-12-29 06:56 UTC, yogkumgit commented
@msbemba

2020-12-29 07:26 UTC, msbemba commented
@KCCross Yes, This was a response to the Customer's request. Since there was ambiguity on whether the admin or the users need the appropriate licenses.

Thanks
Sri

2021-01-29 21:40 UTC, KCCross commented
Still not following. For SPO you assign a DEP at the site level, not per user. Please reword this.

2021-02-01 05:14 UTC, yogkumgit commented
@msbemba

2021-02-01 22:45 UTC, msbemba commented
@KCCross Thanks for the update. I'll close this PR and update the user.

2021-02-01 22:45 UTC, closed without merging