Update technologies.md
MicrosoftDocs/microsoft-365-docs pull request #3380
Opened 2020-11-06 19:30 UTC by dannoakes

Adding the Windows technologies used.

2020-11-13 13:44 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-11-14 06:54 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/intro/technologies.md
> +[Microsoft 365 data loss prevention](https://docs.microsoft.com/microsoft-365/compliance/endpoint-dlp-learn-about) | Customers are recommend to implement Microsoft 365 data loss prevention (DLP) to m
```suggestion
[Microsoft 365 data loss prevention](https://docs.microsoft.com/microsoft-365/compliance/endpoint-dlp-learn-about) | Customers are recommended to implement Microsoft 365 data loss prevention (DLP) to monitor the actions that are being taken on items you've determined to be sensitive and to help prevent the unintentional sharing of those items.   
```

2020-11-14 06:56 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/intro/technologies.md
> +[Windows Defender System Guard]( https://docs.microsoft.com/windows/security/threat-protection/windows-defender-system-guard/system-guard-how-hardware-based-root-of-trust-helps-protect-windows) | Pro
```suggestion
[Windows Defender System Guard]( https://docs.microsoft.com/windows/security/threat-protection/windows-defender-system-guard/system-guard-how-hardware-based-root-of-trust-helps-protect-windows) | Protects the integrity of the system at start-up and validates that system integrity has truly been maintained.
```

2020-11-14 07:05 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/intro/technologies.md
> +[Microsoft Defender Antivirus Behavior-based, heuristic, and real-time antivirus protection]( https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defe
```suggestion
[Microsoft Defender Antivirus Behavior-based, heuristic, and real-time antivirus protection]( https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-in-windows-10) | Always-on scanning for file and process threats which may not be detected as malware.
```

2020-11-14 07:11 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/intro/technologies.md
> + --- | ---
```suggestion
 --- | --- |
```

2020-11-14 07:19 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-08 14:56 UTC, yogkumgit commented
@dannoakes

2021-01-13 09:41 UTC, yogkumgit commented
@dannoakes Please implement the feedback so that merge can be initiated. Thanks

2021-01-26 17:19 UTC, dannoakes commented
@yogkumgit please confirm the feedback.

2021-01-26 17:32 UTC, JohanFreelancer9 requested changes
@dannoakes - please check, if you look at the rich diff, the table does not render correctly.

2021-01-27 10:30 UTC, yogkumgit commented
@JohanFreelancer9

2021-01-27 16:18 UTC, JohanFreelancer9 approved these changes

2021-01-27 17:41 UTC, jaimeo commented
@dannoakes your revised heading is unclear. Are there three things in the list? (1: Windows 10 Enterprise E3, 2) Windows 10 Enterprise E5, 3) Microsoft Defender for Endpoint.) Or two: (1: Windows 10 Enterprise E3, 2) Windows 10 Enterprise E5 + Microsoft Defender for Endpoint)?

2021-02-01 05:49 UTC, yogkumgit commented
@dannoakes Please reply to this comment. Thanks

2021-02-02 22:11 UTC, dannoakes commented
> @dannoakes your revised heading is unclear. Are there three things in the list? (1: Windows 10 Enterprise E3, 2) Windows 10 Enterprise E5, 3) Microsoft Defender for Endpoint.) Or two: (1: Windows 10 Enterprise E3, 2) Windows 10 Enterprise E5 + Microsoft Defender for Endpoint)?

It is s single heading "Windows 10 Enterprise E3, E5 and Microsoft Defender for Endpoint" for the table. It lists the 3 product SKUs a customer may have purchased. If it is simpler change to "Windows 10 Enterprise E5 or E3 with Microsoft Defender for Endpoint"

This is no different to the "Office 365 E3 or E5" heading for the above table, this is describing 2 product SKUs a customer may have purshased.

2021-02-02 22:27 UTC, jaimeo commented
Thanks! I think that slight rewording makes it clearer, especially for people who are just scanning.

2021-02-02 22:28 UTC, merged