Update mailbox-usage.md
MicrosoftDocs/microsoft-365-docs pull request #3440
Opened 2020-11-12 15:30 UTC by msbemba

Corrected navigation to usage reports

2020-11-12 15:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-12 15:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3368

2020-11-13 04:33 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/mailbox-usage.md
> +2. Click on  **View More** under **Active users - Microsoft 365 Services** and Click on **Active users** drop down, select **Exchange** \> **Mailbox usage**.
```suggestion
2. Select **View More** under **Active users - Microsoft 365 Services**. 
3. From the **Active users** drop-down list, select **Exchange** \> **Mailbox usage**.
```

2020-11-13 04:35 UTC, JohanFreelancer9 requested changes
Copy review - suggestions only.

2020-11-13 06:38 UTC, JohanFreelancer9 approved these changes

2020-11-13 07:39 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2020-11-17 02:05 UTC, merged