Update endpoint-dlp-learn-about.md
MicrosoftDocs/microsoft-365-docs pull request #3443
Opened 2020-11-12 16:33 UTC by msbemba

Copying sensitive content to the clipboard in public preview -https://techcommunity.microsoft.com/t5/microsoft-security-and/announcing-public-preview-of-microsoft-endpoint-data-loss/ba-p/1534085 
"Modifying a file" activity is also available in Endpoint DLP

2020-11-12 16:33 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-12 16:33 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3399

2020-11-13 05:01 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-learn-about.md
> +|Modify a file    |  auditable and restrictable       |
```suggestion
|modify a file    |  auditable and restrictable       |
```

2020-11-13 05:02 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-11-13 06:39 UTC, JohanFreelancer9 approved these changes

2020-11-13 08:18 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2020-12-16 21:24 UTC, chrfox commented
separate update made, this PR is outdated

2020-12-16 21:24 UTC, closed without merging