Update recommended-settings-for-eop-and-office365-atp.md
MicrosoftDocs/microsoft-365-docs pull request #3472
Opened 2020-11-16 18:41 UTC by msbemba

Added a default tab for Anti phishing policies

2020-11-16 18:41 UTC, msbemba commented
@JohanFreelancer9 please copy review

2020-11-16 18:42 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3452

2020-11-17 08:29 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md
> +|Security feature name|SDefault|Standard|Strict|Comment|
```suggestion
|Security feature name|Default|Standard|Strict|Comment|
```

2020-11-17 08:35 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-17 09:50 UTC, JohanFreelancer9 approved these changes

2020-11-17 17:49 UTC, merged