Update financial-services-secure-collaboration.md
MicrosoftDocs/microsoft-365-docs pull request #3528
Opened 2020-11-23 13:11 UTC by msbemba

Added more info link about Insider management

2020-11-23 13:12 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-23 13:12 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3477

2020-11-23 15:17 UTC, JohanFreelancer9 commented on microsoft-365/solutions/financial-services-secure-collaboration.md
> +Insider risk management in Microsoft 365 significantly increases capabilities of organizations to monitor and investigate insider risks while allowing organizations to still meet data privacy regulat
```suggestion
Insider risk management in Microsoft 365 significantly increases capabilities of organizations to monitor and investigate insider risks while allowing organizations to still meet data privacy regulations and follow established escalation paths when cases require higher-level action. For more information about insider risk management in Microsoft 365, see [Modern risk pain points and Workflow in Insider risk management in Microsoft 365](https://docs.microsoft.com/microsoft-365/compliance/insider-risk-management?view=o365-worldwide).
```

2020-11-23 15:18 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-25 02:14 UTC, JohanFreelancer9 approved these changes

2020-11-29 04:55 UTC, yogkumgit commented
@BrendaCarter Please merge this PR. Thanks

2021-01-26 22:42 UTC, merged