Update configure-email-forwarding.md
MicrosoftDocs/microsoft-365-docs pull request #3530
Opened 2020-11-23 13:27 UTC by msbemba

Added an important note about controlling automatic forwarding to external restrictions

2020-11-23 13:28 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-23 13:28 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3490

2020-11-23 15:00 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/configure-email-forwarding.md
> +> [!Important]
```suggestion
> [!IMPORTANT]
```

2020-11-23 15:01 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/configure-email-forwarding.md
> +> You can use outbound spam filter policies to control automatic forwarding to external recipients. For more information, View [Control automatic external email forwarding in Microsoft 365](https://d
```suggestion
> You can use outbound spam filter policies to control automatic forwarding to external recipients. For more information, see [Control automatic external email forwarding in Microsoft 365](https://docs.microsoft.com/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide#how-the-outbound-spam-filter-policy-settings-work-with-other-automatic-email-forwarding-controls).
```

2020-11-23 15:03 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-23 15:23 UTC, JohanFreelancer9 approved these changes

2020-11-24 03:49 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks.

2020-12-02 18:59 UTC, merged