Update ome-faq.md
MicrosoftDocs/microsoft-365-docs pull request #3542
Opened 2020-11-24 00:41 UTC by samschan-ms

Added link on Outlook client support of encrypted mail. @KCCross

2020-11-24 04:55 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-11-24 10:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.md
> +You can create protected messages from Outlook 2016, and Outlook 2013 for Windows and Mac, and from Outlook on the web. See [client details](https://support.microsoft.com/office/send-view-and-reply-t
```suggestion
You can create protected messages from Outlook 2016, Outlook 2013 for Windows and Mac, and from Outlook on the web. See the [Send, view, and reply to encrypted messages in Outlook for PC](https://support.microsoft.com/office/send-view-and-reply-to-encrypted-messages-in-outlook-for-pc-eaa43495-9bbb-4fca-922a-df90dee51980?ui=en-us&rs=en-us&ad=us) topic for more information on sending encrypted messages.
```

2020-11-24 10:52 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-25 01:53 UTC, JohanFreelancer9 approved these changes

2020-12-15 23:14 UTC, merged