Update admin-submission.md
MicrosoftDocs/microsoft-365-docs pull request #3546
Opened 2020-11-24 07:02 UTC by andypunt

Updated admin submissions flow.

2020-11-25 07:35 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-11-25 10:32 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +Messages that are submitted in Admin submissions are rescanned and results shown in the details flyout:
```suggestion
Messages that are submitted in admin submissions are rescanned and results shown in the details flyout:
```

2020-11-25 10:35 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +1) if there was a failure in the sender's email authentication at time of delivery
```suggestion
1) If there was a failure in the sender's email authentication at the time of delivery.
```

2020-11-25 10:35 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +2) Information about any policy hits that could have affected or overridden the verdict of a message
```suggestion
2) Information about any policy hits that could have affected or overridden the verdict of a message.
```

2020-11-25 10:36 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +3) current detonation results to see if the URLs or files contained in the message were malicious or not
```suggestion
3) Current detonation results to see if the URLs or files contained in the message were malicious or not.
```

2020-11-25 10:36 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +4) feedback from graders
```suggestion
4) Feedback from graders.
```

2020-11-25 10:36 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +If a override was found, the rescan should complete in several minutes. If there wasn't a problem in email authentication or delivery wasn't affected by an override, then the feedback from graders co
```suggestion
If an override was found, the rescan should complete in several minutes. If there wasn't a problem in email authentication or delivery wasn't affected by an override, then the feedback from graders could take up to a day.
```

2020-11-25 10:37 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-26 02:24 UTC, JohanFreelancer9 approved these changes

2020-11-30 19:40 UTC, merged