Update communication.md
MicrosoftDocs/microsoft-365-docs pull request #3564
Opened 2020-11-26 09:22 UTC by msbemba

Fixed typo. It should be Channel instead of Chat.

2020-11-26 09:22 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-26 09:23 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3521

2020-11-26 13:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/productivity/communication.md
>          - **Numerator:** People who sent chat messages on Microsoft Teams in the last 28 days
```suggestion
        - **Numerator:** People who sent chat messages on Microsoft Teams in the last 28 days.
```

2020-11-26 13:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/productivity/communication.md
>          - **Denominator:** People sent messages on Microsoft Teams in the last 28 days
```suggestion
        - **Denominator:** People who sent messages on Microsoft Teams in the last 28 days.
```

2020-11-26 13:19 UTC, JohanFreelancer9 requested changes
Copy review - a few additional changes, please.

2020-11-27 01:13 UTC, JohanFreelancer9 approved these changes

2020-11-27 05:46 UTC, yogkumgit commented
@Kateyanne Please merge this PR. Thanks

2020-11-30 20:41 UTC, merged