Update information-protection-deploy-assess.md
MicrosoftDocs/microsoft-365-docs pull request #3565
Opened 2020-11-26 09:36 UTC by msbemba

Added a note about using AIP to learn about sensitive information types in on-premises data stores.

2020-11-26 09:36 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3478

2020-11-26 09:36 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-26 13:05 UTC, JohanFreelancer9 commented on microsoft-365/solutions/information-protection-deploy-assess.md
> +> To Find what sensitive information you have in files stored on-premises, Please refer to [Azure Information Protection](https://docs.microsoft.com/azure/information-protection/quickstart-findsensit
```suggestion
> To Find what sensitive information you have in files stored on-premises, please refer to [Azure Information Protection](https://docs.microsoft.com/azure/information-protection/quickstart-findsensitiveinfo).
```

2020-11-26 13:05 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-27 01:14 UTC, JohanFreelancer9 approved these changes

2020-11-29 04:45 UTC, yogkumgit commented
@BrendaCarter Please merge this PR. Thanks.

2021-01-26 22:42 UTC, merged