Update change-address-contact-and-more.md
MicrosoftDocs/microsoft-365-docs pull request #3566
Opened 2020-11-26 09:47 UTC by msbemba

Changed steps for Changing Alternate email address.

2020-11-26 09:47 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-26 09:47 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3537

2020-11-26 12:51 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/change-address-contact-and-more.md
> +4. In the Eamail section, Click on **Change**
```suggestion
4. In the Email section, select **Change**
```

2020-11-26 12:54 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/change-address-contact-and-more.md
> +6. Enter the Code  sent to the Alternate email and Click on **OK** to verify the change.
```suggestion
6. Enter the code sent to the Alternate email and select **OK** to verify the change.
```

2020-11-26 12:57 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-27 01:23 UTC, JohanFreelancer9 approved these changes

2020-11-29 04:47 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2020-12-02 18:13 UTC, merged