Update bookings-faq.md
MicrosoftDocs/microsoft-365-docs pull request #3579
Opened 2020-11-27 08:44 UTC by msbemba

Changed entire document to reflect new name changes with M365 business suite and also modified availability to reflect availability on M365 Business Standard as well..

2020-11-27 08:44 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-27 08:45 UTC, msbemba commented
Isuse#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3562

2020-11-27 15:31 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-faq.md
>  If a customer wants to disable access to Bookings for certain eligible licenses in their tenant, they can either user a group policy to restrict licenses or implement an OWA Mailbox policy that will
```suggestion
If a customer wants to disable access to Bookings for certain eligible licenses in their tenant, they can either use a group policy to restrict licenses or implement an OWA Mailbox policy that will restrict who is able to create new Bookings calendars.
```

2020-11-27 15:33 UTC, JohanFreelancer9 requested changes
Copy review - one additional edit, please.

2020-11-28 07:13 UTC, JohanFreelancer9 approved these changes

2020-11-29 04:06 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2020-12-02 20:10 UTC, merged