Update ome-faq.md
MicrosoftDocs/microsoft-365-docs pull request #3580
Opened 2020-11-27 08:48 UTC by msbemba

Made changes to reflect that the new OME supports 150MB as the size limit for encrypted messages.

2020-11-27 08:48 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-27 08:49 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3561

2020-11-27 15:17 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.md
> +Yes. The maximum message size you can send with OME(for subscribers using Office 365 Message Encryption with new capabilities), including attachments, is 150 MB.
```suggestion
Yes. The maximum message size you can send with OME (for subscribers using Office 365 Message Encryption with new capabilities), including attachments, is 150 MB.
```

2020-11-27 15:18 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-28 07:06 UTC, JohanFreelancer9 approved these changes

2020-12-15 23:23 UTC, KCCross commented
This has been to reduced to 25MB per product team.

2020-12-15 23:23 UTC, closed without merging

2020-12-16 09:13 UTC, msbemba commented
Thank you @KCCross