Update set-password-expiration-policy.md
MicrosoftDocs/microsoft-365-docs pull request #3585
Opened 2020-11-29 07:40 UTC by msbemba

Made changes to uncheck the box instead of select the check box

2020-11-29 07:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-29 07:40 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3559

2020-11-29 10:05 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/set-password-expiration-policy.md
> +4. If you don't want users to have to change passwords, Uncheck the box next to **Set user passwords to expire after a number of days**.
```suggestion
4. If you don't want users to have to change passwords, uncheck the box next to **Set user passwords to expire after a number of days**.
```

2020-11-29 10:06 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-21 09:58 UTC, yogkumgit commented
@JohanFreelancer9

2020-12-21 10:44 UTC, JohanFreelancer9 approved these changes

2021-01-04 17:32 UTC, merged