Update productivity-score.md
MicrosoftDocs/microsoft-365-docs pull request #3589
Opened 2020-11-30 08:04 UTC by msbemba

Added a note of users being able to view some of their productivity insights

2020-11-30 08:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-11-30 08:04 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3563

2020-11-30 11:23 UTC, JohanFreelancer9 commented on microsoft-365/admin/productivity/productivity-score.md
> +> User's also have option to vieww productivity insights from [Workplace Analytics](https://docs.microsoft.com/workplace-analytics/myanalytics/use/dashboard-2)
```suggestion
> Users also have the option to view productivity insights from the [MyAnalytics dashboard](https://docs.microsoft.com/workplace-analytics/myanalytics/use/dashboard-2).
```

2020-11-30 11:28 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-01 01:23 UTC, JohanFreelancer9 approved these changes

2020-12-02 06:40 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks.

2020-12-15 23:45 UTC, merged