Update remove-a-domain.md
MicrosoftDocs/microsoft-365-docs pull request #3619
Opened 2020-12-03 08:58 UTC by msbemba

Added a note as users need to know what happens to active accounts in o365 when a domain is removed

2020-12-03 08:58 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-03 08:58 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3583

2020-12-03 09:49 UTC, JohanFreelancer9 commented on microsoft-365/admin/get-help-with-domains/remove-a-domain.md
> +> You can't remove the [".onmicrosoft.com"](https://docs.microsoft.com/microsoft-365/admin/setup/domains-faq) domain from your account. When you remove a domain, Office 365 user accounts will revert
```suggestion
> You can't remove the [".onmicrosoft.com"](https://docs.microsoft.com/microsoft-365/admin/setup/domains-faq) domain from your account. When you remove a domain, Office 365 user accounts will revert back to the .onmicrosoft.com address as the Primary SMTP/UserprincipalName.
```

2020-12-03 09:52 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-12-03 15:37 UTC, JohanFreelancer9 approved these changes

2020-12-04 05:39 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks.

2020-12-15 18:09 UTC, merged