Update convert-user-mailbox-to-shared-mailbox.md
MicrosoftDocs/microsoft-365-docs pull request #3621
Opened 2020-12-03 10:56 UTC by msbemba

Added a note stating that conversion of shared mailbox can be done on-prem (cmdlets can be only used Starting in Cumulative Update 21 for Exchange Server 2013 and Cumulative Update 10 for Exchange Server 2016.)

2020-12-03 10:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-03 10:56 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3590

2020-12-03 15:21 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md
> +> Starting in Cumulative Update 21 for Exchange Server 2013 and Cumulative Update 10 for Exchange Server 2016 in an on-premises Exchange Server environment, you can directly create or modify a remote
```suggestion
> Starting in Cumulative Update 21 for Exchange Server 2013 and Cumulative Update 10 for Exchange Server 2016 in an on-premises Exchange Server environment, you can directly create or modify a remote shared mailbox. For more information, see [Cmdlets to create or modify a remote shared mailbox in an on-premises Exchange environment](https://support.microsoft.com/help/4133605/cmdlets-to-create-modify-remote-shared-mailbox-in-on-premises-exchange).
```

2020-12-03 15:24 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-04 07:35 UTC, JohanFreelancer9 approved these changes

2020-12-07 04:54 UTC, yogkumgit commented
@SKjerland Please merge this PR. Thanks.

2020-12-16 01:53 UTC, SKjerland commented
@yogkumgit or @JohanFreelancer9 - Please resolve conflicts and then ping me again so I can merge. Thanks!

2020-12-16 03:01 UTC, JohanFreelancer9 commented
@msbemba - would you be able to resolve the conflicts, please.

2020-12-16 09:09 UTC, msbemba commented
The conflicts have been resolved. Thank you. @SKjerland

2020-12-16 19:15 UTC, merged