Update admin-mobile-app.md
MicrosoftDocs/microsoft-365-docs pull request #3646
Opened 2020-12-05 12:18 UTC by msbemba

Added information about changing language in the admin app

2020-12-05 12:18 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-05 12:18 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3575

2020-12-07 04:02 UTC, JohanFreelancer9 commented on microsoft-365/admin/admin-overview/admin-mobile-app.md
> +The app supports all 39 languages that the web-based Microsoft 365 admin center supports. To change the language, select the app launch icon in the upper bar and click on settings and Language.
```suggestion
The app supports all 39 languages that the web-based Microsoft 365 admin center supports. To change the language, select the app launch icon in the upper bar and select **Settings** > **Language**.
```

2020-12-07 04:03 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-21 10:10 UTC, yogkumgit commented
@JohanFreelancer9

2020-12-21 10:38 UTC, JohanFreelancer9 approved these changes

2021-01-19 17:59 UTC, merged