Update manage-deployment-of-add-ins.md
MicrosoftDocs/microsoft-365-docs pull request #3651
Opened 2020-12-07 12:49 UTC by msbemba

Added a new link for Building Office add-ins as the old one was broken

2020-12-07 12:49 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-07 12:49 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3641

2020-12-07 15:23 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-deployment-of-add-ins.md
> +[Building Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator.
```suggestion
[Building Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator).
```

2020-12-07 15:28 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-08 05:50 UTC, JohanFreelancer9 approved these changes

2020-12-16 18:03 UTC, merged