Updated licensing description
MicrosoftDocs/microsoft-365-docs pull request #3683
Opened 2020-12-10 13:35 UTC by computeronix

Based on recent licensing changes, adjusted licensing verbage

2020-12-14 05:57 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-12-14 08:03 UTC, JohanFreelancer9 commented on microsoft-365/compliance/compliance-manager-quickstart.md
> +Compliance Manager provides intelligent and actionable data upon your first visit. Compliance Manager also has advanced capabilities for scaling your compliance when you’re ready. Available assessmen
```suggestion
Compliance Manager provides intelligent and actionable data upon your first visit. Compliance Manager also has advanced capabilities for scaling your compliance when you’re ready. Available assessments depend on your licensing agreement; to learn more, see [Microsoft 365 licensing guidance for security & compliance](https://go.microsoft.com/fwlink/?linkid=2132371).
```

2020-12-14 08:04 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-14 17:23 UTC, chvukosw commented on microsoft-365/compliance/compliance-manager-quickstart.md
> +Compliance Manager provides intelligent and actionable data upon your first visit. Compliance Manager also has advanced capabilities for scaling your compliance when you’re ready. Available assessmen
This is approved.

2020-12-14 17:25 UTC, chvukosw commented on microsoft-365/compliance/compliance-manager-quickstart.md
> +Compliance Manager provides intelligent and actionable data upon your first visit. Compliance Manager also has advanced capabilities for scaling your compliance when you’re ready. Available assessmen
This is approved.

2020-12-15 11:06 UTC, yogkumgit commented
@computeronix

2020-12-15 17:21 UTC, chvukosw commented
I approve of this. I don't see where else I need to indicate it. Please proceed, thanks.

2020-12-15 17:22 UTC, chvukosw approved these changes

2020-12-16 06:29 UTC, JohanFreelancer9 commented
@chvukosw - please merge the commit on the copy/edit review done by myself or make the necessary changes on the PR following the suggestions made. Thank you.

2020-12-16 19:02 UTC, merged