Update cortana-integration.md
MicrosoftDocs/microsoft-365-docs pull request #3692
Opened 2020-12-10 20:32 UTC by msbemba

Corrected from US only to worldwide as this feature is currently being rolled out (Roadmap - https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Rolling%20out&searchterms=57204)

2020-12-10 20:32 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-10 20:32 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3636

2020-12-10 20:54 UTC, rsun0525 commented
When will this show up?  I'm still seeing the phrasing https://docs.microsoft.com/en-us/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide "New Microsoft 365 experiences, such as the Briefing email and Play My Emails, will be enabled using Cortana enterprise services and fully comply with those promises. These features are currently available in the English (United States) market for users with mailboxes in the US geo, and for employees of multi-national corporations with US-based mailboxes. For more information on finding the usage location, please visit View additional property values for accounts."

2020-12-10 20:57 UTC, msbemba commented
@rsun0525 This is a Pull request created for the author to review and approve (it takes 2-3 business days). Once the author Approves the Change it takes less than 48 hours for the changes to reflect on the document.

2020-12-10 21:07 UTC, rsun0525 commented
Thanks for the detail.  Have a great day.

 

From: Sriraman M S <notifications@github.com> 
Sent: Thursday, December 10, 2020 15:58
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: rsun0525 <richard.d.sun@gmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update cortana-integration.md (#3692)

 

@rsun0525 <https://github.com/rsun0525>  This is a Pull request created for the author to review and approve (it takes 2-3 business days). Once the author Approves the Change it takes less than 48 hours for the changes to reflect on the document.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3692#issuecomment-742794414> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AHDXGC6LAYCT77LTIAE5JADSUEY3ZANCNFSM4UVSCIEQ> .  <https://github.com/notifications/beacon/AHDXGC6QMS5BUUUEONXBDLTSUEY3ZA5CNFSM4UVSCIE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFRDCJLQ.gif>

2020-12-11 01:59 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/cortana-integration.md
> +- New Microsoft 365 experiences, such as the Briefing email and Play My Emails, will be enabled using Cortana enterprise services and fully comply with those promises. These features are currently av
```suggestion
- New Microsoft 365 experiences, such as the Briefing email and Play My Emails, will be enabled using Cortana enterprise services and fully comply with those promises. These features are currently available worldwide (standard multi-tenant). For more information on finding the usage location, please visit [View additional property values for accounts](https://docs.microsoft.com/microsoft-365/enterprise/view-user-accounts-with-microsoft-365-powershell?view=o365-worldwide#view-additional-property-values-for-accounts).
```

2020-12-11 02:00 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-11 15:23 UTC, JohanFreelancer9 approved these changes

2020-12-14 06:02 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2021-01-04 17:34 UTC, merged