Update m365-campaigns-increase-protection.md
MicrosoftDocs/microsoft-365-docs pull request #3712
Opened 2020-12-14 11:08 UTC by msbemba

Made changes to the navigation for enabling unified Audit log

2020-12-14 11:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-14 11:08 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3704

2020-12-14 15:39 UTC, JohanFreelancer9 commented on microsoft-365/campaigns/m365-campaigns-increase-protection.md
> +1. To turn on the audit log search on, go to the admin center at <https://admin.microsoft.com> and then choose **Security** under **Admin centers** in the left nav.
```suggestion
1. To turn on the audit log search, go to the admin center at <https://admin.microsoft.com> and then choose **Security** under **Admin centers** in the left nav.
```

2020-12-14 15:42 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-15 07:41 UTC, JohanFreelancer9 approved these changes

2020-12-15 11:21 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks

2020-12-16 18:08 UTC, merged