Update enable-modern-authentication.md
MicrosoftDocs/microsoft-365-docs pull request #3761
Opened 2020-12-18 14:08 UTC by msbemba

Added a related article which talks about outlook prompting for password and does use modern auth

2020-12-18 14:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-18 14:09 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3725

2020-12-19 04:03 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/enable-modern-authentication.md
> +[Outlook prompts for password and doesn't use Modern Authentication to connect to Office 365](https://docs.microsoft.com/outlook/troubleshoot/authentication/outlook-prompt-password-modern-authenticat
```suggestion

[Outlook prompts for password and doesn't use Modern Authentication to connect to Office 365](https://docs.microsoft.com/outlook/troubleshoot/authentication/outlook-prompt-password-modern-authentication-enabled)
```

2020-12-19 04:03 UTC, JohanFreelancer9 requested changes
Coy review - minor edit.

2020-12-21 08:42 UTC, yogkumgit commented
@msbemba

2020-12-22 06:43 UTC, JohanFreelancer9 approved these changes

2020-12-22 13:10 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks.

2021-03-11 23:01 UTC, merged