Update give-mailbox-permissions-to-another-user.md
MicrosoftDocs/microsoft-365-docs pull request #3762
Opened 2020-12-18 14:56 UTC by msbemba

Added a note about Full access- It does not include Sendas or behalf of and only has access to Read and manage.

2020-12-18 14:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-18 14:57 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3729

2020-12-19 03:48 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md
> +> Read and Modify access is also called as Fullaccess permissions when granting access through Exchange admin center. Full access does not grant **Send as** or **Send on Behalf**  permission.
```suggestion
> Read and manage access is called Full access permission when granting access through the Exchange admin center. Full access does not grant **Send as** or **Send on Behalf**  permissions.
```

2020-12-19 04:00 UTC, JohanFreelancer9 requested changes
Coy review.

2020-12-21 08:46 UTC, yogkumgit commented
@msbemba

2020-12-21 19:49 UTC, denisebmsft approved these changes
Thank you @msbemba

2020-12-21 19:49 UTC, merged