Update submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-f…
MicrosoftDocs/microsoft-365-docs pull request #3773
Opened 2020-12-21 21:02 UTC by andypunt

…or-analysis.md

Adding section to speak to how data is stored.

2020-12-22 14:37 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2020-12-23 03:24 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md
> +The data resides in the Office 365 compliance boundary in North America datacenters and are reviewed by analysts on the engineering team to improve the effectiveness of the filters.
```suggestion
The data resides in the Office 365 compliance boundary in North American data centers and are reviewed by analysts on the engineering team to improve the effectiveness of the filters.
```

2020-12-23 03:25 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-23 10:26 UTC, JohanFreelancer9 approved these changes

2021-01-04 19:40 UTC, merged