Update privacy.md
MicrosoftDocs/microsoft-365-docs pull request #3774
Opened 2020-12-21 21:17 UTC by msbemba

Changed the Navigation settings for PS

2020-12-21 21:18 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3733

2020-12-21 21:18 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-22 05:20 UTC, JohanFreelancer9 commented on microsoft-365/admin/productivity/privacy.md
> +1. In the admin center, go to the  **Settings**  >  **Org Settings**, and **Productivity Score**
```suggestion
1. In the admin center, go to **Settings**  >  **Org Settings** > **Productivity Score**.
```

2020-12-22 05:21 UTC, JohanFreelancer9 approved these changes

2020-12-22 05:22 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-22 13:03 UTC, JohanFreelancer9 approved these changes

2020-12-22 13:09 UTC, yogkumgit commented
@Sirkkuw Please merge this PR. Thanks

2021-02-17 23:45 UTC, merged