Update double-key-encryption.md
MicrosoftDocs/microsoft-365-docs pull request #3798
Opened 2020-12-24 13:30 UTC by msbemba

Added a note that Keyname is Case sensitive as it needs to be as in the appsettings.json.

2020-12-24 13:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-24 13:31 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3785

2020-12-25 04:17 UTC, JohanFreelancer9 commented on microsoft-365/compliance/double-key-encryption.md
> +> Key name is case senstive. Provide the Keyname as in the appsettings.json.
```suggestion
> The key name is case sensitive. Provide the key name as it appears in the appsettings.json file.
```

2020-12-25 04:18 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-26 03:11 UTC, JohanFreelancer9 approved these changes

2020-12-28 10:22 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks.

2020-12-28 22:28 UTC, KCCross commented
Remove the "Note" formatting. This is not information they can skip, it's part of the regular flow of information in the text. Do that and I'll merge this.

2020-12-29 03:02 UTC, JohanFreelancer9 commented on microsoft-365/compliance/double-key-encryption.md
> +> [!NOTE]
```suggestion
```

2020-12-29 03:02 UTC, JohanFreelancer9 commented on microsoft-365/compliance/double-key-encryption.md
> +> The key name is case sensitive. Enter the key name as it appears in the appsettings.json file.
```suggestion
The key name is case sensitive. Enter the key name as it appears in the appsettings.json file.
```

2020-12-29 03:03 UTC, JohanFreelancer9 commented on microsoft-365/compliance/double-key-encryption.md
> +> The key name is case sensitive. Enter the key name as it appears in the appsettings.json file.
As per @KCCross's suggestion.

2020-12-29 06:58 UTC, yogkumgit commented
@msbemba

2020-12-29 07:56 UTC, JohanFreelancer9 approved these changes

2021-01-29 21:37 UTC, merged