Update groups-naming-policy.md
MicrosoftDocs/microsoft-365-docs pull request #3803
Opened 2020-12-26 11:46 UTC by msbemba

Added more information to what triggers 365groups naming policy

2020-12-26 11:46 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-12-26 11:46 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3728

2020-12-27 03:16 UTC, JohanFreelancer9 commented on microsoft-365/solutions/groups-naming-policy.md
> +The naming policy is applied to groups that are created across all groups workloads (like Outlook, Microsoft Teams, SharePoint, Planner, Yammer, etc.). It gets applied to both the group name and grou
```suggestion
The naming policy is applied to groups that are created across all groups workloads (like Outlook, Microsoft Teams, SharePoint, Planner, Yammer, etc.). It gets applied to both the group name and group alias. It also gets applied when a user creates a group and when the group name, alias, description, or avatar is edited for an existing group. Even clicking on the update button triggers the naming policy.
```

2020-12-27 03:17 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-28 06:49 UTC, JohanFreelancer9 approved these changes

2020-12-28 09:51 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-01-04 15:27 UTC, MikePlumleyMSFT commented
@ArunMSFT can you [review this update](https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3803/files)?

2021-01-05 04:35 UTC, ArunMSFT requested changes
The first of the updates look good but I'm not clear what this second update is about and what additional value it adds.

`Even clicking on the update button triggers the naming policy.`

2021-01-05 09:14 UTC, msbemba commented
@ArunMSFT  I meant updating the naming policy. I see the ambiguity there, So I'll remove that part from the PR.

2021-01-05 13:21 UTC, merged