correcting urls for Datacenter IP Ranges
MicrosoftDocs/microsoft-365-docs pull request #3818
Opened 2021-01-01 04:22 UTC by thedxt

fixes 3817

removed the old link Microsoft Azure Datacenter IP Ranges link that went to the deprecated url. It was deprecated June 30, 2020.

added the new replacement links 

Microsoft Azure IP Ranges and Service Tags – Public Cloud
Microsoft Azure IP Ranges and Service Tags – US Government Cloud
Microsoft Azure IP Ranges and Service Tags – Germany Cloud
Microsoft Azure IP Ranges and Service Tags – China Cloud

2021-01-01 14:56 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-01-02 06:22 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/urls-and-ip-address-ranges.md
> +[Microsoft Azure IP Ranges and Service Tags – China Cloud](https://www.microsoft.com/en-us/download/details.aspx?id=57062)
```suggestion
[Microsoft Azure IP Ranges and Service Tags – Public Cloud](https://www.microsoft.com/download/details.aspx?id=56519)

[Microsoft Azure IP Ranges and Service Tags – US Government Cloud](https://www.microsoft.com/download/details.aspx?id=57063)

[Microsoft Azure IP Ranges and Service Tags – Germany Cloud](https://www.microsoft.com/download/details.aspx?id=57064)

[Microsoft Azure IP Ranges and Service Tags – China Cloud](https://www.microsoft.com/download/details.aspx?id=57062)
```

2021-01-02 06:24 UTC, JohanFreelancer9 requested changes
Copy review - please remove the locale from the links.

2021-01-02 06:27 UTC, JohanFreelancer9 approved these changes

2021-01-09 06:44 UTC, yogkumgit commented
@JoeDavies-MSFT Please merge this PR. Thanks

2021-01-11 18:20 UTC, merged