Update detect-and-remediate-illicit-consent-grants.md
MicrosoftDocs/microsoft-365-docs pull request #3854
Opened 2021-01-06 10:50 UTC by msbemba

Made changes to viewing audit logs for Consent To Application as it is not available in Security and compliance any more and can be found in Azure Ad Audit logs.

2021-01-06 10:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-01-06 10:51 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3801

2021-01-06 13:35 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md
> +1. Open the **Azure Active directory** at <https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Overview>.
```suggestion
1. Open [Azure Active directory](https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Overview).
```

2021-01-06 13:36 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md
> +3. Search (all activities and all users) and enter the  date andthen click **Apply**.
```suggestion
3. Search (all activities and all users) and enter the  date and then click **Apply**.
```

2021-01-06 13:43 UTC, JohanFreelancer9 requested changes
Coppy review.

2021-01-06 14:12 UTC, JohanFreelancer9 approved these changes

2021-01-07 14:47 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks.

2021-02-05 14:58 UTC, yogkumgit commented
Gentle reminder, @MSFTTracyP Please merge this PR. Thanks.

2021-09-28 23:37 UTC, merged