Update data-classification-content-explorer.md
MicrosoftDocs/microsoft-365-docs pull request #3863
Opened 2021-01-07 16:21 UTC by msbemba

added portal URL to assign permissions

2021-01-07 16:26 UTC, msbemba commented
@JohanFreelancer9 please copy review

2021-01-07 16:26 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3826

2021-01-07 16:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-content-explorer.md
> +There are two roles that grant access to content explorer and it can be granted using the Microsoft Security and Complaince center(https://protection.office.com/permissions0:
```suggestion
There are two roles that grant access to content explorer and it is granted using the Microsoft Security & Compliance Center(https://protection.office.com/permissions):
```

2021-01-07 16:49 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-08 04:01 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-content-explorer.md
> +There are two roles that grant access to content explorer and it is granted using the Microsoft Security & Compliance Center(https://protection.office.com/permissions):
```suggestion
There are two roles that grant access to content explorer and it is granted using the [Microsoft Security & Compliance Center](https://protection.office.com/permissions).
```

2021-01-08 04:02 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-content-explorer.md
> +There are two roles that grant access to content explorer and it is granted using the Microsoft Security & Compliance Center(https://protection.office.com/permissions):
Apologies @msbemba - my mistake.

2021-01-08 15:39 UTC, JohanFreelancer9 approved these changes

2021-01-11 13:51 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2021-02-01 21:02 UTC, merged