Update create-retention-policies.md
MicrosoftDocs/microsoft-365-docs pull request #3876
Opened 2021-01-08 08:56 UTC by msbemba

Added a work around when using more than 1000 mailboxes per inclusion/exclusion.

2021-01-08 08:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-01-08 08:57 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3840

2021-01-08 15:18 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-retention-policies.md
> +The workaround is be to use groups instead when exceeding 1000 mailboxes per inclusion/exclusion.
```suggestion
The workaround is to use Microsoft 365 groups instead when exceeding 1000 mailboxes per inclusion/exclusion.
```

2021-01-08 15:19 UTC, JohanFreelancer9 requested changes
Copy reviewp.

2021-01-08 15:47 UTC, JohanFreelancer9 approved these changes

2021-01-11 13:40 UTC, yogkumgit commented
@cabailey Please merge this PR. Thanks.

2021-01-12 22:17 UTC, cabailey commented
I'm closing this PR because this is not a valid workaround - the 1,000 mailboxes is for any type of mailbox, whether it's a user mailbox or group mailbox. I've got an update in progress that makes this clearer and emphasizes that if you hit the limitations, you can create multiple retention policies (with the tradeoff of additional admin overheads), and some concrete examples for valid workarounds.

2021-01-12 22:17 UTC, closed without merging

2021-01-13 01:40 UTC, cabailey commented
The update for this page is now live.