Technical correction to multi-geo-tenant-configuration.md
MicrosoftDocs/microsoft-365-docs pull request #3884
Opened 2021-01-08 22:44 UTC by LaumanK

Correct the Note at the end of this section which states that EXO does not automatically migrate mailboxes when the PDL changes.  It is automatically migrated if there is a mismatch between the Mailbox Region and the Mailbox DB Geo location.  Reference:  https://docs.microsoft.com/en-us/microsoft-365/enterprise/administering-exchange-online-multi-geo?view=o365-worldwide#find-the-geo-location-of-a-mailbox

2021-01-11 14:58 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-01-11 16:38 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/multi-geo-tenant-configuration.md
> +If the user already has a OneDrive site created in the tenant, setting their PDL will not automatically move their existing OneDrive. To move a user's OneDrive, see [OneDrive for Business Geo Move](m
```suggestion
If the user already has a OneDrive site created in the tenant, setting their PDL will not automatically move their existing OneDrive. To move a user's OneDrive, see [OneDrive for Business Geo Move](move-onedrive-between-geo-locations.md). Please follow the instructions in Moving OneDrive between geo locations. (Note that Exchange Online automatically relocates the user's mailbox if the PLD changes and the MailboxRegion no longer matches the Mailbox Database Geo Location code. See [Administering Exchange Online mailboxes in a multi-geo environment](https://docs.microsoft.com/microsoft-365/enterprise/administering-exchange-online-multi-geo?view=o365-worldwide).)
```

2021-01-11 16:44 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-12 03:16 UTC, yogkumgit commented
@LaumanK

2021-01-28 14:46 UTC, merged