Update office-365-service-encryption.md
MicrosoftDocs/microsoft-365-docs pull request #3901
Opened 2021-01-13 15:45 UTC by msbemba

Corrected SFB to Teams on this document.

2021-01-13 15:45 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3869

2021-01-13 15:45 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-01-13 17:21 UTC, JohanFreelancer9 commented on microsoft-365/compliance/office-365-service-encryption.md
> +In addition to using volume-level encryption, Exchange Online, Teams, SharePoint Online, and OneDrive for Business also use Service Encryption to encrypt customer data. Service Encryption allows for
```suggestion
In addition to using volume-level encryption, Exchange Online, Microsoft Teams, SharePoint Online, and OneDrive for Business also use Service Encryption to encrypt customer data. Service Encryption allows for two key management options:
```

2021-01-13 17:22 UTC, JohanFreelancer9 commented on microsoft-365/compliance/office-365-service-encryption.md
> +To learn how to set up Customer Key for Microsoft 365 for Exchange Online, Teams, SharePoint Online, including Team Sites, and OneDrive for Business, see these articles:
```suggestion
To learn how to set up Customer Key for Microsoft 365 for Exchange Online, Microsoft Teams, SharePoint Online, including Team Sites, and OneDrive for Business, see these articles:
```

2021-01-13 17:22 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-14 06:53 UTC, JohanFreelancer9 approved these changes

2021-01-29 20:52 UTC, merged