Updates after sync with PM
MicrosoftDocs/microsoft-365-docs pull request #3926
Opened 2021-01-16 00:16 UTC by tweekerz

2021-01-18 11:02 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-01-18 17:21 UTC, JohanFreelancer9 commented on microsoft-365/compliance/unlimited-archiving.md
> +  - Auto-expanded archive search is available in Outlook Desktop in Current Channel (Preview). Within this preview, the Current Mailbox scope is available, thus allowing you to search the auto-expand
```suggestion
  - Auto-expanded archive search is available in Outlook Desktop in Current Channel (Preview). Within this preview, the Current Mailbox scope is available, thus allowing you to search the auto-expanded archive. For more information about this and other Microsoft Search support features, see [How Outlook for Windows connected to Exchange Online utilizes Microsoft Search](https://techcommunity.microsoft.com/t5/outlook-global-customer-service/how-outlook-for-windows-connected-to-exchange-online-utilizes/ba-p/1715045). 
```

2021-01-18 17:25 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-19 10:37 UTC, yogkumgit commented
@tweekerz

2021-01-22 17:36 UTC, tweekerz commented
@yogkumgit approved please commit the PR. Thanks!

2021-01-25 05:37 UTC, yogkumgit commented
@JohanFreelancer9

2021-01-25 09:50 UTC, JohanFreelancer9 approved these changes

2021-01-26 02:54 UTC, tweekerz commented
Do we have any ETA on the PR? I still do not see it approved.

Rob Whaley<mailto:rob.whaley@microsoft.com>
Sr. Support Escalation Engineer, Beta Engineer


From: JohanFreelancer9 <notifications@github.com>
Sent: Monday, January 25, 2021 3:51 AM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Rob Whaley (EXCHANGE) <Rob.Whaley@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Updates after sync with PM (#3926)


@JohanFreelancer9 approved this pull request.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F3926%23pullrequestreview-575225103&data=04%7C01%7Crob.whaley%40microsoft.com%7Cf5c8e711cf1945f5a25a08d8c116b99d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637471650637798784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pEjTdz45Y%2FC2zWxYR0PpcFww%2F2DJBIhTsOak2NIMEdA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC5SXQCVL6W2DDEWB2NYKPTS3U5ILANCNFSM4WEZIHNA&data=04%7C01%7Crob.whaley%40microsoft.com%7Cf5c8e711cf1945f5a25a08d8c116b99d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637471650637808749%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IkxeCMDi%2Flm9IeWVDpDPJqa%2FJWu1yvNfwo5CzFtBXmE%3D&reserved=0>.

2021-01-26 13:01 UTC, yogkumgit commented
@markjjo Please merge this PR. Thanks

2021-01-26 22:51 UTC, merged

2021-01-26 22:52 UTC, markjjo commented
@tweekerz PR merged. Updated article should be live later today or tomorrow mid-AM at the latest.

2021-01-27 03:37 UTC, tweekerz commented
Thanks Mark!
________________________________
From: Mark Johnson - MSFT <notifications@github.com>
Sent: Tuesday, January 26, 2021 4:52 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Rob Whaley (EXCHANGE) <Rob.Whaley@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Updates after sync with PM (#3926)


@tweekerz<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftweekerz&data=04%7C01%7Crob.whaley%40microsoft.com%7C33de9edceaf742f5efa108d8c24d14dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637472983900077391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eTykt3QcH94ogf3H2aRRab%2BrSBK4D7%2BqO2NhhOfdDXY%3D&reserved=0> PR merged. Updated article should be live later today or tomorrow mid-AM at the latest.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F3926%23issuecomment-767880225&data=04%7C01%7Crob.whaley%40microsoft.com%7C33de9edceaf742f5efa108d8c24d14dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637472983900087347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c2kLFL6V9XbPR7L58StoE46npzrFqvqCLqzg5f0SUEQ%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC5SXQAJFPIPP7MW5I7MXBTS35BTNANCNFSM4WEZIHNA&data=04%7C01%7Crob.whaley%40microsoft.com%7C33de9edceaf742f5efa108d8c24d14dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637472983900087347%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WlExOxcNxF0ZhdT5k0mN%2BPoE31CT9Op5e0wPriNiSbU%3D&reserved=0>.