Update api-advanced-hunting.md
MicrosoftDocs/microsoft-365-docs pull request #3931
Opened 2021-01-17 10:24 UTC by BenAlfasi

2021-01-18 11:05 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-01-18 16:51 UTC, JohanFreelancer9 commented on microsoft-365/security/mtp/api-advanced-hunting.md
>  5. You have four total hours of running time day per tenant.
```suggestion
5. You have four total hours of running time per day per tenant.
```

2021-01-18 16:52 UTC, JohanFreelancer9 commented on microsoft-365/security/mtp/api-advanced-hunting.md
> +>[!Note]
```suggestion
> [!NOTE]
```

2021-01-18 16:57 UTC, JohanFreelancer9 commented on microsoft-365/security/mtp/api-advanced-hunting.md
> +> All quatas listed above (e.g. 15 calls per min) are per tenant size. The above quotas are the minimum.
```suggestion
> All quatas listed above (for example 15 calls per min) are per tenant size. The above quotas are the minimum.
```

2021-01-18 16:58 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-19 10:34 UTC, yogkumgit commented
@BenAlfasi

2021-01-20 11:11 UTC, yogkumgit commented
@JohanFreelancer9

2021-01-20 17:34 UTC, JohanFreelancer9 approved these changes

2021-01-21 12:26 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks.

2021-01-26 01:08 UTC, merged