Update create-a-keyword-dictionary.md
MicrosoftDocs/microsoft-365-docs pull request #3934
Opened 2021-01-18 11:36 UTC by pratjain523

@chrfox We have increased the limit of keyword dictionaries from 100KB to 1MB.

2021-01-18 15:22 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-01-18 16:18 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-a-keyword-dictionary.md
>  > Microsoft 365 Information Protection now  supports in preview double byte character set languages for:
```suggestion
> Microsoft 365 Information Protection now supports in preview double-byte character set languages for:
```

2021-01-18 16:19 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-18 16:21 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-a-keyword-dictionary.md
> +Data loss prevention (DLP) can identify, monitor, and protect your sensitive items. Identifying sensitive items sometimes requires looking for keywords, particularly when identifying generic content
```suggestion
Data loss prevention (DLP) can identify, monitor, and protect your sensitive items. Identifying sensitive items sometimes requires looking for keywords, particularly when identifying generic content (such as healthcare-related communication), or inappropriate or explicit language. Although you can create keyword lists in sensitive information types, keyword lists are limited in size and require modifying XML to create or edit them. Keyword dictionaries provide simpler management of keywords and at a much larger scale, supporting up to 1 MB of terms (post-compression) in the dictionary and support any language. The tenant limit is also 1 MB after compression. 1 MB of post-compression limit means that all dictionaries combined across a tenant can have close to 1 million characters.
```

2021-01-18 16:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-a-keyword-dictionary.md
> +Data loss prevention (DLP) can identify, monitor, and protect your sensitive items. Identifying sensitive items sometimes requires looking for keywords, particularly when identifying generic content
```suggestion
Data loss prevention (DLP) can identify, monitor, and protect your sensitive items. Identifying sensitive items sometimes requires looking for keywords, particularly when identifying generic content (such as healthcare-related communication), or inappropriate or explicit language. Although you can create keyword lists in sensitive information types, keyword lists are limited in size and require modifying XML to create or edit them. Keyword dictionaries provide simpler management of keywords and at a much larger scale, supporting up to  1 MB of terms (post-compression) in the dictionary and support any language. The tenant limit is also 1 MB after compression. 1 MB of post-compression limit means that all dictionaries combined across a tenant can have close to 1 million characters.
```

2021-01-19 10:33 UTC, yogkumgit commented
@pratjain523

2021-01-19 10:41 UTC, pratjain523 commented on microsoft-365/compliance/create-a-keyword-dictionary.md
> +Data loss prevention (DLP) can identify, monitor, and protect your sensitive items. Identifying sensitive items sometimes requires looking for keywords, particularly when identifying generic content
I am good with the suggested changes.

2021-01-19 23:45 UTC, merged