Update admin-submission.md
MicrosoftDocs/microsoft-365-docs pull request #3945
Opened 2021-01-19 18:57 UTC by andypunt

Clarify the section on what happens during submission.

2021-01-21 13:34 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-01-22 05:53 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +1) Email authentication check: details on if email authentication passed or failed when it was delivered
```suggestion
1) **Email authentication check**: Details on whether email authentication passed or failed when it was delivered.
```

2021-01-22 05:54 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +2) Policy hits: information about any policies that may have allowed or blocked the incoming email into your tenant, overriding our service filter verdicts
```suggestion
2) Policy hits: information about any policies that may have allowed or blocked the incoming email into your tenant, overriding our service filter verdicts
```
```suggestion
2) **Policy hits**: Information about any policies that may have allowed or blocked the incoming email into your tenant, overriding our service filter verdicts.
```

2021-01-22 05:56 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +3) Payload reputation/detonation: examination of any URLs and attachments in the message
```suggestion
3) **Payload reputation/detonation**: Examination of any URLs and attachments in the message.
```

2021-01-22 05:57 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +4) Grader analysis: review done by human graders in order to confirm if messages are malicious or not
```suggestion
4) **Grader analysis**: Review done by human graders in order to confirm whether or not messages are malicious.
```

2021-01-22 05:58 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +> Payload reputation/detonation and grader analysis is not done in all tenants. Information is blocked from going outside of the tenancy when  data is not supposed to leave the tenant boundary for co
```suggestion
> Payload reputation/detonation and grader analysis are not done in all tenants. Information is blocked from going outside of the tenancy when data is not supposed to leave the tenant boundary for compliance purposes.
```

2021-01-22 05:59 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-22 06:50 UTC, JohanFreelancer9 approved these changes

2021-01-22 21:37 UTC, merged