Update install-app-guard.md
MicrosoftDocs/microsoft-365-docs pull request #4015
Opened 2021-01-28 23:40 UTC by sazankha

Updated minimum system requirements

2021-02-01 05:45 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-02-01 13:36 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/install-app-guard.md
> +* **Office**: Office Current Channel Build version 2011 16.0.13530.10000 or later. Both 32-bit and 64-bit versions of office are supported.
```suggestion
* **Office**: Office Current Channel Build version 2011 16.0.13530.10000 or later. Both 32-bit and 64-bit versions of Office are supported.
```

2021-02-01 13:37 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-02 05:34 UTC, JohanFreelancer9 approved these changes

2021-02-02 11:46 UTC, yogkumgit commented
@schmurky Please merge this PR. Thanks

2021-02-03 09:04 UTC, merged