Documentation updates for new changes (Alert ID, Data retention for Trial tenants, change in Export limits) for MDO Threat Explorer/Alerts
MicrosoftDocs/microsoft-365-docs pull request #4044
Opened 2021-02-02 16:07 UTC by vippand

As part of this work, made changes for the following updates: 
•	Alert ID integration (search using Alert ID and Alert-Explorer navigation) with Threat Explorer.
•	Extending the Explorer (and Real-time Detections) data retention and search limit for trial tenants from 7 (current limit) to 30 days
•	Increasing the limits for Export of records for Threat Explorer from 9990 to 200,000.

2021-02-02 17:03 UTC, vippand commented
cc @MSFTTracyP @denisebmsft - please let me know if there needs to be an update to the PR path.

2021-02-09 13:47 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-02-09 15:54 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer-views.md
> +> We will soon be extending the Explorer (and Real-time Detections) data retention and search limit for trial tenants from 7 to 30 days. This change is being tracked as part of roadmap item no. 70544
```suggestion
> We will soon be extending the Explorer (and Real-time detections) data retention and search limit for trial tenants from 7 to 30 days. This change is being tracked as part of roadmap item no. 70544, and is currently in a roll-out phase. 
```

2021-02-09 15:56 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer.md
> +Today if you navigate from an Alert to Threat Explorer, it opens a filtered view within the Explorer, with the view filtered by Alert policy ID (Policy ID being a unique identifier for an Alert polic
```suggestion
Today, if you navigate from an Alert to Threat Explorer, it opens a filtered view within the Explorer, with the view filtered by Alert policy ID (Policy ID being a unique identifier for an Alert policy).
```

2021-02-09 16:13 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-09 16:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer.md
> +We are making this integration more relevant by introducing the alert ID (an example of alert ID below) in Threat Explorer and Real-time detections, so that you see messages which are relevant to the
```suggestion
We are making this integration more relevant by introducing the alert ID (see an example of alert ID below) in Threat Explorer and Real-time detections so that you see messages which are relevant to the specific alert, as well as a count of emails. You will also be able to see if a message was part of an alert, as well as navigate from that message to the specific alert.  
```

2021-02-09 16:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer.md
> +Alert ID is available within the URL, when you are viewing an individual alert, an example being https://protection.office.com/viewalerts?id=372c9b5b-a6c3-5847-fa00-08d8abb04ef1
```suggestion
Alert ID is available within the URL when you are viewing an individual alert; an example being https://protection.office.com/viewalerts?id=372c9b5b-a6c3-5847-fa00-08d8abb04ef1
```

2021-02-09 16:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer.md
> +### Extending the Explorer (and Real-time Detections) data retention and search limit for trial tenants from 7 to 30 days (Preview)
```suggestion
### Extending the Explorer (and Real-time detections) data retention and search limit for trial tenants from 7 to 30 days (Preview)  
```

2021-02-09 16:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer.md
> +As part of this change, you will be able to search for, and filter across email data across 30 days (increase from the previous 7 days) in Threat Explorer/Real-time detections for both Defender for O
```suggestion
As part of this change, you will be able to search for, and filter across email data across 30 days (increase from the previous 7 days) in Threat Explorer/Real-time detections for both Defender for Office P1 and P2 trial tenants. 
```
```suggestion
As part of this change, you will be able to search for, and filter email data across 30 days (an increase from the previous 7 days) in Threat Explorer/Real-time detections for both Defender for Office P1 and P2 trial tenants. 
```

2021-02-09 16:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer.md
> +As part of this update, the no. of rows for Email records that can be exported from Threat Explorer are being increased from 9990 to 200,000 records. The set of columns  that can be exported today wi
```suggestion
As part of this update, the number of rows for Email records that can be exported from Threat Explorer is increased from 9990 to 200,000 records. The set of columns that can be exported currently will remain the same, but the number of rows will increase from the current limit.
```

2021-02-09 16:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/whats-new-in-office-365-atp.md
> +- Extending the Explorer (and Real-time Detections) data retention and search limit for trial tenants from 7 (previous limit) to 30 days in [hunting experiences](threat-explorer.md)
```suggestion
- Extending the Explorer (and Real-time detections) data retention and search limit for trial tenants from 7 (previous limit) to 30 days in [hunting experiences](threat-explorer.md)
```

2021-02-09 16:13 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/threat-explorer-views.md
>  |
```suggestion
```

2021-02-10 12:18 UTC, yogkumgit commented
@vippand

2021-02-11 10:08 UTC, vippand commented
@yogkumgit  @JohanFreelancer9 Thanks for the edits- I have made the modifications

2021-02-11 17:46 UTC, JohanFreelancer9 approved these changes

2021-02-12 13:36 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks.

2021-02-17 22:36 UTC, MSFTTracyP approved these changes
Thanks!

2021-02-17 22:49 UTC, MSFTTracyP commented
Updated. **Vipul please check that these documents look as expected** and report back if they do not, asap!

2021-02-17 22:50 UTC, merged

2021-02-19 17:34 UTC, vippand commented
@MSFTTracyP @yogkumgit - I do not see the changes reflected in the docs page, even though the changes were merged 2 days ago. Is there an issue with the build? 

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/whats-new-in-office-365-atp?view=o365-worldwide
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide