Update sensitive-information-type-learn-about.md
MicrosoftDocs/microsoft-365-docs pull request #4070
Opened 2021-02-05 05:42 UTC by arastogi205

Adding a note for the current set of solutions that support the improved confidence levels.

2021-02-05 12:50 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-02-05 15:38 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-learn-about.md
> +> Please note that improved confidence levels are available for immediate use within Data Loss Prevention for Microsoft 365 services, Microsoft Information Protection for M365 services, Communication
```suggestion
> Improved confidence levels are available for immediate use within Data Loss Prevention for Microsoft 365 services, Microsoft Information Protection for Microsoft 365 services, Communication Compliance, Information Governance, and Records Management.
```

2021-02-05 15:38 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-08 05:41 UTC, yogkumgit commented
@arastogi205

2021-02-08 05:45 UTC, arastogi205 commented
i have committed the change. Will this start reflecting on the page?

2021-02-08 06:06 UTC, yogkumgit commented
@JohanFreelancer9

2021-02-08 07:44 UTC, JohanFreelancer9 approved these changes

2021-02-08 08:31 UTC, arastogi205 commented
@JohanFreelancer9 - will these changes now reflect on the webpage or does it need an additional approval from someone else?

2021-02-08 08:54 UTC, JohanFreelancer9 commented
@arastogi205 It still needs to be approved by the document owner before it can go live.

2021-02-08 13:10 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks.

2021-02-09 16:43 UTC, merged