Update set-up-content-understanding.md
MicrosoftDocs/microsoft-365-docs pull request #4075
Opened 2021-02-05 16:28 UTC by msbemba

Made a slight navigation change as the assign more button is not available any more

2021-02-05 16:28 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-05 16:29 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4024

2021-02-05 17:43 UTC, JohanFreelancer9 commented on microsoft-365/contentunderstanding/set-up-content-understanding.md
> +3. Click on **Apps** drop down.
```suggestion
3. Choose **Apps** from the drop-down menu.
```

2021-02-05 17:45 UTC, JohanFreelancer9 commented on microsoft-365/contentunderstanding/set-up-content-understanding.md
> +4. SelectSshow apps for  **SharePoint Syntex**. Under **Apps**, make sure **Common Data Service for SharePoint Syntex**, **SharePoint Syntex**, and **SharePoint Syntex - SPO type** are all selected.
```suggestion
4. Select **Show apps for  SharePoint Syntex**. Under **Apps**, make sure **Common Data Service for SharePoint Syntex**, **SharePoint Syntex**, and **SharePoint Syntex - SPO type** are all selected.
```

2021-02-05 17:46 UTC, JohanFreelancer9 commented on microsoft-365/contentunderstanding/set-up-content-understanding.md
>  2. Select the users that you want to license, and click **Manage product licenses**.
```suggestion
2. Select the users that you want to license, and choose **Manage product licenses**.
```

2021-02-05 17:48 UTC, JohanFreelancer9 requested changes
Copy review - not sure, please confirm that my suggestions are technically correct.

2021-02-06 04:38 UTC, JohanFreelancer9 approved these changes

2021-02-08 05:48 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks.

2021-02-08 13:49 UTC, merged