Update insider-risk-management-configure.md
MicrosoftDocs/microsoft-365-docs pull request #4096
Opened 2021-02-09 05:27 UTC by msbemba

Added Office 365 E3 + Enterprise Mobility and Security E3 + the Microsoft 365 E5 Compliance add-on reference document  https://www.microsoft.com/en-gb/microsoft-365/business/e5-compliance?activetab=pivot%3aoverviewtab

2021-02-09 05:28 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-09 05:28 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3972

2021-02-09 05:50 UTC, JohanFreelancer9 commented on microsoft-365/compliance/insider-risk-management-configure.md
> +- Office 365 E3 + Enterprise Mobility and Security E3 + the Microsoft 365 E5 Compliance add-on
```suggestion
- Office 365 E3 subscription + Enterprise Mobility and Security E3 + the Microsoft 365 E5 Compliance add-on
```

2021-02-09 05:50 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-09 06:44 UTC, JohanFreelancer9 approved these changes

2021-02-09 10:39 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2021-02-09 16:54 UTC, robmazz commented
@yogkumgit  and @msbemba - confirming with PG and Marketing

2021-02-11 21:46 UTC, robmazz commented
@yogkumgit and @msbemba - marketing folks have reached consensus and will add, but in different place on the list. Closing this and will merge separately.

2021-02-11 21:46 UTC, closed without merging