Update retention-policies-teams.md
MicrosoftDocs/microsoft-365-docs pull request #4103
Opened 2021-02-09 15:01 UTC by msbemba

Added Chat and call data for External users

2021-02-09 15:02 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4083

2021-02-09 15:02 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-09 16:51 UTC, JohanFreelancer9 commented on microsoft-365/compliance/retention-policies-teams.md
> +All Teams chats and calls are stored as compliance records in the Guest users shadow mailbox. However, Federated users in a call or chat would retain the compliance records in their own tenant.
```suggestion
All Teams chats and calls are stored as compliance records in the guest user's shadow mailbox. However, federated users in a call or chat would retain the compliance records in their own tenant.
```

2021-02-09 16:51 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-10 00:12 UTC, cabailey commented
As per the comments in the related GitHub Issue, closing this PR.

2021-02-10 00:12 UTC, closed without merging