Update report-junk-email-and-phishing-scams-in-outlook-for-iOS-and-An…
MicrosoftDocs/microsoft-365-docs pull request #4106
Opened 2021-02-09 17:11 UTC by andypunt

…droid.md

We should remove or update this article to use the Report Message or Report Phishing add-in experience. The native reporting experience has issues and we should no longer point people to it for security flows.

2021-02-10 14:51 UTC, siosulli commented
Hi @andypunt just before I merge this. In the Report Message and Report Phish articles we state: 

"If you're an admin in a Microsoft 365 organization with Exchange Online mailboxes, we recommend that you use the Submissions portal in the Security & Compliance Center." 

so I was just wondering if this new text is a bit conflicting? 

We could put a note at the top of this article instead, to state something like: 

To report messages to Microsoft, we recommend using the Report Message add-in or the Report Phishing add-in.

2021-02-10 16:48 UTC, andypunt commented
> Hi @andypunt just before I merge this. In the Report Message and Report Phish articles we state:
> 
> "If you're an admin in a Microsoft 365 organization with Exchange Online mailboxes, we recommend that you use the Submissions portal in the Security & Compliance Center."
> 
> so I was just wondering if this new text is a bit conflicting?
> 
> We could put a note at the top of this article instead, to state something like:
> 
> To report messages to Microsoft, we recommend using the Report Message add-in or the Report Phishing add-in.

That is still applicable since admin submissions is more powerful than user submissions. You can update the statement to call that out if needed. In other words, to report messages, you should use the Report Message or Phishing add-ins, but if you are an admin, you can use admin submissions in the security portal because it is gives you more in terms of feedback.

2021-02-11 10:32 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-02-12 08:40 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-for-iOS-and-Android.md
> +Admins should use the Report Message or the Report Phishing add-in experience to report messages: https://docs.microsoft.com/microsoft-365/security/office-365-security/enable-the-report-message-add-i
```suggestion
Admins should use the Report Message or the Report Phishing add-in experience to report messages. See [Enable the Report Message add-in](https://docs.microsoft.com/microsoft-365/security/office-365-security/enable-the-report-message-add-in) for more information.

```

2021-02-12 08:52 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-12 14:20 UTC, yogkumgit commented
@andypunt

2021-02-13 06:07 UTC, JohanFreelancer9 approved these changes

2021-02-15 06:06 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks.

2021-02-15 08:18 UTC, siosulli commented
@yogkumgit I will merge this morning. I just have one update to make after a discussion with Andy. thanks!

2021-02-15 12:37 UTC, merged