Update create-a-topic.md
MicrosoftDocs/microsoft-365-docs pull request #4184
Opened 2021-02-17 22:18 UTC by msbemba

Added a new line item to first click on the new topic page from the manage topics page before creating it.

2021-02-17 22:18 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4146

2021-02-17 22:18 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-18 02:57 UTC, JohanFreelancer9 commented on microsoft-365/knowledge/create-a-topic.md
> +1. Select the option to create a new Topic Page from the ribbon on the Manage Topics page.
```suggestion
1. Select the option to create a new topic page from the ribbon on the **Manage topics** page.
```

2021-02-18 02:58 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-18 12:59 UTC, yogkumgit commented
@msbemba

2021-02-18 17:40 UTC, merged