Update manage-deployment-of-add-ins.md
MicrosoftDocs/microsoft-365-docs pull request #4194
Opened 2021-02-19 12:23 UTC by msbemba

Added a note about integrated apps and only Global admins can access it.

2021-02-19 12:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-19 12:24 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4159

2021-02-19 12:49 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-deployment-of-add-ins.md
> +    > The admin center is getting updated to deployment experience with Integrated Apps .The Integrated Apps is supposed to be visible for Global administrator only, while for others the old experien
```suggestion
    > The admin center is getting updated to deployment experience with Integrated Apps. Integrated Apps are visible for Global administrators only, while for others the old experience still exists. If you don't see the above steps, go to the Centralized Deployment section by going to **Settings** > **Integrated apps**. On the top of the **Integrated apps** page, choose **Add-ins**.
```

2021-02-19 13:09 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-19 13:10 UTC, JohanFreelancer9 approved these changes

2021-02-22 08:46 UTC, yogkumgit commented
@scotvidican Please assign it to the right person for the merge. Thanks.

2021-02-23 17:52 UTC, merged