Update use-notifications-and-policy-tips.md
MicrosoftDocs/microsoft-365-docs pull request #4195
Opened 2021-02-19 12:31 UTC by msbemba

Added Conditions and Exceptions to the more information section

2021-02-19 12:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-19 12:31 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4131

2021-02-19 13:12 UTC, JohanFreelancer9 commented on microsoft-365/compliance/use-notifications-and-policy-tips.md
> +-
```suggestion
```

2021-02-19 13:13 UTC, JohanFreelancer9 requested changes
Copy review - please remove the blank line.

2021-02-20 04:47 UTC, JohanFreelancer9 approved these changes

2021-02-26 21:48 UTC, merged