Update atp-safe-links.md
MicrosoftDocs/microsoft-365-docs pull request #4203
Opened 2021-02-21 18:15 UTC by msbemba

Added the new option called to display the org branding on notification and warning pages

2021-02-21 18:15 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4163

2021-02-21 18:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-22 08:06 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/atp-safe-links.md
> +- **Display the organization branding on notification and warning pages**: This option is to show your organization’s branding on warning pages. This should help users identify that it’s a legitimate
```suggestion
- **Display the organization branding on notification and warning pages**: This option shows your organization’s branding on warning pages. This should help users identify that it’s a legitimate warning they’re seeing, as default Microsoft warning pages are often used by malicious actors to look legitimate themselves.
```

2021-02-22 08:06 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-22 08:57 UTC, JohanFreelancer9 approved these changes

2021-02-22 09:00 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks.

2021-02-26 08:16 UTC, msbemba commented
@JohanFreelancer9 I have made some minor changes. Could you please copy review?

2021-02-26 17:11 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/atp-safe-links.md
> +- **Display the organization branding on notification and warning pages**: This option shows your organization’s branding on warning pages. It should help users identify that it’s a legitimate warnin
```suggestion
- **Display the organization branding on notification and warning pages**: This option shows your organization’s branding on warning pages. It should help users identify that it’s a legitimate warning they’re seeing, as default Microsoft warning pages are often used by malicious actors to look legitimate themselves. See [Add branding to your organization's Azure Active Directory sign-in page](https://docs.microsoft.com/azure/active-directory/fundamentals/customize-branding) for more information about customized branding.
```

2021-02-26 17:12 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-26 18:08 UTC, JohanFreelancer9 approved these changes

2021-03-11 17:51 UTC, merged