Add "Important" to the managed devices callout.
MicrosoftDocs/microsoft-365-docs pull request #4210
Opened 2021-02-22 14:55 UTC by petey121175

Would like to add an "Important" notification to the managed device callout.

2021-02-23 13:14 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-02-23 16:25 UTC, JohanFreelancer9 commented on microsoft-365/knowledge/set-up-topic-experiences.md
> +## Important ##
```suggestion
> [!IMPORTANT]
```

2021-02-23 16:25 UTC, JohanFreelancer9 commented on microsoft-365/knowledge/set-up-topic-experiences.md
> +
```suggestion
```

2021-02-23 16:26 UTC, JohanFreelancer9 commented on microsoft-365/knowledge/set-up-topic-experiences.md
>  If you have configured SharePoint to [require managed devices](https://docs.microsoft.com/sharepoint/control-access-from-unmanaged-devices), be sure to set up Topics from a managed device.
```suggestion
> If you have configured SharePoint to [require managed devices](https://docs.microsoft.com/sharepoint/control-access-from-unmanaged-devices), you must set up Topics from a managed device.
```

2021-02-23 16:26 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-24 10:23 UTC, yogkumgit commented
@petey121175

2021-03-01 15:31 UTC, yogkumgit commented
Reminder @petey121175

2021-03-06 20:18 UTC, Josegto1 approved these changes

2021-03-07 03:27 UTC, yogkumgit commented
@JohanFreelancer9

2021-03-07 05:38 UTC, Josegto1 commented
AP

2021-03-07 05:57 UTC, Josegto1 approved these changes
GJ

2021-03-08 04:55 UTC, JohanFreelancer9 approved these changes

2021-08-20 12:38 UTC, merged