Update manage-addins-in-the-admin-center.md
MicrosoftDocs/microsoft-365-docs pull request #4212
Opened 2021-02-22 16:05 UTC by msbemba

fixed deadlink for centralized deployment powershell cmdlets to manage add-ins

2021-02-22 16:05 UTC, msbemba commented
@JohanFreelancer9 please copy review

2021-02-22 16:05 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4168

2021-02-23 05:40 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-addins-in-the-admin-center.md
> +[Use Centralized Deployment PowerShell cmdlets to manage add-ins](https://docs.microsoft.com/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins).
```suggestion
[Use the Centralized Deployment PowerShell cmdlets to manage add-ins](https://docs.microsoft.com/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins)
```

2021-02-23 05:40 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-23 16:09 UTC, JohanFreelancer9 approved these changes

2021-03-26 06:09 UTC, closed without merging