Update manage-guest-access-in-groups.md
MicrosoftDocs/microsoft-365-docs pull request #4219
Opened 2021-02-23 07:13 UTC by msbemba

Added a not about adding a Guest user to an M365 group using Dynamic membership rules

2021-02-23 07:13 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-23 07:13 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4202

2021-02-24 10:24 UTC, yogkumgit commented
@JohanFreelancer9

2021-02-24 16:18 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/manage-guest-access-in-groups.md
> +> Dynamic membership is supported for Microsoft 365 Groups. If you want to add an external user to a M365 group using Dynamic membership rules, the option to "View all and manage members"  will not b
```suggestion
> Dynamic membership is supported for Microsoft 365 Groups. If you want to add an external user to a Microsoft 365 group using dynamic membership rules, the option to "View all and manage members"  will not be available in the admin center. Instead, you need to [create or update a dynamic group in Azure Active Directory](https://docs.microsoft.com/azure/active-directory/enterprise-users/groups-create-rule).
```

2021-02-24 16:19 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-25 04:16 UTC, JohanFreelancer9 approved these changes

2021-02-25 04:28 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-02-25 13:44 UTC, merged