Update setup-guides-for-microsoft-365.md
MicrosoftDocs/microsoft-365-docs pull request #4220
Opened 2021-02-23 07:22 UTC by msbemba

Added the new Integrate a third-party cloud app with Azure AD to the documentation

2021-02-23 07:22 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-23 07:22 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4197

2021-02-23 15:06 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +Improve the user experience and provide an additional layer of security by integrating your third-party app with ‎Azure Active Directory (Azure AD). With this end-to-end experience you can do most of
```suggestion
Improve the user experience and provide an additional layer of security by integrating your third-party app with ‎Azure Active Directory (Azure AD). With this end-to-end experience, you can do most of the configuration directly from this wizard. Where appropriate, we'll redirect you to the corresponding configuration page.
```

2021-02-23 15:07 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +Use the [Integrate third-party cloud app](https://admin.microsoft.com/Adminportal/Home?#/azureadappintegration) wizard to Integrate a third-party cloud app with Azure AD.
```suggestion
Use the [Integrate third-party cloud app](https://admin.microsoft.com/Adminportal/Home?#/azureadappintegration) wizard to integrate a third-party cloud app with Azure AD.
```

2021-02-23 15:10 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-24 04:53 UTC, JohanFreelancer9 approved these changes

2021-02-24 17:05 UTC, merged