Update install-app-guard.md
MicrosoftDocs/microsoft-365-docs pull request #4239
Opened 2021-02-24 03:55 UTC by ekarafezov

Adding location to Office-specific policies in group policy editor. @Dansimp @beschorr

2021-02-24 10:25 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-02-24 15:34 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/install-app-guard.md
> +Policy settings can be found in **User Configuration\Administrative Templates\Microsoft Office 2016\Security Settings\Trust Center\Application Guard.**
```suggestion
Policy settings can be found in **User Configuration\Administrative Templates\Microsoft Office 2016\Security Settings\Trust Center\Application Guard**.
```

2021-02-24 15:35 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-02-25 04:23 UTC, yogkumgit commented
@ekarafezov

2021-02-25 04:36 UTC, ekarafezov commented
Yes, bold should end after the period. Thanks!

2021-02-25 07:50 UTC, JohanFreelancer9 approved these changes
Good to go. I deleted my suggestion.

2021-03-01 19:00 UTC, ekarafezov commented
Anything else need to merge this change? I'm new to this process but I anticipate more frequent updates may be needed and coming up as I hear more customer feedback on this article. Thanks!

2021-03-06 02:55 UTC, JohanFreelancer9 commented
@yogkumgit

2021-04-06 16:18 UTC, yogkumgit commented
@maccaoz-zz Please merge this PR. Thanks

2021-08-20 13:44 UTC, tiburd commented on microsoft-365/security/office-365-security/install-app-guard.md
> +Policy settings can be found in **User Configuration\Administrative Templates\Microsoft Office 2016\Security Settings\Trust Center\Application Guard.**
```suggestion
Policy settings can be found at **User Configuration** > **Administrative Templates** > **Microsoft Office 2016** > **Security Settings** > **Trust Center** > **Application Guard**.
```

2021-08-20 14:12 UTC, tiburd commented
@ekarafezov 

Can you please confirm that your proposed changes are still valid? Where you proposed your change, a link has been added:

- Here's the article: https://docs.microsoft.com/microsoft-365/security/office-365-security/install-app-guard
- The relevant information has been replaced with a link to this article: https://docs.microsoft.com/DeployOffice/overview-office-cloud-policy-service

Please @ mention me in your reply. Thank you!

2021-08-20 16:59 UTC, ekarafezov commented
You can abandon this PR, it's been a while and there were later changes so this is no longer applicable.

From: Tina Burden ***@***.***>
Sent: Friday, August 20, 2021 7:13 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Emil Karafezov ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update install-app-guard.md (#4239)


@ekarafezov<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fekarafezov&data=04%7C01%7CEmil.Karafezov%40microsoft.com%7Cc675de5f21f8404d5f2908d963e4a2a8%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650655919015705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2Ry%2Bd7oXGZdKUT4xVVeEWqgI2PP181mcEa3Qb4yD%2F3s%3D&reserved=0>

Can you please confirm that your proposed changes are still valid? Where you proposed your change, a link has been added:

  *   Here's the article: https://docs.microsoft.com/microsoft-365/security/office-365-security/install-app-guard<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fmicrosoft-365%2Fsecurity%2Foffice-365-security%2Finstall-app-guard&data=04%7C01%7CEmil.Karafezov%40microsoft.com%7Cc675de5f21f8404d5f2908d963e4a2a8%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650655919025687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rNzN9piR2gbQVDcTNN7DdaGv4kpPXk0kF2lXDINmjd8%3D&reserved=0>
  *   The relevant information has been replaced with a link to this article: https://docs.microsoft.com/DeployOffice/overview-office-cloud-policy-service<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2FDeployOffice%2Foverview-office-cloud-policy-service&data=04%7C01%7CEmil.Karafezov%40microsoft.com%7Cc675de5f21f8404d5f2908d963e4a2a8%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650655919025687%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JXfVgGksN%2FpbYahjhmz59x6GG52SYK2WWDwhuJnxsOo%3D&reserved=0>

Please @ mention me in your reply. Thank you!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F4239%23issuecomment-902722141&data=04%7C01%7CEmil.Karafezov%40microsoft.com%7Cc675de5f21f8404d5f2908d963e4a2a8%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650655919035683%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZAo1Yc5ZT8sBCKedlzweirckkQ7kmVlWFrAWaMxaSFo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASPMFME4R5RJYSXBYZOPIM3T5ZPHHANCNFSM4YDXE5LA&data=04%7C01%7CEmil.Karafezov%40microsoft.com%7Cc675de5f21f8404d5f2908d963e4a2a8%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650655919035683%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zFi%2FiyaP7a21Gov%2Fsbz4EBTzenAj4SBvWDMd%2By%2BJVhc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CEmil.Karafezov%40microsoft.com%7Cc675de5f21f8404d5f2908d963e4a2a8%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650655919045686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BI9MIg%2FIv4Zkv7Fncq71auLqDkdiEAcXTZddcWGvLRE%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CEmil.Karafezov%40microsoft.com%7Cc675de5f21f8404d5f2908d963e4a2a8%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637650655919045686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yTgDD%2Fn%2Fpwh4QvmZSBJlg%2FVOv26eX0%2FcLwJRYerEuoA%3D&reserved=0>.

2021-08-20 17:15 UTC, closed without merging