Updated link to validation document
MicrosoftDocs/microsoft-365-docs pull request #4241
Opened 2021-02-24 15:55 UTC by anwara-ms

Updated link to validation document

2021-02-25 14:46 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-02-26 02:06 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-tenant-level.md
> +These steps are similar but not identical to the steps for setting up Customer Key at the application level. You should only use this public preview with test data in test tenants. Do not use this re
```suggestion
These steps are similar but not identical to the steps for setting up Customer Key at the application level. You should only use this public preview with test data in test tenants. Do not use this release with production data or in your production environment. If you already have a production deployment of Customer Key, use these steps to set up Customer Key at the tenant level in a test environment. Once you have assigned a tenant level DEP to your tenant, you can start the validation process and reach out to m365ck@microsoft.com with any questions or concerns. You can also find have documented validation steps in the public preview of [Validation Instructions for Data-at-rest Encryption for Microsoft 365](https://aka.ms/CustomerKey/PublicPreviewValidation).
```

2021-02-26 02:07 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-26 04:32 UTC, yogkumgit commented
@anwara-ms

2021-02-26 15:08 UTC, anwara-ms commented
looks good to me.

2021-02-26 15:08 UTC, anwara-ms commented
is it ready to be published today?

2021-02-26 17:52 UTC, JohanFreelancer9 commented
@anwara-ms - please commit my changes.

2021-02-26 19:58 UTC, anwara-ms commented
I just did. All looking good to publish?

2021-02-27 02:51 UTC, JohanFreelancer9 approved these changes

2021-03-08 18:57 UTC, anwara-ms commented
Hi, this is still not published. Reminder- @KCCross

2021-03-16 20:19 UTC, merged