made changes to powershell commandlet
MicrosoftDocs/microsoft-365-docs pull request #4245
Opened 2021-02-24 19:39 UTC by anwara-ms

made changes to powershell commandlet

Original cmdlet was giving error

2021-02-25 14:46 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-02-26 01:40 UTC, JohanFreelancer9 commented on microsoft-365/compliance/information-barriers-policies.md
> +   1. Pre-requisite: Install Azure PowerShell from [here](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps)
```suggestion
   1. Pre-requisite: [Install Azure PowerShell](https://docs.microsoft.com/powershell/azure/install-az-ps).
```

2021-02-26 01:42 UTC, JohanFreelancer9 commented on microsoft-365/compliance/information-barriers-policies.md
> +   1. Pre-requisite: Install Azure PowerShell from [here](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps)
```suggestion
   1. Pre-requisite: Install Azure PowerShell from [here](https://docs.microsoft.com/powershell/azure/install-az-ps).
```

2021-02-26 01:44 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-26 04:31 UTC, yogkumgit commented
@anwara-ms

2021-02-26 07:42 UTC, JohanFreelancer9 commented on microsoft-365/compliance/information-barriers-policies.md
> +      Connect-AzAccount -Tenant "<yourtenantdomain.com>"  //e.g. Connect-AzAccount -Tenant "Contoso.onmicrosoft.com"
```suggestion
      Connect-AzAccount -Tenant "<yourtenantdomain.com>", for example Connect-AzAccount -Tenant "Contoso.onmicrosoft.com"
```

2021-02-26 15:11 UTC, anwara-ms commented
plz dont remove "//", as if you remove it, the line will become part of code that runs in powershell and will give error output.

2021-02-26 18:00 UTC, JohanFreelancer9 approved these changes

2021-02-26 19:57 UTC, anwara-ms reviewed
all good from my end.

2021-02-26 19:57 UTC, anwara-ms commented
I cant approve. Can someone approve and merge to production plz?

2021-03-15 19:48 UTC, merged