Changes to update FAQ and known issues section
MicrosoftDocs/microsoft-365-docs pull request #4260
Opened 2021-02-25 23:00 UTC by anwara-ms

Changes to update FAQ and known issues section

Please use content from this document for FAQ section

https://microsoft-my.sharepoint-df.com/:w:/p/anwara/EZafBUGq44BJvCYe0-YwiJAB8y6PR1DGQaGIb0gpeoA2DA?e=sjfeoW

2021-02-25 23:02 UTC, anwara-ms commented
@brdesai  FYI

2021-03-01 15:28 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-02 02:44 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-tenant-level.md
> +## Known Issues
```suggestion
## Known issues
```

2021-03-02 02:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-tenant-level.md
> +- We see that when Customer Key is enabled, creation of team from Microsoft Teams fails.
```suggestion
- When Customer Key is enabled, the creation of a new team in Microsoft Teams fails.
```

2021-03-02 02:48 UTC, JohanFreelancer9 requested changes
Copy review - I'll do a complete copy edit once the requested FAQs are included in this topic.

2021-03-02 03:56 UTC, yogkumgit commented
@anwara-ms

2021-03-08 18:55 UTC, anwara-ms commented
Hi, is it ready to be published? Can you send me preview on how the FAQ section will look like?

2021-03-09 14:58 UTC, yogkumgit commented
@JohanFreelancer9

2021-03-10 05:26 UTC, JohanFreelancer9 commented
@yogkumgit - I do not have access to the reference document to include the FAQs in this PR so someone else has to incorporate it.

2021-03-10 11:29 UTC, yogkumgit commented
@KCCross

2021-03-16 19:13 UTC, anwara-ms commented
for your action @KCCross  @LauraWi . Please help publish this.

2021-03-26 22:20 UTC, KCCross commented
Several of these are incorporated through another PR. Some of these are still in discussion. Leaving this PR open while we discuss offline.

2021-06-17 17:17 UTC, KCCross commented
Content added through other PRs. closing.

2021-06-17 17:17 UTC, closed without merging