Update ome-version-comparison.md
MicrosoftDocs/microsoft-365-docs pull request #4262
Opened 2021-02-26 00:59 UTC by samschan-ms

Added KB article that describes how to determine and migrate AD RMS to Azure RMS.
@KCCross please review.

2021-03-01 15:28 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-02 02:50 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-version-comparison.md
>  Exchange Online includes Information Rights Management (IRM) functionality that provides online and offline protection of email messages and attachments. By default, Exchange Online uses Azure Azure
```suggestion
Exchange Online includes Information Rights Management (IRM) functionality that provides online and offline protection of email messages and attachments. By default, Exchange Online uses Azure Information Protection. However, your organization may have configured Exchange Online IRM to use on-premises Active Directory Rights Management Service (AD RMS). AD RMS support in Exchange Online is retiring. Instead, Azure Information Protection will replace AD RMS entirely.
```

2021-03-02 02:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-version-comparison.md
> +See [KB article 5001237]https://support.microsoft.com/help/5001237 to assess whether this impacts your organization.  The article provides recommendation on migation options.
```suggestion
See [KB article 5001237](https://support.microsoft.com/help/5001237) to assess whether this deprecation impacts your organization. The article provides recommendations on migration options.
```

2021-03-02 02:58 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-02 03:56 UTC, yogkumgit commented
@samschan-ms

2021-03-03 11:17 UTC, yogkumgit commented
@JohanFreelancer9

2021-03-03 16:17 UTC, JohanFreelancer9 commented
@samschan-ms - please commit my second suggestion as well.

2021-03-03 17:23 UTC, JohanFreelancer9 approved these changes

2021-03-26 22:15 UTC, merged