Update prerequisites.md
MicrosoftDocs/microsoft-365-docs pull request #4264
Opened 2021-02-26 07:35 UTC by msbemba

Added mailbox requirements

2021-02-26 07:35 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4186

2021-02-26 07:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-02-26 07:46 UTC, JohanFreelancer9 commented on microsoft-365/security/mtp/prerequisites.md
> +## Mailbox Requirements
```suggestion
## Mailbox requirements
```

2021-02-26 07:50 UTC, JohanFreelancer9 commented on microsoft-365/security/mtp/prerequisites.md
> +- Microsoft 365 Defender can be enabled to protect Exchange Online cloud-hosted mailboxes. To learn more about Exchange Online, see the Exchange Online service description.
```suggestion
- Microsoft 365 Defender can be enabled to protect Exchange Online cloud-hosted mailboxes. To learn more about Exchange Online, see the [Exchange Online service description](https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description).
```

2021-02-26 07:54 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-26 07:59 UTC, JohanFreelancer9 approved these changes

2021-03-01 11:53 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-04-06 14:23 UTC, yogkumgit commented
@mjcaparas Gentel reminder, Please merge this PR. Thanks.

2021-04-06 20:57 UTC, mjcaparas commented
pls resolve conflicts. then i can merge.

2021-04-06 21:17 UTC, msbemba commented
@yogkumgit  @JohanFreelancer9  for some reason I don't see an option to resolve conflicts and it is grayed out (saying Only those with the write access can merge pull requests). Let me know what to do.

2021-04-07 10:55 UTC, yogkumgit commented
@Kateyanne Please provide the internal help. Thanks.

2021-04-08 14:53 UTC, msbemba commented
@yogkumgit The changes are made on the document already. So this PR is no longer required.

2021-04-08 14:53 UTC, closed without merging