Update virus-detection-in-spo.md
MicrosoftDocs/microsoft-365-docs pull request #4308
Opened 2021-03-02 21:33 UTC by AdwoodMicrosoft

clarity around the AV scan order of events and asynchronous wording.

2021-03-05 14:03 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-06 07:01 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/virus-detection-in-spo.md
> +## What happens if an infected file is uploaded to SharePoint Online?
```suggestion
## What happens if an infected file is uploaded to SharePoint Online?
```

2021-03-06 07:02 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/virus-detection-in-spo.md
> +The Microsoft 365 virus detection engine runs asynchronously (idenpedent from file uploads) within SharePoint Online. **All files are not automatically scanned**. Heuristics determine the files to sc
```suggestion
The Microsoft 365 virus detection engine runs asynchronously (independent from file uploads) within SharePoint Online. **All files are not automatically scanned**. Heuristics determine the files to scan. When a file is found to contain a virus, the file is flagged. In April 2018, we removed the 25 MB limit for scanned files.
```

2021-03-06 07:03 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/virus-detection-in-spo.md
> +2. SharePoint Online as part of its virus scanning processes later determines if the file meets the criteria for a scan.
```suggestion
2. SharePoint Online, as part of its virus scanning processes, later determines if the file meets the criteria for a scan.
```

2021-03-06 07:05 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-07 03:23 UTC, yogkumgit commented
@AdwoodMicrosoft

2021-03-11 17:47 UTC, merged