Update microsoft-365-groups-expiration-policy.md
MicrosoftDocs/microsoft-365-docs pull request #4339
Opened 2021-03-05 05:09 UTC by msbemba

Not sure if this can be added as another line but Added a note about Yammer native mode.

2021-03-05 05:09 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-03-05 05:09 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4263

2021-03-05 06:30 UTC, JohanFreelancer9 commented on microsoft-365/solutions/microsoft-365-groups-expiration-policy.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2021-03-05 06:33 UTC, JohanFreelancer9 commented on microsoft-365/solutions/microsoft-365-groups-expiration-policy.md
> +> Microsoft 365 Groups converted by Yammer in native mode do not renew automatically and the yammer activities donot count for automatic renewal. For more information about Native mode, See[Overview
```suggestion
> Microsoft 365 Groups converted by Yammer in Native Mode do not renew automatically and the Yammer activities do not count towards automatic renewal. For more information about Native Mode, see [Overview of Native Mode](https://docs.microsoft.com/yammer/configure-your-yammer-network/overview-native-mode).
```

2021-03-05 06:33 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-05 12:24 UTC, yogkumgit commented
@msbemba

2021-03-05 18:12 UTC, MikePlumleyMSFT commented
@ArunMSFT can you review?

2021-03-06 06:10 UTC, JohanFreelancer9 approved these changes

2021-03-08 18:27 UTC, Josegto1 approved these changes

2021-03-09 14:56 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks.

2021-03-18 11:25 UTC, yogkumgit commented
Gentle reminder @MikePlumleyMSFT Please merge this PR. Thanks.

2021-03-18 13:41 UTC, MikePlumleyMSFT commented
@ArunMSFT can you review?

2021-03-23 12:39 UTC, merged