Update allow-members-to-send-as-or-send-on-behalf-of-group.md
MicrosoftDocs/microsoft-365-docs pull request #4340
Opened 2021-03-05 05:25 UTC by msbemba

replaced members with users for the below reasons. verify and let me know if this is OK or should we just add a note about these two line items.

1) users can send emails as a group even without being a member of a group
2) not all members have access to send as and only internal users have that privilege.

2021-03-05 05:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-03-05 05:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4284

2021-03-05 06:25 UTC, JohanFreelancer9 commented on microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md
> +title: "Allow Users to send as or send on behalf of a Group"
```suggestion
title: "Allow users to send as or send on behalf of a Group"
```

2021-03-05 06:26 UTC, JohanFreelancer9 commented on microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md
> +# Allow Users to send as or send on behalf of a group
```suggestion
# Allow users to send as or send on behalf of a group
```

2021-03-05 06:28 UTC, JohanFreelancer9 commented on microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md
>  description: "Learn how to allow members to send email as a Microsoft 365 group or send email on behalf of a Microsoft 365 group."
```suggestion
description: "Learn how to allow users to send email as a Microsoft 365 group or send email on behalf of a Microsoft 365 group."
```

2021-03-05 06:29 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-05 12:28 UTC, yogkumgit commented
@msbemba

2021-03-05 18:08 UTC, MikePlumleyMSFT commented
@msbemba "users" is too broad a term. Let's just note that guests aren't included near the top of the article.

2021-03-06 19:40 UTC, Josegto1 approved these changes

2021-03-06 19:40 UTC, Josegto1 approved these changes

2021-03-07 12:41 UTC, msbemba commented
@JohanFreelancer9 Please copy review.

2021-03-08 03:57 UTC, JohanFreelancer9 commented on microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md
> +> [!Note]
```suggestion
> [!NOTE]
```

2021-03-08 04:02 UTC, JohanFreelancer9 commented on microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md
> +> Guests who are members of the group cannot be granted to send as or send on behalf of a group
```suggestion
> Guests who are members of a Microsoft 365 group cannot be granted **Send as** or **Send on behalf** permissions for the group.
```

2021-03-08 04:02 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-08 09:07 UTC, JohanFreelancer9 approved these changes

2021-03-11 13:23 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-03-11 13:40 UTC, merged