Update use-network-upload-to-import-pst-files.md
MicrosoftDocs/microsoft-365-docs pull request #4341
Opened 2021-03-05 05:29 UTC by msbemba

Made changes to the navigation as it has changed

2021-03-05 05:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-03-05 05:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4295

2021-03-05 06:23 UTC, JohanFreelancer9 commented on microsoft-365/compliance/use-network-upload-to-import-pst-files.md
> +2. Start the Microsoft Azure Storage Explorer, Choose **Blob Container**
```suggestion
2. Start the Microsoft Azure Storage Explorer and choose **Blob Container**.
```

2021-03-05 06:24 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-06 07:08 UTC, JohanFreelancer9 approved these changes

2021-03-09 00:13 UTC, merged