Update use-dkim-to-validate-outbound-email.md
MicrosoftDocs/microsoft-365-docs pull request #4342
Opened 2021-03-05 05:42 UTC by msbemba

Added another line about configuring DKIM for the first time

2021-03-05 05:42 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-03-05 05:42 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3076

2021-03-05 06:21 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md
> +6.  If you are configuring DKIM for the first time and see the error 'No DKIM keys saved for this domain.' you will have to use Windows powershell to enable Dkim Signing as explained in the next step
```suggestion
6. If you are configuring DKIM for the first time and see the error 'No DKIM keys saved for this domain.' you will have to use Windows PowerShell to enable DKIM Signing as explained in the next step.
```

2021-03-05 06:21 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-05 12:31 UTC, yogkumgit commented
@msbemba

2021-03-06 07:12 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md
> +6. If you are configuring DKIM for the first time and see the error 'No DKIM keys saved for this domain.' you will have to use Windows PowerShell to enable DKIM Signing as explained in the next step.
```suggestion
6. If you are configuring DKIM for the first time and see the error 'No DKIM keys saved for this domain.' you will have to use Windows PowerShell to enable DKIM signing as explained in the next step.
```

2021-03-06 07:13 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more minor edit, please.

2021-03-06 18:13 UTC, Josegto1 approved these changes

2021-03-07 03:24 UTC, yogkumgit commented
@JohanFreelancer9

2021-03-08 04:36 UTC, JohanFreelancer9 approved these changes

2021-04-05 14:28 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks.

2021-07-20 18:51 UTC, MSFTTracyP reviewed
"If you are configuring DKIM for the first time and see the error 'No DKIM keys saved for this domain.' you"

So if you're quoting an error message, don't include the period mark. It can be confusing.

2021-07-20 18:53 UTC, merged