Update sensitive-information-type-learn-about.md to include a note for customers moving from existing number based system to upgraded confidence levels
MicrosoftDocs/microsoft-365-docs pull request #4345
Opened 2021-03-05 09:32 UTC by arastogi205

@chrfox - we have had a couple of enquiries from existing customers on how their existing policies & custom SITs will get impacted and if they need to take an action to move to the upgraded confidence levels. I have added this not in order to address the same. Please review and suggest changes.

2021-03-05 14:09 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-06 06:40 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-learn-about.md
> +> If you have existing policies or custom SITs defined using number based confidence levels(also know as accuracy), then they will automatically be mapped to the three discrete confidence levels - lo
```suggestion
> If you have existing policies or custom sensitive information types (SITs) defined using number-based confidence levels (also know as accuracy), they will automatically be mapped to the three discrete confidence levels; low confidence, medium confidence, and high confidence, across the Security @ Compliance Center UI.
```

2021-03-06 06:41 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-learn-about.md
> +> - All policies with min accuracy or custom SIT patterns with confidence levels between 76 & 100 will be mapped to high confidence.
```suggestion
> - All policies with minimum accuracy or custom SIT patterns with confidence levels of between 76 and 100 will be mapped to high confidence. 
```

2021-03-06 06:42 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-learn-about.md
> +> - All policies with min accuracy or custom SIT patterns with confidence levels between 66 & 75 will be mapped to medium confidence.
```suggestion
> - All policies with minimum accuracy or custom SIT patterns with confidence levels of between 66 and 75 will be mapped to medium confidence.
```

2021-03-06 06:44 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-learn-about.md
> +> - All policies with min accuracy or custom SIT patterns with confidence levels less than equal to 65 will be mapped to low confidence.
```suggestion
> - All policies with minimum accuracy or custom SIT patterns with confidence levels less than or equal to 65 will be mapped to low confidence. 
```

2021-03-06 06:44 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-06 18:25 UTC, Josegto1 approved these changes

2021-03-07 03:21 UTC, yogkumgit commented
@JohanFreelancer9

2021-03-08 05:37 UTC, JohanFreelancer9 commented
@arastogi205 - please commit my suggestions.

2021-03-08 09:15 UTC, arastogi205 commented
@JohanFreelancer9 - done. Thanks for the recommended changes.

2021-03-08 09:21 UTC, JohanFreelancer9 approved these changes

2021-03-11 20:57 UTC, merged