Search times
MicrosoftDocs/microsoft-365-docs pull request #4350
Opened 2021-03-05 18:28 UTC by StefanieBier

These are included in the AeD article and need to be in the content search limits as well

2021-03-08 15:44 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-09 06:34 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +## Search Times
```suggestion
## Search times
```

2021-03-09 06:37 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +Microsoft collects performance information for searches run by all organizations. While the complexity of the search query can impact search times, the biggest factor that affects how long searches t
```suggestion
We collect performance information for searches run by all organizations. While the complexity of the search query can impact search times, the biggest factor that affects how long searches take is the number of mailboxes searched. Although we don't provide a Service Level Agreement for search times, the following table lists average search times for collection searches based on the number of mailboxes included in the search.
```

2021-03-09 06:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +Number of mailboxes	Average search time
```suggestion
| Number of mailboxes| Average search time |
|:-----|:-----|
|100  <br/> |30 seconds<br/> |
|1,000  <br/> |45 seconds<br/> |
|10,000  <br/> |4 minutes<br/> |
|25,000  <br/> |10 minures<br/> |
|50,000  <br/> |20 minutes<br/> |
|100,000  <br/> |25 minutes<br/> |


```

2021-03-09 06:51 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +100
```suggestion
```

2021-03-09 06:51 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +30 seconds
```suggestion
```

2021-03-09 06:51 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +1,000
```suggestion
```

2021-03-09 06:52 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +45 seconds
```suggestion
```

2021-03-09 06:52 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +10,000
```suggestion
```

2021-03-09 06:52 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +4 minutes
```suggestion
```

2021-03-09 06:52 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +25,000
```suggestion
```

2021-03-09 06:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +10 minutes
```suggestion
```

2021-03-09 06:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +50,000
```suggestion
```

2021-03-09 06:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +20 minutes
```suggestion
```

2021-03-09 06:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +100,000
```suggestion
```

2021-03-09 06:54 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-for-content-search.md
> +25 minutes
```suggestion
```

2021-03-09 06:55 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-09 15:21 UTC, yogkumgit commented
@StefanieBier

2021-03-09 18:04 UTC, markjjo commented
@Yogeshmahi @JohanFreelancer9 These search times must be formatted as a table. At some point in this PR, the table formatting got removed. Table formatting needs to be added back into topic.

2021-03-10 04:10 UTC, JohanFreelancer9 commented
@StefanieBier - could you please format these times as a table, as requested? Thanks.

2021-03-10 19:00 UTC, merged

2021-03-10 19:01 UTC, markjjo commented
@StefanieBier @JohanFreelancer9 I took care of the formatting and merged the PR; no more work is necessary