Added B2B requirements for tenant to valid issuers
MicrosoftDocs/microsoft-365-docs pull request #4354
Opened 2021-03-05 20:46 UTC by dke-benjy

2021-03-08 15:44 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-09 06:20 UTC, JohanFreelancer9 commented on microsoft-365/compliance/double-key-encryption.md
> +Please note: if you want to enable external B2B access to your key store, you will also need to include these external tenants as part of the valid issuers list.
```suggestion
> [!NOTE]
> If you want to enable external B2B access to your key store, you will also need to include these external tenants as part of the valid issuers' list.
```

2021-03-09 06:26 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-09 15:19 UTC, yogkumgit commented
@dke-benjy

2021-03-26 22:20 UTC, merged