Update Basic Mobility&Security comparison areas
MicrosoftDocs/microsoft-365-docs pull request #4363
Opened 2021-03-08 09:09 UTC by v-rechau

It felt quite odd for one of the Feature Areas to be called "Basic Mobility and Security Application Management", only for it to say that Basic Mobility and Security doesn't support that feature at all.

2021-03-08 10:14 UTC, Josegto1 approved these changes
@

2021-03-08 15:46 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-09 06:06 UTC, JohanFreelancer9 commented on microsoft-365/admin/basic-mobility-security/choose-between-basic-mobility-and-security-and-intune.md
>  |Zero touch enrollment programs Autopilot) |Enroll large numbers of corporate-owned devices, while simplifying user setup. |No|Yes|
```suggestion
|Zero touch enrollment programs (AutoPilot) |Enroll large numbers of corporate-owned devices, while simplifying user setup. |No|Yes|
```

2021-03-09 06:08 UTC, JohanFreelancer9 requested changes
@v-rechau - not related to this PR, but please also commit my additional typo correction.

2021-03-09 15:18 UTC, yogkumgit commented
@JohanFreelancer9

2021-03-10 04:41 UTC, JohanFreelancer9 approved these changes

2021-03-18 14:19 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2021-03-18 17:57 UTC, merged