Adding license mention
MicrosoftDocs/microsoft-365-docs pull request #4396
Opened 2021-03-09 20:57 UTC by computeronix

Mentioning license for this, which basically mentions this is included as part of owning M365

2021-03-10 12:50 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-11 06:12 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +A license that provides access to the M365 Admin Center.
```suggestion
You require a  license that provides access to the Microsoft 365 Admin Center.
```

2021-03-11 06:13 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-11 13:10 UTC, yogkumgit commented
@computeronix

2021-03-16 14:44 UTC, yogkumgit commented
@computeronix Gentle reminder

2021-03-26 08:22 UTC, JohanFreelancer9 approved these changes

2021-04-02 20:18 UTC, merged