Update limits-ediscovery20.md
MicrosoftDocs/microsoft-365-docs pull request #4434
Opened 2021-03-15 18:06 UTC by shelri

These changes are a reflection to a larger clarification of what all counts towards the 4,000 character search limit customers are experiencing.

2021-03-16 14:44 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-17 04:29 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-ediscovery20.md
> +|Maximum number of characters for a search query for Sharepoint and OneDrive For Business Sites (including operators and conditions). |10,000<br>4,000 with Wildcards&nbsp;<sup>2</sup>|
```suggestion
|Maximum number of characters for a search query for SharePoint and OneDrive for Business sites (including operators and conditions). |10,000<br>4,000 with Wildcards&nbsp;<sup>2</sup>|
```

2021-03-17 04:31 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-ediscovery20.md
> +> - All Characters in both the Users and Filters fields
```suggestion
> - All characters in both the Users and Filters fields.
```

2021-03-17 04:32 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-ediscovery20.md
> +> - All Compliance Security Filters that apply to the user will be included in their search.
```suggestion
> - All compliance security filters that apply to the user will be included in their search.
```

2021-03-17 04:33 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-ediscovery20.md
> +> - The characters from any location properties in the search (ExchangeLocation,PublicFolderLocation,SharpointLocation,ExchangeLocationExclusion,PublicFolderLocationExclusion,SharePointLocationExclus
```suggestion
> - The characters from any location properties in the search (ExchangeLocation,PublicFolderLocation,SharPointLocation,ExchangeLocationExclusion,PublicFolderLocationExclusion,SharePointLocationExclusion, OneDriveLocationExclusion).
```

2021-03-17 04:33 UTC, JohanFreelancer9 commented on microsoft-365/compliance/limits-ediscovery20.md
> +> - Example: Including all SPO/ODB workloads will incur 6 characters as the word "ALL" will appear for both the SharePointLocation and OneDriveLocation
```suggestion
> - Example: Including all SPO/ODB workloads will incur 6 characters as the word "ALL" will appear for both the SharePointLocation and OneDriveLocation.
```

2021-03-17 04:36 UTC, JohanFreelancer9 requested changes
Copy review - @shelri please commit my suggestions.

2021-03-23 14:27 UTC, yogkumgit commented
Gentle reminder @shelri Please update with feedback

2021-03-23 19:04 UTC, markjjo commented
@yogkumgit I am working offline with @shelri and the PM on this PR. It's assigned to me and I will take ownership of any additional changes that need to be made.

2021-05-05 01:12 UTC, merged

2021-05-05 01:14 UTC, markjjo commented
@shelri PR merged. These updates in the three pull requests that you submitted should be published by EOD tomorrow. Thanks again for submitting these.