Update permissions-filtering-for-content-search.md
MicrosoftDocs/microsoft-365-docs pull request #4435
Opened 2021-03-15 18:06 UTC by shelri

This is a part of a larger update of documentation for eDiscovery cases we have seen. We have a 4,000 character limit for sharepoint and ODB site searches that customers are hitting due to how searches are expanded on the backend.

2021-03-16 14:45 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-17 04:24 UTC, JohanFreelancer9 commented on microsoft-365/compliance/permissions-filtering-for-content-search.md
> +- **Do Compliance Security Filters Count against Search Query Limits?** Yes. Compliance Security filters do count against the character limit for Search queries. For more information, see [Limits in
```suggestion
- **Do compliance security filters count against search query limits?** Yes. Compliance security filters do count against the character limit for search queries. For more information, see [Limits in Advanced eDiscovery](https://docs.microsoft.com/microsoft-365/compliance/limits-ediscovery20?view=o365-worldwide).
```

2021-03-17 04:25 UTC, JohanFreelancer9 requested changes
Copy review - @shelri please commit my suggestions.

2021-03-23 14:28 UTC, yogkumgit commented
Gentle reminder @shelri Please update with feedback

2021-03-23 19:03 UTC, markjjo commented
@yogkumgit I am working offline with @shelri and the PM on this PR. It's assigned to me and I will take ownership of any additional changes that need to be made.

2021-05-05 01:02 UTC, merged

2021-05-05 01:02 UTC, markjjo commented
@shelri PR merged. Sorry for the delay.