Update move-users-different-subscription.md
MicrosoftDocs/microsoft-365-docs pull request #4438
Opened 2021-03-15 18:50 UTC by msbemba

Made changes to Move users to a different sub as options have changed

2021-03-15 18:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-03-15 18:50 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4371

2021-03-16 08:49 UTC, JohanFreelancer9 commented on microsoft-365/commerce/subscriptions/move-users-different-subscription.md
> +4. In the **Manage product licenses** pane, Select the licenses that you would like to assign to the user and Unselect the current sibscription.
```suggestion
4. In the **Manage product licenses** pane, select the licenses that you would like to assign to the user and unselect the current subscription.
```

2021-03-16 08:59 UTC, JohanFreelancer9 commented on microsoft-365/commerce/subscriptions/move-users-different-subscription.md
> +4. In the **Manage product licenses** pane, Select the licenses that you would like to assign to the user and Unselect the current sibscription.
Shouldn't the current subscription be unselected before the new licenses are assigned?

2021-03-16 09:00 UTC, JohanFreelancer9 commented on microsoft-365/commerce/subscriptions/move-users-different-subscription.md
> +5. At the bottom , select **Save Changes** \> **Close**.
```suggestion
5. At the bottom, select **Save Changes** \> **Close**.
```

2021-03-16 09:01 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-16 14:46 UTC, yogkumgit commented
@msbemba

2021-03-17 03:28 UTC, JohanFreelancer9 approved these changes

2021-03-17 12:07 UTC, yogkumgit commented
@cmcatee-MSFT

2021-03-23 14:28 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks.

2021-03-23 19:35 UTC, cmcatee-MSFT requested changes
The steps that have been added are for 1 user only. Please rewrite so that it covers multiple users (the UI is slightly different in that case).
Also, it's "deselect" not "unselect". Please fix.

2021-03-24 13:35 UTC, yogkumgit commented
@msbemba Please implement the feedback. Thanks

2021-03-26 05:47 UTC, msbemba commented
@cmcatee-MSFT Thank you for the input. I have made changes to the PR to reflect the same.

2021-03-26 08:49 UTC, JohanFreelancer9 approved these changes

2021-03-26 18:49 UTC, merged