Update office-365-network-mac-perf-overview.md
MicrosoftDocs/microsoft-365-docs pull request #4442
Opened 2021-03-16 15:34 UTC by pandrew1

Added paragraph about network connectivity data sharing with Microsoft for linking from new UX setting.
FYI @kelleyvice-msft  @ivybarley

2021-03-23 14:29 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-24 01:58 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +By default the network assessments for your organization and the network insights are shared with Microsoft employees. This does not include any personal data from your staff but only the specific ne
```suggestion
By default, the network assessments for your organization and the network insights are shared with Microsoft employees. This does not include any personal data from your staff but only the specific network assessment metrics and network insights shown in the admin center for your office locations. It also does not include your office location names or street addresses so you would need to tell them the city and support ID of the office you want to discuss. If this is turned off, the Microsoft engineers that you are discussing your network connectivity with cannot view any of this information. Enabling this setting only shares future data starting the day after you enable it.
```

2021-03-24 02:01 UTC, JohanFreelancer9 requested changes
Copy review - minor suggestions.

2021-03-24 13:37 UTC, yogkumgit commented
@pandrew1

2021-03-24 21:13 UTC, pandrew1 commented
Ack, thank you @yogkumgit and @JohanFreelancer9

2021-03-25 07:13 UTC, JohanFreelancer9 commented
@pandrew1 - Could you please commit my suggestions? Thanks.

2021-03-25 18:44 UTC, pandrew1 commented
@JohanFreelancer9 Got it. Thanks for pointing that out

2021-03-26 22:40 UTC, merged