Update set-up.md
MicrosoftDocs/microsoft-365-docs pull request #4485
Opened 2021-03-20 07:13 UTC by neillnolann

- [Microsoft365.com/setup](https://soft365setup.com/)
- [Set up Microsoft 365 Business Basic](setup-business-basic.md)
- [Set up Microsoft Business Standard](setup-business-standard.md)
- [Set up Microsoft 365 Business Premium](../../business/set-up.md)
- [Set up Microsoft 365 Apps for business](setup-apps-for-business.md)

2021-03-23 14:33 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-24 03:38 UTC, JohanFreelancer9 commented on microsoft-365/business-video/set-up.md
>  13. After your setup is complete, return to the Microsoft admin center. In the admin center you can continue setting up features like Windows 10 policies, DLP, etc. on the  **Setup**  page.
```suggestion
13. After your setup is complete, return to the Microsoft 365 admin center. In the admin center, you can continue setting up features like Windows 10 policies, DLP, etc. on the  **Setup**  page.
```

2021-03-24 03:38 UTC, JohanFreelancer9 requested changes
Copy review - two additional minor edits, please.

2021-03-24 13:49 UTC, yogkumgit commented
@neillnolann Please implement the suggestions. Thanks

2021-03-25 19:52 UTC, pebaum commented
no way. this Microsoft365.com/setup link actually links to https://soft365setup.com/ a phishing site.

2021-03-25 19:52 UTC, closed without merging