Update dlp-microsoft-teams.md
MicrosoftDocs/microsoft-365-docs pull request #4493
Opened 2021-03-22 16:38 UTC by DanStevensonMSFT

added an important note regarding the risky loophole around activity notifications

2021-03-23 14:33 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-24 04:05 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-microsoft-teams.md
> +> DLP currently applies only to the actual messages in the chat or channel thread. Activity notifications -- which include a short message preview and appear based on a user's notification settings -
```suggestion
> DLP currently applies only to the actual messages in the chat or channel thread. Activity notifications—which include a short message preview and appear based on a user's notification settings—are _not_ included in Teams DLP at this time. Any sensitive information present in the part of the message that appears in the preview will remain visible in the notification even after the DLP policy has been applied and removed sensitive information from the message itself.
```

2021-03-24 04:08 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-24 14:14 UTC, yogkumgit commented
@DanStevensonMSFT Please update with the feedback. Thanks

2021-03-29 12:26 UTC, yogkumgit commented
@DanStevensonMSFT Gentle reminder

2021-03-29 18:54 UTC, merged