Update manage-quarantined-messages-and-files.md
MicrosoftDocs/microsoft-365-docs pull request #4496
Opened 2021-03-23 00:34 UTC by faoquong

@chrisda  we added this button recently. so I'm updating the documentation as well

2021-03-23 14:33 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-24 04:39 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md
> +-**Block Sender**: this blocks the sender from sending emails to recipient in the organization.
```suggestion
-**Block Sender**: This blocks the sender from sending emails to recipients in the organization.
```

2021-03-24 04:46 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-24 14:15 UTC, yogkumgit commented
@faoquong Please update with the feedback. Thanks.

2021-03-25 03:24 UTC, faoquong commented
@chrisda i have made a mistake. 

it should say this instead " -**Block Sender**: This blocks the sender from sending emails to the Admin recipient mailbox."

2021-03-25 08:55 UTC, JohanFreelancer9 commented
@faoquong - I have updated my suggestion in accordance with your comment. If you agree, please commit my suggestion. Thanks.

2021-03-25 14:58 UTC, merged