Update find-and-release-quarantined-messages-as-a-user.md
MicrosoftDocs/microsoft-365-docs pull request #4497
Opened 2021-03-23 00:36 UTC by faoquong

@chrisda

2021-03-23 14:34 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-24 04:48 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md
> +- **Block Sender**: this blocks the sender from sending emails to user.
```suggestion
- **Block Sender**: This blocks the sender from sending emails to the user.
```

2021-03-24 04:50 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-24 14:16 UTC, yogkumgit commented
@faoquong Please update with the feedback. Thanks.

2021-03-25 15:19 UTC, merged