Update migrate-to-microsoft-365-business.md
MicrosoftDocs/microsoft-365-docs pull request #450
Opened 2019-08-28 00:54 UTC by quietlikeninja

Just a minor change from using "he or she" to "they"

2019-08-28 07:59 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-08-28 14:45 UTC, JohanFreelancer9 commented on microsoft-365/business/migrate-to-microsoft-365-business.md
> +You have two ways to get Microsoft 365 Business. If you have a partner, they can purchase Microsoft 365 Business for you from [Microsoft Partner Center](get-microsoft-365-business.md). Your partner c
```suggestion
You have two ways to get Microsoft 365 Business. A partner can purchase Microsoft 365 Business for you from [Microsoft Partner Center](get-microsoft-365-business.md). Your partner can also help you transition to Microsoft 365 Business.
```

2019-08-28 14:47 UTC, JohanFreelancer9 requested changes
Copy Review

2019-08-28 15:12 UTC, mypil commented
@quietlikeninja - please merge the commit on the copy/edit review made by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-08-29 08:20 UTC, mypil commented
@Sirkkuw - PR has been copy edited and is ready for final review. 

Thank you.

2019-09-06 07:23 UTC, mypil commented
@Sirkkuw - PR has been copy edited and is ready for final review. Kindly assist to check and merge.

Thank you.

2019-09-06 17:48 UTC, merged