Update microsoft-365-vpn-implement-split-tunnel.md
MicrosoftDocs/microsoft-365-docs pull request #4500
Opened 2021-03-23 11:22 UTC by PaulCollinge

Updated FAQ to reflect support in browser

2021-03-23 14:34 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-24 05:11 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md
> +Yes it does, via supported browsers which are listed at https://docs.microsoft.com/en-us/microsoftteams/get-clients#web-client
```suggestion
Yes, it does, via supported browsers which are listed in the [Web client](https://docs.microsoft.com/microsoftteams/get-clients#web-client) topic.
```

2021-03-24 05:11 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-24 14:17 UTC, yogkumgit commented
@PaulCollinge Please update with the feedback. Thanks

2021-03-24 14:26 UTC, PaulCollinge reviewed
Change looks good.

2021-03-24 16:01 UTC, JohanFreelancer9 commented
Hi @PaulCollinge - could you please commit my changes?

2021-03-26 22:38 UTC, merged