Update microsoft-defender-endpoint-linux.md
MicrosoftDocs/microsoft-365-docs pull request #4506
Opened 2021-03-23 22:06 UTC by mariusgx

Fixed typos

2021-03-29 12:27 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-29 15:17 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md
>    >[!NOTE]
```suggestion
  > [!NOTE]
```

2021-03-29 15:18 UTC, JohanFreelancer9 requested changes
Copy review - minor additional edit, please.

2021-03-30 10:26 UTC, yogkumgit commented
@mariusgx Please implement the feedback, if you agree. Thanks

2021-03-31 02:02 UTC, JohanFreelancer9 approved these changes

2021-04-01 15:19 UTC, merged