Add 500 limitation for [Selected] option
MicrosoftDocs/microsoft-365-docs pull request #4524
Opened 2021-03-25 18:09 UTC by juntakata

Currently, there is a 500 group limit on the [Selected] option in M365 group expiration notification feature. I added a note to explain this limitation based on the conversation with Somesh Chandra.

2021-03-29 12:28 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-29 15:40 UTC, JohanFreelancer9 commented on microsoft-365/solutions/microsoft-365-groups-expiration-policy.md
> +> When you set the policy for selected groups, up to 500 groups can be added in the list. If you need to add more than 500 groups, you can set the policy for all of your groups. 500 limitation will n
```suggestion
> When you set the policy for selected groups, up to 500 groups can be added to the list. If you need to add more than 500 groups, you can set the policy for all of your groups. The 500 groups limitation will not be applied in this case.
```

2021-03-29 15:45 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-30 10:30 UTC, yogkumgit commented
@juntakata please implement the feedback. Thanks

2021-04-02 20:04 UTC, juntakata commented
Thanks @JohanFreelancer9 and @yogkumgit, I implemented the feedback.

2021-04-04 02:44 UTC, JohanFreelancer9 approved these changes

2021-04-05 13:04 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks.

2021-04-05 13:27 UTC, merged