Updated Script Sample
MicrosoftDocs/microsoft-365-docs pull request #4532
Opened 2021-03-26 05:43 UTC by tweekerz

Updated Script Sample

2021-03-29 12:29 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-30 00:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/unlimited-archiving.md
> +- Search for auto-expanded archiving is available in Outlook for the web (OWA). Similar to Online Archive, you can search for items that were moved to an additional storage area. When archive is sele
```suggestion
- Search for auto-expanded archiving is available in Outlook for the web (OWA). Similar to Online Archive, you can search for items that were moved to an additional storage area. When archive is selected as the search scope in OWA, all archives (including auto-expanded archives) and their corresponding subfolders will be searched.
```

2021-03-30 00:52 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-30 03:20 UTC, tweekerz commented
approved

Rob ***@***.***>
Sr. Support Escalation Engineer, Beta Engineer

From: JohanFreelancer9 ***@***.***>
Sent: Monday, March 29, 2021 7:52 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Rob Whaley (EXCHANGE) ***@***.***>; Author ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Updated Script Sample (#4532)


@JohanFreelancer9 requested changes on this pull request.

Copy review.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F4532%23pullrequestreview-623758969&data=04%7C01%7Crob.whaley%40microsoft.com%7C0f64fab05a4b467280a008d8f3161185%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637526623407511054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WkUBEpxzopMgk8f7%2Few5M1cIZSx0kNldqEDnsU9lLEk%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC5SXQFYIWJF75ZKQCMZWADTGEOEDANCNFSM4Z2XQRZA&data=04%7C01%7Crob.whaley%40microsoft.com%7C0f64fab05a4b467280a008d8f3161185%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637526623407521043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HTayqAA%2BSbbVIyIrjrD%2BdBGJIHl5hqdyICizq2Mi%2F4A%3D&reserved=0>.

2021-03-30 03:29 UTC, JohanFreelancer9 approved these changes

2021-03-30 10:43 UTC, yogkumgit commented
@JoeDavies-MSFT Please merge this PR. Thanks.

2021-03-30 23:01 UTC, merged