Update manage-creation-of-groups.md
MicrosoftDocs/microsoft-365-docs pull request #4533
Opened 2021-03-26 05:53 UTC by msbemba

GA can only create groups via EAC, O365 Admin center, Planner and SPO. Teams and Outlook/owa does not let them create it when the restrictions are in place.

2021-03-26 05:53 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2021-03-26 05:53 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4218

2021-03-26 08:53 UTC, JohanFreelancer9 approved these changes

2021-03-26 14:06 UTC, MikePlumleyMSFT commented
@ArunMSFT can you verify?

2021-03-26 14:49 UTC, JohanFreelancer9 commented on microsoft-365/solutions/manage-creation-of-groups.md
> +The steps in this article won't prevent members of certain roles from creating Groups. Office 365 Global admins can create Groups via  Microsoft 365 admin center, Planner,  Exchange, and SharePoint O
```suggestion
The steps in this article won't prevent members of certain roles from creating Groups. Office 365 Global admins can create Groups via the Microsoft 365 admin center, Planner, Exchange, and SharePoint Online. Other roles can create Groups via limited means, listed below.
```

2021-03-26 14:53 UTC, JohanFreelancer9 requested changes
Apologies @msbemba - please commit these further changes.

2021-03-28 12:30 UTC, yogkumgit commented
@msbemba

2021-03-29 16:00 UTC, JohanFreelancer9 approved these changes

2021-03-30 10:20 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks.

2021-03-30 12:52 UTC, MikePlumleyMSFT commented
@ArunMSFT can you verify?

2021-04-06 14:24 UTC, yogkumgit commented
@ArunMSFT Kindly verify and merge this PR. Thanks.

2021-04-09 08:04 UTC, ArunMSFT commented
Mike - Please merge, thanks.

From: Yogesh Kumar ***@***.***>
Sent: Tuesday, April 6, 2021 7:55 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Arunkumaran Varadharajan ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update manage-creation-of-groups.md (#4533)


@ArunMSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FArunMSFT&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7Cc9b94382240d45c28dea08d8f907c677%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637533159088353153%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1SFtkPF0bS7rosHD0a74eYM9jnrkcYPJO%2F4MNPKKz7g%3D&reserved=0> Kindly verify and merge this PR. Thanks.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F4533%23issuecomment-814163793&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7Cc9b94382240d45c28dea08d8f907c677%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637533159088353153%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SQXdJBu1pPYfOv94XdLlmLMEeKNn%2BAy931sxdpuPCjA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHZV2TEBR2UD4RGHVNK63PDTHMKUDANCNFSM4Z2X3ORA&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7Cc9b94382240d45c28dea08d8f907c677%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637533159088363147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WTIVKfgWpFF8E6fB1Iutl3osOsfg4HFyuuIw%2FYDnHyM%3D&reserved=0>.

2021-04-09 14:44 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-04-09 14:49 UTC, merged