Included Application Guard
MicrosoftDocs/microsoft-365-docs pull request #4547
Opened 2021-03-27 01:52 UTC by ekarafezov

Application Guard is an upgraded experience (using SafeDocs as well) from Protected View when tenant has enabled the feature and set the policy.

2021-03-29 12:31 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-03-30 04:26 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/safe-docs.md
> +Safe Documents is a feature in Microsoft 365 E5 or Microsoft 365 E5 Security that uses [Microsoft Defender for Endpoint](/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-
```suggestion
Safe Documents is a feature in Microsoft 365 E5 or Microsoft 365 E5 Security that uses [Microsoft Defender for Endpoint](/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection) to scan documents and files that are opened in [Protected View](https://support.microsoft.com/office/d6f09ac7-e6b9-4495-8e43-2bbcdbcb6653) or [Application Guard for Office](https://support.microsoft.com/topic/application-guard-for-office-9e0fb9c2-ffad-43bf-8ba3-78f785fdba46).
```

2021-03-30 04:29 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/safe-docs.md
> +### Onboard to the Microsoft Defender for Endpoint Service to enable auditing capabilities
```suggestion
### Onboard to the Microsoft Defender for Endpoint service to enable auditing capabilities
```

2021-03-30 04:30 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/safe-docs.md
> +To deploy Microsoft Defender for Endpoint you must go through the various phases of deployment. After onboarding you can configure auditing capabilities in the Security & Compliance Center.
```suggestion
To deploy Microsoft Defender for Endpoint you must go through the various phases of deployment. After onboarding, you can configure auditing capabilities in the Security & Compliance Center. 
```

2021-03-30 04:31 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/safe-docs.md
> +To learn more see [Onboard to the Microsoft Defender for Endpoint service] (/security/defender-endpoint/onboarding). If you need additional help please refer to the [Troubleshoot Microsoft Defender f
```suggestion
To learn more, see [Onboard to the Microsoft Defender for Endpoint service] (/security/defender-endpoint/onboarding). If you need additional help, please refer to [Troubleshoot Microsoft Defender for Endpoint onboarding issues] (/security/defender-endpoint/troubleshoot-onboarding).
```

2021-03-30 04:33 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-30 11:06 UTC, yogkumgit commented
@ekarafezov Please implement the feedback. Thanks

2021-03-30 17:01 UTC, merged