Update view-reports-for-mdo.md
MicrosoftDocs/microsoft-365-docs pull request #4555
Opened 2021-03-29 17:16 UTC by msbemba

Added information about URL click protection action

2021-03-29 17:17 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-03-29 17:17 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4501

2021-03-30 05:40 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-reports-for-mdo.md
> +  - **Blocked and clicked through** (the user choose to continue navigating to the URL)
```suggestion
  - **Blocked and clicked through** (the user has chosen to continue navigating to the URL)
```

2021-03-30 05:41 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/view-reports-for-mdo.md
> +  - **Clicked through during scan** (the user click on the link before the scan is complete)
```suggestion
  - **Clicked through during scan** (the user has clicked on the link before the scan was complete)
```

2021-03-30 05:42 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-30 10:32 UTC, yogkumgit commented
@msbemba

2021-03-30 15:41 UTC, JohanFreelancer9 approved these changes

2021-03-31 12:00 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks.

2021-04-06 16:12 UTC, merged