Update compliance-manager-assessments.md
MicrosoftDocs/microsoft-365-docs pull request #4568
Opened 2021-03-30 17:30 UTC by msbemba

Added Compliance manager assessors to the note as they have access to Build and manage assessment.

2021-03-30 17:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4474

2021-03-30 17:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-03-31 00:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/compliance-manager-assessments.md
> +> Only users who hold a Global Administrator or Compliance Manager Administration role can manage template creation and modification. The Compliance Manager Assessors role can create and modify asses
```suggestion
> Only users who hold a Global Administrator or Compliance Manager Administration role can manage template creation and modification. The Compliance Manager Assessors role can create and modify assessments using templates created or modified by the Global Administrator or Compliance Manager Administration. Learn more about [roles and permissions](compliance-manager-setup.md#set-user-permissions-and-assign-roles).
```

2021-03-31 01:06 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-03-31 12:20 UTC, yogkumgit commented
@msbemba

2021-03-31 16:51 UTC, JohanFreelancer9 approved these changes

2021-03-31 23:17 UTC, chvukosw commented
The suggested edit isn't fully accurate per engineering. Will update this article in a separate PR to indicate that CM Assessors can also create and modify assessments.

2021-03-31 23:17 UTC, closed without merging