Update data-storage-privacy.md
MicrosoftDocs/microsoft-365-docs pull request #4595
Opened 2021-04-01 17:20 UTC by msbemba

Added details about advanced hunting data

2021-04-01 17:20 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-04-01 17:20 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4540

2021-04-02 05:19 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/data-storage-privacy.md
> +**Advanced Hunting data**<br.
```suggestion
**Advanced Hunting data**<br>
```

2021-04-02 05:21 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-04 04:44 UTC, JohanFreelancer9 approved these changes

2021-04-06 14:50 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-04-07 16:47 UTC, merged