Update enable-usage-analytics.md
MicrosoftDocs/microsoft-365-docs pull request #4596
Opened 2021-04-01 18:34 UTC by msbemba

The UI changed for Enabling template app

2021-04-01 18:34 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-04-01 18:34 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4561

2021-04-02 05:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/enable-usage-analytics.md
> +1. In the admin center, go to the **Settings** \> **Org settings** \> **Service** Tab.
```suggestion
1. In the admin center, go to the **Settings** \> **Org settings** \> **Services** Tab. 
```

2021-04-02 05:17 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/enable-usage-analytics.md
> +2. On the **Services** tab, Select  **Reports** .
```suggestion
2. On the **Services** tab, Select  **Reports**.
```

2021-04-02 05:18 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-04 04:38 UTC, JohanFreelancer9 approved these changes

2021-04-06 14:55 UTC, yogkumgit commented
@scotvidican Please help us in merging this PR. Thanks.

2021-04-12 11:27 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-04-20 11:20 UTC, yogkumgit commented
Gentle reminder, @kwekuako Please merge this PR. Thanks.

2021-04-20 14:53 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/enable-usage-analytics.md
> +1. In the admin center, go to the **Settings** \> **Org settings** \> **Services** Tab.
```suggestion
1. In the admin center, go to the **Settings** \> **Org settings** \> **Services** tab. 
```

2021-04-20 14:54 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/enable-usage-analytics.md
> +2. On the **Services** tab, Select  **Reports**.
```suggestion
2. On the **Services** tab, select  **Reports**.
```

2021-04-20 14:54 UTC, JohanFreelancer9 requested changes
Apologies @msbemba - two more, please.

2021-04-21 15:37 UTC, JohanFreelancer9 approved these changes

2021-04-21 23:48 UTC, merged