Update mmd-app-requirements.md
MicrosoftDocs/microsoft-365-docs pull request #4649
Opened 2021-04-08 16:59 UTC by dannoakes

2021-04-16 14:02 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-04-16 15:20 UTC, jaimeodell commented
I believe you've assigned this to the incorrect person. I am not familiar with this project.

Thanks,
Jaime

From: Yogesh Kumar ***@***.***>
Sent: Friday, April 16, 2021 8:03 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Jaime Odell ***@***.***>; Assign ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update mmd-app-requirements.md (#4649)


@JohanFreelancer9<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJohanFreelancer9&data=04%7C01%7Cjaime%40waypoint.ws%7C690b39aeb32a41a5976f08d900e05997%7C4f6058ed26734ff5b1e64825cdf4183f%7C0%7C0%7C637541785876224142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c%2F0vCOikANGXPMtkH%2BfMSgZekh899wIXRQ54XEg1oK8%3D&reserved=0> - kindly do the copy editor review for this PR. Thanks

-
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F4649%23issuecomment-821199841&data=04%7C01%7Cjaime%40waypoint.ws%7C690b39aeb32a41a5976f08d900e05997%7C4f6058ed26734ff5b1e64825cdf4183f%7C0%7C0%7C637541785876224142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=htYrhcaatgr2H8rZVd5tFaCUslV4Xu%2Ffw8cxFyNFHzY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQYJOQYFAHXDY46YY2BWPULTJA7RLANCNFSM42TJB5SQ&data=04%7C01%7Cjaime%40waypoint.ws%7C690b39aeb32a41a5976f08d900e05997%7C4f6058ed26734ff5b1e64825cdf4183f%7C0%7C0%7C637541785876234126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pSzegScyo4RGaZeEEGw0Jmu8vOCFpQ9fABq0S3iwCKk%3D&reserved=0>.

2021-04-17 04:27 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +|Application management     | Applications must be deployed using Microsoft Intune and Company Portal. See Secuirty and Protection applications for for guidance and conditions      |
```suggestion
|Application management     | Applications must be deployed using Microsoft Intune and Company Portal. See Security and Protection applications for guidance and conditions      |
```

2021-04-17 04:29 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +Microsoft Managed Desktop might monitor other software running on managed devices. If it negatively impacts device management, device security, performance, or reliability you may be required to take
```suggestion
Microsoft Managed Desktop might monitor other software running on managed devices. If it negatively impacts device management, device security, performance, or reliability you might be required to take action.
```

2021-04-17 04:34 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +# Non-Microsoft Security and Protection Applications
```suggestion
# Non-Microsoft security and protection applications
```

2021-04-17 04:42 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +Microsoft Managed Desktop does not test with or ensure continued functioning as part of the service for non-Microsoft security and protection applications. This includes but is not limited to applica
```suggestion
Microsoft Managed Desktop does not test with or ensure continued functioning as part of the service for non-Microsoft security and protection applications. This includes but is not limited to applications commonly referred to as agents, drivers, kernel drivers, or non-Microsoft Windows services running as a local system. The Microsoft Managed Desktop service does not take dependencies on any external applications or services deployed by IT or Security admins as part of service delivery. See [Microsoft Managed Desktop service description](https://docs.microsoft.com/microsoft-365/managed-desktop/service-description/?view=o365-worldwide) for more information.
```

2021-04-17 04:43 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +These types of apps may provide unrestricted privilege to the operating system and expose Windows to additional threats. See [Technology Used]technologies.md) to identify the capabilities included as
```suggestion
These types of apps may provide unrestricted privilege to the operating system and expose Windows to additional threats. See [Technology Used]technologies.md) to identify the capabilities included as part of Microsoft Managed Desktop and the recommended Microsoft 365 native capabilities an IT or Security admin should implement.
```

2021-04-17 04:46 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +These types of apps may provide unrestricted privilege to the operating system and expose Windows to additional threats. See [Technology Used]technologies.md) to identify the capabilities included as
Please also confirm that this link is correct.

2021-04-17 04:49 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +The requirements listed below must be met if it is not possible for IT or Security Admins to implement or integrate with Microsoft Managed Desktop service options and recommended Microsoft 365 native
```suggestion
The following requirements must be met if it is not possible for IT or Security admins to implement or integrate with Microsoft Managed Desktop service options and recommended Microsoft 365 native capabilities. Microsoft Managed Desktop might monitor other software running on managed devices. If it negatively impacts device management, device security, performance, or reliability, you might be required to take action.
```

2021-04-17 04:56 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +•	Services implemented by Microsoft Managed Desktop must not be impeded or blocked
```suggestion
 - Services implemented by Microsoft Managed Desktop must not be impeded or blocked.
```

2021-04-17 04:57 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +•	Settings managed by Microsoft Managed Desktop must not be modified or impeded
```suggestion
 - Settings managed by Microsoft Managed Desktop must not be modified or impeded.
 
```

2021-04-17 05:03 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +•	Microsoft Defender Antivirus state must be Active and therefore must not be modified - see the compatibility matrix to understand if the application being installed will change this state https://d
```suggestion
 - Microsoft Defender Antivirus state must be _Active_ and therefore must not be modified; see [Microsoft Defender Antivirus compatibility](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility) to understand if the application being installed will change this state.
```

2021-04-17 05:06 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +•	Only Credential Providers included with Windows 10 may be used – see Credential Providers included with Windows 10  https://docs.microsoft.com/en-us/windows/win32/secauthn/credential-providers-in-w
```suggestion
 - Only Credential Providers included with Windows 10 may be used; see [Credential Providers in Windows 10](https://docs.microsoft.com/windows/win32/secauthn/credential-providers-in-windows).
 
```

2021-04-17 05:09 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +•	System drive encryption included in the settings documented as managed by Microsoft, must not be modified or impeded
```suggestion
 - System drive encryption included in the settings documented as managed by Microsoft must not be modified or impeded.
 
```

2021-04-17 05:13 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +•	The required network endpoints must not be impeded or blocked – see https://docs.microsoft.com/microsoft-365/managed-desktop/get-ready/network
```suggestion
 - The required network endpoints must not be impeded or blocked; see [Network configuration for Microsoft Managed Desktop](https://docs.microsoft.com/microsoft-365/managed-desktop/get-ready/network) for details.
 
```

2021-04-17 05:18 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/mmd-app-requirements.md
> +•	IT and Security Admins must use the Security operations process in response to threats on endpoints, https://docs.microsoft.com/microsoft-365/managed-desktop/service-description/security-operations
```suggestion
 - IT and Security admins must use the security operations process in response to threats on endpoints; see
[Security operations in Microsoft Managed Desktop](https://docs.microsoft.com/microsoft-365/managed-desktop/service-description/security-operations) for details.
```

2021-04-17 05:19 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-19 13:53 UTC, yogkumgit commented
@jaimeodell please review the feedback and update the PR.  Thanks.

2021-04-19 14:28 UTC, yogkumgit commented
@dannoakes Please update the PR with suggested changes. Thanks

2021-08-20 14:25 UTC, tiburd commented
@dannoakes 

Can you please review this PR and determine whether the proposed changes are still technically accurate?

Please **@ mention** me in your reply. If the changes are still technically accurate, I will propose them in the private repo (and close this PR) so that I can confirm the changes on staging before they go live.

Thank you!

2022-01-20 12:37 UTC, dannoakes commented
This can be closed.

2022-01-20 12:37 UTC, closed without merging