Update microsoft-365-business-faqs.md
MicrosoftDocs/microsoft-365-docs pull request #465
Opened 2019-09-18 10:52 UTC by msbemba

added conditional access feature

2019-09-18 18:44 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-09-19 07:40 UTC, JohanFreelancer9 commented on microsoft-365/business/support/microsoft-365-business-faqs.md
> +- Microsoft 365 Business customers can enable Conditional Access via the Azure Directory settings in the Azure portal. For more information on how to configure Conditional Access policies, please see
```suggestion
- Microsoft 365 Business customers can enable Conditional Access via the Azure Directory settings in the Azure portal. For more information on how to configure Conditional Access policies, please see the article [What is Conditional access](https://docs.microsoft.com/azure/active-directory/conditional-access/overview).
```

2019-09-19 07:41 UTC, JohanFreelancer9 requested changes
Copy Review - please remove locale from link.

2019-09-19 16:26 UTC, mypil commented
@Sirkkuw - PR has been copy edited and is ready for final review. This is based on issue #461.

Thank you.

2019-09-19 22:22 UTC, Sirkkuw commented
@mypil go ahead and merge.

2019-09-20 01:29 UTC, mypil commented
@Sirkkuw - Please assist to merge this. Thank you.

2019-09-24 16:38 UTC, merged