change in data center location for ASC tenants
MicrosoftDocs/microsoft-365-docs pull request #4740
Opened 2021-04-20 09:34 UTC by malidgi

in the past (until a few months ago), is MDE was enabled for the first time via the integration with Azure defender, the data location for MDE data was hardcoded EU. 
we changed it a few months ago, and today we use the same methodology to choose the data center location as all other tenants. 
contact me for more details

2021-04-20 11:26 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-04-20 13:06 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/m365d-enable.md
> +> in the past, Microsoft Defender for Endpoint automatically used to be provisioned European Union (EU) data centers when turned on through Azure Defender. Microsoft 365 Defender will automatically p
```suggestion
> In the past, Microsoft Defender for Endpoint automatically provisioned in European Union (EU) data centers when turned on through Azure Defender. Microsoft 365 Defender will automatically provision in the same EU data center for customers who have provisioned Defender for Endpoint in this manner.
```

2021-04-20 13:07 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-21 10:55 UTC, yogkumgit commented
@malidgi Please implement the suggestions. Thanks

2021-04-21 12:09 UTC, malidgi commented
@yogkumgit can you be more specific about the required action on my side?

2021-04-21 12:24 UTC, yogkumgit commented
@malidgi Johan performed copy edit and have suggested some changes. :) Thanks

2021-04-21 12:42 UTC, malidgi commented
@yogkumgit the changes look good!

2021-04-21 16:16 UTC, JohanFreelancer9 commented
@malidgi - please click on the commit button to commit my changes. Thanks so much.

2021-04-26 15:17 UTC, yogkumgit commented
@JohanFreelancer9

2021-04-26 15:59 UTC, JohanFreelancer9 approved these changes

2021-04-27 13:15 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks.

2021-06-08 22:56 UTC, merged