Update evaluate-attack-surface-reduction.md
MicrosoftDocs/microsoft-365-docs pull request #4759
Opened 2021-04-21 23:52 UTC by kurtsarens

adding Warning for Server 2016 as ASR rules can have unexpected results on this unsupported platform

2021-04-22 12:23 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-04-22 14:57 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/evaluate-attack-surface-reduction.md
> +> [!Warning]
```suggestion
> [!WARNING]
```

2021-04-22 15:05 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/evaluate-attack-surface-reduction.md
> +> Enabling Attack Service Reduction rules on Windows Server 2016 may lead to unexpected results and impact server performance. It is not recommended to enable or deploy Attack Surface Reduction rules
```suggestion
> Enabling attack service reduction rules on Windows Server 2016 may lead to unexpected results and impact server performance. We do not recommend enabling or deploying attack surface reduction rules to unsupported platforms.
```

2021-04-22 15:06 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-23 01:34 UTC, JohanFreelancer9 requested changes
@kurtsarens - please also change the word "Warning" to "WARNING" ( all caps) as indicated. Thanks.

2021-06-08 22:58 UTC, merged