Update use-dkim-to-validate-outbound-email.md
MicrosoftDocs/microsoft-365-docs pull request #4769
Opened 2021-04-23 04:47 UTC by puneethmeister

The above wording of default domain is causing confusion for customers, we need to replace it with MOERA or initial domain i.e. onmicrosoft domain
https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/2074507?src=WorkItemMention&src-action=artifact_link

2021-04-26 15:17 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-04-27 03:49 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md
> +If you do not enable DKIM, Microsoft 365 automatically creates a 1024-bit DKIM public key for your MOERA/Initial domain and the associated private key which we store internally in our datacenter. By
```suggestion
If you do not enable DKIM, Microsoft 365 automatically creates a 1024-bit DKIM public key for your Microsoft Online Email Routing Address (MOERA)/initial domain and the associated private key which we store internally in our datacenter. By default, Microsoft 365 uses a default signing configuration for domains that do not have a policy in place. This means that if you do not set up DKIM yourself, Microsoft 365 will use its default policy and keys it creates to enable DKIM for your domain.
```

2021-04-27 03:54 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md
> +Also, if you disable DKIM signing on custom domain after enabling it, after a period of time, Microsoft 365 will automatically apply the MOERA/Initial domain policy for your custom domain.
```suggestion
Also, if you disable DKIM signing on your custom domain after enabling it, after a period of time, Microsoft 365 will automatically apply the MOERA/initial domain policy for your custom domain.
```

2021-04-27 03:55 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-27 13:26 UTC, yogkumgit commented
@puneethmeister Please review and implement the suggested changes. Thanks

2021-06-25 08:53 UTC, puneethmeister commented
@yogkumgit committed the suggested changes

2021-06-25 11:00 UTC, JohanFreelancer9 approved these changes

2021-06-28 11:54 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2021-07-14 07:27 UTC, puneethmeister commented
@MSFTTracyP Gentle Reminder

2021-07-20 17:47 UTC, merged

2021-07-20 17:49 UTC, MSFTTracyP reviewed
Thanks

2021-07-20 19:33 UTC, MSFTTracyP reviewed
Thanks