Added info about using Test wizard for EDM
MicrosoftDocs/microsoft-365-docs pull request #4771
Opened 2021-04-23 07:05 UTC by Esaggese

Added reference to the EDM wizard article steps on testing your EDM type.

2021-04-26 15:18 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-04-27 04:45 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md
> +After you have imported your rule package with your EDM Sensitive info type and have imported your sensitive data table, you can test your newly created type by using the Test function in the EDM wiz
```suggestion
After you have imported your rule package with your EDM sensitive info type and have imported your sensitive data table, you can test your newly created type by using the **Test** function in the EDM wizard in the compliance center. See [Use the Exact Data Match Schema and Sensitive Information Type Wizard](sit-edm-wizard.md) for instructions on using this functionality.
```

2021-04-27 04:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md
> +After you have imported your rule package with your EDM Sensitive info type and have imported your sensitive data table, you can test your newly created type by using the Test function in the EDM wiz
```suggestion
After you have imported your rule package with your EDM sensitive info type and have imported your sensitive data table, you can test your newly created type by using the **Test** function in the EDM wizard in the compliance center. See [Use the Exact Data Match Schema and Sensitive Information Type Wizard](sit-edm-wizard.md) for instructions on using this functionality.
```

2021-04-27 04:46 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-27 13:30 UTC, yogkumgit commented
@Esaggese Please review and implement the suggested changes. Thanks

2021-04-28 14:31 UTC, yogkumgit commented
@JohanFreelancer9

2021-04-29 06:16 UTC, JohanFreelancer9 approved these changes

2021-04-29 16:08 UTC, merged