Update archive-android-archiver-data.md
MicrosoftDocs/microsoft-365-docs pull request #4773
Opened 2021-04-23 09:51 UTC by Durga-SC

remove the 24 hours since data flow in real time @markjjo

2021-04-26 15:18 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-04-27 06:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/archive-android-archiver-data.md
> +2. The Android Archiver connector that you create in the Microsoft 365 compliance center connects to the TeleMessage site every day and transfers the Android data from the previous 24 hours to a secu
```suggestion
2. The Android Archiver connector that you create in the Microsoft 365 compliance center connects to the TeleMessage site every day and transfers the Android data from the previous 24 hours to a secure Azure storage location in the Microsoft cloud. The connector also converts the Android data to an email message format.
```

2021-04-27 06:58 UTC, JohanFreelancer9 commented on microsoft-365/compliance/archive-android-archiver-data.md
> +3. The connector imports the mobile communication items to the mailbox of a specific user. A new folder named Android Archiver is created in the specific user's mailbox and the items are imported to
```suggestion
3. The connector imports the mobile communication items to the mailbox of a specific user. A new folder named Android Archiver is created in the specific user's mailbox and the items are imported to it. The connector does mapping by using the value of the *User’s Email address* property. Every email message contains this property, which is populated with the email address of every participant of the email message. In addition to automatic user mapping using the value of the *User’s Email address* property, you can also define a custom mapping by uploading a CSV mapping file. This mapping file should contain the user’s mobile number and the corresponding Microsoft 365 mailbox address for each user. If you enable automatic user mapping and provide a custom mapping, for every email item the connector will first look at the custom mapping file. If it doesn't find a valid Microsoft 365 user that corresponds to a user's mobile number, the connector will use the user‘s email address property of the email item. If the connector doesn't find a valid Microsoft 365 user in either the custom mapping file or the *user’s email address* property of the email item, the item won't be imported.
```

2021-04-27 07:00 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-27 13:36 UTC, yogkumgit commented
@Durga-SC Please review and implement the suggested changes. Thanks.

2021-04-28 17:04 UTC, markjjo commented
This PR has been replaced by newer PR

2021-04-28 17:04 UTC, closed without merging