Update manage-addins-in-the-admin-center.md
MicrosoftDocs/microsoft-365-docs pull request #4813
Opened 2021-04-27 14:57 UTC by v-padum

Although the link for Services & Add-ins is correct and still points to the right place, the text no longer represents how the UI element is titled. Rather, it's now part of Settings > Org settings and Settings > Integrated apps based on which specific setting we're talking about.

Because of the new admin center, the experience to remove add-ins is also extremely convoluted. Instructions updated in this PR.

The note can also be removed because there is no longer an alternate UI in the works (as far as I understand it) and the production version has been rolled out everywhere in WW.

2021-04-28 14:47 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-04-29 06:46 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-addins-in-the-admin-center.md
> +2. Select the deployed add-in and click the **Configuration** tab
```suggestion
2. Select the deployed add-in and select the **Configuration** tab.
```

2021-04-29 06:46 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-addins-in-the-admin-center.md
> +3. In the **Configuration** pane go to **Advanced Settings** > **Add-ins**
```suggestion
3. In the **Configuration** pane, go to **Advanced Settings** > **Add-ins**.
```

2021-04-29 06:47 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-addins-in-the-admin-center.md
> +4. Select the add-in from the list again
```suggestion
4. Select the add-in from the list again.
```

2021-04-29 06:47 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-addins-in-the-admin-center.md
> +5. Click on **Remove Add-In**. Remove the Add-in button on the bottom right corner.
```suggestion
5. Choose **Remove Add-In**. Remove the Add-in button on the bottom right corner.
```

2021-04-29 06:53 UTC, JohanFreelancer9 requested changes
Copy review - @v-padum, could you please commit my suggested changes if you agree with them? Many thanks.

2021-04-29 14:53 UTC, v-padum commented
Done, perfect and thanks!
________________________________
From: JohanFreelancer9 ***@***.***>
Sent: Thursday, April 29, 2021 2:54 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Patricia Dumas Bonnier (Sherweb Inc) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update manage-addins-in-the-admin-center.md (#4813)


@JohanFreelancer9 requested changes on this pull request.

Copy review - @v-padum<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fv-padum&data=04%7C01%7Cv-padum%40microsoft.com%7Ca65dee02ccbe4b3d51fe08d90adb92c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637552760445993239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w8jNpan%2Fq9%2FDokvZRA7MTUedGOCNLfE6Ls%2Bj6xQzOWk%3D&reserved=0>, could you please commit my suggested changes if you agree with them? Many thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F4813%23pullrequestreview-647863534&data=04%7C01%7Cv-padum%40microsoft.com%7Ca65dee02ccbe4b3d51fe08d90adb92c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637552760446003194%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0L46hqp%2FJ7t8VkXfeiFQye6cBBXX2buyXOu6s%2Bv50dE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPLQ4OJXXHWU6VWD4DAFMGLTLD7AVANCNFSM43VFJZEA&data=04%7C01%7Cv-padum%40microsoft.com%7Ca65dee02ccbe4b3d51fe08d90adb92c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637552760446003194%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W4l6BpHFQ%2BJU6HlOb0vLHkqqcT85CyjSR8G6pLBdJxo%3D&reserved=0>.

2021-04-30 13:55 UTC, yogkumgit commented
@JohanFreelancer9

2021-04-30 15:39 UTC, JohanFreelancer9 approved these changes

2021-05-03 14:25 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2021-10-11 08:09 UTC, yogkumgit commented
@tiburd Please resolve this conflict. Thanks

2021-10-12 11:21 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2021-10-21 17:36 UTC, merged