Update multi-geo-add-group-with-pdl.md
MicrosoftDocs/microsoft-365-docs pull request #4817
Opened 2021-04-27 19:15 UTC by msbemba

Added Abbreviation for PDL to avoid confusion.

2021-04-27 19:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-04-27 19:15 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4736

2021-04-28 04:06 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/multi-geo-add-group-with-pdl.md
> +title: "Create a Microsoft 365 Group with a specific Preferred Data Location (PDL)"
```suggestion
title: "Create a Microsoft 365 Group with a specific preferred data location (PDL)"
```

2021-04-28 04:08 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/multi-geo-add-group-with-pdl.md
> +When users in a multi-geo environment create a Microsoft 365 Group, the group Preferred Data Location (PDL) is automatically set to that of the user. Global, SharePoint, and Exchange Administrators c
```suggestion
When users in a multi-geo environment create a Microsoft 365 Group, the group preferred data location (PDL) is automatically set to that of the user. Global, SharePoint, and Exchange Administrators can create groups in any region they select. 
```

2021-04-28 04:09 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/multi-geo-add-group-with-pdl.md
> +# Create a Microsoft 365 Group with a specific Preferred Data Location (PDL)
```suggestion
# Create a Microsoft 365 Group with a specific preferred data location (PDL)
```

2021-04-28 04:10 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-28 14:01 UTC, yogkumgit commented
@msbemba

2021-04-29 03:30 UTC, JohanFreelancer9 approved these changes

2021-04-29 13:52 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-04-29 14:00 UTC, merged