Update customer-key-overview.md
MicrosoftDocs/microsoft-365-docs pull request #4819
Opened 2021-04-27 19:31 UTC by msbemba

Added Teams to the list as Customer Key support for Microsoft Teams now in Public Preview! ( https://techcommunity.microsoft.com/t5/microsoft-teams-blog/customer-key-support-for-microsoft-teams-now-in-public-preview/ba-p/1999893) 

Reference Doc:- https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-tenant-level

2021-04-27 19:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-04-27 19:31 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4753

2021-04-28 04:22 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-overview.md
> +**Exchange Online, Teams and Skype for Business** You can create up to 50 DEPs per tenant. You associate DEPs to your Customer Keys in Azure Key Vault and then assign DEPs to individual mailboxes. Wh
```suggestion
**Exchange Online, Teams, and Skype for Business** You can create up to 50 DEPs per tenant. You associate DEPs to your Customer Keys in Azure Key Vault and then assign DEPs to individual mailboxes. When you assign a DEP to a mailbox:
```

2021-04-28 04:23 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-28 06:27 UTC, JohanFreelancer9 approved these changes

2021-05-14 14:01 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks.

2021-05-21 11:07 UTC, yogkumgit commented
@KCCross Gentle reminder

2021-08-26 16:04 UTC, tiburd commented
This change has been incorporated into the updated article via a different PR. Closing this PR.

2021-08-26 16:04 UTC, closed without merging