Updates to use Ansible terminology
MicrosoftDocs/microsoft-365-docs pull request #4833
Opened 2021-04-28 11:45 UTC by governmentSponsored

Replaces primary computer with control node, client with managed node, and host with managed node. All per https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html.

2021-04-28 14:35 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-04-29 06:42 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/linux-install-with-ansible.md
> +- SSH must be configured for an administrator account between the control node and all managed nodes (machines that will have Defender installed on them), and it is recommended be configured with pub
```suggestion
- SSH must be configured for an administrator account between the control node and all managed nodes (devices that will have Defender for Endpoint installed on them), and it is recommended to be configured with public key authentication.
```

2021-04-29 06:43 UTC, JohanFreelancer9 requested changes
Copy review - @governmentSponsored, could you please commit my suggested changes if you agree? Many thanks.

2021-04-29 16:27 UTC, governmentSponsored commented
@JohanFreelancer9 that looks great to me. Accepted those changes.

2021-04-30 03:52 UTC, JohanFreelancer9 approved these changes

2021-04-30 14:19 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-04-30 17:06 UTC, merged