Update respond-machine-alerts.md
MicrosoftDocs/microsoft-365-docs pull request #4836
Opened 2021-04-28 20:25 UTC by msbemba

Added another note(Disclaimer) about devices that are behind a full VPN tunnel.

2021-04-28 20:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-04-28 20:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4797

2021-04-29 04:18 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/respond-machine-alerts.md
> +>- When isolating a device, only certain processes and destinations are allowed. Therefore, devices that are behind a full VPN tunnel won't be able to reach the Microsoft Defender for Endpoint Cloud
```suggestion
>- When isolating a device, only certain processes and destinations are allowed. Therefore, devices that are behind a full VPN tunnel won't be able to reach the Microsoft Defender for Endpoint cloud service after the device is isolated. We recommend using a split-tunneling VPN for Microsoft Defender for Endpoint and Microsoft Defender Antivirus cloud-based protection-related traffic.
```

2021-04-29 04:18 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-29 07:51 UTC, JohanFreelancer9 approved these changes

2021-04-29 13:44 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks.

2021-05-14 11:34 UTC, yogkumgit commented
@mjcaparas Gentle reminder, please merge this PR. Thanks

2021-05-17 19:16 UTC, merged