More clarification
MicrosoftDocs/microsoft-365-docs pull request #4866
Opened 2021-05-02 08:29 UTC by joinimran

There was confusion if the license is not assigned to the user. Updated the information.

Problem: #9161

2021-05-02 08:30 UTC, joinimran commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2021-05-02 10:00 UTC, illfated commented on microsoft-365/security/defender-endpoint/mac-support-license.md
> +You deployed and/or installed the Microsoft Defender for Endpoint for macOS package ("Download installation package") but you might have run the configuration script ("Download onboarding package").
Very well. Let us go for the same line as in your previous PR - https://github.com/MicrosoftDocs/windows-itpro-docs/pull/9251:
```suggestion
You deployed and/or installed the Microsoft Defender for Endpoint for macOS package ("Download installation package"), but you might have run the configuration script ("Download onboarding package"), or you have not assigned a license to the user.
```

2021-05-03 04:27 UTC, JohanFreelancer9 requested changes
Copy review - only @illfated's suggestions.

2021-05-04 18:23 UTC, nam31 commented
@Dansimp PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-04 19:35 UTC, illfated commented
@joinimran : Thank you for recreating your PR in the new repository. This PR will be ready to merge as soon as the suggested change has been committed.

2021-05-05 16:44 UTC, merged