Update create-retention-policies.md
MicrosoftDocs/microsoft-365-docs pull request #4887
Opened 2021-05-03 18:49 UTC by msbemba

Added more information about retention limitations for private channels

2021-05-03 18:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-03 18:50 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4851

2021-05-04 03:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-retention-policies.md
> +   For **Teams channel messages**, message from standard channels are included, but not [private channels](/microsoftteams/private-channels). Teams messages in private channels are currently not supp
```suggestion
   For **Teams channel messages**, message from standard channels are included, but not [private channels](/microsoftteams/private-channels). Teams messages in private channels are currently not supported for retention policies. Code snippets, recorded voice memos from the Teams mobile client, thumbnails, announcement images, and reactions from others in the form of emoticons are not retained when you use retention policies for Teams. For more information, See [Teams Retention policies](retention-policies-teams.md).
```

2021-05-04 03:15 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-04 11:14 UTC, yogkumgit commented
@msbemba

2021-05-04 13:07 UTC, JohanFreelancer9 approved these changes

2021-05-04 19:25 UTC, cabailey commented
#hold-off

2021-05-12 00:24 UTC, cabailey commented
Closing.  We already have the statement that private channels aren't supported (in our experience, customers are aware of this limitation) and a link to where we publish the authoritative source for what's included and excluded for Teams retention messages.  We want to avoid duplicating technical details like these so that when things change, the support statements don't get out of sync and people get confused which is correct.

2021-05-12 00:24 UTC, closed without merging