Update device-list.md
MicrosoftDocs/microsoft-365-docs pull request #489
Opened 2019-09-25 20:50 UTC by rekhanr

1) Moved Dell 3530 to the beginning of the list. 2) Added a row for 7200 2-in-1/7300/7400

2019-09-26 14:04 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-09-26 14:52 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/device-list.md
> +[Dell Latitude 7200 2-in-1/7300/7400](https://www.dell.com/en-us/work/shop/dell-laptops-and-notebooks/latitude-7200-2-in-1-business-laptop/spd/latitude-12-7200-2-in-1-laptop) | 256 GB / Intel i5 / 8
```suggestion
[Dell Latitude 7200 2-in-1  / 7300 / 7400](https://www.dell.com/en-us/work/shop/dell-laptops-and-notebooks/latitude-7200-2-in-1-business-laptop/spd/latitude-12-7200-2-in-1-laptop) | 256 GB / Intel i5 / 8 GB RAM | IR camera required | May 1, 2021  | May 1, 2024  |
```

2019-09-26 14:53 UTC, JohanFreelancer9 requested changes
Copy Review

2019-09-26 14:57 UTC, JohanFreelancer9 approved these changes

2019-09-27 02:46 UTC, mypil commented
@jaimeo - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

2019-09-27 16:28 UTC, merged