MCD migration - Add details to Exchange Online pre-work
MicrosoftDocs/microsoft-365-docs pull request #4903
Opened 2021-05-05 17:30 UTC by heikobischoff

2021-05-06 20:40 UTC, JoeDavies-MSFT commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-07 01:10 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ms-cloud-germany-transition-add-pre-work.md
> +Users using device connections to Microsoft Cloud Deutschland endpoints for client protocols IMAP4, POP3, SMTP are required to manually update their client devices to switch to the [Exchange Online s
```suggestion
Users using device connections to Microsoft Cloud Deutschland endpoints for client protocols IMAP4, POP3, SMTP are required to manually update their client devices to switch to the [Exchange Online server names](/exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4#settings-users-use-to-set-up-pop3-or-imap4-access-to-their-exchange-online-mailboxes) if they want to pursue these protocols.
```

2021-05-07 01:12 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ms-cloud-germany-transition-add-pre-work.md
> +Pre-communicate this dependency to users of these protocols and ensure they either switch to use Outlook mobile or Outlook on the web during this migration. Failure to update the client endpoints wil
```suggestion
Pre-communicate this dependency to users of these protocols and ensure they either switch to use Outlook for mobile or Outlook on the web during this migration. Failure to update the client endpoints will result in client connection failures with Microsoft Cloud Deutschland when mailboxes are migrated.
```

2021-05-07 01:15 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ms-cloud-germany-transition-add-pre-work.md
> +The new endpoints cannot be configured in advance, they  become available **only** when the mailbox is migrated.
```suggestion
The new endpoints cannot be configured in advance; they become available **only** when the mailbox is migrated.
```

2021-05-07 01:17 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ms-cloud-germany-transition-add-pre-work.md
> +The exact point of time to change the endpoint configuration cannot be predicted. During phase 5, user mailboxes will be successively migrated to the new Office 365 German region. The start of phase
```suggestion
The exact point of time to change the endpoint configuration cannot be predicted. During phase 5, user mailboxes will be successively migrated to the new Office 365 German region. The start of phase 5 will be announced in the Office 365 Admin Center. After each individual mailbox migration, the old endpoints become unavailable immediately, the client device will be disconnected from Exchange Online, and the user must reconfigure all connected devices with the new [Exchange Online server endpoint](/exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4#settings-users-use-to-set-up-pop3-or-imap4-access-to-their-exchange-online-mailboxes). 
```

2021-05-07 01:18 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ms-cloud-germany-transition-add-pre-work.md
> +This limitation is unique to POP3/IMAP4 connections and does not apply to MAPI connections. Consider switching to Outlook apps or other modern protocols on all connected devices before phase 5 starts
```suggestion
This limitation is unique to POP3/IMAP4 connections and does not apply to MAPI connections. Consider switching to Outlook apps or other modern protocols on all connected devices, before phase 5 starts, to improve the user experience.
```

2021-05-07 01:21 UTC, JohanFreelancer9 requested changes
Copy review - a few minor suggestions.

2021-05-07 15:43 UTC, heikobischoff commented
Commited, thanks @JohanFreelancer9!

2021-05-08 03:26 UTC, JohanFreelancer9 approved these changes

2021-05-11 13:14 UTC, yogkumgit commented
@JoeDavies-MSFT Please merge this PR. Thanks

2021-05-12 11:50 UTC, yogkumgit commented
@JoeDavies-MSFT Please merge this PR. Thanks.

2021-05-12 16:23 UTC, merged