Update assign-licenses-to-users.md
MicrosoftDocs/microsoft-365-docs pull request #4905
Opened 2021-05-05 18:49 UTC by msbemba

Added a note about group-based licensing in case users are trying to assign licenses to thousands of users.

2021-05-05 18:51 UTC, msbemba commented
@JohanFreelancer9 Please copy review.

Please note that the I was not able to use the relative link and had to use the absolute link. COuld this be because it was from Azure repo?

2021-05-05 18:51 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4822

2021-05-05 23:08 UTC, cmcatee-MSFT requested changes
Please make the 2 changes as noted.

2021-05-05 23:08 UTC, cmcatee-MSFT commented on microsoft-365/admin/manage/assign-licenses-to-users.md
> +
Replace with the following:

`If you want to assign licenses for a large number of users, use [Assign licenses to users by group membership in Azure Active Directory](/azure/active-directory/enterprise-users/licensing-groups-assign).`

Also, in the "Before you begin" section, please replace the second bullet with the following:

`You can [assign Microsoft 365 licenses to user accounts with PowerShell](../../enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md).`

2021-05-06 05:48 UTC, JohanFreelancer9 reviewed
@msbemba - I'll do a copy review once @cmcatee-MSFT's suggested changes have been implemented. Thanks.

2021-05-06 12:24 UTC, msbemba commented on microsoft-365/admin/manage/assign-licenses-to-users.md
> +
Thank you, Cern. Made changes as per your request.

Thanks
Sri

2021-05-06 12:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-06 13:21 UTC, JohanFreelancer9 approved these changes

2021-05-06 14:10 UTC, yogkumgit commented
@cmcatee-MSFT

2021-05-06 18:24 UTC, merged