Update set-up-multi-factor-authentication.md
MicrosoftDocs/microsoft-365-docs pull request #4909
Opened 2021-05-05 20:07 UTC by msbemba

Moved the TUrn off legacy per user MFA next to before you begin section.

2021-05-05 20:07 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-05 20:07 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4858

2021-05-06 06:18 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md
```suggestion
```

2021-05-06 06:19 UTC, JohanFreelancer9 commented on microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md
```suggestion
```

2021-05-06 06:19 UTC, JohanFreelancer9 requested changes
Please remove blank lines.

2021-05-06 13:10 UTC, JohanFreelancer9 approved these changes

2021-05-06 14:18 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-08-05 09:53 UTC, yogkumgit commented
@kwekuako Gentle reminder, please merge this PR. Thanks

2021-08-16 14:55 UTC, yogkumgit commented
@kwekuako conflict is resolved. Thanks

2021-08-16 16:56 UTC, merged