Update information-for-dns-records.md
MicrosoftDocs/microsoft-365-docs pull request #4912
Opened 2021-05-05 20:31 UTC by msbemba

Made changes to the steps to add DNS records

2021-05-05 20:33 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4867

2021-05-06 14:25 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-07 04:41 UTC, JohanFreelancer9 commented on microsoft-365/admin/get-help-with-domains/information-for-dns-records.md
> +3. Choose  **Manage DNS**, Click on **More Options**, select **Add your own DNS** and cick on **Continue** to see the DNS records to add.
```suggestion
3. Choose  **Manage DNS**, select **More Options** > **Add your own DNS** and select **Continue** to see the DNS records to add.
```

2021-05-07 04:41 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-07 13:07 UTC, JohanFreelancer9 approved these changes

2021-05-07 13:23 UTC, yogkumgit commented
@scotvidican Please merge this PR. Thanks

2021-05-21 11:05 UTC, yogkumgit commented
@scotvidican Gentle reminder.

2021-06-03 18:02 UTC, cmcatee-MSFT requested changes
Please change **Setup** to **Settings** at line 68, 74, and 80.

2021-06-03 18:44 UTC, msbemba commented
> Please change **Setup** to **Settings** at line 68, 74, and 80.

I have made those changes now. Please review and merge.

2021-06-03 19:05 UTC, cmcatee-MSFT requested changes
For lines 92-94 (Steps 4 & 5), please replace with the following:

`4. Go to [Add DNS records to connect your domain](create-dns-records-at-any-dns-hosting-provider.md), and follow the steps to add records at your DNS host's website.'

2021-06-03 19:05 UTC, cmcatee-MSFT commented on microsoft-365/admin/get-help-with-domains/information-for-dns-records.md
> +3. Choose  **Manage DNS**, select **More Options** > **Add your own DNS** and select **Continue** to see the DNS records to add.
Please send screenshots for steps 1 through 3 to me at cmcatee@microsoft.com. I'm not seeing the same UI.

2021-06-03 19:21 UTC, msbemba commented on microsoft-365/admin/get-help-with-domains/information-for-dns-records.md
> +3. Choose  **Manage DNS**, select **More Options** > **Add your own DNS** and select **Continue** to see the DNS records to add.
Cern, Looks like the options have changed in the last 25 days. I shall update you once I make these changes to the document.

2021-06-06 05:15 UTC, msbemba commented on microsoft-365/admin/get-help-with-domains/information-for-dns-records.md
> +3. Choose  **Manage DNS**, select **More Options** > **Add your own DNS** and select **Continue** to see the DNS records to add.
@cmcatee-MSFT I have made changes to the document according to the new UI. Also emailed you the screenshots.

2021-07-01 01:43 UTC, cmcatee-MSFT approved these changes

2021-07-01 01:44 UTC, merged