Update end-life-cycle-groups-teams-sites-yammer.md
MicrosoftDocs/microsoft-365-docs pull request #4956
Opened 2021-05-10 17:21 UTC by msbemba

Reconstructing a teams chat conversation is now possible - https://docs.microsoft.com/en-us/microsoft-365/compliance/conversation-review-sets?view=o365-worldwide

updated the information in the Teams Section

2021-05-10 17:21 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-10 17:21 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4932

2021-05-11 02:17 UTC, JohanFreelancer9 commented on microsoft-365/solutions/end-life-cycle-groups-teams-sites-yammer.md
> +Additionally, if a retention policy is applied to Teams, the conversations are retained and available through eDiscovery searches. Using advanced eDiscovery you can [reconstruct a Teams chat conversa
```suggestion
Additionally, if a retention policy is applied to Teams, the conversations are retained and available through eDiscovery searches. Using advanced eDiscovery you can [reconstruct a Teams chat conversations](/microsoft-365/compliance/conversation-review-sets).
```

2021-05-11 02:19 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-11 09:33 UTC, JohanFreelancer9 approved these changes

2021-05-11 12:27 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-05-11 12:48 UTC, merged