Update send-email-as-distribution-list.md
MicrosoftDocs/microsoft-365-docs pull request #4960
Opened 2021-05-10 18:24 UTC by msbemba

Added instructions for outlook client as well.

2021-05-10 18:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-10 18:24 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4907

2021-05-11 01:31 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/send-email-as-distribution-list.md
> +2. Compose a New Email. Click the **From** field and select **Other email address**. If you do not see the From field, navigate to Options and select From in the section Show fields.
```suggestion
2. Compose a New Email. Click the **From** field and select **Other email address**. If you do not see the From field, navigate to **Options** and select **From** in the Show fields section.
```

2021-05-11 01:36 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-11 09:32 UTC, JohanFreelancer9 approved these changes

2021-05-11 12:33 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-05-11 16:54 UTC, merged