Update centralized-deployment-of-add-ins.md
MicrosoftDocs/microsoft-365-docs pull request #4966
Opened 2021-05-11 08:07 UTC by msbemba

Added a line stating that the module works only with Basic auth. As there is ambiguity on whether this works with Modern auth with MFA disabled.

2021-05-11 08:07 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-11 08:07 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4685

2021-05-11 08:58 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/centralized-deployment-of-add-ins.md
> +> Multifactor authentication is not supported when using the Central Deployment PowerShell module. The module only works with basic authentication.
```suggestion
> Multifactor authentication is not supported when using the Central Deployment PowerShell module. The module only works with Basic authentication.
```

2021-05-11 08:59 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-05-11 13:04 UTC, yogkumgit commented
@msbemba

2021-05-11 16:22 UTC, JohanFreelancer9 approved these changes

2021-05-12 12:01 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-05-21 11:09 UTC, yogkumgit commented
@kwekuako Gentle reminder

2021-06-03 11:55 UTC, yogkumgit commented
@efrene  Please help as it is from addins area.

2021-06-04 15:47 UTC, merged