Update device-control-removable-storage-access-control.md
MicrosoftDocs/microsoft-365-docs pull request #4971
Opened 2021-05-11 16:13 UTC by tewchen

2021-05-14 14:04 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-15 05:49 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +    - DeviceId: add wildcard support (* or ?) anywhere in the text value in the version 4.18.2105 or later
```suggestion
    - DeviceId: add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
```

2021-05-15 05:51 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +    - HardwareId: add wildcard support (* or ?) anywhere in the text value in the version 4.18.2105 or later
```suggestion
    - HardwareId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
```

2021-05-15 05:51 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +    - InstancePathId: add wildcard support (* or ?) anywhere in the text value in the version 4.18.2105 or later
```suggestion
    - InstancePathId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
```

2021-05-15 05:51 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +    - FriendlyNameId: add wildcard support (* or ?) anywhere in the text value in the version 4.18.2105 or later
```suggestion
    - FriendlyNameId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
```

2021-05-15 05:52 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +    - SerialNumberId: add wildcard support (* or ?) anywhere in the text value in the version 4.18.2105 or later
```suggestion
    - SerialNumberId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
```

2021-05-15 05:53 UTC, JohanFreelancer9 requested changes
Copy review - @tewchen, could you please commit my suggested changes? Many thanks.

2021-05-15 06:17 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +    - SerialNumberId: add wildcard support (* or ?) anywhere in the text value in the version 4.18.2105 or later
```suggestion
    - DeviceId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
    - HardwareId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
    - InstancePathId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
    - FriendlyNameId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
    - SerialNumberId: Add wildcard support (* or ?) anywhere in the text value in version 4.18.2105 or later
```

2021-05-17 10:27 UTC, yogkumgit commented
@tewchen Please implement the suggested feedback. Thanks

2021-06-18 03:10 UTC, JohanFreelancer9 approved these changes

2021-06-18 11:38 UTC, yogkumgit commented
@v-smandalika Please merge this PR. Thanks

2021-06-18 12:21 UTC, v-smandalika commented
@yogkumgit @AshaIyengar21 @claydetels19 


Hi Yogesh Kumar,

Based on the chain of the notification emails, we understand that we need to carry out the changes through a new ticket as we do not have the privileges to merge PRs and that too one that is worked on by an SME/POC.

I shall take this up with my lead and project manager and shall revert. Hope this plan is okay with you.


Thanks,
Siddarth

2021-08-05 09:56 UTC, yogkumgit commented
@v-smandalika OK. please either merge or close the PRs associated to you.

2021-08-05 11:55 UTC, v-smandalika commented
Hi @yogkumgit,

Apologies that we could not take this up with our Principal Manager Daniel Simpson.

Just FYI, we from the documentation team do not have the privileges to merge PRs; hence, we have taken this up with Daniel Simpson.  We will be getting an idea as to whether new tickets are to be created for us to import changes from this PR into our new PRs.

We have notified Daniel Simpson about this PR's status, and we will be reverting to you tomorrow.


Thanks,
Siddarth

2021-08-20 11:32 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2021-08-24 18:30 UTC, chrisda commented
Updated information already in topic in the [Prepare your endpoints](https://docs.microsoft.com/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control#prepare-your-endpoints) section:

Deploy Removable Storage Access Control on Windows 10 devices that have antimalware client version **4.18.2103.3 or later**.

- **4.18.2104 or later**: Add SerialNumberId, VID_PID, filepath-based GPO support, ComputerSid
- **4.18.2105 or later**: Add Wildcard support for HardwareId/DeviceId/InstancePathId/FriendlyNameId/SerialNumberId, the combination of specific user on specific machine, removeable SSD (a SanDisk Extreme SSD)/USB Attached SCSI (UAS) support

Closing

2021-08-24 18:30 UTC, closed without merging