Update create-a-custom-sensitive-information-type-in-scc-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #4990
Opened 2021-05-13 20:24 UTC by kellybos

Addition of note about known extraction issue with no ETA for fix. Bug - 

https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/2068902

2021-05-14 14:04 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-15 06:07 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell.md
> +> If you use an ampersand character (&) as part of a keyword in your custom sensitive information type, please note that there is a known issue. You should add an additional term with spaces around t
```suggestion
> If you use an ampersand character (&) as part of a keyword in your custom sensitive information type, please note that there is a known issue. You should add an additional term with spaces around the character to make sure that the character is properly identified, for example, L & P _not_ L&P.
```

2021-05-15 06:08 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell.md
> +><Term>L & P</Term>
```suggestion
```

2021-05-15 06:13 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-17 10:28 UTC, yogkumgit commented
@kellybos Please implement the suggested changes. Thanks

2021-05-17 14:21 UTC, JohanFreelancer9 approved these changes

2021-05-18 12:40 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks.

2021-06-01 22:36 UTC, kellybos commented
@chrfox Any update on getting this PR finalized?

2021-06-10 16:55 UTC, merged