Add Cipher article
MicrosoftDocs/microsoft-365-docs pull request #4996
Opened 2021-05-14 14:20 UTC by salarson

#SignOff

2021-05-18 12:53 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-18 13:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/prepare-tls-1.2-in-office-365.md
> +- [TLS cipher suites supported by Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/technical-reference-details-about-encryption?view=o365-worldwide#tls-cipher-suites-supported-by
```suggestion
- [TLS cipher suites supported by Office 365](/microsoft-365/compliance/technical-reference-details-about-encryption?view=o365-worldwide#tls-cipher-suites-supported-by-office-365)
```

2021-05-18 13:54 UTC, JohanFreelancer9 requested changes
Copy review - please change to relative link as indicated.

2021-05-18 15:23 UTC, JohanFreelancer9 approved these changes

2021-05-19 07:36 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2021-06-17 17:23 UTC, merged