Update enable-controlled-folders.md
MicrosoftDocs/microsoft-365-docs pull request #5010
Opened 2021-05-16 01:19 UTC by msbemba

Made changes to navigation in endpoint manager to enable controlled folder access

2021-05-16 01:19 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4981

2021-05-16 01:19 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-16 06:20 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +1. Sign in to the [Endpoint Manager](https://endpoint.microsoft.com) and open Endpoint Security.
```suggestion
1. Sign in to the [Endpoint Manager](https://endpoint.microsoft.com) and open Endpoint Security.
```

2021-05-16 06:23 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +3. Select the Plaform , choose **Windows 10 and later** and Select the profile **Attack Surface Reduction rules** > Click **Create**
```suggestion
3. Select **Platform**, choose **Windows 10 and later**, and select the profile **Attack Surface Reduction rules** > **Create**.
```

2021-05-16 06:27 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +5.  Scroll down to the bottom and Select **Enable Folder Protection** Drop down and Choose **Enable**
```suggestion
5.  Scroll down to the bottom, select the **Enable Folder Protection** drop-down, and choose **Enable**.
```

2021-05-16 06:28 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +6.  Select **List of additional folders that need to be protected** and **Add** the folders that needs to be protected.
```suggestion
6.  Select **List of additional folders that need to be protected** and **Add** the folders that need to be protected.
```

2021-05-16 06:29 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +8.  Select **Exclude files and paths from attack surface reduction rules** and **Add** the Files and paths that needs to be excluded from Attack surface Reduction rules.
```suggestion
8.  Select **Exclude files and paths from attack surface reduction rules** and **Add** the Files and paths that need to be excluded from attack surface reduction rules.
```

2021-05-16 06:30 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +4.  **Name** the Policy and add **Description** > Click **Next**
```suggestion
4.  Name the policy and add a description. Select **Next**.
```

2021-05-16 06:31 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +9.  Select the profile **Assignments**, assign to **All Users & All Devices**, and **Save**.
```suggestion
9.  Select the profile **Assignments**, assign to **All Users & All Devices**, and select **Save**.
```

2021-05-16 06:31 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +10.  Select **Next** to save each open blade and **Create**.
```suggestion
10.  Select **Next** to save each open blade and then **Create**.
```

2021-05-16 06:33 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +   > Wilcard is supported for applications, but not for folders. Subfolders are not protected. Allowed apps will continue to trigger events until they are restarted.
```suggestion
   > Wildcards are supported for applications, but not for folders. Subfolders are not protected. Allowed apps will continue to trigger events until they are restarted.
```

2021-05-16 06:37 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-controlled-folders.md
> +7.  Select **List of apps that have access to protected folders** and **Add** the apps that have access to protected folders.
```suggestion
7.  Select **List of apps that have access to protected folders** and add the apps that have access to protected folders.
```

2021-05-16 06:38 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-17 10:40 UTC, yogkumgit commented
@JohanFreelancer9

2021-05-17 14:06 UTC, JohanFreelancer9 approved these changes

2021-05-18 12:38 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks.

2021-05-21 11:04 UTC, yogkumgit commented
@Dansimp Gentle reminder.

2021-06-08 23:02 UTC, merged