Update turn-audit-log-search-on-or-off.md
MicrosoftDocs/microsoft-365-docs pull request #5043
Opened 2021-05-18 22:56 UTC by msbemba

made changes to the navigation in the compliance center to turn on the Audit log.

2021-05-18 22:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-18 22:57 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5016

2021-05-19 03:56 UTC, JohanFreelancer9 commented on microsoft-365/compliance/turn-audit-log-search-on-or-off.md
> +3. Click  **Start recording user and admin activity**. You will be prompted to confirm if **Your Oraganization settings need to be udpated. Do you want to Continue?**. Click **Yes** to turn on Audit
```suggestion
3. Select**Start recording user and admin activity**. You will be prompted to confirm if **Your Organization settings need to be updated. Do you want to Continue?**. Select **Yes** to turn on Audit log search.
```

2021-05-19 04:09 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-19 07:50 UTC, yogkumgit commented
@msbemba

2021-05-19 16:06 UTC, JohanFreelancer9 commented on microsoft-365/compliance/turn-audit-log-search-on-or-off.md
> +3. Select**Start recording user and admin activity**. You will be prompted to confirm if **Your Organization settings need to be updated. Do you want to Continue?**. Select **Yes** to turn on audit l
```suggestion
3. Select **Start recording user and admin activity**. You will be prompted to confirm if **Your Organization settings need to be updated. Do you want to Continue?**. Select **Yes** to turn on audit log search.
```

2021-05-19 16:06 UTC, JohanFreelancer9 requested changes
@msbemba - one more, please.

2021-05-20 02:40 UTC, JohanFreelancer9 approved these changes

2021-05-20 11:20 UTC, yogkumgit commented
@markjjo Please merge this PR. Thanks

2021-05-25 19:32 UTC, merged