Update event-views.md
MicrosoftDocs/microsoft-365-docs pull request #5046
Opened 2021-05-18 23:31 UTC by msbemba

Using site-relative links as the image is from a different repo

2021-05-18 23:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-18 23:31 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5014

2021-05-19 03:07 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/event-views.md
>  4. Navigate to where you extracted XML file for the custom view you want and select it.
```suggestion
4. Navigate to where you extracted the XML file for the custom view you want and select it.
```

2021-05-19 03:08 UTC, JohanFreelancer9 requested changes
Copy review - one minor additional edit, please.

2021-05-19 08:02 UTC, yogkumgit commented
@msbemba

2021-05-19 16:03 UTC, JohanFreelancer9 approved these changes

2021-05-20 11:19 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2021-05-21 11:01 UTC, yogkumgit commented
@Dansimp Gentle reminder, please merge this PR. Thanks

2021-06-08 23:48 UTC, Dansimp commented
I don't think referencing the name of the repo will work here. I will need to double check. we might need to move the image files over to this repo.

2021-06-22 13:34 UTC, yogkumgit commented
@msbemba and @Dansimp

2021-07-12 13:18 UTC, yogkumgit commented
@Dansimp Gentle reminder, please merge or reply. Awaiting resolution. Thanks

2021-08-06 16:34 UTC, merged