Additional step to closing, deleting and reopening
MicrosoftDocs/microsoft-365-docs pull request #5068
Opened 2021-05-20 17:49 UTC by StefanieBier

Please add the additional step required to find the "more information" section on the Case Information panel.

2021-05-21 13:24 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-22 03:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/close-or-delete-case.md
> +3. At the bottom of the **Case Information** panel, you will see a "..." with more options.
```suggestion
3. At the bottom of the **Case Information** panel, select **...** (more options).  
```

2021-05-22 03:31 UTC, JohanFreelancer9 commented on microsoft-365/compliance/close-or-delete-case.md
> +3. At the bottom of the **Case Information** panel, you will see a "..." with more options.
```suggestion
3. At the bottom of the **Case Information** panel, click **...** (more options).  
```

2021-05-22 03:32 UTC, JohanFreelancer9 commented on microsoft-365/compliance/close-or-delete-case.md
> +3. At the bottom of the **Case Information** panel, you will see a "..." with more options.
```suggestion
3. At the bottom of the **Case Information** panel, click **...** (more options).  
```

2021-05-22 03:34 UTC, JohanFreelancer9 requested changes
Copy review - @StefanieBier, please commit my suggested changes if you agree.

2021-05-25 19:33 UTC, merged

2021-05-25 19:34 UTC, markjjo commented
@StefanieBier PR merged. Thanks for making this update. I'm going to tweak it a little bit.