Update endpoint-dlp-getting-started.md
MicrosoftDocs/microsoft-365-docs pull request #5093
Opened 2021-05-23 09:59 UTC by amirsc3

Adding important note to pre-requisites

2021-05-23 23:30 UTC, nihendle commented
@chrfox can you please review these changes?

2021-05-24 10:19 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-25 03:03 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-getting-started.md
> +   > [!NOTE]
```suggestion
> [!NOTE] 
```

2021-05-25 03:10 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-getting-started.md
> +   > If using 'AAD registered' devices, then you must reboot the device after completing the AAD registration. This is required for each new user logging-in to the device.<br>
```suggestion
> - If you are using _Azure AD registered_ devices, you must reboot the device after completing the Azure AD registration. This is required for each new user signing in to the device.
> - If you are using either _Azure AD registered_ or _Hybrid Azure AD joined_ devices, the device can be joined to on-premises Active Directory as well.
```

2021-05-25 03:11 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-getting-started.md
> +   > If using either 'AAD registered' or 'Hybrid Azure AD joined' devices, then the device can be joined to on-premises Active Directory as well.<br>
```suggestion
```

2021-05-25 03:14 UTC, JohanFreelancer9 requested changes
Copy review. @amirsc3, could you please commit my suggested changes if you agree with them? Many thanks.

2021-05-25 07:18 UTC, amirsc3 commented
@chrfox can you please confirm that the Azure AD public doc we are pointing to in the AAD registered scenario was updated to include a reboot step? 
If yes, then we should remove the remaining note below:
> [!NOTE] 
   > If using 'AAD registered' devices, then you must reboot the device after completing the AAD registration. This is required for each new user logging-in to the device.<br>

2021-05-25 15:47 UTC, JohanFreelancer9 approved these changes

2021-05-25 16:08 UTC, chrfox commented
edits made in different PR

2021-05-25 16:08 UTC, closed without merging