Update user-submission.md
MicrosoftDocs/microsoft-365-docs pull request #5103
Opened 2021-05-24 21:07 UTC by andypunt

2021-05-25 06:16 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-25 06:58 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/user-submission.md
> +The message formatting requirements are described in the next section. The formatting is optional, but if it does not follow the prexscribed format, the reports will always be submitted as phish.
```suggestion
The message formatting requirements are described in the next section. The formatting is optional, but if it does not follow the prescribed format, the reports will always be submitted as phish.
```

2021-05-25 06:59 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-25 07:05 UTC, JohanFreelancer9 approved these changes

2021-05-26 04:39 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2021-05-26 12:04 UTC, merged