Update data-loss-prevention-policies.md
MicrosoftDocs/microsoft-365-docs pull request #5121
Opened 2021-05-25 22:30 UTC by msbemba

Added a line stating that Compliance and security admin need no extra permissions to create or modify a policy as they have the access by default.

2021-05-26 05:15 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-26 06:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-loss-prevention-policies.md
> +By default, Global admin, Security admin and Complaince admin will have access to create and apply a DLP policy. Other Members of your compliance team who will create DLP policies need permissions to
```suggestion
By default, Global admins, Security admins, and Compliance admins will have access to create and apply a DLP policy. Other Members of your compliance team who will create DLP policies need permissions to the Security &amp; Compliance Center. By default, your Tenant admin will have access to this location and can give compliance officers and other people access to the Security &amp; Compliance Center, without giving them all of the permissions of a Tenant admin. To do this, we recommend that you:
```

2021-05-26 06:16 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-27 05:17 UTC, yogkumgit commented
@msbemba

2021-05-27 15:17 UTC, JohanFreelancer9 approved these changes

2021-05-28 04:33 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2021-06-10 16:56 UTC, merged