Update ome-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #5124
Opened 2021-05-25 23:30 UTC by msbemba

Tested and able to view encrypted email and attachments on outlook for IOS and android

2021-05-25 23:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5037

2021-05-25 23:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-26 01:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          - Users can view attachments that inherit protection from email when they use Outlook for Windows, Outlook for Mac, Outlook for Android, Outlook for iOS and Outlook on the web.
```suggestion
          - Users can view attachments that inherit protection from email when they use Outlook for Windows, Outlook for Mac, Outlook for Android, Outlook for iOS, and Outlook on the web.
```

2021-05-26 01:10 UTC, JohanFreelancer9 requested changes
Copy review. Minor edit.

2021-05-26 05:24 UTC, yogkumgit commented
@msbemba

2021-05-28 03:28 UTC, JohanFreelancer9 approved these changes

2021-05-28 05:09 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2021-06-02 06:26 UTC, yogkumgit commented
@KCCross Please merge this Pr. Thanks

2021-10-25 07:27 UTC, yogkumgit commented
@KCCross Gentle reminder.

2021-12-06 22:29 UTC, KCCross commented
Samson, please review. Difference between functional and supported.

2022-01-09 06:36 UTC, yogkumgit commented
@samschan-ms Gentle reminder

2022-01-11 00:36 UTC, samschan-ms commented
@KCCross please add a note that android and iOS would use the Office mobile app to view the encrypted attachments, and not directly in Outlook mobile.

2022-01-26 09:54 UTC, msbemba commented
@KCCross  made changes per samschan-ms advise

2022-01-26 18:04 UTC, samschan-ms approved these changes

2022-02-08 14:38 UTC, yogkumgit commented
@tiburd As Samson has reviewed it, kindly merge this PR. Thanks

2022-02-08 21:01 UTC, merged