Update office-365-groups.md
MicrosoftDocs/microsoft-365-docs pull request #5151
Opened 2021-05-27 22:29 UTC by msbemba

I have added other resources that a user cannot create when he is limited from creating groups. I can confirm that these cannot be created when there is a restriction, but I would like you to review and confirm if this can be added to the document.

2021-05-27 22:29 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5086

2021-05-27 22:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-28 03:57 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/office-365-groups.md
> +Any user can create a group unless you [limit group creation to a specific set of people](../../solutions/manage-creation-of-groups.md). If you limit group creation, users who cannot create groups wi
```suggestion
Any user can create a group unless you [limit group creation to a specific set of people](../../solutions/manage-creation-of-groups.md). If you limit group creation, users who cannot create groups will not be able to create SharePoint sites, Planners, teams, Outlook group calendars, Stream groups, Yammer groups, Shared libraries in OneDrive, or shared Power BI workspaces. These services require the people creating them to be able to create a group. Users can still participate in group activities, such as creating tasks in Planner or using Teams chat, provided they are a member of the group.
```

2021-05-28 03:58 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-28 05:01 UTC, yogkumgit commented
@msbemba

2021-05-29 09:20 UTC, JohanFreelancer9 approved these changes

2021-05-31 11:48 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks.

2021-06-01 13:10 UTC, MikePlumleyMSFT commented
@ArunMSFT can you review?

2021-06-01 15:05 UTC, ArunMSFT commented
Change looks good, please ensure it matches our style guide.

From: Mike Plumley ***@***.***>
Sent: Tuesday, June 1, 2021 6:41 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Arunkumaran Varadharajan ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update office-365-groups.md (#5151)


@ArunMSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FArunMSFT&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7C9a30547d6ebc417e587408d924feac0a%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637581498505511140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qkgRiEoKjgFbHWcyBWM5lDsdw9YLUiAwsNmsSnBKnDc%3D&reserved=0> can you review?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F5151%23issuecomment-852111622&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7C9a30547d6ebc417e587408d924feac0a%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637581498505511140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MX03aI6By%2F%2FFUK3ax8oerjgo%2BteeEMGkrWW%2B%2ByFbBdc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHZV2TF3AZXOFTZ6NOC36SLTQTL5PANCNFSM45VHFSTQ&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7C9a30547d6ebc417e587408d924feac0a%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637581498505521140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cBcuzFd6mpQVCu5L%2FwPNI5CoiFlSTT9n8qIbcMjFqX0%3D&reserved=0>.

2021-06-04 09:35 UTC, yogkumgit commented
@MikePlumleyMSFT

2021-06-04 12:28 UTC, merged