Update remove-former-employee-step-4.md
MicrosoftDocs/microsoft-365-docs pull request #5154
Opened 2021-05-27 23:23 UTC by msbemba

Added details on how to grant access to another user on former employees onedrive

2021-05-27 23:23 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5087

2021-05-27 23:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-28 03:37 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-4.md
> +
```suggestion
You can also grant access to another user to a former employee's OneDrive.
```

2021-05-28 03:42 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-4.md
> +7. Enter the Former employee's name and select **Find**.
```suggestion
7. Enter the former employee's name and select **Find**.
```

2021-05-28 03:43 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-4.md
> +8. Right-click the user, and then choose **Manage site collection owners**.
```suggestion
8. Right-click on the user, and then choose **Manage site collection owners**.
```

2021-05-28 03:45 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-4.md
> +9. Add the **User** to the **Site collection Administrators** and Click On **Ok**
```suggestion
9. Add the user to **Site collection administrators** and select **Ok**.
```

2021-05-28 03:47 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-4.md
> +10. The **User** will now able to access the former employees Onedrive using the onedrive **URL**
```suggestion
10. The user will now be able to access the former employee's OneDrive using the OneDrive URL. 
```

2021-05-28 03:50 UTC, JohanFreelancer9 requested changes
Copy review.

2021-05-28 05:08 UTC, yogkumgit commented
@msbemba

2021-05-31 04:02 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-4.md
> +You can also grant access to another user to a former employee's OneDrive.
```suggestion
You can also grant access to another user to access a former employee's OneDrive.
```

2021-05-31 04:03 UTC, JohanFreelancer9 requested changes
@msbemba - one more, please.

2021-05-31 05:24 UTC, JohanFreelancer9 approved these changes

2021-05-31 11:31 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-06-01 18:21 UTC, merged