Update whats-new-in-defender-for-office-365.md
MicrosoftDocs/microsoft-365-docs pull request #5159
Opened 2021-05-28 15:18 UTC by VipulMSFT

Updating the doc to cover Email entity page, Management API updates and Threat Analytics

2021-05-31 11:57 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-31 14:55 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md
> +- [Email entity page](mdo-email-entity-page.md): A unified 360-degree view of an email with enriched information around Threats, authentication and detections, detonation details, and a brand-new Ema
```suggestion
- [Email entity page](mdo-email-entity-page.md): A unified 360-degree view of an email with enriched information around threats, authentication and detections, detonation details, and a brand-new email preview experience.
```

2021-05-31 15:04 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md
> +- Office 365 Management API: Updates to EmailEvents (RecordType 28) to add Delivery Action, Original and Latest Delivery Locations, and updated Detection details. https://docs.microsoft.com/en-us/off
```suggestion
- [Office 365 Management API](/office/office-365-management-api/office-365-management-activity-api-schema#email-message-events): Updates to EmailEvents (RecordType 28) to add delivery action, original and latest delivery locations, and updated detection details.
```

2021-05-31 15:10 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md
> +- Threat Analytics for Defender for Office 365: View active threat actors, popular techniques and attack surfaces, along with extensive reporting from Microsoft researchers around ongoing campaigns.
```suggestion
- [Threat Analytics for Defender for Office 365](/microsoft-365/security/defender/threat-analytics): View active threat actors, popular techniques and attack surfaces, along with extensive reporting from Microsoft researchers around ongoing campaigns. 
```

2021-05-31 15:11 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md
> +
```suggestion
```

2021-05-31 15:12 UTC, JohanFreelancer9 requested changes
Copy review - @VipulMSFT, please commit my suggested changes if you agree with them. Many thanks.

2021-05-31 15:18 UTC, VipulMSFT commented
@JohanFreelancer9 - can you please have a relook at the URLs? I agreed with all the changes, but looks like the URL hyperlink may not be working. 
This includes the Threat Analytics link over here: 
https://docs.microsoft.com/en-us/microsoft-365/security/defender/threat-analytics?view=o365-worldwide 

And Management API link over here: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#email-message-events

2021-05-31 16:33 UTC, JohanFreelancer9 approved these changes
@VipulMSFT - Thank you for committing my suggested changes. The relative links might not work in the preview version for the PR, but they'll work when the article is merged to master.

2021-05-31 16:43 UTC, VipulMSFT commented
@yogkumgit the PR has been approved by Johan

2021-06-04 09:36 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2021-06-04 21:14 UTC, merged