Fix typo in onboard-downlevel.md
MicrosoftDocs/microsoft-365-docs pull request #5167
Opened 2021-05-29 02:30 UTC by h0ffayyy

Fix a small typo line 76: "you environment" to "your environment"

2021-05-31 11:58 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-05-31 14:01 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/onboard-downlevel.md
> +- Meet the Azure Log Analytics agent minimum system requirements. For more information, see [Collect data from computers in your environment with Log Analytics](https://docs.microsoft.com/azure/log-a
```suggestion
- Meet the Azure Log Analytics agent minimum system requirements. For more information, see [Collect data from computers in your environment with Log Analytics](/azure/log-analytics/log-analytics-concept-hybrid#prerequisites).
```

2021-05-31 14:05 UTC, JohanFreelancer9 requested changes
Copy review - @h0ffayyy, please also commit my suggested changes. Many thanks.

2021-05-31 19:06 UTC, h0ffayyy commented
@JohanFreelancer9 done!

2021-06-01 01:19 UTC, JohanFreelancer9 approved these changes

2021-06-01 11:00 UTC, yogkumgit commented
@Kateyanne Please merge this PR. Thanks

2021-06-01 14:54 UTC, merged