Update business-assist.md
MicrosoftDocs/microsoft-365-docs pull request #5178
Opened 2021-05-31 20:55 UTC by msbemba

Made changes to the navigation as tenants with fewer than 5 users will be on simplified view

2021-05-31 20:55 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-05-31 20:55 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5165

2021-06-01 01:34 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/business-assist.md
> +1. In the simplified view of Microsoft 365 admin center, go to **Subscriptions** tab > **Add Products**.
```suggestion
1. In the simplified view of the Microsoft 365 admin center, go to the **Subscriptions** tab > **Add Products**.
```

2021-06-01 01:35 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-01 14:10 UTC, JohanFreelancer9 approved these changes

2021-06-01 14:13 UTC, JohanFreelancer9 reviewed
Apologies @msbemba, one more, please.

2021-06-01 14:24 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/business-assist.md
> +1. In the simplified view of the Microsoft 365 admin center, go to the **Subscriptions** tab > **Add Products**.
```suggestion
1. In the simplified view of the Microsoft 365 admin center, go to the **Subscriptions** tab and select **Add Products**.
```

2021-06-01 17:56 UTC, AntoniaBlume commented on microsoft-365/admin/misc/business-assist.md
> +1. In the simplified view of Microsoft 365 admin center, go to **Subscriptions** tab > **Add Products**.
Please change "Add Products" to "Add products" (lowercase)

2021-06-01 17:57 UTC, AntoniaBlume commented on microsoft-365/admin/misc/business-assist.md
> +2. On the Purchase services page, Select **Details** on the **Business Assist for Microsoft 365** and complete your purchase.
Please remove "the" before "Business Assist for Microsoft 365".

2021-06-01 17:59 UTC, AntoniaBlume commented on microsoft-365/admin/misc/business-assist.md
> +**Business Assist for Microsoft 365** is designed for businesses with fewer than 5 users to give you and your employees around-the-clock access to small business specialists as you grow your business
Please make this same change in the "Eligibility of Business Assist" section (change less to fewer)

2021-06-01 17:59 UTC, AntoniaBlume requested changes
See comments inline.

2021-06-02 00:54 UTC, msbemba commented
> See comments inline.

Thank you.

2021-06-02 01:38 UTC, JohanFreelancer9 approved these changes

2021-06-02 06:19 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-06-02 15:59 UTC, merged