added link to SMTP Auth clients report
MicrosoftDocs/microsoft-365-docs pull request #5216
Opened 2021-06-04 07:00 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/298

2021-06-04 07:01 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @nam31, for your information

Thank you

2021-06-04 08:05 UTC, JohanFreelancer9 commented on microsoft-365/compliance/prepare-tls-1.2-in-office-365.md
> +- For identifying version of TLS used by SMTP clients, see [SMTP Auth clients insight and report in the Security & Compliance Center](/microsoft-365/security/office-365-security/mfi-smtp-auth-clients
```suggestion
- To identify the version of TLS used by SMTP clients, see [SMTP Auth clients insight and report in the Security & Compliance Center](/microsoft-365/security/office-365-security/mfi-smtp-auth-clients-report).
```

2021-06-04 09:38 UTC, yogkumgit commented
@MaratMussabekov

2021-06-04 12:57 UTC, JohanFreelancer9 requested changes
@MaratMussabekov - could you please commit my suggested changes? Many thanks.

2021-06-07 14:39 UTC, yogkumgit commented
@MaratMussabekov Gentle reminder

2021-06-07 14:54 UTC, JohanFreelancer9 approved these changes

2021-06-08 13:07 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2021-07-22 09:15 UTC, merged