Update threat-protection-integration.md
MicrosoftDocs/microsoft-365-docs pull request #5267
Opened 2021-06-09 17:05 UTC by msbemba

Fixed broken link

2021-06-09 17:05 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5224

2021-06-09 17:05 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2021-06-10 08:00 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/threat-protection-integration.md
>  With Microsoft 365 Defender, Microsoft Defender for Endpoint and various Microsoft security solutions form a unified pre- and post-breach enterprise defense suite that natively integrates across endp
```suggestion
With Microsoft 365 Defender, Microsoft Defender for Endpoint, and various Microsoft security solutions form a unified pre- and post-breach enterprise defense suite that natively integrates across endpoint, identity, email, and applications to detect, prevent, investigate, and automatically respond to sophisticated attacks. 
```

2021-06-10 08:00 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, a couple of minor additional edits, please.

2021-06-10 16:19 UTC, merged