Update ome-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #5283
Opened 2021-06-10 17:33 UTC by msbemba

Encrypted messages can be opened in owa. Only in outlook, the automapping feature is required.

2021-06-10 17:33 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-06-10 17:33 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5217

2021-06-11 05:57 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          Users can open encrypted messages in outlook as long as they are given direct access and automapping is turned ON. Access is not allowed in outlook if the access is granted via an email-ena
```suggestion
          Users can open encrypted messages in Outlook as long as they are given direct access and automapping is turned ON. Access is not allowed in Outlook if the access is granted via an email-enabled security group. Users can access encrypted messages using Outlook on the web.
```

2021-06-11 05:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-11 08:50 UTC, JohanFreelancer9 approved these changes

2021-06-11 13:27 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2021-08-05 10:00 UTC, yogkumgit commented
@KCCross Gentle reminder, please merge this PR. Thanks

2021-12-06 22:36 UTC, KCCross commented
@msbemba Please resolve - You can sign in to the OME portal to retrieve mail as long as the sender's organization is active and the mail has not been configured to expire.

2021-12-07 12:56 UTC, msbemba commented
Thank you @KCCross

2021-12-07 12:56 UTC, closed without merging