Update use-dkim-to-validate-outbound-email.md
MicrosoftDocs/microsoft-365-docs pull request #5308
Opened 2021-06-14 07:20 UTC by puneethmeister

Currently we do not auto rotate, hence the option a is not valid "a) let the Microsoft 365 service rotate the selector and upgrade to 2048-bitness within the next 6 months"

2021-06-14 07:21 UTC, puneethmeister commented
cc : @MSFTTracyP

2021-06-15 11:28 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-06-15 14:00 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md
> +If you want to rotate to the second selector, After 4 days and confirming that 2048-bitness is in use, manually rotate the second selector key by using the appropriate cmdlet listed above.
```suggestion
If you want to rotate to the second selector, after 4 days and confirming that 2048-bitness is in use, manually rotate the second selector key by using the appropriate cmdlet listed above.
```

2021-06-15 14:01 UTC, JohanFreelancer9 requested changes
Copy review - @puneethmeister, kindly commit the minor edit. Many thanks.

2021-06-18 13:40 UTC, yogkumgit commented
@puneethmeister Gentle reminder

2021-06-25 11:14 UTC, JohanFreelancer9 approved these changes

2021-06-28 11:55 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2021-07-14 07:28 UTC, puneethmeister commented
@MSFTTracyP Gentle reminder

2021-07-20 17:41 UTC, MSFTTracyP reviewed
Thanks

2021-07-20 17:42 UTC, merged