updated steps
MicrosoftDocs/microsoft-365-docs pull request #532
Opened 2019-10-08 10:54 UTC by VLG17

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/476

2019-10-08 13:23 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-10-08 13:37 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/identity-access-policies.md
> +To create a new app protection policy, log in to the Microsoft Azure portal with your administer credentials, and then navigate to **Client apps > App protection policies**. Choose **Create policy**.
```suggestion
To create a new app protection policy, sign in to the Microsoft Azure portal with your administrator credentials, and then navigate to **Client apps** > **App protection policies**. Choose **Create policy**.
```

2019-10-08 13:37 UTC, JohanFreelancer9 requested changes
Copy Review

2019-10-08 13:48 UTC, mypil commented
@VLG17 - please merge the commit on the copy/edit review made by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-10-09 14:16 UTC, mypil commented
@BrendaCarter - PR has been copy edited and is ready for final review. This is based on issue #476

Thank you.

cc: @kenwith

2019-10-18 00:24 UTC, merged