Update ms-cloud-germany-transition-add-devices.md
MicrosoftDocs/microsoft-365-docs pull request #5334
Opened 2021-06-15 18:00 UTC by Ariantor

Add 1 entry FAQ in the Devices section

2021-06-16 07:38 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-06-16 10:47 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ms-cloud-germany-transition-add-devices.md
> +**Do I still need to add the DNS name as stated in this [Create DNS records for Microsoft using Windows-based DNS](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-using-wi
```suggestion
**Do I still need to add the DNS name as stated in [Create DNS records for Microsoft using Windows-based DNS](/microsoft-365/admin/dns/create-dns-records-using-windows-based-dns?view=o365-worldwide#add-two-cname-records-for-mobile-device-management-mdm-for-microsoft)?**
```

2021-06-16 10:48 UTC, JohanFreelancer9 requested changes
Copy review - @Ariantor, kindly commit my suggested changes. Many thanks.

2021-07-05 12:10 UTC, yogkumgit commented
Gentle reminder @Ariantor

2021-07-15 00:22 UTC, merged