Update manage-addins-in-the-admin-center.md
MicrosoftDocs/microsoft-365-docs pull request #5351
Opened 2021-06-17 13:49 UTC by msbemba

I have added the note based on the internal ADO item and discussion - https://office.visualstudio.com/OC/_workitems/edit/5121015?src=WorkItemMention&src-action=artifact_link

2021-06-17 13:49 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-06-17 13:49 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5302

2021-06-18 08:47 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-addins-in-the-admin-center.md
> +> Add-ins such as Visio Data Visualizer, Bing Maps, and People Graph will still show up in the ribbon, even if an admin has disabled the Store. To remove these links, adminisrators must disable the s
```suggestion
> Add-ins such as Visio Data Visualizer, Bing Maps, and People Graph will still show up in the ribbon, even if an admin has disabled the Store. To remove these links, administrators must disable the Store through Group Policy Object (GPO).
```

2021-06-18 08:48 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-18 10:44 UTC, yogkumgit commented
@msbemba

2021-06-18 17:49 UTC, JohanFreelancer9 approved these changes

2021-06-21 04:09 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-06-29 20:00 UTC, AlexJerabek commented
Pinging this thread to see when this PR will be merged. There's a related customer issue we'd like to close out.

Thanks!

2021-07-05 12:11 UTC, yogkumgit commented
Gentle reminder @kwekuako

2021-07-06 19:06 UTC, merged