Update use-content-search-for-targeted-collections.md
MicrosoftDocs/microsoft-365-docs pull request #5381
Opened 2021-06-22 02:43 UTC by shelri

https://o365exchange.visualstudio.com/Enterprise%20Cloud/_workitems/edit/2159632/

Trailing asterisk is required or the user will not return any results.

2021-06-22 13:31 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-06-23 09:39 UTC, JohanFreelancer9 commented on microsoft-365/compliance/use-content-search-for-targeted-collections.md
>  - This example searches a site folder (and any subfolder) for documents there were changed within a date range.
```suggestion
- This example searches a site folder (and any subfolder) for documents that were changed within a date range.
```

2021-06-23 09:40 UTC, JohanFreelancer9 requested changes
Copy review - @shelri, not related to your PR but could you please also commit my suggested change to fix the typo. Many thanks.

2021-06-24 15:49 UTC, merged

2021-06-24 15:49 UTC, markjjo commented
@shelri PR merged. Thanks for adding this bit.

2021-06-29 13:34 UTC, shelri commented on microsoft-365/compliance/use-content-search-for-targeted-collections.md
>  - This example searches a site folder (and any subfolder) for documents there were changed within a date range.
Will do