Patch 2
MicrosoftDocs/microsoft-365-docs pull request #5386
Opened 2021-06-22 12:02 UTC by panjkov

Updated step 3 to reflect UX of the new admin center.

2021-06-22 13:32 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-06-23 09:25 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-lockbox-requests.md
> +3. Select **Security & Privacy** then click on **Customer Lockbox** in the left column and check the checkbox besides text "Require approval for all data access request" and save changes to turn the
```suggestion
3. Select **Security & Privacy**, then select **Customer Lockbox** in the left column and check the checkbox beside the text "Require approval for all data access requests" and save changes to turn the feature on.
```

2021-06-23 09:27 UTC, JohanFreelancer9 requested changes
Copy review - @panjkov, kindly commit my suggested changes if you agree with them. Many thanks.

2021-06-23 09:30 UTC, panjkov commented
@JohanFreelancer9 in general I agree, but the user does not have option to select "Customer Lockbox", there is only a text they can click.

2021-06-23 09:34 UTC, JohanFreelancer9 approved these changes

2021-06-23 14:37 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2021-07-05 12:12 UTC, yogkumgit commented
Gentle reminder @KCCross kcc

2021-12-06 22:40 UTC, merged