Update office-365-network-mac-perf-overview.md
MicrosoftDocs/microsoft-365-docs pull request #5440
Opened 2021-06-25 17:14 UTC by ivybarley

@jwhit-MSFT In this PR, I added a Note about the use of IPv6 and IPv4 addresses. @pandrew1

2021-06-28 15:27 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-06-29 05:00 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +<<<<<<< Updated upstream
```suggestion
```

2021-06-29 05:01 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +=======
```suggestion
```

2021-06-29 05:05 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +>>>>>>> Stashed changes
```suggestion
> [!NOTE]
> When adding your office locations to Microsoft 365 network connectivity in the Microsoft 365 admin center, you can provide either IPv4 or IPv6 addresses for your LAN subnets. Egress IP addresses must use IPv4.
```

2021-06-29 05:06 UTC, JohanFreelancer9 requested changes
Copy review - @ivybarley, kindly commit the suggested changes. Many thanks.

2021-06-30 03:01 UTC, ivybarley commented
@JohanFreelancer9 I've committed your suggestions. Cc: @pandrew1

2021-06-30 09:18 UTC, JohanFreelancer9 approved these changes

2021-07-01 11:11 UTC, yogkumgit commented
@jwhit-MSFT Please merge this PR. Thanks

2021-07-02 16:35 UTC, ivybarley commented
Asking @LauraWi to merge this PR as Jason is out of office. Thanks. Cc: @pandrew1

2021-07-02 16:55 UTC, merged