Update remove-former-employee-step-2.md
MicrosoftDocs/microsoft-365-docs pull request #5441
Opened 2021-06-25 17:25 UTC by msbemba

Made changes to the version of outlook as we cannot backup data to PST from Web app.

2021-06-25 17:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-06-25 17:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5409

2021-06-26 04:22 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-26 04:23 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-2.md
> +2. Add the former employee's email address to your version of Outlook Desktop app, and then export the data to a .pst file. You can import the data to another email account as needed. Check out [Step
```suggestion
2. Add the former employee's email address to your version of Outlook on Desktop, and then export the data to a .pst file. You can import the data to another email account as needed. Check out [Step 6 - Give another employee access to OneDrive and Outlook data](remove-former-employee-step-6.md).
```

2021-06-28 01:36 UTC, JohanFreelancer9 approved these changes

2021-06-28 12:03 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-06-28 18:09 UTC, merged