Update add-storage-space.md
MicrosoftDocs/microsoft-365-docs pull request #5454
Opened 2021-06-25 20:09 UTC by msbemba

I can see the option to add storage on A3 and A5 faculty at 0.17$ per GB. Made changes to the document accordingly. Please verify and approve.

Thanks
Sri

2021-06-28 12:32 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-06-28 13:01 UTC, msbemba commented
issue#5373

2021-06-28 15:24 UTC, JohanFreelancer9 commented on microsoft-365/commerce/add-storage-space.md
> +- Office 365 A5(faculty)
```suggestion
- Office 365 A3 (faculty)
- Office 365 A5 (faculty)
```

2021-06-28 15:24 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-28 15:28 UTC, yogkumgit commented
@msbemba

2021-06-29 09:21 UTC, JohanFreelancer9 approved these changes

2021-06-29 14:22 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2021-07-01 01:19 UTC, merged