GA for MIP-MCAS integration
MicrosoftDocs/microsoft-365-docs pull request #5473
Opened 2021-06-28 15:11 UTC by idbasre

2021-06-28 15:30 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-06-29 05:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-use-policies-non-microsoft-cloud-apps.md
> +The user who creates the DLP policy should be:
```suggestion
The user who creates the DLP policy should be a:
```

2021-06-29 05:54 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-use-policies-non-microsoft-cloud-apps.md
>  >DLP policies applied to non-Microsoft apps use Microsoft Cloud App Security. When the DLP policy for a non-Microsoft app is created, the same policy will be automatically created in Microsoft Cloud
```suggestion
> [!NOTE]
> DLP policies applied to non-Microsoft apps use Microsoft Cloud App Security. When the DLP policy for a non-Microsoft app is created, the same policy will be automatically created in Microsoft Cloud App Security.
```

2021-06-29 05:55 UTC, JohanFreelancer9 requested changes
Copy review. @idbasre, kindly commit the few minor suggested changes. Many thanks.

2021-06-29 08:05 UTC, idbasre commented
@JohanFreelancer9 I have committed the changes.

2021-06-29 08:10 UTC, JohanFreelancer9 approved these changes

2021-06-29 14:17 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2021-07-06 08:50 UTC, idbasre commented
@chrfox Hi, there is an ETA when it will be done?

2021-07-06 17:06 UTC, merged