Update ediscovery-troubleshooting-common-issues.md
MicrosoftDocs/microsoft-365-docs pull request #5532
Opened 2021-07-02 13:13 UTC by syagey

https://o365exchange.visualstudio.com/Enterprise%20Cloud/_workitems/edit/2139277

We receive multiple escalations for exports stuck where we recommend canceling and re-running the export.  We are attempting to provide additional deflection at the admin center level by suggesting a re-run when they have an export stuck issue.

2021-07-05 12:18 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-05 13:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery-troubleshooting-common-issues.md
> +## Error/issue: Exporting not progressing or stuck
```suggestion
## Error/issue: Exporting not progressing or is stuck
```

2021-07-05 13:10 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery-troubleshooting-common-issues.md
> +Exporting search results from eDiscovery or Content Search in the Security and Compliance Center appear stuck or not progressing.
```suggestion
Exporting search results from eDiscovery or Content Search in the Security and Compliance Center appears stuck or is not progressing.
```

2021-07-05 13:10 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery-troubleshooting-common-issues.md
> +2. Export the content
```suggestion
1. Re-run the search.
2. Export the content.
```

2021-07-05 13:12 UTC, JohanFreelancer9 requested changes
Copy review - @syagey, kindly commit the suggested minor suggested changes. Many thanks.

2021-07-05 16:03 UTC, JohanFreelancer9 approved these changes

2021-07-06 09:18 UTC, yogkumgit commented
@markjjo Please merge this PR. Thanks

2021-07-08 17:41 UTC, merged

2021-07-08 17:42 UTC, markjjo commented
@syagey PR is revised and merged. Can you please sign the contributor agreement? The PR is saying that it need to be signed.