Update configure-advanced-delivery.md
MicrosoftDocs/microsoft-365-docs pull request #5558
Opened 2021-07-06 21:12 UTC by ssaini-pm

Added link to URL syntax format information

2021-07-07 09:00 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-07 11:34 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/configure-advanced-delivery.md
> +   - **Simulation URLs to allow**: Expand this setting and optionally enter specific URLs that are part of your phishing simulation campaign that should not be blocked or detonated by clicking in the
```suggestion
   - **Simulation URLs to allow**: Expand this setting and optionally enter specific URLs that are part of your phishing simulation campaign that should not be blocked or detonated by clicking in the box, entering a value, and then pressing Enter or selecting the value that's displayed below the box. You can add up to 10 entries. For the URL syntax format, see [URL syntax for the Tenant Allow/Block List](/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide#url-syntax-for-the-tenant-allowblock-list).
```

2021-07-07 11:35 UTC, JohanFreelancer9 requested changes
Copy review - @ssaini-pm, kindly commit the suggested changes if you agree with them. Many thanks.

2021-07-08 05:20 UTC, yogkumgit commented
@chrisda please merge this PR. Thanks

2021-07-08 08:19 UTC, JohanFreelancer9 approved these changes

2021-07-12 17:11 UTC, merged