Update set-password-to-never-expire.md
MicrosoftDocs/microsoft-365-docs pull request #5560
Opened 2021-07-06 21:18 UTC by msbemba

Removed the note about the cloud only accounts can have a password expiration policy as synchronized users can have password expiration policies setup on Azure

Reference:- https://dorcs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-password-hash-synchronization#enforcecloudpasswordpolicyforpasswordsyncedusers

2021-07-06 21:18 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-07-06 21:18 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5439

2021-07-07 02:11 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/set-password-to-never-expire.md
```suggestion
```

2021-07-07 02:12 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-07 08:43 UTC, yogkumgit commented
@msbemba

2021-07-07 17:53 UTC, merged