Update data-loss-prevention-policies.md
MicrosoftDocs/microsoft-365-docs pull request #558
Opened 2019-10-15 16:30 UTC by FBrownMSFT

Using labels as conditions does not explain that Exchange and Teams locations are not currently supported.  Customers receive the following error:

"Protecting labeled content in email and teams messages isn't supported. Either remove the label below or turn off Exchange and Teams as a location."

This is because Exchange transport does not evaluate the label metadata during message submission and delivery.

2019-10-15 18:59 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-10-16 01:13 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-loss-prevention-policies.md
> +NOTE:  If you specify a retention label as a condition in a DLP policy, and you also include Exchange and/or Teams as a location you will receive the following error:
```suggestion
> [!NOTE]
> If you specify a retention label as a condition in a DLP policy and you also include Exchange and/or Teams as a location, you will receive the following error:
```

2019-10-16 01:14 UTC, JohanFreelancer9 requested changes
Copy Review - please apply standard NOTE format.

2019-10-16 08:10 UTC, mypil commented
@FBrownMSFT - please merge the commit on the copy/edit review made by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-10-16 14:04 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

2019-10-22 16:53 UTC, merged

2019-10-22 16:54 UTC, chrfox commented
merged