Update use-dkim-to-validate-outbound-email.md
MicrosoftDocs/microsoft-365-docs pull request #5589
Opened 2021-07-09 06:35 UTC by puneethmeister

2021-07-12 16:22 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-13 02:45 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md
> +Disabling the signing policy does not completely disable DKIM. After a period of time, Microsoft 365 will automatically apply the default policy for your domain, if deafult policy is still in enabled
```suggestion
Disabling the signing policy does not completely disable DKIM. After a period of time, Microsoft 365 will automatically apply the default policy for your domain, if the default policy is still in the enabled state. If you wish to completely disable DKIM, you need to disable DKIM on both the custom and default domains. For more information, see [Default behavior for DKIM and Microsoft 365](use-dkim-to-validate-outbound-email.md#DefaultDKIMbehavior).
```

2021-07-13 02:45 UTC, JohanFreelancer9 requested changes
Copy review - @puneethmeister, kindly commit the suggested changes. Many thanks.

2021-07-14 07:29 UTC, puneethmeister commented
@MSFTTracyP Gentle reminder

2021-07-14 07:32 UTC, JohanFreelancer9 approved these changes

2021-07-20 17:36 UTC, MSFTTracyP reviewed
Thanks

2021-07-20 17:37 UTC, merged