Cross-tenant mailbox migration updates
MicrosoftDocs/microsoft-365-docs pull request #5592
Opened 2021-07-09 16:09 UTC by tweekerz

2021-07-12 16:22 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-12 19:13 UTC, JoeDavies-MSFT commented
@tweekerz Can you select "Resolve conflicts" above and remove the old sections where they are marked in the markdown file? Thanks

2021-07-13 06:41 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-mailbox-migration.md
> +    | -ResourceTenantId                           | Tenant ID of the Source tenant. For example, the [Azure AD tenant ID](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-d
```suggestion
    | -ResourceTenantId                           | Tenant ID of the Source tenant. For example, the [Azure AD tenant ID](/azure/active-directory/fundamentals/active-directory-how-to-find-tenant) of contoso\.onmicrosoft.com tenant.                                                                 | Required             |
```

2021-07-13 06:45 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-mailbox-migration.md
> +    | -CertificateName                            | Certificate name when generating or searching for certificate in key vault.
```suggestion
    | -CertificateName                            | Certificate name when generating or searching for certificate in Key Vault.                                                                                                                                                                                                         | Required             |
```

2021-07-13 06:45 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-mailbox-migration.md
> +    | -AzureResourceLocation                      | The location (Display Name) of the Azure resource group and key vault. You can run `Get-AzResourceProvider -ProviderNamespace Microsoft.KeyVault |
```suggestion
    | -AzureResourceLocation                      | The location (Display Name) of the Azure resource group and Key Vault. You can run `Get-AzResourceProvider -ProviderNamespace Microsoft.KeyVault | Select-Object -ExpandProperty Locations -Unique` to see the available names.                                                     | Required             |
```

2021-07-13 06:47 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-mailbox-migration.md
> +    | -TargetTenantId                   | Tenant ID of the target tenant. For example, the [Azure AD tenant ID](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-h
```suggestion
    | -TargetTenantId                   | Tenant ID of the target tenant. For example, the [Azure AD tenant ID](/azure/active-directory/fundamentals/active-directory-how-to-find-tenant) of fabrikam\.onmicrosoft.com tenant.  |
```

2021-07-13 06:50 UTC, JohanFreelancer9 requested changes
Copy review - @tweekerz, kindly commit the suggested changes.

2021-07-14 23:05 UTC, tweekerz commented
@JoeDavies-MSFT @JohanFreelancer9 I have resolved as requested, ping me on teams if you need anything else. Thanks!!!

2021-07-15 05:36 UTC, JohanFreelancer9 commented
@tweekerz - It seems that my suggested changes (including changing links to relative links) have not actually been committed. Could you please check and confirm? Many thanks.

2021-07-26 10:35 UTC, yogkumgit commented
@tweekerz Please resolve this conflict.

2021-08-02 11:11 UTC, yogkumgit commented
@tweekerz Please resolve.

2021-09-19 14:48 UTC, yogkumgit commented
@tiburd

2021-09-21 04:16 UTC, tweekerz commented
I have resolved all changes back in July there is no further actions I can take, the only option I have is to unresolve. Please push the changes.

2021-09-21 13:28 UTC, yogkumgit commented
@JohanFreelancer9

2021-09-21 14:56 UTC, JohanFreelancer9 commented
@yogkumgit @yogkumgit - My suggestions have been marked as resolved, but they have not been committed. Unfortunately, I cannot commit them - they need to be committed by the PR author or person who merges the PR (to commit the change in its own commit, click "Commit suggestion").

2021-09-21 16:48 UTC, merged