Update updates.md
MicrosoftDocs/microsoft-365-docs pull request #5613
Opened 2021-07-13 20:01 UTC by sh783

Updated cadence from 0 0 0 3 to 0 0 0 7, per the change that finished deploying this week. Also added clarity around device restart expectations.

2021-07-14 07:18 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-14 08:05 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/updates.md
> +    - Example: if an issue is discovered while deploying a quality update to the First group, then update deployments to First, Fast, and Broad will all be paused until the issue is mitigated.
```suggestion
    - Example: If an issue is discovered while deploying a quality update to the First group, then update deployments to First, Fast, and Broad will all be paused until the issue is mitigated.
```

2021-07-14 08:13 UTC, JohanFreelancer9 requested changes
Copy review - @sh783, kindly commit the additional minor suggested change. Many thanks.

2021-07-19 07:20 UTC, yogkumgit commented
@sh783 Please implement the suggested changes. Thanks

2021-07-19 18:57 UTC, sh783 commented
@yogkumgit suggested change committed.

2021-07-20 01:24 UTC, JohanFreelancer9 approved these changes

2021-07-20 22:50 UTC, sh783 commented
@JohanFreelancer9 can we please merge this today? We're getting questions about this inconsistent documentation.

2021-07-21 07:32 UTC, JohanFreelancer9 commented
@yogkumgit

2021-07-22 05:10 UTC, yogkumgit commented
@jaimeo Please merge this PR. Thanks.

2021-07-22 17:42 UTC, sh783 commented
Pretty sure that Jaime is still on vacation. Who is handling this in his absence?


From: Yogesh Kumar ***@***.***>
Sent: Wednesday, July 21, 2021 10:10 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Steve Henry (MMD) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update updates.md (#5613)


@jaimeo<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjaimeo&data=04%7C01%7Cshenry%40microsoft.com%7Cec5fb147ff344e701f2308d94ccf037f%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637625274279294826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n9EnDKL8jT8UzAOetX9ZKtMX0Ba849S8abRnna0Ip%2BE%3D&reserved=0> Please merge this PR. Thanks.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F5613%23issuecomment-884659473&data=04%7C01%7Cshenry%40microsoft.com%7Cec5fb147ff344e701f2308d94ccf037f%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637625274279304817%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DXX4fUXZmhhPc09INhm%2FutiSZsiiXZ%2B6nShgUKbpirE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOVU6FCZNFO6PC4PFCW54JLTY6R4BANCNFSM5AKA3DIQ&data=04%7C01%7Cshenry%40microsoft.com%7Cec5fb147ff344e701f2308d94ccf037f%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637625274279304817%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9P%2BU%2FZviyeuXHJNufsZSSm7vcS1trU7B28SwiE3dMlY%3D&reserved=0>.

2021-07-27 16:59 UTC, merged