Update register-devices-partner.md
MicrosoftDocs/microsoft-365-docs pull request #5639
Opened 2021-07-16 08:49 UTC by msbemba

Both the scripts are similar and it works for partners as well - So removed the part "he Windows PowerShell script is different from the one used for the Microsoft Managed Desktop Admin portal." from not. 

Also added a note about editing the file in excel and saving as a CSV will not generate a usable file -Extra columns are not supported. Quotes are not supported. Only ANSI-format text files can be used (not Unicode). Headers are case-sensitive. Editing the file in Excel and saving as a CSV file will not generate a usable file due to these requirements.

2021-07-16 08:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-07-16 08:50 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5506

2021-07-16 15:45 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/get-started/register-devices-partner.md
> +> You should have received this .csv file with your device purchase. If you didn't receive a .csv file, you can create one yourself by following the steps in [Adding devices to Windows Autopilot](/wi
```suggestion
> You should have received this .csv file with your device purchase. If you didn't receive a .csv file, you can create one yourself by following the steps in [Adding devices to Windows Autopilot](/windows/deployment/windows-autopilot/add-devices#collecting-the-hardware-id-from-existing-devices-using-powershell). Extra columns are not supported. Quotes are not supported. Only ANSI-format text files can be used (not Unicode). Headers are case-sensitive. Editing the file in Excel and saving it as a CSV file will not generate a usable file due to these requirements. Please make sure that any leading zeroes are preserved in the device serial numbers. Partners should use [Get-WindowsAutoPilotInfo](https://www.powershellgallery.com/packages/Get-WindowsAutoPilotInfo) to register devices for Microsoft Managed Desktop devices in Partner Center.
```

2021-07-16 15:46 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-16 16:52 UTC, JohanFreelancer9 approved these changes

2021-07-19 07:25 UTC, yogkumgit commented
@jaimeo Please merge this PR. Thanks

2021-07-27 17:39 UTC, jaimeo commented
@msbemba @JohanFreelancer9 : we do not use "please."

2021-07-27 17:40 UTC, jaimeo commented
@jwmurraycmu are you OK with these edits w/r/t technical accuracy?

2021-07-27 17:52 UTC, jaimeo commented
@AlexBlain are you OK with these edits w/r/t technical accuracy?

2021-07-27 18:29 UTC, AlexBlain commented
@jaimeo fine with that

2021-07-28 13:17 UTC, merged