Update control-usb-devices-using-intune.md
MicrosoftDocs/microsoft-365-docs pull request #5641
Opened 2021-07-16 09:31 UTC by msbemba

Removed the Endpoint ATP baseline settings to control removable storage as Device control is no longer a part of baseline settings.

2021-07-16 09:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-07-16 09:32 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5458

2021-07-16 15:56 UTC, JohanFreelancer9 reviewed
Should "Use Microsoft Defender for Endpoint baseline settings" not be removed from the preceding table as well?

2021-07-16 16:05 UTC, msbemba commented
@JohanFreelancer9  Thank you. Could you please copy review again?

2021-07-16 16:56 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/control-usb-devices-using-intune.md
> +
```suggestion
```

2021-07-16 16:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-18 14:15 UTC, JohanFreelancer9 approved these changes

2021-07-19 07:29 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2021-07-30 06:08 UTC, yogkumgit commented
@Dansimp Gentle reminder

2021-08-02 11:12 UTC, yogkumgit commented
@Dansimp Gentle reminder.

2021-08-05 18:10 UTC, merged