update documentation with MAM and minor enhancements
MicrosoftDocs/microsoft-365-docs pull request #5657
Opened 2021-07-18 16:13 UTC by sunasing

2021-07-18 16:15 UTC, sunasing commented
#sign-off

2021-07-19 07:31 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-19 07:54 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-install-unmanaged.md
> +> Defender for Endpoint on iOS would use a VPN in order to provide the Web Protection feature. This is not a regular VPN and is a local/self-looping VPN that does not take traffic outside the device.
```suggestion
> Defender for Endpoint on iOS uses a VPN in order to provide the Web Protection feature. This is not a regular VPN and is a local/self-looping VPN that does not take traffic outside the device.
```

2021-07-19 07:55 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-install-unmanaged.md
> +Steps to setup app protection policies with Microsoft Defender for Endpoint are as below:
```suggestion
Steps to setup app protection policies with Microsoft Defender for Endpoint are as follows:
```

2021-07-19 07:56 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-install-unmanaged.md
> +1. Select Save. You should see **Connection status** is now set to **Enabled**.
```suggestion
1. Select **Save**. You should see **Connection status** is now set to **Enabled**.
```

2021-07-19 07:58 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-install-unmanaged.md
> +1. Create app protection policy: After your Microsoft Defender for Endpoint connector setup is complete, navigate to **Apps** > **App protection policies** (under Policy) to create a new policy or up
```suggestion
1. Create the app protection policy: After your Microsoft Defender for Endpoint connector setup is complete, navigate to **Apps** > **App protection policies** (under Policy) to create a new policy or update an existing one.
```

2021-07-19 08:02 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-install-unmanaged.md
> +1. Under **Conditional launch** > **Device conditions**, you will find the setting **Max allowed device threat level**. This will need to be configured to either Low, Medium, High, or Secured. The ac
```suggestion
1. Under **Conditional launch** > **Device conditions**, you will find the setting **Max allowed device threat level**. This needs to be configured to either Low, Medium, High, or Secured. The actions available to you will be **Block access** or **Wipe data**. You may see an informational dialog to make sure you have your connector set up prior to this setting taking effect. If your connector is already set up, you may ignore this dialog.
```

2021-07-19 08:05 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-install-unmanaged.md
> +Microsoft Defender for Endpoint on iOS enables the App Protection Policy scenario and is available in the Apple app store.
```suggestion
Microsoft Defender for Endpoint on iOS enables the app protection policy scenario and is available in the Apple app store.
```

2021-07-19 08:06 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-install-unmanaged.md
> +When app protection policies are configured for apps to include device risk signals from Microsoft Defender for Endpoint, user will be redirected to install Microsoft Defender for Endpoint when using
```suggestion
When app protection policies are configured for apps to include device risk signals from Microsoft Defender for Endpoint, users will be redirected to install Microsoft Defender for Endpoint when using such apps. Alternately, users can also install the latest version of the app directly from the Apple app store.
```

2021-07-19 08:11 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/ios-install-unmanaged.md
> +Microsoft Defender for Endpoint can be configured to send threat signals to be used in App Protection Policies (APP, also known as MAM) on iOS/iPadOS. With this capability, you can use Microsoft Defe
```suggestion
Microsoft Defender for Endpoint can be configured to send threat signals to be used in app protection policies (APP, also known as MAM) on iOS/iPadOS. With this capability, you can use Microsoft Defender for Endpoint to protect access to corporate data from unenrolled devices as well.
```

2021-07-19 08:17 UTC, JohanFreelancer9 requested changes
Copy review - @sunasing, kindly commit the minor suggested edits if you agree with them. Many thanks.

2021-07-19 16:29 UTC, merged