Update ome-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #5669
Opened 2021-07-19 21:33 UTC by samschan-ms

Updated delegate access doc

@KCCross please review and merge

2021-07-20 10:32 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-20 11:12 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          Is delegated access supported with opening encrypted messages? Even if delegate has Fullaccess on another user's mailbox?
```suggestion
          Is delegated access supported by opening encrypted messages? Even if a delegate has full access to another user's mailbox?
```

2021-07-20 11:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          Delegate access of encrypted mail is supported in Outlook on the web, Outlook for Mac, Outlook for iOS, and Outlook for Android.  Outlook for Windows do not support delegate access.
```suggestion
          Delegate access of encrypted mail is supported in Outlook on the web, Outlook for Mac, Outlook for iOS, and Outlook for Android.  Outlook for Windows do not support delegate access.
```
```suggestion
          Delegated access of encrypted mail is supported in Outlook on the web, Outlook for Mac, Outlook for iOS, and Outlook for Android.  Outlook for Windows does not support delegated access.
```

2021-07-20 11:15 UTC, JohanFreelancer9 requested changes
Copy review - @samschan-ms, kindly commit the suggested changes. Many thanks.

2021-07-21 03:53 UTC, JohanFreelancer9 approved these changes

2021-07-21 07:09 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2021-07-28 19:44 UTC, merged