Update about-shared-mailboxes.md
MicrosoftDocs/microsoft-365-docs pull request #5672
Opened 2021-07-20 08:11 UTC by guruxp

added a change on the Too Many Users section so we state no more than 25 users is recommended per shared mailbox concurrently. This will help customers better plan their needs, avoid unnecessary cases from being opened and have an article we can answer from support regarding what shared mailboxes are for in terms of sizing.

2021-07-20 10:32 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-20 11:24 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/about-shared-mailboxes.md
> +- **Too many users:** When there are too many designated users concurrently accessing a shared mailbox (no more than 25 is recommended), they may intermittently fail to connect to this mailbox or hav
```suggestion
- **Too many users:** When there are too many designated users concurrently accessing a shared mailbox (no more than 25 is recommended), they may intermittently fail to connect to this mailbox or have inconsistencies like messages being duplicated in the outbox. In this case, you can consider reducing the number of users or using a different workload, such as a Microsoft 365 group or a Public folder.
```

2021-07-20 11:27 UTC, JohanFreelancer9 requested changes
Copy review - @guruxp, kindly commit the suggested changes. Many thanks.

2021-07-20 12:35 UTC, guruxp commented
@JohanFreelancer9 done :) thanks

2021-07-21 02:29 UTC, JohanFreelancer9 approved these changes

2021-07-21 06:31 UTC, guruxp commented
@JohanFreelancer9 do you know when this will go public?

2021-07-21 06:53 UTC, merged