Update overview-security-center.md
MicrosoftDocs/microsoft-365-docs pull request #5676
Opened 2021-07-20 14:29 UTC by msbemba

Changed the wordings from Send us your feedback to Watch this video to find out how you can trust us to read your feedback, as the video talks about what Microsoft accepts and uses the feedback and it is not a link to leave feedback.

2021-07-20 14:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-07-20 14:29 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5647

2021-07-21 03:39 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/overview-security-center.md
> +We need your feedback. We're always looking to improve, so if there's something you'd like to see, [Watch this video to find out how you can trust us to read your feedback.](https://www.microsoft.com
```suggestion
We need your feedback. We're always looking to improve, so if there's something you'd like to see, [watch this video to find out how you can trust us to read your feedback](https://www.microsoft.com/videoplayer/embed/RE4K5Ci).
```

2021-07-21 03:39 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-21 07:19 UTC, yogkumgit commented
@JohanFreelancer9

2021-07-21 08:20 UTC, JohanFreelancer9 approved these changes

2021-07-22 05:12 UTC, yogkumgit commented
@MSFTTracyP Please merge this Pr. Thanks.

2021-07-30 06:09 UTC, yogkumgit commented
@MSFTTracyP Gentle reminder

2021-11-13 00:38 UTC, chrisda commented
Need to close this PR because the original file was renamed or moved (merge conflicts).

2021-11-13 00:38 UTC, closed without merging