Update per-group-guest-access.md
MicrosoftDocs/microsoft-365-docs pull request #5713
Opened 2021-07-22 16:18 UTC by msbemba

Added a script to toggle back to allow guest access to the group.

I don't think pertains to the subject of the document, however, this is definitely good information for users who read and want to know how to toggle back.

2021-07-22 16:18 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-07-22 16:18 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5667

2021-07-26 07:17 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-26 08:16 UTC, JohanFreelancer9 commented on microsoft-365/solutions/per-group-guest-access.md
> +If you wish to toggle the setting back to allow guest access to a particular group, Run the following script, changing */<GroupName/>* to the name of the group where you want to allow guest access.
```suggestion
If you wish to toggle the setting back to allow guest access to a particular group, run the following script, changing */<GroupName/>* to the name of the group where you want to allow guest access.
```

2021-07-26 08:16 UTC, JohanFreelancer9 requested changes
Copy review.

2021-07-26 08:46 UTC, JohanFreelancer9 commented on microsoft-365/solutions/per-group-guest-access.md
> +If you wish to toggle the setting back to allow guest access to a particular group, run the following script, changing */<GroupName/>* to the name of the group where you want to allow guest access.
```suggestion
If you wish to toggle the setting back to allow guest access to a particular group, run the following script, changing ```<GroupName>``` to the name of the group where you want to allow guest access.
```

2021-07-26 08:48 UTC, JohanFreelancer9 requested changes
Apologies, @msbemba, looking at the rich diff view, I have noticed that this element does not display correctly, so this is my suggestion to correct it. The same correction also needs to be applied to line 42. Many thanks.

2021-07-26 12:29 UTC, msbemba commented
@JohanFreelancer9  I shall check line 42 and update if need be.

2021-07-26 13:58 UTC, JohanFreelancer9 approved these changes
@msbemba - Thank you.

2021-07-27 04:38 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-07-27 12:37 UTC, merged