Update remove-former-employee-step-1.md
MicrosoftDocs/microsoft-365-docs pull request #5719
Opened 2021-07-23 02:57 UTC by robertkruk

Updated steps to align more with "the New Exchange admin center"

2021-07-26 10:38 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-26 13:06 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-1.md
> +3. Select the user mailbox from the list and then in the *Details Pane* (on the right hand side), click on **Manage email apps settings** under **Email apps**. Turn **Off** the slider for all the opt
```suggestion
3. Select the user mailbox from the list and then, in the *Details Pane* (on the right-hand side), select **Manage email apps settings** under **Email apps**. Turn **Off** the slider for all the options; **Mobile (Exchange ActiveSync)**, **Outlook on the web**, **Outlook desktop (MAPI)**, **Exchange web services**, **POP3**, and **IMAP**.
```

2021-07-26 13:06 UTC, JohanFreelancer9 requested changes
Copy review - @robertkruk, kindly commit the minor suggested changes. Many thanks.

2021-07-28 04:10 UTC, JohanFreelancer9 approved these changes

2021-07-28 08:11 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-07-28 15:25 UTC, merged