Update operations-and-monitoring.md
MicrosoftDocs/microsoft-365-docs pull request #5754
Opened 2021-07-27 18:03 UTC by rekhanr

Updated the section Device Groups, to add the link to the new feature and update responsibilities for both Microsoft and customer.

2021-07-28 08:34 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-28 11:03 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/operations-and-monitoring.md
> +Device Groups | - Implement and assign the membership of devices within Microsoft Managed Desktop groups.<br>- Use the Microsoft Managed Desktop groups to manage the assignment and release of configu
```suggestion
Device Groups | - Implement and assign the membership of devices within Microsoft Managed Desktop groups.<br>- Use the Microsoft Managed Desktop groups to manage the assignment and release of configuration and updates to devices. | - Create a support request requesting information for a planned configuration change, including configuration details, scope, timeline, and other pertinent details for Microsoft to review.<br>- Only apply a change once Microsoft Managed Desktop Operations has assessed and advised.<br>- Only assign devices to any Microsoft Managed Desktop group following the steps described in [Assign devices to a deployment group](https://docs.microsoft.com/microsoft-365/managed-desktop/working-with-managed-desktop/assign-deployment-group?view=o365-worldwide).<br>- Only use the groups to assign corporate certificates for services such as VPN, Windows Hello for Business or email encryption, or corporate Wi-Fi profile configuration.<br>- Where co-management exists, explicitly exclude all Microsoft Managed Desktop groups when deploying the Configuration Manager client.
```

2021-07-28 11:06 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/operations-and-monitoring.md
> +Device Groups | - Implement and assign the membership of devices within Microsoft Managed Desktop groups.<br>- Use the Microsoft Managed Desktop groups to manage the assignment and release of configu
Please change the line "Only assign devices to any of Microsoft Managed Desktop group, following the steps..." to "Only assign devices to any Microsoft Managed Desktop group following the steps..." (delete the word "of" and the comma).

2021-07-28 11:08 UTC, JohanFreelancer9 requested changes
Copy review - @rekhanr, kindly commit the suggested change. Many thanks.

2021-07-28 16:08 UTC, rekhanr commented
@jaimeo FYI.

2021-07-29 06:17 UTC, JohanFreelancer9 approved these changes

2021-07-29 07:56 UTC, yogkumgit commented
@jaimeo Please merge this PR. Thanks

2021-07-29 10:53 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/operations-and-monitoring.md
> +Device Groups | - Implement and assign the membership of devices within Microsoft Managed Desktop groups.<br>- Use the Microsoft Managed Desktop groups to manage the assignment and release of configu
```suggestion
Device Groups | - Implement and assign the membership of devices within Microsoft Managed Desktop groups.<br>- Use the Microsoft Managed Desktop groups to manage the assignment and release of configuration and updates to devices. | - Create a support request requesting information for a planned configuration change, including configuration details, scope, timeline, and other pertinent details for Microsoft to review.<br>- Only apply a change once Microsoft Managed Desktop Operations has assessed and advised.<br>- Only assign devices to any Microsoft Managed Desktop group following the steps described in [Assign devices to a deployment group](/microsoft-365/managed-desktop/working-with-managed-desktop/assign-deployment-group?view=o365-worldwide).<br>- Only use the groups to assign corporate certificates for services such as VPN, Windows Hello for Business or email encryption, or corporate Wi-Fi profile configuration.<br>- Where co-management exists, explicitly exclude all Microsoft Managed Desktop groups when deploying the Configuration Manager client.
```

2021-07-29 10:55 UTC, JohanFreelancer9 requested changes
Apologies @rekhanr - please also change the link to a relative link as indicated. Should be (/microsoft-365/managed-desktop/working-with-managed-desktop/assign-deployment-group?view=o365-worldwide). Thank you.

2021-07-29 15:44 UTC, rekhanr commented
Thank you. FYI @jaimeo .

2021-07-29 17:04 UTC, jaimeo commented
@JohanFreelancer9 that is not the correct link format for links between articles in the same repo. I've corrected it.

2021-07-29 17:04 UTC, merged