update PBI metrics definition
MicrosoftDocs/microsoft-365-docs pull request #5768
Opened 2021-07-29 11:10 UTC by sarahwxy

- corrected ODB metrics 
- added the table for tenant office licenses

2021-07-30 06:13 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-07-31 09:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/usage-analytics-data-model.md
>  |SPO_GroupFileViewedModified  <br/> |Number of files with this user interacted on any group site.  <br/> |
```suggestion
|SPO_GroupFileViewedModified  <br/> |Number of files with this user interacted with on any group site.  <br/> |
```

2021-07-31 09:19 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/usage-analytics-data-model.md
> +|AssignedCount  <br/> |Number of assigned license.  <br/> |
```suggestion
|AssignedCount  <br/> |Number of assigned licenses.  <br/> |
```

2021-07-31 09:23 UTC, JohanFreelancer9 requested changes
Copy review - @sarahwxy, kindly commit the suggested changes. Many thanks.

2021-08-02 05:17 UTC, yogkumgit commented
@sarahwxy Please implement the suggested changes. Thanks

2021-08-03 06:45 UTC, JohanFreelancer9 commented on microsoft-365/admin/usage-analytics/usage-analytics-data-model.md
> +|SPO_GroupFileViewedModified  <br/> |Number of files with this user interacted with on any group site.  <br/> |
```suggestion
|SPO_GroupFileViewedModified  <br/> |Number of files this user interacted with on any group site.  <br/> |
```

2021-08-03 06:47 UTC, JohanFreelancer9 requested changes
@sarahwxy - apologies, my bad. Please commit the additional edit. Many thanks.

2021-08-03 07:29 UTC, sarahwxy commented
> @sarahwxy - apologies, my bad. Please commit the additional edit. Many thanks.

2021-08-03 07:29 UTC, sarahwxy commented
no worries, committed!

2021-08-03 07:39 UTC, JohanFreelancer9 approved these changes

2021-08-04 11:14 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2021-08-26 10:40 UTC, yogkumgit commented
@efrene Gentle reminder

2021-08-26 16:34 UTC, merged