Update set-password-expiration-policy.md
MicrosoftDocs/microsoft-365-docs pull request #5781
Opened 2021-07-30 13:26 UTC by msbemba

Added a note about Password reset notifications retired per MC219002

2021-07-31 09:00 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5744

2021-07-31 09:00 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-07-31 09:57 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/set-password-expiration-policy.md
> +> Password Expiration Notifications are no longer supported in Office Portal or any Office apps except outlook.
```suggestion
> Password expiration notifications are no longer supported in the Office 365 portal or any Office apps except Outlook.
```

2021-07-31 09:58 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, kindly commit the suggested changes. Many thanks.

2021-07-31 10:03 UTC, JohanFreelancer9 approved these changes

2021-08-02 05:13 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-08-09 21:14 UTC, merged