Update configure-proxy-internet.md
MicrosoftDocs/microsoft-365-docs pull request #5792
Opened 2021-07-31 09:13 UTC by msbemba

Added more information about what URL's to open in firewall.

2021-07-31 09:13 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-07-31 09:13 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5751

2021-07-31 10:02 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-proxy-internet.md
> +In your firewall, open all the URLs where the geography column is WW. For rows where the geography column is not WW, open the URLs to your specific data location. [You can verify your data location s
```suggestion
In your firewall, open all the URLs where the geography column is WW. For rows where the geography column is not WW, open the URLs to your specific data location. [You can verify your data location setting here](/microsoft-365/security/defender-endpoint/data-retention-settings).
```

2021-07-31 10:02 UTC, JohanFreelancer9 requested changes
Copy review. @msbemba, kindly commit the suggested change. Many thanks.

2021-08-02 05:15 UTC, yogkumgit commented
@msbemba

2021-08-02 11:16 UTC, yogkumgit commented
@JohanFreelancer9

2021-08-02 11:44 UTC, JohanFreelancer9 approved these changes

2021-08-02 17:41 UTC, merged