Update enable-the-report-message-add-in.md
MicrosoftDocs/microsoft-365-docs pull request #5795
Opened 2021-08-02 10:42 UTC by guruxp

Added the necessary endpoints for the add-in to work behind a proxy.

2021-08-02 11:17 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-08-02 11:32 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/enable-the-report-message-add-in.md
> +- For organizations that have a URL filtering or security solution in place (i.e. Proxy, FireWall, etc) you will need to have ipagave.azurewebsites.net and outlook.office.com endpoints allowed to be
```suggestion
- Organizations that have a URL filtering or security solution (such as Proxy and FireWall)  in place will need to have ipagave.azurewebsites.net and outlook.office.com endpoints allowed to be reached on HTTPS protocol.
```

2021-08-02 11:34 UTC, JohanFreelancer9 requested changes
Copy review - @guruxp, kindly commit the suggested change. Many thanks.

2021-08-02 11:35 UTC, guruxp commented
@JohanFreelancer9 proposed changes committed :)

2021-08-02 11:37 UTC, JohanFreelancer9 approved these changes

2021-08-02 11:40 UTC, guruxp commented
@yogkumgit could you please proceed with the merge?

2021-08-03 04:30 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2021-08-03 09:54 UTC, merged