Update configure-endpoints-gp.md
MicrosoftDocs/microsoft-365-docs pull request #5796
Opened 2021-08-02 10:51 UTC by msbemba

Updated the doc as environments that have NTLM disabled will have problems using the NetBIOS name.

2021-08-02 10:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-02 10:52 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5787

2021-08-02 11:00 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5785

2021-08-02 13:41 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-endpoints-gp.md
> +8. In the Name field, type an appropriate name for the scheduled task (e.g., Defender for Endpoint Deployment).
```suggestion
8. In the Name field, type an appropriate name for the scheduled task (for example, Defender for Endpoint Deployment).
```

2021-08-02 13:47 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-endpoints-gp.md
> +9. Go to the **Actions** tab and click **New...** Ensure that **Start a program** is selected in the **Action** field. Enter the UNC path, using the file server's fully qualified domain name (FQDN),
```suggestion
9. Go to the **Actions** tab and select **New...** Ensure that **Start a program** is selected in the **Action** field. Enter the UNC path using the file server's fully qualified domain name (FQDN) of the shared *WindowsDefenderATPOnboardingScript.cmd* file.
```

2021-08-02 13:47 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-endpoints-gp.md
> +10. Click **OK** and close any open GPMC windows.
```suggestion
10. Select **OK** and close any open GPMC windows.
```

2021-08-02 13:49 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-endpoints-gp.md
> +8. In the Name field, type an appropriate name for the scheduled task (e.g., Defender for Endpoint Deployment).
```suggestion
8. In the Name field, type an appropriate name for the scheduled task (for example, Defender for Endpoint Deployment).
```

2021-08-02 13:51 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-endpoints-gp.md
> +9. Go to the **Actions** tab and click **New...**. Ensure that **Start a program** is selected in the **Action** field. Enter the UNC path, using the file server's fully qualified domain name (FQDN),
```suggestion
9. Go to the **Actions** tab and select **New...**. Ensure that **Start a program** is selected in the **Action** field. Enter the UNC path, using the file server's fully qualified domain name (FQDN), of the shared *WindowsDefenderATPOffboardingScript_valid_until_YYYY-MM-DD.cmd* file.
```

2021-08-02 13:52 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-endpoints-gp.md
> +10. Click **OK** and close any open GPMC windows.
```suggestion
10. Select **OK** and close any open GPMC windows.
```

2021-08-02 13:54 UTC, JohanFreelancer9 requested changes
Copy review. @msbemba, kindly commit the suggested changes. Many thanks.

2021-08-02 14:30 UTC, JohanFreelancer9 approved these changes

2021-08-03 04:16 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-08-03 19:43 UTC, merged