Update allowselfservicepurchase-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #5834
Opened 2021-08-03 17:59 UTC by msbemba

Added an additional note about running the command individually fr each value if there are multiple values for $product

2021-08-03 17:59 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5757

2021-08-03 17:59 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-04 04:22 UTC, JohanFreelancer9 commented on microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md
> +If there are multiple values for the product, you can run the command individually for each value like this.
```suggestion
If there are multiple values for the product, you can run the command individually for each value as follows:
```

2021-08-04 04:22 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-04 12:01 UTC, yogkumgit commented
@msbemba

2021-08-04 13:03 UTC, JohanFreelancer9 approved these changes

2021-08-05 07:23 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2021-08-17 23:08 UTC, merged