Update machineaction.md
MicrosoftDocs/microsoft-365-docs pull request #6034
Opened 2021-08-17 06:17 UTC by msbemba

Updated values for Type and status.

Additionally, the following fields are  documented 
lastUpdateDateTimeUtc
title
cancellationRequestor
cancellationComment
cancellationDateTimeUtc
requestSource

I do not have the exact description for the below ones. But we still need to add them, could you please help?

commands
troubleshootInfo
errorHResult
externalId

2021-08-17 06:17 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-17 06:17 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5896

2021-08-17 09:41 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/machineaction.md
> +|type|Enum|Type of the action. Possible values are: "RunAntiVirusScan", "Offboard", "Live Response" "CollectInvestigationPackage", "Isolate", "Unisolate", "StopAndQuarantineFile", "RestrictCodeExecut
```suggestion
|type|Enum|Type of the action. Possible values are: "RunAntiVirusScan", "Offboard", "Live Response", "CollectInvestigationPackage", "Isolate", "Unisolate", "StopAndQuarantineFile", "RestrictCodeExecution", and "UnrestrictCodeExecution."|
```

2021-08-17 09:42 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/machineaction.md
> +|cancellationRequestor|String|Identity of the person that Cancelled the action.|
```suggestion
|cancellationRequestor|String|Identity of the person that canceled the action.|
```

2021-08-17 09:43 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/machineaction.md
> +|cancellationComment|String|Comment that was written when Cancelling the action.|
```suggestion
|cancellationComment|String|Comment that was written when canceling the action.|
```

2021-08-17 09:43 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/machineaction.md
> +|status|Enum|Current status of the command. Possible values are: "Pending", "InProgress", "Succeeded", "Failed", "TimeOut" and "Cancelled".|
```suggestion
|status|Enum|Current status of the command. Possible values are: "Pending", "InProgress", "Succeeded", "Failed", "TimeOut", and "Cancelled".|
```

2021-08-17 09:44 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/machineaction.md
> +|cancellationDateTimeUtc|DateTimeOffset|The date and time when the action was Cancelled.|
```suggestion
|cancellationDateTimeUtc|DateTimeOffset|The date and time when the action was canceled.|
```

2021-08-17 09:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/machineaction.md
>  |relatedFileInfo|Class|Contains two Properties. string `fileIdentifier`, Enum `fileIdentifierType` with the possible values: "Sha1", "Sha256" and "Md5".|
```suggestion
|relatedFileInfo|Class|Contains two Properties. string `fileIdentifier`, Enum `fileIdentifierType` with the possible values: "Sha1", "Sha256", and "Md5".|
```

2021-08-17 09:46 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-17 14:42 UTC, yogkumgit commented
@JohanFreelancer9

2021-08-18 08:59 UTC, JohanFreelancer9 approved these changes

2021-08-18 21:53 UTC, mjcaparas commented
@msbemba 
for now, exclude:
troubleshootInfo
errorHResult

externalID:
type: String
Description: Is Id the customer can submit in the request for custom correlation


commands:
relevant only for action https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-live-response?view=o365-worldwide. 
Those are the commands the customer wants to run using this action. (I guess you can just point to there)

2021-08-23 13:08 UTC, msbemba commented
Thank you @mjcaparas. I have updated the two fields.

2021-08-23 15:29 UTC, merged