Update get-assessment-methods-properties.md
MicrosoftDocs/microsoft-365-docs pull request #6035
Opened 2021-08-17 06:27 UTC by msbemba

Updated properties  and added rbacGroupId and os version

2021-08-17 06:27 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-17 06:27 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5877

2021-08-17 09:32 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/get-assessment-methods-properties.md
> +configurationName|string|Display name of the configuration
```suggestion
configurationCategory|string|Category or grouping to which the configuration belongs: Application, OS, Network, Accounts, Security controls.
configurationId|string|Unique identifier for a specific configuration.
configurationImpact|string|Rated impact of the configuration to the overall configuration score (1-10).
configurationName|string|Display name of the configuration.
```

2021-08-17 09:34 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/get-assessment-methods-properties.md
> +isExpectedUserImpact|bool|Indicates whether there will be user impact if the configuration will be applied
```suggestion
isApplicable|bool|Indicates whether the configuration or policy is applicable.
isCompliant|bool|Indicates whether the configuration or policy is properly configured.
isExpectedUserImpact|bool|Indicates whether there will be user impact if the configuration will be applied.
```

2021-08-17 09:35 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/get-assessment-methods-properties.md
> +osPlatform|string|Platform of the operating system running on the device. This indicates specific operating systems, including variations within the same family, such as Windows 10 and Windows 7. See
```suggestion
osPlatform|string|Platform of the operating system running on the device. This indicates specific operating systems, including variations within the same family, such as Windows 10 and Windows 7. See TVM supported operating systems and platforms for details.
```

2021-08-17 09:35 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/get-assessment-methods-properties.md
> +timestamp|string|Last time the configuration was seen on the device
```suggestion
timestamp|string|Last time the configuration was seen on the device.
```

2021-08-17 09:37 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/get-assessment-methods-properties.md
>  NumberOfWeaknesses|int|Number of weaknesses on this software on this device
```suggestion
NumberOfWeaknesses|int|Number of weaknesses on this software on this device.
```

2021-08-17 09:38 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/get-assessment-methods-properties.md
>  RecommendedSecurityUpdateId|string|Identifier of the applicable security updates or identifier for the corresponding guidance or knowledge base (KB) articles
```suggestion
RecommendedSecurityUpdateId|string|Identifier of the applicable security updates or identifier for the corresponding guidance or knowledge base (KB) articles.
```

2021-08-17 09:38 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-17 10:32 UTC, yogkumgit commented
@msbemba Please copy review

2021-08-17 13:27 UTC, yogkumgit commented
@JohanFreelancer9

2021-08-17 15:04 UTC, JohanFreelancer9 approved these changes

2021-08-18 06:14 UTC, yogkumgit commented
@jweston-1 Please merge this PR. Thanks

2021-08-23 06:49 UTC, yogkumgit commented
@jweston-1 Gentle reminder

2021-08-23 17:25 UTC, merged