Update office-365-ti.md
MicrosoftDocs/microsoft-365-docs pull request #6038
Opened 2021-08-17 07:23 UTC by msbemba

updated Office 365 Threat Intelligence connection

2021-08-17 07:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-17 07:24 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5866

2021-08-17 09:19 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/office-365-ti.md
> +This feature is only available if you've an active Office 365 E5 or the Threat Intelligence add-on. For more information, see the Office 365 Enterprise E5 product page.
```suggestion
This feature is only available if you have an active Office 365 E5 subscription or the Threat Intelligence add-on. For more information, see the Office 365 Enterprise E5 product page.
```

2021-08-17 09:20 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-17 10:36 UTC, yogkumgit commented
@msbemba Please copy review

2021-08-17 13:28 UTC, yogkumgit commented
@JohanFreelancer9

2021-08-17 15:21 UTC, JohanFreelancer9 approved these changes

2021-08-18 06:20 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2021-09-19 14:50 UTC, yogkumgit commented
@MSFTTracyP Gentle reminder

2022-02-08 15:04 UTC, yogkumgit commented
@tiburd Please help us here. Thanks

2022-02-16 19:42 UTC, tiburd commented
2/15: sent email to author

2022-02-22 19:13 UTC, MSFTTracyP approved these changes
Thanks

2022-02-22 19:21 UTC, merged