Update get-all-vulnerabilities-by-machines.md
MicrosoftDocs/microsoft-365-docs pull request #6068
Opened 2021-08-18 13:30 UTC by msbemba

Updated list of Odate filter queries

2021-08-18 13:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-18 13:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5931

2021-08-18 14:40 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/get-all-vulnerabilities-by-machines.md
> +- The OData's `$filter` query is supported on: `id`, `cveId`, `machineId`, `fixingKbId`, `productName`, `productVersion`, `severity` and `productVendor` properties.
```suggestion
- The OData's `$filter` query is supported on: `id`, `cveId`, `machineId`, `fixingKbId`, `productName`, `productVersion`, `severity`, and `productVendor` properties.
```

2021-08-18 14:41 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-19 03:17 UTC, JohanFreelancer9 approved these changes

2021-08-23 06:45 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2021-08-24 10:10 UTC, merged