Update get-missing-kbs-machine.md
MicrosoftDocs/microsoft-365-docs pull request #6072
Opened 2021-08-18 16:53 UTC by msbemba

Updated permissions required for the API

2021-08-18 16:53 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-18 16:53 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6051

2021-08-19 03:50 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/get-missing-kbs-machine.md
> +One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Use Microsoft Defender for Endpoint APIs](apis-intro.md)
```suggestion
The following permission is required to call this API. To learn more, including how to choose permissions, see [Use Microsoft Defender for Endpoint APIs](apis-intro.md).
```

2021-08-19 03:51 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-19 06:19 UTC, yogkumgit commented
@JohanFreelancer9

2021-08-19 07:38 UTC, JohanFreelancer9 approved these changes

2021-08-19 15:59 UTC, denisebmsft approved these changes
Thank you @msbemba

2021-08-19 15:59 UTC, merged