clarify "inside" term
MicrosoftDocs/microsoft-365-docs pull request #613
Opened 2019-10-24 09:41 UTC by MaratMussabekov

#575

2019-10-24 10:51 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-10-24 13:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-loss-prevention-policies.md
> +> Users, who have non-guest accounts in host organization's Active Directory or Azure Active Directory tenant, are considered as people inside the organization.
```suggestion
> Users who do not have guest accounts in a host organization's Active Directory or Azure Active Directory tenant are considered members of the organization.
```

2019-10-24 13:50 UTC, JohanFreelancer9 requested changes
Copy Review - suggestion

2019-10-24 14:08 UTC, mypil commented
@MaratMussabekov  - please merge the commit on the copy/edit review done by JohanFreelancer9  or make the necessary changes on the PR following the suggestions made. Thank you.

2019-10-25 12:40 UTC, mypil commented
@chrfox - PR has been copy edited and is ready for final review. This is based on issue #575.

Thank you.

cc: @kenwith

2019-11-06 17:18 UTC, merged