Updated create-retention-policies.md
MicrosoftDocs/microsoft-365-docs pull request #6177
Opened 2021-08-26 20:21 UTC by YuriySamorodov

Corrected OneDrive address naming convention description

2021-08-30 11:58 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-08-30 13:56 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-retention-policies.md
> +> [!NOTE] All period characters in <userprincipalname> should be replaced with underescores if any.
```suggestion
> [!NOTE]
> All period characters in <userprincipalname> should be replaced with underscores if any.
```

2021-08-30 14:00 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-retention-policies.md
> +> As an example, OneDrive address for a user with UserPrincipalName of "adam.smith@contoso.com" would be `https://contoso-my.sharepoint.com/personal/adam_smith_contoso_com`
```suggestion
```

2021-08-30 14:01 UTC, JohanFreelancer9 requested changes
Copy review - @YuriySamorodov, kindly commit the suggested changes. Many thanks.

2021-08-30 16:10 UTC, JohanFreelancer9 approved these changes

2021-08-31 08:04 UTC, yogkumgit commented
@cabailey Please merge this PR. Thanks

2021-09-01 00:21 UTC, cabailey commented
This is a technical change & I don't see confirmation from an authoritative source.  @YuriySamorodov, are you a Microsoft employee or can you provide a reference for this change, such as a support ticket?

2021-09-01 08:33 UTC, YuriySamorodov commented
Hi @cabailey ,

Thanks for the update. I am not Microsoft employee, however I have a vast experience with Office365 as an administrator and I know by heart examples in the article are inaccurate.
Although I have many tickets opened with Microsoft, none of those are related. However, I believe the following proves my point:

- There is no ```UserName``` attribute neither in AD or AzureAD. Few similar ones like ```Name``` or ``SamAccountName``` but none exactly the same.
- If you have M365 license you may want to check it for yourself. Just open your OneDrive and make a note of the URL.
If your tenant is a production environment, it is more than likely you will see your email address with all special characters replaced with underscores instead of ```onmicrosoft.com``` portion.
Here is mine:
![image](https://user-images.githubusercontent.com/5260172/131636768-c5f10b52-585b-4fad-b3ba-30a407bf6ab1.png)
It's obvious blurred part in the end is way too short for "onmicrosoft_com"
However here is what I get if my domain is replaced with "<tenantname>_onmicrosoft_com":
![image](https://user-images.githubusercontent.com/5260172/131637208-46c7ddd8-5f2c-4f34-aab2-cd8ab3c04894.png)
And just for the sake of proof here are a bunch of OneDrive sites pulled with PnP.PowerShell:
![image](https://user-images.githubusercontent.com/5260172/131639083-2f69c26a-3edc-4411-9839-10d15fc11831.png)
As you may see, none of the above users have "onmicrosoft_com" in their OneDrive site addresses. Instead it represents their ```UserPrincipalName``` with underscores instead of special characters.

Hope this helps.

2021-09-02 23:46 UTC, cabailey commented
@YuriySamorodov Thank you for your detailed explanation & sharing your experience. I've been able to run this to ground with an authoritative source from the OneDrive team and updated the article accordingly. It seems the "user name" came from the UI field when you create a new user in the Azure portal, and the example did match exactly against my test tenant (still using the default of "onmicrosoft.com"). However, the explanation and syntax representation was incorrect. I also learned that trying to predict the URL isn't always reliable because of potential conflict detection at the time of creation. The updated information:

To specify individual OneDrive accounts to include or exclude, the URL for a user's OneDrive is usually in the following format. For the user principal name (UPN), any special characters such as a period, comma, space, and the at sign ("@") are converted to underscores ("_"): https://<tenant name>-my.sharepoint.com/personal/<user principal name>

For example, for a user in the Contoso tenant who has a UPN of "rsimone@contoso.onmicrosoft.com": https://contoso-my.sharepoint.com/personal/rsimone_contoso_onmicrosoft_com. However, numbers or GUIDs can be appended when conflicts are detected.

It's always best to confirm a user's URL for their OneDrive account, which you can do with the Microsoft 365 admin center, or PowerShell. For more information, see Get a list of all user OneDrive URLs in your organization.

2021-09-03 00:20 UTC, YuriySamorodov commented
Thanks @cabailey, much appreciated.
Please note though ```UserPrincipalName``` is one word which represents a specific attribute in AD.

2021-09-03 00:20 UTC, closed without merging

2021-09-03 00:50 UTC, cabailey commented
For easier readability, we used complete words - not everybody works at the level of AD attribute names. The term is "user principal name", which is represented by "User Principal Name" in the Azure AD portal, and UserPrincipalName for the Azure AD attribute. I don't think this will trip up anybody.

2021-09-03 01:15 UTC, YuriySamorodov commented
Dear @cabaley,
First and foremost please don't take my comments and PRs personal. It's not my intention to steal your job or devaluate your technical writer skills. The only reason I spend my time suggesting changes is to improve Microsoft documentation.
Believe me or not, the vast majority of users coming to https://docs.microsoft.com are either admins or developers. Especially when it comes to Microsoft 365 **Admin** Center related articles. And for us tech guys ```UserPrincipalName``` does mean something. Moreover as a foreigner, I stumbled over the "user principal name" phrase for a second, wondering "What's the matter with the name of a user's manager?" =) The other purpose of having one word is you get better results on Google. Pretty much the same idea has led Jeffrey Snoover of Microsoft to the word ```cmdlet``` back in 2006, when he introduced PowerShell.
Nevertheless, I am really thankful for your efforts. You and many of your colleagues are making Microsoft documentation better every day!

2021-09-07 22:11 UTC, cabailey commented
@YuriySamorodov  I didn't take it personally at all - always fun to learn together! Since the current text was signed off by the OneDrive PM, and it doesn't assume knowledge of Azure AD attribute names, we'll leave it like this for now and monitor for additional customer feedback. Thanks again for taking the time to flag this and improve the docs!