Fixing Links & Namings
MicrosoftDocs/microsoft-365-docs pull request #6178
Opened 2021-08-27 02:00 UTC by modery

Smaller fixes - correcting some broken links and renaming some older names

2021-08-30 11:59 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-08-30 14:08 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/eval-defender-endpoint-enable-eval.md
> +You can choose to use any of the supported management tools, but Intune provides optimal integration. For more information, see [Configure Microsoft Defender for Endpoint in Microsoft Intune](/mem/in
```suggestion
You can choose to use any of the supported management tools, but Intune provides optimal integration. For more information, see [Configure Microsoft Defender for Endpoint in Microsoft Intune](/mem/intune/protect/advanced-threat-protection-configure#enable-microsoft-defender-for-endpoint-in-intune).
```

2021-08-30 14:12 UTC, JohanFreelancer9 commented on microsoft-365/contentunderstanding/adoption-getstarted.md
>  > [!Note]
```suggestion
> [!NOTE]
```

2021-08-30 14:13 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/eval-defender-endpoint-enable-eval.md
>  >[!TIP]
```suggestion
> [!TIP]
```

2021-08-30 14:13 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/eval-defender-endpoint-enable-eval.md
> +>Microsoft Defender for Endpoint also comes with an in-product evaluation lab where you can add pre-configured devices and run simulations to evaluate the capabilities of the platform. The lab comes
```suggestion
> Microsoft Defender for Endpoint also comes with an in-product evaluation lab where you can add pre-configured devices and run simulations to evaluate the capabilities of the platform. The lab comes with a simplified set-up experience that can help quickly demonstrate the value of Microsoft Defender for Endpoint including guidance for many features like advanced hunting and threat analytics. For more information, see [Evaluate capabilities](../defender-endpoint/evaluation-lab.md). <br> The main difference between the guidance provided in this article and the evaluation lab is the evaluation environment uses production devices whereas the evaluation lab uses non-production devices. 
```

2021-08-30 14:18 UTC, JohanFreelancer9 requested changes
Copy review - @modery, kindly commit the few additional suggested changes. Many thanks.

2021-08-31 08:07 UTC, yogkumgit commented
@JohanFreelancer9

2021-08-31 08:09 UTC, JohanFreelancer9 approved these changes

2021-08-31 08:15 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks.

2021-09-01 16:17 UTC, tiburd commented on microsoft-365/contentunderstanding/trial-syntex.md
> +- Forms-processing models will be stored in the Dataverse (previously named Common Data Service (CDS)) instance of the default Power Platform environment. These could be used with future licensing fo
```suggestion
- Forms-processing models will be stored in the Dataverse (previously named Common Data Service [CDS]) instance of the default Power Platform environment. These could be used with future licensing for SharePoint Syntex or with AI Builder capabilities in the Power Platform.
```

2021-09-01 16:20 UTC, merged