Update teams-classes-with-canvas.md
MicrosoftDocs/microsoft-365-docs pull request #6198
Opened 2021-08-29 16:30 UTC by msbemba

Updated steps on how to grant admin consent

2021-08-29 16:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-29 16:31 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5364

2021-08-30 03:32 UTC, JohanFreelancer9 commented on microsoft-365/lti/teams-classes-with-canvas.md
> +## Grant Admin Consent
```suggestion
## Grant admin consent
```

2021-08-30 03:35 UTC, JohanFreelancer9 commented on microsoft-365/lti/teams-classes-with-canvas.md
> +2. Open Enterprise applications > Select the Application **Microsoft-Teams-Sync-for-Canvas**
```suggestion
2. Open Enterprise applications and select the **Microsoft-Teams-Sync-for-Canvas** application.
```

2021-08-30 03:36 UTC, JohanFreelancer9 commented on microsoft-365/lti/teams-classes-with-canvas.md
> +## Microsoft Office 365 Admin
```suggestion
3. Select **Permissions** and then choose **Grant admin consent**.

4. Agree with the permissions the application requires and grant consent.

## Microsoft Office 365 admin
```

2021-08-30 03:37 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-30 03:56 UTC, yogkumgit commented
@msbemba

2021-08-30 12:02 UTC, yogkumgit commented
@JohanFreelancer9

2021-08-30 15:34 UTC, JohanFreelancer9 approved these changes

2021-08-31 07:56 UTC, yogkumgit commented
@cichur Please merge this PR. Thanks

2021-09-19 14:51 UTC, yogkumgit commented
@tiburd

2021-09-20 15:29 UTC, tiburd commented on microsoft-365/lti/teams-classes-with-canvas.md
> +Prior to managing the Microsoft Teams integration within Instructure Canvas, it is important to have Canvas’s **Microsoft-Teams-Sync-for-Canvas** Azure app approved by your institution’s Microsoft Of
```suggestion
Before managing the Microsoft Teams integration within Instructure Canvas, it's important to have Canvas’s **Microsoft-Teams-Sync-for-Canvas** Azure app approved by your institution’s Microsoft Office 365 admin in your Microsoft Azure tenant before completing the Canvas admin setup. You need to be a Global Administrator to perform these steps.
```

2021-09-20 15:29 UTC, tiburd commented on microsoft-365/lti/teams-classes-with-canvas.md
> +2. Open Enterprise applications and select the **Microsoft-Teams-Sync-for-Canvas** application.
```suggestion
2. Open Enterprise applications, and then select the **Microsoft-Teams-Sync-for-Canvas** application.
```

2021-09-20 15:30 UTC, tiburd commented on microsoft-365/lti/teams-classes-with-canvas.md
> +3. Select **Permissions** and then choose **Grant admin consent**.
```suggestion
3. Select **Permissions**, and then select **Grant admin consent**.
```

2021-09-20 15:30 UTC, tiburd commented on microsoft-365/lti/teams-classes-with-canvas.md
> +4. Agree with the permissions the application requires and grant consent.
```suggestion
4. Agree with the permissions that the application requires, and then grant consent.
```

2021-09-20 15:31 UTC, merged