Update configure-server-endpoints.md
MicrosoftDocs/microsoft-365-docs pull request #6200
Opened 2021-08-29 17:06 UTC by msbemba

updated the required of having server licenses in the tenant 
As some users are getting confused as to where to assign them

2021-08-29 17:06 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6081

2021-08-29 17:07 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-30 04:59 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-server-endpoints.md
> +> Defender for Endpoint standalone server license is required, per node, in order to onboard a Windows server through Microsoft Monitoring Agent (Option 1), or through Microsoft Endpoint Manager (Opt
```suggestion
> Defender for Endpoint standalone server license is required, per node, in order to onboard a Windows server through Microsoft Monitoring Agent (Option 1), or through Microsoft Endpoint Manager (Option 3). Alternatively, an Azure Defender for Servers license is required, per node, in order to onboard a Windows server through Azure Security Center (Option 2). For more information, see [Supported features available in Azure Defender](/azure/security-center/security-center-services). 
```

2021-08-30 04:59 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, minor additional edit, please.

2021-08-30 12:03 UTC, yogkumgit commented
@JohanFreelancer9

2021-08-30 12:09 UTC, JohanFreelancer9 approved these changes

2021-08-30 17:10 UTC, merged