Update readiness-assessment-fix.md
MicrosoftDocs/microsoft-365-docs pull request #6201
Opened 2021-08-29 17:25 UTC by msbemba

Updated based on issue #6124

If there is an existing Autopilot Deployment profile (even if it is not assigned) the setting "Convert all targeted devices to Autopilot" must be set to "No"

2021-08-29 17:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6124

2021-08-29 17:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-30 05:04 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/get-ready/readiness-assessment-fix.md
> +You shouldn't have any existing Autopilot profiles that target assigned or dynamic groups with Microsoft Managed Desktop devices. Microsoft Managed Desktop uses Autopilot to provision new devices. If
```suggestion
You shouldn't have any existing Autopilot profiles that target assigned or dynamic groups with Microsoft Managed Desktop devices. Microsoft Managed Desktop uses Autopilot to provision new devices. If you have an existing Autopilot deployment profile, the "Convert all targeted devices to Autopilot" setting must be set to "No" for the managed desktop readiness test for Autopilot to succeed.
```

2021-08-30 05:06 UTC, JohanFreelancer9 requested changes
Copy review.

2021-08-30 11:54 UTC, JohanFreelancer9 approved these changes

2021-09-01 08:40 UTC, yogkumgit commented
@jaimeo Please merge this PR. Thanks

2021-09-16 19:26 UTC, merged