Update activity-reports.md
MicrosoftDocs/microsoft-365-docs pull request #6221
Opened 2021-08-31 17:44 UTC by msbemba

Updated document based on the change posted via MC275344 (Going live sep1 )

2021-08-31 17:44 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-08-31 17:44 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6145

2021-09-01 03:07 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/activity-reports.md
> +If you want to unhide user level information when you're generating your reports, a global administrator can  quickly make that change in the admin center.
```suggestion
If you want to unhide user-level information when you're generating your reports, a global administrator can quickly make that change in the admin center.
```

2021-09-01 03:08 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/activity-reports.md
> +3. In the **Reports** pane, select the **Choose how to show user information** and  select **Show identifiable user information in reports**
```suggestion
3. In the **Reports** pane, select **Choose how to show user information** and  choose **Show identifiable user information in reports**.
```

2021-09-01 03:20 UTC, JohanFreelancer9 approved these changes

2021-09-01 03:22 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, kindly just commit the minor suggested changes. Many thanks.

2021-09-01 13:28 UTC, JohanFreelancer9 approved these changes

2021-09-06 07:15 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-09-13 16:42 UTC, merged