Update configure-email-forwarding.md
MicrosoftDocs/microsoft-365-docs pull request #6223
Opened 2021-08-31 17:52 UTC by msbemba

Updated the related content with link on how to control external email forwarding as it is related to this document.

2021-08-31 17:52 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6161

2021-08-31 17:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-09-01 03:43 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/configure-email-forwarding.md
> +[control external email forwarding](/security/office-365-security/external-email-forwarding) (article)
```suggestion
[Control automatic external email forwarding in Microsoft 365](/security/office-365-security/external-email-forwarding) (article)
```

2021-09-01 03:44 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/configure-email-forwarding.md
>  [Change a user name and email address](../add-users/change-a-user-name-and-email-address.md) (article)
```suggestion
[Change a user name and email address](../add-users/change-a-user-name-and-email-address.md) (article)\
```

2021-09-01 03:45 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, kindly commit the suggested changes. Many thanks.

2021-09-01 13:18 UTC, JohanFreelancer9 approved these changes

2021-09-06 07:07 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-09-13 16:35 UTC, merged