Update managing-office-365-endpoints.md
MicrosoftDocs/microsoft-365-docs pull request #6271
Opened 2021-09-06 21:10 UTC by msbemba

Updated the way allow customers to block consumer services usinghttps://docs.microsoft.com/en-us/azure/active-directory/manage-apps/tenant-restrictions#blocking-consumer-applications

2021-09-06 21:10 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6233

2021-09-06 21:10 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-09-07 06:19 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/managing-office-365-endpoints.md
> +The  tenant restrictions feature now supports blocking the use of all Microsoft consumer applications (MSA apps) such as OneDrive, Hotmail, and Xbox.com. This uses a separate header to the login.live
```suggestion
The tenant restrictions feature now supports blocking the use of all Microsoft consumer applications (MSA apps) such as OneDrive, Hotmail, and Xbox.com. This uses a separate header to the login.live.com endpoint. For more details, see [Use tenant restrictions to manage access to SaaS cloud applications](/azure/active-directory/manage-apps/tenant-restrictions#blocking-consumer-applications),
```

2021-09-07 06:21 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-07 11:17 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/managing-office-365-endpoints.md
> +The tenant restrictions feature now supports blocking the use of all Microsoft consumer applications (MSA apps) such as OneDrive, Hotmail, and Xbox.com. This uses a separate header to the login.live.
```suggestion
The tenant restrictions feature now supports blocking the use of all Microsoft consumer applications (MSA apps) such as OneDrive, Hotmail, and Xbox.com. This uses a separate header to the login.live.com endpoint. For more details, see [Use tenant restrictions to manage access to SaaS cloud applications](/azure/active-directory/manage-apps/tenant-restrictions#blocking-consumer-applications).
```

2021-09-07 11:18 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more minor edit please.

2021-09-07 11:25 UTC, JohanFreelancer9 approved these changes

2021-09-09 05:31 UTC, yogkumgit commented
@pandrew1 Please merge this PR. Thanks

2021-09-19 14:52 UTC, yogkumgit commented
@pandrew1 Gentle reminder

2021-10-22 05:53 UTC, yogkumgit commented
@tiburd Please help us and follow with the stakeholder who can merge this PR. Thanks

2021-10-22 16:49 UTC, merged