Update monitor-connectivity.md
MicrosoftDocs/microsoft-365-docs pull request #6274
Opened 2021-09-06 21:35 UTC by msbemba

Updated Microsoft System Center Operations Manager Management Pack for Microsoft 365

2021-09-06 21:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-09-06 21:36 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6138

2021-09-07 06:57 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/monitor-connectivity.md
> +|**Use System Center to Monitor Microsoft 365** <br/> |If you're using Microsoft System Center, you can download the [Microsoft System Center Operations Manager Management Pack for Microsoft 365](hht
```suggestion
|**Use System Center to Monitor Microsoft 365** <br/> |If you're using Microsoft System Center, you can download the [Microsoft System Center Operations Manager Management Pack for Microsoft 365](https://www.microsoft.com/download/details.aspx?id=103379) to begin monitoring Microsoft 365 today. For more detailed guidance, please see the management pack operations guide. <br/> |
```

2021-09-07 06:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-07 11:14 UTC, JohanFreelancer9 approved these changes

2021-09-08 02:43 UTC, merged