Added a note
MicrosoftDocs/microsoft-365-docs pull request #629
Opened 2019-10-26 06:33 UTC by joinimran

As per the author's recommendation, I have updated a note in the document.

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/486

2019-10-28 08:51 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-10-28 16:00 UTC, JohanFreelancer9 commented on microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md
> +> Anyother fields in header that are not mentioned below are exclusively used by the Microsoft anti-spam team for diagnostic purposes.
```suggestion
> Any other fields in the header that are not mentioned below are exclusively used by the Microsoft anti-spam team for diagnostic purposes.
```

2019-10-28 16:01 UTC, JohanFreelancer9 requested changes
Copy Review

2019-10-29 04:43 UTC, joinimran commented
Ready to go live.

2019-10-29 14:22 UTC, mypil commented
@chrisda - PR has been copy edited and is ready for final review. This is based on this issue comment https://github.com/MicrosoftDocs/microsoft-365-docs/issues/486#issuecomment-540828898

Thank you.

cc: @kenwith

2019-11-12 18:24 UTC, merged