Update migrate-email.md
MicrosoftDocs/microsoft-365-docs pull request #6297
Opened 2021-09-08 21:51 UTC by msbemba

Added people API to the steps

2021-09-08 21:51 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-09-08 21:52 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6259

2021-09-09 06:17 UTC, JohanFreelancer9 commented on microsoft-365/business-video/moveto-microsoft-365/migrate-email.md
> +1. Repeat this process for Google Calendar API, People API and Contacts API.
```suggestion
1. Repeat this process for Google Calendar API, People API, and Contacts API. 
```

2021-09-09 06:18 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-09 09:01 UTC, JohanFreelancer9 approved these changes

2021-09-09 11:33 UTC, yogkumgit commented
@twernermsft Please merge this PR. Thanks

2021-09-10 15:20 UTC, merged