inclusive definition updatea
MicrosoftDocs/microsoft-365-docs pull request #6298
Opened 2021-09-08 23:04 UTC by StefanieBier

Updating inclusive definitions to provide clarity.

2021-09-09 11:34 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-09-09 11:41 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-09-10 04:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/email-threading-in-advanced-ediscovery.md
> +Email threading parses each email and deconstructs it to individual messages; each email is a chain of individual messages. It then analyzes all emails in the review set to determine whether an email
```suggestion
Email threading parses each email and deconstructs it to individual messages; each email is a chain of individual messages. It then analyzes all emails in the review set to determine whether an email message has unique content or if the chain (parent messages) is wholly contained in the final email. Email messages are divided into four inclusive values:
```

2021-09-10 04:15 UTC, JohanFreelancer9 commented on microsoft-365/compliance/email-threading-in-advanced-ediscovery.md
> +- **Inclusive**: An inclusive email is the the final email message in an email thread and contains all previous history of that email thread.
```suggestion
- **Inclusive**: An inclusive email is the final email message in an email thread and contains all the previous history of that email thread.
```

2021-09-10 04:16 UTC, JohanFreelancer9 commented on microsoft-365/compliance/email-threading-in-advanced-ediscovery.md
> +- **Inclusive minus**: An email messaage is designated as Inclusive minus if there are one or more attachments associated with the specific message within the email thread. A reviewer can use the Inc
```suggestion
- **Inclusive minus**: An email message is designated as Inclusive minus if there are one or more attachments associated with the specific message within the email thread. A reviewer can use the Inclusive minus value to determine which specific email message within the thread has associated attachments. 
```

2021-09-10 04:18 UTC, JohanFreelancer9 commented on microsoft-365/compliance/email-threading-in-advanced-ediscovery.md
> +- **Inclusive copy**: An email message is considered an Inclusive copy if it is an exact copy of an inclusive/inclusive minus email.
```suggestion
- **Inclusive copy**: An email message is considered an inclusive copy if it is an exact copy of an inclusive/inclusive minus email. 
```

2021-09-10 04:20 UTC, JohanFreelancer9 requested changes
Copy review - @StefanieBier, kindly commit the suggested changes. Many thanks.

2021-09-10 17:36 UTC, merged

2021-09-10 17:36 UTC, markjjo commented
@StefanieBier I have reviewed and revised updates and merged this PR. Should be live by end of day