Update get-started-windows-365-business.md
MicrosoftDocs/microsoft-365-docs pull request #6300
Opened 2021-09-09 09:21 UTC by yuhonda

This description lead to misunderstand that mobile device is not supported for Cloud PC. I suggest that add additional description about NOTE in Windows 365 home page section.

2021-09-09 11:41 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-09-10 04:11 UTC, JohanFreelancer9 requested changes
Copy review - @yuhonda, kindly commit my suggested edit. Many thanks.

2021-09-10 04:11 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/get-started-windows-365-business.md
> +> Mobile devices aren’t currently supported to use browser to open the Cloud PC. Remote Desktop app is supported.
```suggestion
> Mobile devices aren’t currently supported for using a browser to open Cloud PC. The Remote Desktop app is supported.
```

2021-09-10 04:22 UTC, yuhonda commented
Thank you I have commited.

2021-09-10 04:24 UTC, yuhonda commented
Sorry. I missed to close PR. I have committed suggestion and please consider to merge.

2021-09-10 05:39 UTC, yogkumgit commented
@JohanFreelancer9

2021-09-10 05:41 UTC, JohanFreelancer9 approved these changes

2021-09-12 13:22 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2021-09-13 15:50 UTC, merged