Update configure-arcsight.md
MicrosoftDocs/microsoft-365-docs pull request #6303
Opened 2021-09-09 13:18 UTC by msbemba

removed <i></i> from the URL's

2021-09-09 13:41 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6281

2021-09-09 13:42 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-09-10 03:15 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-arcsight.md
> +   |Events URL|Depending on the location of your datacenter, select either the EU or the US URL: <ul><li>**For EU**:  `https://wdatp-alertexporter-eu.windows.com/api/alerts/?sinceTimeUtc=$START_AT_TI
```suggestion
   |Events URL|Depending on the location of your datacenter, select either the EU, the US, or the UK URL: <ul><li>**For EU**:  `https://wdatp-alertexporter-eu.windows.com/api/alerts/?sinceTimeUtc=$START_AT_TIME`</li><li>**For US**: `https://wdatp-alertexporter-us.windows.com/api/alerts/?sinceTimeUtc=$START_AT_TIME`</li><li>**For UK**: `https://wdatp-alertexporter-uk.windows.com/api/alerts/?sinceTimeUtc=$START_AT_TIME`</li></ul>|
```

2021-09-10 03:15 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-10 05:14 UTC, JohanFreelancer9 approved these changes

2021-09-10 05:28 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-09-10 15:16 UTC, merged