Update create-a-dlp-policy-from-a-template.md
MicrosoftDocs/microsoft-365-docs pull request #6304
Opened 2021-09-09 15:30 UTC by msbemba

Fixed typo

2021-09-09 15:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6290

2021-09-09 15:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-09-10 04:41 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-a-dlp-policy-from-a-template.md
>  11. On the **Protection actions** page if you want, you can customize the policy tip notifications and notification emails. Enable **When content matches the policy conditions, show policy tips to us
```suggestion
11. On the **Protection actions** page if you want, you can customize the policy tip notifications and notification emails. Enable **When content matches the policy conditions, show policy tips to users and send them an email notification**, then choose **Customize the tip and email**.
```

2021-09-10 04:42 UTC, JohanFreelancer9 requested changes
Copy review - Minor additional edit, please.

2021-09-10 11:08 UTC, yogkumgit commented
@msbemba

2021-09-10 13:28 UTC, JohanFreelancer9 approved these changes

2021-09-10 15:16 UTC, merged