Update update-payment.md
MicrosoftDocs/microsoft-365-docs pull request #6323
Opened 2021-09-13 16:19 UTC by msbemba

Updated roles needed for following the steps

2021-09-13 16:19 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-09-13 16:19 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6279

2021-09-13 17:19 UTC, JohanFreelancer9 commented on microsoft-365/business-video/update-payment.md
> +You must be a Global or Billing admin to do the tasks in this article. For more information, see [About admin roles](../../admin/add-users/about-admin-roles.md).
```suggestion
You must be a Global or Billing admin to do the tasks in this article. For more information, see [About admin roles](/microsoft-365/admin/add-users/about-admin-roles).
```

2021-09-13 17:20 UTC, JohanFreelancer9 requested changes
Copy review

2021-09-14 05:40 UTC, yogkumgit commented
@JohanFreelancer9

2021-09-14 07:42 UTC, JohanFreelancer9 approved these changes

2021-09-14 22:32 UTC, merged