Update recover from ransomware
MicrosoftDocs/microsoft-365-docs pull request #6392
Opened 2021-09-21 20:09 UTC by drew-russell

Update the recover from ransomware documentation to add more wholistic best practices for backup and recovery data protection and better highlight today's M365 threat landscape

2021-09-24 11:51 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-09-24 14:43 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/recover-from-ransomware.md
> +Even if you take every precaution to protect your organization, you can still fall victim to a [ransomware](/windows/security/threat-protection/intelligence/ransomware-malware) attack. Ransomware is
```suggestion
Even if you take every precaution to protect your organization, you can still fall victim to a [ransomware](/windows/security/threat-protection/intelligence/ransomware-malware) attack. Ransomware is big business, and in today's threat landscape Microsoft 365 is an ever-increasing [target for sophisticated attacks](https://i.blackhat.com/USA21/Wednesday-Handouts/us-21-Cloudy-With-A-Chance-Of-APT-Novel-Microsoft-365-Attacks-In-The-Wild.pdf).
```

2021-09-24 14:45 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/recover-from-ransomware.md
> +The Microsoft 365 compliance suite of tools are designed to meet your organizations [legal and regulatory standards](/microsoft-365/compliance/) which is why as a best practice, we [recommend](https:
```suggestion
The Microsoft 365 compliance suite of tools is designed to meet your organization's [legal and regulatory standards](/microsoft-365/compliance/) which is why as a best practice, we [recommend](https://www.microsoft.com/servicesagreement) that you regularly back up your Microsoft 365 content and data using third-party apps and services.
```

2021-09-24 14:47 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/recover-from-ransomware.md
> +In order to ensure you have the ability to restore your data, it's important to regularly test your backups and validate they can be restored in the event of an attack. In the case of an actual attac
```suggestion
In order to ensure you have the ability to restore your data, it is important to regularly test your backups and validate they can be restored in the event of an attack. In the case of an actual attack, these restorations should not be completed until **after** you've removed the ransomware payload (malware) from your environment and **after** you have verified there is no unauthorized access in your Microsoft 365 environments.
```

2021-09-24 14:47 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/recover-from-ransomware.md
> +To ensure your backups were not also affected by ransomware, the third-party service should be air gapped from your environments.
```suggestion
To ensure your backups were not also affected by ransomware, the third-party service should be air-gapped from your environments.
```

2021-09-24 14:49 UTC, JohanFreelancer9 requested changes
Copy review - @drew-russell,  kindly commit my suggested changes. Many thanks.

2021-09-24 14:50 UTC, JohanFreelancer9 approved these changes

2021-09-24 14:50 UTC, drew-russell commented
@JohanFreelancer9 appreciate the quick eye on here! All changes have been committed.

2021-09-27 05:53 UTC, yogkumgit commented
@chrisda Please merge this PR. Thanks

2021-09-27 16:16 UTC, merged