Update user-submission.md
MicrosoftDocs/microsoft-365-docs pull request #6414
Opened 2021-09-23 15:26 UTC by BrunoDal

Update for user reporting only for phish &  report in user quarantine.

2021-09-24 11:51 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-09-24 15:04 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/user-submission.md
> +       -  **Only display when user reports phishing** : Check this option if you want to display the message only when an email is reporeted as phish, if not checked messages will be shown for any ki
```suggestion
       -  **Only display when user reports phishing**: Check this option if you want to display the message only when an email is reported as phish. If not, checked messages will be shown for any kind of report.
```

2021-09-24 15:09 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/user-submission.md
> +Enable this feature if you want to let end users report a message from the user quarantine.
```suggestion
   - **Microsoft Outlook Report Message button**: Enable this feature if you want to let end users report a message from the user quarantine.
```

2021-09-24 15:13 UTC, JohanFreelancer9 requested changes
Copy review - @BrunoDal, kindly commit the suggested changes. Many thanks.

2021-09-27 07:43 UTC, JohanFreelancer9 approved these changes

2021-09-27 08:02 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2021-09-27 09:21 UTC, siosulli commented
@Dansimp @chrisda - the update here is:

"- **Microsoft Outlook Report Message button**: Enable this feature if you want to let end users report a message from the user quarantine." 

I don't want to just merge this as 'user quarantine' is not something I am familiar with so if could review and merge that would be great. Thanks.

2021-09-27 17:26 UTC, chrisda commented
Yeah, there really is no such thing as 'user quarantine'; it's just quarantine. Users only see their own messages (where they're a recipient). Admins see everyone's messages, and often more types of quarantined messages (malware, quarantined by transport rules, etc.). Same quarantine URL for everyone.

2021-09-27 20:33 UTC, merged