Update add-another-email-alias-for-a-user.md
MicrosoftDocs/microsoft-365-docs pull request #6435
Opened 2021-09-27 17:33 UTC by msbemba

Added admin role needed to create a alias.

2021-09-27 17:33 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-09-27 17:34 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6388

2021-09-28 03:19 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/add-another-email-alias-for-a-user.md
> +You must have Global Admin rights to add email aliases to a user.
```suggestion
You must have Global Admin rights to add email aliases for a user.
```

2021-09-28 03:20 UTC, JohanFreelancer9 requested changes
Copy review.

2021-09-28 14:14 UTC, yogkumgit commented
@msbemba

2021-09-28 15:37 UTC, merged