Updating "unified audit logs" to Microsoft 365 Audit
MicrosoftDocs/microsoft-365-docs pull request #6448
Opened 2021-09-28 18:55 UTC by sujitnaray

Microsoft 365 Audit is the product name.

2021-09-28 18:56 UTC, sujitnaray commented
@robmazz , @markjjo - Could you please approve the changes to reflect "Microsoft 365 Audit" as the product name? Thanks.

2021-09-30 12:50 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-09-30 15:34 UTC, JohanFreelancer9 commented on microsoft-365/compliance/communication-compliance-siem.md
> +A common need for organizations is to integrate communication compliance alerts and these SIEM solutions. With this integration, organizations can view communication compliance alerts in their SIEM s
```suggestion
A common need for organizations is to integrate communication compliance alerts and these SIEM solutions. With this integration, organizations can view communication compliance alerts in their SIEM solution and then remediate alerts within the communication compliance workflow and user experience. For example, an employee sends an offensive message to another employee and that message is detected by a communication compliance policy monitoring for offensive language. These events are tracked in the Microsoft 365 Audit (also known as "unified audit log") by the communication compliance solution and imported into the SIEM solution. An alert is then triggered in the SIEM solution for the organization from events monitored in the Microsoft 365 Audit that is associated with communication compliance alerts. Investigators are notified of the alert in the SIEM solutions and then they investigate and remediate the alert in the communication compliance solution.
```

2021-09-30 15:35 UTC, JohanFreelancer9 commented on microsoft-365/compliance/communication-compliance-siem.md
> +**Example of an Audit log entry for a policy with custom keyword match (custom sensitive information type):**
```suggestion
**Example of a Microsoft 365 Audit log entry for a policy with custom keyword match (custom sensitive information type):**
```

2021-09-30 15:38 UTC, JohanFreelancer9 commented on microsoft-365/compliance/communication-compliance-siem.md
>  >[!NOTE]
```suggestion
> [!NOTE]
```

2021-09-30 15:39 UTC, JohanFreelancer9 commented on microsoft-365/compliance/communication-compliance-siem.md
> +>Currently, there may be up to a 24h delay between the time a policy match is recorded in the Microsoft 365 Audit and the time in which you can investigate policy matches in communication compliance.
```suggestion
> Currently, there may be up to a 24-hour delay between the time a policy match is recorded in the Microsoft 365 Audit and the time in which you can investigate policy matches in communication compliance.
```

2021-09-30 15:40 UTC, JohanFreelancer9 commented on microsoft-365/compliance/communication-compliance-siem.md
> +For more information about the Audit logs for Office 365 collected by Azure Sentinel, see [Azure Monitor Logs reference](/azure/azure-monitor/reference/tables/OfficeActivity).
```suggestion
For more information about the Microsoft 365 Audit logs for Office 365 collected by Azure Sentinel, see [Azure Monitor Logs reference](/azure/azure-monitor/reference/tables/OfficeActivity).
```

2021-09-30 15:42 UTC, JohanFreelancer9 requested changes
Copy review - @sujitnaray, kindly commit the suggested changes if you agree with them. Many thanks.

2021-09-30 16:12 UTC, sujitnaray reviewed
Approved Johan's suggestions.

2021-09-30 16:14 UTC, JohanFreelancer9 approved these changes

2021-09-30 16:14 UTC, sujitnaray commented
@JohanFreelancer9 , @robmazz  - I think I have approved all your changes.  Please submit! Or let me know if you need anything else from me.

2021-09-30 16:18 UTC, JohanFreelancer9 commented
@sujitnaray - thank you for committing the changes. Nothing more is needed from you at this time. The PR will be merged into live once it has been approved by the doc owner/manager.

2021-10-01 12:41 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2021-10-05 19:58 UTC, robmazz commented
@sujitnaray  and @yogkumgit - Is 'the Microsoft 365 Audit" really correct reference throughout this change? Sounds grammatically incorrect. I'll also reach out to the audit content writer about this, I assume all that content would need to match/sync.

2021-10-05 20:07 UTC, sujitnaray commented
@robmazz - Yes, "Microsoft 365 Audit" is the product name, and not "unified audit logs".  Adding @markjjo who is the Audit content writer to look over the changes too.

2021-10-05 21:31 UTC, robmazz commented
@sujitnaray - thanks. I also spoke with Mark so we could be consistent in the docs. This PR still has some grammar issues, for example - instead of saying 'the Microsoft 365 Audit', we should just say 'Microsoft 365 Audit'. But I'll accept and push this PR and change those items in a separate follow-on PR later today.

2021-10-05 21:31 UTC, merged