Update centralized-deployment-of-add-ins.md
MicrosoftDocs/microsoft-365-docs pull request #6492
Opened 2021-10-04 12:23 UTC by msbemba

updated licensing requirements

2021-10-04 12:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-04 12:23 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6430

2021-10-04 14:28 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/centralized-deployment-of-add-ins.md
> +Centralized deployment of add-ins requires that the users are using Microsoft 365 Enterprise SKUs: E3/E5/F3, Office 365 Enterprise SKUs: E3/E5/F3 or Business SKUs: Business Basic, Business Standard,
```suggestion
Centralized deployment of add-ins requires that the users are using Microsoft 365 Enterprise SKUs: E3/E5/F3, Office 365 Enterprise SKUs: E3/E5/F3, or Business SKUs: Business Basic, Business Standard, Business Premium (and are signed into Office using their organizational ID), and have Exchange Online and active Exchange Online mailboxes. Your subscription directory must either be in or federated to Azure Active Directory.
```

2021-10-04 14:29 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-04 16:22 UTC, JohanFreelancer9 approved these changes

2021-10-05 06:24 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-10-21 17:44 UTC, merged