Update device-control-removable-storage-access-control.md
MicrosoftDocs/microsoft-365-docs pull request #6499
Opened 2021-10-04 22:09 UTC by msbemba

updated navigation path for device control policy under attack surface reduction

2021-10-04 22:09 UTC, msbemba commented
@JohanFreelancer9 please copy review

2021-10-04 22:09 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6421

2021-10-05 02:32 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +This capability is availabile at  Microsoft Endpoint Manager admin center (<https://endpoint.microsoft.com/>) \> Endpoint Security \> Attack Surface Reduction \> Create Policy \> Platform: Windows 10
```suggestion
This capability is availabile at Microsoft Endpoint Manager admin center (<https://endpoint.microsoft.com/>) \> Endpoint Security \> Attack Surface Reduction \> Create Policy \> Platform: Windows 10 and later & Profile: Device Control) 
```

2021-10-05 02:41 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-05 06:43 UTC, yogkumgit commented
@msbemba

2021-10-05 10:17 UTC, JohanFreelancer9 approved these changes

2021-10-05 17:22 UTC, denisebmsft approved these changes
Thank you @msbemba

2021-10-05 17:22 UTC, merged