Update customer-key-overview.md
MicrosoftDocs/microsoft-365-docs pull request #6502
Opened 2021-10-04 22:25 UTC by msbemba

updated unified audit log storage to DEP for multiple Microsoft 365 workloads

2021-10-04 22:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-04 22:26 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6433

2021-10-05 02:16 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-overview.md
> +- Unified Audit log storage
```suggestion
- Unified audit log storage
```

2021-10-05 02:16 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-05 06:57 UTC, yogkumgit commented
@msbemba

2021-10-05 11:31 UTC, JohanFreelancer9 approved these changes

2021-10-06 12:23 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2021-10-25 07:31 UTC, yogkumgit commented
@KCCross Gentle reminder

2021-12-06 22:14 UTC, merged