Update prepare-for-directory-synchronization.md
MicrosoftDocs/microsoft-365-docs pull request #6504
Opened 2021-10-04 22:40 UTC by msbemba

updated Non ASCII characters does not sync for any attributes as there was no specific mention about that in the document.

2021-10-04 22:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-04 22:40 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6395

2021-10-05 01:53 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/prepare-for-directory-synchronization.md
> +> Non ASCII characters does not sync for any attributes on the AD DS user account
```suggestion
> Non-ASCII characters do not sync for any attributes on the AD DS user account.
```

2021-10-05 01:54 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-05 07:06 UTC, yogkumgit commented
@msbemba

2021-10-05 11:38 UTC, JohanFreelancer9 approved these changes

2021-10-06 12:21 UTC, yogkumgit commented
@LauraWi / @kelleyvice-msft Please merge this PR. Thanks

2021-10-06 17:31 UTC, merged