Update remove-former-employee-step-4.md
MicrosoftDocs/microsoft-365-docs pull request #6528
Opened 2021-10-06 12:53 UTC by msbemba

Updated instructions to get access to onedrive

2021-10-06 12:54 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6484

2021-10-06 12:54 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-07 04:23 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-4.md
> +3. In the user properties page, select **OneDrive**. Under **Get access to files**, select **Create link to files**.
```suggestion
3. On the user properties page, select **OneDrive**. Under **Get access to files**, select **Create link to files**.
```

2021-10-07 04:24 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-07 12:57 UTC, JohanFreelancer9 approved these changes

2021-10-10 07:17 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-10-21 17:39 UTC, merged