Update secure-by-default.md
MicrosoftDocs/microsoft-365-docs pull request #6547
Opened 2021-10-08 03:28 UTC by msbemba

Added a note about tenant override taking effect versus Secure by default if MX is not pointing to EOP.

2021-10-08 03:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-08 03:29 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6427

2021-10-08 08:02 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/secure-by-default.md
> +> In case, a third party spam filter exists or MX record is not point to EOP, tenant overrides are applied.
```suggestion
> If a third-party spam filter exists or the MX record does not point to EOP, tenant overrides are applied.
```

2021-10-08 08:04 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-08 11:02 UTC, yogkumgit commented
@msbemba

2021-10-08 13:22 UTC, JohanFreelancer9 approved these changes

2021-10-10 06:29 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2021-10-25 07:08 UTC, yogkumgit commented
@MSFTTracyP Gentle reminder.

2021-11-12 23:15 UTC, chrisda commented
Closing, because the addition is confusing and not correct. There is absolutely no way to allow malware (always) or high-confidence phishing messages (recently) into the service, even if you have an override configured. This includes customers with a service or device sitting in front of Microsoft 365.

2021-11-12 23:15 UTC, closed without merging