Updated Links
MicrosoftDocs/microsoft-365-docs pull request #655
Opened 2019-10-30 23:15 UTC by alyboyd

Updated links, specifically links in document to bibliography.  Made some verbiage adjustments.  Corrected for accuracy.

2019-10-31 09:31 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-10-31 11:42 UTC, JohanFreelancer9 commented on microsoft-365/compliance/gdpr-arc-prof-services.md
> +|***Privacy impact assessment (7.2.5)***|The customer should be aware of requirements for completing privacy impact assessments (when they should be performed, categories of data that might necessita
```suggestion
|***Privacy impact assessment (7.2.5)***|The customer should be aware of requirements for completing privacy impact assessments (when they should be performed, categories of data that might necessitate one, timing of completing the assessment).|Microsoft Professional Services provides guidance as to when and how to determine when to perform a DPIA, and an overview of the DPIA program at Microsoft including the involvement of the DPO, which is provided n the Service Trust Portal *Data* [Protection, Impact Assessments (DPIAs) page](https://servicetrust.microsoft.com/ViewPage/GDPRDPIA).<p>For support for your DPIAs see:<br>- Key Information from Microsoft Professional Services for Customer Data Protection Impact Assessments [[9](gdpr-arc-prof-services.md#9)]</p>|Article (35)|
```

2019-10-31 11:44 UTC, JohanFreelancer9 commented on microsoft-365/compliance/gdpr-arc-prof-services.md
>  |***Records related to processing PII (7.2.7)***|The customer should maintain all necessary and required records related to processing personal data (for example, purpose, security measures, etc.). W
```suggestion
|***Records related to processing PII (7.2.7)***|The customer should maintain all necessary and required records related to processing personal data (for example, purpose, security measures, etc.). Where some of these records must be provided by a sub-processor, the customer should ensure that they can obtain such records.|Microsoft Professional Services maintains records necessary to demonstrate compliance and support for accountability under the GDPR. See the Microsoft Professional Services Security Documentation [[2](gdpr-arc-prof-services.md#2)]|(5)(2), (24)(1), (30)(1)(a), (30)(1)(b), (30)(1)(c), (30)(1)(d), (30)(1)(g), (30)(1)(f), (30)(3), (30)(4), (30)(5)|
```

2019-10-31 11:50 UTC, JohanFreelancer9 commented on microsoft-365/compliance/gdpr-arc-prof-services.md
> +| ***Provide mechanism to modify or withdraw consent (7.3.4)*** | The customer should understand requirements for informing users about their right to access, correct, and/or erase their personal dat
```suggestion
| ***Provide mechanism to modify or withdraw consent (7.3.4)*** | The customer should understand requirements for informing users about their right to access, correct, and/or erase their personal data and for providing a mechanism for them to do so. If a third-party system is used and provides this mechanism as part of its functionality, the customer should utilize that functionality as necessary. | Information about capabilities in Microsoft services that you can use when defining the information you provide to data subjects when requesting consent.<br>- Microsoft Professional Services Data Subject Requests for the GDPR [[7](gdpr-arc-prof-services.md#7)] | (7)(3), (13)(2)(c), (14)(2)(d), (18)(1)(a), (18)(1)(b), (18)(1)(c), (18)(1)(d) |
```

2019-10-31 11:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/gdpr-arc-prof-services.md
> +| ***Correction or erasure (7.3.7)*** | The customer should understand requirements for informing users about their right to access, correct, and/or erase their personal data and for providing a mech
```suggestion
| ***Correction or erasure (7.3.7)*** | The customer should understand requirements for informing users about their right to access, correct, and/or erase their personal data and for providing a mechanism for them to do so. If a third-party system is used and provides this mechanism as part of its functionality, the customer should utilize that functionality as necessary. | Information about Microsoft services relating to their ability to access, correct, or erase personal data that you can include in the data you provide to data subjects.<br>- Microsoft Professional Services Data Subject Requests for the GDPR [[7](gdpr-arc-prof-services.md#7)]||
```

2019-10-31 12:23 UTC, JohanFreelancer9 requested changes
Copy Review

2019-10-31 12:33 UTC, mypil commented
@alyboyd - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-10-31 18:45 UTC, alyboyd commented
This has been completed.  Please let me know if there is anything else needed on my end.

Thanks,
Aly

From: Joyce Y. <notifications@github.com>
Sent: Thursday, October 31, 2019 5:33 AM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Aly Boyd (RedClound Inc) <v-alybo@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Updated Links (#655)


@alyboyd<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falyboyd&data=02%7C01%7Cv-alybo%40microsoft.com%7Ccfa5e78fd7024a69fd0d08d75dfe87e3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637081220114688802&sdata=nKBlWKOVziybWd0a2%2F1yCfydavMBpUL5k%2FLD3XwC69A%3D&reserved=0> - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F655%3Femail_source%3Dnotifications%26email_token%3DALUMJWOGBHNRZZJJ52RUKATQRLGBPA5CNFSM4JHBT5ZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECXSYTI%23issuecomment-548351053&data=02%7C01%7Cv-alybo%40microsoft.com%7Ccfa5e78fd7024a69fd0d08d75dfe87e3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637081220114698797&sdata=4qu%2FmAuhvmrFwzW%2FPOVqe33vp3XNu6v3nPWDktXTbSo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALUMJWJGFMCDH72JYX6OXALQRLGBPANCNFSM4JHBT5ZA&data=02%7C01%7Cv-alybo%40microsoft.com%7Ccfa5e78fd7024a69fd0d08d75dfe87e3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637081220114698797&sdata=guOU14cIHh7Dh72E2ULKSMQRY9O5lT7rPpPpZ7FYFGA%3D&reserved=0>.

2019-11-01 15:41 UTC, mypil commented
@robmazz - PR has been copy edited and is ready for final review. Please take note that this is a GDPR topic so I will leave it to your discretion whether to merge this PR or not. 

Thank you.

cc: @kenwith

2019-11-01 23:48 UTC, robmazz commented
@alyboyd - thanks for the feedback, but this is more tightly controlled topic that requires review and approval by our legal department. We do not accept verbiage updates to this topic.

2019-11-01 23:48 UTC, closed without merging

2019-11-01 23:51 UTC, alyboyd commented
Hi Robert,

Please advise who should review these changes.  It was mainly changes to correct links that were inaccurate (links in document that point to links in the bibliography).  We have updated this before without further legal review.  Is this a new process?

Thanks,
Aly

From: Robert Mazzoli <notifications@github.com>
Sent: Friday, November 1, 2019 4:48 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Aly Boyd (RedClound Inc) <v-alybo@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Updated Links (#655)


@alyboyd<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falyboyd&data=02%7C01%7Cv-alybo%40microsoft.com%7C380f2402e15f45eb0d9808d75f25f735%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637082488992395345&sdata=QwlWq7dSsbjMWHrRt0Ov5EeWmb0ateVAOPdgS8d2Qks%3D&reserved=0> - thanks for the feedback, but this is more tightly controlled topic that requires review and approval by our legal department. We do not accept verbiage updates to this topic.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F655%3Femail_source%3Dnotifications%26email_token%3DALUMJWIPGA5LIZG2O43ELT3QRS537A5CNFSM4JHBT5ZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC4NZFA%23issuecomment-548986004&data=02%7C01%7Cv-alybo%40microsoft.com%7C380f2402e15f45eb0d9808d75f25f735%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637082488992405337&sdata=IK3IMgaop55ukMkQm5BSTLUuDHA2Ed6tIcPg50J7KW0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALUMJWMYEJ2EQCV76PAQEC3QRS537ANCNFSM4JHBT5ZA&data=02%7C01%7Cv-alybo%40microsoft.com%7C380f2402e15f45eb0d9808d75f25f735%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637082488992405337&sdata=qcK7paOxQx699YylKh7RFRqeQRBSfBTpzH%2FTolszvqQ%3D&reserved=0>.