Update encryption-office-365-certificate-chains.md
MicrosoftDocs/microsoft-365-docs pull request #6551
Opened 2021-10-08 06:26 UTC by msbemba

Added details about ISRG Root X1 as it replaces the DST root CA X3 which got expired last month.

2021-10-08 06:26 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-08 06:26 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6369

2021-10-08 08:45 UTC, JohanFreelancer9 commented on microsoft-365/compliance/encryption-office-365-certificate-chains.md
> +| **Public Key Length** | RSA 4096 bit) |
```suggestion
| **Public Key Length** | RSA 4096 bit |
```

2021-10-08 08:45 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-08 13:21 UTC, JohanFreelancer9 approved these changes

2021-10-10 07:05 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2021-10-25 07:10 UTC, yogkumgit commented
@KCCross Gentle reminder.

2021-11-02 21:40 UTC, LauraWi commented
Assigning to @kelleyvice-msft

2021-11-03 16:51 UTC, kelleyvice-msft commented
I am assuming that this certificate has not been updated in the related .p7b file, so I will make that change and investigate whether other changes may be required due to other updates while I've been on leave.

2021-11-03 16:52 UTC, merged