Update office-365-network-mac-perf-overview.md
MicrosoftDocs/microsoft-365-docs pull request #6560
Opened 2021-10-08 20:50 UTC by pandrew1

I added some extra detail on how to add a LAN IP Address for matching a new location. We are seeing lots of customer escalations for people not being able to make this work and trying to make it clearer. 

@kelleyvice-msft

2021-10-10 07:43 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-10-11 01:51 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +<<<<<<< Updated upstream
```suggestion
#### Update upstream

```

2021-10-11 01:59 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +You also need to add locations in the Admin Center network connectivity page or to import those from a CSV file as described below. The locations added must include your office LAN subnet information
```suggestion
Make sure that you also add locations in the admin center network connectivity page or import those from a CSV file. The locations added must include your office LAN subnet information. In the dialog for adding or editing a location, you can specify a number of LAN subnets and a number of public egress IP subnets. The LAN subnets are required and one of them must match the LAN subnet attribute on a received network assessment for results to show up. Super nets are not supported so the LAN subnet must match exactly.

Note that usually, LAN subnets are private IP address ranges as defined in RFC1918 such that the use of public IP addresses as the LAN subnets is likely to be incorrect. The dialog will show suggestions of LAN subnets that have been seen in recent network assessment tests for your organization so that you can choose.

If you add public egress IP addresses, these are used as a secondary differentiator and are intended for when you have multiple sites using the same LAN subnet IP address ranges. To make sure your test results show up, you should start by leaving the public egress IP address ranges blank. If they are included then a test result must match both one of the LAN subnet IP address ranges and one of the public egress IP address ranges.
```

2021-10-11 01:59 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +>>>>>>> Stashed changes
```suggestion
#### Stashed changes
```

2021-10-11 02:04 UTC, JohanFreelancer9 requested changes
Copy review - suggestions only. Not sure if my interpretation is correct.

2021-10-11 06:36 UTC, yogkumgit commented
@pandrew1

2021-10-18 13:40 UTC, yogkumgit commented
@pandrew1 Gentle reminder, please implement the suggested changes, if you agree. Thanks

2021-10-19 02:59 UTC, pandrew1 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +<<<<<<< Updated upstream
These words "updated upstream" is a result of some kind of git error. I'll try to remove them separately

2021-10-19 03:00 UTC, pandrew1 commented on microsoft-365/enterprise/office-365-network-mac-perf-overview.md
> +>>>>>>> Stashed changes
These words "Stashed changes" are a result of some GIT error. I'll try to remove them selarately

2021-10-19 03:07 UTC, pandrew1 commented
@yogkumgit Please advise next steps for publishing

2021-10-19 03:48 UTC, JohanFreelancer9 approved these changes

2021-10-19 10:10 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2021-10-20 14:41 UTC, merged