Updated Block abuse of exploited vulnerable signed drivers
MicrosoftDocs/microsoft-365-docs pull request #6564
Opened 2021-10-11 06:16 UTC by JoelJerkin

Updated technical accuracy for Block abuse of exploited vulnerable signed drivers since it's not available yet in Intune or Configuration Manager yet.'
#ATCP

2021-10-11 07:19 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-10-11 09:24 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/attack-surface-reduction-rules.md
> +Intune Name: `Block abuse of exploited vulnerable signed drivers` (Not yet available)
```suggestion
Intune Name: `Block abuse of exploited vulnerable signed drivers` (not yet available)
```

2021-10-11 09:25 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-10-12 10:58 UTC, yogkumgit commented
@JoelJerkin Please implement the feedback. Thanks

2021-10-12 11:35 UTC, JoelJerkin commented
> @JoelJerkin Please implement the feedback. Thanks

Done!

2021-10-12 13:06 UTC, JohanFreelancer9 approved these changes

2021-10-12 14:45 UTC, yogkumgit commented
@jweston-1 Please merge this PR. Thanks.

2021-10-14 17:30 UTC, BarbaraSelden commented
@jweston-1 this contribution now appears to be out of date (branch) but still needs to be published. Can you help?

2021-10-15 04:34 UTC, yogkumgit commented
@JoelJerkin

2021-10-15 05:22 UTC, JoelJerkin commented
@BarbaraSelden @yogkumgit Done!

2021-10-18 08:21 UTC, yogkumgit commented
@jweston-1 /@BarbaraSelden Please merge this PR. Thanks

2021-10-21 17:02 UTC, BarbaraSelden commented
I dont have rights to this repo which is why i asked @jweston-1 to merge. can this get done today please?

2021-10-21 17:23 UTC, merged

2021-10-21 18:36 UTC, jweston-1 commented
Merged, per request.