Clarified the use of the AIP client in coexistence with built-in labels (added paragraphs in the right order this time)
MicrosoftDocs/microsoft-365-docs pull request #6586
Opened 2021-10-13 00:49 UTC by E-Saggese

…ls (in the right order this time)

The vast majority of customers interviewed didn't know this critical scenario was an option, and as a result most of them were not using built-in labels in Office.

2021-10-13 03:16 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-10-13 07:39 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitivity-labels-office-apps.md
> +You may want to use the built-in sensitivity labeling capabilities in Office to benefit from the latest features and enhance user experience while at the same time having the abilit to label and prot
```suggestion
You might want to use the built-in sensitivity labeling capabilities in Office to benefit from the latest features and enhance user experience while at the same time having the ability to label and protect non-Office files from the desktop with the Azure Information Protection client. 
```

2021-10-13 07:40 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitivity-labels-office-apps.md
> +By default, if users have the [Azure Information Protection client installed](/azure/information-protection/rms-client/aip-clientv2) the built-in labeling client is turned off in their Office apps an
```suggestion
By default, if users have the [Azure Information Protection client installed](/azure/information-protection/rms-client/aip-clientv2), the built-in labeling client is turned off in their Office apps and the plug-in functionality is used instead. 
```

2021-10-13 07:42 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitivity-labels-office-apps.md
> +To maintain the ability to use the Azure Information Protection clientfor labeling non-Office files from the desktop without disabling the built-in labeling functinality within Office apps, we recomm
```suggestion
To maintain the ability to use the Azure Information Protection client for labeling non-Office files from the desktop without disabling the built-in labeling functionality within Office apps, we recommend you use the Group Policy setting **List of managed add-ins** as documented in [No Add-ins loaded due to group policy settings for Office 2013 and Office 2016 programs](https://support.microsoft.com/help/2733070/no-add-ins-loaded-due-to-group-policy-settings-for-office-2013-and-off).
```

2021-10-13 07:48 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitivity-labels-office-apps.md
> +You can also use the following registry value to quickly toggle between using the Azure Information Protection plugin and built-in sensitivity labels in Office apps:
```suggestion
You can also use the following registry value to quickly toggle between using the Azure Information Protection plug-in and built-in sensitivity labels in Office apps:
```

2021-10-13 07:52 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitivity-labels-office-apps.md
> +Setting this value to 1 enables the built-in sensitivity labeling options in Office, setting it to 0 enables the AIP plugin if it is installed.
```suggestion
Setting this value to **1** enables the built-in sensitivity labeling options in Office; setting it to **0** enables the AIP plug-in if it is installed. 
```

2021-10-13 07:56 UTC, JohanFreelancer9 requested changes
Copy review - @E-Saggese, kindly commit the suggested changes. Many thanks.

2021-10-14 02:59 UTC, E-Saggese commented
Hi @JohanFreelancer9, apologies for my ignorance, I committed the changes, but do I need to close the pull request? When I do it tells me the branch has uncommitted changes.

2021-10-14 06:50 UTC, JohanFreelancer9 approved these changes
@E-Saggese, thank you for committing the changes. No, please don't close the pull request. It needs to be approved by the document author/manager, and will then be merged.

2021-10-14 14:55 UTC, yogkumgit commented
@cabailey Please merge this PR. Thanks

2021-10-25 07:13 UTC, yogkumgit commented
@cabailey Gentle reminder.

2021-10-29 01:34 UTC, cabailey commented
Closing after discussion with contributor

2021-10-29 01:34 UTC, closed without merging