Update manage-groups.md
MicrosoftDocs/microsoft-365-docs pull request #6653
Opened 2021-10-20 19:43 UTC by msbemba

Added a note about the time it takes to propagate the changes made to let external users email the group.

2021-10-20 19:43 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-20 19:43 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6612

2021-10-21 04:57 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/manage-groups.md
> +> The changes could take 30 minutes to propogate and let external users email the organization.
```suggestion
> The changes could take up to 30 minutes to propagate and let external users email the organization.
```

2021-10-21 04:58 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-21 06:24 UTC, yogkumgit commented
@msbemba

2021-10-22 04:44 UTC, yogkumgit commented
@JohanFreelancer9

2021-10-22 09:07 UTC, JohanFreelancer9 approved these changes

2021-10-25 05:55 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-10-25 12:35 UTC, merged