Update secure-by-default.md
MicrosoftDocs/microsoft-365-docs pull request #6656
Opened 2021-10-20 20:03 UTC by msbemba

Added steps to configure the delivery of Simulations to users

2021-10-20 20:03 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6613

2021-10-20 20:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-21 04:51 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/secure-by-default.md
> +- Phishing simulations: Simulated attacks can help you identify vulnerable users before a real attack impacts your organization. Find more information on [how to Configure the delivery of third-party
```suggestion
- Phishing simulations: Simulated attacks can help you identify vulnerable users before a real attack impacts your organization. Find more information on [how to Configure the delivery of third-party phishing simulations to users and unfiltered messages to SecOps mailboxes](/security/office-365-security/configure-advanced-delivery).
```

2021-10-21 04:52 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-21 06:29 UTC, yogkumgit commented
@msbemba

2021-10-22 04:44 UTC, yogkumgit commented
@JohanFreelancer9

2021-10-22 09:13 UTC, JohanFreelancer9 approved these changes

2021-10-25 05:56 UTC, yogkumgit commented
@MSFTTracyP Please merge  this PR. Thanks

2021-11-13 00:27 UTC, merged