Update activity-reports.md
MicrosoftDocs/microsoft-365-docs pull request #6658
Opened 2021-10-20 21:58 UTC by msbemba

Removed the numbers as it is not accurate.

2021-10-20 21:58 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-20 21:58 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6590

2021-10-21 03:38 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/activity-reports.md
> +Whenever you close a user's account, Microsoft will delete that user's usage data within 30 days. That user will still be included in the Activity chart totals for the periods she was active in, but
```suggestion
Whenever you close a user's account, Microsoft will delete that user's usage data within 30 days. That user will still be included in the Activity chart totals for the periods the user was active in, but will not appear in the User Details table.
```

2021-10-21 03:39 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-21 06:47 UTC, yogkumgit commented
@msbemba

2021-10-21 17:33 UTC, merged