Diagnostic that can be run in context of M365 Administrator
MicrosoftDocs/microsoft-365-docs pull request #6668
Opened 2021-10-21 19:03 UTC by petey121175

I would like to provide this link as a button like what is seen in this article: https://docs.microsoft.com/en-us/sharepoint/troubleshoot/sharing-and-permissions/access-denied-due-to-org-policies 

This diagnostic is intended to identify site/page performance issues in the context as a Microsoft 365 Administrator. It will bring the user to the MAC portal and all they need to do is click Run.

2021-10-25 07:17 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-10-25 09:31 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/diagnosing-performance-issues-with-sharepoint-online.md
> +This topic describes how to use each of these methods to diagnose performance issues. Once you've figured out the cause of the problem, you can work toward a solution using the articles about improvi
```suggestion
This topic describes how to use each of these methods to diagnose performance issues. Once you've figured out the cause of the problem, you can work toward a solution using the articles about improving SharePoint performance that you can find on https://aka.ms/tune. Alternatively, if you are an administrator and you want to diagnose the issue quickly, [run this diagnostic tool](https://aka.ms/PillarSiteandPagePerf). 
```

2021-10-25 09:33 UTC, JohanFreelancer9 requested changes
Copy review. @petey121175, kindly commit the suggested changes. Many thanks.

2021-10-29 05:17 UTC, yogkumgit commented
@petey121175 Please commit the suggested changes.

2021-10-29 20:58 UTC, petey121175 commented
@yogkumgit @JohanFreelancer9 thank you and sorry for the delay.

2021-10-30 05:03 UTC, JohanFreelancer9 approved these changes

2021-11-01 04:39 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2021-11-01 19:11 UTC, merged