Add a table to tell the availability of each report in each environment
MicrosoftDocs/microsoft-365-docs pull request #6672
Opened 2021-10-22 06:36 UTC by guochen2010

2021-10-25 07:18 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-10-26 07:40 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/activity-reports.md
> +[^2]: The service is not available in the environment so no plan to release the report.
```suggestion
[^1] The report is planned to be released in the future. The <a href="https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=" target="_blank">Microsoft 365 Roadmap</a> will be updated before the release.
[^2] The service is not available in the environment so there is no plan to release the report.
```

2021-10-26 07:56 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/browser-usage-report.md
> +The Microsoft 365 Reports dashboard shows you an activity overview across the products in your organization. It enables you to drill into individual product level reports to give you more granular in
```suggestion
The Microsoft 365 Reports dashboard shows you an activity overview across the products in your organization. It enables you to drill in to individual product level reports to give you more granular insight about the activities within each product. Check out [the Reports overview topic](activity-reports.md). In the Microsoft browser usage report, you can gain insights on Internet Explorer, Microsoft Edge Legacy, and new Microsoft Edge usage. Usage reporting is based on Microsoft 365 online services accessed by using a Microsoft browser.
```

2021-10-26 07:58 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/yammer-activity-report-ww.md
> +As Microsoft 365 admin, the Reports dashboard shows you data on the usage of the products within your organization. Check out [activity reports in the admin center](activity-reports.md). With the **Y
```suggestion
As Microsoft 365 admin, the Reports dashboard shows you data on the usage of the products within your organization. Check out [activity reports in the admin center](activity-reports.md). With the **Yammer Activity report**, you can understand the level of engagement of your organization with Yammer by looking at the number of unique users using Yammer to post, like, or read a message and the amount of activity generated across the organization. 
```

2021-10-26 07:59 UTC, JohanFreelancer9 requested changes
Copy review - @guochen2010, kindly commit the minor additional suggested changes. Many thanks.

2021-10-27 20:25 UTC, merged