Update endpoint-dlp-getting-started.md
MicrosoftDocs/microsoft-365-docs pull request #6694
Opened 2021-10-26 06:21 UTC by msbemba

Made changes to navigation

2021-10-26 06:21 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6662

2021-10-26 06:21 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-26 09:54 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-getting-started.md
> +2. Choose **settings**  and choose **Device Onboarding**.
```suggestion
2. Choose **Settings** > **Device onboarding**.
```

2021-10-26 09:55 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-29 04:46 UTC, yogkumgit commented
@msbemba

2021-10-29 08:54 UTC, JohanFreelancer9 approved these changes

2021-11-01 04:06 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2021-11-05 19:58 UTC, merged