Update domains-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #6695
Opened 2021-10-26 06:23 UTC by msbemba

Added Cloudflare to the list as it also supports All DNS records.

2021-10-26 06:23 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6664

2021-10-26 06:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-10-26 09:47 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/domains-faq.yml
> +          - CloudFlare
```suggestion
          - Cloudflare
```

2021-10-26 09:47 UTC, JohanFreelancer9 requested changes
Copy review.

2021-10-26 10:04 UTC, JohanFreelancer9 approved these changes

2021-10-29 04:49 UTC, yogkumgit commented
@scotvidican Please merge this PR. Thanks

2021-11-05 04:33 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks

2022-02-08 15:13 UTC, yogkumgit commented
@pebaum Gentle reminder.

2022-02-08 16:45 UTC, merged