Adding rules.md for infra folders and registry keys
MicrosoftDocs/microsoft-365-docs pull request #6708
Opened 2021-10-27 05:54 UTC by AndreiCsibi-msft

2021-10-29 05:18 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-10-29 07:33 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +All application or tests in Test Base need to follow the following rules:
```suggestion
All applications or tests in Test Base need to comply with the following rules:
```

2021-10-29 07:33 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +## Test Base Folders
```suggestion
## Test Base folders 
```

2021-10-29 07:33 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +> **Avoid the following:**
```suggestion
> **Avoid the following**:
```

2021-10-29 07:34 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +> * Blocking the execution of any process from these folders. If your application is an anti-malware software, configure your app installation to allow unimpeded execution of all processes from these
```suggestion
> * Blocking the execution of any process from these folders. If your application is anti-malware software, configure your app installation to allow unimpeded execution of all processes from these folders.
```

2021-10-29 07:34 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +> * Tampering with of these folders.
```suggestion
> * Tampering with any of these folders.
```

2021-10-29 07:35 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +## Test Base Registry Keys
```suggestion
## Test Base registry keys
```

2021-10-29 07:38 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +The applications/tests should not delete/modify any registry keys related to:
```suggestion
The applications/tests should not delete or modify any registry keys related to:
```

2021-10-29 07:38 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +* Windows Telemetry level
```suggestion
* Windows telemetry level
```

2021-10-29 07:40 UTC, JohanFreelancer9 commented on microsoft-365/test-base/rules.md
> +# Application / Test rules
```suggestion
# Application/Test rules
```

2021-10-29 07:42 UTC, JohanFreelancer9 requested changes
Copy review - @AndreiCsibi-msft, kindly commit the suggested changes if you agree with them. Many thanks.

2021-11-01 04:09 UTC, yogkumgit commented
@AndreiCsibi-msft Gentle remnder

2021-11-01 16:55 UTC, AndreiCsibi-msft commented
> @AndreiCsibi-msft Gentle remnder

@yogkumgit : I'll take a look at these comments later today. Thanks a lot!

2021-11-02 04:38 UTC, JohanFreelancer9 approved these changes

2021-11-02 12:35 UTC, yogkumgit commented
@mansipatel-usl Please merge this PR. Thanks

2021-11-02 17:45 UTC, AndreiCsibi-msft commented
@yogkumgit: Is there anyone else who can review/merge this PR if needed? Mansi is OOF for another week.

2021-11-03 07:59 UTC, yogkumgit commented
@tiburd Please help

2021-11-03 15:50 UTC, tiburd commented
@AndreiCsibi-msft 

This pull request was opened in the public repo. PMs and content developers should work in the private repo, per the [MARVEL Authoring Guide for Docs](https://review.docs.microsoft.com/en-us/office-authoring-guide/office-docs-authoring-overview?branch=master). 

Please create a PR in the private repo to submit this content update. We'll close this PR. 

Thanks!

2021-11-03 15:50 UTC, closed without merging