Update endpoint-dlp-learn-about.md
MicrosoftDocs/microsoft-365-docs pull request #6769
Opened 2021-11-02 23:16 UTC by MasLibman

Fixing Windows 10/11
@chrfox

2021-11-03 08:31 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-11-03 10:36 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-learn-about.md
> +Microsoft Endpoint DLP enables you to audit and manage the following types of activities users take on sensitive items that are physically stored Windows 10, Windows 11, or macOS devices.
```suggestion
Microsoft Endpoint DLP enables you to audit and manage the following types of activities users take on sensitive items that are physically stored on Windows 10, Windows 11, or macOS devices.
```

2021-11-03 10:37 UTC, JohanFreelancer9 requested changes
Copy review - @MasLibman, kindly commit the minor additional suggestion. Many thanks.

2021-11-05 04:35 UTC, yogkumgit commented
@MasLibman Please update the changes.

2021-11-05 20:22 UTC, merged