Update endpoint-dlp-getting-started.md
MicrosoftDocs/microsoft-365-docs pull request #6770
Opened 2021-11-02 23:19 UTC by MasLibman

I suggest we optimize towards mentioning windows 10 / 11 when setting context and in requirements and then leaving it at "Windows".

I dont think onboarding needs to mention Windows version unless there is a specific different for onboarding based upon Windows version. 
@chrfox

2021-11-03 08:32 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-11-03 10:24 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-getting-started.md
> +### Prepare your Windows 10/11 endpoints
```suggestion
### Prepare your Windows 10/Windows 11 endpoints
```

2021-11-03 10:24 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-getting-started.md
> +1. The following Updates are installed on Windows 10 devices
```suggestion
1. The following updates are installed on Windows 10 devices
```

2021-11-03 10:28 UTC, JohanFreelancer9 requested changes
Copy review - @MasLibman, kindly commit the minor suggested changes if you agree with them. Many thanks.

2021-11-05 04:35 UTC, yogkumgit commented
@MasLibman Please implement the changes, if you agree. Thanks

2021-11-05 20:24 UTC, merged