Update post-ti-indicator.md
MicrosoftDocs/microsoft-365-docs pull request #6809
Opened 2021-11-05 06:26 UTC by msbemba

Updated the action setting "GenerateAlert" is an item that must be set to "TRUE" when creating an action with "Audit".

2021-11-05 06:26 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-05 06:26 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6717

2021-11-05 08:28 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/post-ti-indicator.md
> +action|Enum|The action that will be taken if the indicator will be discovered in the organization. Possible values are: "Alert", "Warn", "Block", "Audit, "BlockAndRemediate", "AlertAndBlock", and "Al
```suggestion
action|Enum|The action that will be taken if the indicator will be discovered in the organization. Possible values are: "Alert", "Warn", "Block", "Audit, "BlockAndRemediate", "AlertAndBlock", and "Allowed". **Required**. The "GenerateAlert" parameter must be set to "TRUE" when creating an action with "Audit".
```

2021-11-05 08:29 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, kindly commit the suggested changes if you agree with it. Many thanks.

2021-11-05 09:56 UTC, JohanFreelancer9 approved these changes

2021-11-07 05:32 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-11-22 21:59 UTC, merged