What data is not protected via customer key
MicrosoftDocs/microsoft-365-docs pull request #681
Opened 2019-11-05 12:44 UTC by joinimran

As per user recommendation got by MS support, I have added another query whereas it mentioned what data is not protected by customer key.

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/634

2019-11-05 15:02 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-06 03:13 UTC, JohanFreelancer9 commented on microsoft-365/compliance/service-encryption-with-customer-key-faq.md
> +Customer Key is only used to encrypt files, it does not encrypt any other SharePoint Online content such as metadata in documents and libraries, data in lists except attachments, data stored in user
```suggestion
Customer Key is only used to encrypt files. It does not encrypt any other SharePoint Online content such as metadata in documents and libraries, data in lists except attachments, data stored in user profiles, data stored in search indices, and data stored in other services such as Planner, Stream, Delve, Microsoft Teams, Yammer, etc.
```

2019-11-06 03:14 UTC, JohanFreelancer9 requested changes
Copy Review

2019-11-06 05:42 UTC, joinimran commented
Ready to go live

2019-11-06 14:53 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review based on issue #634. 

Thank you.

cc: @kenwith

2019-12-02 14:49 UTC, joinimran commented
@KCCross , A followup on this PR. Did you get a chance to review the PR? Its already been copy-edited.

2019-12-06 14:23 UTC, mypil commented
@KCCross @LauraWi - Can anyone of you please assist to review and merge this PR?

Thank you.

2019-12-06 17:57 UTC, LauraWi commented
@KC Cross<mailto:KC.Cross@microsoft.com> – does this need PM review?

From: Joyce Y. <notifications@github.com>
Sent: Friday, December 6, 2019 6:24 AM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Laura Williams <Laura.Williams@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] What data is not protected via customer key (#681)


@KCCross<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKCCross&data=02%7C01%7CLaura.Williams%40microsoft.com%7Cdc8837b1300d4c91c59408d77a57dff7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637112390158108294&sdata=6J2mYGqqVSZdxKjOQJQyX7VTHKA2liQyl7vGS0O1TAs%3D&reserved=0> @LauraWi<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLauraWi&data=02%7C01%7CLaura.Williams%40microsoft.com%7Cdc8837b1300d4c91c59408d77a57dff7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637112390158108294&sdata=JVnKuTi74C7hRefdmWF3dIaqb%2BiOwmvz688heGSGkxY%3D&reserved=0> - Can anyone of you please assist to review and merge this PR?

Thank you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F681%3Femail_source%3Dnotifications%26email_token%3DAH243MI2CCWB42LKM4ALSRTQXJN6JA5CNFSM4JJCC7D2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGEHGKI%23issuecomment-562590505&data=02%7C01%7CLaura.Williams%40microsoft.com%7Cdc8837b1300d4c91c59408d77a57dff7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637112390158108294&sdata=dg7ESb0OX0gRNrdEf1tiPHBvFtWJQUIod37fjCGyxaY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAH243MJZCCXVXEHHSQVOXVLQXJN6JANCNFSM4JJCC7DQ&data=02%7C01%7CLaura.Williams%40microsoft.com%7Cdc8837b1300d4c91c59408d77a57dff7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637112390158118244&sdata=5jBPTkr1LdqZCtZC7zLrJPzu%2BecnT2lu9PxbHAcOXQs%3D&reserved=0>.

2019-12-06 20:12 UTC, KCCross commented
The content in this PR is not entirely accurate. Reviewing with PM before rolling out update.

2019-12-14 00:37 UTC, mypil commented
@KCCross - Do you have any updates on this? 
Please let us know if there are any changes needed for this PR so we can let @joinimran make the change. 

Thank you.

2020-01-08 15:19 UTC, mypil commented
@KCCross - We would like to follow up. Any updates on this?

Thank you.

2020-01-14 00:33 UTC, MSFTTracyP requested changes
Also, cached content, any web part data, solutions, and other SharePoint customizations. Also, files synced down to a desktop or mobile device. Basically, Customer Key works for SPO, EXO, Teams (if you're using SPO for data storage), and some Skype for Business features (yes, for texts, no for recordings, and content uploads). Be aware, for the most part, we document what Customer Key covers, not what it does not cover.

2020-01-14 08:34 UTC, joinimran commented
@MSFTTracyP You are suggesting to make this change as 

Customer Key is only used to encrypt files, cached content, any web part data, solutions, and other SharePoint customizations. It is also used for files synced down to a desktop or mobile device. Customer Key works for SharePoint Online, Exchange Online, Team (if you are using SharePoint Online for data storage) and some Skype for business features.

2020-01-14 17:49 UTC, MSFTTracyP commented
@joinimran - Ohp. Teams. Not Team. To clarify, it _isn't_ used for files synced down to the desktop or mobile devices, cached content, web part data, solutions, and other SharePoint customizations. I'm sorry that was unclear. I was listing additional things it doesn't encrypt. It _is_ used for SharePoint Online, Exchange Online, Teams (if you are using SharePoint Online for data storage) and some Skype for Business features.

2020-01-14 19:17 UTC, joinimran commented
@MSFTTracyP I got your point here that means we are going with a statement **It is used for SharePoint Online, Exchange Online, Teams (if you are using SharePoint Online for data storage) and some Skype for Business features.** Not with any other details like it doesn't work with ... as you have already mentioned that we tell it works with, not where it will not work. Correct?

2020-01-14 19:55 UTC, KCCross commented
Hello everyone,
I’ve returned from vacation and from wide-ranging power outages in my area. I’ll touch base with Tracy shortly and pick up where we left off. Thanks,
KC

From: ImranHabib <notifications@github.com>
Sent: Tuesday, January 14, 2020 11:17 AM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: KC Cross <KC.Cross@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] What data is not protected via customer key (#681)


@MSFTTracyP<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMSFTTracyP&data=02%7C01%7CKC.Cross%40microsoft.com%7C89c68d2816824e7f7bca08d7992663ec%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637146262482249041&sdata=BqNSaYcZBXBmQMq84tredkYffWzP%2FkuumOrIY%2F9HsBs%3D&reserved=0> I got your point here that means we are going with a statement It is used for SharePoint Online, Exchange Online, Teams (if you are using SharePoint Online for data storage) and some Skype for Business features. Not with any other details like it doesn't work with ... as you have already mentioned that we tell it works with, not where it will not work. Correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F681%3Femail_source%3Dnotifications%26email_token%3DAG6CYYIKH5A4WEIJKMJ5JZLQ5YFULA5CNFSM4JJCC7D2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI5ZCMI%23issuecomment-574329137&data=02%7C01%7CKC.Cross%40microsoft.com%7C89c68d2816824e7f7bca08d7992663ec%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637146262482259037&sdata=wSyaqBVF9kd%2F83%2BWHyFquoOVzRl%2BhrBzw73nUsIl1M0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG6CYYNC6ESE5XZFKBI7U63Q5YFULANCNFSM4JJCC7DQ&data=02%7C01%7CKC.Cross%40microsoft.com%7C89c68d2816824e7f7bca08d7992663ec%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637146262482259037&sdata=Vz9AeGtbViXvX%2B%2FKudPqFR%2FwAgeJssoZHICgWCusXOk%3D&reserved=0>.

2020-01-14 21:38 UTC, MSFTTracyP commented
@joinimran - So here's the rub. The question isn't 'What is protected by customer key?' it's 'What data is not protected via customer key?' In my opinion, we should always try to stick with the more concise 'what _is_ protected by Customer Key' info, as specifically as we can. But if the FAQ question is ~ what's not protected, and we can't ignore that question. The problem with the question is that I can say 'items in your purse' and be correct. When we answer this, we should acknowledge the scope of the question, and say that information about what _is_ protected will be more fleshed-out, and should be where customers' turn, first.

KC may choose to change the question in the FAQ if she feels this is needed, but there is value in letting customers know what doesn't fall under Customer Key and where they may want to look for further technologies (like device-based conditional access policies, and Azure Information Protection, both of which you can mention and link to) to safeguard their data. In other words, we'll answer the question. But we should conclude the question with a clear statement about what Customer Key _does_ protect.

2020-01-15 20:29 UTC, KCCross commented
As luck would have it, the FAQ is going away entirely. We’re replacing the question in the FAQ with a comprehensive overview of customer key and how it compares to related technologies, complete with links to those technologies. I’m working with Tracy to ensure we catch the bit we missed in the original FAQ. Thank you Tracy for all you’ve captured here. This will surely improve the rewrite.

From: MSFTTracyP <notifications@github.com>
Sent: Tuesday, January 14, 2020 1:38 PM
To: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: KC Cross <KC.Cross@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] What data is not protected via customer key (#681)


@joinimran<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoinimran&data=02%7C01%7CKC.Cross%40microsoft.com%7C81133226a16148d59c2608d7993a1093%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637146346983526148&sdata=HNwQffUjOIIuEdlm7Rlk5DxFjYVq8fFKRhRq4eoiHvA%3D&reserved=0> - So here's the rub. The question isn't 'What is protected by customer key?' it's 'What data is not protected via customer key?' In my opinion, we should always try to stick with the more concise 'what is protected by Customer Key' info, as specifically as we can. But if the FAQ question is ~ what's not protected, and we can't ignore that question. The problem with the question is that I can say 'items in your purse' and be correct. When we answer this, we should acknowledge the scope of the question, and say that information about what is protected will be more fleshed-out, and should be where customers' turn, first.

KC may choose to change the question in the FAQ if she feels this is needed, but there is value in letting customers know what doesn't fall under Customer Key and where they may want to look for further technologies (like device-based conditional access policies, and Azure Information Protection, both of which you can mention and link to) to safeguard their data. In other words, we'll answer the question. But we should conclude the question with a clear statement about what Customer Key does protect.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F681%3Femail_source%3Dnotifications%26email_token%3DAG6CYYKKNVYAINJN5OI4Q7TQ5YWEPA5CNFSM4JJCC7D2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI6G6PA%23issuecomment-574385980&data=02%7C01%7CKC.Cross%40microsoft.com%7C81133226a16148d59c2608d7993a1093%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637146346983526148&sdata=9FtWyL8p7DYmcI79YcD3v9c6p3A1ybnDXptVi07IQoA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG6CYYJAKA3V5X3623IGXCDQ5YWEPANCNFSM4JJCC7DQ&data=02%7C01%7CKC.Cross%40microsoft.com%7C81133226a16148d59c2608d7993a1093%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637146346983536143&sdata=BeppQFbWGfN6o3M0PbVvmsnBev%2BhSxndIg8KoEHT3Rg%3D&reserved=0>.

2020-01-16 06:05 UTC, joinimran commented
@KCCross This means this document is going to be re-written? What inputs are required from my side? Or we can close this PR and issue with feedback that we are re-writing the document with all the required and updated info.

2020-02-09 17:41 UTC, mypil commented
@KCCross - We would like to follow up. Can you please advise how you want to proceed with this so we can close issue #634?

2020-02-10 21:22 UTC, MSFTTracyP commented
@mypil Hi! I know you're busy, but could you put together an updated response to the question given the information I've given you and place it in the document so that it can be used as reference material for KC's overview when the time comes for to publish it?

2020-02-10 22:12 UTC, mypil commented
@MSFTTracyP - I received your email. It would be freelancer @joinimran who can provide more information about this PR. We can discuss this further internally with him via email.  Thanks.

2020-02-14 22:36 UTC, KCCross commented
Apologies for the late comment here - The entire content area was being overhauled for the last several months. This delayed fixes to the existing content that weren't p0 breakfix. Since the Customer Key content is sensitive in nature, I found it prudent to wait until the entire new content set was available before closing these. Thank you for your understanding. I look forward to your feedback on the new content.

2020-02-14 22:36 UTC, closed without merging