Update admin-submission.md
MicrosoftDocs/microsoft-365-docs pull request #6810
Opened 2021-11-05 06:31 UTC by msbemba

updated Mark as and notify

2021-11-05 06:32 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-05 06:32 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6511

2021-11-05 08:32 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +1. In the Microsoft 365 Defender portal, go directly to the **Submissions** page: [https://security.microsoft.com/reportsubmission](https://security.microsoft.com/reportsubmission).
```suggestion
1. In the Microsoft 365 Defender portal, go directly to the [**Submissions**](https://security.microsoft.com/reportsubmission) page.
```

2021-11-05 08:32 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +2. Click **User reported messages**, and then select the message you want to mark and notify.
```suggestion
2. Select **User reported messages**, and then select the message you want to mark and notify.
```

2021-11-05 08:33 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +3. Select the **Mark as and notify** drop-down, and then select **No threats found**, **Phishing**, or **Junk**.
```suggestion
3. Select the **Mark as and notify** drop-down, and then select **No threats found** > **Phishing** or **Junk**.
```

2021-11-05 08:35 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +The reported message will be marked as either false positive or false negative, and an email will be automatically sent from within the portal notifying the user who reported the message.
```suggestion
The reported message will be marked as either false positive or false negative, and an email will be sent automatically from within the portal, notifying the user who reported the message.
```

2021-11-05 08:37 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/admin-submission.md
> +
```suggestion
The reported message will be marked as either false positive or false negative and an email will be sent automatically from within the portal to notify the user who reported the message.
```

2021-11-05 08:39 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, kindly commit the suggested changes if you agree with them. Many thanks.

2021-11-05 10:08 UTC, JohanFreelancer9 approved these changes

2021-11-07 05:35 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2021-11-17 18:46 UTC, merged