Update supported versions list for MDE for Linux
MicrosoftDocs/microsoft-365-docs pull request #6824
Opened 2021-11-08 05:39 UTC by ejazr83

The supported versions of Redhat Linux does not mention RHEL 8.x However, other documentation does mention RHEL 8 https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide#client-configuration

Can we add a line to mention RHEL 8.x or higher?

2021-11-09 07:43 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-11-09 08:35 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md
>    - Red Hat Enterprise Linux 7.2 or higher
```suggestion
  - Red Hat Enterprise Linux 6.7 or higher
  - Red Hat Enterprise Linux 7.2 or higher
  - Red Hat Enterprise Linux 8.x
```

2021-11-09 08:36 UTC, JohanFreelancer9 requested changes
Copy review - @ejazr83, kindly commit the minor suggested change (cosmetic).

2021-11-09 08:41 UTC, ejazr83 commented
@JohanFreelancer9 Thanks for reviewing, I have made the change.

2021-11-09 09:08 UTC, JohanFreelancer9 approved these changes

2021-11-10 11:50 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2021-11-24 14:19 UTC, ejazr83 commented
@Dansimp  and @yogkumgit , is there anything else stopping from merging this PR so that the updated RHEL support versions are listed in the docs?

2021-11-25 12:38 UTC, yogkumgit commented
@Dansimp Gentle reminder

2022-01-19 17:20 UTC, merged