Update minimum-requirements.md
MicrosoftDocs/microsoft-365-docs pull request #6825
Opened 2021-11-08 13:11 UTC by msbemba

updated M365 business premium.reference https://docs.microsoft.com/en-us/microsoft-365/admin/misc/microsoft-365-business-faqs?view=o365-worldwide#can-microsoft-365-business-premium-customers-use-microsoft-defender-for-endpoint

2021-11-08 13:11 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-08 13:11 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6811

2021-11-08 13:51 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/minimum-requirements.md
> +- Microsoft 365 Business Premium When purchased from  [Microsoft Cloud Solution Provider](https://partner.microsoft.com/membership/cloud-solution-provider/find-a-provider)
```suggestion
- Microsoft 365 Business Premium when purchased from a [Microsoft Cloud Solution Provider](https://partner.microsoft.com/membership/cloud-solution-provider/find-a-provider)
```

2021-11-08 13:55 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-08 14:01 UTC, JohanFreelancer9 approved these changes

2021-11-09 04:13 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-11-22 22:21 UTC, merged