Update ediscovery.md
MicrosoftDocs/microsoft-365-docs pull request #6826
Opened 2021-11-08 13:13 UTC by msbemba

Updated Microsoft 365 Business Premium in Content search and core ediscovery

2021-11-08 13:13 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6816

2021-11-08 13:14 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-08 13:47 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery.md
> +- Microsoft 365 Business Premium
```suggestion
- Microsoft 365 Business Premium subscription
```

2021-11-08 13:49 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-08 13:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery.md
> +- Microsoft 365 Business Premium
```suggestion
- Microsoft 365 Business Premium subscription
```

2021-11-08 13:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery.md
> +- Microsoft 365 Business Premium
```suggestion
- Microsoft 365 Business Premium subscription
```

2021-11-08 14:00 UTC, JohanFreelancer9 approved these changes

2021-11-09 07:00 UTC, yogkumgit commented
@markjjo Please merge this PR. Thanks

2021-11-09 19:52 UTC, merged