Update prevent-changes-to-security-settings-with-tamper-protection.md
MicrosoftDocs/microsoft-365-docs pull request #6835
Opened 2021-11-08 18:29 UTC by danorum

Added a note in the applies to section regarding the requirement to use the new unified solution package that is currently in preview. I am not sure if it belongs here in Applies to: or in the Requirements section further down the page.

2021-11-08 22:36 UTC, danorum commented
Actually, that should not have Windows Server 2016 as it does have tamper protection without the new unified package. I am unsure how to change my edit/pull request to reflect that.

2021-11-08 23:09 UTC, danorum commented
I believe I fixed it to take Windows Server 2012 out with an additional Commit.

2021-11-09 07:44 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-11-09 08:29 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md
> +[!NOTE]Tamper protection on Windows Server 2012 R2 is available for devices onboarded using the modern unified solution package. For more information, see https://github.com/MicrosoftDocs/microsoft-3
```suggestion
> [!NOTE]
> Tamper protection in Windows Server 2012 R2 is available for devices onboarded using the modern unified solution package. For more information, see [New functionality in the modern unified solution for Windows Server 2012 R2 and 2016 Preview](/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#new-functionality-in-the-modern-unified-solution-for-windows-server-2012-r2-and-2016-preview).
```

2021-11-09 08:30 UTC, JohanFreelancer9 requested changes
Copy review - @danorum, kindly commit the suggested change. Many thanks.

2021-11-09 23:56 UTC, merged