Update endpoint-dlp-using.md
MicrosoftDocs/microsoft-365-docs pull request #6856
Opened 2021-11-10 05:52 UTC by shpalta

@chrfox can you please review and commit this?

2021-11-10 12:48 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-11-10 13:52 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-using.md
> +Support for advanced classification scanning and protection is currently available in the following Windows versions :
```suggestion
Support for advanced classification scanning and protection is currently available in the following Windows versions: 
```

2021-11-10 13:53 UTC, JohanFreelancer9 requested changes
Copy review - @shpalta, kindly commit the minor suggested change. Many thanks.

2021-11-10 20:00 UTC, merged

2021-11-17 23:28 UTC, garycentric commented
@shpalta 
Microsoft-credentialed contributors are strongly encouraged to work in the private repos, not the public. The private repos provide checks for build integrity, checks for spelling & grammar, and provide preview links for added and modified articles. The private repos also have a shorter path to publication, and they're a secure place to add content prior to official release. 

For more information about working in the private repos, please see [Where do I start?](https://review.docs.microsoft.com/en-us/office-authoring-guide/office-docs-authoring-overview?branch=master#where-do-i-start) in the MARVEL authoring guide. If you have questions or need help, please contact [Ask an Admin](https://aka.ms/askanadmin) in Teams.