Clarification added for PDF doc
MicrosoftDocs/microsoft-365-docs pull request #686
Opened 2019-11-06 06:35 UTC by joinimran

As PDF docs are supported so I have mentioned in this document. 

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/645

2019-11-06 06:36 UTC, joinimran commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-06 10:06 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.md
> +Yes! PDF files are supported. You can view supported file formats mentioned [here](https://docs.microsoft.com/information-protection/rms-client/client-admin-guide-file-types). You can also enable enc
```suggestion
Yes! PDF files are supported. To view supported file formats, refer to [File types supported by the Azure Information Protection client](https://docs.microsoft.com/information-protection/rms-client/client-admin-guide-file-types). You can also enable encryption for PDF attachments for your Office 365 organizations. To enable encryption for PDF attachments, run the following command in [Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell):
```

2019-11-06 10:06 UTC, JohanFreelancer9 requested changes
Copy Review - suggestion

2019-11-06 10:12 UTC, joinimran commented
Thanks @JohanFreelancer9 

Ready to go live @mypil

2019-11-06 14:06 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review. This is based on issue #645.

Thank you.

cc: @kenwith

2019-12-20 14:46 UTC, joinimran commented
The data has already been updated through commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/bf56a07f3ca51ee35f039841c21efe15f3d08336#diff-77bba5c43dc54bb9c724167604ae3adb

Closing this PR.

![image](https://user-images.githubusercontent.com/47118050/71262376-57cbdf00-2361-11ea-9469-18c0af03f48e.png)

2019-12-20 14:46 UTC, closed without merging