Update cross-tenant-mailbox-migration.md
MicrosoftDocs/microsoft-365-docs pull request #6864
Opened 2021-11-10 21:29 UTC by zouma83

### How do I know this worked?
=> testing relationship^and endpoint before/after creating at list one object in the target tenant
;)
FM

2021-11-15 06:53 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-11-15 08:39 UTC, JohanFreelancer9 reviewed
@yogkumgit - Could you please request a review from the document author or manager before I do a copy review. I am not at all sure about this.

2021-11-16 07:27 UTC, yogkumgit commented
@kelleyvice-msft Please help. Thanks

2021-11-20 08:50 UTC, zouma83 commented
hi all

tested and used twice during two migrations with the actual manual
> Test-MigrationServerAvailability -Endpoint "[the name of your cross-tenant migration endpoint]" -TestMailbox "[email address of a source mailbox that is part of your migration scope]"

nok error, even before/after creating target object(s)

so for checking the source & target organisation's preparations:
target tenant:
> Test-MigrationServerAvailability -Endpoint "[the name of your cross-tenant migration endpoint]"
> Get-OrganizationRelationship | fl name, DomainNames, MailboxMoveEnabled, MailboxMoveCapability

source tenant:
> Get-OrganizationRelationship | fl name, DomainNames, MailboxMoveEnabled, MailboxMoveCapability

ok, informations indicate ready for mailboxes migrations for both organisations (source & target)
these commands came from the previous manual's version (tested and used several times too)

thanks

2021-12-03 06:40 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-mailbox-migration.md
> +
```suggestion
   > - Target tenant:
   > 
   > Test-MigrationServerAvailability -Endpoint "[the name of your cross-tenant migration endpoint]"
   >
   > Get-OrganizationRelationship | fl name, DomainNames, MailboxMoveEnabled, MailboxMoveCapability
   >
   > - Source tenant:
   > 
   > Get-OrganizationRelationship | fl name, DomainNames, MailboxMoveEnabled, MailboxMoveCapability
   
```

2021-12-03 06:41 UTC, JohanFreelancer9 requested changes
Copy review - @zouma83, kindly commit the minor suggested changes. Many thanks.

2021-12-04 04:49 UTC, JohanFreelancer9 approved these changes

2021-12-06 04:54 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-03-01 17:24 UTC, merged