Update minimum-requirements.md
MicrosoftDocs/microsoft-365-docs pull request #6898
Opened 2021-11-13 07:39 UTC by msbemba

Added- Microsoft Business Premium and - Microsoft 365 E3 (M365 E3) with Addon Enterprise Mobility + Security E5

2021-11-13 07:39 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6842

2021-11-13 07:39 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-13 08:13 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/minimum-requirements.md
> +- Microsoft 365 E3 (M365 E3) with Addon Enterprise Mobility + Security E5
```suggestion
- Microsoft 365 E3 (M365 E3) with Enterprise Mobility + Security E5 Add-on
```

2021-11-13 08:14 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-14 08:16 UTC, yogkumgit commented
@JohanFreelancer9

2021-11-14 09:30 UTC, JohanFreelancer9 approved these changes

2021-11-15 05:52 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-11-22 22:27 UTC, merged