Update feedback-provide-microsoft.md
MicrosoftDocs/microsoft-365-docs pull request #6899
Opened 2021-11-14 09:09 UTC by msbemba

removed place holder  text. Cosmetic change.

2021-11-14 09:15 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6895

2021-11-14 09:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-14 09:23 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/feedback-provide-microsoft.md
> +Selecting a forum allows you to see all feedback related to that product, and you can upvote or comment on feedback that matches yours.  If you do not see feedback that is similar to your own, you ca
```suggestion
Selecting a forum allows you to see all feedback related to that product, and you can upvote or comment on feedback that matches yours.  If you do not see feedback that is similar to your own, you can submit new feedback through the portal itself.
```

2021-11-14 09:24 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-14 09:48 UTC, JohanFreelancer9 approved these changes

2021-11-17 06:59 UTC, yogkumgit commented
@tiburd  Please merge this PR. Thanks

2021-11-17 16:15 UTC, merged