Update secure-score-comparison-bar.png
MicrosoftDocs/microsoft-365-docs pull request #6916
Opened 2021-11-16 14:20 UTC by msbemba

Changed the Screenshot as it has changed recently.

2021-11-16 14:21 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6841

2021-11-16 14:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-16 14:41 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/microsoft-secure-score-history-metrics-trends.md
> +There are two places to see how your score compares to organizations that are similar to you.
```suggestion
There are two places to see how your score compares to organizations that are similar to yours.
```

2021-11-16 14:41 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-17 07:03 UTC, JohanFreelancer9 approved these changes

2021-11-21 10:29 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2021-12-10 16:13 UTC, merged