Update mac-jamfpro-policies.md
MicrosoftDocs/microsoft-365-docs pull request #6979
Opened 2021-11-22 23:53 UTC by msbemba

updated the navigation steps

2021-11-22 23:53 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6948

2021-11-22 23:53 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-23 01:40 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md
> +2. Login to Jamf Pro and navigate t0 **Computers** > **Configuration Profiles** and click **New**
```suggestion
2. Sign in to Jamf Pro, navigate to **Computers** > **Configuration Profiles**, and select **New**.
```

2021-11-23 01:40 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-23 06:43 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2021-11-23 08:20 UTC, JohanFreelancer9 approved these changes

2022-01-06 04:38 UTC, merged