Update mac-jamfpro-policies.md
MicrosoftDocs/microsoft-365-docs pull request #6980
Opened 2021-11-22 23:56 UTC by msbemba

Updated the navigation for Application & Custom Settings on Jamf pro 10.33.0

2021-11-22 23:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-22 23:56 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6949

2021-11-23 01:28 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md
> +4.  Navigate to the **Application & Custom Settings** payload and select **Upload** > **Add**
```suggestion
4.  Navigate to the **Application & Custom Settings** page and select **Upload** > **Add**.
```

2021-11-23 01:28 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-23 01:41 UTC, JohanFreelancer9 approved these changes

2021-11-23 06:44 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2022-01-06 04:40 UTC, merged