Update hybrid-modern-auth-overview.md
MicrosoftDocs/microsoft-365-docs pull request #7008
Opened 2021-11-26 07:20 UTC by msbemba

Added signin options registry key to prerequisites

2021-11-26 07:20 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-26 07:20 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6900

2021-11-26 13:08 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/hybrid-modern-auth-overview.md
> +  - Make sure the SignInOptions setting in Microsoft Office is not configured to its most restrictive setting. For more information, see [ How to Allow office to connect to the internet](/office365/t
```suggestion
  - Make sure the SignInOptions setting in Microsoft Office is not configured to its most restrictive setting. For more information, see [How to allow Office to connect to the internet](/office365/troubleshoot/access-management/office-feature-disabled).
```

2021-11-26 13:08 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-27 02:17 UTC, JohanFreelancer9 approved these changes

2021-11-29 12:22 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-02-20 14:02 UTC, yogkumgit commented
@kelleyvice-msft Gentle reminder. Thanks

2022-03-01 17:23 UTC, merged