Update microsoft-defender-endpoint-linux.md
MicrosoftDocs/microsoft-365-docs pull request #7010
Opened 2021-11-26 07:47 UTC by msbemba

Added a note of support for previous versions.

2021-11-26 07:47 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-11-26 07:47 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6943

2021-11-26 12:56 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md
> + > After a new package version is released, support for the previous two versions is reduced to technical support only. Versions older than that are listed in this section, are provided for technical
```suggestion
 > After a new package version is released, support for the previous two versions is reduced to technical support only. Versions older than that that are listed in this section are provided for technical upgrade support only.
```

2021-11-26 12:57 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-27 02:10 UTC, JohanFreelancer9 approved these changes

2021-11-29 12:36 UTC, yogkumgit commented
@Dansimp Pleas merge this PR. Thanks

2022-01-06 05:34 UTC, merged