Changes Line 33 and line 81
MicrosoftDocs/microsoft-365-docs pull request #7057
Opened 2021-12-02 23:10 UTC by YogeshBarania

Added section separately due to requirement instead of adding to benefits. Also, pls add pointing URL from Admin requirement section to line 33 in the end so that users can navigate to it directly

2021-12-03 08:03 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-03 08:36 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/centralized-deployment-of-add-ins.md
> +- An admin can deploy and assign an add-in directly to a user, to multiple users via a group, or to everyone in the organization (see Admin requirement section for info)
```suggestion
- An admin can deploy and assign an add-in directly to a user, to multiple users via a group, or to everyone in the organization (see Admin requirement section for information).
```

2021-12-03 08:39 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/centralized-deployment-of-add-ins.md
> +>Exchange admin can deploy add-in only if **App Registrations** property is set to true in Azure Active Directory admin center as shown below:
```suggestion
> An Exchange admin can deploy an add-in only if **App Registrations** property is set to true in Azure Active Directory admin center as shown in the following image:
```

2021-12-03 08:40 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/centralized-deployment-of-add-ins.md
> +>![image](https://user-images.githubusercontent.com/89943918/144516704-8874a10d-b540-41f3-ae9d-c07a8d7e143f.png)
```suggestion
> ![image](https://user-images.githubusercontent.com/89943918/144516704-8874a10d-b540-41f3-ae9d-c07a8d7e143f.png)
```

2021-12-03 08:43 UTC, JohanFreelancer9 requested changes
Copy review - @YogeshBarania, kindly commit the suggested changes. Many thanks.

2021-12-03 15:16 UTC, YogeshBarania commented
Changes done as per suggestion, pls approve and publish this doc., thanks.

2021-12-04 06:26 UTC, JohanFreelancer9 approved these changes

2021-12-06 04:42 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-12-06 19:30 UTC, merged