Update microsoft-365-client-support-certificate-based-authentication.md
MicrosoftDocs/microsoft-365-docs pull request #7082
Opened 2021-12-04 16:37 UTC by msbemba

Made changes to the note as Third-party apps CAN access client certificates from the keychain and have access to the public key in the keychain that points to an external smart card. Reference https://developer.apple.com/documentation/cryptotokenkit/using_cryptographic_assets_stored_on_a_smart_card

2021-12-04 16:37 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-04 16:37 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7022

2021-12-05 04:52 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/microsoft-365-client-support-certificate-based-authentication.md
> +> Edge for iOS and Android supports certificate-based authentication during account add flows. Edge for Android does not support certificate-based authentication when performing authentication agains
```suggestion
> Edge for iOS and Android supports certificate-based authentication during account add flows. Edge for Android does not support certificate-based authentication when performing authentication against websites, which are typically intranet sites. <br><br>  In this scenario, a user navigates to a website (usually on the intranet) where the website requires the user to authenticate via a certificate. This does not involve modern authentication at all and does not leverage a Microsoft authentication library. 
```

2021-12-05 04:52 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-05 05:31 UTC, JohanFreelancer9 approved these changes

2021-12-06 05:17 UTC, yogkumgit commented
@robmazz Please merge this Pr. Thanks

2022-01-11 19:00 UTC, robmazz commented
@yogkumgit and @msbemba - submitted suggested note change to PM team for review.

2022-01-17 07:54 UTC, yogkumgit commented
@robmazz Any update?

2022-01-18 16:17 UTC, robmazz commented
@yogkumgit - the PM Team is discussing if we want to deprecate all the client service app topics (including this one), should have a decision this week.

2022-03-15 06:14 UTC, yogkumgit commented
@robmazz Awaiting your kind response. Thanks

2022-04-22 02:22 UTC, robmazz commented
@yogkumgit - this topic has been deprecated

2022-04-22 02:22 UTC, closed without merging