Update steps to elevate and escalate.
MicrosoftDocs/microsoft-365-docs pull request #7088
Opened 2021-12-06 03:05 UTC by mounicabattula

Making changes to the steps to create MMD elevation and escalation requests after SEP portal migration to MEM. The new changes will be in effect from December 7th 2021 (the release date of SEP portal migration to MEM.)

2021-12-06 07:37 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-06 09:35 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/working-with-managed-desktop/end-user-support.md
> +4. Alternatively, to create a new elevation request on the **Elevations Requests tab**, select **+New elevation request.**
```suggestion
1. Sign in to [Microsoft Endpoint Manager](https://endpoint.microsoft.com/) and navigate to the **Devices** menu.
2. Look for the **Microsoft Managed Desktop** section, and then select the **Devices** blade which contains two tabs – the **Devices** tab and the **Elevation Requests** tab. 
3. To create a new elevation request on the **Device** tab, select a single device that you want to elevate, and then select **Request elevation** from the Device actions dropdown menu. A new elevation request fly-in pane will appear with the device’s name prepopulated in that field.
4. Alternatively, to create a new elevation request on the **Elevations Requests** tab, select **+New elevation request.**
```

2021-12-06 09:37 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/working-with-managed-desktop/end-user-support.md
> +    - **Device name**(only when creating request from **Elevation Requests Tab**): Enter the device serial number and then select the device from the menu.
```suggestion
    - **Device name**(only when creating request from the **Elevation Requests** tab): Enter the device serial number and then select the device from the menu.
```

2021-12-06 09:44 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/working-with-managed-desktop/end-user-support.md
> +5. Select the **Category** and **Sub-category** that best fits your issue and click on **Next**.
```suggestion
5. Select the **Category** and **Sub-category** that best fits your issue and select **Next**.
```

2021-12-06 09:48 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/working-with-managed-desktop/end-user-support.md
> +6. On the Details section, provide the following information:
```suggestion
6. In the **Details** section, provide the following information:
```

2021-12-06 09:51 UTC, JohanFreelancer9 requested changes
Copy review - @mounicabattula, kindly commit the suggested changes. Many thanks.

2021-12-06 15:49 UTC, JohanFreelancer9 approved these changes

2021-12-07 10:47 UTC, yogkumgit commented
@greg-lindsay Please merge this PR. Thanks

2021-12-07 23:44 UTC, merged