Update multi-geo-add-group-with-pdl.md
MicrosoftDocs/microsoft-365-docs pull request #7097
Opened 2021-12-06 21:13 UTC by msbemba

Added link to create group with specific PDL

2021-12-06 21:13 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-06 21:13 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7034

2021-12-07 04:09 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/multi-geo-add-group-with-pdl.md
> +[Create groups with a specific preferred data location using Grpah API](/graph/api/group-post-groups)
```suggestion

[Create groups with a specific preferred data location using Graph API](/graph/api/group-post-groups)
```

2021-12-07 04:09 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-07 11:00 UTC, yogkumgit commented
@msbemba

2021-12-07 11:47 UTC, JohanFreelancer9 approved these changes

2021-12-07 12:49 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-12-07 13:59 UTC, merged