Update share-calendars-with-external-users.md
MicrosoftDocs/microsoft-365-docs pull request #7098
Opened 2021-12-06 21:20 UTC by msbemba

Added sharing intervals to the document -reference https://support.microsoft.com/en-us/office/calendar-sharing-in-microsoft-365-b576ecc3-0945-4d75-85f1-5efafb8a37b4?ui=en-us&rs=en-us&ad=us

2021-12-06 21:20 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-06 21:20 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7047

2021-12-07 04:19 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/share-calendars-with-external-users.md
> +## External Sharing Sync Interval
```suggestion
## External sharing sync interval
```

2021-12-07 04:25 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/share-calendars-with-external-users.md
> +An ICS URL is generated when sharing, which the recipient can use to add to any calendar service. With an ICS subscription, the recipient’s calendar service chooses when to sync the ICS subscription
```suggestion
1. **Microsoft 365 to another Microsoft 365 user (if external sharing is enabled)**: A fully shared calendar is created, but the sync will happen approximately every three hours. Instant syncing will eventually be enabled for this setup.

2. **Microsoft 365 to an Outlook.com user**: If external sharing is disabled, sharing to another Microsoft 365 user also falls into this group. An ICS URL is generated when sharing, which the recipient can use to add to any calendar service. With an ICS subscription, the recipient’s calendar service chooses when to sync the ICS subscription to receive new updates. If the recipient is an Outlook.com or a Microsoft 365 user, the sync will happen approximately every three hours.
```

2021-12-07 04:25 UTC, JohanFreelancer9 requested changes
Copy review - suggestions.

2021-12-07 11:03 UTC, yogkumgit commented
@msbemba

2021-12-07 11:50 UTC, JohanFreelancer9 approved these changes

2021-12-07 12:51 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2021-12-14 05:34 UTC, yogkumgit commented
@msbemba Please resolve the conflict

2021-12-14 20:13 UTC, merged