Update configure-endpoints-script.md
MicrosoftDocs/microsoft-365-docs pull request #7102
Opened 2021-12-06 22:01 UTC by msbemba

made changes to the important note with more information as requested by the user.

2021-12-06 22:01 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-06 22:01 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7087

2021-12-07 05:17 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-endpoints-script.md
>  > This script has been optimized for use on up to 10 devices.
```suggestion
> This script has been optimized for use on up to ten devices.
```

2021-12-07 05:20 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-endpoints-script.md
> +>If you are deploying to a production environment as described above, use [other deployment options](configure-endpoints.md)like  Group Policy or Microsoft Endpoint Configuration Manager.
```suggestion
> Local scripting is a special onboarding method for evaluating Microsoft Defender for Endpoint.
>
> The data reporting frequency is set higher than with other onboarding methods when onboarding using local script is performed.
>
> This setting is for evaluation purposes and is not normally used in production deployments. For this reason, there are concerns about environmental impact, so we recommend limiting the number of deployments using local scripts to ten.
>
> If you are deploying to a production environment as previously described, use [other deployment options](configure-endpoints.md) like  Group Policy or Microsoft Endpoint Configuration Manager.
```

2021-12-07 05:27 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-07 11:01 UTC, JohanFreelancer9 approved these changes

2021-12-07 11:26 UTC, yogkumgit commented
@mjcaparas Pleas merge this PR. Thanks

2022-01-06 06:58 UTC, merged