Update push-content-type-to-hub.md
MicrosoftDocs/microsoft-365-docs pull request #7103
Opened 2021-12-06 22:08 UTC by msbemba

Added a line about the changes that happen to the library view after content types are pushed to a document library.

2021-12-06 22:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-06 22:08 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7019

2021-12-07 05:43 UTC, JohanFreelancer9 commented on microsoft-365/contentunderstanding/push-content-type-to-hub.md
> +After the settings are updated, the content type with these settings will be available in any newly associated site with the hub in a few minutes. The default Library view will be changed to one of t
```suggestion
After the settings are updated, the content type with these settings will be available in any newly associated site with the hub in a few minutes. The default library view will be changed to one of these automatically created views. Then, any new list or library created will have the content type automatically added to it within a few minutes of creation. A pushed content type will be added to a document library only if it derives directly or indirectly from the Document content type, and a content type will be added to a list only if it does not derive from the Document content type directly or indirectly.
```

2021-12-07 05:43 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-12-07 10:52 UTC, JohanFreelancer9 approved these changes

2021-12-07 11:30 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2021-12-07 13:57 UTC, merged