Update create-sensitivity-labels.md
MicrosoftDocs/microsoft-365-docs pull request #7104
Opened 2021-12-06 22:22 UTC by msbemba

made changes as the navigation options have changed.

2021-12-06 22:22 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-06 22:23 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7004

2021-12-07 07:19 UTC, JohanFreelancer9 commented on microsoft-365/business-video/create-sensitivity-labels.md
> +1. From the [Microsoft 365 compliance center](https://compliance.microsoft.com/), select **Solutions** > **Information protection**
```suggestion
1. From the [Microsoft 365 compliance center](https://compliance.microsoft.com/), select **Solutions** > **Information protection**.
```

2021-12-07 07:20 UTC, JohanFreelancer9 commented on microsoft-365/business-video/create-sensitivity-labels.md
> +2. On the **Labels** page, select **+ Create a label** to start the New sensitivity label configuration.
```suggestion
2. On the **Labels** page, select **+ Create a label** to start the new sensitivity label configuration. 
```

2021-12-07 07:25 UTC, JohanFreelancer9 commented on microsoft-365/business-video/create-sensitivity-labels.md
> +    - If **Groups & sites** is selected, you can configure settings that apply to Microsoft 365 groups, and sites for Teams and SharePoint. If this option isn't selected, you see the first page of th
```suggestion
    - If **Groups & sites** is selected, you can configure settings that apply to Microsoft 365 groups and sites for Teams and SharePoint. If this option isn't selected, you see the first page of these settings but you can't configure them and the labels won't be available for users to select for groups and sites.
```

2021-12-07 07:35 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-07 10:48 UTC, JohanFreelancer9 approved these changes

2021-12-07 11:55 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2021-12-13 21:40 UTC, efrene commented
@yogkumgit @msbemba, I am in the process of creating an updated video for this article, so I will update the steps when I post the new video.   Thanks!

2022-02-08 15:27 UTC, yogkumgit commented
@efrene

2022-03-15 06:12 UTC, yogkumgit commented
@efrene Kindly merge this PR. Thanks

2022-10-10 17:44 UTC, tiburd commented
@msbemba 
Hi Sri,
This PR is old, and the procedure has been updated, so I'm closing this PR.
Thanks!

cc: @yogkumgit

2022-10-10 17:44 UTC, closed without merging