Updated compatibility table and unallowed browsers
MicrosoftDocs/microsoft-365-docs pull request #7135
Opened 2021-12-09 01:03 UTC by edwinchan-microsoft

@chrfox 
Based on feedback we split the table into 2 parts.

2021-12-09 06:46 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-09 08:35 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-using.md
> +|Auto-quarantine files from unallowed apps     |Supported         |Not supported         |        |
```suggestion
|Auto-quarantine files from unallowed apps     |Supported         |Not Supported         |        |
```

2021-12-09 08:36 UTC, JohanFreelancer9 requested changes
Copy review - @edwinchan-microsoft, for consistency, kindly commit the minor suggested change. Many thanks.

2022-01-26 21:13 UTC, chrfox commented
the changed content still says "Edge VERSION NUMBER NEEDED"

2022-02-10 12:19 UTC, yogkumgit commented
@edwinchan-microsoft Please implement the suggestions. Thanks

2022-03-18 23:21 UTC, closed without merging