Updating TenantID information in the article based on customer input
MicrosoftDocs/microsoft-365-docs pull request #7138
Opened 2021-12-09 14:40 UTC by LikhithaMS

Though the article is clear with all of us being familiar with what a tenantID is, one of the customer ended up feeding the domain onmicrosoft.com name in the place on the $SourcetenantID and $TargettenantID looking at the following check it does against the domainname i.e. $existingOrgRel = $orgrels | ?{$_.DomainNames -like $targetTenantId}
So they have a request of adding a screenshot of an example  which depicts  $SourcetenantID and $TargettenantID.

2021-12-10 11:01 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-13 04:33 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-mailbox-migration.md
> +![image](https://user-images.githubusercontent.com/74538523/145413901-e8924abf-13bd-442c-912d-932707ae8b9c.png)
```suggestion
> [!NOTE]
> The tenant ID fed to the $sourceTenantId and $targetTenantId is the GUID and not the tenant domain name. For an example of a tenant ID and information about finding your tenant ID, see [Find your Microsoft 365 tenant ID](/onedrive/find-your-office-365-tenant-id).
```

2021-12-13 04:39 UTC, JohanFreelancer9 requested changes
Copy review - @LikhithaMS, kindly commit the suggested changes if you agree with them (note that the screenshot is already included in the referenced article). Many thanks.

2021-12-13 05:00 UTC, LikhithaMS commented
Done, thank you!

Regards,
Likhitha

From: JohanFreelancer9 ***@***.***>
Sent: 13 December 2021 10:09
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Likhitha K ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Updating TenantID information in the article based on customer input (PR #7138)


@JohanFreelancer9 requested changes on this pull request.

Copy review - @LikhithaMS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLikhithaMS&data=04%7C01%7Clikhitk%40microsoft.com%7Cae0717cb19bd4e9db61308d9bdf285aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637749671648598830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gEZU5DhpaRMYwMNB51CX4C4lw045AffOvmZFxFH8czQ%3D&reserved=0>, kindly commit the suggested changes if you agree with them (note that the screenshot is already included in the referenced article). Many thanks.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F7138%23pullrequestreview-829764898&data=04%7C01%7Clikhitk%40microsoft.com%7Cae0717cb19bd4e9db61308d9bdf285aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637749671648598830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ahEeZ1X3HqtxLJdx69Q9HNR7hVwX5QfqXOzrGHKF7H4%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARYV4G24IKF4TFJKPSJWBVTUQV2HJANCNFSM5JWUN6XQ&data=04%7C01%7Clikhitk%40microsoft.com%7Cae0717cb19bd4e9db61308d9bdf285aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637749671648608824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CPKkzIwQ5dY9BzxAkTKW1%2FfCQ3yCik%2Bii%2F0wMjv1Z3o%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clikhitk%40microsoft.com%7Cae0717cb19bd4e9db61308d9bdf285aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637749671648608824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HVCKp7zqw5a00O5AQkvxfOlLI4vBDxWcMYCMv0xeKHg%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clikhitk%40microsoft.com%7Cae0717cb19bd4e9db61308d9bdf285aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637749671648618817%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Kd4GLpKJszy4iwMIVS2lBUYspVs9kB%2Fpgl1LS%2Bc1IkI%3D&reserved=0>.

2021-12-13 05:34 UTC, yogkumgit commented
@JohanFreelancer9

2021-12-13 05:46 UTC, JohanFreelancer9 approved these changes

2021-12-13 06:37 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2021-12-13 16:02 UTC, merged