Update access-admin-portal.md
MicrosoftDocs/microsoft-365-docs pull request #7155
Opened 2021-12-10 20:46 UTC by mounicabattula

With the SEP portal migration to MEM/MMD portal, Support Partners can use MMD/MEM portal to create elevations and escalations. Adding the MMD Support Partner role in the list to MMD built-in roles list.

2021-12-13 06:42 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-13 08:34 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/get-started/access-admin-portal.md
> +|Microsoft Managed Desktop Support Partner |When assigned to a user, this role gives that admin **read and write permissions only for creating and managing elevation requests, and support partner eng
```suggestion
|Microsoft Managed Desktop Support Partner |When assigned to a user, this role gives the admin **read and write permissions only for creating and managing elevation requests and support partner engaged escalation requests** in the Microsoft Managed Desktop Admin portal.   |
```

2021-12-13 08:34 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-14 05:18 UTC, yogkumgit commented
@mounicabattula Please implement the suggested changes. Thanks

2022-01-04 04:34 UTC, JohanFreelancer9 approved these changes

2022-01-04 08:37 UTC, yogkumgit commented
@jaimeo Please merge this PR. Thanks

2022-01-04 16:09 UTC, jaimeo commented
I'm not in this area anymore (article authorship has not been updated yet). Contact @dougeby

2022-01-05 14:19 UTC, yogkumgit commented
@dougeby Please merge this PR. Thanks

2022-01-07 18:33 UTC, merged