Update dlp-conditions-and-exceptions.md
MicrosoftDocs/microsoft-365-docs pull request #7163
Opened 2021-12-14 05:33 UTC by aamalhot

Add details for sender address location

2021-12-14 05:34 UTC, aamalhot commented
Please hold for approval

2021-12-14 06:25 UTC, aamalhot commented
@chrfox please review and merge

2021-12-15 05:30 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-15 07:58 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-conditions-and-exceptions.md
> +For conditions and exceptions that examine the sender's address, you can specify where rule looks for the sender's address. The sender address used by Data Loss Prevention (DLP) to evaluate sender ba
```suggestion
For conditions and exceptions that examine the sender's address, you can specify where the rule looks for the sender's address. The sender address, used by the DLP rule to evaluate the sender-based conditions listed below, is the envelope address. Note that Exchange transport rules use the header address as the default sender address location.
```

2021-12-15 08:02 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-conditions-and-exceptions.md
> +>Starting 20th January 2021, the default sender address location will be moved to the Header address along with the availability of the -SenderAddressLocation parameter to configure desired behavior
```suggestion
> [!NOTE]
> Starting January 20, 2021, the default sender address location will be moved to the header address along with the availability of the -SenderAddressLocation parameter to configure desired behavior at a DLP rule level.
```

2021-12-15 08:03 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-conditions-and-exceptions.md
> +At the tenant level, you can configure a Sender Address Location to be used across all rules, unless overridden by a single rule. To revert tenant DLP policy configuration to evaluate sender address
```suggestion
At the tenant level, you can configure a sender address location to be used across all rules, unless overridden by a single rule. To revert tenant DLP policy configuration to evaluate sender address from Envelope across all rules, you can run the below command-
```

2021-12-15 08:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-conditions-and-exceptions.md
> +To configure sender address location at a DLP rule level, the parameter is _SenderAddressLocation_. The available values are:
```suggestion
To configure the sender address location at a DLP rule level, the parameter is _SenderAddressLocation_. The available values are:
```

2021-12-15 08:15 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-16 04:50 UTC, yogkumgit commented
@aamalhot Please implement the suggested changes. Thanks

2021-12-17 11:14 UTC, yogkumgit commented
@JohanFreelancer9

2021-12-17 12:56 UTC, JohanFreelancer9 commented
@aamalhot, kindly commit all my suggested changes. You only seem to have committed one suggestion. Many thanks.

2021-12-17 12:58 UTC, aamalhot commented
Thanks @JohanFreelancer9. Completed all

2021-12-20 04:15 UTC, yogkumgit commented
@JohanFreelancer9

2021-12-20 06:49 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-conditions-and-exceptions.md
>  ****
```suggestion
```

2021-12-20 06:51 UTC, aamalhot commented
@JohanFreelancer9 updated

2021-12-20 06:54 UTC, JohanFreelancer9 approved these changes
Thank you, @aamalhot.

2021-12-21 04:53 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-01-06 04:48 UTC, aamalhot commented
Looks good @chrfox . Please proceed with publish

2022-01-07 16:22 UTC, merged