Changed procedure from AzureRm to Az module
MicrosoftDocs/microsoft-365-docs pull request #717
Opened 2019-11-11 22:26 UTC by get-itips

Proposing the procedure to reflect the use of the new Az module

@KCCross Please review

cc @mypil 

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/654

2019-11-12 09:13 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-12 14:22 UTC, JohanFreelancer9 commented on microsoft-365/compliance/controlling-your-data-using-customer-key.md
> +You will complete most of these tasks by remotely connecting to Azure PowerShell. For best results, use version 3.0 or later of Azure PowerShell Az module, for more information, see the [Introducing
```suggestion
You will complete most of these tasks by remotely connecting to Azure PowerShell. For best results, use version 3.0 or later of Azure PowerShell Az module. For more information, see [Introducing the new Azure PowerShell Az module](https://docs.microsoft.com/powershell/azure/new-azureps-module-az?view=azps-3.0.0).
```

2019-11-12 14:26 UTC, JohanFreelancer9 commented on microsoft-365/compliance/controlling-your-data-using-customer-key.md
> +- If you intend to use Customer Key with Exchange Online and Skype for Business, you need to give permission to Office 365 to use the key vault on behalf of Exchange Online and Skype for Business. Li
```suggestion
- If you intend to use Customer Key with Exchange Online and Skype for Business, you need to give permission to Office 365 to use the key vault on behalf of Exchange Online and Skype for Business. Likewise, if you intend to use Customer Key with SharePoint Online and OneDrive for Business, you need to add permission for Office 365 to use the key vault on behalf of SharePoint Online and OneDrive for Business. To give permission to Office 365, run the **Set-AzKeyVaultAccessPolicy** cmdlet using the following syntax: 
```

2019-11-12 14:29 UTC, JohanFreelancer9 commented on microsoft-365/compliance/controlling-your-data-using-customer-key.md
> +To verify that an expiration date is not set for your keys run the [Get-AzKeyVaultKey](https://docs.microsoft.com/powershell/module/az.keyvault/get-azkeyvaultkey) cmdlet as follows:
```suggestion
To verify that an expiration date is not set for your keys, run the [Get-AzKeyVaultKey](https://docs.microsoft.com/powershell/module/az.keyvault/get-azkeyvaultkey) cmdlet as follows: 
```

2019-11-12 14:31 UTC, JohanFreelancer9 requested changes
Copy Review - minor edits

2019-11-13 12:41 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review based on issue #654. 

Thank you.

cc: @kenwith

2019-12-12 12:20 UTC, mypil commented
@KCCross - We would like to follow up on this. Can you please assist to review and approve this PR for merging?
@LauraWi - Would you be able to help merge this PR?

Thank you.

2020-01-08 15:19 UTC, mypil commented
@KCCross - We would like to follow up. Any updates on this?

Thank you.

2020-02-14 12:16 UTC, get-itips commented
It seems that the affected article has been removed and replaced with https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-overview

2020-02-14 12:16 UTC, closed without merging

2020-02-14 22:34 UTC, KCCross commented
Apologies for the late comment here - The entire content area was being overhauled for the last several months. This delayed fixes to the existing content that weren't p0 breakfix. Since the Customer Key content is sensitive in nature, I found it prudent to wait until the entire new content set was available before closing these. Thank you for your understanding. I look forward to your feedback on the new content.