Update use-intune-config-manager-microsoft-defender-antivirus.md
MicrosoftDocs/microsoft-365-docs pull request #7172
Opened 2021-12-14 17:00 UTC by dlmsft

2021-12-15 05:34 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-15 07:14 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/use-intune-config-manager-microsoft-defender-antivirus.md
> +> AllowOnAccessProtection and AllowIntrusionPreventionSystem Antivirus settings are officially being deprecated and as such cannot be configured.
```suggestion
> AllowOnAccessProtection and AllowIntrusionPreventionSystem antivirus settings are officially being deprecated and as such cannot be configured. 
```

2021-12-15 07:14 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/use-intune-config-manager-microsoft-defender-antivirus.md
>  8. Choose **Review + save**
```suggestion
8. Choose **Review + save**.
```

2021-12-15 07:15 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-16 04:47 UTC, yogkumgit commented
@dlmsft Please implement the suggested changes. Thanks

2021-12-16 09:20 UTC, dlmsft reviewed
approved all suggested changes

2021-12-16 13:47 UTC, JohanFreelancer9 commented
@dlmsft - please also commit the second suggested change. Many thanks.

2021-12-16 19:04 UTC, denisebmsft approved these changes
Thank you @dlmsft @yogkumgit @JohanFreelancer9

2021-12-16 19:04 UTC, merged