Update device-list.md
MicrosoftDocs/microsoft-365-docs pull request #718
Opened 2019-11-12 04:38 UTC by rekhanr

1. Removed HP EliteBook 830 / 840 / 850 G5 from the Active list 
2.  Moved HP EliteBook 830 / 840 / 850 G5 to the Archived list
3. Added HP EliteBook 830 / 840 / 850 G6 to the Active list
4. Added HP EliteBook x360 830 G6 Notebook PC to the Active list

2019-11-12 09:14 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-12 14:18 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/device-list.md
> +| [HP EliteBook 830 / 840 / 850 G6 Notebook PC](https://store.hp.com/us/en/mdp/laptops/elitebook-840#!&tab=features) | 128 GB / Intel i5 / 8 GB RAM | SKU with 5VS01AV, IR Camera or fingerprint sensor
```suggestion
| [HP EliteBook 830 / 840 / 850 G6 Notebook PC](https://store.hp.com/us/en/mdp/laptops/elitebook-840#!&tab=features) | 128 GB / Intel i5 / 8 GB RAM | SKU with 5VS01AV, IR camera or fingerprint sensor required | Nov 30, 2020 | Nov 30, 2023 |
```

2019-11-12 14:19 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/device-list.md
> +| [HP EliteBook x360 830 G6 Notebook PC](https://store.hp.com/us/en/pdp/hp-elitebook-x360-830-g6-notebook-pc) | 128 GB / Intel i5 / 8 GB RAM | SKU with 5VS01AV, IR Camera or fingerprint sensor requir
```suggestion
| [HP EliteBook x360 830 G6 Notebook PC](https://store.hp.com/us/en/pdp/hp-elitebook-x360-830-g6-notebook-pc) | 128 GB / Intel i5 / 8 GB RAM | SKU with 5VS01AV, IR camera or fingerprint sensor required | Nov 30, 2020 | Nov 30, 2023 |
```

2019-11-12 14:20 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/device-list.md
> +- For more questions on HP devices and device ordering instructions contact: Americas (<a href="mailto:mmd-americas@hp.com">mmd-americas@hp.com</a>); Europe/Middle East/Africa (<a href="mailto:mmd-em
```suggestion
- For more questions on HP devices and device ordering instructions, contact: Americas (<a href="mailto:mmd-americas@hp.com">mmd-americas@hp.com</a>); Europe/Middle East/Africa (<a href="mailto:mmd-emea@hp.com">mmd-emea@hp.com</a>); Asia Pacific/Japan (<a href="mailto:mmd-apj@hp.com">mmd-apj@hp.com</a>); Global (<a href="mailto:mmd@hp.com">mmd@hp.com</a>)
```

2019-11-12 14:20 UTC, JohanFreelancer9 requested changes
Copy Review

2019-11-13 01:46 UTC, rekhanr commented
@mypil , I have accepted the changes. Can you please merge the files?

2019-11-13 05:08 UTC, mypil commented
@rekhanr - There appears to be a branch conflict to this PR. Can you please check on resolving this conflict first?

Thank you.

2019-11-13 19:19 UTC, mertenar commented
@jaimeo can you provide assistance with this one?

2019-11-13 19:24 UTC, jaimeo commented
I'll need to do this with @rekhanr to be sure we accept the correct version. Contact me internally....

2019-11-13 21:40 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/MicrosoftDocs/microsoft-365-docs?pullRequest=718) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/MicrosoftDocs/microsoft-365-docs?pullRequest=718) before we can accept your contribution.<br/><br/>:x: rekhanr [sign now](https://cla.opensource.microsoft.com/MicrosoftDocs/microsoft-365-docs?pullRequest=718)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/MicrosoftDocs/microsoft-365-docs?pullRequest=718) it.</sub>

2019-11-14 17:13 UTC, merged