Update mdatp-6-systemconfigurationprofiles.png
MicrosoftDocs/microsoft-365-docs pull request #7180
Opened 2021-12-15 13:01 UTC by msbemba

Change in the screenshot as deployment channel is available now

2021-12-15 13:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-15 13:04 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7095

2021-12-15 13:57 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/mac-install-with-intune.md
> +1. Choose a Deployment channel.
```suggestion
1. Choose a deployment channel.
```

2021-12-15 13:58 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-15 16:27 UTC, jerryabo commented
Thanks, I think we want to also work in/breadcrumb the What's New guidance/details here as well please @msbemba https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#new-deployment-channel-setting-for-custom-device-configuration-profiles-on-macos-devices

2021-12-16 03:44 UTC, JohanFreelancer9 approved these changes

2021-12-16 04:53 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2021-12-17 02:21 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7194

2022-01-19 17:17 UTC, merged