Update archived-device-list.md
MicrosoftDocs/microsoft-365-docs pull request #719
Opened 2019-11-12 04:41 UTC by rekhanr

Added HP EliteBook 830 / 840 / 850 G5 to the archived list

2019-11-12 09:14 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-12 14:15 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/service-description/archived-device-list.md
> +| [HP EliteBook 830 / 840 / 850 G5](https://store.hp.com/us/en/mdp/laptops/elitebook-840#!&tab=features) | 128 GB / Intel i5 / 8 GB RAM | SKU with 5VS01AV, IR Camera or fingerprint sensor required |
```suggestion
| [HP EliteBook 830 / 840 / 850 G5](https://store.hp.com/us/en/mdp/laptops/elitebook-840#!&tab=features) | 128 GB / Intel i5 / 8 GB RAM | SKU with 5VS01AV, IR camera or fingerprint sensor required | None | **Feb 15, 2023** |
```

2019-11-12 14:15 UTC, JohanFreelancer9 requested changes
Copy Review - minor edit

2019-11-13 05:10 UTC, mypil commented
@jaimeo - PR has been copy edited and is ready for final review. 


Thank you.

cc: @kenwith

2019-11-13 16:11 UTC, merged