removed brackets
MicrosoftDocs/microsoft-365-docs pull request #7213
Opened 2021-12-18 14:39 UTC by RAJU2529

as per user feedback  #7179  so i  removed brackets.

2021-12-20 04:27 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-20 06:58 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-addins-in-the-admin-center.md
> +Office add-ins help you personalize your documents and streamline the way you access information on the web see [Start using your Office add-in](https://support.microsoft.com/office/82e665c4-6700-4b5
```suggestion
Office add-ins help you personalize your documents and streamline the way you access information on the web. See [Start using your Office add-in](https://support.microsoft.com/office/82e665c4-6700-4b56-a3f3-ef5441996862). 
```

2021-12-20 07:01 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-addins-in-the-admin-center.md
> +After you deploy an add-in, your end users can start using it in their Office applications see [Start using your Office Add-in](https://support.microsoft.com/office/82e665c4-6700-4b56-a3f3-ef54419968
```suggestion
After you deploy an add-in, your end users can start using it in their Office applications. The add-in appears on all platforms that the add-in supports. See [Start using your Office Add-in](https://support.microsoft.com/office/82e665c4-6700-4b56-a3f3-ef5441996862). 
```

2021-12-20 07:02 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-20 07:10 UTC, JohanFreelancer9 approved these changes

2021-12-21 04:55 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks.

2022-01-05 00:58 UTC, merged