Update microsoft-365-guest-settings.md
MicrosoftDocs/microsoft-365-docs pull request #7217
Opened 2021-12-19 01:08 UTC by msbemba

made changes to the setting where guests are to be added to a group.

Tested and it does not let even guests within the org to be added when the setting is OFF

2021-12-19 01:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-19 01:08 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7166

2021-12-19 04:04 UTC, JohanFreelancer9 commented on microsoft-365/solutions/microsoft-365-guest-settings.md
> +|Let group owners add people outside your organization to groups|On|When **On**, Owners of Microsoft 365 Groups or Teams can invite new guests to the group. When **Off**, they can't. This setting sho
```suggestion
|Let group owners add people outside your organization to groups|On|When **On**, owners of Microsoft 365 Groups or Teams can invite new guests to the group. When **Off**, they can't. This setting should be **On** for any scenario where guests are to be added to groups.|
```

2021-12-19 04:04 UTC, JohanFreelancer9 requested changes
Copy review - minor edit, please.

2021-12-19 04:55 UTC, JohanFreelancer9 approved these changes

2021-12-20 04:43 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2022-01-03 15:01 UTC, merged