Update enable-siem-integration.md
MicrosoftDocs/microsoft-365-docs pull request #7252
Opened 2021-12-23 06:12 UTC by msbemba

Added an important note that the feature will be no longer supported effective immediately.

2021-12-23 06:12 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-23 06:12 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7241

2021-12-23 07:32 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-siem-integration.md
> +>The Microsoft Defender for Endpoint SIEM REST API is being retired on March 1st, 2022, as the Microsoft Defender for Endpoint Alert API and the Microsoft 365 Defender Incident API that replace it pr
```suggestion
> The Microsoft Defender for Endpoint SIEM REST API is being retired on March 1, 2022, as the Microsoft Defender for Endpoint Alert API and the Microsoft 365 Defender Incident API that replace it provide richer metadata - including up-to-date status of the alert, evidence entities related to the alert, comments entered by analysts, and they support updating the status, assignedTo, classification, and determination fields programmatically. **Effective immediately, no new customer onboarding to the SIEM REST API will be supported.**
```

2021-12-23 07:32 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-23 07:43 UTC, JohanFreelancer9 approved these changes

2021-12-23 12:10 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2021-12-23 15:02 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-siem-integration.md
> +> [!Important]
```suggestion
> [!IMPORTANT]
```

2021-12-23 15:03 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2021-12-23 16:04 UTC, JohanFreelancer9 approved these changes

2021-12-24 04:52 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks.

2022-01-06 07:09 UTC, merged