Update recommended-settings-for-eop-and-office365.md
MicrosoftDocs/microsoft-365-docs pull request #7255
Opened 2021-12-23 06:46 UTC by msbemba

Preset security policies cannot be modified and needs to be disabled if message senders are to be added.

2021-12-23 06:46 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7226

2021-12-23 12:21 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-23 14:34 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md
> +|**Enable users to protect** (impersonated user protection) <p> _EnableTargetedUserProtection_ <p> _TargetedUsersToProtect_|Not selected <p> `$false` <p> none|Selected <p> `$true` <p> \<list of users
```suggestion
|**Enable users to protect** (impersonated user protection) <p> _EnableTargetedUserProtection_ <p> _TargetedUsersToProtect_|Not selected <p> `$false` <p> none|Selected <p> `$true` <p> \<list of users\>|Selected <p> `$true` <p> \<list of users\>|We recommend adding users (message senders) in key roles. Internally, protected senders might be your CEO, CFO, and other senior leaders. Externally, protected senders could include council members or your board of directors. Preset security policies cannot be modified; it must be disabled if you want to add users in key roles as suggested.|
```

2021-12-23 14:35 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-23 16:04 UTC, JohanFreelancer9 approved these changes

2021-12-24 04:51 UTC, yogkumgit commented
@chrisda Please merge this PR. Thanks

2022-01-03 17:52 UTC, merged