added correct link, added letter a
MicrosoftDocs/microsoft-365-docs pull request #7276
Opened 2021-12-29 19:54 UTC by RAJU2529

as per user feedback #7275 , so i added correct link and added letter a

2021-12-30 11:13 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2021-12-30 13:53 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/set-password-to-never-expire.md
> +This article is for people who set password expiration policy for a business, school, or nonprofit. To complete these steps, you need to sign in with your Microsoft 365 admin account. [Overview of th
```suggestion
This article is for people who set password expiration policy for a business, school, or nonprofit. To complete these steps, you need to sign in with your Microsoft 365 admin account. See [Overview of the Microsoft 365 admin center](/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide).
```

2021-12-30 13:53 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-30 14:05 UTC, JohanFreelancer9 approved these changes

2022-01-01 11:50 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-01-05 00:56 UTC, merged