Update set-password-expiration-policy.md
MicrosoftDocs/microsoft-365-docs pull request #7292
Opened 2022-01-03 09:15 UTC by msbemba

Made changes to the important note as it creates ambiguity when saying M365 admin center as users dont have access to it.

2022-01-03 09:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-01-03 09:15 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7262

2022-01-03 10:25 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/set-password-expiration-policy.md
> +> Password expiration notifications are no longer supported in the Office web apps,  or [Office portal](https://portal.office.com).
```suggestion
> Password expiration notifications are no longer supported in Office web apps or the [Office portal](https://portal.office.com).
```

2022-01-03 10:25 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-03 11:03 UTC, JohanFreelancer9 approved these changes

2022-01-04 07:58 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-02-10 19:31 UTC, tiburd commented on microsoft-365/admin/manage/set-password-expiration-policy.md
> +> Password expiration notifications are no longer supported in Office web apps or the [Office portal](https://portal.office.com).
```suggestion
> Password expiration notifications are no longer supported in Office web apps or the [admin center](https://portal.office.com).
```

2022-02-10 19:42 UTC, merged