Update dlp-on-premises-scanner-get-started.md
MicrosoftDocs/microsoft-365-docs pull request #7363
Opened 2022-01-11 17:08 UTC by braalf

Adding license information on who needs a license to use the scanner.

2022-01-11 17:09 UTC, braalf commented
@chrfox

2022-01-14 15:16 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-15 04:36 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-on-premises-scanner-get-started.md
> +> All users that contribute to the scanned location either by adding files or consuming files need to have a license.  Not just the scanner user.
```suggestion
> All users who contribute to the scanned location either by adding files or consuming files need to have a license, not just the scanner user.
```

2022-01-15 04:36 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-15 08:17 UTC, yogkumgit commented
@braalf Please implement the suggested changes. Thanks

2022-01-16 11:19 UTC, braalf commented
@yogkumgit updated with suggested change.  Thank you.

2022-01-17 04:36 UTC, JohanFreelancer9 approved these changes

2022-01-18 10:25 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-01-20 18:25 UTC, merged