Update win11-overview.md
MicrosoftDocs/microsoft-365-docs pull request #7366
Opened 2022-01-11 20:03 UTC by sh783

@VinnieFlynt @dougeby for review. Removed references to pre-release Windows 11 on main overview.

2022-01-14 15:16 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-15 04:39 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/intro/win11-overview.md
> +Microsoft Managed Desktop continues to support Windows 10 in parallel until it reaches end of enterprise support. Please see [Windows 10 release information](/windows/release-health/release-informati
```suggestion
Microsoft Managed Desktop continues to support Windows 10 in parallel until it reaches end of enterprise support. See [Windows 10 release information](/windows/release-health/release-information) for life cycle information.
```

2022-01-15 04:42 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/intro/win11-overview.md
> +For Microsoft Managed Desktop devices, you can [add devices to the Windows 11 test device group] (https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/working-with-managed-desktop/test-win1
```suggestion
For Microsoft Managed Desktop devices, you can [add devices to the Windows 11 test device group] (/microsoft-365/managed-desktop/working-with-managed-desktop/test-win11-mmd?view=o365-worldwide#add-devices-to-the-windows-11-test-group). This group receives the Windows 11 general availability build along with a Microsoft Managed Desktop baseline configuration. Once added to the device group, allow one to two days for a device to pick up the new settings and be offered Windows 11.
```

2022-01-15 04:43 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/intro/win11-overview.md
> +For your devices that aren't managed by Microsoft Managed Desktop, you can read [Endpoint Manager guidance](https://techcommunity.microsoft.com/t5/microsoft-endpoint-manager-blog/endpoint-manager-sim
```suggestion
For your devices that aren't managed by Microsoft Managed Desktop, you can read [Endpoint Manager guidance](https://techcommunity.microsoft.com/t5/microsoft-endpoint-manager-blog/endpoint-manager-simplifies-upgrades-to-windows-11/ba-p/2771886) to learn about deploying Windows 11 yourself. If you have devices running Windows 11 and later, enroll them in Microsoft Managed Desktop; they won't revert back to Windows 10.
```

2022-01-15 04:48 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/intro/win11-overview.md
> +If you encounter app compatibility issues in test or production environments, you can receive no-cost support by opening a [service request] (https://docs.microsoft.com/en-us/microsoft-365/managed-de
```suggestion
If you encounter app compatibility issues in test or production environments, you can receive no-cost support by opening a [service request](/microsoft-365/managed-desktop/working-with-managed-desktop/test-win11-mmd?view=o365-worldwide#report-issues). For Windows 11, this includes any functionality with Office, Microsoft Edge, Teams, and line-of-business applications running on the latest operating system builds. Microsoft App Assure directly engages app publishers to prioritize and resolve app compatibility issues when needed.
```

2022-01-15 04:53 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-15 08:18 UTC, yogkumgit commented
@sh783 Please implement the suggested changes. Thanks

2022-01-21 20:23 UTC, merged