Update test-win11-mmd.md
MicrosoftDocs/microsoft-365-docs pull request #7367
Opened 2022-01-11 20:03 UTC by sh783

@VinnieFlynt @dougeby for review. Updated descriptions to remove "pre-release" references where appropriate. Note that the group still has "pre-release" in the name by design, an unfortunate artifact from when it was created prior to GA.

2022-01-14 15:17 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-15 05:00 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/working-with-managed-desktop/test-win11-mmd.md
```suggestion
```

2022-01-15 05:01 UTC, JohanFreelancer9 requested changes
Copy review - please remove the extra blank line. Thanks.

2022-01-15 08:19 UTC, yogkumgit commented
@sh783 implement the suggested changes. Thanks

2022-01-21 21:17 UTC, merged