Update ediscovery-decryption.md
MicrosoftDocs/microsoft-365-docs pull request #7375
Opened 2022-01-12 14:26 UTC by v-padum

Update for accuracy of behavior in the tool

2022-01-14 15:19 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-15 05:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery-decryption.md
> +- As previously explained, if you enable decryption of RMS-protected messages when you export them, you have to export the search results as individual messages. If you try to export search results t
```suggestion
- As previously explained, if you enable decryption of RMS-protected messages when you export them, you have to export the search results as individual messages. If you attempt to export search results to a PST file, RMS-protected messages will be exported as individual emails instead.
```

2022-01-15 05:28 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-15 08:20 UTC, yogkumgit commented
@v-padum Please implement the suggested changes. Thanks

2022-01-18 03:59 UTC, JohanFreelancer9 approved these changes

2022-01-24 13:29 UTC, yogkumgit commented
@markjjo Please merge this PR. Thanks

2022-03-15 11:21 UTC, yogkumgit commented
@markjjo Kindly merge this PR. Thanks

2022-04-14 18:07 UTC, merged