Update custom-detection-rules.md
MicrosoftDocs/microsoft-365-docs pull request #7401
Opened 2022-01-14 14:39 UTC by msbemba

Added statement for Alert tittle and detection name that they need to be unique as the rule does not get created if the name already exists.

2022-01-14 14:40 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-01-14 14:40 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7384

2022-01-15 04:02 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/custom-detection-rules.md
> +- **Detection name**—name of the detection rule and this needs to be unique.
```suggestion
- **Detection name**—name of the detection rule that needs to be unique.
```

2022-01-15 04:05 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/custom-detection-rules.md
> +- **Alert title**—title displayed with alerts triggered by the rule and this needs to be unique.
```suggestion
- **Alert title**—title displayed with alerts triggered by the rule; this title needs to be unique.
```

2022-01-15 04:07 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-15 07:54 UTC, yogkumgit commented
@msbemba

2022-01-15 08:28 UTC, yogkumgit commented
@JohanFreelancer9

2022-01-17 05:27 UTC, JohanFreelancer9 approved these changes

2022-01-17 06:28 UTC, yogkumgit commented
@schmurky Please merge this PR. Thanks

2022-02-03 19:46 UTC, DulceMontemayor commented
The base branch is out of date, please update and resend this merge request and i will approve, Thanks!

2022-02-04 08:26 UTC, yogkumgit commented
@msbemba

2022-02-04 13:10 UTC, msbemba commented
@yogkumgit Base branch has been updated.

2022-02-07 15:18 UTC, yogkumgit commented
@DulceMontemayor Please merge. Thanks

2022-02-10 17:44 UTC, DulceMontemayor commented
@yogkumgit please update the base branch, resubmit, and i will merge. Thank you!

2022-02-11 01:51 UTC, merged