Fixed for new UI
MicrosoftDocs/microsoft-365-docs pull request #7419
Opened 2022-01-17 23:21 UTC by dbroussa

Loading non O365 Data has been changed in the UI.  I have updated the steps to reflect the new change.

2022-01-18 07:16 UTC, JohanFreelancer9 commented on microsoft-365/compliance/load-non-Office-365-data-into-a-review-set.md
> +4. In the review set, click **Manage review set** (the down arrow just after the **Actions** option), and then click **Non-Office 365 data** option.
```suggestion
4. In the review set, click **Manage review set** (the down arrow just after the **Actions** option), and then click the **Non-Office 365 data** option.
```

2022-01-18 07:17 UTC, JohanFreelancer9 requested changes
Copy review - @dbroussa, kindly commit the minor suggested change. Many thanks.

2022-01-19 07:55 UTC, JohanFreelancer9 approved these changes

2022-01-19 14:27 UTC, yogkumgit commented
@markjjo Please merge this PR. Thanks

2022-01-24 18:41 UTC, merged