Fix "scan" description
MicrosoftDocs/microsoft-365-docs pull request #7452
Opened 2022-01-20 15:06 UTC by anvascon

Fix "scan" description

2022-01-21 09:46 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/live-response.md
> +| scan  | Runs an antivirus scan to help identify and remediate malware  | N  | Y  | Y  |
```suggestion
| scan  | Runs an antivirus scan to help identify and remediate malware.  | N  | Y  | Y  |
```

2022-01-21 09:47 UTC, JohanFreelancer9 requested changes
Copy review - @anvascon, kindly commit the minor suggested change. Many thanks.

2022-01-24 13:37 UTC, yogkumgit commented
@anvascon Please implement the suggested changes. Thanks

2022-01-25 04:22 UTC, JohanFreelancer9 approved these changes

2022-01-25 06:16 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-01-25 22:49 UTC, tiburd commented
@mjcaparas 
Hi, Joey,
Can you please review and merge, if you approve?
Thanks!

2022-01-25 23:18 UTC, merged