Update cross-tenant-mailbox-migration.md
MicrosoftDocs/microsoft-365-docs pull request #7471
Opened 2022-01-24 13:56 UTC by msbemba

Fixed mispelling

2022-01-24 13:56 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7453

2022-01-24 13:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-01-25 03:58 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-mailbox-migration.md
> +5. On the Register an application page, under Supported account types, Select Accounts in any organizational directory (Any Azure AD directory - Multitenant). Then under Redirect URI (optional), sele
```suggestion
5. On the Register an application page, under Supported account types, select Accounts in any organizational directory (Any Azure AD directory - Multitenant). Then, under Redirect URI (optional), select Web and enter <https://office.com>. Lastly, select Register.
```

2022-01-25 03:58 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-25 06:10 UTC, yogkumgit commented
@msbemba

2022-01-25 10:13 UTC, JohanFreelancer9 approved these changes

2022-01-25 16:16 UTC, merged