Update about-shared-mailboxes.md
MicrosoftDocs/microsoft-365-docs pull request #7478
Opened 2022-01-24 20:31 UTC by msbemba

Added details about shared mailbox licensing in Multi geo

2022-01-24 20:32 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7465

2022-01-24 20:32 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-01-25 07:39 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/about-shared-mailboxes.md
> +- **Multi-Geo** In a multi-geo environment, Shared mailboxes need to be licensed the same way a user mailbox is licensed. Note that cross-geo mailbox auditing is not supported. For example, if a user
```suggestion
- **Multi-Geo** In a multi-geo environment, shared mailboxes need to be licensed the same way a user mailbox is licensed. Note that cross-geo mailbox auditing is not supported. For example, if a user is assigned permissions to access a shared mailbox in a different geo location, mailbox actions performed by that user are not logged in the mailbox audit log of the shared mailbox. 
```

2022-01-25 07:39 UTC, JohanFreelancer9 requested changes
Copy review, @msbemba, kindly commit the minor suggested change. Many thanks.

2022-01-25 10:22 UTC, JohanFreelancer9 approved these changes

2022-01-26 01:33 UTC, merged