Update mdatp-portal-overview.png
MicrosoftDocs/microsoft-365-docs pull request #7488
Opened 2022-01-25 14:07 UTC by msbemba

Microsoft defender screenshot added

2022-01-25 14:08 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7377

2022-01-25 14:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-01-26 02:39 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/portal-overview.md
> +When you open the portal, you'll see Navigation pane (select the horizontal lines at the top of the navigation pane to show or hide it)
```suggestion
When you open the portal, you'll see the Navigation pane (select the horizontal lines at the top of the navigation pane to show or hide it).
```

2022-01-26 02:39 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-26 10:00 UTC, JohanFreelancer9 approved these changes

2022-01-26 11:26 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-02-02 21:30 UTC, merged