Update company-portal.md
MicrosoftDocs/microsoft-365-docs pull request #753
Opened 2019-11-15 22:00 UTC by mertenar

adding link for this to help admins @jaimeo

2019-11-17 13:12 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-17 14:11 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/get-started/company-portal.md
> +- How to send requests to IT administrators for applications that are not currently available. Documentation on this can be found [here in the Intune user help documentation](https://docs.microsoft.c
```suggestion
- How to send requests to IT administrators for applications that are not currently available. For more information, see [Request an app for work or school](https://docs.microsoft.com/intune-user-help/install-apps-cpapp-windows#request-an-app-for-work-or-school).  
```

2019-11-17 14:11 UTC, JohanFreelancer9 requested changes
Copy Review

2019-11-18 18:42 UTC, mertenar commented
@jaimeo incorporated

2019-11-18 19:00 UTC, merged