Update advanced-spam-filtering-asf-options.md
MicrosoftDocs/microsoft-365-docs pull request #754
Opened 2019-11-15 23:32 UTC by andypunt

Updating article to show deprecation

2019-11-17 13:09 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-17 14:26 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/advanced-spam-filtering-asf-options.md
> +>[!NOTE]
```suggestion
> [!NOTE]
```

2019-11-17 14:30 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/advanced-spam-filtering-asf-options.md
> +> The Anti-spam policy Advanced Spam filter settings are being deprecated at the time of this writing. Our recommended settings for these are to turn them **OFF**. The functions that were available i
```suggestion
> The Advanced Spam filter settings of the Anti-spam policy are currently being deprecated. Our recommended settings for these are to turn them **OFF**. The functions that were available in the Advanced Spam filter is being incorporated into other parts of the filtering stack.
```

2019-11-17 14:32 UTC, JohanFreelancer9 requested changes
Copy Review

2019-11-19 12:56 UTC, mypil commented
@MSFTTracyP  - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

2019-11-21 17:00 UTC, merged