Update info about renaming team site URL
MicrosoftDocs/microsoft-365-docs pull request #7540
Opened 2022-01-28 16:21 UTC by rgsteele

I wasn't able to verify whether the link to https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name will work correctly, please check before merging

2022-01-29 02:45 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/domains-faq.yml
> +          - **You may not be able to change your SharePoint domain name.** Your SharePoint domain name is based on your onmicrosoft.com domain name. The ability to [change the SharePoint domain name]
```suggestion
          - **You might not be able to change your SharePoint domain name.** Your SharePoint domain name is based on your onmicrosoft.com domain name. The ability to [change the SharePoint domain name](/sharepoint/change-your-sharepoint-domain-name) is available in public preview for organizations whose total SharePoint sites and OneDrive accounts number fewer than 1000.
```

2022-01-29 02:46 UTC, JohanFreelancer9 requested changes
Copy review - @rgsteele, kindly commit the suggested changes. Many thanks.

2022-02-01 05:17 UTC, yogkumgit commented
@rgsteele Gentle reminder, please implement the suggested changes. Thanks

2022-02-01 08:08 UTC, JohanFreelancer9 approved these changes

2022-02-02 06:11 UTC, yogkumgit commented
@pebaum Please merge this PR. Thanks

2022-02-02 16:49 UTC, merged