Update setup-guides-for-microsoft-365.md
MicrosoftDocs/microsoft-365-docs pull request #7557
Opened 2022-01-31 14:32 UTC by msbemba

Updated the setup guides with the recent changes made in the admin center.

2022-01-31 14:33 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7297

2022-01-31 14:33 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-01 03:52 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +3. Select **Advanced deployment guides** and clikc on **All guides**
```suggestion
3. Select **Advanced deployment guides** and then select **All guides**.
```

2022-02-01 03:54 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +The [Configure multifactor authentication (MFA) guide](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/featureexplorer/security/ConditionalAccess) provides information to Secure your
```suggestion
The [Configure multifactor authentication (MFA) guide](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/featureexplorer/security/ConditionalAccess) provides information to secure your organization against breaches due to lost or stolen credentials. MFA immediately increases account security by prompting for multiple forms of verification to prove a user's identity when they sign in to an app or other company resource. This prompt could be to enter a code on the user's mobile device or to provide a fingerprint scan. MFA is enabled through Conditional Access, security defaults, or per-user MFA. This guide will provide the recommended MFA option for your org, based on your licenses and existing configuration.
```

2022-02-01 03:57 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +[This guide](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/modernonboarding/identitywizard) will help streamline the process of getting your user accounts setup in **Microsoft 365*
```suggestion
[This guide](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/modernonboarding/identitywizard) will help streamline the process of getting your user accounts set up in **Microsoft 365**. Based on your environment and needs, you can choose to add users individually, migrate your on-premises directory with Azure AD cloud sync or Azure AD Connect, or troubleshoot existing sync problems when necessary.
```

2022-02-01 03:59 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +[This guide](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/azureadappintegration) helps helps IT admins to select and configure the App.
```suggestion
[This guide](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/azureadappintegration) helps IT admins to select and configure the App.
```

2022-02-01 04:01 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +
```suggestion
[This guide](https://admin.microsoft.com/Adminportal/Home?source=applauncher#/azureadappintegration) helps IT admins to select and configure the App.
```

2022-02-01 04:04 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +
```suggestion
The Microsoft security suite offers an integrated ecosystem to help protect your organization. This guide helps you analyze your security posture. The Microsoft secure score is a measurement of an organization's security posture, with a higher number indicating a stronger security posture.
```

2022-02-01 04:07 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/setup-guides-for-microsoft-365.md
> +The [Microsoft 365 Apps setup guide](https://aka.ms/OPPquickstartguide) helps you get your users' devices running the latest version of Office products like Word, Excel, PowerPoint, and OneNote. You'
```suggestion
The [Microsoft 365 Apps setup guide](https://aka.ms/OPPquickstartguide) helps you get your users' devices running the latest version of Office products like Word, Excel, PowerPoint, and OneNote. You'll get guidance on the various deployment methods that include easy self-install options to enterprise deployments with management tools. The instructions will help you assess your environment, figure out your specific deployment requirements, and implement the necessary support tools to ensure a successful installation.
```

2022-02-01 04:09 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-01 04:40 UTC, yogkumgit commented
@msbemba

2022-02-02 06:11 UTC, yogkumgit commented
@JohanFreelancer9

2022-02-02 11:52 UTC, JohanFreelancer9 approved these changes

2022-02-02 16:15 UTC, merged