Update offboard-machine-api.md
MicrosoftDocs/microsoft-365-docs pull request #7577
Opened 2022-02-01 19:28 UTC by msbemba

Added details on how to get the ID to offboard

2022-02-01 19:28 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-01 19:28 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7477

2022-02-02 10:31 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/offboard-machine-api.md
> +The machine id can be found on the URL when you select the device. Generally, it is a 40 digit alphanumeric number that can be found in the URL.
```suggestion
The machine ID can be found in the URL when you select the device. Generally, it is a 40 digit alphanumeric number that can be found in the URL.
```

2022-02-02 10:31 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-02 12:10 UTC, JohanFreelancer9 approved these changes

2022-02-02 14:47 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-02-02 21:38 UTC, merged