Update portals.md
MicrosoftDocs/microsoft-365-docs pull request #7580
Opened 2022-02-01 19:55 UTC by msbemba

Added AAD portal details to other workloads section

2022-02-01 19:55 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-01 19:55 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7521

2022-02-02 10:49 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/portals.md
> +| Azure active directory portal | View and manage [Azure Active Directory](/azure/active-directory/fundamentals/active-directory-whatis) | [aad.portal.azure.com](https://aad.portal.azure.com/) |
```suggestion
| Azure Active Directory portal | View and manage [Azure Active Directory](/azure/active-directory/fundamentals/active-directory-whatis) | [aad.portal.azure.com](https://aad.portal.azure.com/) |
```

2022-02-02 10:49 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-02 12:25 UTC, JohanFreelancer9 approved these changes

2022-02-02 14:48 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2022-02-11 15:23 UTC, merged