Update set-password-expiration-policy.md
MicrosoftDocs/microsoft-365-docs pull request #7581
Opened 2022-02-01 20:04 UTC by being-a-geek

Security and Privacy tab has moved under Settings> Org Settings in the Microsoft 365 Admin Portal

2022-02-02 14:49 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-02-03 15:35 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/set-password-expiration-policy.md
> +1. In the Microsoft 365 admin center, go to Settings, Org Settings, and then the <a href="https://go.microsoft.com/fwlink/p/?linkid=2072756" target="_blank">**Security & privacy** tab</a>.
```suggestion
1. In the Microsoft 365 admin center, go to **Settings** > **Org Settings**, and then select the <a href="https://go.microsoft.com/fwlink/p/?linkid=2072756" target="_blank">**Security & privacy** tab</a>.
```

2022-02-03 15:36 UTC, JohanFreelancer9 requested changes
Copy review - @being-a-geek, kindly commit the suggested change. Many thanks.

2022-02-03 15:40 UTC, being-a-geek commented
> Copy review - @being-a-geek, kindly commit the suggested change. Many thanks.

committed the suggested change

2022-02-03 16:35 UTC, JohanFreelancer9 approved these changes

2022-02-04 08:02 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-02-10 18:00 UTC, merged