Update use-the-delist-portal-to-remove-yourself-from-the-office-365-b…
MicrosoftDocs/microsoft-365-docs pull request #7619
Opened 2022-02-03 23:50 UTC by hudish

…locked-senders-lis.md

This proposed content change has been reviewed and verified by dhagarwal@microsoft.com.

2022-02-04 08:40 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-02-04 09:08 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md
> +>	550 5.7.511 Access denied, banned sender[xxx.xxx.xxx.xxx]. To request removal from this list please forward this message to delist {at} messaging.microsoft.com. For more information please go to ht
```suggestion
>	550 5.7.511 Access denied, banned sender[xxx.xxx.xxx.xxx]. To request removal from this list, forward this message to delist@messaging.microsoft.com. For more information. go to http://go.microsoft.com/fwlink/?LinkId=526653. 
```

2022-02-04 09:16 UTC, JohanFreelancer9 requested changes
Copy review - @hudish, kindly commit the suggested changes. Many thanks.

2022-02-04 16:03 UTC, hudish commented
I don't believe I have access to commit directly, can you help or clarify what I should do next?

2022-02-04 19:25 UTC, MSFTTracyP approved these changes
Thanks!

2022-02-04 22:03 UTC, merged

2022-02-07 20:23 UTC, MSFTTracyP commented
@Dansimp Does this need further action from me?