Update non-windows.md
MicrosoftDocs/microsoft-365-docs pull request #7642
Opened 2022-02-07 17:46 UTC by msbemba

Made changes to the document to add Plan 1 and 2 as Plan 1 supports macOS and android https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1?view=o365-worldwide#cross-platform-support

2022-02-07 17:47 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-07 17:49 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7609

2022-02-08 07:24 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/non-windows.md
> +- [Microsoft Defender for Office 365 plan 1 and plan 2](defender-for-office-365.md)
```suggestion
- [Microsoft Defender for Office 365 plan 1 and plan 2](/microsoft-365/security/office-365-security/defender-for-office-365)
```

2022-02-08 07:25 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-08 08:33 UTC, JohanFreelancer9 approved these changes

2022-02-08 13:11 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-02-20 13:55 UTC, yogkumgit commented
@mjcaparas Gentle reminder. Thanks

2022-02-23 16:45 UTC, mjcaparas commented
I don't think it's office 365 - Microsoft Defender for Office 365 plan 1 and plan 2. Shouldn't it be Defender for Endpoint Plan 1 and Plan 2? @msbemba

2022-02-23 17:01 UTC, msbemba commented
Thank you, @mjcaparas That is correct. I have made the changes to the PR and it should be good now.

Thank you
Sri

2022-02-25 19:22 UTC, merged