Update live-response-command-examples.md
MicrosoftDocs/microsoft-365-docs pull request #7665
Opened 2022-02-10 15:27 UTC by arnydo

Add comment regarding the \\ indicating a registry value vs key.
Added example for remediating a registry value.

2022-02-11 06:37 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/live-response-command-examples.md
> +# Show information about a specific registry value (the double backslash \\ indicates a registry value vs key)
```suggestion
# Show information about a specific registry value (the double backslash \\ indicates a registry value versus key)
```

2022-02-11 06:37 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/live-response-command-examples.md
> +# Remediate a registry value (the double backslash \\ indicates a registry value vs key)
```suggestion
# Remediate a registry value (the double backslash \\ indicates a registry value versus key)
```

2022-02-11 06:38 UTC, JohanFreelancer9 requested changes
Copy review - @arnydo, kindly commit the minor suggested changes. Many thanks.

2022-02-11 13:04 UTC, arnydo commented
I have committed the suggested changes.
Thank you!

2022-02-11 13:20 UTC, JohanFreelancer9 approved these changes

2022-02-20 13:15 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-02-23 01:00 UTC, merged

2022-02-24 19:02 UTC, arnydo commented
Thank you for the merge!