Update sensitivity-labels-sharepoint-onedrive-files.md
MicrosoftDocs/microsoft-365-docs pull request #771
Opened 2019-11-19 13:41 UTC by msbemba

Added Sharepoint latest version Info

2019-11-21 16:49 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-12-05 03:35 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md
> +Before you enable the preview, ensure that you're running SharePoint Online Management Shell Version 16.0.19418.12000 or above. If you already have the latest version, you can go ahead and enable the
```suggestion
Before you enable the preview, ensure that you're running SharePoint Online Management Shell version 16.0.19418.12000 or above. If you already have the latest version, you can go ahead and enable the preview.
```

2019-12-05 03:37 UTC, JohanFreelancer9 requested changes
Copy Review - minor edit

2019-12-06 14:27 UTC, mypil commented
@msbemba - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-12-10 19:07 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review. This is based on issue #771 

Thank you.

2019-12-12 22:25 UTC, cabailey commented
Approving this change

2019-12-12 22:26 UTC, merged