Updated timeouts \  limits
MicrosoftDocs/microsoft-365-docs pull request #7713
Opened 2022-02-15 16:45 UTC by mjmelone

Updated fileinfo limit and added per-command timeouts per discussion with @anvascon

2022-02-16 09:42 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/live-response.md
> +- Individual live response commands have a time limit of 10 minutes, with the exception of getfile, findfile, and run which have a limit of 30 minutes.
```suggestion
- Individual live response commands have a time limit of 10 minutes, with the exception of `getfile`, `findfile`, and `run`, which have a limit of 30 minutes.
```

2022-02-16 09:43 UTC, JohanFreelancer9 requested changes
Copy review - @mjmelone, kindly commit the suggested change. Many thanks.

2022-02-17 06:02 UTC, JohanFreelancer9 approved these changes

2022-02-20 13:17 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-02-23 00:50 UTC, merged