Update set-up-irm-in-sp-admin-center.md
MicrosoftDocs/microsoft-365-docs pull request #7724
Opened 2022-02-16 12:00 UTC by karthik55217

We updated PDF protector in SharePoint IRM, and updating the doc accordingly.

2022-02-20 13:17 UTC, yogkumgit commented
@JohanFreelancer9

2022-02-21 06:40 UTC, JohanFreelancer9 requested changes
Copy review - @karthik55217, not related to this PR but kindly also commit the minor suggested change to correct the typo. Many thanks.

2022-02-21 16:38 UTC, JohanFreelancer9 commented on microsoft-365/compliance/set-up-irm-in-sp-admin-center.md
>  You cannot create or edit documents in an IRM-enabled library using Office in a browser. Instead, one person at a time can download and edit IRM-encrypted files. Use check-in and check-out to manage
```suggestion
You cannot create or edit documents in an IRM-enabled library using Office in a browser. Instead, one person at a time can download and edit IRM-encrypted files. Use check-in and check-out to manage  *co-authoring*, or authoring across multiple users. 
```

2022-02-21 16:38 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-22 04:09 UTC, karthik55217 commented
@KCCross @JohanFreelancer9  - I committed the suggestions. Could you help merge this PR into main branch? (Looks like I do not have permissions to merge)

2022-02-22 04:35 UTC, JohanFreelancer9 approved these changes

2022-02-22 10:02 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-03-01 11:49 UTC, yogkumgit commented
@KCCross Gentle reminder.

2022-06-09 20:29 UTC, merged