Update ediscovery.md
MicrosoftDocs/microsoft-365-docs pull request #7782
Opened 2022-02-22 11:24 UTC by msbemba

Added M365 Business standard and Basic to content search after confirming here -https://aka.ms/M365BusinessPlans

2022-02-22 11:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-22 11:24 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7709

2022-02-22 13:25 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ediscovery.md
> +- Microsoft 365 Business Basic
```suggestion
- Microsoft 365 Business Standard subscription
- Microsoft 365 Business Basic subscription
```

2022-02-22 13:26 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-22 13:30 UTC, JohanFreelancer9 approved these changes

2022-02-23 06:55 UTC, yogkumgit commented
@markjjo Please merge this PR. Thanks

2022-03-01 11:40 UTC, yogkumgit commented
@markjjo Gentle reminder.

2022-03-15 11:16 UTC, yogkumgit commented
@markjjo Kindly merge this PR. Thanks

2022-03-15 17:27 UTC, merged