Update ome.md
MicrosoftDocs/microsoft-365-docs pull request #7784
Opened 2022-02-22 11:35 UTC by msbemba

tested and removed outlook.com as the experience is seamless

2022-02-22 11:35 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7748

2022-02-22 11:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-22 13:13 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome.md
> +Recipients of encrypted messages who receive encrypted or rights-protected mail sent to their Gmail, and Yahoo accounts receive a wrapper mail that directs them to the OME Portal where they can easil
```suggestion
Recipients of encrypted messages who receive encrypted or rights-protected mail sent to their Gmail and Yahoo accounts receive a wrapper mail that directs them to the OME Portal where they can easily authenticate using a Microsoft account, Gmail, or Yahoo credentials.
```

2022-02-22 13:14 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-22 13:33 UTC, JohanFreelancer9 approved these changes

2022-02-23 06:58 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-03-01 11:41 UTC, yogkumgit commented
@KCCross Gentle reminder

2022-03-15 06:40 UTC, yogkumgit commented
@KCCross Kindly merge this PR. Thanks

2022-06-09 20:33 UTC, KCCross commented
@samschan-ms - Review the situations where Microsoft accounts end up with an OPC. @msbemba - Requires more context.

2022-06-09 20:56 UTC, samschan-ms commented
@KCCross this is correct. Outlook.com can render encrypted mail inline.

2022-06-10 09:24 UTC, yogkumgit commented
@msbemba

2022-08-16 10:13 UTC, yogkumgit commented
@msbemba Please add a comment.

2022-08-22 03:56 UTC, msbemba commented
@yogkumgit Sam has confirmed that Outlook.com can render encrypted mail inline. It is seamless per my testing as well.

We can check with KC Cross to see if this can be merged now.

2022-08-22 14:43 UTC, yogkumgit commented
@KCCross Please comment or merge this PR. Thanks

2022-09-28 16:25 UTC, opbld32 commented
Learn Build status updates of commit _[df0c777](https://github.com/msbemba/microsoft-365-docs/commits/df0c777f4d7d74884e02d95fadebad13469ce4c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/ome.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-942/microsoft-365/compliance/ome.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209281621407183-7784/BuildReport?accessString=4fb177bc32a71e4d504dc4f7845e9dccf3f258bf7fc0bc630ddef360f8e70a53).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-28 16:26 UTC, merged