Update onedrive-lti.md
MicrosoftDocs/microsoft-365-docs pull request #7794
Opened 2022-02-23 05:30 UTC by msbemba

Added another step after 9 stating that the remaining permission are needed. so another admin consent is required.

2022-02-23 05:30 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2022-02-23 05:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7686

2022-02-23 07:26 UTC, JohanFreelancer9 commented on microsoft-365/lti/onedrive-lti.md
> +10. Sign into the <a href="https://onedrivelti.microsoft.com/admin" target="_blank">Microsoft OneDrive LTI Registration Portal</a> and  Select the **Admin Consent** button and accept the remaining pe
```suggestion
10. Sign into the <a href="https://onedrivelti.microsoft.com/admin" target="_blank">Microsoft OneDrive LTI Registration Portal</a>, select the **Admin Consent** button, and accept the remaining permissions.
```

2022-02-23 07:27 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-23 10:11 UTC, JohanFreelancer9 approved these changes

2022-02-25 11:18 UTC, yogkumgit commented
@MicrosoftHeidi Please merge this PR. Thanks

2022-03-01 11:39 UTC, yogkumgit commented
@MicrosoftHeidi Gentle reminder.

2022-03-15 06:38 UTC, yogkumgit commented
@MicrosoftHeidi Kindly merge this PR. Thanks

2022-05-09 14:09 UTC, merged