Update password-policy-recommendations.md
MicrosoftDocs/microsoft-365-docs pull request #7796
Opened 2022-02-23 06:01 UTC by msbemba

Added detail stating that password policy for Cloud only accounts cannot be changed and The only item you can change is how many days until a password expires and whether or not passwords expire at all.

2022-02-23 06:01 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-23 06:01 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7727

2022-02-23 07:41 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/password-policy-recommendations.md
> +For Cloud Only Accounts Microsoft has a pre-defined password policy that can't be changed. The only item you can change is how many days until a password expires and whether or not passwords expire a
```suggestion
Microsoft cloud-only accounts have a pre-defined password policy that cannot be changed. The only items you can change are the number of days until a password expires and whether or not passwords expire at all. 
```

2022-02-23 07:42 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-23 10:12 UTC, JohanFreelancer9 approved these changes

2022-02-25 11:19 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-03-01 11:41 UTC, yogkumgit commented
@kwekuako Gentle reminder.

2022-03-02 01:48 UTC, merged