Update advanced-features.md
MicrosoftDocs/microsoft-365-docs pull request #7804
Opened 2022-02-23 20:46 UTC by edberei

Made clarification to documentation

2022-02-24 06:43 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/advanced-features.md
> +> Live Response requires Automated investigation to be turned on before you can enable it in the advanced settings section in the MDE portal.
```suggestion
> Live response requires **Automated investigation** to be turned on before you can enable it in the advanced settings section in the Microsoft for Endpoint portal.
```

2022-02-24 06:44 UTC, JohanFreelancer9 requested changes
Copy review - @edberei, kindly commit the suggested changes. Many thanks.

2022-02-25 11:20 UTC, yogkumgit commented
@edberei Gentle reminder. Thanks

2022-02-25 16:57 UTC, edberei commented
I believe I just pushed it out, thank you!

Ed Berei
Support Engineer | Endpoint Protection
Customer Service & Support | Microsoft Corporation
*(980) 776-1263  * ***@***.******@***.***>
Working Hours: Mon-Fri 8:30 am - 5:30pm EST (UTC-4)
If you'd like to provide feedback about my service, please e-mail my manager at ***@***.******@***.***>

***@***.***

From: Yogesh Kumar ***@***.***>
Sent: Friday, February 25, 2022 6:21 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Ed Berei ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update advanced-features.md (PR #7804)


@edberei<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fedberei&data=04%7C01%7Cedberei%40microsoft.com%7C46e90679b0a04a7023c708d9f850dbb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637813848439348315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=37tqvL2RNEKLOTHXoyHBo89l3fzSett6l9be5ezTdgk%3D&reserved=0> Gentle reminder. Thanks

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F7804%23issuecomment-1050767115&data=04%7C01%7Cedberei%40microsoft.com%7C46e90679b0a04a7023c708d9f850dbb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637813848439398223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ddKZGI4op0FznFxyJIFYu92zJv%2F5E4XILsjvnmMUePY%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXSR6NO4ABH2QAXUPXLVEMTU45QYTANCNFSM5PFPDFUA&data=04%7C01%7Cedberei%40microsoft.com%7C46e90679b0a04a7023c708d9f850dbb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637813848439398223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1XqjIZS1o3RCK3T82EByY%2F8qlIxyF70FJoeqYLuYkB0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cedberei%40microsoft.com%7C46e90679b0a04a7023c708d9f850dbb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637813848439398223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QUuXU4%2FNW1Ymf6azdTL3mCE8K1V0k1Womh5KZIlZB3A%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cedberei%40microsoft.com%7C46e90679b0a04a7023c708d9f850dbb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637813848439398223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6nuZrLgJNMw2saYa3AFAfPSOhMsAicc8eLVLDZQuXYg%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-02-25 19:13 UTC, merged