Update configure-extension-file-exclusions-microsoft-defender-antivir…
MicrosoftDocs/microsoft-365-docs pull request #7818
Opened 2022-02-25 07:34 UTC by msbemba

…us.md

Added a important note about wild card

2022-02-25 07:34 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7765

2022-02-25 07:34 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-02-25 09:44 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md
> +> - You can only use a maximum of 6 wildcards per entry.
```suggestion
> - You can only use a maximum of six wildcards per entry.
```

2022-02-25 09:45 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-25 11:37 UTC, JohanFreelancer9 approved these changes

2022-02-25 11:38 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2022-02-27 22:34 UTC, denisebmsft approved these changes
Thank you @msbemba

2022-02-27 22:35 UTC, merged