replaced link
MicrosoftDocs/microsoft-365-docs pull request #7873
Opened 2022-03-02 04:25 UTC by RAJU2529

as per user report #7860 , so i removed invalid lik and replaced wit correct link.

2022-03-02 09:04 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-using.md
> +- [Onboarding tools and methods for Windows 10 machines](https://docs.microsoft.com/microsoft-365/compliance/device-onboarding-overview?view=o365-worldwide)
```suggestion
- [Onboard Windows 10 and Windows 11 devices into Microsoft 365 overview](/microsoft-365/compliance/device-onboarding-overview)
```

2022-03-02 09:05 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-02 10:57 UTC, JohanFreelancer9 approved these changes

2022-03-03 12:34 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-03 15:49 UTC, merged