Updating Loose Files and PSTs folder structure
MicrosoftDocs/microsoft-365-docs pull request #7905
Opened 2022-03-03 21:34 UTC by marstev

We received an escalation a few months back where customer performed an export, and an additional folder was in the Exchange folder with name <username>_looseFiles. This was not documented anywhere, and customer did not know why they were getting this folder.

2022-03-04 08:20 UTC, JohanFreelancer9 commented on microsoft-365/compliance/export-documents-from-review-set.md
> +        - Any messages that were IRM protected and have been decoded.
```suggestion
        - Any Information Rights Management (IRM) protected messages that have been decoded. 
```

2022-03-04 08:22 UTC, JohanFreelancer9 commented on microsoft-365/compliance/export-documents-from-review-set.md
> +        - Any modern attachments/links referenced in e-mails.
```suggestion
        - Any error-remediated messages. 
        - Any modern attachments or links referenced in emails. 
```

2022-03-04 08:23 UTC, JohanFreelancer9 requested changes
Copy review - @marstev, kindly commit the minor suggested changes. Many thanks.

2022-03-04 23:08 UTC, markjjo commented
@marstev Thanks for submitting this PR. Can you please update the PR and clarify and add more information about this statement: " Encrypted items are not added back into the PST."  Do you mean that encrypted items that are not included in the PST will be exported to the Exchange folder?

2022-03-07 16:57 UTC, nahz3matics commented
@markjjo To my understanding the encrypted items will be in the loose files and not actual PST. I can go ahead and remove it for now as the previous lines should be enough detail to what could be included in the loose files.

2022-03-07 17:00 UTC, marstev commented
@markjjo Was not signed in with FTE account in my response. I can go ahead and remove it for now as the previous lines should be enough detail to what could be included in the loose files.

2022-03-07 17:08 UTC, marstev reviewed
removing line

2022-03-07 17:36 UTC, markjjo commented
@marstev Thanks very much for the response and removing the line. I will merge the PR. The updated changes should be live by end of the day.

2022-03-07 17:48 UTC, merged