Update overview.md
MicrosoftDocs/microsoft-365-docs pull request #7926
Opened 2022-03-06 02:21 UTC by msbemba

Removed all references to windows phone  as it is no longed supported platform

2022-03-06 02:21 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-06 02:21 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7878

2022-03-07 06:34 UTC, JohanFreelancer9 commented on microsoft-365/admin/basic-mobility-security/overview.md
> +You can use Basic Mobility and Security to manage many types of mobile devices like  Android, iPhone, and iPad. To manage mobile devices used by people in your organization, each person must have an
```suggestion
You can use Basic Mobility and Security to manage many types of mobile devices like Android, iPhone, and iPad. To manage mobile devices used by people in your organization, each person must have an applicable Microsoft 365 license and their device must be enrolled in Basic Mobility and Security.
```

2022-03-07 06:35 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-07 08:55 UTC, JohanFreelancer9 approved these changes

2022-03-13 03:29 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-06-10 00:20 UTC, merged