Update set-up-new-message-encryption-capabilities.md
MicrosoftDocs/microsoft-365-docs pull request #7928
Opened 2022-03-06 04:25 UTC by msbemba

added step to troubleshoot if step3 fails.

2022-03-06 04:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-06 04:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7886

2022-03-07 06:51 UTC, JohanFreelancer9 commented on microsoft-365/compliance/set-up-new-message-encryption-capabilities.md
> +4.If the test fails with an error message **Failed to acquire RMS templates**, you need to execute the following commands and  Run the Test-IRMConfiguration cmdlet to verify it passes.
```suggestion
4. If the test fails with an error message **Failed to acquire RMS templates**, you need to execute the following commands and  Run the Test-IRMConfiguration cmdlet to verify that it has passed.
```

2022-03-07 06:54 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-07 08:51 UTC, JohanFreelancer9 approved these changes

2022-03-13 03:30 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-03-13 05:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/set-up-new-message-encryption-capabilities.md
> +4. If the test fails with an error message **Failed to acquire RMS templates**, execute the following commands and  Run the Test-IRMConfiguration cmdlet to verify that it passes.
```suggestion
4. If the test fails with an error message **Failed to acquire RMS templates**, execute the following commands and run the Test-IRMConfiguration cmdlet to verify that it passes.
```

2022-03-13 05:54 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2022-03-14 07:17 UTC, JohanFreelancer9 approved these changes

2022-06-09 20:52 UTC, merged