Update secure-score-improvement-action-details.png
MicrosoftDocs/microsoft-365-docs pull request #7930
Opened 2022-03-06 04:47 UTC by msbemba

Changed screenshot for improvement action as it has changed.

2022-03-06 04:47 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7778

2022-03-06 04:47 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-07 06:59 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/microsoft-secure-score-improvement-actions.md
> +- Select **Manage in Microsoft 365 Defender** to go the configuration screen and make the change. You'll then gain the points that the action is worth, visible in the fly out. Points generally take a
```suggestion
- Select **Manage in Microsoft 365 Defender** to go to the configuration screen and make the change. You'll then gain the points that the action is worth, visible in the flyout. Points generally take about 24 hours to update.
```

2022-03-07 06:59 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-07 08:50 UTC, JohanFreelancer9 approved these changes

2022-03-15 07:00 UTC, yogkumgit commented
@Dansimp Kindly merge this PR. Thanks

2022-03-30 15:08 UTC, merged