Update device-onboarding-offboarding-macos-jamfpro.md
MicrosoftDocs/microsoft-365-docs pull request #7939
Opened 2022-03-07 21:27 UTC by tewchen

2022-03-10 00:26 UTC, mjcaparas commented
@tewchen not sure what you mean by "an identify" can you clarify?

2022-03-11 03:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/device-onboarding-offboarding-macos-jamfpro.md
> +- Make sure your macOS devices are associated with an identify (Azure AD joined UPN) through JAMF Connect
```suggestion
- Make sure your macOS devices are associated with an identifiable Azure AD joined UPN through JAMF Connect
```

2022-03-11 03:56 UTC, JohanFreelancer9 requested changes
Copy review - @tewchen, kindly commit the suggested changes if you agree with them. Many thanks.

2022-03-12 02:39 UTC, JohanFreelancer9 approved these changes

2022-03-14 17:56 UTC, merged