Update customer-key-set-up.md
MicrosoftDocs/microsoft-365-docs pull request #7946
Opened 2022-03-08 20:22 UTC by sathana87

2022-03-11 03:27 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> +SharePoint Online (SPO) uses Azure Key Vaults where customer store the keys that they want use to encrypt their documents and files in SharePoint Online and OneDrive for Business.
```suggestion
SharePoint Online uses Azure Key Vaults where you store the keys that you want to use to encrypt your documents and files in SharePoint Online and OneDrive for Business. 
```
```suggestion
SharePoint Online (SPO) uses Azure Key Vaults where customer store the keys that they want use to encrypt their documents and files in SharePoint Online and OneDrive for Business. 
```

2022-03-11 03:27 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> +SharePoint Online (SPO) uses Azure Key Vaults where customer store the keys that they want use to encrypt their documents and files in SharePoint Online and OneDrive for Business.
```suggestion
SharePoint Online uses Azure Key Vaults where you store the keys that you want to use to encrypt your documents and files in SharePoint Online and OneDrive for Business. 
```
```suggestion
SharePoint Online (SPO) uses Azure Key Vaults where customer store the keys that they want use to encrypt their documents and files in SharePoint Online and OneDrive for Business. 
```

2022-03-11 03:30 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> + SPO supports both Standard/Premium vaults as well as Managed HSM.
```suggestion
 Azure Key Vault provides two types of containers:

- Premium Key Vaults for storing and managing cryptographic keys, secrets, certificates, and storage account keys. These come in Standard and Premium vaults. These vaults are certified to FIPS 140-2 Level-2.   

- Managed HSM pool for storing and managing HSM-backed cryptographic keys. Managed HSMs are certified to FIPS 140-2 Level-2. 

 SharePoint Online supports both Standard and Premium vaults as well as Managed HSM.
```
```suggestion
 Azure Key Vault provides two types of containers, 


1) Premium key Vaults for storing and managing cryptographic keys, secrets, certificates and storage account keys. These come in Standard and Premium vaults. These vaults are certified to FIPS 140-2 Level-2.   

2) Managed HSM pool for storing and managing HSM-backed cryptographic keys. Managed HSMs are certified to FIPS 140-2 Level-2. 

 SPO supports both Standard/Premium vaults as well as Managed HSM.
```

2022-03-11 03:30 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> + SPO supports both Standard/Premium vaults as well as Managed HSM.
```suggestion
 Azure Key Vault provides two types of containers:

- Premium Key Vaults for storing and managing cryptographic keys, secrets, certificates, and storage account keys. These come in Standard and Premium vaults. These vaults are certified to FIPS 140-2 Level-2.   

- Managed HSM pool for storing and managing HSM-backed cryptographic keys. Managed HSMs are certified to FIPS 140-2 Level-2. 

 SharePoint Online supports both Standard and Premium vaults as well as Managed HSM.
```
```suggestion
 Azure Key Vault provides two types of containers, 


1) Premium key Vaults for storing and managing cryptographic keys, secrets, certificates and storage account keys. These come in Standard and Premium vaults. These vaults are certified to FIPS 140-2 Level-2.   

2) Managed HSM pool for storing and managing HSM-backed cryptographic keys. Managed HSMs are certified to FIPS 140-2 Level-2. 

 SPO supports both Standard/Premium vaults as well as Managed HSM.
```

2022-03-11 03:35 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> + SPO supports both Standard/Premium vaults as well as Managed HSM.
```suggestion
  Azure Key Vault provides two types of containers:

- Premium Key Vaults for storing and managing cryptographic keys, secrets, certificates, and storage account keys. These come in Standard and Premium vaults. These vaults are certified to FIPS 140-2 Level-2.   

- Managed HSM pool for storing and managing HSM-backed cryptographic keys. Managed HSMs are certified to FIPS 140-2 Level-2.

SharePoint Online supports both Standard and Premium vaults as well as Managed HSM.```

2022-03-11 03:35 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> + SPO supports both Standard/Premium vaults as well as Managed HSM.
```suggestion
  Azure Key Vault provides two types of containers:

- Premium Key Vaults for storing and managing cryptographic keys, secrets, certificates, and storage account keys. These come in Standard and Premium vaults. These vaults are certified to FIPS 140-2 Level-2.   

- Managed HSM pool for storing and managing HSM-backed cryptographic keys. Managed HSMs are certified to FIPS 140-2 Level-2.

SharePoint Online supports both Standard and Premium vaults as well as Managed HSM.```

2022-03-11 03:38 UTC, JohanFreelancer9 requested changes
Copy review - @sathana87, kindly commit the suggested changes. Many thanks.

2022-03-15 10:16 UTC, yogkumgit commented
@sathana87 Please implement the suggested changes. Thanks

2022-03-16 17:33 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-set-up.md
> +SharePoint Online (SPO) uses Azure Key Vaults where customer store the keys that they want use to encrypt their documents and files in SharePoint Online and OneDrive for Business.
```suggestion
SharePoint Online uses Azure Key Vaults where you store the keys that you want to use to encrypt your documents and files in SharePoint Online and OneDrive for Business. 
```

2022-03-17 04:23 UTC, yogkumgit commented
@sathana87 Please update . Thanks

2022-03-23 12:26 UTC, yogkumgit commented
@sathana87 Gentle reminder.

2022-08-16 10:11 UTC, yogkumgit commented
@sathana87 Please implement the suggested changes, in the event of no response we may may have to close this PR. Thanks

2022-08-25 04:47 UTC, yogkumgit commented
@sathana87 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

2022-08-25 04:47 UTC, closed without merging