Update ome-advanced-message-encryption.md
MicrosoftDocs/microsoft-365-docs pull request #7949
Opened 2022-03-08 20:49 UTC by lindabrGithub

@KCCross we have request from EEE to add the following note due to PG escalation.  Can you help with this.

"Advanced Message Encryption revocation and expiration functions will not function unless the "Premium Encryption in Office 365" option is enabled in their E5 license."

2022-03-11 02:46 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-advanced-message-encryption.md
> +Note:"Advanced Message Encryption revocation and expiration functions will not function unless the "Premium Encryption in Office 365" option is enabled in their E5 license."
```suggestion
> [!NOTE]
> Advanced Message Encryption revocation and expiration functions will not function unless you enable the **Premium Encryption in Office 365** option in your E5 license.
```

2022-03-11 02:50 UTC, JohanFreelancer9 requested changes
Copy review - @lindabrGithub, kindly commit the suggested changes if you agree with them. Many thanks.

2022-03-15 10:14 UTC, yogkumgit commented
@lindabrGithub Please implement the suggested changes. Thanks

2022-03-23 12:28 UTC, yogkumgit commented
@lindabrGithub Gentle reminder

2022-03-24 14:52 UTC, lindabrGithub commented
@yogkumgit , sorry for the delay, I missed the comment.  Let me know if there is anything else you need me to do to complete this.

2022-03-25 04:49 UTC, JohanFreelancer9 approved these changes

2022-03-25 12:36 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-04-01 19:20 UTC, merged