Update Yammer in M365 group auto renewal
MicrosoftDocs/microsoft-365-docs pull request #7982
Opened 2022-03-11 07:54 UTC by slowik84

added Yammer auto renewal feature based on https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-lifecycle and removed note about file add

2022-03-11 18:50 UTC, MikePlumleyMSFT commented
@ArunMSFT can you review?

2022-03-12 07:36 UTC, JohanFreelancer9 commented on microsoft-365/solutions/microsoft-365-groups-expiration-policy.md
> +- Yammer: View a post within a Yammer community or an interactive email in Outlook
```suggestion
- Yammer: View a post within a Yammer community or an interactive email in Outlook.
```

2022-03-12 07:36 UTC, JohanFreelancer9 requested changes
Copy review @slowik84, kindly commit the minor suggested change. Many thanks.

2022-03-23 12:30 UTC, yogkumgit commented
@slowik84 Gentle reminder, Please implement the suggested changes. Thanks

2022-03-23 14:49 UTC, ArunMSFT commented
Looks good to me.

@Mike ***@***.***> FYI

From: Mike Plumley ***@***.***>
Sent: Saturday, March 12, 2022 12:21 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Arunkumaran Varadharajan ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update Yammer in M365 group auto renewal (PR #7982)


@ArunMSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FArunMSFT&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7Ce092ad5b35764f74113008da03900baa%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637826214461145423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AqPuiWwNMnxVkIqBcSNJCeaf1S%2B2Bv9jetacoRcS2GY%3D&reserved=0> can you review?

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F7982%23issuecomment-1065394856&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7Ce092ad5b35764f74113008da03900baa%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637826214461145423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sFKhN90crw2NdBnIN9%2Bnali1nr4p%2B4LL8NFai3j2O9U%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHZV2TGON6Y4GSYVC55NTSDU7OIYFANCNFSM5QO35XVQ&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7Ce092ad5b35764f74113008da03900baa%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637826214461145423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=16gBpFdsF5gnWQzNjfR3BCcYlRVCZfxd10cClBMCvCU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7Ce092ad5b35764f74113008da03900baa%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637826214461145423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YwWLx9H0%2BVOYchEHLYneJLkwlcf99IvDjkcMQewBei8%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Carunkumaran.varadharajan%40microsoft.com%7Ce092ad5b35764f74113008da03900baa%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637826214461145423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LhVOiHk0zXfexgTjkJsG0U60sS%2B2ECl2LCghE36M4rE%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-03-28 21:26 UTC, ArunMSFT commented
Thanks so much, Mike Plumley, for making this change. One request...SharePoint, Outlook, and Teams are all followed by a hyphen before the statement which explains their renewal activities. Can we do the same for Yammer in this particular article? Currently I see a colon in GitHub, presumably because it was copy&pasted from the other article. Thanks!

Mike McLean

From: Arunkumaran Varadharajan ***@***.***>
Sent: Wednesday, March 23, 2022 7:50 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>; MicrosoftDocs/microsoft-365-docs ***@***.***>; Mike McLean ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Update Yammer in M365 group auto renewal (PR #7982)

Looks good to me.

@Mike ***@***.***> FYI

From: Mike Plumley ***@***.******@***.***>>
Sent: Saturday, March 12, 2022 12:21 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.******@***.***>>
Cc: Arunkumaran Varadharajan ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update Yammer in M365 group auto renewal (PR #7982)


@ArunMSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FArunMSFT&data=04%7C01%7CMichael.McLean%40microsoft.com%7C946d971b3326416a008108da0cdc5733%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637836437759478139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UbOGjTyWy0AS7L%2FTxsaLGK%2BgmPFHDvSFq41%2F%2FiOPGL8%3D&reserved=0> can you review?

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F7982%23issuecomment-1065394856&data=04%7C01%7CMichael.McLean%40microsoft.com%7C946d971b3326416a008108da0cdc5733%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637836437759478139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=utV7Uk2KsezrEkR3dd5e7q0k9dyvpOJJ9ZHX80xlSn8%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHZV2TGON6Y4GSYVC55NTSDU7OIYFANCNFSM5QO35XVQ&data=04%7C01%7CMichael.McLean%40microsoft.com%7C946d971b3326416a008108da0cdc5733%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637836437759478139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jcpRQRZ3C%2BqZpXRQbEc71HkqT6wf35Wj%2F9ITtTAmV00%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMichael.McLean%40microsoft.com%7C946d971b3326416a008108da0cdc5733%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637836437759478139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EiJJpqdpN%2FYwjqh4szF1jKtaG7hWGQi6pwDhACpGFrU%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMichael.McLean%40microsoft.com%7C946d971b3326416a008108da0cdc5733%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637836437759478139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eE2PVCx91%2FRgN5ZlqWM%2BnRJBqULzukU8GAl8ORap%2B74%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-03-29 03:48 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-29 12:34 UTC, JohanFreelancer9 requested changes
Suggestion updated in accordance with @ArunMSFT's observation. @slowik84, kindly commit the suggested change.

2022-05-11 04:40 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-11 07:30 UTC, JohanFreelancer9 commented on microsoft-365/solutions/microsoft-365-groups-expiration-policy.md
> +- Yammer - View a post within a Yammer community or an interactive email in Outlook.
```suggestion
- Yammer - view a post within a Yammer community or an interactive email in Outlook.
```

2022-05-11 07:31 UTC, JohanFreelancer9 requested changes
@slowik84, apologies - one more minor change for consistency, please.

2022-06-28 13:27 UTC, yogkumgit commented
@slowik84 Gentle reminder. Thanks

2023-03-29 14:28 UTC, yogkumgit commented
@slowik84 closing the PR, as suggested changes are not implemented. Please feel free to reopen it, in case you wish to take an action. Thanks

2023-03-29 14:28 UTC, closed without merging