Update data-classification-content-explorer.md with latest
MicrosoftDocs/microsoft-365-docs pull request #7983
Opened 2022-03-11 10:01 UTC by shparshw

Onedrive and EXO SITs are no longer in preview. 
Teams is released WW.

2022-03-12 07:23 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-content-explorer.md
> +> It can take upto *seven days* for counts to be updated in Content Explorer.
```suggestion
> It can take up to *seven days* for counts to be updated in content explorer.
```

2022-03-12 07:24 UTC, JohanFreelancer9 requested changes
Copy review - @shparshw, kindly commit the suggested change. Many thanks.

2022-03-12 11:55 UTC, shparshw commented
Completing the PR.

2022-03-12 12:09 UTC, shparshw commented
Completing PR

2022-03-13 01:30 UTC, JohanFreelancer9 approved these changes

2022-03-13 02:07 UTC, JohanFreelancer9 approved these changes

2022-03-14 16:43 UTC, merged