Update view-service-health.md
MicrosoftDocs/microsoft-365-docs pull request #7993
Opened 2022-03-13 15:27 UTC by msbemba

Made changes to reduce ambiguity on how to access Service health

2022-03-13 15:27 UTC, msbemba commented
@JohanFreelancer9 please copy review

2022-03-13 15:27 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7903

2022-03-14 07:00 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/view-service-health.md
> +2. To view service health, in the in the left-hand navigation of the admin center, go to **Health** > **Service health**, or select the **Service health** card on the **Home dashboard**. The dashboar
```suggestion
2. To view service health, in the left-hand navigation of the admin center, go to **Health** > **Service health**, or select the **Service health** card on the **Home dashboard**. The dashboard card indicates whether there is an active service issue and links to the detailed **Service health** page.
```

2022-03-14 07:00 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-14 12:42 UTC, JohanFreelancer9 approved these changes

2022-03-14 13:43 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-03-14 15:17 UTC, merged