Update enable-the-report-message-add-in.md
MicrosoftDocs/microsoft-365-docs pull request #7995
Opened 2022-03-13 16:26 UTC by msbemba

Cleared both (On prem and shared mailboxes) into different lines that way there is less ambiguity.

2022-03-13 16:26 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-13 16:26 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7921

2022-03-14 06:52 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/enable-the-report-message-add-in.md
> +- Both add-ins aren't available for shared mailboxes.
```suggestion
- Both add-ins are not available for shared mailboxes.
```

2022-03-14 06:52 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-14 12:58 UTC, JohanFreelancer9 approved these changes

2022-03-14 13:47 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2022-03-14 16:35 UTC, merged