Update respond-file-alerts.md
MicrosoftDocs/microsoft-365-docs pull request #7997
Opened 2022-03-13 16:54 UTC by msbemba

Added Defender for plan 1 to the applies to as Plan 1 allows file indicators - Verified with the overview document/reference -https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1?view=o365-worldwide#manual-response-actions

2022-03-13 16:55 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-13 16:55 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7936

2022-03-14 06:25 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/respond-file-alerts.md
> +-[Microsoft Defender for Endpoint Plan 1](/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1)
```suggestion

- [Microsoft Defender for Endpoint Plan 1](/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1)
```

2022-03-14 06:25 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-14 13:03 UTC, JohanFreelancer9 approved these changes

2022-03-14 13:51 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-03-23 12:31 UTC, yogkumgit commented
@mjcaparas Gentle reminder.

2022-03-28 17:13 UTC, merged