Appending a different way of calling X64
MicrosoftDocs/microsoft-365-docs pull request #8048
Opened 2022-03-17 17:08 UTC by kaustd

Can we add x86_64 which in my understanding is also called X64 for more clarification while retaining other information as is.

2022-03-18 08:06 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md
> +- Supported Linux server distributions and x64 (AMD64/EM64T) / x86_64 versions:
```suggestion
- Supported Linux server distributions and x64 (AMD64/EM64T) and x86_64 versions:
```

2022-03-18 08:07 UTC, JohanFreelancer9 requested changes
Copy review - @kaustd, kindly commit the minor suggested change. Many thanks.

2022-03-20 04:38 UTC, JohanFreelancer9 approved these changes

2022-03-23 12:33 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-03-28 17:14 UTC, merged