removed "Action" section
MicrosoftDocs/microsoft-365-docs pull request #809
Opened 2019-11-22 05:14 UTC by MaratMussabekov

as the only possible action is "quarantine" - see the note [here](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/new-malwarefilterpolicy?view=exchange-ps)
#737

2019-11-24 16:27 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-25 02:26 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/anti-malware-protection.md
> +When malware is detected, Exchange Online Protection allows the messages being delivered, but attachments that contain malware are quarantined. Anti-malware policies control notification options for
```suggestion
When malware is detected, Exchange Online Protection allows the messages to be delivered, but attachments that contain malware are quarantined. Anti-malware policies control notification options for malware detection. The important settings in anti-malware policies are:
```

2019-11-25 02:27 UTC, JohanFreelancer9 requested changes
Copy Review

2019-11-30 09:47 UTC, mypil commented
@MSFTTracyP - PR has been copy edited and is ready for final review. This is based on issue #737

Thank you.

cc: @kenwith

2019-12-07 00:46 UTC, merged