typo correction
MicrosoftDocs/microsoft-365-docs pull request #8120
Opened 2022-03-25 18:09 UTC by RAJU2529

as per user report #8086, so i corrected word.

2022-03-27 02:27 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-28 06:18 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/configure-server-endpoints.md
>  >[!NOTE]
```suggestion
> [!NOTE]
```

2022-03-28 06:18 UTC, JohanFreelancer9 requested changes
Copy review - minor additional suggestion, please.

2022-03-28 07:29 UTC, JohanFreelancer9 approved these changes

2022-03-28 11:15 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-28 16:53 UTC, merged