Update web-content-filtering.md
MicrosoftDocs/microsoft-365-docs pull request #8162
Opened 2022-03-31 08:04 UTC by msbemba

Web content filtering works with M365 E3

MDEP1 is included in E3 .

2022-03-31 08:04 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8074

2022-03-31 08:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-31 09:12 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/web-content-filtering.md
> +- Your subscription includes one of the following: Windows 10 Enterprise E5, Microsoft 365 E5, Microsoft 365 E5 Security, Microsoft 365 E3 or the Microsoft Defender for Endpoint standalone license.
```suggestion
- Your subscription includes one of the following: Windows 10 Enterprise E5, Microsoft 365 E5, Microsoft 365 E5 Security, Microsoft 365 E3, or the Microsoft Defender for Endpoint standalone license. 
```

2022-03-31 09:13 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-31 09:30 UTC, JohanFreelancer9 approved these changes

2022-03-31 12:50 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2022-04-01 23:09 UTC, denisebmsft approved these changes
Thank you @msbemba

2022-04-01 23:09 UTC, merged