Update connect-to-microsoft-365-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #8167
Opened 2022-03-31 08:56 UTC by msbemba

Section was missing the import-module cmdlet

2022-03-31 08:56 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-31 08:56 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8116

2022-03-31 09:47 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/connect-to-microsoft-365-powershell.md
> +3.  Run this command to import the module
```suggestion
3.  Run this command to import the module:
```

2022-03-31 09:47 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-31 13:05 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-31 13:06 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-04-01 05:24 UTC, JohanFreelancer9 approved these changes

2022-04-06 19:38 UTC, merged