Update upgrade-to-different-plan.md
MicrosoftDocs/microsoft-365-docs pull request #8168
Opened 2022-03-31 09:10 UTC by msbemba

Made changes to the upgrade option as the navigation has changes

2022-03-31 09:10 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8123

2022-03-31 09:10 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-03-31 09:29 UTC, JohanFreelancer9 commented on microsoft-365/commerce/subscriptions/upgrade-to-different-plan.md
> +3. On the subscription details page, Under **Product details and upgrades**, Select **View upgrades recommended for your org**
```suggestion
3. On the subscription details page, under **Product details and upgrades**, select **View upgrades recommended for your org**.
```

2022-03-31 09:29 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-31 09:48 UTC, JohanFreelancer9 approved these changes

2022-03-31 13:08 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2022-04-22 13:06 UTC, yogkumgit commented
@cmcatee-MSFT Gentle reminder

2022-06-10 00:38 UTC, cmcatee-MSFT approved these changes

2022-06-10 00:39 UTC, merged