Update idle-session-timeout-web-apps.md
MicrosoftDocs/microsoft-365-docs pull request #8196
Opened 2022-04-04 10:52 UTC by msbemba

Made changes to the document as the Azure AD conditional access for different users and groups are not available for Office.com or any other admin centers. From my testing it is restricted to SP and EXO.

2022-04-04 10:52 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-04 10:52 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8132

2022-04-04 11:59 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/idle-session-timeout-web-apps.md
> +- Once you turn on idle session timeout, it applies to your entire organization and can't be scoped to specific users, organizational units, or groups. Use [Azure AD Conditional Access](/azure/active
```suggestion
- Once you turn on idle session timeout, it applies to your entire organization and can't be scoped to specific users, organizational units, or groups. Use [Azure AD Conditional Access](/azure/active-directory/conditional-access/) policies for different users and groups to access SharePoint and Exchange Online.
```

2022-04-04 12:00 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-04 12:07 UTC, JohanFreelancer9 approved these changes

2022-04-04 14:59 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-04-22 13:06 UTC, yogkumgit commented
@kwekuako Gentle reminder

2022-04-22 20:16 UTC, merged