Update ome-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #8209
Opened 2022-04-04 21:50 UTC by samschan-ms

updated that OME branding needs a mail sent from inside the cloud organization. @KCCross to review

2022-04-05 08:39 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          Yes, for mail sent from an Exchange Online mailbox in your organization! For information on customizing email messages and the OME portal, see Add your organization's brand to your encrypte
```suggestion
          Yes, for mail sent from an Exchange Online mailbox in your organization! For information on customizing email messages and the OME portal, see [Add your organization's brand to your encrypted messages](add-your-organization-brand-to-encrypted-messages.md).
```

2022-04-05 08:39 UTC, JohanFreelancer9 requested changes
Copy review - @samschan-ms, kindly commit the suggested change. Many thanks.

2022-04-06 02:17 UTC, JohanFreelancer9 approved these changes

2022-04-10 02:43 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-04-22 13:05 UTC, yogkumgit commented
@KCCross Gentle reminder

2022-06-09 22:34 UTC, merged