Update add-your-organization-brand-to-encrypted-messages.md
MicrosoftDocs/microsoft-365-docs pull request #8210
Opened 2022-04-04 23:14 UTC by samschan-ms

Added clarification the branding applies to mail sent from your organizaiton's online mailboxes. @KCCross  to review

2022-04-05 08:45 UTC, JohanFreelancer9 commented on microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md
> +Once you've created the templates, you can apply them to encrypted emails sent from by using Exchange mail flow rules. If you have Office 365 Advanced Message Encryption, you can revoke any email tha
```suggestion
Once you've created the templates, you can apply them to encrypted emails _sent from_ by using Exchange mail flow rules. If you have Office 365 Advanced Message Encryption, you can revoke any email that you've branded by using these templates.
```

2022-04-05 08:50 UTC, JohanFreelancer9 requested changes
Copy review - @samschan-ms, kindly commit the suggested change if you agree with it. Many thanks.

2022-04-06 02:28 UTC, JohanFreelancer9 approved these changes

2022-04-10 02:43 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-04-22 13:04 UTC, yogkumgit commented
@KCCross Gentle reminder

2022-10-14 20:24 UTC, KCCross commented
Added content through a PR in the private repo. Closing this PR as the changes were incorporated elsewhere.

2022-10-14 20:24 UTC, closed without merging

2022-10-14 20:30 UTC, KCCross commented
https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/17000