Split out DLP from MIP
MicrosoftDocs/microsoft-365-docs pull request #8225
Opened 2022-04-05 23:42 UTC by tiffanyyumsft

2022-04-09 10:18 UTC, JohanFreelancer9 commented on microsoft-365/compliance/compliance-easy-trials.md
> +  Data Loss Prevention helps you control sharing and use of sensitive info on devices, apps, and services. With trials, you can extend coverage of DLP polices to Teams and devices, protect even more
```suggestion
- **Data Loss Prevention** 
  Data Loss Prevention (DLP) helps you control sharing and use of sensitive info on devices, apps, and services. With trials, you can extend coverage of DLP policies to Teams and devices, protect even more sensitive content using trainable classifiers and exact data match (EDM), and get started quickly with our recommended DLP policies.  [Learn more about Data Loss Prevention](dlp-learn-about-dlp.md).
```

2022-04-09 10:23 UTC, JohanFreelancer9 requested changes
Copy review - @tiffanyyumsft, kindly commit the suggested changes. Many thanks.

2022-04-11 15:34 UTC, tiffanyyumsft commented
> Copy review - @tiffanyyumsft, kindly commit the suggested changes. Many thanks.

@JohanFreelancer9 Done

2022-04-12 05:12 UTC, JohanFreelancer9 approved these changes

2022-04-19 23:25 UTC, chrfox commented
adding @v-tophillips

2022-04-19 23:34 UTC, v-tophillips approved these changes

2022-04-19 23:52 UTC, v-tophillips reviewed
@tiffanyyumsft After looking at your changes, several places would replace the Purview branding and undo the rebranding changes. I propose canceling this PR and I will create another PR that includes your changes without the branding so that we don't undo work that is already done. Will that work for you?

2022-04-19 23:54 UTC, tiffanyyumsft commented
@v-tophillips Yes, Todd that works for me. Appreciate your help on this!

2022-04-20 00:11 UTC, closed without merging