Update the overview page
MicrosoftDocs/microsoft-365-docs pull request #8227
Opened 2022-04-06 00:09 UTC by seakim-ms

Added disclaimer for feedback collection

2022-04-09 10:27 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/servicenow-overview.md
> +> The Microsoft 365 support integration app will occasionally prompt users for feedback about the app. If you don’t want users to be prompted for feedback, turn off this functionality in the app sett
```suggestion
> The Microsoft 365 support integration app will occasionally prompt users for feedback about the app. If you don’t want users to be prompted for feedback, turn off this functionality in the app settings. For more information about Microsoft feedback policies, see [Learn about Microsoft feedback for your organization](/microsoft-365/admin/misc/feedback-user-control). To change the feedback settings, follow the steps in the installation process.
```

2022-04-09 10:28 UTC, JohanFreelancer9 requested changes
Copy review - @seakim-ms, kindly commit the suggested change to change to a relative link. Many thanks.

2022-04-22 13:04 UTC, yogkumgit commented
@seakim-ms Gentle reminder

2022-04-23 06:06 UTC, JohanFreelancer9 approved these changes

2022-08-16 10:51 UTC, yogkumgit commented
@seakim-ms Please implement the suggested changes, in the event of no response we may have to close this PR. Thanks

2022-08-16 16:55 UTC, opbld30 commented
Docs Build status updates of commit _[93dde39](https://github.com/seakim-ms/microsoft-365-docs/commits/93dde391676f4923eff5e18ecfa51621f8b3edd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/servicenow-overview.md](https://github.com/seakim-ms/microsoft-365-docs/blob/patch-12/microsoft-365/admin/manage/servicenow-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208161652295900-8227/BuildReport?accessString=8f4d0c398a31f28f560beea8de749e5c5e6d7db757a52655e0c4f712c7f62778).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 16:56 UTC, merged