Update network-and-migration-planning.md
MicrosoftDocs/microsoft-365-docs pull request #8255
Opened 2022-04-07 14:09 UTC by msbemba

Added Microsoft 365 network connectivity test tool to the list of tools to test network

2022-04-07 14:10 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-07 14:10 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8241

2022-04-08 03:46 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/network-and-migration-planning.md
> +- [Microsoft 365 network connectivity test tool](/microsoft-365/enterprise/office-365-network-mac-perf-onboarding-tool): Microsoft 365 network connectivity test tool.
```suggestion
- [Microsoft 365 network connectivity test tool](/microsoft-365/enterprise/office-365-network-mac-perf-onboarding-tool): Tests Microsoft 365 network connectivity.
```

2022-04-08 03:46 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-08 09:04 UTC, JohanFreelancer9 approved these changes

2022-04-10 02:47 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-04-22 13:02 UTC, yogkumgit commented
@kelleyvice-msft Gentle reminder

2022-04-26 14:40 UTC, merged