Update microsoft-defender-endpoint-android.md
MicrosoftDocs/microsoft-365-docs pull request #8341
Opened 2022-04-18 07:16 UTC by allenhsiaoMS

Add one line directly point out that intune license is needed before onboarding Android devices
Reason: Some customer get confused because we didn't directly mentioned that Intune license is a must

2022-04-19 05:24 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-android.md
> +  - Intune license is needed before onboarding Android Devices
```suggestion
  - Microsoft Defender for Endpoint license assigned to the end user(s) of the app. See [Microsoft Defender for Endpoint licensing requirements](/microsoft-365/security/defender-endpoint/minimum-requirements#licensing-requirements).
  - Intune license is needed before onboarding Android devices.
```

2022-04-19 05:25 UTC, JohanFreelancer9 requested changes
Copy review - @allenhsiaoMS, kindly commit the minor suggested changes. Many thanks.

2022-04-20 12:29 UTC, JohanFreelancer9 approved these changes

2022-04-21 07:23 UTC, allenhsiaoMS commented
Hi Team, when will the update present in public docs after approval? thankyou

2022-04-22 13:00 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-05-05 17:00 UTC, merged