Update information-barriers-policies.md
MicrosoftDocs/microsoft-365-docs pull request #8344
Opened 2022-04-18 15:00 UTC by Gautamkv

Hide from address list enabled set to false for users in same IB segment to join Teams meeting.

2022-04-19 05:37 UTC, JohanFreelancer9 commented on microsoft-365/compliance/information-barriers-policies.md
> +- **No address book policies**: Before you define and apply information barrier policies, make sure no Exchange address book policies are in place. Information barriers are based on address book poli
```suggestion
- **No address book policies**: Before you define and apply information barrier policies, make sure no Exchange address book policies are in place. Information barriers are based on address book policies, but the two kinds of policies are not compatible. If you do have such policies, make sure to [remove your address book policies](/exchange/address-books/address-book-policies/remove-an-address-book-policy) first. Once information barrier policies are enabled and you have hierarchical address book enabled, all users ***who are not included*** in an information barrier segment will see the [hierarchical address book](/exchange/address-books/hierarchical-address-books/hierarchical-address-books) in Exchange online. Additionally, ensure that the user is visible in the address list with the **HiddenFromAddressListsEnabled** property set to $False.
```

2022-04-19 05:37 UTC, JohanFreelancer9 requested changes
Copy review - @Gautamkv, kindly commit the suggested changes. Many thanks.

2022-04-22 12:59 UTC, yogkumgit commented
@Gautamkv Gentle reminder

2022-04-27 15:23 UTC, JohanFreelancer9 approved these changes

2022-04-27 16:53 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2022-12-20 17:13 UTC, robmazz commented
@Gautamkv - thanks for the feedback. This topic is undergoing changes for the newer version of IB, I will discuss this the PG and confirm that this addition is still accurate. Thanks again.

2022-12-20 17:13 UTC, closed without merging