Update remove-former-employee-step-5.md
MicrosoftDocs/microsoft-365-docs pull request #8404
Opened 2022-04-25 06:35 UTC by msbemba

Added information about onedrive URL

2022-04-25 06:35 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8376

2022-04-25 06:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-25 09:46 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/remove-former-employee-step-5.md
> +10. The user will now be able to access the former employee's OneDrive using the OneDrive URL. For more information, See [About OneDrive URLs](/onedrive/list-onedrive-urls#about-onedrive-urls)
```suggestion
10. The user will now be able to access the former employee's OneDrive using the OneDrive URL. For more information, see [About OneDrive URLs](/onedrive/list-onedrive-urls#about-onedrive-urls).
```

2022-04-25 09:47 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-26 05:02 UTC, JohanFreelancer9 approved these changes

2022-04-26 08:17 UTC, yogkumgit commented
@kwekuako Please merge this PR. thanks

2022-04-26 22:33 UTC, merged