Batch 2: SEO H1 headings
MicrosoftDocs/microsoft-365-docs pull request #8408
Opened 2022-04-25 13:39 UTC by lhcole613

FREELANCERS: Please do NOT merge as per @pebaum.

2022-04-25 22:47 UTC, SKjerland commented on microsoft-365/admin/misc/device-list.md
> +# Windows Autopilot device list CSV-file
@lhcole613 - Shouldn't we include the product name for SEO? "Windows Autopilot device list CSV-file in Microsoft 365 for business"

2022-04-25 22:48 UTC, SKjerland commented on microsoft-365/admin/misc/icann-verification-of-contact-information.md
> +# ICANN verification of contact information
@lhcole613 - Same comment as above about adding product name. Should this be "ICANN verification of contact information in Microsoft 365 for business" or whichever product this is in (I'm not sure from this context)?

2022-04-25 22:50 UTC, SKjerland commented on microsoft-365/admin/misc/power-bi-in-your-organization.md
> +# Using Power BI data in your organization
@lhcole613 - For SEO, shouldn't the product name be mentioned in this H1?

2022-04-25 22:51 UTC, SKjerland commented on microsoft-365/admin/productivity/communication.md
> +# Communication insights score– People experiences
@lhcole613 - Add product name to H1 for SEO?

2022-04-25 22:51 UTC, SKjerland commented on microsoft-365/admin/productivity/meetings.md
> +# Meetings insights score – People experiences
@lhcole613 - Add product name to H1 for SEO?

2022-04-25 22:52 UTC, SKjerland commented on microsoft-365/admin/productivity/mobility.md
> +# Mobility insights score – People experiences
@lhcole613 - Add product name to H1 for SEO?

2022-04-25 22:57 UTC, SKjerland commented on microsoft-365/admin/misc/power-bi-in-your-organization.md
> +# Using Power BI data in your organization
@lhcole613 - I think you'll get dinged by a PubOps reviewer if you use a gerund in the heading, unless they changed this rule. They forced me to change a gerund once. Maybe change to "Overview of Power BI in your organization" if it's an issue.

2022-04-25 23:01 UTC, SKjerland commented on microsoft-365/business-premium/m365-campaigns-users.md
>  ---
@lhcole613 - Can you please change "affects" to "affect" and "protects" to "protect" in the metadata description? Thanks!

2022-04-25 23:02 UTC, SKjerland requested changes
@lhcole613 - Please see my individual comments inline. Thanks!

2022-05-12 08:02 UTC, officedocspr2 commented
## ![STOP](https://docs.microsoft.com/en-us/office/media/internal/prfilecountcheck-stop-sign.png)  Caution: Large pull request

This **public** repo applies limits on the number of files that can be merged in a single pull request (PR):

- **Warning** Warning message and ability to unblock PR using the *Merge large pull request*<sup>\*</sup> label - 30
- **Block** Block message and PR is blocked - 100

This pull request will change **32** files, which exceeds the **warning** limit of **32**.

Before this pull request can be merged, you must review the list of files it contains and their changes to confirm they are correct and intentional. **This includes files you did not change and/or do not own**. If there are changes you aren't familiar with, contact the individuals who submitted the commits included in this pull request and review the changes with them.

**The individual who merges this pull request is responsible for ensuring the changes included in it are correct, and for resolving any issues that might result in merging it.**

### To merge this pull request

If you have determined that the changes in this pull request are correct, add the **Merge large pull request**<sup>\*</sup> label to it, wait for the **max/pr-file-count** check to pass, and then click **Merge**. To add a label, click the gear icon next to **Labels** and then select **Merge large pull request**<sup>\*</sup>.

![Label UI screenshot](https://docs.microsoft.com/en-us/office/media/internal/prfilecountcheck-label-screenshot.gif)

### To reject this pull request

If you can't confirm the changes in this pull request are correct, click **Close pull request** at the bottom of this page to close it without merging. Work with your team to revert any changes that aren't correct.

<sup>\*</sup> You must have write or triage access to this repo to add labels.

2022-05-17 17:45 UTC, merged