Update data-classification-overview.md
MicrosoftDocs/microsoft-365-docs pull request #8415
Opened 2022-04-26 03:41 UTC by sudeepghatak

2022-04-26 04:11 UTC, JohanFreelancer9 commented on microsoft-365/compliance/data-classification-overview.md
> +As a Microsoft 365 administrator or compliance administrator, you can evaluate and then tag content in your organization in order to control where it goes, protect it no matter where it is and to ens
```suggestion
As a Microsoft 365 administrator or compliance administrator, you can evaluate and then tag content in your organization in order to control where it goes, protect it no matter where it is, and ensure that it is preserved and deleted according to your organization's needs. You do this through the application of [sensitivity labels](sensitivity-labels.md), [retention labels](retention.md#retention-labels), and sensitive information type classification. There are various ways to do the discovery, evaluation, and tagging, but the end result is that you may have a very large number of documents and emails that are tagged and classified with one or both of these labels. After you apply your retention labels and sensitivity labels, you'll want to see how the labels are being used across your tenant and what is being done with those items. The data classification page provides visibility into that body of content, specifically:
```

2022-04-26 04:18 UTC, JohanFreelancer9 requested changes
Copy review - @sudeepghatak, kindly also commit the additional suggested changes. Many thanks.

2022-05-24 06:39 UTC, yogkumgit commented
@sudeepghatak Gentle reminder.

2022-05-25 06:08 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-25 06:08 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-05-25 13:28 UTC, JohanFreelancer9 approved these changes

2022-07-20 18:36 UTC, merged