Update connect-to-microsoft-365-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #8446
Opened 2022-04-28 16:37 UTC by msbemba

Added a section for connecting to Microsoft Graph powershell as powershell graph SDK is going to replace AzureAD module  in the future.

2022-04-28 16:37 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8299

2022-04-28 16:37 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-04-29 04:28 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/connect-to-microsoft-365-powershell.md
> +You can use Microsoft Graph PowerShell SDK to Access to all Microsoft Graph APIs.
```suggestion
You can use the Microsoft Graph PowerShell SDK to Access all Microsoft Graph APIs.
```

2022-04-29 04:29 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-29 05:40 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/connect-to-microsoft-365-powershell.md
> +You can use the Microsoft Graph PowerShell SDK to Access all Microsoft Graph APIs.
```suggestion
You can use the Microsoft Graph PowerShell SDK to access all Microsoft Graph APIs.
```

2022-04-29 05:41 UTC, JohanFreelancer9 requested changes
Apoplogies @msbemba, one more, please.

2022-04-29 05:47 UTC, JohanFreelancer9 approved these changes

2022-04-29 10:11 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-05-02 16:27 UTC, merged