Update connect-to-microsoft-365-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #8500
Opened 2022-05-05 19:14 UTC by msbemba

moved the sdk line to to a note at the top of the article.

2022-05-05 19:15 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-05 19:15 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8299

2022-05-06 09:58 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/connect-to-microsoft-365-powershell.md
> +
```suggestion
>[!NOTE]
> The AzureAD module is being replaced by the Microsoft Graph PowerShell SDK.
> 
> You can use the Microsoft Graph PowerShell SDK to access all Microsoft Graph APIs. For more information, see [Get started with the Microsoft Graph PowerShell SDK](/powershell/microsoftgraph/get-started).
```

2022-05-06 10:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-06 14:14 UTC, JohanFreelancer9 approved these changes

2022-05-20 21:26 UTC, merged