Update documentation of KQL query search and conditions
MicrosoftDocs/microsoft-365-docs pull request #8511
Opened 2022-05-06 17:35 UTC by CoreySchneider-MSFT

Added link to "recipient expansion" section for relevant fields.

2022-05-07 08:08 UTC, JohanFreelancer9 commented on microsoft-365/compliance/keyword-queries-and-search-conditions.md
> +|Bcc|The Bcc field of an email message.<sup>1</sup>|`bcc:pilarp@contoso.com` <p> `bcc:pilarp` <p> `bcc:"Pilar Pinilla"`|All examples return messages with Pilar Pinilla included in the Bcc field.<br>(
```suggestion
|Bcc|The Bcc field of an email message.<sup>1</sup>|`bcc:pilarp@contoso.com` <p> `bcc:pilarp` <p> `bcc:"Pilar Pinilla"`|All examples return messages with Pilar Pinilla included in the Bcc field.<br>See [Recipient expansion](recipient-expansion.md).|
```

2022-05-07 08:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/keyword-queries-and-search-conditions.md
> +|Cc|The Cc field of an email message.<sup>1</sup>|`cc:pilarp@contoso.com` <p> `cc:"Pilar Pinilla"`|In both examples, messages with Pilar Pinilla specified in the Cc field.<br>([See Recipient Expansio
```suggestion
|Cc|The Cc field of an email message.<sup>1</sup>|`cc:pilarp@contoso.com` <p> `cc:"Pilar Pinilla"`|In both examples, messages with Pilar Pinilla specified in the Cc field.<br>See [Recipient expansion](recipient-expansion.md).|
```

2022-05-07 08:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/keyword-queries-and-search-conditions.md
> +|From|The sender of an email message.<sup>1</sup>|`from:pilarp@contoso.com` <p> `from:contoso.com`|Messages sent by the specified user or sent from a specified domain.<br>([See Recipient Expansion](h
```suggestion
|From|The sender of an email message.<sup>1</sup>|`from:pilarp@contoso.com` <p> `from:contoso.com`|Messages sent by the specified user or sent from a specified domain.<br>See [Recipient expansion](recipient-expansion.md).|
```

2022-05-07 08:10 UTC, JohanFreelancer9 commented on microsoft-365/compliance/keyword-queries-and-search-conditions.md
> +|Participants|All the people fields in an email message. These fields are From, To, Cc, and Bcc.<sup>1</sup>|`participants:garthf@contoso.com` <p> `participants:contoso.com`|Messages sent by or sent
```suggestion
|Participants|All the people fields in an email message. These fields are From, To, Cc, and Bcc.<sup>1</sup>|`participants:garthf@contoso.com` <p> `participants:contoso.com`|Messages sent by or sent to garthf@contoso.com. The second example returns all messages sent by or sent to a user in the contoso.com domain.<br>See [Recipient expansion](recipient-expansion.md).|
```

2022-05-07 08:11 UTC, JohanFreelancer9 commented on microsoft-365/compliance/keyword-queries-and-search-conditions.md
> +|Recipients|All recipient fields in an email message. These fields are To, Cc, and Bcc.<sup>1</sup>|`recipients:garthf@contoso.com` <p> `recipients:contoso.com`|Messages sent to garthf@contoso.com. T
```suggestion
|Recipients|All recipient fields in an email message. These fields are To, Cc, and Bcc.<sup>1</sup>|`recipients:garthf@contoso.com` <p> `recipients:contoso.com`|Messages sent to garthf@contoso.com. The second example returns messages sent to any recipient in the contoso.com domain.<br>See [Recipient expansion](recipient-expansion.md).|
```

2022-05-07 08:12 UTC, JohanFreelancer9 commented on microsoft-365/compliance/keyword-queries-and-search-conditions.md
> +|Sender/Author|For email, the person who sent a message. For documents, the person cited in the author field from Office documents. You can type more than one name, separated by commas. Two or more v
```suggestion
|Sender/Author|For email, the person who sent a message. For documents, the person cited in the author field from Office documents. You can type more than one name, separated by commas. Two or more values are logically connected by the **OR** operator.<br>See [Recipient expansion](recipient-expansion.md).|
```

2022-05-07 08:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/keyword-queries-and-search-conditions.md
> +|Participants|All the people fields in an email message. These fields are From, To, Cc, and Bcc. ([See Recipient Expansion](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-a
```suggestion
|Participants|All the people fields in an email message. These fields are From, To, Cc, and Bcc. See [Recipient expansion](recipient-expansion.md).|
```

2022-05-07 08:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/keyword-queries-and-search-conditions.md
> +|Recipients|All recipient fields in an email message. These fields are To, Cc, and Bcc. ([See Recipient Expansion](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search
```suggestion
|Recipients|All recipient fields in an email message. These fields are To, Cc, and Bcc. See [Recipient expansion](recipient-expansion.md).|
```

2022-05-07 08:22 UTC, JohanFreelancer9 requested changes
Copy review - @CoreySchneider-MSFT, kindly commit the suggested changes. Many thanks.

2022-05-07 16:30 UTC, jamesreedMSFT approved these changes
These changes look good.

2022-05-09 22:37 UTC, v-tophillips approved these changes

2022-05-09 22:37 UTC, merged