Update ome-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #8527
Opened 2022-05-09 06:25 UTC by msbemba

Added clarification that only encrypted messages sent internally to a shared mailbox will be viewable on the outlook client.  The delegates receiving it from external sources should open it via outlook on the web

2022-05-09 06:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8455

2022-05-09 06:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-09 08:37 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          Yes! You can open encrypted messages for a shared mailbox which sent internally within the same tenant, when you're logged into a supported Outlook client. Delegates to a shared mailbox get
```suggestion
          Yes! You can open encrypted messages for a shared mailbox which sent internally within the same tenant when you're logged into a supported Outlook client. Delegates to a shared mailbox getting encrypted messages sent from an external organization should use Outlook on the web to sign in as the shared mailbox to read these messages.
```

2022-05-09 08:37 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-09 10:19 UTC, JohanFreelancer9 approved these changes

2022-05-09 11:37 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-07-11 06:17 UTC, yogkumgit commented
@KCCross Gentle reminder. Thanks

2022-07-11 11:01 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          Yes! You can open encrypted messages for a shared mailbox which sent internally within the same tenant when you're logged into a supported Outlook client. Delegates to a shared mailbox gett
```suggestion
          Yes! You can open encrypted messages for a shared mailbox which sent internally within the same tenant when you're logged into a supported Outlook client. Delegates to a shared mailbox getting encrypted messages sent from an external organization should use Outlook on the web to sign in as the shared mailbox to read these messages.
```

2022-10-14 21:06 UTC, KCCross commented
Completed this work on the internal repo.

2022-10-14 21:06 UTC, closed without merging