Fixes #8501 change inline code blocks
MicrosoftDocs/microsoft-365-docs pull request #8545
Opened 2022-05-10 13:06 UTC by chadmando

Change inline code blocks to PowerShell language-specific code blocks

2022-05-10 14:17 UTC, alosaimii requested changes
I'm so sorry bro but why ?

2022-05-10 14:44 UTC, chadmando commented
@alosaimii Top three reasons would be:
* Easier copy / paste functionality with language blocks
* Provides syntax highlighting for better readability
* Creates consistency in the document since all other code block and language specific

2022-05-10 15:58 UTC, alosaimii approved these changes

2022-05-10 15:59 UTC, alosaimii approved these changes

2022-05-11 08:24 UTC, JohanFreelancer9 approved these changes

2022-05-16 18:45 UTC, chadmando commented
Closed as duplicate

2022-05-16 18:45 UTC, closed without merging