Update managing-holds.md
MicrosoftDocs/microsoft-365-docs pull request #8554
Opened 2022-05-10 20:59 UTC by StefanieBier

2022-05-11 09:06 UTC, JohanFreelancer9 commented on microsoft-365/compliance/managing-holds.md
> +> When you create a query-based hold, all content from selected locations is initially placed on hold. Once the timer job in either Exchange or SharePoint runs, any content that doesn't match the spe
```suggestion
> When you create a query-based hold, all content from selected locations is initially placed on hold. Once the timer job in either Exchange or SharePoint runs, any content that doesn't match the specified query is cleared from the hold. Once the character count across all queries on a single location exceeds 10,000 characters, the entire location is placed on hold. 
```

2022-05-11 09:12 UTC, JohanFreelancer9 requested changes
Copy review. @StefanieBier, kindly commit the suggested change. Many thanks.

2022-05-17 05:32 UTC, yogkumgit commented
@StefanieBier Gentle reminder, please implement the suggested changes, thanks.

2022-06-28 13:23 UTC, yogkumgit commented
@tiburd Please help. Thanks

2022-06-28 17:06 UTC, tiburd commented on microsoft-365/compliance/managing-holds.md
> +> When you create a query-based hold, all content from selected locations is initially placed on hold. Once the timer job in either Exchange or SharePoint runs, any content that doesn't match the spe
```suggestion
> When you create a query-based hold, all content from selected locations is initially placed on hold. Once the timer job in either Exchange or SharePoint runs, any content that doesn't match the specified query is cleared from the hold. After the character count across all queries on a single location exceeds 10,000 characters, the entire location is placed on hold. 
```

2022-06-28 17:08 UTC, tiburd commented on microsoft-365/compliance/managing-holds.md
> +> When you create a query-based hold, all content from selected locations is initially placed on hold. Once the timer job in either Exchange or SharePoint runs, any content that doesn't match the spe
```suggestion
> When you create a query-based hold, all content from selected locations is initially placed on hold. After the timer job in either Exchange or SharePoint runs, any content that doesn't match the specified query is cleared from the hold. After the character count across all queries on a single location exceeds 10,000 characters, the entire location is placed on hold. 
```

2022-06-28 17:09 UTC, merged