Suggesting missing step
MicrosoftDocs/microsoft-365-docs pull request #8574
Opened 2022-05-11 16:31 UTC by jorlopama

Added missing step on the section to add a new onmicrosoft.com domain  (Step 2) - it was confusing for a couple of customers since it doesn't say that after step 1 ,  customers should select their current onmicrosoft.com domain in order to have the  option suggested in the next step .

2022-05-11 16:49 UTC, jorlopama reviewed
Submit review

2022-05-12 06:45 UTC, JohanFreelancer9 commented on microsoft-365/admin/setup/add-domain.md
> +2. On the **Domains** page, select your current ***.onmicrosoft.com(Default)** domain.
```suggestion
2. On the **Domains** page, select your current ***.onmicrosoft.com (Default)** domain.
```

2022-05-12 06:48 UTC, JohanFreelancer9 requested changes
Copy review - @jorlopama, kindly commit the suggested change. Many thanks.

2022-05-13 08:27 UTC, JohanFreelancer9 approved these changes

2022-05-17 05:39 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2022-06-28 13:22 UTC, yogkumgit commented
@efrene Gentle reminder. Thanks

2022-06-28 16:12 UTC, merged