Update recommended-settings-for-eop-and-office365-atp.md
MicrosoftDocs/microsoft-365-docs pull request #858
Opened 2019-11-28 00:16 UTC by andypunt

Add tip to make sure Junk Email Rule is enabled.

2019-11-30 06:06 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-11-30 07:58 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md
> +> The Junk Email Configuration has to be enabled on the mailbox in order for filtering to work properly. This is enabled by default, but should be checked if filtering does not seem to be working. [R
```suggestion
> The Junk Email Configuration has to be enabled on the mailbox in order for filtering to work properly. This is enabled by default, but should be checked if filtering does not seem to be working. Read [Set-MailboxJunkEmailConfiguration](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/set-mailboxjunkemailconfiguration) to find out more. 
```

2019-11-30 07:59 UTC, JohanFreelancer9 requested changes
Copy Review

2019-11-30 08:16 UTC, mypil commented
@andypunt - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-12-06 16:29 UTC, mypil commented
@MSFTTracyP - PR has been copy edited and is ready for final review.  


Thank you.

cc: @kenwith

2019-12-07 00:48 UTC, merged