added note about digitally sighned PDF
MicrosoftDocs/microsoft-365-docs pull request #859
Opened 2019-11-28 04:03 UTC by MaratMussabekov

#738

2019-11-30 06:07 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-12-17 01:47 UTC, JohanFreelancer9 commented on microsoft-365/compliance/set-up-irm-in-sp-admin-center.md
> +> IRM protection cannot be applied to the protected documents (like digitally signed PDF files) as SharePoint needs to open the document on upload.
```suggestion
> IRM protection cannot be applied to protected documents (like digitally signed PDF files) as SharePoint needs to open the document on upload. 
```

2019-12-17 01:48 UTC, JohanFreelancer9 requested changes
Copy Review - minor edit.

2019-12-17 02:08 UTC, mypil commented
@MaratMussabekov - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-12-24 15:17 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review. This is based on issue #738

Thank you.

cc: @kenwith

2020-01-08 15:20 UTC, mypil commented
@KCCross - We would like to follow up. Any updates on this?

Thank you.

2020-01-23 20:08 UTC, KCCross commented
We've just onboarded a new PM in this space and I'm working on getting confirmation about this. The underlying issue has to do with encryption support for PDF in a similar technology that uses IRM. Apologies for the hold-up. This IS on my radar.

2020-02-14 22:38 UTC, KCCross commented
Kaarin, requesting assistance on finalizing information for SharePoint and PDF

2020-03-11 21:53 UTC, merged