Update bookings-in-outlook.md
MicrosoftDocs/microsoft-365-docs pull request #8596
Opened 2022-05-13 21:23 UTC by Smartboss88

Clarify licensing requirement for Bookings for Outlook.

2022-05-14 06:58 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-in-outlook.md
> +Bookings in Outlook needs service plan “Microsoft Bookings” assigned to users to be able to access Bookings. This service plan can be enabled/disabled by tenant admins. So, if the service “Microsoft
```suggestion
Bookings in Outlook needs the **Microsoft Bookings** service plan assigned to users for them to be able to access Bookings. This service plan can be enabled/disabled by tenant admins. So, if **Microsoft Bookings** is not assigned to them, Bookings access will be denied to users even if they are in one of the previously listed SKUs.
```

2022-05-14 06:59 UTC, JohanFreelancer9 requested changes
Copy review - @Smartboss88, kindly commit the suggested changes. Many thanks.

2022-05-15 15:31 UTC, JohanFreelancer9 approved these changes

2022-05-17 05:43 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-05-17 23:46 UTC, merged