Update integrate-microsoft-365-defender-secops-services.md
MicrosoftDocs/microsoft-365-docs pull request #8600
Opened 2022-05-14 15:27 UTC by Angelines-YG

Fixed broken link for "what is Defender for Office 365"

2022-05-15 03:35 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/integrate-microsoft-365-defender-secops-services.md
> +- [What is Defender for Office 365?](/microsoft-365/security/defender/microsoft-365-defender?view=o365-worldwide)
```suggestion
- [What is Defender for Office 365?](/microsoft-365/security/defender/microsoft-365-defender)
```

2022-05-15 03:37 UTC, JohanFreelancer9 requested changes
Copy review - @Angelines-YG, kindly commit the suggested change. Many thanks.

2022-05-16 14:17 UTC, Angelines-YG commented
@JohanFreelancer9  

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

2022-05-16 15:40 UTC, JohanFreelancer9 approved these changes

2022-05-16 16:32 UTC, denisebmsft approved these changes
Thank you @Angelines-YG

2022-05-16 16:33 UTC, merged