Updated broken link
MicrosoftDocs/microsoft-365-docs pull request #8601
Opened 2022-05-14 16:27 UTC by Angelines-YG

Fixed broken link for: Microsoft 365 Device Inventory 
Replaced with: /microsoft-365/security/defender-endpoint/device-discovery?view=o365-worldwide

2022-05-15 03:43 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/integrate-microsoft-365-defender-secops-use-cases.md
> +|SOC Oversight|All assets connected to approved networks are identified and categorized|SOC Oversight, BU owners, application owners, IT asset owners, etc.|Centralized asset management system to disc
```suggestion
|SOC Oversight|All assets connected to approved networks are identified and categorized|SOC Oversight, BU owners, application owners, IT asset owners, etc.|Centralized asset management system to discover and list asset category and attributes based on risk.|ServiceNow or other assets. <br><br>[Microsoft 365 Device Inventory](/microsoft-365/security/defender-endpoint/device-discovery)|Only 70% of assets have been discovered. Microsoft 365 Defender remediation tracking only effective for known assets|Mature asset lifecycle management services to ensure Microsoft 365 Defender has 100% coverage|N|
```

2022-05-15 03:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/integrate-microsoft-365-defender-secops-use-cases.md
> +|SOC Oversight|All assets connected to approved networks are identified and categorized|SOC Oversight, BU owners, application owners, IT asset owners, etc.|Centralized asset management system to disc
```suggestion
|SOC Oversight|All assets connected to approved networks are identified and categorized|SOC Oversight, BU owners, application owners, IT asset owners, etc.|Centralized asset management system to discover and list asset category and attributes based on risk.|ServiceNow or other assets. <br><br>[Microsoft 365 Device Inventory](/microsoft-365/security/defender-endpoint/device-discovery)|Only 70% of assets have been discovered. Microsoft 365 Defender remediation tracking only effective for known assets|Mature asset lifecycle management services to ensure Microsoft 365 Defender has 100% coverage|N|
```

2022-05-15 03:46 UTC, JohanFreelancer9 requested changes
Copy review - @Angelines-YG, kindly commit the suggested change. Many thanks.

2022-05-16 14:12 UTC, Angelines-YG commented
@JohanFreelancer9, @officedocspr2

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

2022-05-16 14:16 UTC, Angelines-YG commented
@JohanFreelancer9 

Suggested change has been committed. Please let me know if there is anything that needs to be changed. 
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

2022-05-16 15:27 UTC, JohanFreelancer9 approved these changes
Thank you @Angelines-YG.

2022-05-16 16:34 UTC, denisebmsft approved these changes
Thank you @Angelines-YG @JohanFreelancer9

2022-05-16 16:34 UTC, merged