Broken Links: Update customer-key-manage.md
MicrosoftDocs/microsoft-365-docs pull request #8602
Opened 2022-05-14 18:31 UTC by kturetz

Corrected broken link on Line 103.

2022-05-15 03:57 UTC, JohanFreelancer9 requested changes
Copy review - @kturetz, kindly commit the suggested change. Many thanks.

2022-05-15 03:57 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-manage.md
> +For detailed syntax and parameter information, see [New-DataEncryptionPolicy](/powershell/module/exchange/new-dataencryptionpolicy?view=exchange-ps).
```suggestion
For detailed syntax and parameter information, see [New-DataEncryptionPolicy](/powershell/module/exchange/new-dataencryptionpolicy).
```

2022-05-16 04:21 UTC, JohanFreelancer9 approved these changes

2022-05-17 15:55 UTC, kturetz commented
*Global effort to fix broken links** 

@krowley 

 The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

2022-05-18 05:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/customer-key-manage.md
> +For detailed syntax and parameter information, see [New-DataEncryptionPolicy](/powershell/module/exchange/new-dataencryptionpolicy).
```suggestion
For detailed syntax and parameter information, see [New-DataEncryptionPolicy](/powershell/module/exchange/new-dataencryptionpolicy).
```

2022-05-18 05:30 UTC, JohanFreelancer9 approved these changes

2022-05-24 07:02 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-24 15:39 UTC, merged