Broken Links: Corrected Azure pricing link
MicrosoftDocs/microsoft-365-docs pull request #8604
Opened 2022-05-14 21:07 UTC by kturetz

Fixed broken link on Line 23.

2022-05-15 04:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/double-key-encryption.md
> +> *Applies to: Microsoft Purview Double Key Encryption, [Microsoft Purview](https://www.microsoft.com/microsoft-365/business/compliance-management), [Azure Information Protection](https://azure.micro
```suggestion
> *Applies to: Microsoft Purview Double Key Encryption, [Microsoft Purview](https://www.microsoft.com/microsoft-365/business/compliance-management), [Azure Information Protection](https://azure.microsoft.com/pricing/)*
```

2022-05-15 04:28 UTC, JohanFreelancer9 requested changes
Copy review - @kturetz, kindly commit the suggested change to remove the locale from the link. Many thanks.

2022-05-16 04:25 UTC, JohanFreelancer9 approved these changes

2022-05-17 16:14 UTC, kturetz commented
**Global effort to fix broken links** 

@krowley

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

2022-05-18 06:09 UTC, JohanFreelancer9 approved these changes

2022-05-24 07:00 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-24 15:35 UTC, merged