Update set-password-expiration-policy.md
MicrosoftDocs/microsoft-365-docs pull request #8611
Opened 2022-05-16 08:23 UTC by msbemba

made changes to the password expiration policy section.

2022-05-16 08:23 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8585

2022-05-16 08:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-16 09:46 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/set-password-expiration-policy.md
>      If you aren't a global admin or security admin, you won't see the Security and privacy option.
```suggestion
    If you aren't a global admin or security admin, you won't see the Security & privacy option.
```

2022-05-16 09:54 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/set-password-expiration-policy.md
> +1. In the Microsoft 365 admin center, go to the <a href="https://go.microsoft.com/fwlink/p/?linkid=2072756" target="_blank">**Security & privacy** tab</a> .
```suggestion
1. In the Microsoft 365 admin center, go to the <a href="https://go.microsoft.com/fwlink/p/?linkid=2072756" target="_blank">**Security & privacy** tab</a>.
```

2022-05-16 09:55 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/set-password-expiration-policy.md
>      If you aren't a global admin or security admin, you won't see the Security and privacy option.
```suggestion
    If you aren't a global admin or security admin, you won't see the Security & privacy option.
```

2022-05-16 09:55 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-16 13:28 UTC, JohanFreelancer9 approved these changes

2022-05-17 03:16 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-05-17 23:48 UTC, merged