Update use-notifications-and-policy-tips.md
MicrosoftDocs/microsoft-365-docs pull request #8613
Opened 2022-05-16 14:17 UTC by ybhargav1995

2022-05-17 05:45 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-17 13:09 UTC, JohanFreelancer9 commented on microsoft-365/compliance/use-notifications-and-policy-tips.md
> +> Email notifications can be sent only to individual recipients—not groups or distribution lists. Only new content will trigger an email notification. Editing existing content will trigger policy tip
```suggestion
> Email notifications can be sent only to individual recipients—not groups or distribution lists. Only new content will trigger an email notification. Editing existing content will trigger policy tips, but not an email notification. If an email is sent from a user external to the organization that has set the rule, they will not receive any notification as these notifications only go to internal users.
```

2022-05-17 13:10 UTC, JohanFreelancer9 requested changes
Copy review - @ybhargav1995, kindly commit the suggested changes. Many thanks.

2022-05-24 04:52 UTC, ybhargav1995 commented
@chrfox @JohanFreelancer9 can you please merge this

2022-05-24 10:49 UTC, JohanFreelancer9 approved these changes

2022-05-24 16:47 UTC, merged