Update information-barriers-policies.md
MicrosoftDocs/microsoft-365-docs pull request #8617
Opened 2022-05-16 16:33 UTC by DamienPascua

Description of "Visibility of non-IB users and groups" has been corrected. If the difference between allow and block policies is a future release, please specify this as the previous explanation is not in current circulation of IB policies.
Trying to hyperlink "SharePoint Mode" to https://docs.microsoft.com/en-us/sharepoint/information-barriers#information-barriers-modes-and-sharepoint-sites
and hyperlink "OneDrive Mode" to https://docs.microsoft.com/en-us/onedrive/information-barriers#information-barriers-modes-and-onedrive

2022-05-17 05:46 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-17 13:30 UTC, JohanFreelancer9 commented on microsoft-365/compliance/information-barriers-policies.md
> +- **Visibility of non-IB users and groups**. Non-IB users and groups are users and groups excluded from IB segments and policies. Non-IB groups and users will be visible to Search in Teams and your g
```suggestion
- **Visibility of non-IB users and groups**. Non-IB users and groups are users and groups excluded from IB segments and policies. Non-IB groups and users will be visible to search in Teams and your global address list. SharePoint and OneDrive may allow search of non-IB groups and users depending on the [SharePoint Mode](/SharePoint/SharePointOnline/information-barriers#information-barriers-modes-and-sharepoint-sites) or [OneDrive Mode](/OneDrive/information-barriers#information-barriers-modes-and-onedrive).  
```

2022-05-17 13:31 UTC, JohanFreelancer9 requested changes
Copy review - @DamienPascua, kindly commit the suggested changes. Many thanks.

2022-05-18 05:53 UTC, JohanFreelancer9 approved these changes

2022-05-19 03:39 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2022-12-20 17:16 UTC, robmazz commented
@DamienPascua - thanks for the feedback. This topic is undergoing changes for the newer version of IB, I will discuss this the PG and confirm that this addition is still accurate. Thanks again.

2022-12-20 17:16 UTC, closed without merging