Update information-barriers-policies.md
MicrosoftDocs/microsoft-365-docs pull request #8619
Opened 2022-05-16 17:01 UTC by DamienPascua

Example starting at line 419 creates a policy mismatch error.
Either 
Manufacturing can talk to everyone and only Sales and Research block each other 
OR 
Manufacturing can only talk to HR and Marketing, blocking Sales and Research.
Have proposed here how to make a blend of both as this is a frequently requested scenario within Support.

Three additional changes proposed:
-Expanding "Everyone" in HR and Marketing and "Anyone other than HR or Marketing" in Manufacturing would help clear up this understanding and reflect how a policy is made in UI or PowerShell.
-Using a naming convention like "Sales_Policy" to match the assigned segment allows for changes in the policy, such as including Manufacturing to correct the example, to make sense since policy names cannot change without first deleting the entire policy and recreating from scratch.
-Identify why HR and Marketing do not need policies.

2022-05-16 17:01 UTC, ghost commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/MicrosoftDocs/microsoft-365-docs?pullRequest=8619) <br/>All CLA requirements met.

2022-05-17 05:46 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-18 04:22 UTC, JohanFreelancer9 commented on microsoft-365/compliance/information-barriers-policies.md
> +For this scenario, it's not necessary to define IB policies for *HR* or *Marketing* as IB policies without a defined policy has an implied allow all communication with all other segments.
```suggestion
For this scenario, it's not necessary to define IB policies for *HR* or *Marketing* as IB policies without a defined policy have an implied allow all communication with all other segments.
```

2022-05-18 04:26 UTC, JohanFreelancer9 commented on microsoft-365/compliance/information-barriers-policies.md
> +| **Policy 3: Allow Manufacturing to communicate with HR and Marketing only** | `New-InformationBarrierPolicy -Name "Manufacturing_Policy" -AssignedSegment "Manufacturing" -SegmentsAllowed "HR","Sale
```suggestion
| **Policy 3: Allow Manufacturing to communicate with HR and Marketing only** | `New-InformationBarrierPolicy -Name "Manufacturing_Policy" -AssignedSegment "Manufacturing" -SegmentsAllowed "HR","Sales","Marketing","Manufacturing" -State Inactive` <p> In this case, the IB policy is called *Manufacturing_Policy*. When this policy is active and applied, Manufacturing can communicate only with HR, Sales, and Marketing. Allow and Block policies can be mixed in this way as long as symmetry is met, as outlined in the previous table. |
```

2022-05-18 04:31 UTC, JohanFreelancer9 requested changes
Copy review - @DamienPascua, kindly commit the minor suggested changes. Many thanks.

2022-05-19 06:06 UTC, JohanFreelancer9 commented on microsoft-365/compliance/information-barriers-policies.md
> +For this scenario, it's not necessary to define IB policies for *HR* or *Marketing* as IB policies without a defined policy has an implied allow all communication with all other segments.
```suggestion
For this scenario, it's not necessary to define IB policies for *HR* or *Marketing* as IB policies without a defined policy have an implied allow all communication with all other segments.
```

2022-05-19 06:08 UTC, JohanFreelancer9 requested changes
@DamienPascua, kindly commit the remaining suggested change. Thanks.

2022-05-20 03:49 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-20 03:56 UTC, JohanFreelancer9 approved these changes

2022-05-20 23:32 UTC, DamienPascua commented
@JohanFreelancer9 Looking to confirm we are good on this pull request, do I need to take any additional action?

2022-05-21 04:49 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2022-05-31 17:04 UTC, robmazz commented
@yogkumgit, @DamienPascua - thanks for the feedback, will need to confirm these suggestions with PM and DEV.

2022-12-20 17:18 UTC, robmazz commented
@DamienPascua - thanks for the feedback. This topic is undergoing changes for the newer version of IB, I will discuss this the PG and confirm that this addition is still accurate. Thanks again.

2022-12-20 17:18 UTC, closed without merging