Update attack-surface-reduction-rules-reference.md
MicrosoftDocs/microsoft-365-docs pull request #8670
Opened 2022-05-19 16:08 UTC by msbemba

Add a note that the PS scripts have been temporarily excluded from the "Block execution of potentially obfuscated scripts" rule  due to the large scale FP issues faced in the past.

2022-05-19 16:08 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-19 16:08 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8506

2022-05-19 16:08 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8530

2022-05-20 04:23 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md
> +> The Powershell scripts have been temporarily excluded from the "Block execution of potentially obfuscated scripts" rule  due to the large scale FP issues faced in the past.
```suggestion
> PowerShell scripts have been temporarily excluded from the "Block execution of potentially obfuscated scripts" rule due to the large-scale FP issues faced in the past.
```

2022-05-20 04:23 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-20 11:49 UTC, JohanFreelancer9 approved these changes

2022-05-27 06:41 UTC, yogkumgit commented
@tiburd Please merge this PR.

2022-05-27 13:55 UTC, merged