Update ownerless-groups-teams.md
MicrosoftDocs/microsoft-365-docs pull request #8672
Opened 2022-05-19 16:19 UTC by msbemba

Mentioned that Global administrator is required to create a policy for ownerless groups

2022-05-19 16:19 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-19 16:19 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8543

2022-05-20 04:56 UTC, JohanFreelancer9 commented on microsoft-365/admin/create-groups/ownerless-groups-teams.md
> +A Global administrator create a policy what automatically asks the most active members or an ownerless group or team if they'll accept ownership. When a member accepts the invitation to become an own
```suggestion
A Global administrator can create a policy that automatically asks the most active members of an ownerless group or team if they'll accept ownership. When a member accepts the invitation to become an owner, the action is logged in the compliance portal audit log. Guests are never invited to be owners.
```

2022-05-20 04:56 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-20 10:17 UTC, merged