Update web-content-filtering.md
MicrosoftDocs/microsoft-365-docs pull request #8685
Opened 2022-05-22 13:34 UTC by msbemba

added M365 business premium to the list of prereqs as it includes M365 Defender for business

2022-05-22 13:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-22 13:35 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8593

2022-05-23 03:46 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/web-content-filtering.md
> +| Subscription | Your subscription must include one of the following:<br/>- [Windows 10/11 Enterprise E5](/windows/deployment/deploy-enterprise-licenses)<br/>- [Microsoft 365 E5](https://www.microsof
```suggestion
| Subscription | Your subscription must include one of the following:<br/>- [Windows 10/11 Enterprise E5](/windows/deployment/deploy-enterprise-licenses)<br/>- [Microsoft 365 E5](https://www.microsoft.com/microsoft-365/enterprise/e5?activetab=pivot%3aoverviewtab)<br/>- Microsoft 365 E5 Security<br/>- [Microsoft 365 E3](https://www.microsoft.com/microsoft-365/enterprise/e3?activetab=pivot%3aoverviewtab)<br/>- [Microsoft Defender for Endpoint Plan 1 or Plan 2](../defender/eval-defender-endpoint-overview.md)<br/>- [Microsoft Defender for Business](../defender-business/mdb-overview.md)<br/>- [Microsoft 365 Business Premium](https://www.microsoft.com/microsoft-365/business/microsoft-365-business-premium)|
```

2022-05-23 03:47 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-23 04:45 UTC, JohanFreelancer9 approved these changes

2022-05-23 17:48 UTC, denisebmsft approved these changes
Thank you @msbemba @JohanFreelancer9

2022-05-23 17:48 UTC, merged