Replaced slang terms
MicrosoftDocs/microsoft-365-docs pull request #8719
Opened 2022-05-25 13:59 UTC by JeremyTBradshaw

There is no such thing as the "Exchange Online admin" role.  There is no place in these docs for writers' comfort-zone slang.  Readers came here for a reason, we shouldn't steer them wrong with terminology that is not going to be found anywhere within the products that they've come here to learn about.

Also, updated the recommendation to also assign the "Service Support Administrator" (not "Service admin") role so that it is clearly just that, a recommendation.  It's not mandatory to do that and it's subjective.

2022-05-27 05:20 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/about-exchange-online-admin-role.md
>  description: "Exchange Online admins manage your organization email and mailboxes and, for example, recover deleted items in a user's mailbox."
```suggestion
description: "Exchange administrators manage your organization's email and mailboxes and, for example, recover deleted items in a user's mailbox."
```

2022-05-27 05:22 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/about-exchange-online-admin-role.md
> + **Tip**: When you assign someone to the Exchange Administrator role, it is recommended to assign them to the Service Support Administrator role. This way they can see important information in the Mi
```suggestion
 **Tip**: When you assign someone to the Exchange Administrator role, we recommend assigning them to the Service Support Administrator role. This way they can see important information in the Microsoft 365 admin center, such as the health of the Exchange Online service, and change and release notifications.
```

2022-05-27 05:23 UTC, JohanFreelancer9 requested changes
Copy review - @JeremyTBradshaw, kindly commit the minor additional suggested changes. Many thanks.

2022-05-27 11:19 UTC, JeremyTBradshaw commented
@JohanFreelancer9 I think I've done so correctly.  Here's hoping.  Just let me know if I need to redo or do anything more.  Thanks!

2022-05-27 13:26 UTC, JohanFreelancer9 commented on microsoft-365/admin/add-users/about-exchange-online-admin-role.md
> + **Tip**: When you assign someone to the Exchange Administrator role, it is recommended to assign them to the Service Support Administrator role. This way they can see important information in the Mi
```suggestion
> [!TIP]
> When you assign someone to the Exchange Administrator role, we recommend assigning them to the Service Support Administrator role. This way they can see important information in the Microsoft 365 admin center, such as the health of the Exchange Online service, and change and release notifications.
```

2022-05-27 13:29 UTC, JohanFreelancer9 approved these changes
Thank you @JeremyTBradshaw.

2022-06-01 12:21 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2022-06-01 18:26 UTC, merged