Update onboard-windows-multi-session-device.md
MicrosoftDocs/microsoft-365-docs pull request #8747
Opened 2022-05-28 12:04 UTC by msbemba

Corrected all references to WVD

2022-05-28 12:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-28 12:04 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8723

2022-05-30 08:01 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md
> +There are several ways to onboard a AVD host machine:
```suggestion
There are several ways to onboard an AVD host machine:
```

2022-05-30 08:03 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md
> +As part of your onboarding, you may want to consider setting a machine tag to can differentiate AVD machines more easily in the Microsoft Security Center. For more information, see
```suggestion
As part of your onboarding, you may want to consider setting a machine tag to differentiate AVD machines more easily in the Microsoft Security Center. For more information, see
```

2022-05-30 08:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-30 08:50 UTC, JohanFreelancer9 commented
@msbemba, you have missed one suggestion. Could you please also commit that? Many thanks.

2022-05-30 12:10 UTC, JohanFreelancer9 approved these changes

2022-06-01 12:23 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2022-06-09 18:31 UTC, merged