Minor Modification and Reference Link addition
MicrosoftDocs/microsoft-365-docs pull request #875
Opened 2019-12-02 16:44 UTC by joinimran

Added a  reference link to get details of the values required to set.

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/801

2019-12-02 16:44 UTC, joinimran commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-12-03 02:56 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md
> +|Set Bulk email threshold to|6|4|The default is currently 7 but it is recommended to make it 6. For details see [Bulk Complaint Level values](https://docs.microsoft.com/microsoft-365/security/office-
```suggestion
|Set Bulk email threshold to|6|4|The default is currently 7 but it is recommended to change it to 6. For details, see [Bulk Complaint Level values](https://docs.microsoft.com/microsoft-365/security/office-365-security/bulk-complaint-level-values). |
```

2019-12-03 02:57 UTC, JohanFreelancer9 requested changes
Copy Review

2019-12-03 04:37 UTC, joinimran commented
Ready to go live

2019-12-04 19:35 UTC, mypil commented
@MSFTTracyP - PR has been copy edited and is ready for final review. This is based on issue #801.

Thank you.

cc: @kenwith

2019-12-07 00:51 UTC, merged