Update protect-your-global-administrator-accounts.md
MicrosoftDocs/microsoft-365-docs pull request #8750
Opened 2022-05-29 12:42 UTC by michaelmsonne

Added Best practices for Azure AD roles

2022-05-30 09:24 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/protect-your-global-administrator-accounts.md
> +> To secure your privileged roles, check out [Best practices for Azure AD roles](/azure/active-directory/roles/best-practices) to securing privileged access to your tenant.
```suggestion
> To secure your privileged roles, check out [Best practices for Azure AD roles](/azure/active-directory/roles/best-practices) to secure privileged access to your tenant.
```

2022-05-30 09:25 UTC, JohanFreelancer9 requested changes
Copy review - @michaelmsonne, kindly commit the suggested change. Many thanks.

2022-05-30 09:32 UTC, michaelmsonne commented on microsoft-365/enterprise/protect-your-global-administrator-accounts.md
> +> To secure your privileged roles, check out [Best practices for Azure AD roles](/azure/active-directory/roles/best-practices) to securing privileged access to your tenant.
Sure, i see 👍

2022-05-30 11:24 UTC, JohanFreelancer9 approved these changes

2022-06-01 12:25 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-06-07 16:55 UTC, merged