Update plan-external-collaboration.md
MicrosoftDocs/microsoft-365-docs pull request #8759
Opened 2022-05-30 13:16 UTC by msbemba

Added a statement that protected documents can be opened by external if permissions are configured.

2022-05-30 13:16 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8725

2022-05-30 13:16 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-31 04:50 UTC, JohanFreelancer9 commented on microsoft-365/solutions/plan-external-collaboration.md
> +[Sensitivity labels](/microsoft-365/compliance/sensitivity-labels) available in the host organization are the only labels that can be applied to the documents in a shared channel site. A file that is
```suggestion
[Sensitivity labels](/microsoft-365/compliance/sensitivity-labels) available in the host organization are the only labels that can be applied to the documents in a shared channel site. A file that is encrypted by a sensitivity label cannot be opened by external participants unless permissions are granted. Automatic labeling is not used.
```

2022-05-31 04:50 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-31 08:10 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-31 08:11 UTC, yogkumgit commented
@MikePlumleyMSFT Please merge this PR. Thanks

2022-05-31 11:35 UTC, JohanFreelancer9 approved these changes

2022-05-31 15:03 UTC, merged