Update microsoft-defender-antivirus-compatibility.md
MicrosoftDocs/microsoft-365-docs pull request #8762
Opened 2022-05-30 14:04 UTC by msbemba

Updated the table with Windows 2012 R2 as well

2022-05-30 14:04 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-05-30 14:05 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8690

2022-05-31 05:11 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md
> +|Windows Server 2022<br/>Windows Server 2019<br/>Windows Server, version 1803, or newer <br/> Windows Server 2016 <br/> Windows Server 2012R2 |A non-Microsoft antivirus/antimalware solution|Disabled
```suggestion
|Windows Server 2022 <br/> Windows Server 2019<br/> Windows Server, version 1803, or newer <br/> Windows Server 2016 <br/> Windows Server 2012 R2 |Microsoft Defender Antivirus|Active mode|
|Windows Server 2022<br/>Windows Server 2019<br/>Windows Server, version 1803, or newer <br/> Windows Server 2016 <br/> Windows Server 2012 R2 |A non-Microsoft antivirus/antimalware solution|Disabled (set manually) <sup>[[1](#fn1)]</sup>|
```

2022-05-31 05:12 UTC, JohanFreelancer9 requested changes
Copy review.

2022-05-31 08:21 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-31 08:22 UTC, yogkumgit commented
@denisebmsft Please merge this PR. Thanks

2022-05-31 11:53 UTC, JohanFreelancer9 approved these changes

2022-06-02 19:58 UTC, merged