Update manage-license-requests.md
MicrosoftDocs/microsoft-365-docs pull request #8791
Opened 2022-06-02 16:58 UTC by msbemba

Added related content (Self Service purchase Faq) to this document.

2022-06-02 16:58 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-02 16:58 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8769

2022-06-03 04:10 UTC, JohanFreelancer9 commented on microsoft-365/commerce/licenses/manage-license-requests.md
> +[Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq?view=o365-worldwide)
```suggestion
[Self-service purchase FAQ](/microsoft-365/commerce/subscriptions/self-service-purchase-faq)
```

2022-06-03 04:10 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-03 07:25 UTC, JohanFreelancer9 approved these changes

2022-06-03 12:45 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2022-06-10 00:16 UTC, cmcatee-MSFT approved these changes

2022-06-10 00:17 UTC, merged