Update create-user-accounts-with-microsoft-365-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #8792
Opened 2022-06-02 17:11 UTC by msbemba

Added Licensing SKU document in a couple of places to avoid delay in finding the SKU

2022-06-02 17:11 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-02 17:11 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8781

2022-06-03 04:26 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/create-user-accounts-with-microsoft-365-powershell.md
> +|**LicenseAssignment** <br/> |No  <br/> |This is the licensing plan also known as the [license plan or SKU](https://docs.microsoft.com/azure/active-directory/enterprise-users/licensing-service-plan-r
```suggestion
|**LicenseAssignment** <br/> |No  <br/> |This is the licensing plan (also known as the [license plan or SKU](/azure/active-directory/enterprise-users/licensing-service-plan-reference)) from which an available license is assigned to the user account. The license defines the Microsoft 365 services that are available to the account. You don't have to assign a license to a user when you create the account, but the account must have a license to access Microsoft 365 services. You have 30 days to license the user account after you create it. |
```

2022-06-03 04:27 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/create-user-accounts-with-microsoft-365-powershell.md
> +To list the available [licensing plan names](https://docs.microsoft.com/azure/active-directory/enterprise-users/licensing-service-plan-reference), use this command:
```suggestion
To list the available [licensing plan names](/azure/active-directory/enterprise-users/licensing-service-plan-reference), use this command:
```

2022-06-03 04:27 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-03 07:37 UTC, JohanFreelancer9 approved these changes

2022-06-03 12:21 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-06-07 16:55 UTC, merged