Update share-calendars-with-external-users.md
MicrosoftDocs/microsoft-365-docs pull request #8801
Opened 2022-06-03 10:41 UTC by msbemba

Added instructions to share calendar to external users

2022-06-03 10:41 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-03 10:41 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8782

2022-06-03 14:51 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/share-calendars-with-external-users.md
> +Once sharing is enabled, calendar owners can extend invitations to specific users.
```suggestion
Once sharing is enabled, calendar owners can extend invitations to specific users by following these steps:
```

2022-06-03 15:00 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/share-calendars-with-external-users.md
> +- Select **Share**.
```suggestion
1. Open [Outlook on the Web](https://outlook.office365.com).

2. At the top of the page, select the app launcher and select **Calendar**. By default, your primary calendar is called "Calendar". If you created other calendars, you can select one of them to share instead. You cannot share calendars owned by other people.

3. Enter the name or email address of the person with whom you want to share your calendar in the **Send a sharing invitation in email** box.

4. Choose how much information you want this person to see:

- **Can view when I'm busy** lets the person see when you are busy but does not include details such as the event location.

- **Can view titles and locations** lets the person see when you are busy as well as the title and location of events.

- **Can view all details** lets the person see all the details of your events.

- **Can edit** lets the person see all details of your events and edit your calendar (only available when sharing with people in your organization).

5. Select **Share**. 
```

2022-06-03 15:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-04 07:25 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/share-calendars-with-external-users.md
> +- **Can edit** lets the person see all details of your events and edit your calendar (only available when sharing with people in your organization).
```suggestion
     - **Can view when I'm busy** lets the person see when you are busy but does not include details such as the event location.

     - **Can view titles and locations** lets the person see when you are busy as well as the title and location of events.

     - **Can view all details** lets the person see all the details of your events.

     - **Can edit** lets the person see all details of your events and edit your calendar (only available when sharing with people in your organization).
```

2022-06-04 07:26 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2022-06-09 09:59 UTC, yogkumgit commented
@JohanFreelancer9

2022-06-09 14:12 UTC, JohanFreelancer9 approved these changes

2022-06-09 23:37 UTC, merged