Update manage-billing-profiles.md
MicrosoftDocs/microsoft-365-docs pull request #8802
Opened 2022-06-03 11:09 UTC by msbemba

Updated the billing profiles to reduce ambiguity

2022-06-03 11:09 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-03 11:09 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8751

2022-06-03 15:18 UTC, JohanFreelancer9 commented on microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md
> +A billing profile contains a payment method, Bill-to information, and other invoice settings, such as purchase order number and email invoice preference. You use a billing profile to pay for the prod
```suggestion
A billing profile contains a payment method, Bill-to information, and other invoice settings, such as purchase order number and email invoice preference. You use a billing profile to pay for the products that you buy from Microsoft. Billing profiles are only available if you bought your subscription directly through Microsoft Sales. They aren't available for customers who bought their subscription through the product's website or on the Purchase services page in the Microsoft 365 admin center. Each billing profile is invoiced separately. 
```

2022-06-03 15:19 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-04 06:34 UTC, JohanFreelancer9 approved these changes

2022-06-20 10:49 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2022-07-06 23:21 UTC, merged