Corrected a wrong and misleading limitation
MicrosoftDocs/microsoft-365-docs pull request #8806
Opened 2022-06-03 20:44 UTC by cyrusirandoust

After spending months with Microsoft on behalf of an important public sector organization, Microsoft recognized that the documentation was wrong about the limitation of "100,000 devices and 7 Mb files" which is by essence impossible as the limitation for any OMA-URI XML file in Microsoft back-end is 350,000 characters. 
If you require, I can share with you the official answer from Microsoft Premier support escalated to the product owner. 
The error in the documentation led our client to loose a lot of time and money to find that specific answer. 
Feel free to contact me for any improvement on my pull request.

2022-06-05 08:51 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +### What is the removable storage media and policy limitations?
```suggestion
### What are the removable storage media and policy limitations?
```

2022-06-05 08:52 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +Either from the Microsoft Endpoint Manager portal (Intune) or through MS Graph API, the backend call is done through OMA-URI (GET to read or PATCH to update) and therefore the limitation is the same
```suggestion
Either from the Microsoft Endpoint Manager portal (Intune) or through Microsoft Graph API, the backend call is done through OMA-URI (GET to read or PATCH to update) and therefore the limitation is the same as any OMA-URI custom configuration profile in Microsoft which is officially 350,000 characters for XML files. 
```

2022-06-05 08:53 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +As example, if you need two blocks of Entry per user SID to "Allow"/"Audit allowed" specific users and 2 block of Entry at the end to "Deny" all, you will be able to manage 2276 users.
```suggestion
For example, if you need two blocks of entries per user SID to "Allow"/"Audit allowed" specific users and two blocks of entries at the end to "Deny all", you will be able to manage 2276 users. 
```

2022-06-05 08:54 UTC, JohanFreelancer9 requested changes
Copy review - @cyrusirandoust, kindly commit the suggested changes. Many thanks.

2022-06-06 07:05 UTC, cyrusirandoust commented
Hi @JohanFreelancer9 thanks for the review. I just have a doubt about the "Deny all" as only the word "Deny" is an option, but the place it has in my example means "Deny all". It's implicit, but technically can confuse if people read literally.  
Do you think those changes can be pushed today?

2022-06-06 10:07 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md
> +For example, if you need two blocks of entries per user SID to "Allow"/"Audit allowed" specific users and two blocks of entries at the end to "Deny all", you will be able to manage 2276 users.
```suggestion
For example, if you need two blocks of entries per user SID to "Allow"/"Audit allowed" specific users and two blocks of entries at the end to "Deny" all, you will be able to manage 2276 users. 
```

2022-06-06 10:14 UTC, JohanFreelancer9 commented
Hi @cyrusirandoust. Thanks for committing the changes and your clarification. I agree with you, so please revert that specific change. Unfortunately, I cannot give you a specific answer as to when your changes will be merged, but today is certainly a possibility. @yogkumgit?

2022-06-06 15:10 UTC, denisebmsft approved these changes
Thank you @cyrusirandoust @JohanFreelancer9

2022-06-06 15:11 UTC, merged