Update dlp-configure-endpoint-settings.md
MicrosoftDocs/microsoft-365-docs pull request #8821
Opened 2022-06-07 07:18 UTC by kurtsarens

Better use direct language. The wording was confusing and could be interpreted that files directly under the folder are also excluded. Confirmed with page in Dutch language

2022-06-08 06:42 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-configure-endpoint-settings.md
> +- Valid file path that ends with `\*`, which means only files under subfolders, files directly under the folder are not excluded. <br/>For example: `C:\Temp\*`
```suggestion
- Valid file path that ends with `\*`, which means only files under subfolders. Files directly under the folder are not excluded. <br/>For example: `C:\Temp\*`
```

2022-06-08 06:43 UTC, JohanFreelancer9 requested changes
Copy review - @kurtsarens, kindly commit the suggested change. Many thanks.

2022-06-08 15:39 UTC, kurtsarens commented
@JohanFreelancer9 who has write access?

2022-06-08 17:04 UTC, JohanFreelancer9 commented
@kurtsarens, as the creator of this PR, you should be able to commit these changes.

2022-06-08 18:09 UTC, kurtsarens commented
@JohanFreelancer9 I have 2 commits... what else is needed here?

2022-06-09 09:23 UTC, JohanFreelancer9 approved these changes

2022-06-09 09:25 UTC, JohanFreelancer9 commented
@kurtsarens, thank you for the commits. Nothing else is required from you. After approval, your changes will be merged and will be live.

2022-06-20 10:50 UTC, yogkumgit commented
@chrfox Please review and merge this PR. Thanks

2022-07-20 18:07 UTC, chrfox commented
holding this pending feedback from PT

2022-08-16 15:44 UTC, opbld31 commented
Docs Build status updates of commit _[0df28b1](https://github.com/kurtsarens/microsoft-365-docs/commits/0df28b1d6e678fb90d0245762c3e3401a89ef26c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-configure-endpoint-settings.md](https://github.com/kurtsarens/microsoft-365-docs/blob/patch-7/microsoft-365/compliance/dlp-configure-endpoint-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208161543278074-8821/BuildReport?accessString=585a8c299a0f247c6105107cd2f455cd6056bcdd6bfbdd5606e81f8ffb1fef04).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 15:45 UTC, opbld33 commented
Docs Build status updates of commit _[c9f9c76](https://github.com/kurtsarens/microsoft-365-docs/commits/c9f9c767c647567fdc2ff1da226931fc73503565)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-configure-endpoint-settings.md](https://github.com/kurtsarens/microsoft-365-docs/blob/patch-7/microsoft-365/compliance/dlp-configure-endpoint-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208161544053449-8821/BuildReport?accessString=b3c6667cf15b7c738318180ea83800990016afe66133e7e63ec91ab2bbb230c5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 15:52 UTC, merged