Update protection-stack-microsoft-defender-for-office365.md
MicrosoftDocs/microsoft-365-docs pull request #8849
Opened 2022-06-09 11:12 UTC by msbemba

Trusted ARC sealers is an admin-created list of intermediary domains who have implemented ARC sealing. reference https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders?view=o365-worldwide

2022-06-09 11:12 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8830

2022-06-09 11:13 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-09 17:04 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md
> +    - **ARC**  builds on DMARC to work with forwarding in mailing lists, while recording an authentication chain.
```suggestion
    - **ARC**  builds on DMARC to work with forwarding in mailing lists while recording an authentication chain.
```

2022-06-09 17:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-10 08:14 UTC, yogkumgit commented
@msbemba

2022-06-14 08:32 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md
> +    - **ARC**  builds on DMARC to work with forwarding in mailing lists while recording an authentication chain.
```suggestion
    - **ARC** builds on DMARC to work with forwarding in mailing lists while recording an authentication chain.
```

2022-06-14 08:32 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more ,please.

2022-06-15 10:52 UTC, yogkumgit commented
@JohanFreelancer9

2022-06-15 12:57 UTC, JohanFreelancer9 approved these changes

2022-06-16 05:03 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2022-07-11 06:12 UTC, yogkumgit commented
@MSFTTracyP Gentle reminder. thanks

2022-08-26 21:49 UTC, opbld31 commented
Docs Build status updates of commit _[5d5a3fa](https://github.com/msbemba/microsoft-365-docs/commits/5d5a3fa742afb8195238d25a0be26892276be325)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1078/microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208262148457069-8849/BuildReport?accessString=b9380f86fb0006d122968f2b55064351ff8260a43f5b0d2445fe5bc9826a8bea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 22:02 UTC, opbld33 commented
Docs Build status updates of commit _[5ba191a](https://github.com/msbemba/microsoft-365-docs/commits/5ba191a57b44e0c6bdeefa0a9a52db19b3f3a6ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1078/microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208262159442378-8849/BuildReport?accessString=1f72b5ba2ccd5f7e67536eab0bf63746c7c35edbc1c72c05ee822faa0055eed7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 22:02 UTC, merged