Update offboard-machine-api.md
MicrosoftDocs/microsoft-365-docs pull request #8852
Opened 2022-06-09 11:27 UTC by msbemba

Added a statement stating that if you don't use the json comment it will error out with 400

2022-06-09 11:27 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8838

2022-06-09 11:28 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-10 06:05 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/offboard-machine-api.md
> +Here is an example of the request. If there is no json comment added, it will error out with code **400**
```suggestion
Here is an example of the request. If there is no JSON comment added, it will error out with code **400**.
```

2022-06-10 06:05 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-10 08:29 UTC, yogkumgit commented
@msbemba

2022-06-20 10:51 UTC, yogkumgit commented
@msbemba Gentle reminder

2022-06-21 07:57 UTC, JohanFreelancer9 approved these changes

2022-06-22 03:50 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-06-28 20:38 UTC, merged