Update install-app-guard.md
MicrosoftDocs/microsoft-365-docs pull request #8856
Opened 2022-06-09 13:04 UTC by manoth-msft

Updated and clarified the references to the Microsoft 365 Apps plus various channels (removing the generic 'Office' term which leads to confusion if e.g. Office 2019 is supported).

2022-06-12 08:18 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/install-app-guard.md
> +* **Office**: Microsoft 365 apps with build 16.0.13530.10000 or later. For Current Channel and Monthly Enterprise Channel installations, this equals to version 2011. For Semi-Annual Enterprise Channe
```suggestion
* **Office**: Microsoft 365 Apps with build 16.0.13530.10000 or later. For Current Channel and Monthly Enterprise Channel installations, this equals to version 2011. For Semi-Annual Enterprise Channel and Semi-Annual Enterprise Channel (Preview), the minimum version is 2108 or later. Both 32-bit and 64-bit versions are supported.
```

2022-06-12 08:19 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/install-app-guard.md
> +To learn more about Microsoft 365 apps update channels, see [Overview of update channels for Microsoft 365 Apps](/deployoffice/overview-update-channels).
```suggestion
To learn more about Microsoft 365 Apps update channels, see [Overview of update channels for Microsoft 365 Apps](/deployoffice/overview-update-channels).
```

2022-06-12 08:19 UTC, JohanFreelancer9 requested changes
Copy review - @manoth-msft, kindly commit the suggested changes. Many thanks.

2022-06-13 06:39 UTC, JohanFreelancer9 approved these changes

2022-06-20 10:52 UTC, yogkumgit commented
@schmurky Please merge this PR. Thanks

2022-06-28 13:20 UTC, yogkumgit commented
@schmurky Gentle reminder. Thanks

2022-06-29 03:17 UTC, merged