Update advanced-hunting-fileprofile-function.md
MicrosoftDocs/microsoft-365-docs pull request #8887
Opened 2022-06-12 07:07 UTC by amirsc3

Adjusting explanation to avoid customer confusion. Based on dev confirmation - this will return false if the binary is not built-in to Windows OS.

2022-06-12 08:55 UTC, JohanFreelancer9 commented on microsoft-365/security/defender/advanced-hunting-fileprofile-function.md
> +| `IsRootSignerMicrosoft` | `boolean` | Indicates whether the signer of the root certificate is Microsoft and file is built-in to Windows OS |
```suggestion
| `IsRootSignerMicrosoft` | `boolean` | Indicates whether the signer of the root certificate is Microsoft and the file is built-in to Windows OS |
```

2022-06-12 08:56 UTC, JohanFreelancer9 requested changes
Copy review - @amirsc3, kindly commit the minor suggested change. Many thanks.

2022-06-12 17:12 UTC, JohanFreelancer9 approved these changes

2022-06-20 10:52 UTC, yogkumgit commented
@schmurky Please merge this PR. Thanks

2022-06-28 13:20 UTC, yogkumgit commented
@schmurky Gentle reminder. Thanks

2022-07-14 09:05 UTC, merged