Update get-started-core-ediscovery.md
MicrosoftDocs/microsoft-365-docs pull request #8912
Opened 2022-06-14 12:42 UTC by msbemba

Update per user licensing as well

2022-06-14 12:42 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8813

2022-06-14 12:42 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-14 17:56 UTC, v-tophillips approved these changes

2022-06-15 10:18 UTC, JohanFreelancer9 commented on microsoft-365/compliance/get-started-core-ediscovery.md
> +  -  Exchange online Plan 2 license
```suggestion
  
  -  Exchange Online Plan 2 license
```

2022-06-15 10:18 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-15 10:53 UTC, yogkumgit commented
@msbemba

2022-06-15 17:46 UTC, merged