updated with Defender status
MicrosoftDocs/microsoft-365-docs pull request #8923
Opened 2022-06-15 10:38 UTC by DevOpsStyle

Hello All,

actually in the documentation was reported the method to disable the Defender with the Registry Key. I aso addedd the procedure for disable the Defender with a GPO.

Thank you all for the support

2022-06-16 10:29 UTC, DevOpsStyle reviewed
Added information about GPO procedure related Defender

2022-06-17 02:35 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md
> +- Set the GPO to "Enabled"
```suggestion
- Open Group Policy Management Editor -> **Computer Configuration** -> **Administrative Templates** -> **Windows Components** -> **Microsoft Defender Antivirus**.
- Select **Turn Off Microsoft Defender Antivirus**.
- Set the GPO to **Enabled**.
```

2022-06-17 02:36 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md
> +We can view the Protection status in Powershell with the command "Get-MpComputerStatus" and the key "AMRunningMode"
```suggestion
You can view the Protection status in PowerShell with the command "Get-MpComputerStatus" and the key "AMRunningMode".
```

2022-06-17 02:39 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md
> +In the example below the Defender status is **Not Running**.
```suggestion
In the following example, the Defender status is **Not Running**.
```

2022-06-17 02:41 UTC, JohanFreelancer9 requested changes
Copy review - @DevOpsStyle, kindly commit the suggested changes. Many thanks.

2022-06-17 08:29 UTC, DevOpsStyle commented
> Copy review - @DevOpsStyle, kindly commit the suggested changes. Many thanks.

Thanks for your support.

Your suggestions are commited

2022-06-17 12:53 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md
> +- Open Group Policy Management Editor -> **Computer Configuration** -> **Administrative Templates** -> **Windows Components** -> **Microsoft Defender Antivirus**.
```suggestion
- Open Group Policy Management Editor > **Computer Configuration** > **Administrative Templates** > **Windows Components** > **Microsoft Defender Antivirus**.
```

2022-06-17 12:55 UTC, JohanFreelancer9 requested changes
My apologies @DevOpsStyle, just minor style changes that I missed the first time around. Thank you so much.

2022-06-17 13:25 UTC, DevOpsStyle commented
> My apologies @DevOpsStyle, just minor style changes that I missed the first time around. Thank you so much.

Please don't say sorry :) 
Thanks again for your help, commit pushed 👍

2022-06-17 15:10 UTC, JohanFreelancer9 approved these changes
Thanks, @DevOpsStyle.

2022-06-17 18:07 UTC, DevOpsStyle commented
> Thanks, @DevOpsStyle.

Thank you too :) 
There is nothing else i need to do previously to the merge?

2022-06-17 19:58 UTC, denisebmsft approved these changes
Thank you @DevOpsStyle

2022-06-17 19:59 UTC, merged