Update ome-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #8947
Opened 2022-06-17 17:23 UTC by samschan-ms

Added portal log FAQ. @KCCross , @v-tophillips please review

2022-06-20 10:54 UTC, yogkumgit commented
@JohanFreelancer9

2022-06-20 16:16 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          The encrypted message portal support preview of any encrypted attachment copies added to the encrypted mail. The support file types includes Word, Excel, Powerpoint, and PDF files.
```suggestion
          The encrypted message portal support preview of any encrypted attachment copies added to the encrypted mail. The support file types include Word, Excel, Powerpoint, and PDF files.  
```

2022-06-20 16:19 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          What types of recipients do the encrypted message portal activity logs work?
```suggestion
          On what types of recipients do the encrypted message portal activity logs work?
```

2022-06-20 16:21 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          The encrypted message portal activity logs only capture events for external recipients by accessing the encrypted message portals.  Any activities in email clients triggered by external rec
```suggestion
          The encrypted message portal activity logs only capture events for external recipients by accessing the encrypted message portals.  Any activities in email clients triggered by external recipients are not recorded. For internal recipients, see [Purview Audit (Premium) - Mail items accessed logs](/compliance/mailitemsaccessed-forensics-investigations#the-mailitemsaccessed-mailbox-auditing-action). 
```

2022-06-20 16:27 UTC, JohanFreelancer9 requested changes
Copy review - @samschan-ms, kindly commit the suggested changes.

2022-06-21 09:37 UTC, JohanFreelancer9 approved these changes

2022-06-22 04:10 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-08-24 00:41 UTC, KCCross commented
I reworked these changes through the private repo as some needed additional clarification.

2022-08-24 00:41 UTC, closed without merging