Minor document changes
MicrosoftDocs/microsoft-365-docs pull request #8951
Opened 2022-06-18 03:19 UTC by dhairyya

Allows are not automatically extended by us
Allow and blocks are both supported by spoof sender is no longer needed after document structuring
Notes for blocked spoof senders updated

2022-06-20 10:55 UTC, yogkumgit commented
@JohanFreelancer9

2022-06-21 08:59 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/allow-block-email-spoof.md
> +Note that admins can't add allows directly to the Tenant Allow/Block List. Instead, you use the admin submission process to submit the message that were blocked so the corresponding URL, file, and/or
```suggestion
Note that admins can't add allows directly to the Tenant Allow/Block List. Instead, you use the admin submission process to submit the message that was blocked so the corresponding URL, file, and/or senders will be added to the Tenant Allow/Block List. If a block of the file, URL, or sender has not happened, then the allow will not be created. In most cases where the message was determined to be a false positive that was incorrectly blocked, the allows are removed on the date of the expiry as set by you while creating it.
```

2022-06-21 09:06 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/allow-block-email-spoof.md
> +8. When you're finished, click the **Submit** button.
```suggestion
8. When you're finished, select the **Submit** button.
```

2022-06-21 09:06 UTC, JohanFreelancer9 requested changes
Copy review - @dhairyya, kindly commit the suggested changes. Many thanks.

2022-06-21 16:43 UTC, merged