Update use-dmarc-to-validate-email.md
MicrosoftDocs/microsoft-365-docs pull request #8984
Opened 2022-06-23 04:57 UTC by msbemba

Updated Step 3 to reflect 5321.MailFrom as the default

2022-06-23 04:57 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8924

2022-06-23 04:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-23 09:58 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md
> +Once you've set up SPF, you need to set up DKIM. DKIM lets you add a digital signature to email messages in the message header. If you don't set up DKIM and instead allow Microsoft 365 to use the def
```suggestion
Once you've set up SPF, you need to set up DKIM. DKIM lets you add a digital signature to email messages in the message header. If you don't set up DKIM and instead allow Microsoft 365 to use the default DKIM configuration for your domain, DMARC may fail. This failure can happen because the default DKIM configuration uses your original *onmicrosoft.com* domain as the *5321.MailFrom* address, not your *custom* domain. This creates a mismatch between the *5321.MailFrom* and the *5322.From addresses* in all the email sent from your domain.
```

2022-06-23 09:58 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-23 11:16 UTC, JohanFreelancer9 approved these changes

2022-06-24 15:19 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-06-24 15:29 UTC, tiburd commented
reviewed + confirmed

2022-06-24 15:29 UTC, merged