Update use-microsoft-365-cdn-with-spo.md
MicrosoftDocs/microsoft-365-docs pull request #8987
Opened 2022-06-23 05:12 UTC by msbemba

to reduce ambiguity removed the Germany cloud as it has been retired - https://www.microsoft.com/en-us/cloud-platform/germany-cloud-regions#:~:text=A%3A%20On%20October%2029%2C%202021,in%20Europe%20before%20this%20time.

2022-06-23 05:12 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-23 05:12 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8941

2022-06-23 09:46 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md
> +> The Office 365 CDN is only available to tenants in the **Production** (worldwide) cloud. Tenants in the US Government amd China clouds do not currently support the Office 365 CDN.
```suggestion
> The Office 365 CDN is only available to tenants in the **Production** (worldwide) cloud. Tenants in the US Government and China clouds do not currently support the Office 365 CDN.
```

2022-06-23 09:46 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-23 11:19 UTC, JohanFreelancer9 approved these changes

2022-06-24 15:25 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-06-28 15:20 UTC, merged