Update manage-feedback-product-insights.md
MicrosoftDocs/microsoft-365-docs pull request #8991
Opened 2022-06-23 05:34 UTC by msbemba

checked and updated admin center to reflect M365 admin center and also added a hyper link to the same

2022-06-23 05:34 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-06-23 05:34 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8967

2022-06-23 09:09 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/manage-feedback-product-insights.md
> +1. In the [M365 admin center](https://admin.microsoft.com/), go to the **Health** > **Product feedback** > **NPS survey insights**.
```suggestion
1. In the [Microsoft 365 admin center](https://admin.microsoft.com/), go to **Health** > **Product feedback** > **NPS survey insights**.
```

2022-06-23 09:09 UTC, JohanFreelancer9 requested changes
Copy review.

2022-06-23 11:20 UTC, JohanFreelancer9 approved these changes

2022-06-24 15:40 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-07-07 21:39 UTC, merged