Update ome-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #9034
Opened 2022-06-27 20:59 UTC by samschan-ms

@KCCross , @v-tophillips  to review the minor change to explain encryption inheritance to unencrypted attachments.

2022-06-28 06:24 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          Protection is inherited from mail to unencrypted attachments only.  If a file format is supported, such as a Word, Excel, or PowerPoint file, the file is always protected, even after the at
```suggestion
          Protection is inherited from mail to unencrypted attachments only. If a file format is supported, such as a Word, Excel, or PowerPoint file, the file is always protected, even after the attachment has been downloaded by the recipient. For example, say an attachment is protected by Do Not Forward. The original recipient downloads the file, creates a message to a new recipient, and attaches the file. When the new recipient receives the file, the recipient will not be able to open the protected file.
```

2022-06-28 06:25 UTC, JohanFreelancer9 requested changes
Copy review - @samschan-ms, kindly commit the minor suggested change. Many thanks.

2022-06-29 07:45 UTC, JohanFreelancer9 approved these changes

2022-06-30 10:16 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-08-24 00:02 UTC, opbld32 commented
Docs Build status updates of commit _[36d6a85](https://github.com/samschan-ms/microsoft-365-docs/commits/36d6a85ee2f47512f216c5f8b02c6984d2274059)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/ome-faq.yml](https://github.com/samschan-ms/microsoft-365-docs/blob/patch-43/microsoft-365/compliance/ome-faq.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208240001387725-9034/BuildReport?accessString=be621d7bcdcc3a5c4a8e61cbe8e755fa54967d0728d2fd9c1d3751c9c0c34250).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 00:27 UTC, merged