added correct path , added links, made bold
MicrosoftDocs/microsoft-365-docs pull request #9094
Opened 2022-07-05 16:16 UTC by RAJU2529

as per user report #9077, i added correct path of cmd.exe  , added links of windows server 2022 and windows 11 and  removed gap.

2022-07-06 08:32 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md
> +> After onboarding to Defender for Endpoint, you might have to set Microsoft Defender Antivirus to passive mode on **Windows Server**. To validate that passive mode was set as expected, search for *e
```suggestion
> After onboarding to Defender for Endpoint, you might have to set Microsoft Defender Antivirus to passive mode on **Windows Server**. To validate that passive mode was set as expected, search for *event 5007* in the **Microsoft-Windows-Windows Defender Operational** log (located at `C:\Windows\System32\winevt\Logs`), and confirm that either the  **ForceDefenderPassiveMode** or **PassiveMode** registry keys were set to **0x1**.
```

2022-07-06 08:33 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md
> +|[Microsoft Endpoint Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/)|See [Create and deploy antimalware policies for Endpoint Protection in Configuration Manager](/mem/configm
```suggestion
|[Microsoft Endpoint Configuration Manager](/mem/configmgr)|See [Create and deploy antimalware policies for Endpoint Protection in Configuration Manager](/mem/configmgr/protect/deploy-use/endpoint-antimalware-policies). <br/><br/> When you create and configure your antimalware policies, make sure to review the [real-time protection settings](/mem/configmgr/protect/deploy-use/endpoint-antimalware-policies#real-time-protection-settings) and [enable block at first sight](configure-block-at-first-sight-microsoft-defender-antivirus.md).
```

2022-07-06 08:36 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md
> +|[Windows 11](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-overview) <br/><br/>Windows 10, [version 1803](/lifecycle/announcements/windows-server-1803-end-of-servicing) or later (See
```suggestion
|[Windows 11](/windows/whats-new/windows-11-overview) <br/><br/>Windows 10, [version 1803](/lifecycle/announcements/windows-server-1803-end-of-servicing) or later (See [Windows 10 release information](/windows/release-health/release-information))<br/><br/>Windows 10, version 1703 or 1709 with [KB4493441](https://support.microsoft.com/help/4493441) installed <br/><br/> [Windows Server 2022](/windows/release-health/status-windows-server-2022)<br/><br/>[Windows Server 2019](/windows/release-health/status-windows-10-1809-and-windows-server-2019) <br/><br/>[Windows Server 2016](/windows/release-health/status-windows-10-1607-and-windows-server-2016)<br/><br/>[Windows Server 2012 R2](/windows/release-health/status-windows-8.1-and-windows-server-2012-r2)<br/><br/>[Windows Server, version 1803](/windows-server/get-started/whats-new-in-windows-server-1803) | `C:\Program Files\Windows Defender Advanced Threat Protection\MsSense.exe`<br/><br/>`C:\Program Files\Windows Defender Advanced Threat Protection\SenseCncProxy.exe`<br/><br/>`C:\Program Files\Windows Defender Advanced Threat Protection\SenseSampleUploader.exe`<br/><br/>`C:\Program Files\Windows Defender Advanced Threat Protection\SenseIR.exe`<br/><br/>`C:\Program Files\Windows Defender Advanced Threat Protection\SenseCM.exe`<br/><br/>`C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\DataCollection`<br/><br/> In addition, on Windows Server 2012 R2 and 2016 running the modern, unified solution the following exclusions are required after updating the Sense EDR component using [KB5005292](https://support.microsoft.com/en-us/topic/microsoft-defender-for-endpoint-update-for-edr-sensor-f8f69773-f17f-420f-91f4-a8e5167284ac):<br/> <br/> `C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Platform\*\MsSense.exe` <br/><br/>`C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Platform\*\SenseCnCProxy.exe`<br/><br/>`C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Platform\*\SenseIR.exe`<br/><br/>`C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Platform\*\SenseCE.exe`<br/><br/>`C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Platform\*\SenseSampleUploader.exe`<br/><br/>`C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Platform\*\SenseCM.exe`|
```

2022-07-06 08:37 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-06 15:36 UTC, JohanFreelancer9 approved these changes

2022-07-07 17:42 UTC, denisebmsft approved these changes
Thank you @RAJU2529 @JohanFreelancer9

2022-07-07 17:42 UTC, merged