added  MHA link
MicrosoftDocs/microsoft-365-docs pull request #9095
Opened 2022-07-05 16:30 UTC by RAJU2529

as per user report #9084, so i added  new  link  of MHA **https://mha.azurewebsites.net/**  this new link is included in below article 

**https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide**

![Screenshot 2022-07-05 220051](https://user-images.githubusercontent.com/3296790/177374430-65d02586-0d09-4a37-b418-6b55e2174c41.jpg)

2022-07-06 08:44 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md
> +After setup, check your ARC Headers with [Message Header Analyzer](https://mha.azurewebsites.net/).
```suggestion
After setup, check your ARC Headers with [Message Header Analyzer](https://mha.azurewebsites.net).
```

2022-07-06 08:45 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-06 10:02 UTC, JohanFreelancer9 approved these changes

2022-07-08 13:34 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2022-07-28 17:10 UTC, merged