Update transfer-a-domain-from-microsoft-to-another-host.md
MicrosoftDocs/microsoft-365-docs pull request #9126
Opened 2022-07-08 10:57 UTC by msbemba

Added line about signing in as GA

2022-07-08 10:57 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9103

2022-07-08 10:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-08 11:08 UTC, JohanFreelancer9 commented on microsoft-365/admin/get-help-with-domains/transfer-a-domain-from-microsoft-to-another-host.md
> +Sign in as a Global Administrator, follow these steps to get a code at Microsoft 365, and then go to the other domain registrar website to set up transferring your domain name to the new registrar.
```suggestion
Sign in as a global administrator, follow these steps to get a code at Microsoft 365, and then go to the other domain registrar website to set up transferring your domain name to the new registrar.
```

2022-07-08 11:09 UTC, JohanFreelancer9 requested changes
Copy review - @msbemba, I know there are many inconsistencies in the capitalization of global admin, but this is the latest guidance. Thanks.

2022-07-14 07:59 UTC, yogkumgit commented
@msbemba Gentle reminder

2022-07-14 11:29 UTC, JohanFreelancer9 approved these changes

2022-07-15 11:34 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2022-10-14 16:50 UTC, opbld30 commented
Learn Build status updates of commit _[5fc0cb4](https://github.com/msbemba/microsoft-365-docs/commits/5fc0cb47608df9a070c9f2b8002982e4dd9c6f3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/get-help-with-domains/transfer-a-domain-from-microsoft-to-another-host.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1116/microsoft-365/admin/get-help-with-domains/transfer-a-domain-from-microsoft-to-another-host.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210141648131802-9126/BuildReport?accessString=ae47e9d777ae2fe14528d26ab004cd4fa51f04d340bfab48ac688a2586edb487).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 17:04 UTC, merged