Update endpoint-dlp-using.md
MicrosoftDocs/microsoft-365-docs pull request #9135
Opened 2022-07-11 07:11 UTC by msbemba

Added subscription requirement for endpoint DLP. @chrfox  This is assuming that the licenses needed have not changed with Microsoft purview.

2022-07-11 07:12 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9082

2022-07-11 07:12 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-11 08:11 UTC, JohanFreelancer9 commented on microsoft-365/compliance/endpoint-dlp-using.md
> +for full licensing details, see [Microsoft 365 licensing guidance for information protection](/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-lice
```suggestion
For full licensing details, see [Microsoft 365 licensing guidance for information protection](/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection-data-loss-prevention-for-exchange-online-sharepoint-online-and-onedrive-for-business).
```

2022-07-11 08:11 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-11 11:44 UTC, JohanFreelancer9 approved these changes

2022-07-12 04:49 UTC, yogkumgit commented
@chrfox Please merge this PR. Thnaks.

2022-07-20 17:00 UTC, merged