Update sensitive-information-type-entity-definitions.md
MicrosoftDocs/microsoft-365-docs pull request #9160
Opened 2022-07-13 13:23 UTC by pratjain523

@chrfox Updates to the definition of 2 SITs. Also removing the message of partial availability of some SITs since now all solutions including endpoint have those SITs

2022-07-13 13:39 UTC, pratjain523 commented
@chrfox Added the definition of 2 new SITs as well

2022-07-14 07:59 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-entity-definitions.md
> +Seven or eight or nine alphanumeric characters
```suggestion
seven or eight or nine alphanumeric characters
```

2022-07-14 08:00 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-entity-definitions.md
> +- one letter followed by seven digits followed by one letter
```suggestion
- one letter followed by six digits
or
- two letters followed by six digits
or
- two letters followed by seven digits
or
- one letter followed by seven digits followed by one letter.
```

2022-07-14 08:00 UTC, yogkumgit commented
@pratjain523 Please implement the suggested changes. Thanks.

2022-07-14 08:01 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-entity-definitions.md
> +Seven or eight or nine alphanumeric characters
```suggestion
Seven or eight or nine alphanumeric characters:
```

2022-07-14 08:03 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-entity-definitions.md
> +eleven digits:
```suggestion
Eleven digits:
```

2022-07-14 08:03 UTC, JohanFreelancer9 commented on microsoft-365/compliance/sensitive-information-type-entity-definitions.md
> +- five digits
```suggestion
- five digits.
```

2022-07-14 08:06 UTC, JohanFreelancer9 requested changes
Copy review - @pratjain523, kindly commit the minor suggested changes. Many thanks.

2022-07-15 11:26 UTC, yogkumgit commented
@pratjain523 Please implement the suggested changes. Thanks

2022-07-18 06:28 UTC, yogkumgit commented
@pratjain523 Gentle reminder

2022-07-18 09:37 UTC, pratjain523 commented
Committed all suggestions.

2022-07-18 13:03 UTC, JohanFreelancer9 approved these changes

2022-07-19 05:46 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-07-20 16:54 UTC, chrfox commented
holding this until after the publication of split SIT entity defn

2022-07-27 14:43 UTC, pratjain523 commented
@chrfox I see the doc has been split. Can you help push these changes through?

2022-08-08 21:37 UTC, chrfox commented
@pratjain523  - You can to make these changes to the individual articles now, they are all public.

2022-08-19 17:15 UTC, chrfox commented
all accomplished in other PR's

2022-08-19 17:15 UTC, closed without merging