Update set-up-new-message-encryption-capabilities.md
MicrosoftDocs/microsoft-365-docs pull request #9171
Opened 2022-07-14 11:06 UTC by msbemba

Updated the steps as aadrm module is depricated and is replaced by AIP service

2022-07-14 11:07 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-14 11:07 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9171

2022-07-14 14:37 UTC, JohanFreelancer9 commented on microsoft-365/compliance/set-up-new-message-encryption-capabilities.md
> +4. If the test fails with an error message **Failed to acquire RMS templates**, execute the following commands and run the Test-IRMConfiguration cmdlet to verify that it passes. Connect to the [AIPSe
```suggestion
4. If the test fails with an error message **Failed to acquire RMS templates**, execute the following commands and run the Test-IRMConfiguration cmdlet to verify that it passes. Connect to the [AIPService module](/powershell/module/aipservice/?view=azureipps) to run the cmdlet.
```

2022-07-14 14:39 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-14 15:17 UTC, JohanFreelancer9 approved these changes

2022-07-15 11:47 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-07-29 21:12 UTC, merged

2022-07-29 21:17 UTC, opbld31 commented
Docs Build status updates of commit _[dbcdfc5](https://github.com/msbemba/microsoft-365-docs/commits/dbcdfc5b736e0313f2efb8adae1cfb0a5a0e3b6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/set-up-new-message-encryption-capabilities.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1126/microsoft-365/compliance/set-up-new-message-encryption-capabilities.md) | :bulb:Suggestion | | [Details](#user-content-c2c4a36bb97858e5bdbe6d19613936cb-7925b975)

<a id="c2c4a36bb97858e5bdbe6d19613936cb-7925b975"></a>
### [microsoft-365/compliance/set-up-new-message-encryption-capabilities.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1126/microsoft-365/compliance/set-up-new-message-encryption-capabilities.md)
 - **Line 104, Column 194**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/module/aipservice/?view=azureipps`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207292114067581-9171/BuildReport?accessString=301f28e67cff679e76187e518e716b5a01c3bf1838659e0557e6b43b7d4114e8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 21:18 UTC, opbld32 commented
Docs Build status updates of commit _[dbcdfc5](https://github.com/msbemba/microsoft-365-docs/commits/dbcdfc5b736e0313f2efb8adae1cfb0a5a0e3b6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/set-up-new-message-encryption-capabilities.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1126/microsoft-365/compliance/set-up-new-message-encryption-capabilities.md) | :bulb:Suggestion | | [Details](#user-content-c2c4a36bb97858e5bdbe6d19613936cb-1c473849)

<a id="c2c4a36bb97858e5bdbe6d19613936cb-1c473849"></a>
### [microsoft-365/compliance/set-up-new-message-encryption-capabilities.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1126/microsoft-365/compliance/set-up-new-message-encryption-capabilities.md)
 - **Line 104, Column 194**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/module/aipservice/?view=azureipps`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207292115063688-9171/BuildReport?accessString=05a6fef6767beabfab3fc9fbd34325f36baf5b781a2b9f337c3941b448375d95).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>