Update and rename How to enable DMARC Reporting for Microsoft Online …
MicrosoftDocs/microsoft-365-docs pull request #9178
Opened 2022-07-14 17:37 UTC by MSFTBen

…Email Routing Address (MOERA) and parked Domains to How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains.md

2022-07-15 08:14 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/step-by-step-guides/How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains.md
>  - Sufficient permissions as Global Admin to make the appropriate changes in the Microsoft 365 Admin Center
```suggestion
- Sufficient permissions as global admin to make the appropriate changes in Microsoft 365 admin center
```

2022-07-15 08:18 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/step-by-step-guides/How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains.md
>  1.  Login to the [Microsoft 365 Admin Center](https://admin.microsoft.com).
```suggestion
1. Sign in to [Microsoft 365 admin center](https://admin.microsoft.com).
```

2022-07-15 08:20 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/step-by-step-guides/How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains.md
>  1.  Press **Save**.
```suggestion
1.  Select **Save**.
```

2022-07-15 08:21 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/step-by-step-guides/How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains.md
> +1.  Check if SPF is already configured for your parked domain, following this guide: [Set up SPF to help prevent spoofing - Office 365 | Microsoft Docs](https://docs.microsoft.com/microsoft-365/secur
```suggestion
1.  Check if SPF is already configured for your parked domain, following this guide: [Set up SPF to help prevent spoofing - Office 365 | Microsoft Docs](/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing#how-to-handle-subdomains).
```

2022-07-15 08:22 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/step-by-step-guides/How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains.md
> +1.  Ask to add this DMARC txt record with your appropriate email reporting addresses "v=DMARC1; p=reject; rua=mailto:d@rua.contoso.com;ruf=mailto:d@ruf.contoso.com"
```suggestion
1.  Ask to add this DMARC txt record with your appropriate email reporting addresses "v=DMARC1; p=reject; rua=mailto:d@rua.contoso.com;ruf=mailto:d@ruf.contoso.com".
```

2022-07-15 08:23 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/step-by-step-guides/How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains.md
> +[Set up SPF to help prevent spoofing - Office 365 | Microsoft Docs](https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing)
```suggestion
[Set up SPF to help prevent spoofing - Office 365 | Microsoft Docs](/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing)
```

2022-07-15 08:23 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/step-by-step-guides/How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains.md
> +[Use DMARC to validate email, setup steps - Office 365 | Microsoft Docs](https://docs.microsoft.com/microsoft-365/security/office-365-security/use-dmarc-to-validate-email)
```suggestion
[Use DMARC to validate email, setup steps - Office 365 | Microsoft Docs](/microsoft-365/security/office-365-security/use-dmarc-to-validate-email)
```

2022-07-15 08:26 UTC, JohanFreelancer9 requested changes
Copy review - @MSFTBen, kindly also commit the few additional suggested changes (even though they are mostly not related to your changes). Many thanks.

2022-07-18 06:29 UTC, yogkumgit commented
@MSFTBen Gentle reminder

2022-07-20 17:16 UTC, MSFTTracyP approved these changes
Thanks

2022-07-20 17:21 UTC, merged