Update ome-faq.yml
MicrosoftDocs/microsoft-365-docs pull request #9184
Opened 2022-07-15 20:11 UTC by samschan-ms

MInor update to clarify pdf encryption

2022-07-18 06:30 UTC, yogkumgit commented
@JohanFreelancer9

2022-07-18 12:44 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-faq.yml
> +          The short answer is yes! If enabled in Exchange Online, PDF encryption allows you to protect sensitive PDF documents attached to email. When you send an email, the Office 365 service encryp
```suggestion
          The short answer is yes! If enabled in Exchange Online, PDF encryption allows you to protect sensitive PDF documents attached to emails. When you send an email, the Office 365 service encrypts PDF file attachments for Outlook on the web, Outlook for Mac, Outlook for iOS, and Outlook for Android. You can encrypt PDFs you send without any more steps.
```

2022-07-18 12:46 UTC, JohanFreelancer9 requested changes
Copy review - @samschan-ms, kindly commit the minor suggested changes. Many thanks.

2022-07-19 05:37 UTC, JohanFreelancer9 approved these changes

2022-07-19 05:49 UTC, yogkumgit commented
@KCCross Please merge this PR. Thanks

2022-08-23 23:48 UTC, opbld32 commented
Docs Build status updates of commit _[44d827e](https://github.com/samschan-ms/microsoft-365-docs/commits/44d827e5e9d759d322e715776cbed1f164b20551)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/ome-faq.yml](https://github.com/samschan-ms/microsoft-365-docs/blob/patch-45/microsoft-365/compliance/ome-faq.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208232347533238-9184/BuildReport?accessString=4525644f25d8a6c6b42ed94b087e99a0246b1d474d4b14fff75ce0bb89e08dcc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 23:49 UTC, merged