Update dlp-policy-reference.md
MicrosoftDocs/microsoft-365-docs pull request #9199
Opened 2022-07-19 19:34 UTC by edwinchan-microsoft

added Preview items for Trainable classifiers

@chrfox @LauraWi

2022-07-20 07:24 UTC, yogkumgit commented
@JohanFreelancer9

2022-07-20 08:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-policy-reference.md
> +> DLP now supports usage of Trainable Classifiers as a condition to detect sensitive documents. Content can be defined by Trainable Classifiers in Exchange email online, Sharepoint Online sites, OneD
```suggestion
> DLP now supports the usage of Trainable Classifiers as a condition to detect sensitive documents. Content can be defined by Trainable Classifiers in Exchange email online, Sharepoint Online sites, OneDrive for Business accounts, Teams Chat and Channels, and Devices. For more information, see [Trainable Classifiers](classifier-learn-about.md).
```

2022-07-20 08:15 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-policy-reference.md
> +- (In Preview)[Trainable Classifiers](classifier-learn-about.md)
```suggestion
- [Trainable Classifiers](classifier-learn-about.md) (in preview) 
```

2022-07-20 08:16 UTC, JohanFreelancer9 requested changes
Copy review - @edwinchan-microsoft, kindly commit the suggested changes. Many thanks.

2022-07-20 17:18 UTC, JohanFreelancer9 approved these changes

2022-07-27 18:26 UTC, KCCross commented
KC merging on behalf of Chris Fox. Update DLP policy reference for using TC as a condition is now in public preview.

2022-07-27 18:27 UTC, merged