Update microsoft-365-mailbox-utilization-service-alerts.md
MicrosoftDocs/microsoft-365-docs pull request #9216
Opened 2022-07-20 22:43 UTC by holliep1

Adding a blurb that the mailbox usage report is 24 hours behind the alert. And updating a piece of the document that didn't read right.

2022-07-21 07:23 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/microsoft-365-mailbox-utilization-service-alerts.md
> +To display a list of mailboxes that are nearing their storage quota, click the highlighted link in the following screenshot to access your mailbox usage report. This link is displayed in the service
```suggestion
To display a list of mailboxes that are nearing their storage quota, select the highlighted link in the following screenshot to access your mailbox usage report. This link is displayed in the service advisory.
```

2022-07-21 07:24 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/microsoft-365-mailbox-utilization-service-alerts.md
> +Please note that the mailbox usage report information could be 24 hours behind your mailbox utilization service advisory alert.
```suggestion
> [!NOTE]
> The mailbox usage report information could be 24 hours behind your mailbox utilization service advisory alert.
```

2022-07-21 07:25 UTC, JohanFreelancer9 requested changes
Copy review - @holliep1, kindly commit the suggested changes. Many thanks.

2022-07-22 06:11 UTC, JohanFreelancer9 approved these changes

2022-07-25 04:30 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-07-26 16:21 UTC, merged