Update delete-calendar.md
MicrosoftDocs/microsoft-365-docs pull request #9227
Opened 2022-07-21 15:40 UTC by msbemba

Updated the document to reduce ambiguity between users and booking calendar

2022-07-21 15:40 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9155

2022-07-21 15:40 UTC, msbemba commented
@JohanFreelancer9 please copy review.

2022-07-22 07:24 UTC, JohanFreelancer9 commented on microsoft-365/bookings/delete-calendar.md
> +1. On the **Active Users** page, choose the names of the Booking calendar that you want to delete, and then select **Delete user**.
```suggestion
1. On the **Active Users** page, choose the name of the booking calendar that you want to delete and then select **Delete user**.
```

2022-07-22 07:24 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-22 10:50 UTC, JohanFreelancer9 approved these changes

2022-07-25 04:31 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-07-26 19:09 UTC, merged