Update preset-security-policies.md
MicrosoftDocs/microsoft-365-docs pull request #9266
Opened 2022-07-27 11:36 UTC by msbemba

Added PS cmdlets to review the settings

2022-07-27 11:36 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9195

2022-07-27 11:36 UTC, msbemba commented
@JohanFreelancer9 Please copy review.

2022-07-27 11:37 UTC, msbemba commented
@yogkumgit The Author is chrisda

2022-07-27 13:52 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/preset-security-policies.md
> +There are two cmdlets that we can use to view these policies:
```suggestion
There are two cmdlets that you can use to view these policies:
```

2022-07-27 13:52 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/preset-security-policies.md
> +1. To View Safe Attachments and Safe Link Policies, you can use the below Cmdlet
```suggestion
1. To view Safe Attachments and Safe Link policies, use the following cmdlet:
```

2022-07-27 13:52 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/preset-security-policies.md
> +2. To View Hosted Connection Filter, Anti-Phish and Malware Filter you can use the below Cmdlet
```suggestion
2. To view the Hosted Connection, Anti-Phish, and Malware filters, use the following cmdlet:
```

2022-07-27 13:53 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/preset-security-policies.md
> +
```suggestion
```

2022-07-27 13:53 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-27 17:34 UTC, chrisda commented
I was in discussion about publishing these \*-\*ProtectionPolicyRule cmdlet reference topics way back in 2020 when preset security policies went live. I have them all semi-documented in a branch in the office-docs-powershell repo, but I never published them on advice from the PM.

A preset security policy simply creates a bunch of regular polices (EOP: malware, spam, phishing (spoof); MDO: phishing (impersonation) Safe Links, Safe Attachments) with names like 'Standard Preset Security Policy1622650008534' or 'Strict Preset Security Policy1642034873192' you can view the settings using the regular Get- cmdlets (i.e., Get-MalwareFilterPolicy).

The \*-EOPProtectionPolicyRule and \*-ATPProtectionPolicyRule cmdlets link the rules to the Standard or Strict polices, and determine who the policies apply to. For some reason, preset security policies couldn't use the regular \*-\<Feature\>Rule cmdlets that are normally associated with policies (i.e, \*-MalwareFilterRule for \*-MalwareFilterPolicy).

So, I don't want to approve this PR (yet) because the cmdlets you added to this topic aren't present in the PowerShell repo. I need to ponder the best way forward.

2022-07-28 03:23 UTC, JohanFreelancer9 approved these changes

2022-07-29 01:07 UTC, chrisda commented
Closing this PR as a massive, better version is coming

2022-07-29 01:07 UTC, closed without merging

2022-07-29 01:14 UTC, opbld30 commented
Docs Build status updates of commit _[cd0a28d](https://github.com/msbemba/microsoft-365-docs/commits/cd0a28d1e8f5893c3a43e7f9a86b393fb418aae1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1136/microsoft-365/security/office-365-security/preset-security-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207290107094600-9266/BuildReport?accessString=1ee2cc5a0f968f258a8e50326c1eddb187cfbf816034afdef03a449229d9a5f5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>