Update bookings-in-outlook.md
MicrosoftDocs/microsoft-365-docs pull request #9270
Opened 2022-07-27 16:20 UTC by msbemba

Made changes to the domains in Default Sharing Policy

2022-07-27 16:20 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9202

2022-07-27 16:20 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-28 02:22 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-in-outlook.md
> +    "Anonymous:ContactsSharing": Share contacts only.
```suggestion
You should have one of the following domains in the response:

    "Anonymous:CalendarSharingFreeBusySimple": Share free/busy hours only.
    
    "Anonymous:CalendarSharingFreeBusyDetail": Share free/busy hours, subject, and location.
    
    "Anonymous:CalendarSharingFreeBusyReviewer": Share free/busy hours, subject, location, and the body of the message or calendar item.
    
    "Anonymous:ContactsSharing": Share contacts only.
```

2022-07-28 02:22 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-in-outlook.md
> +   You should have one of the above domains in the response.
```suggestion
```

2022-07-28 02:23 UTC, JohanFreelancer9 commented on microsoft-365/bookings/bookings-in-outlook.md
> +   To enable anonymous sharing, use the following command or alter **Add** section with the domain that you would like to add.
```suggestion
   To enable anonymous sharing, use the following command or alter the **Add** section with the domain that you would like to add.
```

2022-07-28 02:25 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-28 02:52 UTC, yogkumgit commented
@msbemba

2022-07-28 15:17 UTC, JohanFreelancer9 approved these changes

2022-07-28 22:47 UTC, opbld30 commented
Docs Build status updates of commit _[4197cf2](https://github.com/msbemba/microsoft-365-docs/commits/4197cf2cdb1dffbd64b0b91d88fdfc7c56b5c72e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md) | :bulb:Suggestion | | [Details](#user-content-bac18554b5bf27fe4f797e7390aa3447-1ec6f1b1)

<a id="bac18554b5bf27fe4f797e7390aa3447-1ec6f1b1"></a>
### [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md)
 - **Line 60, Column 105**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps`````
 - **Line 70, Column 1**: **[Suggestion: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207282239355873-9270/BuildReport?accessString=1947e9807be4588f71c527cf39edc4eed8fda48028f49be681b3ef11e1451b43).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-28 22:54 UTC, opbld30 commented
Docs Build status updates of commit _[4197cf2](https://github.com/msbemba/microsoft-365-docs/commits/4197cf2cdb1dffbd64b0b91d88fdfc7c56b5c72e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md) | :bulb:Suggestion | | [Details](#user-content-bac18554b5bf27fe4f797e7390aa3447-f5d2b787)

<a id="bac18554b5bf27fe4f797e7390aa3447-f5d2b787"></a>
### [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md)
 - **Line 60, Column 105**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps`````
 - **Line 70, Column 1**: **[Suggestion: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207282239399341-9270/BuildReport?accessString=00ba2fd448295e67d43c8626394beb5b3cc63af4fa96e28c45d1be7e20b08889).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 00:38 UTC, tiburd commented
@msbemba @JohanFreelancer9 @yogkumgit 
Hi!
This repo now has build validation checks turned on - see above.
Note that validation must pass for the PR to be merged:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/54688693/181659202-e903ca24-e8c3-4b41-9720-34d4e82828a9.png">
For your questions, please send me email. 
Thank you!

2022-08-02 11:14 UTC, yogkumgit commented
@kwekuako Please merge this PR. thanks

2022-08-02 11:43 UTC, opbld30 commented
Docs Build status updates of commit _[361bdef](https://github.com/msbemba/microsoft-365-docs/commits/361bdeffb557aab002a6b42ddfaa676883983d10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md) | :bulb:Suggestion | | [Details](#user-content-bac18554b5bf27fe4f797e7390aa3447-f1dce9ea)

<a id="bac18554b5bf27fe4f797e7390aa3447-f1dce9ea"></a>
### [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md)
 - **Line 60, Column 105**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 60, Column 105**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps`````
 - **Line 70, Column 1**: **[Suggestion: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208021142367182-9270/BuildReport?accessString=190b21735f2967b79bd402314d28105449d89e22f4ac1daf742956c6c6883c11).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 11:46 UTC, opbld33 commented
Docs Build status updates of commit _[9fb8631](https://github.com/msbemba/microsoft-365-docs/commits/9fb86316f19307d2c077d020ed1c5ab69c2b47bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md) | :bulb:Suggestion | | [Details](#user-content-bac18554b5bf27fe4f797e7390aa3447-563a9b4f)

<a id="bac18554b5bf27fe4f797e7390aa3447-563a9b4f"></a>
### [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md)
 - **Line 70, Column 1**: **[Suggestion: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208021145335628-9270/BuildReport?accessString=9bfec48b81f4f75c6bb9c9466caacfa4fccce8966b54a6a952bb8f62d428ade8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 11:54 UTC, opbld32 commented
Docs Build status updates of commit _[88535ef](https://github.com/msbemba/microsoft-365-docs/commits/88535efff13d47d6eb7e1d0b06783714e8b00415)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md) | :bulb:Suggestion | | [Details](#user-content-bac18554b5bf27fe4f797e7390aa3447-67440326)

<a id="bac18554b5bf27fe4f797e7390aa3447-67440326"></a>
### [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1139/microsoft-365/bookings/bookings-in-outlook.md)
 - **Line 70, Column 1**: **[Suggestion: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208021153258571-9270/BuildReport?accessString=3e5982a14943d0dfcfe66a1841d36748d9b6efafc2142a4340b610356137acea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 00:35 UTC, tiburd commented
@get-itips @dariomws @tseward 
Hi! Can you please review the changes to the PowerShell blocks in this PR?
Thanks!

2022-08-30 01:10 UTC, ghost approved these changes

2022-08-30 23:55 UTC, ekaplanb commented on microsoft-365/bookings/bookings-in-outlook.md
> +    Anonymous:ContactsSharing: Share contacts only.
Share contact only doesn't allow viewing the Calendar  Freebusy status of the organizer, why added?

2022-08-31 11:22 UTC, yogkumgit commented
@msbemba

2022-08-31 13:05 UTC, get-itips commented
I think this PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9473 replaces this one, @msbemba please confirm, if positive, this PR should be closed.

2022-08-31 17:01 UTC, msbemba commented
Closing this PR as we have another one replacing this #9473 https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9473

2022-08-31 17:01 UTC, closed without merging