Update add-licenses-using-product-key.md
MicrosoftDocs/microsoft-365-docs pull request #9282
Opened 2022-07-29 14:24 UTC by msbemba

Made changes to the navigation as the options have changed

2022-07-29 14:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-29 14:25 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9258

2022-07-29 14:32 UTC, opbld30 commented
Docs Build status updates of commit _[362d0b0](https://github.com/msbemba/microsoft-365-docs/commits/362d0b03a67bb7955daf6c51d54d7f73c3816ed5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/commerce/licenses/add-licenses-using-product-key.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1141/microsoft-365/commerce/licenses/add-licenses-using-product-key.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207291424434461-9282/BuildReport?accessString=50d8416fcb3e6ccecdf80a59cbd8ae6a1575d4fd627bc5cd13cd871142b05d2c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 15:09 UTC, JohanFreelancer9 commented on microsoft-365/commerce/licenses/add-licenses-using-product-key.md
> +5. Enter the product key, then select **Validate** and **Next**
```suggestion
3. On the subscription details page, in the **Licenses** section, select **Add licenses**.
4. In the **Add licenses pane**, select **Redeem Product Key**.
5. Enter the product key, then select **Validate** and **Next**.
```

2022-07-29 15:10 UTC, JohanFreelancer9 approved these changes

2022-07-29 15:11 UTC, JohanFreelancer9 requested changes
@msbemba, kindly commit the suggested changes. Many thanks.

2022-07-29 15:32 UTC, opbld32 commented
Docs Build status updates of commit _[fea89c5](https://github.com/msbemba/microsoft-365-docs/commits/fea89c58fd6b57cd0a8ac05c4028b026294b892b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/commerce/licenses/add-licenses-using-product-key.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1141/microsoft-365/commerce/licenses/add-licenses-using-product-key.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207291524459881-9282/BuildReport?accessString=3b0733b08b5dc1442bd49bb2c8ed57af143d72d489daac7157a5141acee6aca8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 16:15 UTC, JohanFreelancer9 approved these changes

2022-08-02 11:15 UTC, yogkumgit commented
@cmcatee-MSFT Please merge this PR. Thanks

2022-10-06 18:43 UTC, cmcatee-MSFT commented
Article has been retired and the procedures moved to 2 separate articles. After I review the UI with the PM, I'll update the necessary files. In the meantime, closing this PR.

2022-10-06 18:43 UTC, closed without merging