Update assign-licenses-to-user-accounts-with-microsoft-365-powershell.md
MicrosoftDocs/microsoft-365-docs pull request #9285
Opened 2022-07-29 14:39 UTC by msbemba

Added another cmdlet to pull all synced unlicensed users

2022-07-29 14:39 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9268

2022-07-29 14:39 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-29 14:47 UTC, opbld33 commented
Docs Build status updates of commit _[ad67757](https://github.com/msbemba/microsoft-365-docs/commits/ad6775712dbc0b06de8eabf30c43753af4c0b028)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1144/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207291439051068-9285/BuildReport?accessString=8d14629182e06f7d2963971345f03d91822f9e76157585bb4f909621bcc2049b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 15:51 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md
> +To find the unlicensed Synchornized users in your oganization, run this command.
```suggestion
To find the unlicensed synchronized users in your organization, run the following command.
```

2022-07-29 15:52 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-29 16:59 UTC, opbld33 commented
Docs Build status updates of commit _[13d3d6c](https://github.com/msbemba/microsoft-365-docs/commits/13d3d6c36d6988703299692e5d20ed1a7d1c8c29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1144/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207291651480201-9285/BuildReport?accessString=4ba699c4fda5f5cc47466b43a50b4c06cdfd5652da15d2675a0b3e4d80d1c6df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 17:20 UTC, JohanFreelancer9 approved these changes

2022-08-01 14:09 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-08-12 19:24 UTC, opbld30 commented
Docs Build status updates of commit _[29dc16d](https://github.com/msbemba/microsoft-365-docs/commits/29dc16dc36736bf7b97b01a9c6a911d36f25c555)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1144/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208121921082788-9285/BuildReport?accessString=5ddaa9e414fc4635e12573da2cdcff0a944427405a76966692afefe5da3add06).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 19:24 UTC, merged