Update bulk-import-external-contacts.md
MicrosoftDocs/microsoft-365-docs pull request #9290
Opened 2022-07-31 21:11 UTC by msbemba

Updated Steps 3 with the correct Cmdlet. Tested and verified

2022-07-31 21:12 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9120

2022-07-31 21:12 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-31 21:14 UTC, opbld30 commented
Docs Build status updates of commit _[0eabe00](https://github.com/msbemba/microsoft-365-docs/commits/0eabe001ba98371c15590452579555c5786ce4e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/bulk-import-external-contacts.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1146/microsoft-365/compliance/bulk-import-external-contacts.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207312111523273-9290/BuildReport?accessString=93729149e4c57970b27b25a12aef363fa986d14453ccf55342964721adfd88b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 05:06 UTC, JohanFreelancer9 commented on microsoft-365/compliance/bulk-import-external-contacts.md
>  3. Run the following two commands to add the other properties from the CSV file to the external contacts that you created in Step 2.
```suggestion
3. Run the following command to add the other properties from the CSV file to the external contacts that you created in Step 2.
```

2022-08-01 05:06 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-01 13:34 UTC, opbld31 commented
Docs Build status updates of commit _[de9a937](https://github.com/msbemba/microsoft-365-docs/commits/de9a9372ee69ca9ce2a3b955df26058c63109963)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/bulk-import-external-contacts.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1146/microsoft-365/compliance/bulk-import-external-contacts.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208011331565706-9290/BuildReport?accessString=146ff6ea3eca1bee8faf13afad2c3ccb017b8c591a8347a9110684027075b99c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 14:26 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-01 14:26 UTC, yogkumgit commented
@v-tophillips Please merge this PR. Thanks

2022-08-01 14:34 UTC, JohanFreelancer9 approved these changes

2022-08-01 21:27 UTC, v-tophillips approved these changes

2022-08-01 21:28 UTC, merged

2022-08-01 21:29 UTC, opbld31 commented
Docs Build status updates of commit _[15a23dd](https://github.com/msbemba/microsoft-365-docs/commits/15a23dd711fb8366ac0e560d14b4f644e2b2c809)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/bulk-import-external-contacts.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1146/microsoft-365/compliance/bulk-import-external-contacts.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208012127176897-9290/BuildReport?accessString=5f08ba358b1b0441f16a557090d24cea30743bd96c19dbb129205e6b46e26630).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 21:30 UTC, opbld31 commented
Docs Build status updates of commit _[15a23dd](https://github.com/msbemba/microsoft-365-docs/commits/15a23dd711fb8366ac0e560d14b4f644e2b2c809)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/bulk-import-external-contacts.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1146/microsoft-365/compliance/bulk-import-external-contacts.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208012128469144-9290/BuildReport?accessString=4607ee5754b4386be0f39a71a86977e3d8c815fe63c63c0f97f0bf9d7d4ff843).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>