Update alert-policies.md
MicrosoftDocs/microsoft-365-docs pull request #9291
Opened 2022-07-31 22:44 UTC by msbemba

Find and release quarantined messages as a user in EOP and the triggered alerts are applicable to EOP. Looks like the Basic, Standard and Premium also have this feature.

2022-07-31 22:45 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9274

2022-07-31 22:45 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-07-31 22:45 UTC, opbld32 commented
Docs Build status updates of commit _[f6c3db8](https://github.com/msbemba/microsoft-365-docs/commits/f6c3db883314b9c713d8f337f9b82ab7057a6957)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/alert-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1147/microsoft-365/compliance/alert-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202207312244589697-9291/BuildReport?accessString=e07eb190f1584f3965cc25701bbb5319f5f48824c64c22836c0c72eef3869890).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 05:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/alert-policies.md
> +|**User requested to release a quarantined message**|Generates an alert when a user requests release for a quarantined message. To request the release of quarantined messages, the **Allow recipients
```suggestion
|**User requested to release a quarantined message**|Generates an alert when a user requests release for a quarantined message. To request the release of quarantined messages, the **Allow recipients to request a message to be released from quarantine** (_PermissionToRequestRelease_) permission is required in the quarantine policy (for example, from the **Limited access** preset permissions group). For more information, see [Allow recipients to request a message to be released from quarantine permission](../security/office-365-security/quarantine-policies.md#allow-recipients-to-request-a-message-to-be-released-from-quarantine-permission). This policy has an **Informational** severity setting.|Threat management|No| Microsoft Business Basic, Microsoft Business Standard, Microsoft Business Premium, E1/F1/G1, E3/F3/G3, or E5/G5|
```

2022-08-01 05:15 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-01 13:33 UTC, opbld32 commented
Docs Build status updates of commit _[d596646](https://github.com/msbemba/microsoft-365-docs/commits/d59664621e9303d9519b3151ecf9179244c19d6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/alert-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1147/microsoft-365/compliance/alert-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208011331499646-9291/BuildReport?accessString=bc4404fa114ad6ef6bb7d897c19e4b4e3a154919a967e12dc56ad36d25696bef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 14:17 UTC, JohanFreelancer9 approved these changes

2022-08-01 14:30 UTC, yogkumgit commented
@v-tophillips Please merge this PR. Thanks

2022-08-01 21:30 UTC, merged

2022-08-01 21:32 UTC, opbld31 commented
Docs Build status updates of commit _[266df9e](https://github.com/msbemba/microsoft-365-docs/commits/266df9e3aacb027873a91f842733c50747eb3103)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/alert-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1147/microsoft-365/compliance/alert-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208012129338591-9291/BuildReport?accessString=cc7ff1b2619dbe40053d603be92311ea68ef41ebf0957ba1f77cfa7fc580b4d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 21:35 UTC, opbld31 commented
Docs Build status updates of commit _[266df9e](https://github.com/msbemba/microsoft-365-docs/commits/266df9e3aacb027873a91f842733c50747eb3103)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/alert-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1147/microsoft-365/compliance/alert-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208012130464237-9291/BuildReport?accessString=cc3eb07155b33e5bb0bb10e57925e27bb7ac91913e18b1eee796bccec915abfb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>