Update apply-sensitivity-label-automatically.md
MicrosoftDocs/microsoft-365-docs pull request #9322
Opened 2022-08-03 21:33 UTC by edwinchan-microsoft

@KCCross  / @chrfox

2022-08-03 21:34 UTC, opbld32 commented
Docs Build status updates of commit _[d9d0b97](https://github.com/edwinchan-microsoft/microsoft-365-docs/commits/d9d0b97fc914b7b36c0dda689b837d777605eded)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/edwinchan-microsoft/microsoft-365-docs/blob/patch-11/microsoft-365/compliance/apply-sensitivity-label-automatically.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208032133485632-9322/BuildReport?accessString=a3f318fc4c481c20c90bb3f9893904016395304bffe155c683eed03da0beae6e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 23:01 UTC, opbld33 commented
Docs Build status updates of commit _[7982565](https://github.com/edwinchan-microsoft/microsoft-365-docs/commits/798256523147fa20f5602a9945942f9d4a914a6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/edwinchan-microsoft/microsoft-365-docs/blob/patch-11/microsoft-365/compliance/apply-sensitivity-label-automatically.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208032300268820-9322/BuildReport?accessString=e660a8fc5dc526d66922cb706c534d5b86053a7047a5ada55e80a4132e403415).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 23:03 UTC, opbld33 commented
Docs Build status updates of commit _[3010546](https://github.com/edwinchan-microsoft/microsoft-365-docs/commits/30105463ceeb39de7d939c77cbac47ba90cd5bdf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/edwinchan-microsoft/microsoft-365-docs/blob/patch-11/microsoft-365/compliance/apply-sensitivity-label-automatically.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208032302122013-9322/BuildReport?accessString=c72a77ab17f38172448c6892bef144fcc9bd21a33ef1240b8353e66eefa25189).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 23:07 UTC, KCCross commented
Nice job!

2022-08-04 07:26 UTC, JohanFreelancer9 commented on microsoft-365/compliance/apply-sensitivity-label-automatically.md
> +> (In Preview) Auto-labeling policies can use trainable classifiers as a condition to detect sensitive documents. You can define content with trainable classifiers in Exchange Online, Sharepoint Onli
```suggestion
> (In Preview) Auto-labeling policies can use trainable classifiers as a condition to detect sensitive documents. You can define content with trainable classifiers in Exchange Online, SharePoint Online sites, or OneDrive for Business accounts. For more information on Trainable Classifiers, see [Trainable Classifiers](classifier-learn-about.md).
```

2022-08-04 07:27 UTC, JohanFreelancer9 requested changes
Copy review - @edwinchan-microsoft, kindly commit the suggested change. Many thanks.

2022-08-05 00:05 UTC, cabailey commented
As discussed, closing & replacing with 15503

2022-08-05 00:05 UTC, closed without merging

2022-08-05 00:07 UTC, opbld33 commented
Docs Build status updates of commit _[3010546](https://github.com/edwinchan-microsoft/microsoft-365-docs/commits/30105463ceeb39de7d939c77cbac47ba90cd5bdf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/edwinchan-microsoft/microsoft-365-docs/blob/patch-11/microsoft-365/compliance/apply-sensitivity-label-automatically.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208050005187187-9322/BuildReport?accessString=eafb0e2136ae2308751f83cc1f3a712b6135e5856c6e8a9b9862b4be84b838d7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>