Clarifying the behavior of the UX when a device is not supported
MicrosoftDocs/microsoft-365-docs pull request #9330
Opened 2022-08-04 20:05 UTC by j0shbregman

The UX shows the troubleshooting mode option even if the device does not support troubleshooting mode.  This can be confusing, so I've updated the documentation.

2022-08-04 20:07 UTC, opbld30 commented
Docs Build status updates of commit _[bcf143f](https://github.com/j0shbregman/microsoft-365-docs/commits/bcf143f36124a56a4aad9fa9dfa2054f8aa978ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208042005177673-9330/BuildReport?accessString=92132ab46480045ab2f34eb9729010b4330ec170fd1e75efe4b53c90123093c9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 20:09 UTC, opbld30 commented
Docs Build status updates of commit _[a7e2db6](https://github.com/j0shbregman/microsoft-365-docs/commits/a7e2db681795584f71ed128fe516ce5002dc63de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208042006135703-9330/BuildReport?accessString=cd5a6cbd8b19e14ab19f425a78581740b296e834942b0530dd2e80bae8684784).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 20:11 UTC, j0shbregman commented
@denisebmsft Can you hold this until I get final review?

2022-08-04 22:24 UTC, denisebmsft commented
> @denisebmsft Can you hold this until I get final review?

Sure thing!

2022-08-05 04:12 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md
> +> The **Turn on troubleshooting mode** option is available on all devices, even if the device does not meet the pre-requisites for troubleshooting mode.
```suggestion
> The **Turn on troubleshooting mode** option is available on all devices, even if the device does not meet the prerequisites for troubleshooting mode.  
```

2022-08-05 04:12 UTC, JohanFreelancer9 requested changes
Copy review - @j0shbregman, kindly commit the minor suggested change. Many thanks.

2022-08-08 17:26 UTC, opbld32 commented
Docs Build status updates of commit _[4df2cc0](https://github.com/j0shbregman/microsoft-365-docs/commits/4df2cc0e7c0de37d358a2ebd98ab6d1c3622ba2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081725255857-9330/BuildReport?accessString=2fd09507379c41ee77034c56ba22053e5f2f799ae6e7e6286d1ee42a1ae7a04e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 17:27 UTC, opbld32 commented
Docs Build status updates of commit _[af6106a](https://github.com/j0shbregman/microsoft-365-docs/commits/af6106a792551464e3e93cac5d12c5617612e0d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081725330378-9330/BuildReport?accessString=3ef870e1473a58ca39e2cf2e629419f9e8f633fa61e2de6b337c47e09feb9b11).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 02:50 UTC, JohanFreelancer9 approved these changes

2022-08-19 21:37 UTC, opbld33 commented
Docs Build status updates of commit _[59897fe](https://github.com/j0shbregman/microsoft-365-docs/commits/59897fe1a12bf6c2ee42c0868c9968a71dfa9bee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208192135168564-9330/BuildReport?accessString=12d0eaa7adaa8cadca60b82dbf71fa01bbf853a54a9e3ec12c7c90a6bb911dc3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 20:36 UTC, denisebmsft commented
@j0shbregman are we ready to publish?

2022-08-29 20:37 UTC, opbld30 commented
Docs Build status updates of commit _[8fb8591](https://github.com/j0shbregman/microsoft-365-docs/commits/8fb859159cf615c174d3db770d6e32578ace5acd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208292036322084-9330/BuildReport?accessString=953ca9db0f74f0b1f38cbbda4940015aa1dec7b7fd886caf4eaff87de4ea2ce6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 16:40 UTC, opbld31 commented
Docs Build status updates of commit _[76ed5a8](https://github.com/j0shbregman/microsoft-365-docs/commits/76ed5a82ce0a28bb296272f3d1efb4f197e00692)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208301638589317-9330/BuildReport?accessString=ffe5faa6122fc74f936ae55943a0a8d12c59b03599b76a9dd2be61ba3f61a407).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-10 16:36 UTC, opbld30 commented
Learn Build status updates of commit _[a44ce42](https://github.com/j0shbregman/microsoft-365-docs/commits/a44ce422aeeffeec643e11c9f0ae79664ff60765)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210101634304446-9330/BuildReport?accessString=8e7d581fe25387a586532464b02d61c59d20ff206caa5670db2005b3d7b5b124).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 20:41 UTC, opbld33 commented
Learn Build status updates of commit _[a5f5554](https://github.com/j0shbregman/microsoft-365-docs/commits/a5f555418ed997566301ce38631b9f0d730eb55a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082039446164-9330/BuildReport?accessString=d75c887bf259e0c1ba8a64cac032a2c154fe96158d9fbe689ad1c44e68845dcd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-05 19:50 UTC, opbld32 commented
Learn Build status updates of commit _[ff42617](https://github.com/j0shbregman/microsoft-365-docs/commits/ff4261796119759b47a768307b75cf805979420b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/j0shbregman/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202301051948295307-9330/BuildReport?accessString=deb5b24bd4413bf2f8ef715461e8e501e660029cc50f264ca57b1bb04c6f4ec1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-05-31 20:58 UTC, denisebmsft approved these changes
Thank you @j0shbregman

2023-06-01 08:40 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +Tampering is the general term used to describe attackers attempts to impair the effectiveness of Microsoft Defender for Endpoint. The ultimate goal of attackers is not to impact a single device, but
```suggestion
Tampering is the general term used to describe attackers' attempts to impair the effectiveness of Microsoft Defender for Endpoint. The ultimate goal of attackers is not to impact a single device, but rather to achieve their objective by launching a ransomware attack, for example.  As such, the anti-tampering capabilities of Microsoft Defender for Endpoint extend beyond preventing the tampering of a single device to detecting attacks and minimizing their impact. 
```

2023-06-01 08:41 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +- Follow the best practice of least privlege. See [Access control overview for Windows](/windows/security/identity-protection/access-control/access-control).
```suggestion
- Follow the best practice of least privilege. See [Access control overview for Windows](/windows/security/identity-protection/access-control/access-control).
```

2023-06-01 08:52 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +> On Windows devices, Microsoft Defender Antivirus can be also be managed via Group Policy, WMI, and PowerShell cmdlets. These methods are more susceptible to tampering than using Microsoft Intune or
```suggestion
> On Windows devices, Microsoft Defender Antivirus can also be managed via Group Policy, WMI, and PowerShell cmdlets. These methods are more susceptible to tampering than using Microsoft Intune, Microsoft Configuration Manager, or Microsoft Defender for Endpoint Security Configuration Management. 
```

2023-06-01 08:57 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +> If you're using Group Policy, we recommend [disabling local overrides for Microsoft Defender Antivirus settings](/microsoft-365/security/defender-endpoint/configure-local-policy-overrides-microsoft
```suggestion
>
> If you are using Group Policy, we recommend [disabling local overrides for Microsoft Defender Antivirus settings](/microsoft-365/security/defender-endpoint/configure-local-policy-overrides-microsoft-defender-antivirus#configure-local-overrides-for-microsoft-defender-antivirus-settings) and [disabling local list merging](/microsoft-365/security/defender-endpoint/configure-local-policy-overrides-microsoft-defender-antivirus#configure-how-locally-and-globally-defined-threat-remediation-and-exclusions-lists-are-merged).
```

2023-06-01 08:58 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +Beyond basic hygiene, attackers use a varierty of tampering techniques to disable Microsoft Defender for Endpoint on a single device.  Different techniques are preventing by different controls on dif
```suggestion
Beyond basic hygiene, attackers use a variety of tampering techniques to disable Microsoft Defender for Endpoint on a single device.  Different techniques are prevented by different controls on different operating systems.
```

2023-06-01 09:00 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +|Attack surface reduction rules | Windows | Kernel drivers (see [Block abuse of exploted vulnerable signed drivers](/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference#
```suggestion
|Attack surface reduction rules | Windows | Kernel drivers (see [Block abuse of exploted vulnerable signed drivers](/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference#block-abuse-of-exploited-vulnerable-signed-drivers)|
```

2023-06-01 09:05 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +## Understanding the different ways to prevent driver based tampering on Windows
```suggestion
## Understanding the different ways to prevent driver-based tampering on Windows
```

2023-06-01 09:09 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +One of the most common techniques is for an attacker to use a driver that has a vulnerability, exploit it, and to gain access to the kernel.  This makes chosing which drivers to block complicated as
```suggestion
One of the most common techniques is for an attacker to use a driver that has a vulnerability, exploit it, and gain access to the kernel. This makes choosing which drivers to block complicated as they often are still used legitimately in many user environments. To that end, Microsoft provides mechanisms for blocking drivers.
```

2023-06-01 09:10 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +A known set of malicious drivers can be blocked from being loaded by Windows using the [Microsoft recommended driver blocklist](/windows/security/threat-protection/windows-defender-application-contro
```suggestion
A known set of malicious drivers can be blocked from being loaded by Windows using the [Microsoft recommended driver blocklist](/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules#microsoft-vulnerable-driver-blocklist).  This functionality is on by default. It is updated as part of operating system releases.  
```

2023-06-01 09:19 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +Vulnerable drivers can be blocked from being loaded by Windows Defender Application Control (WDAC) using the [Vulnerable Driver blocklist XML](/windows/security/threat-protection/windows-defender-app
```suggestion
Vulnerable drivers can be blocked from being loaded by Windows Defender Application Control (WDAC) using the [Vulnerable Driver blocklist XML](/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules#microsoft-vulnerable-driver-blocklist). This list is updated more frequently. WDAC provides an audit mode to help understand the impact of applying the policy in block mode to avoid accidentally impacting legitimate use.
```

2023-06-01 09:21 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +Exploited vulnerable and signed drivers can be blocked from being written to disk by attack surface reduction rules (ASR) using the [Block abuse of exploited vulnerable signed drivers rule](/microsof
```suggestion
Exploited vulnerable and signed drivers can be blocked from being written to disk by attack surface reduction rules (ASR) using the [Block abuse of exploited vulnerable signed drivers rule](/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference#block-abuse-of-exploited-vulnerable-signed-drivers). This list is updated more frequently, and like WDAC has an audit mode to avoid accidentally impacting legitimate use.
```

2023-06-01 09:22 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +## Preventing tampering via Microsof Defender Antivirus exclusions on Windows
```suggestion
## Preventing tampering via Microsoft Defender Antivirus exclusions on Windows
```

2023-06-01 09:23 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +## Organization wide tamper resiliency is built on Zero Trust
```suggestion
## Organization-wide tamper resiliency is built on Zero Trust
```

2023-06-01 09:24 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +- The device is managed by Intune; and
```suggestion
- The device is managed by Intune, and 
```

2023-06-01 09:24 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +For more details see [Tamper protection for antivirus exclusions](/microsoft-365/security/defender-endpoint/manage-tamper-protection-intune#tamper-protection-for-antivirus-exclusions).
```suggestion
For more details, see [Tamper protection for antivirus exclusions](/microsoft-365/security/defender-endpoint/manage-tamper-protection-intune#tamper-protection-for-antivirus-exclusions).
```

2023-06-01 09:25 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +Attackers can be preventing from discovering existing antivirus exclusions by enabling [HideExclusionsFromLocalAdmin](/windows/client-management/mdm/defender-csp#configurationhideexclusionsfromlocala
```suggestion
Attackers can be prevented from discovering existing antivirus exclusions by enabling [HideExclusionsFromLocalAdmin](/windows/client-management/mdm/defender-csp#configurationhideexclusionsfromlocaladmins).  
```

2023-06-01 09:27 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +- Tampering with the Microsoft Defender for Endpoint sensor
```suggestion
- Possible Antimalware Scan Interface (AMSI) tampering.
- Potential attempt to tamper with MDE via drivers.
- Tamper Protection bypass.
- Tampering with the Microsoft Defender for Endpoint sensor.
```

2023-06-01 09:27 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +- Possible tampering with protected processes
```suggestion
- Possible tampering with protected processes.
```

2023-06-01 09:31 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +If the abuse of exploited vulnerable or signed driver ASR rule is triggered, this can be seen in the [ASR Report](/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-report) as w
```suggestion
If the abuse of an exploited vulnerable or signed driver ASR rule is triggered, this can be seen in the [ASR Report](/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-report) as well as in [Advanced Hunting](/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-operationalize#asr-rules-advanced-hunting).
```

2023-06-01 09:32 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/tamper-resiliency.md
> +
```suggestion
```

2023-06-01 09:33 UTC, JohanFreelancer9 requested changes
Copy review - @j0shbregman, kindly commit the suggested changes. Many thanks.

2023-06-01 17:23 UTC, merged