Update advanced-hunting-devicealertevents-table.md
MicrosoftDocs/microsoft-365-docs pull request #9338
Opened 2022-08-05 11:25 UTC by msbemba

DeviceAlertEvents No Longer Provided and is replaced by The AlertInfo and AlertEvidence 
Reference https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-migrate-from-mde?view=o365-worldwide

Added an important note at the top of the article and linked the mapping table

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9316

2022-08-05 11:25 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-05 11:27 UTC, opbld33 commented
Docs Build status updates of commit _[42eb423](https://github.com/msbemba/microsoft-365-docs/commits/42eb423e92a7e6afa1a25c0fe014abea4389890f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md) | :bulb:Suggestion | | [Details](#user-content-4d5e65accc54c0d14adec5d7c51a84ad-0df2d887)

<a id="4d5e65accc54c0d14adec5d7c51a84ad-0df2d887"></a>
### [microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md)
 - **Line 29, Column 1**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /defender/advanced-hunting-migrate-from-mde?view=o365-worldwide#map-devicealertevents-table`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208051125167888-9338/BuildReport?accessString=a5bc805607c98fd901d19c71a03843dd2094feeb86ee8f6e72ff8389da07ea0a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 14:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md
> +>The `AlertInfo` and `AlertEvidence` tables replace the `DeviceAlertEvents` table in the Microsoft Defender for Endpoint schema. See more, for
```suggestion
> [!IMPORTANT]
> The `AlertInfo` and `AlertEvidence` tables replace the `DeviceAlertEvents` table in the Microsoft Defender for Endpoint schema. To learn more, see [Map DeviceAlertEvents Table](/microsoft-365/defender/advanced-hunting-migrate-from-mde?view=o365-worldwide#map-devicealertevents-table).
```

2022-08-05 14:45 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md
> +[Map DeviceAlertEvents](/defender/advanced-hunting-migrate-from-mde?view=o365-worldwide#map-devicealertevents-table)
```suggestion
```

2022-08-05 14:46 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-05 15:43 UTC, yogkumgit commented
@msbemba

2022-08-05 16:40 UTC, opbld31 commented
Docs Build status updates of commit _[7894461](https://github.com/msbemba/microsoft-365-docs/commits/789446117dbe21a5489d0a23e5703ae8fe8127e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208051638006787-9338/BuildReport?accessString=2e32cba91f6ef189dda7caf78de18c49693fa98d5401cc2ac928173c87f78ff4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 16:41 UTC, opbld30 commented
Docs Build status updates of commit _[119f1eb](https://github.com/msbemba/microsoft-365-docs/commits/119f1eb731c0d5b7dce45f9d91c1c93518fafa17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md) | :bulb:Suggestion | | [Details](#user-content-4d5e65accc54c0d14adec5d7c51a84ad-edcf7599)

<a id="4d5e65accc54c0d14adec5d7c51a84ad-edcf7599"></a>
### [microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md)
 - **Line 28, Column 150**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/defender/advanced-hunting-migrate-from-mde?view=o365-worldwide#map-devicealertevents-table`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208051638083300-9338/BuildReport?accessString=d8828e367badab836ac88b83e280e8f4c7921304fe8b9a96ef6f0b4abfc3bbf7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-06 09:29 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md
> +> The `AlertInfo` and `AlertEvidence` tables replace the `DeviceAlertEvents` table in the Microsoft Defender for Endpoint schema. To learn more, see [Map DeviceAlertEvents Table](/microsoft-365/defen
```suggestion
> The `AlertInfo` and `AlertEvidence` tables replace the `DeviceAlertEvents` table in the Microsoft Defender for Endpoint schema. To learn more, see [Map DeviceAlertEvents Table](/microsoft-365/defender/advanced-hunting-migrate-from-mde?view=o365-worldwide#map-devicealertevents-table).
```

2022-08-06 09:29 UTC, JohanFreelancer9 approved these changes

2022-08-08 08:41 UTC, opbld33 commented
Docs Build status updates of commit _[cd8deb9](https://github.com/msbemba/microsoft-365-docs/commits/cd8deb9b79a47ecb3c93e7177d68295482972f1b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 11:22 UTC, yogkumgit commented
@tiburd Kindly guide.

2022-08-08 14:05 UTC, tiburd commented
close > reopen

2022-08-08 14:06 UTC, msbemba commented
Thank you @tiburd

2022-08-08 14:07 UTC, opbld30 commented
Docs Build status updates of commit _[cd8deb9](https://github.com/msbemba/microsoft-365-docs/commits/cd8deb9b79a47ecb3c93e7177d68295482972f1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md) | :bulb:Suggestion | | [Details](#user-content-4d5e65accc54c0d14adec5d7c51a84ad-9cccabe5)

<a id="4d5e65accc54c0d14adec5d7c51a84ad-9cccabe5"></a>
### [microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md)
 - **Line 28, Column 150**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/defender/advanced-hunting-migrate-from-mde?view=o365-worldwide#map-devicealertevents-table`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081405343920-9338/BuildReport?accessString=4efe081fc8d7450b5a68075c9fd68a24732f5a117547bba9e4cbf566f572aee7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 14:10 UTC, opbld32 commented
Docs Build status updates of commit _[cd8deb9](https://github.com/msbemba/microsoft-365-docs/commits/cd8deb9b79a47ecb3c93e7177d68295482972f1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md) | :bulb:Suggestion | | [Details](#user-content-4d5e65accc54c0d14adec5d7c51a84ad-e1137e76)

<a id="4d5e65accc54c0d14adec5d7c51a84ad-e1137e76"></a>
### [microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md)
 - **Line 28, Column 150**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /microsoft-365/defender/advanced-hunting-migrate-from-mde?view=o365-worldwide#map-devicealertevents-table`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081406075802-9338/BuildReport?accessString=ac6e1b5aa6c40db5cd4bbab3388e23062706bf63cc9d29a0ac67c555d9690dd7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 14:13 UTC, tiburd commented
@msbemba 
This PR can be merged because the validation status = passed.

However, because the suggestion does not affect the technical accuracy, do you want to fix it? Will the bookmark (#map-devicealters-table) work if you remove the view parameter (?view=o365-worldwide)?

2022-08-08 14:17 UTC, msbemba commented
> @msbemba This PR can be merged because the validation status = passed.
> 
> However, because the suggestion does not affect the technical accuracy, do you want to fix it? Will the bookmark (#map-devicealters-table) work if you remove the view parameter (?view=o365-worldwide)?

Yes, @tiburd  I just fixed that part of the URL.

2022-08-08 14:17 UTC, opbld30 commented
Docs Build status updates of commit _[526dd57](https://github.com/msbemba/microsoft-365-docs/commits/526dd576c1a7ea13e6a126bd7155b65b9888e3cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081416465052-9338/BuildReport?accessString=21105b0903693271c189b027ac4d77952f72d30dff0737d31681e3fbf8646444).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 15:50 UTC, tiburd commented
@msbemba - thanks!
@yogkumgit - merging :)

2022-08-08 15:52 UTC, tiburd commented
reviewed + checked links. merging.

2022-08-08 15:52 UTC, merged

2022-08-08 15:55 UTC, opbld31 commented
Docs Build status updates of commit _[526dd57](https://github.com/msbemba/microsoft-365-docs/commits/526dd576c1a7ea13e6a126bd7155b65b9888e3cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1151/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081552551084-9338/BuildReport?accessString=89560fce81dfeb4289a3f14831d0a5a8f892371833b6ba0575c0a062200722ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>