Update microsoft-365-overview.md
MicrosoftDocs/microsoft-365-docs pull request #9359
Opened 2022-08-08 13:54 UTC by msbemba

Changed link for M365 business premium as it was routing to admin center help

2022-08-08 13:54 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-08 13:54 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9286

2022-08-08 13:56 UTC, opbld33 commented
Docs Build status updates of commit _[ad9b3e0](https://github.com/msbemba/microsoft-365-docs/commits/ad9b3e0a9ea7e53f011943ee42971bdb98cba8f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1159/microsoft-365/enterprise/microsoft-365-overview.md) | :bulb:Suggestion | | [Details](#user-content-a8c32d11cb3494a0fccba330a3a32123-a9585596)

<a id="a8c32d11cb3494a0fccba330a3a32123-a9585596"></a>
### [microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1159/microsoft-365/enterprise/microsoft-365-overview.md)
 - **Line 118, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com//microsoft-365/business/' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081354052237-9359/BuildReport?accessString=2dfe748647359437200fbf33c696485ef079041525dbce8e728af60567d842f4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 14:46 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/microsoft-365-overview.md
> +- [Microsoft 365 Business Premium](https://docs.microsoft.com//microsoft-365/business/)
```suggestion
- [Microsoft 365 Business Premium](/microsoft-365/business/)
```

2022-08-08 14:46 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-08 15:05 UTC, opbld30 commented
Docs Build status updates of commit _[020a64b](https://github.com/msbemba/microsoft-365-docs/commits/020a64b2a00d12efbae3eb5ca9e8517c3b7e3307)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1159/microsoft-365/enterprise/microsoft-365-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081502550940-9359/BuildReport?accessString=51122caaa417197292cea8eb394953d139b59a36d5769a2c878042f0cf50e4da).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 15:23 UTC, JohanFreelancer9 approved these changes

2022-08-08 16:28 UTC, denisebmsft approved these changes
Thank you @msbemba

2022-08-08 16:29 UTC, opbld31 commented
Docs Build status updates of commit _[5d61e32](https://github.com/msbemba/microsoft-365-docs/commits/5d61e323bcbe85ce85fcc74c1da30f77a69a9ffd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1159/microsoft-365/enterprise/microsoft-365-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081628263118-9359/BuildReport?accessString=166d7e6611f60cc3d1cfd0c4f88c9d7d31e80a942011a1f5b04f26ec5b977b79).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 16:32 UTC, opbld30 commented
Docs Build status updates of commit _[fec5703](https://github.com/msbemba/microsoft-365-docs/commits/fec57039a7df92e1f2cba4aec986f8584c0ee8eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1159/microsoft-365/enterprise/microsoft-365-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081628521077-9359/BuildReport?accessString=ba0474d0990de425613dd748964c639dc45484e62c9d4bc3747fdd704abdd5ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 16:35 UTC, opbld32 commented
Docs Build status updates of commit _[c1bd62a](https://github.com/msbemba/microsoft-365-docs/commits/c1bd62a4dbc8fda7baf4451aba346a770746356c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1159/microsoft-365/enterprise/microsoft-365-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208081631483269-9359/BuildReport?accessString=ef2add10cac0900d08a70e634d4b8c074c5dd89eb946a8232ae8c628b6d00773).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 14:03 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-08-12 19:29 UTC, opbld33 commented
Docs Build status updates of commit _[fc28333](https://github.com/msbemba/microsoft-365-docs/commits/fc2833316a4749a1b1182b76b4fe952dc97f340d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1159/microsoft-365/enterprise/microsoft-365-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208121928247718-9359/BuildReport?accessString=a52d169482e1443c13c47cd97895bb8d59ca399c67a58cf7a62e717ae025fc44).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 19:29 UTC, merged