Update experience-insights-dashboard.md
MicrosoftDocs/microsoft-365-docs pull request #9381
Opened 2022-08-09 17:41 UTC by msbemba

Added information about requirement fo 20K plus seats

Reference # https://techcommunity.microsoft.com/t5/microsoft-365-blog/introducing-preview-of-experience-insights-for-microsoft-365/ba-p/3574383

Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9373

2022-08-09 17:41 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-09 17:42 UTC, opbld31 commented
Docs Build status updates of commit _[af63d73](https://github.com/msbemba/microsoft-365-docs/commits/af63d73f3c91d595fa9122ed13dc34b726346adf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1163/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-e22e649b)

<a id="87453c5c6aa1d6417d44c75e598194e7-e22e649b"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1163/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208091741092749-9381/BuildReport?accessString=fa299ee3c8a184de3788b471b5582d4b0d2d9ded75b1c13ac1ef1223488806c8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 06:42 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/experience-insights-dashboard.md
> +Experience insights is optimized for organizations with higher volumes of data so is only available for organizations with 20,000 plus seats. Microsoft are working on bringing the experience to small
```suggestion
Experience insights is optimized for organizations with higher volumes of data so is only available for organizations with 20,000 plus seats. We are working on bringing the experience to smaller organizations in the future. This information and data on the dashboard will help you better understand and improve your users' experience with Microsoft 365. The dashboard shows you data across usage and user sentiment and helps give you a fuller picture of your users' overall experience. You can drill down into specific information such as feature usage for certain apps, exact feedback and Net Promoter Score (NPS) comments, and top help articles viewed by users in your organization. This info can help you identify opportunities to improve user’s Microsoft 365 products and app experiences in your organization.
```

2022-08-10 06:44 UTC, JohanFreelancer9 requested changes
Copy review - a few minor additional changes, please.

2022-08-10 08:46 UTC, opbld31 commented
Docs Build status updates of commit _[29b4e92](https://github.com/msbemba/microsoft-365-docs/commits/29b4e92b7153a8c46f2a91fc558ef1fe80437cc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1163/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-461e7ca5)

<a id="87453c5c6aa1d6417d44c75e598194e7-461e7ca5"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1163/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208100844258766-9381/BuildReport?accessString=252f65e9671596936e8d616ba7bc7967465be121a51745fb89d9c05c9f9eb1f5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 11:07 UTC, JohanFreelancer9 approved these changes

2022-08-10 15:31 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-08-29 19:34 UTC, opbld32 commented
Docs Build status updates of commit _[782be07](https://github.com/msbemba/microsoft-365-docs/commits/782be07bf88d3f6c1bbb2e5a0bbcbf7d4089f7e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1163/microsoft-365/admin/misc/experience-insights-dashboard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208291932518497-9381/BuildReport?accessString=f5367d78fc53ed823dcbb6b88a0501c3ec56fd2c548497718b0dc0ae529abfc0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 19:36 UTC, merged