Update experience-insights-dashboard.md
MicrosoftDocs/microsoft-365-docs pull request #9382
Opened 2022-08-09 17:54 UTC by msbemba

Added New links for all additional resources

Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9372

2022-08-09 17:55 UTC, opbld30 commented
Docs Build status updates of commit _[81db03a](https://github.com/msbemba/microsoft-365-docs/commits/81db03a7aad4a66a0aa6db15524421fcea60298f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-6f55cec3)

<a id="87453c5c6aa1d6417d44c75e598194e7-6f55cec3"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````
 - **Line 93, Column 360**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/learn/paths/m365-service-adoption/' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208091754041027-9382/BuildReport?accessString=151186d3af60c5e3807d3d2d295139561a122f284d298fbff147f376c0090790).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 08:28 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/experience-insights-dashboard.md
> +In this introductory course, you'll learn the six critical elements to drive adoption of your Microsoft cloud services to deliver value to your company. This course is applicable to any size company
```suggestion
In this introductory course, you'll learn the six critical elements to drive adoption of your Microsoft cloud services to deliver value to your company. This course is applicable to any size company and uses Office 365 and Microsoft Teams as the example service to create real-world scenarios. For more information on training for adoption specialists, read, [Training for adoption specialists](/learn/paths/m365-service-adoption/)
```

2022-08-10 08:33 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/experience-insights-dashboard.md
> +Welcome to the Driving Adoption Community! Connect and discuss the latest topics and best practices in driving cloud adoption. Meet and learn from peers and Microsoft Staff and stay up to date on upc
```suggestion
Welcome to the Driving Adoption Community! Connect and discuss the latest topics and best practices in driving cloud adoption. Meet and learn from peers and Microsoft Staff and stay up to date on upcoming training, events, and our monthly Community calls. For more information, read [Driving Adoption](https://techcommunity.microsoft.com/t5/driving-adoption/ct-p/DrivingAdoption).
```

2022-08-10 08:36 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/experience-insights-dashboard.md
> +Use our resources to go from inspiration to execution with our productivity cloud. Get started, experiment with our services, and onboard employees at scale while being confident that you are improvi
```suggestion
Use our resources to go from inspiration to execution with our productivity cloud. Get started, experiment with our services, and onboard employees at scale while being confident that you are improving the employee experience. For more information read, [Drive value with
Microsoft 365 adoption tools](https://adoption.microsoft.com)
```

2022-08-10 08:36 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-10 08:44 UTC, opbld32 commented
Docs Build status updates of commit _[746b3fc](https://github.com/msbemba/microsoft-365-docs/commits/746b3fc2670256fa81fef7c2426553f21175697b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-57558d17)

<a id="87453c5c6aa1d6417d44c75e598194e7-57558d17"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````
 - **Line 93, Column 360**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/learn/paths/m365-service-adoption/' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208100842100685-9382/BuildReport?accessString=aa8352a5dfda160f8a89a392d7d272fe7c2aad39bf067aac5f3011b943fc9459).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 08:47 UTC, opbld32 commented
Docs Build status updates of commit _[a8b7dc5](https://github.com/msbemba/microsoft-365-docs/commits/a8b7dc5da9ab61d8bd1ee6f983a3f092538a26a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-8e2b2990)

<a id="87453c5c6aa1d6417d44c75e598194e7-8e2b2990"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208100842196290-9382/BuildReport?accessString=56eae3f133ee0626f28c9966fad284cf63393ebbe6b6958df4dee6e6e77f37ff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 11:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/experience-insights-dashboard.md
> +Use our resources to go from inspiration to execution with our productivity cloud. Get started, experiment with our services, and onboard employees at scale while being confident that you are improvi
```suggestion
Use our resources to go from inspiration to execution with our productivity cloud. Get started, experiment with our services, and onboard employees at scale while being confident that you are improving the employee experience. For more information, read [Drive value with Microsoft 365 adoption tools](https://adoption.microsoft.com).
```

2022-08-10 11:18 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, one more, please.

2022-08-10 11:49 UTC, opbld32 commented
Docs Build status updates of commit _[3e15555](https://github.com/msbemba/microsoft-365-docs/commits/3e155550ff5da8ea06cb8572f33b0cbf3263cc46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-0b410943)

<a id="87453c5c6aa1d6417d44c75e598194e7-0b410943"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208101149022351-9382/BuildReport?accessString=8f46d0bf46bfe48bd352757cd6a72d9801d73fd7f40f387de1e7a026f03e9ed0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 14:32 UTC, JohanFreelancer9 approved these changes

2022-08-10 15:33 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-08-17 06:44 UTC, opbld31 commented
Docs Build status updates of commit _[564fd62](https://github.com/msbemba/microsoft-365-docs/commits/564fd62a80aa9e35b8fb3b98b71eb0846b8dba26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-b920d4c1)

<a id="87453c5c6aa1d6417d44c75e598194e7-b920d4c1"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208170642273674-9382/BuildReport?accessString=60f7a75927f25776b4cbb04a88c6fbf7cba7d5adf4ef76b509a5bb83a767b764).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 03:49 UTC, yogkumgit commented
@kwekuako it is not merged yet. 
cc: @tiburd

2022-08-18 16:40 UTC, tiburd commented on microsoft-365/admin/misc/experience-insights-dashboard.md
> +In this introductory course, you'll learn the six critical elements to drive adoption of your Microsoft cloud services to deliver value to your company. This course is applicable to any size company
```suggestion
In this introductory course, you'll learn the six critical elements to drive adoption of your Microsoft cloud services to deliver value to your company. This course is applicable to any size company and uses Office 365 and Microsoft Teams as the example service to create real-world scenarios. For more information about training for adoption specialists, read [Use the Microsoft service adoption framework to drive adoption in your enterprise](/learn/paths/m365-service-adoption).
```

2022-08-18 16:43 UTC, opbld32 commented
Docs Build status updates of commit _[75ec0e5](https://github.com/msbemba/microsoft-365-docs/commits/75ec0e54e40a52ff6e5155a5f07147df825d2cd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-6192268d)

<a id="87453c5c6aa1d6417d44c75e598194e7-6192268d"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208181640364998-9382/BuildReport?accessString=77d18f2efda680490da6d7ac4afc2566944714f9f3c39b52bc947b167eb431b2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 16:45 UTC, opbld33 commented
Docs Build status updates of commit _[08757df](https://github.com/msbemba/microsoft-365-docs/commits/08757dfa83d741f663b11443bc88360aabf405ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :bulb:Suggestion | | [Details](#user-content-87453c5c6aa1d6417d44c75e598194e7-5b1fe62a)

<a id="87453c5c6aa1d6417d44c75e598194e7-5b1fe62a"></a>
### [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md)
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get a periodic report of how people in your organization are using Microsoft 365 services and drill into each chart for more insights.' is duplicated in 'admin/activity-reports/activity-reports.md(25,14)', 'admin/misc/experience-insights-dashboard.md(11,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208181641429271-9382/BuildReport?accessString=840dead30e825025106be1121d08481659e55033b28002d91b5ecea478b5ebc1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 16:50 UTC, opbld30 commented
Docs Build status updates of commit _[4f543b6](https://github.com/msbemba/microsoft-365-docs/commits/4f543b643d135ada46ff469c70f08f419136a4d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208181649401275-9382/BuildReport?accessString=7ea4a759dc4be80600668a512378edb491eab6f201de424204c0bafe590f88dd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 16:55 UTC, opbld32 commented
Docs Build status updates of commit _[901fb90](https://github.com/msbemba/microsoft-365-docs/commits/901fb9022e96f5e5ff4d09d6dbd877a3a39a9805)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208181654167970-9382/BuildReport?accessString=a66664c272232bfca5176e1754664754992e0b8e358728fa64b20550077be03c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 17:53 UTC, opbld30 commented
Docs Build status updates of commit _[5b532e0](https://github.com/msbemba/microsoft-365-docs/commits/5b532e031a580c385091a3a02187f4406371b355)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1164/microsoft-365/admin/misc/experience-insights-dashboard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208181751246106-9382/BuildReport?accessString=9634dad623c51d0cff708c3a93ac54910005000e00f781f77cbff61d1c8292f4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 17:54 UTC, merged