Update use-arc-exceptions-to-mark-trusted-arc-senders.md
MicrosoftDocs/microsoft-365-docs pull request #9383
Opened 2022-08-09 18:21 UTC by msbemba

Made changes to the Authenticated Received Chain (ARC) in Microsoft 365 Defender for Office section

Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9356

2022-08-09 18:22 UTC, opbld32 commented
Docs Build status updates of commit _[f05ec54](https://github.com/msbemba/microsoft-365-docs/commits/f05ec548e78be37ebdfec05f347e8cad7b694dd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1165/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208091821589958-9383/BuildReport?accessString=2787f45ce4b09b263bd9d58db071cfde80fa84d0fe0cb99319e7e6b73705c8ff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 08:47 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md
> +Services that modify content during transport of the message before delivery to your organization, can invalidate the DKIM email signature and affect the authentication of the message. When these int
```suggestion
Services that modify content during transport of the message before delivery to your organization can invalidate the DKIM email signature and affect the authentication of the message. When these intermediary services perform such actions, they can use ARC to provide details of the original authentication before the modifications occurred, which your organization can then trust to help with authenticating the message.  
```

2022-08-10 08:48 UTC, JohanFreelancer9 requested changes
Copy recview.

2022-08-10 15:36 UTC, yogkumgit commented
@msbemba

2022-08-10 16:59 UTC, opbld31 commented
Docs Build status updates of commit _[2e58d7c](https://github.com/msbemba/microsoft-365-docs/commits/2e58d7cb3a1a240227cd2e100154c92e319c9bde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1165/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208101657113654-9383/BuildReport?accessString=d89f8ceb8de873a39fa6e74ab0d2d0f4cc004eec0b03976bda371199930ec01a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 05:07 UTC, JohanFreelancer9 approved these changes

2022-08-11 11:33 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2022-08-23 19:43 UTC, opbld31 commented
Docs Build status updates of commit _[8f7c90c](https://github.com/msbemba/microsoft-365-docs/commits/8f7c90c85f77bb5b6a081d6b91067d0d8012c205)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1165/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208231941023239-9383/BuildReport?accessString=56b211dc00e321d124a16e31b2b4b979e465362ef67bf866150bf117e558d985).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 19:47 UTC, opbld33 commented
Docs Build status updates of commit _[0b9a635](https://github.com/msbemba/microsoft-365-docs/commits/0b9a6350bce3a8a24d7b08d27808f7c58588f31d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1165/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208231941176233-9383/BuildReport?accessString=343f7a226cc04355af3f357f6a6ec0d922edb4551cd30792eebd9bac4348815d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 19:53 UTC, merged