Update office-365-user-email-settings.md
MicrosoftDocs/microsoft-365-docs pull request #9421
Opened 2022-08-12 13:49 UTC by msbemba

Added a new para about how to access the Mail pane.

Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9404

2022-08-12 13:50 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-12 13:51 UTC, opbld32 commented
Docs Build status updates of commit _[60592e9](https://github.com/msbemba/microsoft-365-docs/commits/60592e9b3b617cfee085ffb88c2689a742db2c8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/email/office-365-user-email-settings.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1171/microsoft-365/admin/email/office-365-user-email-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208121350007259-9421/BuildReport?accessString=e695038fd6af794476998a49d5c15149de26655c25b2506477afc2f24566107b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 16:18 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/office-365-user-email-settings.md
> +
```suggestion
2. Go to **Users** > **Active users** and select the user for whom you would like to manage email settings.
3. In the new pane, select **Mail** to manage email settigs.
```

2022-08-12 16:19 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-12 16:59 UTC, opbld31 commented
Docs Build status updates of commit _[e208b14](https://github.com/msbemba/microsoft-365-docs/commits/e208b1468e09d18eef4483452d0fc17b8192c133)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/email/office-365-user-email-settings.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1171/microsoft-365/admin/email/office-365-user-email-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208121658310209-9421/BuildReport?accessString=633aca956fa996c9d723c8bfbba75a57940f26e36dd9833b080e8f46c57ad190).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-13 07:35 UTC, JohanFreelancer9 commented on microsoft-365/admin/email/office-365-user-email-settings.md
> +3. In the new pane, select **Mail** to manage email settigs.
```suggestion
3. In the new pane, select **Mail** to manage email settings.
```

2022-08-13 07:36 UTC, JohanFreelancer9 requested changes
@msbemba, one more, please.

2022-08-13 07:42 UTC, opbld32 commented
Docs Build status updates of commit _[11a30f1](https://github.com/msbemba/microsoft-365-docs/commits/11a30f14c4fd5e1c2989ad18657604f400f88270)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/email/office-365-user-email-settings.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1171/microsoft-365/admin/email/office-365-user-email-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208130741141497-9421/BuildReport?accessString=dc9b3bf221e81993972083fb61c212bbd81175bc3ae65b1905450cc1691fda4f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-13 07:47 UTC, JohanFreelancer9 approved these changes

2022-08-15 05:15 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-08-22 04:44 UTC, opbld30 commented
Docs Build status updates of commit _[fa562be](https://github.com/msbemba/microsoft-365-docs/commits/fa562beee03f9ba51dd2d67ebdf12b56a4a2f377)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/email/office-365-user-email-settings.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1171/microsoft-365/admin/email/office-365-user-email-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208220441501859-9421/BuildReport?accessString=ead3639889316ceac064b2834ace1387d29a854149e03fcba86d2d741e2e4230).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 14:46 UTC, yogkumgit commented
@kwekuako

2022-08-29 19:35 UTC, opbld30 commented
Docs Build status updates of commit _[d1fb02e](https://github.com/msbemba/microsoft-365-docs/commits/d1fb02e6d901518bcd54e0cfd9d5ea90a4591488)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/email/office-365-user-email-settings.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1171/microsoft-365/admin/email/office-365-user-email-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208291932064664-9421/BuildReport?accessString=c74d9cfb82f59ce46dbc67aa6c4cbeaf8e0035a2eda7629e8339339768488824).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 19:39 UTC, opbld33 commented
Docs Build status updates of commit _[4820939](https://github.com/msbemba/microsoft-365-docs/commits/48209396f50396f3525bc90617464852b9875692)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/email/office-365-user-email-settings.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1171/microsoft-365/admin/email/office-365-user-email-settings.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208291937054013-9421/BuildReport?accessString=bb00e26054778877da91dfa69b6650a5089dc3d4eb65d428fe6e3974b8113d8d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 19:40 UTC, merged