Update tls-1.0-and-1.1-deprecation-for-office-365.md
MicrosoftDocs/microsoft-365-docs pull request #9444
Opened 2022-08-16 16:49 UTC by qiufasheng

Updated current TLS 1.2 enforcement status in WW, and included target date for Gallatin.

2022-08-16 16:50 UTC, opbld31 commented
Docs Build status updates of commit _[7671513](https://github.com/qiufasheng/microsoft-365-docs/commits/76715138595ffdf1f6e7bc1c2e190e2b05657f01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/qiufasheng/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208161649091469-9444/BuildReport?accessString=8dd749424e08e46bc3d430dcdf64c91567a1d5e75e76ab2ef0dc4b9a14bb087c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 18:14 UTC, WorkShay commented
@***@***.******@***.*** ***@***.***>

Hey folks,

Can you both figure out what’s going on and make sure these PRs aren’t getting assigned to me anymore? I don’t remember the login to by Github anymore (yes, I know) so I can’t remove these anyways.

Best,
Shayna

Pronouns: they/them<https://www.mypronouns.org/they-them#:~:text=A%20person%20who%20goes%20by%20%E2%80%9C%20they%20%E2%80%9D,theirs.%20I%20like%20both%20them%20and%20their%20ideas.%E2%80%9D> || she/her<https://www.mypronouns.org/she-her#:~:text=A%20person%20who%20goes%20by%20%E2%80%9C%20she%20%E2%80%9D,hers.%20I%20like%20both%20her%20and%20her%20ideas.%E2%80%9D>
Name pronunciation: [SHā-nah]

From: Denise Vangel-MSFT ***@***.***>
Sent: Tuesday, August 16, 2022 11:02 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Shayna Mehta ***@***.***>; Assign ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update tls-1.0-and-1.1-deprecation-for-office-365.md (PR #9444)


Assigned #9444<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F9444&data=05%7C01%7CShayna.Mehta%40microsoft.com%7C19528853b6c847e196f708da7fb160c4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637962697063790744%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2rqEAipv8ds%2FMGhX1Z3wN2GZ004xtbO6bQXn%2FF3XQR0%3D&reserved=0> to @WorkShay<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWorkShay&data=05%7C01%7CShayna.Mehta%40microsoft.com%7C19528853b6c847e196f708da7fb160c4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637962697063790744%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WJtf5Ueq0KRedrPIME86AfIRvYx9o2MCZ0zXfOKRups%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F9444%23event-7199378356&data=05%7C01%7CShayna.Mehta%40microsoft.com%7C19528853b6c847e196f708da7fb160c4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637962697063790744%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8kuV3m6GQGVqNT6a9tqL8Ijlwl8w90JIfGTes23TPuM%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQJPS6ZQ2DZOTOQ7KHVHGDLVZPJQPANCNFSM56WQ4V4A&data=05%7C01%7CShayna.Mehta%40microsoft.com%7C19528853b6c847e196f708da7fb160c4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637962697063946982%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vIWr3Ts3LbJKh6VyXkX6A8Rq2Wo%2B%2F6jbDb8MmFJvmUA%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2022-08-17 06:24 UTC, JohanFreelancer9 commented on microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md
> +For Microsoft 365 offered by 21 Vianet, TLS 1.0/1.1 will be disabled on June 30, 2023.
```suggestion
For Microsoft 365 operated by 21 Vianet, TLS 1.0/1.1 will be disabled on June 30, 2023.
```

2022-08-17 06:24 UTC, JohanFreelancer9 requested changes
Copy review - @qiufasheng, kindly commit the suggested change. Many thanks.

2022-08-18 00:15 UTC, opbld31 commented
Docs Build status updates of commit _[7bf94a8](https://github.com/qiufasheng/microsoft-365-docs/commits/7bf94a860e829f5cbcbc2d4c6cfe8e3d09d9c102)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/qiufasheng/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208180014433080-9444/BuildReport?accessString=34b179905e41c03c738c4021db8c81c110db0206ffcf05fb92ef22a5e8e96cd4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 00:16 UTC, qiufasheng commented
@JohanFreelancer9, committed change based on your suggestion. Thanks!

2022-08-18 00:18 UTC, opbld31 commented
Docs Build status updates of commit _[7bf94a8](https://github.com/qiufasheng/microsoft-365-docs/commits/7bf94a860e829f5cbcbc2d4c6cfe8e3d09d9c102)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/qiufasheng/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208180017023646-9444/BuildReport?accessString=3514573c7303381636c889ed1185411b81ce8078025cda533f4cd1ca0f14c1c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 09:46 UTC, JohanFreelancer9 approved these changes

2022-08-18 22:14 UTC, opbld30 commented
Docs Build status updates of commit _[6935f3d](https://github.com/qiufasheng/microsoft-365-docs/commits/6935f3d79599308c748de2808527682af7e15870)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/qiufasheng/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208182211108534-9444/BuildReport?accessString=76a213cd3ae4e564db1c02ae1d2a0d69956f154eb3e29c475a1dca14becf09e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 21:42 UTC, opbld33 commented
Docs Build status updates of commit _[b0fd06b](https://github.com/qiufasheng/microsoft-365-docs/commits/b0fd06b4b3350debd81a62536c227c33bce8623b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/qiufasheng/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208192142002260-9444/BuildReport?accessString=f9a3082551ce03c00dd4376c21ae91850b5e08d95d226bbd7761f2befafaa4b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 21:45 UTC, merged