Update ome-message-access-logs.md
MicrosoftDocs/microsoft-365-docs pull request #9479
Opened 2022-08-22 03:18 UTC by msbemba

the -enableportaltracking logs is only available in v2

2022-08-22 03:18 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-22 03:18 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9438

2022-08-22 03:21 UTC, opbld31 commented
Docs Build status updates of commit _[92ffdd2](https://github.com/msbemba/microsoft-365-docs/commits/92ffdd29be2cf5194eb637cff77fd4a8626b6fc2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/ome-message-access-logs.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1179/microsoft-365/compliance/ome-message-access-logs.md) | :bulb:Suggestion | | [Details](#user-content-a28a5bf73f980c89166e51bb52ce73a9-2c98dad5)

<a id="a28a5bf73f980c89166e51bb52ce73a9-2c98dad5"></a>
### [microsoft-365/compliance/ome-message-access-logs.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1179/microsoft-365/compliance/ome-message-access-logs.md)
 - **Line 27, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208220318304020-9479/BuildReport?accessString=022c7e02c989bf3f72532372ca4db52ced9b94aa47f523695aed894a3dd41ef0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 07:50 UTC, JohanFreelancer9 commented on microsoft-365/compliance/ome-message-access-logs.md
> +Access log can be enabled using [Exchange Online PowerShell V2 module](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell). The *-EnablePortalTrackingLogs* parameter
```suggestion
Access log can be enabled using [Exchange Online PowerShell V2 module](/powershell/exchange/connect-to-exchange-online-powershell). The *-EnablePortalTrackingLogs* parameter of Set-IrmConfiguration specifies whether to enable the audit logs of accessing the encrypted message portal. Valid values are:
```

2022-08-22 07:50 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-22 14:35 UTC, yogkumgit commented
@msbemba

2022-08-22 14:57 UTC, opbld31 commented
Docs Build status updates of commit _[9bc5c0c](https://github.com/msbemba/microsoft-365-docs/commits/9bc5c0c911b737874f097a1a8dbab41bb5041e76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/ome-message-access-logs.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1179/microsoft-365/compliance/ome-message-access-logs.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208221454409458-9479/BuildReport?accessString=7383d44a7f7a8760ec6ae5b598265ab15dd72ff88728a0abc8e3ea0ceac5c545).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 15:00 UTC, opbld30 commented
Docs Build status updates of commit _[dfe9574](https://github.com/msbemba/microsoft-365-docs/commits/dfe95747abafb58ad589dd05817878caa2811110)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/ome-message-access-logs.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1179/microsoft-365/compliance/ome-message-access-logs.md) | :bulb:Suggestion | | [Details](#user-content-a28a5bf73f980c89166e51bb52ce73a9-cda96b26)

<a id="a28a5bf73f980c89166e51bb52ce73a9-cda96b26"></a>
### [microsoft-365/compliance/ome-message-access-logs.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1179/microsoft-365/compliance/ome-message-access-logs.md)
 - **Line 27, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208221456555319-9479/BuildReport?accessString=5748cbc0aac68d966329330a0909ad2a4f01b211039682b75f07f03043c99533).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 16:07 UTC, JohanFreelancer9 approved these changes

2022-08-23 10:59 UTC, yogkumgit commented
@v-tophillips Please merge this PR. Thanks

2022-08-23 18:04 UTC, v-tophillips approved these changes

2022-08-23 18:05 UTC, opbld31 commented
Docs Build status updates of commit _[9cba69f](https://github.com/msbemba/microsoft-365-docs/commits/9cba69f66492e5d54916c3a458dc2661077a5891)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/ome-message-access-logs.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1179/microsoft-365/compliance/ome-message-access-logs.md) | :bulb:Suggestion | | [Details](#user-content-a28a5bf73f980c89166e51bb52ce73a9-9153381e)

<a id="a28a5bf73f980c89166e51bb52ce73a9-9153381e"></a>
### [microsoft-365/compliance/ome-message-access-logs.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1179/microsoft-365/compliance/ome-message-access-logs.md)
 - **Line 27, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208231804350348-9479/BuildReport?accessString=33196aa18c9fdf0c4ece4dfa44b7115b04a0f551b25f399da03942b056cf38ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 18:05 UTC, merged