Update idle-session-timeout-web-apps.md
MicrosoftDocs/microsoft-365-docs pull request #9481
Opened 2022-08-22 04:30 UTC by msbemba

Updated per Namit's advise

2022-08-22 04:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-22 04:30 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9107

2022-08-22 04:32 UTC, opbld30 commented
Docs Build status updates of commit _[7f9397a](https://github.com/msbemba/microsoft-365-docs/commits/7f9397ae411fbe0af95ca3e2d88d0a6162ff9f23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1181/microsoft-365/admin/manage/idle-session-timeout-web-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208220430348149-9481/BuildReport?accessString=aa7a8c7ca45f9dae1e0392513c3b5bb2a97a5302edc7f6bebdf3004962bd841f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 08:42 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/idle-session-timeout-web-apps.md
> +    - If they're on a managed device (one that is compliant or joined to a domain) and using a supported browser like Microsoft Edge or Google Chrome (with the [Windows Accounts extension](https://ch
```suggestion
    - If they get single sign-on (SSO) into the web app from the device joined account.
    - If they selected **Stay signed in** at the time of sign-in. For more info on hiding this option for your organization, see [Add branding to your organization's sign-in page](/azure/active-directory/fundamentals/customize-branding).
    - If they're on a managed device (one that is compliant or joined to a domain) and using a supported browser like Microsoft Edge or Google Chrome (with the [Windows Accounts extension](https://chrome.google.com/webstore/detail/windows-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji)).
```

2022-08-22 08:43 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/idle-session-timeout-web-apps.md
> +By default, idle session timeout feature triggers on all device types if the other conditions are met. For this feature to trigger only on an unmanaged device, an eligible Azure AD Premium P1 or P2 s
```suggestion
By default, the idle session timeout feature triggers on all device types if the other conditions are met. For this feature to trigger only on an unmanaged device, an eligible Azure AD Premium P1 or P2 subscription is required. You'll also need to add a Conditional Access policy in the Azure AD admin center.
```

2022-08-22 08:44 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-22 09:57 UTC, opbld33 commented
Docs Build status updates of commit _[ef84883](https://github.com/msbemba/microsoft-365-docs/commits/ef848839476d91609311a8c3e436b5153444837b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1181/microsoft-365/admin/manage/idle-session-timeout-web-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208220954438305-9481/BuildReport?accessString=030db372e6194d2878b79fdee58b685288bcd3f7db51b242d1aa00c357cb7cba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 09:58 UTC, opbld31 commented
Docs Build status updates of commit _[c085dc4](https://github.com/msbemba/microsoft-365-docs/commits/c085dc469deb90670f25172a1512a7a885192352)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1181/microsoft-365/admin/manage/idle-session-timeout-web-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208220954518949-9481/BuildReport?accessString=603e5de2cdf123bba22f103a2760af58bee2949b85ca349dd8b41ee982464389).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 14:04 UTC, JohanFreelancer9 approved these changes

2022-08-23 11:27 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-08-23 13:08 UTC, opbld31 commented
Docs Build status updates of commit _[1a6238e](https://github.com/msbemba/microsoft-365-docs/commits/1a6238ebbdc425efeb982734b5a628eff6d936d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1181/microsoft-365/admin/manage/idle-session-timeout-web-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208231307245272-9481/BuildReport?accessString=427a94c59c5d51334c2253a3682c64f617823fbb180de908be25e628ad8a56fd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 13:09 UTC, merged