Update onboard-windows-server.md
MicrosoftDocs/microsoft-365-docs pull request #9494
Opened 2022-08-23 15:28 UTC by msbemba

Servers can be onboarded through SCCM (2207 now even supports onboarding with Unified Agent), local script, GP/Group Policy script, Defender for Cloud integration etc.
updated/removed the note

2022-08-23 15:28 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-23 15:29 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9466

2022-08-23 15:31 UTC, opbld32 commented
Docs Build status updates of commit _[fbfc2d8](https://github.com/msbemba/microsoft-365-docs/commits/fbfc2d89a0c646b512a2bfd071b99470403d8219)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1185/microsoft-365/security/defender-endpoint/onboard-windows-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208231528362147-9494/BuildReport?accessString=ce8c82a9d4957e55d6fded0c489340b5456676d6e26f6cc88f8b50df3da1e201).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 04:58 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/onboard-windows-server.md
```suggestion
```

2022-08-24 04:58 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-24 06:23 UTC, opbld30 commented
Docs Build status updates of commit _[c1d3152](https://github.com/msbemba/microsoft-365-docs/commits/c1d3152facb7e12cf59ed46fc9c738b0c414fc35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1185/microsoft-365/security/defender-endpoint/onboard-windows-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208240622091037-9494/BuildReport?accessString=6f3cf46856e72bd23106925b2815d5a91aa3913036a1ef9efe1098aacac5d6d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 10:26 UTC, JohanFreelancer9 approved these changes

2022-08-25 03:34 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-09-01 20:22 UTC, opbld31 commented
Docs Build status updates of commit _[093b3b4](https://github.com/msbemba/microsoft-365-docs/commits/093b3b44f52f433746bc4b73711a61413b9ba94a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1185/microsoft-365/security/defender-endpoint/onboard-windows-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209012020457770-9494/BuildReport?accessString=aa5f370142a6293d8680d318f1d071d068c7934ef85ea834055f35bbd9e1df5c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 20:26 UTC, merged