Update onboard-windows-server.md
MicrosoftDocs/microsoft-365-docs pull request #9501
Opened 2022-08-24 07:13 UTC by msbemba

Added License requirements to the top of the page 

Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9467

2022-08-24 07:13 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-24 07:16 UTC, opbld31 commented
Docs Build status updates of commit _[fb72303](https://github.com/msbemba/microsoft-365-docs/commits/fb723030d8ac32c4cdbe26ce94a21ab0c2abe1d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1186/microsoft-365/security/defender-endpoint/onboard-windows-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208240713071111-9501/BuildReport?accessString=959b59536a3313db7fd04bff32448c0c8893ecf3cb6aea55cd69f4d1ffa50873).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 10:46 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/onboard-windows-server.md
> +## License Requirement
```suggestion
## License requirement
```

2022-08-24 10:47 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/onboard-windows-server.md
> +In order to be eligible to purchase Microsoft Defender for Endpoint Server SKU, you must have already purchased a combined minimum of any of the following, Windows E5/A5, Microsoft 365 E5/A5 or Micro
```suggestion
In order to be eligible to purchase Microsoft Defender for Endpoint Server SKU, you must have already purchased a combined minimum of any of the following: Windows E5/A5, Microsoft 365 E5/A5, or Microsoft 365 E5 Security subscription licenses. For more information on licensing, see the [Product Terms](https://www.microsoft.com/licensing/terms/productoffering/MicrosoftDefenderforEndpointServer/all).
```

2022-08-24 10:47 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-24 11:04 UTC, opbld33 commented
Docs Build status updates of commit _[f42f6fb](https://github.com/msbemba/microsoft-365-docs/commits/f42f6fb952dba3b9b67769c8ba37cb4783760693)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1186/microsoft-365/security/defender-endpoint/onboard-windows-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208241102419310-9501/BuildReport?accessString=94031d6c39caa1ce4dacc0028e29ef79388a26683b3119e080ba4087859ed377).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 11:05 UTC, opbld31 commented
Docs Build status updates of commit _[78897fc](https://github.com/msbemba/microsoft-365-docs/commits/78897fca51ee0e39e1838492fbd4be6d386cb84f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1186/microsoft-365/security/defender-endpoint/onboard-windows-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208241102524502-9501/BuildReport?accessString=2248488f8289e860bc8daa4b8591bf1f455dcdc3e0898c859baddbde08427c2f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 11:33 UTC, JohanFreelancer9 approved these changes

2022-08-25 04:22 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-09-01 20:28 UTC, opbld33 commented
Docs Build status updates of commit _[1c324e1](https://github.com/msbemba/microsoft-365-docs/commits/1c324e1087ec63d2bb9f1542792c63778d7bad02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1186/microsoft-365/security/defender-endpoint/onboard-windows-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209012027313739-9501/BuildReport?accessString=d76e5bf592b6143db1a365a8d99ccafb664459bfc62d86f77dde786385c27209).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 20:29 UTC, merged