Update use-dmarc-to-validate-email.md
MicrosoftDocs/microsoft-365-docs pull request #9504
Opened 2022-08-24 07:24 UTC by msbemba

Added another line in the section to create transport rule for all users reject emails that fail org dmarc policy.

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9471

2022-08-24 07:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-24 07:26 UTC, opbld31 commented
Docs Build status updates of commit _[0515960](https://github.com/msbemba/microsoft-365-docs/commits/0515960e847e6472ad3fb7b1fd1b9f114268cf0b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1188/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208240724193282-9504/BuildReport?accessString=c4b0d3e0be653dd0abba12ca4047e2a77fb98cd0b97acf351adb1dc09af18c57).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 11:02 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md
> +- Admins create an Exchange mail flow rule (also known as a transport rule) for all users reject emails that fail your organizations DMARC Policy.
```suggestion
- Admins create an Exchange mail flow rule (also known as a transport rule) for all users for rejected emails that fail your organization's DMARC policy.
```

2022-08-24 11:02 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-25 04:22 UTC, yogkumgit commented
@msbemba

2022-09-02 10:44 UTC, yogkumgit commented
@msbemba Gentle reminder

2022-09-02 12:19 UTC, opbld32 commented
Docs Build status updates of commit _[c040d08](https://github.com/msbemba/microsoft-365-docs/commits/c040d084d4b8f86ea0ee4526c994b962826d91c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1188/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209021217257654-9504/BuildReport?accessString=9d81f8184b11de72c33535181fc292664649cf3d835c4bc0f6361fa23b05d5b6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-05 04:34 UTC, JohanFreelancer9 approved these changes

2022-09-05 09:29 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2023-09-26 01:08 UTC, chrisda commented
Too old. Aticle renamed. I had copied the one-line change into a new PR.

Closing

2023-09-26 01:08 UTC, closed without merging