Update config-setting-deploy.md
MicrosoftDocs/microsoft-365-docs pull request #952
Opened 2019-12-17 21:46 UTC by mertenar

@jaimeo adding note around the caution item that isn't explained yet

2019-12-19 00:05 UTC, mypil commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-12-19 04:40 UTC, JohanFreelancer9 commented on microsoft-365/managed-desktop/working-with-managed-desktop/config-setting-deploy.md
> +> The orange caution icon indicates there is a previous group available for deployment as it’s recommended to rollout in order.
```suggestion
> The orange caution icon indicates there is a previous group available for deployment as it’s recommended to roll out in order. 
```

2019-12-19 04:41 UTC, JohanFreelancer9 requested changes
Copy Review

2019-12-19 21:03 UTC, mypil commented
@mertenar - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-12-24 04:11 UTC, mypil commented
@jaimeo - PR has been copy edited and is ready for final review. 

Thank you.

cc: @kenwith

2020-01-06 17:04 UTC, merged