Update compliance-manager-setup.md
MicrosoftDocs/microsoft-365-docs pull request #9535
Opened 2022-08-26 11:57 UTC by msbemba

Made changes per #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9521 as the report we get doesn't actually include details of work done and no notes exist as part of the export

2022-08-26 11:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-26 11:58 UTC, opbld32 commented
Docs Build status updates of commit _[c2a5120](https://github.com/msbemba/microsoft-365-docs/commits/c2a51202c6e08225907c0f64f9aabed3b3e2a94d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/compliance-manager-setup.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1193/microsoft-365/compliance/compliance-manager-setup.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208261157176575-9535/BuildReport?accessString=c98b95be4216c8ec24d70077a5b8a67c85c58e589f45f150227f55feba54c5ab).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 15:14 UTC, JohanFreelancer9 commented on microsoft-365/compliance/compliance-manager-setup.md
> +The **Manage user history** settings help you quickly identify which users have worked with improvement actions in Compliance Manager. The identifiable user data associated with improvement actions i
```suggestion
The **Manage user history** settings help you quickly identify which users have worked with improvement actions in Compliance Manager. The identifiable user data associated with improvement actions includes the status of the improvement actions and  documents they uploaded. Understanding and retrieving this type of data may be necessary for your organization’s own compliance needs.
```

2022-08-26 15:14 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-26 15:18 UTC, opbld32 commented
Docs Build status updates of commit _[29ca55b](https://github.com/msbemba/microsoft-365-docs/commits/29ca55bad30df9679ec8db909958c439093aa44c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/compliance-manager-setup.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1193/microsoft-365/compliance/compliance-manager-setup.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208261515563676-9535/BuildReport?accessString=9afceeaf3ae90f837c62262b9bbe7d3034face4328141368387caf43a64686b7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 15:24 UTC, JohanFreelancer9 approved these changes

2022-08-29 06:31 UTC, yogkumgit commented
@chvukosw Please merge this PR. Thanks

2022-08-29 20:15 UTC, opbld33 commented
Docs Build status updates of commit _[e3c19a7](https://github.com/msbemba/microsoft-365-docs/commits/e3c19a7a0b1f10d7485b44856bb682f2403c1f2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/compliance-manager-setup.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1193/microsoft-365/compliance/compliance-manager-setup.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208292011156199-9535/BuildReport?accessString=b191777b0ae90579d107813f338d4facf8ca566aeb2af904c480c2b9e570a1df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 20:15 UTC, merged