Update test-and-deploy-microsoft-365-apps.md
MicrosoftDocs/microsoft-365-docs pull request #9537
Opened 2022-08-26 12:53 UTC by msbemba

Added a note about test deployment and what it means

2022-08-26 12:53 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-26 12:53 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9465

2022-08-26 12:55 UTC, opbld31 commented
Docs Build status updates of commit _[8e1a41b](https://github.com/msbemba/microsoft-365-docs/commits/8e1a41bfaa4199710497912de4d158efa03468d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1195/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208261253099509-9537/BuildReport?accessString=26d6eadeff0304a2291cb7d4cd269954cd25b35ec45537f4d8287db7ca054449).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 15:48 UTC, JohanFreelancer9 commented on microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md
> +> Is this a test deployment is a administrative tag to determine if the app is stll in testing Phase. It has no technical impact.
```suggestion
> _Is this a test deployment_ is an administrative tag to determine if the app is still in testing phase. It has no technical impact.
```

2022-08-26 15:48 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-26 16:14 UTC, opbld30 commented
Docs Build status updates of commit _[4d51276](https://github.com/msbemba/microsoft-365-docs/commits/4d51276a3b9655a3f1e8b9c2d1a36240c2518517)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1195/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208261613073180-9537/BuildReport?accessString=b8c2863c36cab83fefce3b1948cf4bb2851078edc901a5dc0bd2877efae3c7ee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 04:01 UTC, JohanFreelancer9 approved these changes

2022-08-29 06:42 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-10-07 11:26 UTC, yogkumgit commented
@kwekuako Gentle reminder

2022-10-07 20:16 UTC, opbld30 commented
Learn Build status updates of commit _[f547920](https://github.com/msbemba/microsoft-365-docs/commits/f5479209886db866c8b05e485d666896cbc14ff1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1195/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210072014209079-9537/BuildReport?accessString=6010e8b6ee8ee5be7d994fc22b746b51ea13de09560046a9c967360ff3c99a68).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 20:19 UTC, opbld31 commented
Learn Build status updates of commit _[b32a667](https://github.com/msbemba/microsoft-365-docs/commits/b32a6670446fe96b7ea583e89e9941462579d431)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1195/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210072017110320-9537/BuildReport?accessString=06b86da49873a8d1d7268119f67d1cd566fc89912fb36874775021a0faa9563e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 20:20 UTC, merged