Update insider-risk-management-solution-overview.md
MicrosoftDocs/microsoft-365-docs pull request #9555
Opened 2022-08-30 09:02 UTC by msbemba

Updated licensing information for Insider Risk Management

Per issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9538

2022-08-30 09:03 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-08-30 09:03 UTC, opbld33 commented
Docs Build status updates of commit _[40de157](https://github.com/msbemba/microsoft-365-docs/commits/40de157d482989d6420dd188b9b0aa337b02ac97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management-solution-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1197/microsoft-365/compliance/insider-risk-management-solution-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202208300902419397-9555/BuildReport?accessString=6f85a0f70a801bff7cc5a44a9f1de94ef0581635578a7ec7860320050bfff80b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 14:07 UTC, JohanFreelancer9 commented on microsoft-365/compliance/insider-risk-management-solution-overview.md
> +Users included in insider risk management policies must be assigned one of the licenses above.
```suggestion
Users included in insider risk management policies must be assigned one of these licenses.
```

2022-08-30 14:10 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-31 10:45 UTC, yogkumgit commented
@msbemba

2022-09-02 10:47 UTC, yogkumgit commented
@msbemba Gentle reminder

2022-09-02 12:20 UTC, opbld33 commented
Docs Build status updates of commit _[a0a84aa](https://github.com/msbemba/microsoft-365-docs/commits/a0a84aad5af940c63d7dd0f4964e05629d9de9f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management-solution-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1197/microsoft-365/compliance/insider-risk-management-solution-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209021217039245-9555/BuildReport?accessString=48da5ff89a5816fe8d04f667aecdec198c0285063b2f1289acebbca3bb3ebf64).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-05 09:28 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-05 09:30 UTC, JohanFreelancer9 approved these changes

2022-09-05 09:44 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2023-06-19 10:56 UTC, yogkumgit commented
Closing as per the comment in #9538

2023-06-19 10:56 UTC, closed without merging