Add a information about remove custom unit file.
MicrosoftDocs/microsoft-365-docs pull request #9608
Opened 2022-09-05 05:57 UTC by kash1064

Add a information about remove custom unit file before uninstall mdatp.
Some user had been confused that custom file is not removed after uninstall mdatp.

2022-09-05 05:58 UTC, opbld30 commented
Docs Build status updates of commit _[99fa823](https://github.com/kash1064/microsoft-365-docs/commits/99fa823a21fc918a9525b2fa780125dce806550b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md](https://github.com/kash1064/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209050557036106-9608/BuildReport?accessString=470417fadfeb2e1f2051a956febcf0a40ce6a8d884abdf82df2fa4d0f272e6a3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 08:50 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md
> +> To remove any additions you have made before uninstall mdatp, either delete the custom file from `/etc/systemd/system`.
```suggestion
> To remove any additions you might have made before uninstalling `mdatp`, delete the custom file from `/etc/systemd/system`.
```

2022-09-06 08:52 UTC, JohanFreelancer9 requested changes
Copy review - @kash1064, kindly commit the suggested changes. Many thanks.

2022-09-06 12:31 UTC, kash1064 commented
@JohanFreelancer9 Thanks for your suggestion.
I have committed that.

2022-09-06 12:33 UTC, opbld31 commented
Docs Build status updates of commit _[8ff2213](https://github.com/kash1064/microsoft-365-docs/commits/8ff221375adb922ea10852319d87430cc7b8a1fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md](https://github.com/kash1064/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209061230516214-9608/BuildReport?accessString=162dac9f6aca0c3423758cf8738b6bbe579591932458e16bcd3337654b56f8e2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 13:06 UTC, JohanFreelancer9 approved these changes

2022-09-07 07:58 UTC, opbld32 commented
Docs Build status updates of commit _[42fdd7d](https://github.com/kash1064/microsoft-365-docs/commits/42fdd7d84223c444565c35d1e522f7d90a0f85a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md](https://github.com/kash1064/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209070755229307-9608/BuildReport?accessString=a4beabbd658056bb9ffe23ec0d444ee373cc04622536d3bd00961c48200006ba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 07:50 UTC, opbld33 commented
Docs Build status updates of commit _[f8aa67f](https://github.com/kash1064/microsoft-365-docs/commits/f8aa67f9e59eb72fdfd8bd530bcc259b3f3a3702)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md](https://github.com/kash1064/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209090747398522-9608/BuildReport?accessString=baa2d720a6c56586e5b9b2f8d1784b167075cfb7b9530fb3253eb84010022802).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 04:27 UTC, opbld31 commented
Docs Build status updates of commit _[817178b](https://github.com/kash1064/microsoft-365-docs/commits/817178b1d8998a0855f8c1d4370d0eec259c17f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md](https://github.com/kash1064/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209120425225357-9608/BuildReport?accessString=371be44046b032631f0a99db240d24dd34d0f09690a1b80ea64d56b5361525ae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 16:47 UTC, opbld32 commented
Docs Build status updates of commit _[21b99e2](https://github.com/kash1064/microsoft-365-docs/commits/21b99e2b0bdb72894b34510db5970fdef120fe8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md](https://github.com/kash1064/microsoft-365-docs/blob/patch-1/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209161644161997-9608/BuildReport?accessString=daebbe8a10f630dd16222b19c0fe3330ca880273a81cfb9976673fad29d6f421).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 16:47 UTC, merged