Update archive-linkedin-data.md
MicrosoftDocs/microsoft-365-docs pull request #9613
Opened 2022-09-05 11:09 UTC by msbemba

added a line to Step 7 about the mailbox license requirement

2022-09-05 11:09 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-05 11:09 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9579

2022-09-05 11:11 UTC, opbld32 commented
Docs Build status updates of commit _[78efe63](https://github.com/msbemba/microsoft-365-docs/commits/78efe63e313e21b76ffb12b0f97afc3537f58dfa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/archive-linkedin-data.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1203/microsoft-365/compliance/archive-linkedin-data.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209051109260187-9613/BuildReport?accessString=a910e0dad0a51c06d376a59953ec20c237da79c256ea2a2df1a29e42f973aa69).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 03:20 UTC, JohanFreelancer9 commented on microsoft-365/compliance/archive-linkedin-data.md
> +7. On the **Choose storage location** page, click in the box, select the email address of a Microsoft 365 mailbox that the LinkedIn items will be imported to, and then click **Next**. Items are impor
```suggestion
7. On the **Choose storage location** page, click in the box, select the email address of a Microsoft 365 mailbox that the LinkedIn items will be imported to, and then click **Next**. Items are imported to the inbox folder in this mailbox. The mailbox used must have an Exchange Online Plan 1 or Plan 2 license.
```

2022-09-06 03:21 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-06 03:53 UTC, opbld30 commented
Docs Build status updates of commit _[bb55942](https://github.com/msbemba/microsoft-365-docs/commits/bb55942d1e1da99f71bafa10148b05e58188ec9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/archive-linkedin-data.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1203/microsoft-365/compliance/archive-linkedin-data.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209060347022558-9613/BuildReport?accessString=4593eb639a59b603e03a74bbaafcdd1563329619bf8ea2b0a27b0e875f8a0da6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 08:05 UTC, JohanFreelancer9 approved these changes

2022-09-06 14:51 UTC, yogkumgit commented
@v-tophillips Please merge this PR. Thanks

2022-09-06 19:11 UTC, v-tophillips approved these changes

2022-09-06 19:13 UTC, opbld31 commented
Docs Build status updates of commit _[0440161](https://github.com/msbemba/microsoft-365-docs/commits/0440161d74bea6b307726918135fcdd4397c190a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/archive-linkedin-data.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1203/microsoft-365/compliance/archive-linkedin-data.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209061912155420-9613/BuildReport?accessString=1864113e876b9b7b7e5b44b34a806e28caaf2a05adea5ef4f579776c4ab30c22).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 19:14 UTC, merged