Update activity-reports.md
MicrosoftDocs/microsoft-365-docs pull request #9614
Opened 2022-09-05 11:11 UTC by msbemba

Made changes to the ## What happens to usage data when a user account is deleted? as Closed doesn't reflect what actually happens with the account when it is deleted.

2022-09-05 11:12 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9580

2022-09-05 11:12 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-05 11:14 UTC, opbld33 commented
Docs Build status updates of commit _[29b1b67](https://github.com/msbemba/microsoft-365-docs/commits/29b1b677f5a61bf3dd07e6bd6c3e6a380fb4212e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1204/microsoft-365/admin/activity-reports/activity-reports.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209051111599931-9614/BuildReport?accessString=ca89520873aa572db14130e5d5f7ac9b16c64c1705857571b7d2a9f752f9a4b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 03:24 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/activity-reports.md
> +Whenever you delete a user's account, Microsoft will delete that user's usage data within 30 days. That user will still be included in the Activity chart totals for the periods she was active in, but
```suggestion
Whenever you delete a user's account, Microsoft will delete that user's usage data within 30 days. Deleted users will still be included in the Activity chart totals for the periods they were active in, but will not appear in the User Details table.
```

2022-09-06 03:25 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-06 03:49 UTC, opbld32 commented
Docs Build status updates of commit _[6f71d32](https://github.com/msbemba/microsoft-365-docs/commits/6f71d326ffde205836e09f72c351230b568271bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1204/microsoft-365/admin/activity-reports/activity-reports.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209060346347033-9614/BuildReport?accessString=9ebe4b71a81176c97845a6c6c54549c7689c3e6812bd5063259e335a1eea93be).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 07:46 UTC, JohanFreelancer9 approved these changes

2022-09-06 14:53 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-10-07 11:26 UTC, yogkumgit commented
@kwekuako Gentle reminder

2022-10-07 20:14 UTC, opbld31 commented
Learn Build status updates of commit _[0e271e0](https://github.com/msbemba/microsoft-365-docs/commits/0e271e09db236403767d8334ec34658d0b509f78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1204/microsoft-365/admin/activity-reports/activity-reports.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210072012575436-9614/BuildReport?accessString=55dc740421d5796d796c22acffb17e35cb5327b24b11686403912b9dbff0cb2c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 20:16 UTC, opbld32 commented
Learn Build status updates of commit _[0d4a37f](https://github.com/msbemba/microsoft-365-docs/commits/0d4a37fb2bb38a4a61871782ad26ec1c48266d2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1204/microsoft-365/admin/activity-reports/activity-reports.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210072013583288-9614/BuildReport?accessString=5f19c14ba638b69b56ac2d1a85d6984c3aae4bcdb54f5b646e9d8a2ba0b9ee94).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 20:16 UTC, merged