Update create-dns-records-at-any-dns-hosting-provider.md
MicrosoftDocs/microsoft-365-docs pull request #9616
Opened 2022-09-05 11:38 UTC by msbemba

added another line to explain how to change the email address if the users were created before

2022-09-05 11:51 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9593

2022-09-07 10:53 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-07 13:16 UTC, JohanFreelancer9 commented on microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md
> +If you have created users before and would like to change their domain, folow steps mentioned at [Change your email address to use your custom domain using the Microsoft 365 admin center](/admin/emai
```suggestion
If you have previously created users and would like to change their domain, follow the steps described in [Change your email address to use your custom domain using the Microsoft 365 admin center](/microsoft-365/admin/email/change-email-address#change-your-email-address-to-use-your-custom-domain-using-the-microsoft-365-admin-center).
```

2022-09-07 13:17 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-07 13:35 UTC, opbld33 commented
Docs Build status updates of commit _[754e491](https://github.com/msbemba/microsoft-365-docs/commits/754e491336b7f11e4f48c1a8dbeb058b65bf4621)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1206/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209071334435648-9616/BuildReport?accessString=d23335eed28c36746665cf670e78a35ca670bda828d12f4b16dd8aa3e7165829).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 15:04 UTC, JohanFreelancer9 approved these changes

2022-09-08 11:00 UTC, yogkumgit commented
@efrene Please merge this PR. Thanks

2022-09-08 15:44 UTC, opbld30 commented
Docs Build status updates of commit _[3845b24](https://github.com/msbemba/microsoft-365-docs/commits/3845b24a6f260b7096cd808245c0b4b623650da1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1206/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209081541392754-9616/BuildReport?accessString=b8b4bbd04b0816f21047e7abc0a2cc9076c7a735901f89423e2d3603eb7f9b41).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 17:39 UTC, merged