Update safety-scanner-download.md
MicrosoftDocs/microsoft-365-docs pull request #9617
Opened 2022-09-05 12:01 UTC by msbemba

Updated the document to reduce ambiguity

2022-09-05 12:01 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9533

2022-09-05 12:02 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-05 12:08 UTC, opbld32 commented
Docs Build status updates of commit _[f4f5a06](https://github.com/msbemba/microsoft-365-docs/commits/f4f5a06b94e9dfbb599f7ca4071904f8228d7ac9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209051201513477-9617/BuildReport?accessString=695573702dc61698c630d376e6277c9cb948558007da725fed70aa2f946f2207).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 03:41 UTC, JohanFreelancer9 commented on microsoft-365/security/intelligence/safety-scanner-download.md
> +- Safety Scanner only scans when manually triggered. The Microsoft Safety Scanner expires 10 days after being downloaded. To rerun a scan with the latest anti-malware definitions, download and run th
```suggestion
- Microsoft Safety Scanner only scans when manually triggered. Safety Scanner expires 10 days after being downloaded. To rerun a scan with the latest anti-malware definitions, download and run Safety Scanner again. We recommend that you always download the latest version of this tool before each scan.
```

2022-09-06 03:41 UTC, JohanFreelancer9 commented on microsoft-365/security/intelligence/safety-scanner-download.md
>  - Safety scanner is a portable executable and does not appear in the Windows Start menu or as an icon on the desktop. Note where you saved this download.
```suggestion
- Safety Scanner is a portable executable and does not appear in the Windows Start menu or as an icon on the desktop. Note where you saved this download.
```

2022-09-06 03:41 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-06 03:48 UTC, opbld33 commented
Docs Build status updates of commit _[c65cee0](https://github.com/msbemba/microsoft-365-docs/commits/c65cee0c6703d30ee2c63df69072e62f17a90b57)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-df3d3792)

<a id="df3d3792"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209060346071019-9617/BuildReport?accessString=858cfe0109ea3e288abc2e925b8ba4f755548f706d13a5a48229bc19ad28d925).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 03:50 UTC, opbld30 commented
Docs Build status updates of commit _[2186c26](https://github.com/msbemba/microsoft-365-docs/commits/2186c261c1868b43e7a13ccc4e0aaa8a253499d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209060346164582-9617/BuildReport?accessString=468d9b38a17e0d63c8362c536e9bf338117151d9c721209b9d2dad06aca3383c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 07:51 UTC, JohanFreelancer9 approved these changes

2022-09-13 11:49 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks.

2022-09-15 14:06 UTC, opbld32 commented
Docs Build status updates of commit _[b78a4f1](https://github.com/msbemba/microsoft-365-docs/commits/b78a4f144c94fd938260d2dba93a3bca620e041a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :warning:Warning | | [Details](#user-content-9ce184770fe9da0bf7808ce99e5d4260-2fa428f0)

<a id="9ce184770fe9da0bf7808ce99e5d4260-2fa428f0"></a>
### [microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md)
 - **Line 17, Column 16**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.technology': 'm365d' is not valid with 'ms.prod' value 'm365-security'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209151403251920-9617/BuildReport?accessString=a8701477882761f8a1f74d908feded299ee074aeaf33d974cbca37811d30aab8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 14:11 UTC, opbld30 commented
Docs Build status updates of commit _[181d0fd](https://github.com/msbemba/microsoft-365-docs/commits/181d0fd5635013a4dd9a15337a9010739c22bfc5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :warning:Warning | | [Details](#user-content-9ce184770fe9da0bf7808ce99e5d4260-5af66cbe)

<a id="9ce184770fe9da0bf7808ce99e5d4260-5af66cbe"></a>
### [microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209151409112958-9617/BuildReport?accessString=24c9cf924203393fe280da5c056309814d541d4ba5feea80bfd3a8f058cb40d5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 05:08 UTC, yogkumgit commented
@msbemba Clear validation check please. Thanks

2022-10-04 07:43 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2022-10-07 11:23 UTC, yogkumgit commented
@Dansimp Gentle reminder.

2022-10-12 15:45 UTC, opbld30 commented
Learn Build status updates of commit _[2736b67](https://github.com/msbemba/microsoft-365-docs/commits/2736b673194795e0ed93835877ea7b8b12f98c75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210121543065340-9617/BuildReport?accessString=b558028c656c71dd222a5e0198b8624c3163451224a865fa22707f1605c87b7f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 14:19 UTC, yogkumgit commented
@msbemba

2022-10-13 15:31 UTC, msbemba commented
It has succeeded now @yogkumgit

2022-10-13 16:29 UTC, opbld33 commented
Learn Build status updates of commit _[b9a4da4](https://github.com/msbemba/microsoft-365-docs/commits/b9a4da45d00beb27f92e90a8580dd85ca0136290)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210131625122990-9617/BuildReport?accessString=e4e6868927b3ff3019ffc33896fddcb84f79a879747c8a531965871741f5531b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 20:30 UTC, opbld33 commented
Learn Build status updates of commit _[feef805](https://github.com/msbemba/microsoft-365-docs/commits/feef805ec7a5845be10f49194c1bb020034e1aa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210132028325170-9617/BuildReport?accessString=cc84f8f11d759fbded3e6b18a3980684e258e9d7205e8179d7cea7e6e32d8db2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 13:18 UTC, yogkumgit commented
@Dansimp Please merge this PR. Thanks

2022-12-08 20:42 UTC, opbld30 commented
Learn Build status updates of commit _[549ba3c](https://github.com/msbemba/microsoft-365-docs/commits/549ba3c67350d2c874a83b76e1c26a8d86d8a53d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082040059470-9617/BuildReport?accessString=64e1c6bb2f4551f27dac608748bb4b936232e59d0396e48e9bf1efde14a7fc24).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 18:57 UTC, opbld30 commented
Learn Build status updates of commit _[4e5ca3c](https://github.com/msbemba/microsoft-365-docs/commits/4e5ca3c5a7fffe0f810967606c80898fe80fda46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1207/microsoft-365/security/intelligence/safety-scanner-download.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212201855070998-9617/BuildReport?accessString=71ddc116135178d7f3384b3c602de18d3fd667767bc3b184c885e56e72ae5304).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 19:01 UTC, merged