Update auditing-solutions-overview.md
MicrosoftDocs/microsoft-365-docs pull request #9625
Opened 2022-09-06 12:22 UTC by msbemba

Added a new note stating that Microsoft Purview auditing is the new name for unified audit log.

2022-09-06 12:22 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-06 12:23 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9594

2022-09-06 12:23 UTC, opbld32 commented
Docs Build status updates of commit _[6658d58](https://github.com/msbemba/microsoft-365-docs/commits/6658d587c58bcf767c23f1ba26259e0914cdccd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/auditing-solutions-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1211/microsoft-365/compliance/auditing-solutions-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209061222510168-9625/BuildReport?accessString=187801c5aab23852a5a8a3bec6bb614aba8c27db39cf3b5999fad41e538d005c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 12:42 UTC, JohanFreelancer9 commented on microsoft-365/compliance/auditing-solutions-overview.md
> +> The Microsoft Purview auditing is the new name for unified audit log.
```suggestion
> Microsoft Purview auditing is the new name for unified audit log.
```

2022-09-06 12:43 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-06 13:31 UTC, opbld30 commented
Docs Build status updates of commit _[1064057](https://github.com/msbemba/microsoft-365-docs/commits/10640576a380cb522328800d392c4aff9ac46a88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/auditing-solutions-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1211/microsoft-365/compliance/auditing-solutions-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209061330165100-9625/BuildReport?accessString=12cb6c7cbffd85fca9b9b717568656ae151eb63b4e24defe3e51cd4b09bbe1e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 04:24 UTC, JohanFreelancer9 approved these changes

2022-09-07 11:25 UTC, yogkumgit commented
@v-tophillips Please merge this PR. Thanks

2022-09-07 19:02 UTC, v-tophillips approved these changes

2022-09-07 19:05 UTC, opbld32 commented
Docs Build status updates of commit _[d5efca5](https://github.com/msbemba/microsoft-365-docs/commits/d5efca54247c991bc6cbad941529e5d333102131)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-68ec0ea2)

<a id="68ec0ea2"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209071902230713-9625/BuildReport?accessString=7ce7ee928721df3e7983020b7922037d1afb9c34d5842127768162194376c067).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 19:06 UTC, v-tophillips approved these changes

2022-09-07 22:45 UTC, opbld33 commented
Docs Build status updates of commit _[158318d](https://github.com/msbemba/microsoft-365-docs/commits/158318d19900526b1d91c0fac96b94cf4e8bc0db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/auditing-solutions-overview.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1211/microsoft-365/compliance/auditing-solutions-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209072244536004-9625/BuildReport?accessString=d96c49820d6bc70d65b5979373c1ebac7562674ab38d76ec7d78198578ff9ccf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 22:45 UTC, merged