Update cross-tenant-mailbox-migration.md
MicrosoftDocs/microsoft-365-docs pull request #9633
Opened 2022-09-07 11:37 UTC by msbemba

For the step Prepare the source (current mailbox location) tenant by accepting the migration application and configuring the organization relationship they user needs to connect to Source tenant. Added that to the document

2022-09-07 11:37 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9597

2022-09-07 11:37 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-07 11:39 UTC, opbld32 commented
Docs Build status updates of commit _[138f5aa](https://github.com/msbemba/microsoft-365-docs/commits/138f5aa0ae772261bf267c4352fd2161a8a1d4da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1212/microsoft-365/enterprise/cross-tenant-mailbox-migration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209071137145897-9633/BuildReport?accessString=7c59bff21fde6a99f458e34d203e540b13b8830d4c3a99bac24f4ad3401526ca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 13:32 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/cross-tenant-mailbox-migration.md
> +3. [Connect to Exchange Online PowerShell](/powershell/exchange/connect-to-exchange-online-powershell) in the Source Exchange Online tenant.
```suggestion
3. [Connect to Exchange Online PowerShell](/powershell/exchange/connect-to-exchange-online-powershell) on the source Exchange Online tenant.
```

2022-09-07 13:34 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-07 13:36 UTC, opbld32 commented
Docs Build status updates of commit _[8119802](https://github.com/msbemba/microsoft-365-docs/commits/8119802fbe624db91ad2c7bd8f1cc9d003306e0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1212/microsoft-365/enterprise/cross-tenant-mailbox-migration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209071334547879-9633/BuildReport?accessString=b1042ff98054163bbe82c3637cf2167c6aa4724098e443dd86e57d9c27f2f9c2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 15:13 UTC, JohanFreelancer9 approved these changes

2022-09-08 10:56 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks.

2022-10-05 18:09 UTC, opbld31 commented
Learn Build status updates of commit _[9a8a79d](https://github.com/msbemba/microsoft-365-docs/commits/9a8a79d8604269ad9423f6c6eadc70dd7faa9091)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1212/microsoft-365/enterprise/cross-tenant-mailbox-migration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210051806152053-9633/BuildReport?accessString=f69ca43a0e2701696fbda3bba9e13c7fc27031842d08163c0c8b12c4fcb4e2b5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 18:10 UTC, merged