Update tenant-roadmap-microsoft-365.md
MicrosoftDocs/microsoft-365-docs pull request #9657
Opened 2022-09-09 14:33 UTC by msbemba

made changes to tenant Isolation URI

2022-09-09 14:33 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9627

2022-09-09 14:33 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-09 14:35 UTC, opbld31 commented
Docs Build status updates of commit _[98abfef](https://github.com/msbemba/microsoft-365-docs/commits/98abfefc0fd733d49a56133c39b089ee88714dd8)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/tenant-roadmap-microsoft-365.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1214/microsoft-365/enterprise/tenant-roadmap-microsoft-365.md) | :bulb:Suggestion | | [Details](#user-content-b7a4e45d6f24b3720888a7c2561da2be-55eb76f1)

<a id="b7a4e45d6f24b3720888a7c2561da2be-55eb76f1"></a>
### [microsoft-365/enterprise/tenant-roadmap-microsoft-365.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1214/microsoft-365/enterprise/tenant-roadmap-microsoft-365.md)
 - **Line 41, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /compliance/assurance/assurance-microsoft-365-isolation-controls?view=o365-worldwide#tenant-isolation`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209091433152570-9657/BuildReport?accessString=099ad03950b76079535efcc7e53420a0466bb00a37c8c3214c0f0022fb3b8b05).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 16:29 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/tenant-roadmap-microsoft-365.md
> +- [Understand tenant isolation](/compliance/assurance/assurance-microsoft-365-isolation-controls?view=o365-worldwide#tenant-isolation)
```suggestion
- [Understand tenant isolation](/compliance/assurance/assurance-microsoft-365-isolation-controls#tenant-isolation)
```

2022-09-09 16:30 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-09 18:03 UTC, opbld32 commented
Docs Build status updates of commit _[e9250bd](https://github.com/msbemba/microsoft-365-docs/commits/e9250bd8304492be02455f1d8a0a3c8483421060)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/tenant-roadmap-microsoft-365.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1214/microsoft-365/enterprise/tenant-roadmap-microsoft-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209091802382101-9657/BuildReport?accessString=ab269b7378c8076ea9b5a42219d158ef4dce3ee8650e0910e875ab2c02ed44c7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-10 03:59 UTC, JohanFreelancer9 approved these changes

2022-09-12 11:24 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-09-12 18:18 UTC, opbld32 commented
Docs Build status updates of commit _[655cf42](https://github.com/msbemba/microsoft-365-docs/commits/655cf421745abeaaa0ee1f36f189039129100768)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/tenant-roadmap-microsoft-365.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1214/microsoft-365/enterprise/tenant-roadmap-microsoft-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209121815089965-9657/BuildReport?accessString=28fb1e7d596a2eca31f2e0559ece1bba9804bcdfb6bf0cc4a7c5b5cd2f2e337b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 18:19 UTC, merged