Update password-policy-recommendations.md
MicrosoftDocs/microsoft-365-docs pull request #9685
Opened 2022-09-12 21:45 UTC by Crys-7

Maintain an fourteen -character minimum length requirement

2022-09-12 21:46 UTC, Crys-7 commented
Updating:   Maintain an fourteen -character minimum length requirement

2022-09-12 21:48 UTC, opbld30 commented
Docs Build status updates of commit _[ffbd2b1](https://github.com/Crys-7/microsoft-365-docs/commits/ffbd2b1d5d5f7d01af28999a60060056c3df3ed2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/Crys-7/microsoft-365-docs/blob/patch-1/microsoft-365/admin/misc/password-policy-recommendations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209122145466631-9685/BuildReport?accessString=001fbc934db802001fb55d25da211f8f9cdb9ab9b1294a0cff935568388363ce).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 06:41 UTC, JohanFreelancer9 commented on microsoft-365/admin/misc/password-policy-recommendations.md
> +- Maintain an fourteen -character minimum length requirement
```suggestion
- Maintain a fourteen-character minimum length requirement
```

2022-09-13 06:42 UTC, JohanFreelancer9 requested changes
Copy review - @Crys-7, kindly commit the suggested changes. Many thanks.

2022-09-13 17:25 UTC, Crys-7 commented
committed

2022-09-13 17:28 UTC, opbld32 commented
Docs Build status updates of commit _[2f183c9](https://github.com/Crys-7/microsoft-365-docs/commits/2f183c95fcb69a6602ba28ea351f2ae875717dcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/Crys-7/microsoft-365-docs/blob/patch-1/microsoft-365/admin/misc/password-policy-recommendations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209131725021973-9685/BuildReport?accessString=6d1796a748d215c2c85561bdddf373fb8f8a2b1a116e3c1aba50aba5ea9e8aec).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 17:29 UTC, opbld31 commented
Docs Build status updates of commit _[2f183c9](https://github.com/Crys-7/microsoft-365-docs/commits/2f183c95fcb69a6602ba28ea351f2ae875717dcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/Crys-7/microsoft-365-docs/blob/patch-1/microsoft-365/admin/misc/password-policy-recommendations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209131726126287-9685/BuildReport?accessString=e7bd340887247fec0979df9a1715a752f529df44d13f5ffad122c93aafe186b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 05:03 UTC, JohanFreelancer9 approved these changes

2022-09-15 10:58 UTC, yogkumgit commented
@kwekuako Please merge this PR. Thanks

2022-10-07 11:26 UTC, yogkumgit commented
@kwekuako Gentle reminder.

2022-10-07 20:12 UTC, opbld33 commented
Learn Build status updates of commit _[999b9b0](https://github.com/Crys-7/microsoft-365-docs/commits/999b9b0a833b1d22fd02ad41bb485fb4fb0d5885)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/Crys-7/microsoft-365-docs/blob/patch-1/microsoft-365/admin/misc/password-policy-recommendations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210072011024070-9685/BuildReport?accessString=30be8fe0e53df1eaa74903a88086d0d28ecccf208fdf9647f6c7f3bf4361bcc5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 20:13 UTC, merged