Update whats-new-in-defender-for-office-365.md
MicrosoftDocs/microsoft-365-docs pull request #9687
Opened 2022-09-13 06:58 UTC by ajaj-shaikh

Update on BCL now being available in advanced hunting

2022-09-13 07:01 UTC, opbld30 commented
Docs Build status updates of commit _[4a893e3](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/4a893e34161a31748c2b0a3b06c8b8419250da2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-2/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209130658280515-9687/BuildReport?accessString=fe9f2e471556d207c358a3f5fbb102ed10d423ee2997cc0038eae90ba32bfb66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 11:53 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-13 15:59 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md
> +- Bulk Complaint Level is now available in EmailEvents table in Advanced Hunting with numeric BCL values from 0 to 9. A higher BCL score indicates that bulk message is more likely to generate complai
```suggestion
- Bulk complaint level (BCL) is now available in the EmailEvents table in advanced hunting with numeric BCL values ranging from 0 to 9. A higher BCL score indicates that bulk messages are more likely to generate complaints and are more likely to be spam.
```

2022-09-13 15:59 UTC, JohanFreelancer9 requested changes
Copy review - @ajaj-shaikh, kindly commit the suggested changes. Many thanks

2022-09-13 16:08 UTC, opbld30 commented
Docs Build status updates of commit _[b6780a9](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/b6780a9143ec760bc34a007fbaf3fe63403a9612)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-2/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209131607148648-9687/BuildReport?accessString=b98993786d96f6dfce0782c681026c0959d6799b7510cd15765820029705462b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 16:11 UTC, opbld31 commented
Docs Build status updates of commit _[7450a25](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/7450a253f15daf8da1adbf3b819a80d4b4315df9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-2/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209131607533450-9687/BuildReport?accessString=2acf931efbb18589eda21c91246c17704f70ce979e051da764c6aaf2912278c3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 17:09 UTC, JohanFreelancer9 approved these changes

2022-09-15 10:59 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2023-09-08 21:18 UTC, chrisda commented
Topic file was renamed, and the proposed change is already present in the September 2022 section, so closing this PR.

2023-09-08 21:18 UTC, closed without merging