Update troubleshoot-asr.md
MicrosoftDocs/microsoft-365-docs pull request #9689
Opened 2022-09-13 08:57 UTC by msbemba

Fixed the ASR reporting part as it is changed to report exploit guard

2022-09-13 08:57 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-13 08:57 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9648

2022-09-13 08:58 UTC, opbld31 commented
Docs Build status updates of commit _[916cf64](https://github.com/msbemba/microsoft-365-docs/commits/916cf64565d2743d2b68d9e846034bfd24516f1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/troubleshoot-asr.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1217/microsoft-365/security/defender-endpoint/troubleshoot-asr.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209130857447108-9689/BuildReport?accessString=0fe97eedc152b9d3b72055612ffacd530ac045865b29ad01936a99c049cfb3fe).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 10:52 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/troubleshoot-asr.md
> +Use the [Windows Defender Security Intelligence web-based submission form](https://www.microsoft.com/en-us/wdsi/support/report-exploit-guard) to report a false negative or false positive for network
```suggestion
Use the [Windows Defender Security Intelligence web-based submission form](https://www.microsoft.com/wdsi/support/report-exploit-guard) to report a false negative or false positive for network protection. With a Windows E5 subscription, you can also [provide a link to any associated alert](alerts-queue.md).
```

2022-09-13 10:52 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-13 10:56 UTC, opbld32 commented
Docs Build status updates of commit _[ec516b1](https://github.com/msbemba/microsoft-365-docs/commits/ec516b1e79b7404bddb1392048817b1ba0fdfa56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/troubleshoot-asr.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1217/microsoft-365/security/defender-endpoint/troubleshoot-asr.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209131053335863-9689/BuildReport?accessString=7f70fbc86b4ef38860c087afe6b783dff3495056337e64bce7f2b429e4f21605).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 11:26 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-13 11:27 UTC, yogkumgit commented
@jweston-1 Please merge this PR. Thanks

2022-09-13 13:30 UTC, JohanFreelancer9 approved these changes

2022-09-14 16:16 UTC, jweston-1 approved these changes

2022-09-14 16:17 UTC, opbld32 commented
Docs Build status updates of commit _[d2ccda0](https://github.com/msbemba/microsoft-365-docs/commits/d2ccda0085f2814928cb9f738b036c196dded32a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/troubleshoot-asr.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1217/microsoft-365/security/defender-endpoint/troubleshoot-asr.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209141616359684-9689/BuildReport?accessString=66271ddc6092fcbe02df0350da460c837b83030dcc094b509d881ce34293a9ff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 16:19 UTC, merged