Update insider-risk-management-policies.md
MicrosoftDocs/microsoft-365-docs pull request #9697
Opened 2022-09-13 11:39 UTC by msbemba

Data leaks by priority users are no longer in preview and are available for the general audience. Updated the Document accordingly.

2022-09-13 11:39 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-13 11:39 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9671

2022-09-13 11:40 UTC, opbld30 commented
Docs Build status updates of commit _[13516c6](https://github.com/msbemba/microsoft-365-docs/commits/13516c6d3c6db8cbbb74df95bf977e9007dd3e9a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management.md) | :warning:Warning | | [Details](#user-content-016eff8ac90de95487e65b53e56f9df7-ed7016b6)
[microsoft-365/compliance/insider-risk-management-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management-policies.md) | :white_check_mark:Succeeded | |

<a id="016eff8ac90de95487e65b53e56f9df7-ed7016b6"></a>
### [microsoft-365/compliance/insider-risk-management.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management.md)
 - **Line 93, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````
 - **Line 164, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````
 - **Line 181, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209131139094383-9697/BuildReport?accessString=de65f7581134cc7522b724c6a8b5c0e94d76074f7b08cf5b625325a27e2cc535).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 14:28 UTC, JohanFreelancer9 commented on microsoft-365/compliance/insider-risk-management-policies.md
>  Protecting data and preventing data leaks for users in your organization may depend on their position, level of access to sensitive information, or risk history. Data leaks can include accidental ove
```suggestion
Protecting data and preventing data leaks for users in your organization may depend on their position, level of access to sensitive information, or risk history. Data leaks can include accidental oversharing of highly sensitive information outside your organization or data theft with malicious intent. With an assigned data loss prevention (DLP) policy as a triggering event option, this template starts scoring real-time detections of suspicious activity and results in an increased likelihood of insider risk alerts and alerts with higher severity levels. Priority users are defined in [priority user groups](insider-risk-management-settings.md#priority-user-groups-preview) configured in the insider risk management settings area.
```

2022-09-13 14:29 UTC, JohanFreelancer9 requested changes
@msbemba, not related to your change, but could you also commit the additional suggested change, please? Many thanks.

2022-09-13 16:04 UTC, opbld30 commented
Docs Build status updates of commit _[df4af2a](https://github.com/msbemba/microsoft-365-docs/commits/df4af2a3f88ba8ee62b3c3bcc77e06242f0d1406)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management.md) | :warning:Warning | | [Details](#user-content-016eff8ac90de95487e65b53e56f9df7-b16bccfe)
[microsoft-365/compliance/insider-risk-management-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management-policies.md) | :white_check_mark:Succeeded | |

<a id="016eff8ac90de95487e65b53e56f9df7-b16bccfe"></a>
### [microsoft-365/compliance/insider-risk-management.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management.md)
 - **Line 93, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````
 - **Line 164, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````
 - **Line 181, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209131603105699-9697/BuildReport?accessString=76e6e04d7b915a7d21e109a57ff1994e24925b4ae63bcd7ee03443d4aeab2e9f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 16:51 UTC, opbld31 commented
Docs Build status updates of commit _[1c86ef3](https://github.com/msbemba/microsoft-365-docs/commits/1c86ef30ad70ab5db908eb0040c65b73e95acea9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management.md) | :warning:Warning | | [Details](#user-content-016eff8ac90de95487e65b53e56f9df7-6c8d744c)
[microsoft-365/compliance/insider-risk-management-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management-policies.md) | :white_check_mark:Succeeded | |

<a id="016eff8ac90de95487e65b53e56f9df7-6c8d744c"></a>
### [microsoft-365/compliance/insider-risk-management.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management.md)
 - **Line 93, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````
 - **Line 164, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````
 - **Line 181, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#data-leaks-by-priority-users-preview' in 'compliance/insider-risk-management-policies.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209131648576865-9697/BuildReport?accessString=ae855bba6f292a5242a93d137787c62fd0ee51d06a49df26179d469b4b7cdf32).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 16:58 UTC, JohanFreelancer9 approved these changes

2022-09-14 04:43 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2022-09-22 05:32 UTC, yogkumgit commented
@msbemba validation warning. Please review. Thanks

2022-09-28 15:12 UTC, yogkumgit commented
@msbemba Gentle reminder

2022-10-03 05:33 UTC, opbld31 commented
Learn Build status updates of commit _[31d7a37](https://github.com/msbemba/microsoft-365-docs/commits/31d7a373b2ffada8f68216fcff534b9f32903dd1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/insider-risk-management.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management.md) | :white_check_mark:Succeeded | |
[microsoft-365/compliance/insider-risk-management-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1223/microsoft-365/compliance/insider-risk-management-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210030531552480-9697/BuildReport?accessString=5eaab498c782ee2b1472327b63239d8dcbdc6cc2e862169683682619f7d81f53).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 06:07 UTC, msbemba commented
> @msbemba Gentle reminder

This has been fixed.

2022-10-03 12:20 UTC, yogkumgit commented
@robmazz Please merge this PR. Thanks

2023-06-19 10:58 UTC, yogkumgit commented
Closing as per the comment in #9671

2023-06-19 10:58 UTC, closed without merging