Added a link to resources
MicrosoftDocs/microsoft-365-docs pull request #971
Opened 2019-12-22 17:58 UTC by joinimran

Added a link to the resources where the user can get more details related to permissions.

Problem: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/817

2019-12-22 17:58 UTC, joinimran commented
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-12-23 02:53 UTC, JohanFreelancer9 commented on microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery.md
> +You can add or remove members to manage who can access the case. Users who are added to Reviewer or eDiscovery Manager role groups can be added as members of the case. The eDiscovery Manager who crea
```suggestion
You can add or remove members to manage who can access the case. Users who are added to Reviewer or eDiscovery Manager role groups can be added as members of the case. The eDiscovery Manager who created the case is automatically added as a member. See [Assign eDiscovery permissions in the Security & Compliance Center](https://docs.microsoft.com/microsoft-365/compliance/assign-ediscovery-permissions) for more details.
```

2019-12-23 02:53 UTC, JohanFreelancer9 requested changes
Copy Review - minor edit.

2019-12-23 07:02 UTC, joinimran commented
@mypil Ready to go live.

2019-12-23 16:06 UTC, mypil commented
@markjjo - PR has been copy edited and is ready for final review. This is based on issue #817.

Thank you.

cc: @kenwith

2019-12-23 22:58 UTC, merged