PST import caveat with autoexpansion
MicrosoftDocs/microsoft-365-docs pull request #9720
Opened 2022-09-14 18:38 UTC by v-padum

Adding caveat for network import into mailboxes that have autoexpanding turned on. (Premier support ticket 32045647)

2022-09-14 18:40 UTC, opbld30 commented
Docs Build status updates of commit _[f408f94](https://github.com/v-padum/microsoft-365-docs/commits/f408f94cdf8fb3f19841b2d8679e3863c1024673)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/v-padum/microsoft-365-docs/blob/patch-7/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :warning:Warning | | [Details](#user-content-a29176b917612325eb861b29a6452462-3b582afe)

<a id="a29176b917612325eb861b29a6452462-3b582afe"></a>
### [microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/v-padum/microsoft-365-docs/blob/patch-7/microsoft-365/compliance/enable-autoexpanding-archiving.md)
 - **Line 40, Column 62**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 62**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 40, Column 62**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209141838471348-9720/BuildReport?accessString=5769d851bf5a237631bd8089c456d513c3e1a7e03ac2babcb343b4d97951f9bd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 20:47 UTC, opbld31 commented
Docs Build status updates of commit _[bd1ffd3](https://github.com/v-padum/microsoft-365-docs/commits/bd1ffd3fe357aa7ee8c93a7970a43b4d766dd227)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/v-padum/microsoft-365-docs/blob/patch-7/microsoft-365/compliance/enable-autoexpanding-archiving.md) | :warning:Warning | | [Details](#user-content-a29176b917612325eb861b29a6452462-ed17143b)

<a id="a29176b917612325eb861b29a6452462-ed17143b"></a>
### [microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/v-padum/microsoft-365-docs/blob/patch-7/microsoft-365/compliance/enable-autoexpanding-archiving.md)
 - **Line 40, Column 62**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 62**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 40, Column 62**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209142045064306-9720/BuildReport?accessString=349f7c6fd5250396e4c7eed97797b5c40915de2d97659800da3bc4528a9a3086).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 05:02 UTC, JohanFreelancer9 commented on microsoft-365/compliance/enable-autoexpanding-archiving.md
> +    - Once auto-expanding archiving is enabled on a mailbox, [network upload of PST files](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-w
```suggestion
    - Once auto-expanding archiving is enabled on a mailbox, [network upload of PST files](/microsoft-365/compliance/use-network-upload-to-import-pst-files) may fail. This is due to the sharding of specific folders into auxiliary archives, which causes imports to a sharded location to generate an error.
```

2022-09-15 05:03 UTC, JohanFreelancer9 requested changes
Copy review - @v-padum, kindly commit the suggested changes. Many thanks.

2022-09-15 13:47 UTC, v-padum commented
Yep perfect and thank you, wasn't sure how to make the relative URL work here given that every markdown file is in a different location.

2022-09-15 18:02 UTC, JohanFreelancer9 approved these changes

2022-09-15 18:40 UTC, cabailey commented
#hold-off Discussing internally

2022-10-04 07:53 UTC, yogkumgit commented
@cabailey Any update please.

2022-10-04 13:17 UTC, v-padum commented
Hi Yogesh. I believe we're cancelling this PR as document owners would want the information and context being added to be in a different location.

Thanks.


From: Yogesh Kumar ***@***.***>
Sent: Tuesday, October 4, 2022 3:54 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Patricia Dumas Bonnier (Sherweb Inc) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] PST import caveat with autoexpansion (PR #9720)


@cabailey<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcabailey&data=05%7C01%7Cv-padum%40microsoft.com%7Ce97d988884004466b43208daa5dd9731%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638004668412690945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P9Tf2XguDmfdGI6cCDngNR%2FZeRwQ9TXoRnOzf%2F8HfPA%3D&reserved=0> Any update please.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F9720%23issuecomment-1266545316&data=05%7C01%7Cv-padum%40microsoft.com%7Ce97d988884004466b43208daa5dd9731%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638004668412690945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=m2rpsTo1ej3WPlMQncxIiSmA3DmrX5FPNYy%2B1cC2uJ0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPLQ4OMDDBNCMBR5DI7D32LWBPPBJANCNFSM6AAAAAAQMV225Y&data=05%7C01%7Cv-padum%40microsoft.com%7Ce97d988884004466b43208daa5dd9731%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638004668412690945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LjPRnk9CYtOO%2BF9Y2tHlocD%2FYTDO6FmJ3tPR7LcjX2g%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-04 16:52 UTC, cabailey commented
Yes, we agreed to move the support statement for PST files from the docs for auto-expanding to the PST import docs (with any new caveats) & I left this PR open in case you wanted to use this for the update & tracking.

2022-12-08 01:21 UTC, cabailey commented
Closing.  We agreed offline that support statements for PST import belong with the PST import docs.

2022-12-08 01:21 UTC, closed without merging