Update machine.md
MicrosoftDocs/microsoft-365-docs pull request #9743
Opened 2022-09-16 11:24 UTC by msbemba

Updated the Possible values for onboarding status.

2022-09-16 11:24 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-09-16 11:24 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9711

2022-09-16 11:26 UTC, opbld30 commented
Docs Build status updates of commit _[507661b](https://github.com/msbemba/microsoft-365-docs/commits/507661b9b7024f0c2c1dd39e4c9f043990b4cb87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/machine.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1234/microsoft-365/security/defender-endpoint/machine.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209161124280076-9743/BuildReport?accessString=330a6ead35dd664b1b9998188452ab3ee217082a4969a3ca956c49e994855a5d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 13:06 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/machine.md
> +|onboardingstatus|String|Status of machine onboarding. Possible values are: "onboarded", "CanBeOnboarded", "Unsupported" amd "InsufficientInfo" .|
```suggestion
|onboardingstatus|String|Status of machine onboarding. Possible values are: "onboarded", "CanBeOnboarded", "Unsupported", and "InsufficientInfo".|
```

2022-09-16 13:07 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-16 13:17 UTC, opbld31 commented
Docs Build status updates of commit _[4d30e99](https://github.com/msbemba/microsoft-365-docs/commits/4d30e99d7c16fd4b681901e0458925bd904fe232)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/machine.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1234/microsoft-365/security/defender-endpoint/machine.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209161314216814-9743/BuildReport?accessString=a29438eaf5cca320fdf97ca2a0c9785545b24f154e7ab9fd6a97bfcc6c7f1ad8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 13:40 UTC, JohanFreelancer9 approved these changes

2022-09-20 07:35 UTC, yogkumgit commented
@siosulli Please merge this PR. Thanks

2022-09-20 10:36 UTC, opbld30 commented
Docs Build status updates of commit _[d398eca](https://github.com/msbemba/microsoft-365-docs/commits/d398ecabfbd7018aeea6c7562c44c1630dc930c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/machine.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1234/microsoft-365/security/defender-endpoint/machine.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209201035312518-9743/BuildReport?accessString=2514a1481f2dce93c702be49da0475de42b5e0ff36269ab31c7414fa0fef69af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 10:38 UTC, merged