Update configure-exchange-server-for-hybrid-modern-authentication.md
MicrosoftDocs/microsoft-365-docs pull request #9750
Opened 2022-09-16 20:14 UTC by Smartboss88

2022-09-16 20:17 UTC, opbld32 commented
Docs Build status updates of commit _[63df1ed](https://github.com/Smartboss88/microsoft-365-docs/commits/63df1ed24464e58fa2df7fdda98a4207fd77df41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/Smartboss88/microsoft-365-docs/blob/patch-8/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209162014354024-9750/BuildReport?accessString=56af0feca41b798c9d8637a34f2d1c369e5477a18727c0abccd4b705f321a7ac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 05:27 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md
> +> Outlook Web App and Exchange Control Panel does not work with hybrid Modern Authentication.  In addition, publishing Outlook Web App and Exchange Control Panel through Azure AD Application Proxy is
```suggestion
> Outlook Web App and Exchange Control Panel do not work with hybrid Modern Authentication.  In addition, publishing Outlook Web App and Exchange Control Panel through Azure AD Application Proxy is unsupported.
```

2022-09-19 05:28 UTC, JohanFreelancer9 requested changes
Copy review - @Smartboss88, kindly commit the additional suggested change. Many thanks.

2022-09-19 12:51 UTC, opbld31 commented
Docs Build status updates of commit _[d2d9be5](https://github.com/Smartboss88/microsoft-365-docs/commits/d2d9be563ce830e861a1e71020e2875e02ba89a3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-523500c4)

<a id="523500c4"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209191251330268-9750/BuildReport?accessString=ba51580a580b73ddced9667ebeb0119ba333b577fee03595e324a9842f664d18).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 13:01 UTC, opbld30 commented
Docs Build status updates of commit _[73a3a81](https://github.com/Smartboss88/microsoft-365-docs/commits/73a3a81913c7215b81dfbdc61227b2d1cdef406a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-47d54806)

<a id="47d54806"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209191301307915-9750/BuildReport?accessString=572706fd868bc4b36084d7e5c4cbcd50e33661637721de058260f9a1e6d3cbc7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 13:24 UTC, JohanFreelancer9 approved these changes

2022-09-20 09:33 UTC, opbld30 commented
Docs Build status updates of commit _[73a3a81](https://github.com/Smartboss88/microsoft-365-docs/commits/73a3a81913c7215b81dfbdc61227b2d1cdef406a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/Smartboss88/microsoft-365-docs/blob/patch-8/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209200931045550-9750/BuildReport?accessString=47922bbf85bfa7a7fed3b30189d15246c7fffc47fa7de6e4f49331a417d83ae7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 05:45 UTC, yogkumgit commented
@kelleyvice-msft Please merge this PR. Thanks

2022-09-29 15:14 UTC, Smartboss88 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Any update please? Sent from Mail for Windows From: Yogesh KumarSent: Thursday, September 22, 2022 1:46 AMTo: MicrosoftDocs/microsoft-365-docsCc: Smartboss88; MentionSubject: Re: [MicrosoftDocs/microsoft-365-docs] Update configure-exchange-server-for-hybrid-modern-authentication.md (PR ***@***.*** Please merge this PR. Thanks—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 

2022-10-04 20:30 UTC, opbld31 commented
Learn Build status updates of commit _[06f5ca2](https://github.com/Smartboss88/microsoft-365-docs/commits/06f5ca2514121f79e60c9d34c6c956173562db54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/Smartboss88/microsoft-365-docs/blob/patch-8/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210042028121183-9750/BuildReport?accessString=5335c60ffa6c3e44662ca142d27df0d302996c0468ff85283bda83cdace8f8d4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 10:58 UTC, yogkumgit commented
@kelleyvice-msft Please merge this P.  Thanks

2022-10-05 18:25 UTC, opbld33 commented
Learn Build status updates of commit _[99e898d](https://github.com/Smartboss88/microsoft-365-docs/commits/99e898df6ca6c3c0777c717fa200498967be4b92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/Smartboss88/microsoft-365-docs/blob/patch-8/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210051823292327-9750/BuildReport?accessString=987c94098012b18ee870f33bccb35f8ebea8f8c5d50203119b2641e605639bb0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 18:26 UTC, merged