Update virus-initiative-criteria.md
MicrosoftDocs/microsoft-365-docs pull request #9753
Opened 2022-09-16 21:36 UTC by adamoboe

Added the following text: The MVI Program has not currently accepting new applications for membership. Please contact MVI@microsoft.com for more information. We are pausing new members while we get out anti-cheat program up and running.

2022-09-16 21:37 UTC, opbld33 commented
Docs Build status updates of commit _[3856de5](https://github.com/adamoboe/microsoft-365-docs/commits/3856de57a415c0d639224006c32440e97896f089)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/virus-initiative-criteria.md](https://github.com/adamoboe/microsoft-365-docs/blob/patch-2/microsoft-365/security/intelligence/virus-initiative-criteria.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209162136051629-9753/BuildReport?accessString=4d9f8a59bcb316fa4022960d5bd339bbe830737d51f6f6af8bca1be53970d88e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 05:34 UTC, JohanFreelancer9 commented on microsoft-365/security/intelligence/virus-initiative-criteria.md
> +The MVI Program has not currently accepting new applications for membership. Please contact MVI@microsoft.com for more information.
```suggestion
> [!NOTE]
> The MVI Program is not currently accepting new applications for membership. Please contact MVI@microsoft.com for more information.
```

2022-09-19 05:35 UTC, JohanFreelancer9 requested changes
Copy review - @adamoboe, kindly commit the suggested change. Many thanks.

2022-09-22 05:46 UTC, yogkumgit commented
@adamoboe Gentle reminder.

2022-10-07 11:23 UTC, yogkumgit commented
@adamoboe Please update the suggested changes, in the event to no response, we may proceed to close this PR. Your cooperation is well appreciated. Thanks

2022-10-17 14:48 UTC, opbld32 commented
Learn Build status updates of commit _[6a3b7cd](https://github.com/adamoboe/microsoft-365-docs/commits/6a3b7cd261bbcaf5ef77068d5e2b8761d7b0d4ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/virus-initiative-criteria.md](https://github.com/adamoboe/microsoft-365-docs/blob/patch-2/microsoft-365/security/intelligence/virus-initiative-criteria.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210171444367150-9753/BuildReport?accessString=d12eb46661651fedabe0cb168909992f91a4c81cdbe4edd0e4bd10be3710acf3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 14:51 UTC, opbld31 commented
Learn Build status updates of commit _[8dad168](https://github.com/adamoboe/microsoft-365-docs/commits/8dad168676e3d16d885c0817e1333f43f597e2ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/intelligence/virus-initiative-criteria.md](https://github.com/adamoboe/microsoft-365-docs/blob/patch-2/microsoft-365/security/intelligence/virus-initiative-criteria.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210171445101690-9753/BuildReport?accessString=e89f0e6c7fccb7ecdd165d8af1862a3b5f848394aef6706d122ddd7b5f53d3f6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 14:52 UTC, merged