Warning about DKIM under specific configuration
MicrosoftDocs/microsoft-365-docs pull request #9783
Opened 2022-09-21 05:51 UTC by FlorentATo

Fixes #9782

2022-09-21 05:52 UTC, opbld30 commented
Docs Build status updates of commit _[010c473](https://github.com/FlorentATo/microsoft-365-docs/commits/010c473b58d187d4825111993f100d966b8e5300)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209210551414847-9783/BuildReport?accessString=42117c50b7ee2d6bd9a3cca724d8e3d67248f9ca3a361e9c2f8a798c4d033f38).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 06:03 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md
> +> - both the sender and the recipient email address use different domains that are controlled by the same organization.
```suggestion
> - Both the sender and the recipient email address use the same domain.
> - Both the sender and the recipient email address use different domains that are controlled by the same organization.
```

2022-09-21 06:03 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md
> +> In both cases, the header will look like something like this:
```suggestion
> In both cases, the header will look similar to this:
```

2022-09-21 06:04 UTC, JohanFreelancer9 requested changes
Copy review - @FlorentATo, kindly commit the suggested changes. Many thanks.

2022-09-21 17:15 UTC, opbld33 commented
Docs Build status updates of commit _[59ec9cc](https://github.com/FlorentATo/microsoft-365-docs/commits/59ec9ccddf5a820cb48d29e4daa9678be972e623)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209211714063624-9783/BuildReport?accessString=3764267c3e3622340ce719e6aa392d4113ccdd71a9485f645dfe412859773d3a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 17:18 UTC, opbld33 commented
Docs Build status updates of commit _[98e0fd3](https://github.com/FlorentATo/microsoft-365-docs/commits/98e0fd3a5c0477436ed1de8a79295ccf0481fc29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209211714207128-9783/BuildReport?accessString=818314c59cd860f979f3a1fce447155800806cf4511cfb823a0cc8632dcafc85).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 20:02 UTC, opbld33 commented
Docs Build status updates of commit _[ca0c30f](https://github.com/FlorentATo/microsoft-365-docs/commits/ca0c30ff701ddf811f32d1265bfca4f3fe03f3a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209211959272380-9783/BuildReport?accessString=5d82748146d8be3df431d0a9b9a5509c998942dd98708a436ccb4ed51a55bc77).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 20:12 UTC, FlorentATo commented
@JohanFreelancer9 for final review, please.

2022-09-22 04:15 UTC, opbld32 commented
Docs Build status updates of commit _[1ac2f96](https://github.com/FlorentATo/microsoft-365-docs/commits/1ac2f961912752131e5c8f2d6af8e4025d09b467)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209220412521970-9783/BuildReport?accessString=1ccbc485a5a03a588bc5355ce83685d502ebed5ea6e4c68d33def0d47de876be).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 05:47 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2022-09-22 06:53 UTC, JohanFreelancer9 approved these changes

2022-09-23 00:46 UTC, opbld32 commented
Docs Build status updates of commit _[8ea4689](https://github.com/FlorentATo/microsoft-365-docs/commits/8ea4689070b5b854e1bceecbb6eb68280f017421)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209230044559048-9783/BuildReport?accessString=39e2302ce9ea0db68a69b642c752104798f6b05e099b50f2ee052499a310356f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 04:42 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2022-09-25 06:40 UTC, opbld33 commented
Docs Build status updates of commit _[5dcec1a](https://github.com/FlorentATo/microsoft-365-docs/commits/5dcec1acbb3bae007eacc2d46e363068ff8710fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209250639351248-9783/BuildReport?accessString=3ecc702c37798d78797caf79bfe9d25687c004178ab740bd5e4b7698c19aa146).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 15:37 UTC, yogkumgit commented
@tiburd Please help us.

2022-09-27 18:43 UTC, opbld30 commented
Docs Build status updates of commit _[1b7d3fc](https://github.com/FlorentATo/microsoft-365-docs/commits/1b7d3fcc8e520cbd4fb3bf344a63443e2c98929b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209271842276828-9783/BuildReport?accessString=bac97e97092b6c2ab5cca7e502dcd2cc6e2f89eefbd85f4c73631c5e82ada66c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-29 20:58 UTC, opbld30 commented
Learn Build status updates of commit _[0a1f3e4](https://github.com/FlorentATo/microsoft-365-docs/commits/0a1f3e4a25e21a3becd22d05cb5af8df824609f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209292056385792-9783/BuildReport?accessString=f2736745316612eb344de9acff869bf0ae5c872800036601014f548e4a41af6c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 10:38 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2022-09-30 16:14 UTC, opbld32 commented
Learn Build status updates of commit _[ace861f](https://github.com/FlorentATo/microsoft-365-docs/commits/ace861f67f196814c460c89f0582470a3c600e96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209301612197099-9783/BuildReport?accessString=0d50af0ca3cbe4556c7e5e5f2138476a95a26e5d4b1a6e08d41c24fd2a5404e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 15:15 UTC, FlorentATo commented
@MSFTTracyP, @tiburd any chance to get to PR merged anytime soon ? Thank you.

2022-10-04 15:16 UTC, opbld32 commented
Learn Build status updates of commit _[3a03639](https://github.com/FlorentATo/microsoft-365-docs/commits/3a036399cdf0eee0219416dad9673f85a57f0394)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/FlorentATo/microsoft-365-docs/blob/patch-1/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210041514329968-9783/BuildReport?accessString=bd2361d192d8f52eb5cc7964d18700881b6352a3ba32eb8bd292eea214d5564a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 15:30 UTC, tiburd commented
@MSFTTracyP 
Hi,
Please review and merge if you approve the changes.
Thanks!

2022-10-25 05:04 UTC, FlorentATo commented
Any update on this @MSFTTracyP @tiburd @yogkumgit @JohanFreelancer9 ?

2022-12-07 05:50 UTC, opbld33 commented
Learn Build status updates of commit _[33fa4d8](https://github.com/FlorentATo/microsoft-365-docs/commits/33fa4d8bd9fb37111f171cd03b52cf1ed3dccba1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3945ea1b)

<a id="3945ea1b"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 33fa4d8bd9fb37111f171cd03b52cf1ed3dccba1 in branch patch-1 of repository https://github.com/FlorentATo/microsoft-365-docs into branch public (commit 2ff545246fec060ea7829da5afbc1cdc698d51ab). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212070549278469-9783/BuildReport?accessString=b1de7384e8b0a32238baadb319b0f82821c9576a96661f31030d4b7f330d40f1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 05:53 UTC, opbld31 commented
Learn Build status updates of commit _[9626f82](https://github.com/FlorentATo/microsoft-365-docs/commits/9626f82dc824f2579b0edf00ae7b6d0136b3e24b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5cb74501)

<a id="5cb74501"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 9626f82dc824f2579b0edf00ae7b6d0136b3e24b in branch patch-1 of repository https://github.com/FlorentATo/microsoft-365-docs into branch public (commit 2ff545246fec060ea7829da5afbc1cdc698d51ab). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212070551566601-9783/BuildReport?accessString=395b111101c1778623ef27f9bc1256ecb56af3096c3e4fa1bdac2ce4e00198dd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 05:55 UTC, opbld32 commented
Learn Build status updates of commit _[ef9c63a](https://github.com/FlorentATo/microsoft-365-docs/commits/ef9c63a57261c86efb568094b99e79e6e9a35e5f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2f44f668)

<a id="2f44f668"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit ef9c63a57261c86efb568094b99e79e6e9a35e5f in branch patch-1 of repository https://github.com/FlorentATo/microsoft-365-docs into branch public (commit 2ff545246fec060ea7829da5afbc1cdc698d51ab). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212070554230703-9783/BuildReport?accessString=58fb546e1a6fe00f8ca8b54b4c69a899b73ecd0583a815fb8338de4e9942ef71).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 05:56 UTC, opbld30 commented
Learn Build status updates of commit _[39a7638](https://github.com/FlorentATo/microsoft-365-docs/commits/39a76380c39a5b966a0a18d176e230cc4a47192c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-28887868)

<a id="28887868"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 39a76380c39a5b966a0a18d176e230cc4a47192c in branch patch-1 of repository https://github.com/FlorentATo/microsoft-365-docs into branch public (commit 2ff545246fec060ea7829da5afbc1cdc698d51ab). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212070555223774-9783/BuildReport?accessString=4030905cfbe43d8cec935fd7cf5ee31679dd0dcdff6bdd1fb18f02c2822384a0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 05:57 UTC, opbld32 commented
Learn Build status updates of commit _[a4f88bc](https://github.com/FlorentATo/microsoft-365-docs/commits/a4f88bcc52201f4b48bea385309ef4e753f68b22)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c4eb4f50)

<a id="c4eb4f50"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit a4f88bcc52201f4b48bea385309ef4e753f68b22 in branch patch-1 of repository https://github.com/FlorentATo/microsoft-365-docs into branch public (commit 2ff545246fec060ea7829da5afbc1cdc698d51ab). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212070555548858-9783/BuildReport?accessString=48de2c1b7d7126109a9888b7676b456d78b856ee1048a403d879419e4787bf93).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 05:59 UTC, opbld33 commented
Learn Build status updates of commit _[ec98f68](https://github.com/FlorentATo/microsoft-365-docs/commits/ec98f6806ca29609a8efe604634a8b1e8e03d653)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2411583b)

<a id="2411583b"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit ec98f6806ca29609a8efe604634a8b1e8e03d653 in branch patch-1 of repository https://github.com/FlorentATo/microsoft-365-docs into branch public (commit 308f8651a592cb85375b4b2d1a543668197f0e47). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212070558356608-9783/BuildReport?accessString=1271c0765606775eb4a495b008fb92a1e3cc91e427884e2fdf7e618a6644c2c3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 06:02 UTC, opbld30 commented
Learn Build status updates of commit _[799b8f1](https://github.com/FlorentATo/microsoft-365-docs/commits/799b8f17871c22844b46a7bfeb93f8e956db0924)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-76e036d0)

<a id="76e036d0"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 799b8f17871c22844b46a7bfeb93f8e956db0924 in branch patch-1 of repository https://github.com/FlorentATo/microsoft-365-docs into branch public (commit 308f8651a592cb85375b4b2d1a543668197f0e47). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212070601362620-9783/BuildReport?accessString=77a5f670c28f06b218dd5ae2482094bcd81765c119ac256d0de676128d8aa9cc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-07 06:04 UTC, closed without merging

2022-12-07 06:06 UTC, FlorentATo commented
Replaced by https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10472