Included writeup for Teams DLP E5 license enforcement
MicrosoftDocs/microsoft-365-docs pull request #9803
Opened 2022-09-21 23:46 UTC by tanaybaldua

We need to mention the impact of E5 license enforcement that is planned to go live by end of week - 9/23. The new part is just a short description and the existing follow up link will provide more information.

2022-09-21 23:47 UTC, opbld31 commented
Docs Build status updates of commit _[6360366](https://github.com/tanaybaldua/microsoft-365-docs/commits/6360366c02a7b1d7c0138e713c7d15925d06c844)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/tanaybaldua/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/dlp-microsoft-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209212346201790-9803/BuildReport?accessString=b1a539b9065bc14bc40d262153783794718993d57ed897174348e9801f9f7da5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 05:49 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-22 07:26 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-microsoft-teams.md
> +If you are a Microsoft 365 E3/A3/G3 tenant and your organization is currently using DLP protection in Teams, the support for the same will end by March 2023 as Teams DLP is available to organizations
```suggestion
If you are a Microsoft 365 E3/A3/G3 tenant and your organization is currently using DLP protection in Teams, note that support for them will end by March 2023 as Teams DLP is available to organizations with a Microsoft 365 E5/A5/G5 subscription. Post March 2023, for any active DLP policies that include Teams, the policy will not be deleted or removed but the protection for Teams will be deactivated. If the policy includes protection for other workloads like SharePoint Online, OneDrive for Business, and Exchange Online in addition to Teams, the protection will continue to be active for all other workloads except Teams. You will not be able to create any new Teams DLP policy after March 2023. To continue your use of Teams DLP, we recommend you get a Microsoft 365 E5/A5/G5 subscription. You should contact your Business Administrator for assistance.
```

2022-09-22 07:28 UTC, JohanFreelancer9 requested changes
Copy review - @tanaybaldua, kindly commit the the minor suggested changes. Many thanks.

2022-09-23 00:55 UTC, opbld33 commented
Docs Build status updates of commit _[495899d](https://github.com/tanaybaldua/microsoft-365-docs/commits/495899d4e8f028826eebca0720d33126f8c605fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/tanaybaldua/microsoft-365-docs/blob/patch-2/microsoft-365/compliance/dlp-microsoft-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209230052264707-9803/BuildReport?accessString=70f338534ea593dc0b31115358863888031299264b29c014c00c46046b26f58f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 04:45 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-23 12:15 UTC, JohanFreelancer9 approved these changes

2022-09-26 15:18 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-09-27 19:59 UTC, chrfox commented
@tanaybaldua - Hi, thanks for making this update.  We never publish guidance about what may or may not be coming in the future as dates and plans slip. Can you please re-write this to account for what the licensing/functionality is right now. Then when it does change, it can be updated.

2022-09-30 16:40 UTC, tanaybaldua commented
Hi Chris, we have heard your views on the future plan and thus have decided to not have any update done on this page as Iicensing guidance is already present. I will come back to you in case we have to update anything else. thanks for time and support.

2022-10-03 12:13 UTC, closed without merging