Descriptive Link Names
MicrosoftDocs/microsoft-365-docs pull request #982
Opened 2019-12-25 04:25 UTC by JohanFreelancer9

Issue #969

2019-12-25 15:46 UTC, mypil commented on microsoft-365/compliance/service-encryption-with-customer-key-faq.md
> +No. Office 365 Message Encryption and the option to provide and control your own encryption keys with Bring Your Own Key (BYOK) for Azure Information Protection was not designed to respond to law enf
```suggestion
No. Office 365 Message Encryption and the option to provide and control your own encryption keys with Bring Your Own Key (BYOK) for Azure Information Protection was not designed to respond to law enforcement subpoenas. Office 365 Message Encryption with BYOK for AIP was designed for compliance focused customers that need to meet their internal or external compliance obligations. Microsoft takes third-party requests for customer data very seriously. As a cloud service provider, we always advocate for the privacy of customer data. In the event we get a subpoena, we always attempt to redirect the third party to the customer to obtain the information. (Please read Brad Smith's blog: [Protecting customer data from government snooping](https://blogs.microsoft.com/blog/2013/12/04/protecting-customer-data-from-government-snooping/)). We periodically publish detailed information of the request we receive in the [Law Enforcement Requests Report](https://www.microsoft.com/corporate-responsibility/law-enforcement-requests-report).
```

2019-12-25 15:46 UTC, mypil commented on microsoft-365/compliance/service-encryption-with-customer-key-faq.md
> +No. Customer Key was not designed to respond to law enforcement subpoenas. It was designed for regulated customers to meet their internal or external compliance obligations. Microsoft takes third-par
```suggestion
No. Customer Key was not designed to respond to law enforcement subpoenas. It was designed for regulated customers to meet their internal or external compliance obligations. Microsoft takes third-party requests for customer data very seriously. As a cloud service provider, we always advocate for the privacy of customer data. In the event we get a subpoena, we always attempt to redirect the third party to the customer to obtain the information. (Please read Brad Smith's blog: [Protecting customer data from government snooping](https://blogs.microsoft.com/blog/2013/12/04/protecting-customer-data-from-government-snooping/)). We periodically publish detailed information of the request we receive [Law Enforcement Requests Report](https://www.microsoft.com/corporate-responsibility/law-enforcement-requests-report).
```

2019-12-25 15:48 UTC, mypil requested changes
@JohanFreelancer9 - Created this commit to remove the "en-us" from the links. Should this be the case for this PR? Please let me know your thoughts. Thank you.

2019-12-25 17:58 UTC, JohanFreelancer9 commented
@mypil  No, I initially also removed the locale, but then the link does not seem to work - certainly not in Vietnam.

2019-12-25 18:09 UTC, mypil commented
@KCCross - PR has been copy edited and is ready for final review. This is based on issue #969.

Thank you.

cc: @kenwith

2020-01-08 15:20 UTC, mypil commented
@KCCross - We would like to follow up. Any updates on this?

Thank you.

2020-02-14 22:35 UTC, KCCross commented
File no longer exists. Content updated and en-us links removed.

2020-02-14 22:35 UTC, closed without merging