added outlook to the list of protected products
MicrosoftDocs/microsoft-365-docs pull request #983
Opened 2019-12-25 04:52 UTC by MaratMussabekov

#920

2019-12-25 15:57 UTC, mypil commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

2019-12-26 02:41 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md
> +| **Office 365 ProPlus, Office for iOS and Android** <br/>    | When this option is selected, ATP Safe Links protection is applied to URLs in Word, Excel, and PowerPoint files on Windows or Mac OS, e
```suggestion
| **Office 365 ProPlus, Office for iOS and Android** <br/>    | When this option is selected, ATP Safe Links protection is applied to URLs in Word, Excel, and PowerPoint files on Windows or Mac OS, emails in Outlook, Office documents on iOS or Android devices, Visio 2016 on Windows, and the web versions of Office apps (Word, PowerPoint, Excel, Outlook, and OneNote), provided the user has signed in to Office 365. |
```

2019-12-26 02:43 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md
> +| **Don't track when users click ATP Safe Links** <br/>  | When this option is selected, click data for URLs in Word, Excel, PowerPoint, and Visio documents and Outlook emails is not stored.  <br/> |
```suggestion
| **Don't track when users click ATP Safe Links** <br/>  | When this option is selected, click data for URLs in Word, Excel, PowerPoint, Visio documents, and Outlook emails is not stored.  <br/> |
```

2019-12-26 02:43 UTC, JohanFreelancer9 requested changes
Copy Review

2019-12-26 17:46 UTC, mypil commented
@MaratMussabekov - please merge the commit on the copy/edit review done by JohanFreelancer9 or make the necessary changes on the PR following the suggestions made. Thank you.

2019-12-28 11:32 UTC, JohanFreelancer9 approved these changes

2019-12-29 01:11 UTC, mypil commented
@MSFTTracyP - PR has been copy edited and is ready for final review. This is based on issue #920

Thank you.

cc: @kenwith

2019-12-30 17:58 UTC, denisebmsft approved these changes

2019-12-30 17:58 UTC, merged