Update classifier-tc-definitions.md
MicrosoftDocs/microsoft-365-docs pull request #9836
Opened 2022-09-28 17:46 UTC by jenli311

Content updates:
- Added content on regulatory compliance classifiers going to public preview
- Added note on regulatory compliance classifier behavior observed during private preview at the end of classifier list

2022-09-28 17:50 UTC, opbld33 commented
Learn Build status updates of commit _[8c26d0d](https://github.com/jenli311/microsoft-365-docs/commits/8c26d0d805d2a80e8e1545b8d1ae32e27e5f8afe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/classifier-tc-definitions.md](https://github.com/jenli311/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/classifier-tc-definitions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209281746328335-9836/BuildReport?accessString=1c1d232e11a6ae7b8f695fc250ed5dd205c5081ce945035b0f426a96cd78e7b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-28 23:32 UTC, jenli311 commented
@chrfox here is the PR for updating trainable classifiers page with new regulatory compliance classifiers

2022-09-29 10:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/classifier-tc-definitions.md
> +- **Corporate Sabotage (preview)**: Detects messages that may mention acts to damage or destroy  corporate assets or property. This classifier can help customers manage regulatory compliance obligati
```suggestion
- **Corporate Sabotage (preview)**: Detects messages that may mention acts to damage or destroy corporate assets or property. This classifier can help customers manage regulatory compliance obligations such as NERC Critical Infrastructure Protection standards or state-by-state regulations like Chapter 9.05 RCW in Washington state. Detects content in .msg, .docx, .pdf, .txt, .rtf, .jpeg, .jpg, .png, .gif, .bmp, .svg files. 
```

2022-09-29 10:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/classifier-tc-definitions.md
> +- **Gifts & entertainment (preview)**: Detects messages that may suggest exchanging gifts or entertainment in return for service, which violates regulations related to bribery. This classifier can he
```suggestion
- **Gifts & entertainment (preview)**: Detects messages that may suggest exchanging gifts or entertainment in return for service, which violates regulations related to bribery. This classifier can help customers manage regulatory compliance obligations such as Foreign Corrupt Practices Act (FCPA), UK Bribery Act, and FINRA Rule 2320. Detects content in .msg, .docx, .pdf, .txt, .rtf, .jpeg, .jpg, .png, .gif, .bmp, .svg files.
```

2022-09-29 10:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/classifier-tc-definitions.md
> +- **Money laundering (preview)**: Detects signs that may suggest money laundering or engagement in acts to conceal or disguise the origin or destination of proceeds. This classifier can help customer
```suggestion
- **Money laundering (preview)**: Detects signs that may suggest money laundering or engagement in acts to conceal or disguise the origin or destination of proceeds. This classifier can help customers manage regulatory compliance obligations such as the Bank Secrecy Act, the USA Patriot Act, FINRA Rule 3310, and the Anti-Money Laundering Act of 2020. Detects content in .msg, .docx, .pdf, .txt, .rtf, .jpeg, .jpg, .png, .gif, .bmp, .svg files.
```

2022-09-29 10:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/classifier-tc-definitions.md
> +- **Regulatory collusion (preview)**: Detects    messages that may violate regulatory anti-collusion requirements such as an attempted concealment of sensitive information. This classifier can help c
```suggestion
- **Regulatory collusion (preview)**: Detects messages that may violate regulatory anti-collusion requirements such as an attempted concealment of sensitive information. This classifier can help customers manage regulatory compliance obligations such as the Sherman Antitrust Act, Securities Exchange Act 1933, Securities Exchange Act of 1934, Investment Advisers Act of 1940, Federal Commission Act, and Robinson-Patman Act. Detects content in .msg, .docx, .pdf, .txt, .rtf, .jpeg, .jpg, .png, .gif, .bmp, .svg files.  
```

2022-09-29 10:55 UTC, JohanFreelancer9 commented on microsoft-365/compliance/classifier-tc-definitions.md
> +- **Stock manipulation (preview)**: Detects signs of possible stock manipulation, such as recommendations to buy, sell or hold stocks that may suggest an attempt to manipulate the stock price. This c
```suggestion
- **Stock manipulation (preview)**: Detects signs of possible stock manipulation, such as recommendations to buy, sell, or hold stocks that may suggest an attempt to manipulate the stock price. This classifier can help customers manage regulatory compliance obligations such as the Securities Exchange Act of 1934, FINRA Rule 2372, and FINRA Rule 5270. Detects content in .msg, .docx, .pdf, .txt, .rtf, .jpeg, .jpg, .png, .gif, .bmp, .svg files.  
```

2022-09-29 11:00 UTC, JohanFreelancer9 commented on microsoft-365/compliance/classifier-tc-definitions.md
> +> For a temporary solution to address large volumes of bulk sender/newsletter content, add the **Message is not sent to any of these domains condition** with a list of domains to exclude.
```suggestion
> The **Corporate sabotage, Gifts & entertainment, Money laundering, Regulatory collusion, Stock Manipulation, and Unauthorized disclosure classifiers** may capture a large volume of bulk sender/newsletter content due to a known issue in development. This behavior will be resolved in the near future. 
>
> For a temporary solution to address large volumes of bulk sender/newsletter content, add the **Message is not sent to any of these domains condition** with a list of domains to exclude. 
```

2022-09-29 11:05 UTC, JohanFreelancer9 requested changes
Copy review - @jenli311, kindly commit the suggested changes. Please note that Microsoft docs does not publish definite dates as dates and plans may slip. Many thanks

2022-09-29 16:17 UTC, opbld32 commented
Learn Build status updates of commit _[ecdc862](https://github.com/jenli311/microsoft-365-docs/commits/ecdc86288de6b8b63142a36fba6a43cfdf31ebf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/classifier-tc-definitions.md](https://github.com/jenli311/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/classifier-tc-definitions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209291615290330-9836/BuildReport?accessString=569646ddeaab2566b2c7306ace602bbc4c190eb987df98bfbd788a9e1068e6ca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 16:21 UTC, opbld30 commented
Learn Build status updates of commit _[1fc7d22](https://github.com/jenli311/microsoft-365-docs/commits/1fc7d228b4f7ddd06686fbfa403379f45a14aae9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/classifier-tc-definitions.md](https://github.com/jenli311/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/classifier-tc-definitions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209291617518294-9836/BuildReport?accessString=d3d4631a4b6d625422f1111cfa7a8c80bc73c39a20a607d99db85b0f79f7560b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 16:36 UTC, chrfox reviewed
@jenli311 please review and approve these changes. When do you want these to go live?

2022-09-30 06:29 UTC, JohanFreelancer9 approved these changes

2022-10-06 20:27 UTC, jenli311 commented on microsoft-365/compliance/classifier-tc-definitions.md
> +- **Gifts & entertainment (preview)**: Detects messages that may suggest exchanging gifts or entertainment in return for service, which violates regulations related to bribery. This classifier can he
good catch!

2022-10-06 20:28 UTC, jenli311 commented on microsoft-365/compliance/classifier-tc-definitions.md
> +- **Money laundering (preview)**: Detects signs that may suggest money laundering or engagement in acts to conceal or disguise the origin or destination of proceeds. This classifier can help customer
good catch, agree with changes

2022-10-06 20:32 UTC, jenli311 reviewed
changes look good to me, approved on my end!

2022-10-06 21:05 UTC, opbld33 commented
Learn Build status updates of commit _[26d3bf5](https://github.com/jenli311/microsoft-365-docs/commits/26d3bf5d51ddb291a4bea1e76242a39e6dc92f74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/classifier-tc-definitions.md](https://github.com/jenli311/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/classifier-tc-definitions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210062103471625-9836/BuildReport?accessString=f5dd2c753788dd1b35d8f6fa636af1499cbb3e793fa0af7fae7ebf9af12a088f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 21:14 UTC, chrfox commented
publish this on 10/20

2022-10-17 15:11 UTC, opbld30 commented
Learn Build status updates of commit _[26d3bf5](https://github.com/jenli311/microsoft-365-docs/commits/26d3bf5d51ddb291a4bea1e76242a39e6dc92f74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/classifier-tc-definitions.md](https://github.com/jenli311/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/classifier-tc-definitions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210171507522641-9836/BuildReport?accessString=1f76b114e30f4e0ec62bdfdc306b78db3c33c8119c4feb2d397a13e28bdfa762).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 18:01 UTC, opbld33 commented
Learn Build status updates of commit _[f58008a](https://github.com/jenli311/microsoft-365-docs/commits/f58008ae2affcd269d40ee2ea95811565fb5d7ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/classifier-tc-definitions.md](https://github.com/jenli311/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/classifier-tc-definitions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210211759036591-9836/BuildReport?accessString=24446dc443487fd4ace2fd1d260d3f62b90a2d780562e70f8a73a357317ba687).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 18:03 UTC, opbld30 commented
Learn Build status updates of commit _[1e3b7a4](https://github.com/jenli311/microsoft-365-docs/commits/1e3b7a4f6bec25b8368129692ab3b279fdb0f542)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/classifier-tc-definitions.md](https://github.com/jenli311/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/classifier-tc-definitions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210211759251886-9836/BuildReport?accessString=58782bb821ae82b5e6038c91fc08395cb1a3ba8061073719e4d612ae7c029130).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 18:05 UTC, merged