Update yammer-device-usage-report-ww.md
MicrosoftDocs/microsoft-365-docs pull request #9837
Opened 2022-09-28 17:52 UTC by eeffaann

Listed out examples of clients that are included in Other.

2022-09-28 18:00 UTC, opbld33 commented
Learn Build status updates of commit _[6d2c279](https://github.com/eeffaann/microsoft-365-docs/commits/6d2c279d4ec1e6e2b9d1164ae686568e9687d24d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md](https://github.com/eeffaann/microsoft-365-docs/blob/patch-1/microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209281752514108-9837/BuildReport?accessString=07a3513fc3e17757a0a97811288e16066ab189f7be26f0ec2ee2a6df8e2d711c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 11:07 UTC, JohanFreelancer9 commented on microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md
> +|other  <br/> |Indicates if the user has used Yammer on another client, not listed previously. This includes Yammer Embed, SharePoint Web Part, Viva Engage, and select Outlook emails.  <br/>|
```suggestion
|other  <br/> |Indicates if the user has used Yammer on another client, not listed previously. This includes Yammer Embed, SharePoint Web Part, Viva Engage, and selected Outlook emails.  <br/>|
```

2022-09-29 11:09 UTC, JohanFreelancer9 requested changes
Copy review - @eeffaann, kindly commit the suggested change. Many thanks.

2022-09-29 16:06 UTC, opbld32 commented
Learn Build status updates of commit _[2e3b712](https://github.com/eeffaann/microsoft-365-docs/commits/2e3b7122a07f7a704a60c0ba467e3899b48945d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md](https://github.com/eeffaann/microsoft-365-docs/blob/patch-1/microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209291604056360-9837/BuildReport?accessString=6b60caa47f6dea624db1f9c12d011dc50bbb8eff541b17c079d13480350a62f2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 06:09 UTC, JohanFreelancer9 approved these changes

2022-09-30 16:17 UTC, opbld30 commented
Learn Build status updates of commit _[72941f0](https://github.com/eeffaann/microsoft-365-docs/commits/72941f054e92942d1a6d8c5efbc0639325991ef6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md](https://github.com/eeffaann/microsoft-365-docs/blob/patch-1/microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202209301613364789-9837/BuildReport?accessString=9088e2b3d4cf8b70e9b532f0badd6abfc41e8efe1dd761087572a6e0841a553f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 11:18 UTC, yogkumgit commented
@camillepack Please merge this PR. Thanks

2022-10-07 16:52 UTC, opbld31 commented
Learn Build status updates of commit _[d44e7aa](https://github.com/eeffaann/microsoft-365-docs/commits/d44e7aa0aea2925595e465daac717b8c32853bed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md](https://github.com/eeffaann/microsoft-365-docs/blob/patch-1/microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210071650211048-9837/BuildReport?accessString=cf4c24354dde7216a51d822bd198f3b8db5dbf68dbd9ba32877b5b828746a328).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 22:52 UTC, opbld33 commented
Learn Build status updates of commit _[377bd10](https://github.com/eeffaann/microsoft-365-docs/commits/377bd101d60d2ee7c37bfe1c55bbf89d4944fba2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md](https://github.com/eeffaann/microsoft-365-docs/blob/patch-1/microsoft-365/admin/activity-reports/yammer-device-usage-report-ww.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210132248513909-9837/BuildReport?accessString=ccbf45f66f1dc6fb9e8fe2a555903d42a518dad9d70962c40563caaca60313af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 22:54 UTC, merged