Update adoption-score.md
MicrosoftDocs/microsoft-365-docs pull request #9867
Opened 2022-10-03 06:37 UTC by msbemba

Adoption score not available in GCC.

per issue #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9814

No other reference document.

2022-10-03 06:38 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-03 06:39 UTC, opbld30 commented
Learn Build status updates of commit _[7684bb0](https://github.com/msbemba/microsoft-365-docs/commits/7684bb08029223b5fc8dfe1957279b3d08858ab8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/adoption/adoption-score.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1253/microsoft-365/admin/adoption/adoption-score.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210030638018421-9867/BuildReport?accessString=597b97054b6eab7b92f651747071d23304a2fbc1e3e75ebda02d9308476d6618).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 08:36 UTC, JohanFreelancer9 commented on microsoft-365/admin/adoption/adoption-score.md
> +> This feature is not available in GCC High, GCC and DOD tenants.
```suggestion
> This feature is not available in GCC High, GCC, and DOD tenants.
```

2022-10-03 08:36 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-03 09:50 UTC, opbld32 commented
Learn Build status updates of commit _[a2685a9](https://github.com/msbemba/microsoft-365-docs/commits/a2685a9fbcb2710f64a9cec925d329bbf8d4b4ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/adoption/adoption-score.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1253/microsoft-365/admin/adoption/adoption-score.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210030947170605-9867/BuildReport?accessString=82e3eea7a2d7b24e2cf505e33e08cc3357218c0ef352bba5234cd19d7c9e68e8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 12:42 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-03 12:42 UTC, yogkumgit commented
@efrene

2022-10-03 15:38 UTC, JohanFreelancer9 approved these changes

2022-10-14 13:39 UTC, yogkumgit commented
@efrene Gentle reminder.

2022-10-14 16:26 UTC, opbld30 commented
Learn Build status updates of commit _[b2d12b8](https://github.com/msbemba/microsoft-365-docs/commits/b2d12b89ba34f9fe7fdeeda0ba63b760b922acd5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/adoption/adoption-score.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1253/microsoft-365/admin/adoption/adoption-score.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210141624131245-9867/BuildReport?accessString=e0b2541b356e22219da4be66437b65c09a4fb5ad4d4d96d10cf656d22347116d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 16:28 UTC, merged