Update flw-onboarding-wizard.md
MicrosoftDocs/microsoft-365-docs pull request #9883
Opened 2022-10-05 13:31 UTC by msbemba

Updated navigation to play the video

2022-10-05 13:31 UTC, msbemba commented
@JohanFreelancer9 Please copy review

Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9841****

2022-10-05 14:15 UTC, opbld32 commented
Learn Build status updates of commit _[9f6825a](https://github.com/msbemba/microsoft-365-docs/commits/9f6825a5d324c9972119d54282f51e00c812f178)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/frontline/flw-onboarding-wizard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1254/microsoft-365/frontline/flw-onboarding-wizard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210051413093926-9883/BuildReport?accessString=6a09e69e275d81cbd1e882a87eabb7cad28a7c17f50fb68e908ac9a22affe846).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 15:08 UTC, JohanFreelancer9 commented on microsoft-365/frontline/flw-onboarding-wizard.md
> +1. In the left navigation of the [Microsoft 365 admin center](https://admin.microsoft.com/), choose **Setup**. Go to the **Apps and email** section, and then under **Get your frontline workforce up a
```suggestion
1. In the left navigation of the [Microsoft 365 admin center](https://admin.microsoft.com/), choose **Setup**. Go to the **Apps and email** section, and then under **Get your frontline workforce up and running**, select **Video** to learn more about the capabilities that Microsoft 365 for frontline workers offers.
```

2022-10-05 15:08 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-05 16:30 UTC, opbld31 commented
Learn Build status updates of commit _[052efe2](https://github.com/msbemba/microsoft-365-docs/commits/052efe2cebf433afa20c7b25d8c093842771ec68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/frontline/flw-onboarding-wizard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1254/microsoft-365/frontline/flw-onboarding-wizard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210051628231482-9883/BuildReport?accessString=4345ee3a57f618d7cf79cc659b0ff867dd841230ef71b20ef27a79d0db8b497f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 02:23 UTC, JohanFreelancer9 approved these changes

2022-10-06 05:29 UTC, yogkumgit commented
@LanaChin Please merge this PR. Thanks

2022-10-07 11:09 UTC, yogkumgit commented
@LanaChin Gentle reminder, please merge this PR. Thanks

2022-12-08 20:42 UTC, opbld30 commented
Learn Build status updates of commit _[ca4d045](https://github.com/msbemba/microsoft-365-docs/commits/ca4d0455b6cab353949c424fc2e9df978d0424a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/frontline/flw-onboarding-wizard.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1254/microsoft-365/frontline/flw-onboarding-wizard.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082040402700-9883/BuildReport?accessString=31c900ad094f07a33b8362942feaf55cc62b46399c5af32c2290d14150fc0367).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-23 16:57 UTC, samanro commented
Updating in separate PR: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/18576

2023-01-23 16:57 UTC, closed without merging