Update create-a-dlp-policy-from-a-template.md
MicrosoftDocs/microsoft-365-docs pull request #9885
Opened 2022-10-05 13:43 UTC by msbemba

Made changes to the steps as we are not able to add M365 groups as members to the role group.

2022-10-05 13:43 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9852

2022-10-05 13:43 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-05 14:17 UTC, opbld31 commented
Learn Build status updates of commit _[905498c](https://github.com/msbemba/microsoft-365-docs/commits/905498c9e52feb262d33970a689fd5f64a156229)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/create-a-dlp-policy-from-a-template.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1256/microsoft-365/compliance/create-a-dlp-policy-from-a-template.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210051415035732-9885/BuildReport?accessString=7340691bbcc46726e71e29fb51b35699543e385a14a868748f355ff964074000).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 15:17 UTC, JohanFreelancer9 commented on microsoft-365/compliance/create-a-dlp-policy-from-a-template.md
>  Use the **View-Only DLP Compliance Management** role to create role group with view-only privileges to the DLP policies and DLP reports.
```suggestion
Use the **View-Only DLP Compliance Management** role to create a role group with view-only privileges to the DLP policies and DLP reports.
```

2022-10-05 15:18 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-05 16:30 UTC, opbld31 commented
Learn Build status updates of commit _[973a3e1](https://github.com/msbemba/microsoft-365-docs/commits/973a3e12ff6aa01c9a1f047682876313babba4bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/create-a-dlp-policy-from-a-template.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1256/microsoft-365/compliance/create-a-dlp-policy-from-a-template.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210051628117993-9885/BuildReport?accessString=f7805da5c151b82603cb277b9ed89a787c02c7fbaa466dbad474d00c1651f004).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 02:31 UTC, JohanFreelancer9 approved these changes

2022-10-06 05:34 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-10-20 12:12 UTC, yogkumgit commented
@chrfox Gentle reminder

2022-12-08 20:42 UTC, opbld33 commented
Learn Build status updates of commit _[e39acb7](https://github.com/msbemba/microsoft-365-docs/commits/e39acb756e7dc869214e99f2d9e3d86679ec326a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/create-a-dlp-policy-from-a-template.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1256/microsoft-365/compliance/create-a-dlp-policy-from-a-template.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082040471559-9885/BuildReport?accessString=3e0f12dd57f49036e8f92a539e8026268aef7d6eac9478c2c34f3cf7676412ec).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-02-01 03:18 UTC, chrfox commented
article retired

2023-02-01 03:18 UTC, closed without merging