DLP For Mac Updates
MicrosoftDocs/microsoft-365-docs pull request #9891
Opened 2022-10-06 07:37 UTC by danwdavey

Line 403: either needs to be ammended to state Mac OS DLP for Endpoint, or removing. Confirmed "Both Outlook mobile/ and Outlook Mac do not support policy tips today."

Line: 396: Outlook Mac should be its own line item

2022-10-06 07:39 UTC, opbld31 commented
Learn Build status updates of commit _[4fee40b](https://github.com/danwdavey/microsoft-365-docs/commits/4fee40bd1cdab59964f8b0f6d750ec277d8d9bef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-policy-tips-reference.md](https://github.com/danwdavey/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/dlp-policy-tips-reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210060737479160-9891/BuildReport?accessString=8b3eb9dd5eb1a8cad062aac46cee1888bd47c484a7916c55900b8a9cc80c065d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 05:59 UTC, JohanFreelancer9 commented on microsoft-365/compliance/dlp-policy-tips-reference.md
> +|**Outlook Mac**|:::image type="icon" source="../media/crsmrk.png" border="false":::|none|none|DLP policy tips are not supported on Outlook mobile|
```suggestion
|**Outlook for Mac**|:::image type="icon" source="../media/crsmrk.png" border="false":::|none|none|DLP policy tips are not supported on Outlook mobile|
```

2022-10-07 06:02 UTC, JohanFreelancer9 requested changes
Copy review - @danwdavey, kindly commit the minor suggested change. Also, please change line 404 to "Endpoint DLP policies are...".Many thanks.

2022-10-07 21:37 UTC, chrfox commented
@danwdavey  -Thanks for your comment.  I am confirming with PG before publishing

2022-10-10 08:29 UTC, danwdavey commented on microsoft-365/compliance/dlp-policy-tips-reference.md
> +|**Outlook Mac**|:::image type="icon" source="../media/crsmrk.png" border="false":::|none|none|DLP policy tips are not supported on Outlook mobile|
I think it should state 'DLP policy tips are not supported on Outlook for Mac' ?

2022-10-10 08:31 UTC, danwdavey commented
> @danwdavey -Thanks for your comment. I am confirming with PG before publishing

@chrfox - Added comment above, edit needs to state Outlook for Mac, not outlook for Mobile

2022-10-20 12:13 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-20 14:17 UTC, JohanFreelancer9 approved these changes

2022-10-21 11:37 UTC, yogkumgit commented
@chrfox Please merge this PR. Thanks

2022-10-28 18:01 UTC, opbld33 commented
Learn Build status updates of commit _[c9ec130](https://github.com/danwdavey/microsoft-365-docs/commits/c9ec13096854bdb453b4e4440edfadb8fe023e6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-policy-tips-reference.md](https://github.com/danwdavey/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/dlp-policy-tips-reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210281759438451-9891/BuildReport?accessString=f735824c0e10276d347c1815a475500a19875cb953a011088e66b8a8a7564683).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 10:01 UTC, danwdavey commented
The article is still wrong;
DLP policy tips are not supported on Outlook mobile

This **should** read: 

DLP policy tips are not supported on Outlook Mac



<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>

2022-11-08 10:02 UTC, opbld32 commented
Learn Build status updates of commit _[58c3d33](https://github.com/danwdavey/microsoft-365-docs/commits/58c3d33db37ea68db6e6108f83b7d7700e178d8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-policy-tips-reference.md](https://github.com/danwdavey/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/dlp-policy-tips-reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211081000589245-9891/BuildReport?accessString=a0ff737e65a272e2704a19fd2aba5830b0b0e139f841dd17f038ceafd5ea1c5a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 11:33 UTC, JohanFreelancer9 requested changes
@danwdavey, could you please commit the suggested change to make the correction?

2022-11-08 11:42 UTC, opbld30 commented
Learn Build status updates of commit _[a4d6056](https://github.com/danwdavey/microsoft-365-docs/commits/a4d605622f6a4faf7c8650d1af19d605229e506e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/compliance/dlp-policy-tips-reference.md](https://github.com/danwdavey/microsoft-365-docs/blob/patch-1/microsoft-365/compliance/dlp-policy-tips-reference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211081139582425-9891/BuildReport?accessString=762f0875bf1aa2470b7b7749d076ef125a526f9456cce5dec1b0c614cb513003).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 12:04 UTC, JohanFreelancer9 approved these changes

2023-04-21 18:27 UTC, chrfox commented
final query out to Swati Kumari to see if this is correct

2023-04-21 20:28 UTC, merged