Update ipv6-support.md
MicrosoftDocs/microsoft-365-docs pull request #9895
Opened 2022-10-06 17:07 UTC by roshansabapaty

This statement "Microsoft 365 services can be successfully used from both IPv6 dual stack and IPv6-only devices" is not true. Modified this to "Microsoft 365 services can be successfully used from both IPv6 dual stack and IPv6-only devices (requires translation technologies such as DNS64/NAT64 for IPv6-only devices)". Please reach out to roshanp (MS alias) for any questions or concerns.

2022-10-06 17:09 UTC, opbld30 commented
Learn Build status updates of commit _[e8ca226](https://github.com/roshansabapaty/microsoft-365-docs/commits/e8ca2267a4ef96c4232e6b613a3f7fa63022bf7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/ipv6-support.md](https://github.com/roshansabapaty/microsoft-365-docs/blob/patch-2/microsoft-365/enterprise/ipv6-support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210061707507716-9895/BuildReport?accessString=f6ae50dd370fdfc6bd1b5dd3868df75696bd8d6f204226264f477dce4d441d54).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 06:09 UTC, JohanFreelancer9 commented on microsoft-365/enterprise/ipv6-support.md
> +With the growing adoption and support of IPv6 across enterprise networks, service providers and devices, many customers are wondering if their users can continue to access Microsoft 365 services from
```suggestion
With the growing adoption and support of IPv6 across enterprise networks, service providers, and devices, many customers are wondering if their users can continue to access Microsoft 365 services from IPv6 clients and IPv6 networks. Microsoft 365 services can be successfully used from both IPv6 dual stack and IPv6-only devices (IPv6-only devices require translation technologies such as DNS64 or NAT64). In fact, we have an increasing number of customers, from consumers to large enterprises, who are moving towards greater adoption of IPv6. For most customers, IPv4 won't completely disappear from their digital landscape, so we aren't planning to require IPv6 or to de-prioritize IPv4 in any Microsoft 365 features or services.
```

2022-10-07 06:10 UTC, JohanFreelancer9 requested changes
Copy review - @roshansabapaty, kindly commit the suggested change. Many thanks.

2022-10-07 20:57 UTC, opbld31 commented
Learn Build status updates of commit _[bdfe3df](https://github.com/roshansabapaty/microsoft-365-docs/commits/bdfe3df519babb6934b57287db08217edd78d920)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/ipv6-support.md](https://github.com/roshansabapaty/microsoft-365-docs/blob/patch-2/microsoft-365/enterprise/ipv6-support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210072055197690-9895/BuildReport?accessString=b9e69f7a23a409f05eb9905be7d94140c856b3664b96c9c56808efcb128a9242).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 08:14 UTC, JohanFreelancer9 approved these changes

2022-10-10 21:03 UTC, opbld33 commented
Learn Build status updates of commit _[634db13](https://github.com/roshansabapaty/microsoft-365-docs/commits/634db13f3f6c22df49c8be92b3a54e3f23fef264)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/ipv6-support.md](https://github.com/roshansabapaty/microsoft-365-docs/blob/patch-2/microsoft-365/enterprise/ipv6-support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210102059026612-9895/BuildReport?accessString=24d9c93628c76afd6ada6f1cba986fe32f5d8a93bf9f89e37251633785fa7784).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 21:03 UTC, roshansabapaty commented
@kelleyvice-msft  can you please approve this change in the public branch?

2022-10-14 21:36 UTC, opbld32 commented
Learn Build status updates of commit _[678cbf7](https://github.com/roshansabapaty/microsoft-365-docs/commits/678cbf70cd6de5b03f08b9dc444c546d132dd106)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/enterprise/ipv6-support.md](https://github.com/roshansabapaty/microsoft-365-docs/blob/patch-2/microsoft-365/enterprise/ipv6-support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210142134299793-9895/BuildReport?accessString=85351f887d9a6c5e68e874ae4e962793187649eda09d523ccdaf231b18d1533f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 21:36 UTC, merged