Update migrate-files-migration-manager.md
MicrosoftDocs/microsoft-365-docs pull request #9940
Opened 2022-10-12 08:35 UTC by msbemba

added information that currently this Migration Manager Google isn't available for any of the Government clouds.

2022-10-12 08:35 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9912

2022-10-12 08:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-12 08:37 UTC, opbld30 commented
Learn Build status updates of commit _[6a985ac](https://github.com/msbemba/microsoft-365-docs/commits/6a985ac0ff51b3ae0dd7bafa7004790d492bf1ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1266/microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210120835285405-9940/BuildReport?accessString=a87c816f945e78f7b6d4ac1191a4cb7ebc0de72bf9b2248a319489930c237bf5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 10:25 UTC, JohanFreelancer9 commented on microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md
> +Currently this Migration Manager Google isn't available for any of the Government clouds.
```suggestion
> [!NOTE]
> Currently, Migration Manager isn't available for Google on any of the Government clouds.
```

2022-10-12 10:26 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-12 11:36 UTC, opbld33 commented
Learn Build status updates of commit _[eb953a7](https://github.com/msbemba/microsoft-365-docs/commits/eb953a7e653e1de6583817f6f1ee6a26aa77f560)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1266/microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210121131449092-9940/BuildReport?accessString=a734902618a28593b2c97cf1fa2f9e031ce45afcab15fabfedb10132b0cf6e82).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 13:17 UTC, JohanFreelancer9 approved these changes

2022-10-13 14:06 UTC, yogkumgit commented
@efrene Please merge this Pr. Thanks

2022-10-13 16:36 UTC, efrene commented
Hi Yogesh,
I'm waiting to hear back from a PM on this to make sure it is true before merging.
Thanks,
Efren


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: Yogesh Kumar ***@***.***>
Sent: Thursday, October 13, 2022 7:06 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Efren Edwards ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Update migrate-files-migration-manager.md (PR #9940)


@efrene<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fefrene&data=05%7C01%7Cefrene%40microsoft.com%7C46d1e87b85864721527708daad242864%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638012668074700816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hulBIdFeIuY7c0rr0QynExx4QzjUVuo80ciBBI%2FbhYQ%3D&reserved=0> Please merge this Pr. Thanks

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fpull%2F9940%23issuecomment-1277670570&data=05%7C01%7Cefrene%40microsoft.com%7C46d1e87b85864721527708daad242864%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638012668074700816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1Y3Sd35sCWT5YidPF3OV72QEZtSdkG1RVM17xPtw7Qs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHD5ZOBUSIVXVDSWGRHX5BLWDAJPHANCNFSM6AAAAAARDBON6E&data=05%7C01%7Cefrene%40microsoft.com%7C46d1e87b85864721527708daad242864%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638012668074700816%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vTFXZktf0KlGt1v1PSd%2FG78%2B4uQcpIM5S5OzGHFuh%2FE%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-12-08 20:43 UTC, opbld31 commented
Learn Build status updates of commit _[da7b51f](https://github.com/msbemba/microsoft-365-docs/commits/da7b51f6ccf9471d88dc226926e4881ed0c3aed6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1266/microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212082041129647-9940/BuildReport?accessString=a1d1c25e10fdd8d817426e1e24d61a6a80f16f79bb5812c39cdd02e5a116346c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-12 20:03 UTC, opbld33 commented
Learn Build status updates of commit _[f2c6821](https://github.com/msbemba/microsoft-365-docs/commits/f2c6821ae1cc11d18ebca3996149e77a81d2804a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1266/microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202212122002046224-9940/BuildReport?accessString=43a094914da69348abeb20297735f974bad145f74017873395cea003d7545de8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-12 20:04 UTC, merged