Update minimum-requirements.md
MicrosoftDocs/microsoft-365-docs pull request #9951
Opened 2022-10-13 15:02 UTC by andrewjohnporter

2022-10-13 15:04 UTC, opbld30 commented
Learn Build status updates of commit _[ceeae84](https://github.com/andrewjohnporter/microsoft-365-docs/commits/ceeae84fe4bb20e24090b5c4a7dbcee1bda0c053)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/andrewjohnporter/microsoft-365-docs/blob/patch-2/microsoft-365/security/defender-endpoint/minimum-requirements.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210131502080553-9951/BuildReport?accessString=5e369ac9798d4852785af94af33525df82a0f1a806dea8d42e815ce86bd8399c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 05:43 UTC, JohanFreelancer9 commented on microsoft-365/security/defender-endpoint/minimum-requirements.md
> +The display name of this service is Connected User Experiences and Telemetry
```suggestion
The display name of this service is _Connected User Experiences and Telemetry_.
```

2022-10-14 05:44 UTC, JohanFreelancer9 requested changes
Copy review - @andrewjohnporter, kindly commit the suggested change. Many thanks.

2022-10-14 15:13 UTC, opbld32 commented
Learn Build status updates of commit _[69707fa](https://github.com/andrewjohnporter/microsoft-365-docs/commits/69707fa487cf9d5fe3b13f3e69a9447faac8300d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/andrewjohnporter/microsoft-365-docs/blob/patch-2/microsoft-365/security/defender-endpoint/minimum-requirements.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210141511103138-9951/BuildReport?accessString=a1b9e003a53bc7a98ec95c5b24356c008f40a25b6d4b0c6bc644feca132f2844).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 10:50 UTC, JohanFreelancer9 approved these changes

2022-10-20 12:18 UTC, yogkumgit commented
@mjcaparas Please merge this PR. Thanks

2022-10-25 16:52 UTC, opbld33 commented
Learn Build status updates of commit _[8928145](https://github.com/andrewjohnporter/microsoft-365-docs/commits/8928145fad770ba3ecf582449152bb90560aa7ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/andrewjohnporter/microsoft-365-docs/blob/patch-2/microsoft-365/security/defender-endpoint/minimum-requirements.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210251651002044-9951/BuildReport?accessString=272f17e93b0de93cef2a93a076022295564d031fc0765bc8fc99a851249c00b5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-25 16:53 UTC, merged