Fixing broken link
MicrosoftDocs/microsoft-365-docs pull request #9959
Opened 2022-10-14 16:13 UTC by gatesry

Fixing broken link

2022-10-14 16:15 UTC, opbld30 commented
Learn Build status updates of commit _[f64c675](https://github.com/gatesry/microsoft-365-docs/commits/f64c6750c936ca53d9ee301a07c969c473dccb3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md](https://github.com/gatesry/microsoft-365-docs/blob/patch-3/microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210141613427325-9959/BuildReport?accessString=b31a12f90dd3536ec482a62e6561a7e324b4e212b3c46796f4258feb783d8a08).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-15 07:07 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md
> +Admins can follow the [recommended bulk threshold values](recommended-settings-for-eop-and-office365.md#anti-spam-anti-malware-and-anti-phishing-protection-in-eop) bulk threshold values or choose a b
```suggestion
Admins can follow the [recommended bulk threshold values](recommended-settings-for-eop-and-office365.md#anti-spam-anti-malware-and-anti-phishing-protection-in-eop) or choose a bulk threshold value that suits the needs of their organization.
```

2022-10-15 07:08 UTC, JohanFreelancer9 requested changes
Copy review - @gatesry, kindly commit the additional suggested change, please.

2022-10-17 17:12 UTC, opbld30 commented
Learn Build status updates of commit _[2216b45](https://github.com/gatesry/microsoft-365-docs/commits/2216b455be711370a872d7e3c1c5d5140621b1fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md](https://github.com/gatesry/microsoft-365-docs/blob/patch-3/microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210171710437284-9959/BuildReport?accessString=79e3bd77d3955161852811b6b6d41e739829a3c3ca235c78ed80e071eec10656).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 17:16 UTC, opbld31 commented
Learn Build status updates of commit _[93a507c](https://github.com/gatesry/microsoft-365-docs/commits/93a507cde05dc293eb45bf22202948303d27e266)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md](https://github.com/gatesry/microsoft-365-docs/blob/patch-3/microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210171711290674-9959/BuildReport?accessString=f0c77c27239a562ebd20e55fd76e90313ed83c70c9861380f45ae065cbc7ade8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 17:21 UTC, merged

2022-10-17 19:12 UTC, gatesry commented
@JohanFreelancer9 - Apologies, was AFK and couldn't review in time. Thank you for merging!