Update index.md
MicrosoftDocs/microsoft-365-docs pull request #9966
Opened 2022-10-17 05:44 UTC by msbemba

Added a section for onenote

2022-10-17 05:44 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-17 05:44 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9937

2022-10-17 05:46 UTC, opbld33 commented
Learn Build status updates of commit _[6cac6b6](https://github.com/msbemba/microsoft-365-docs/commits/6cac6b6e156251039ba872b615dbf24afceb819d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-16f17cbc)

<a id="16f17cbc"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210170544136049-9966/BuildReport?accessString=447212cdbdb479cb0103c27e557ecdd7228c670a104c489f6027f1a40120aa7d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 08:23 UTC, JohanFreelancer9 commented on microsoft-365/lti/index.md
> +OneNote Class Notebook LTI can work with your Learning Management System.Use OneNote Class Notebook with your LMS to create a shared notebook and link it to your course. Students enrolled in your LMS
```suggestion
OneNote Class Notebook LTI can be used with your Learning Management System (LMS) to create a shared notebook and link it to your course. Students enrolled in your LMS course can access the notebook automatically without you having to add their names. For configuration steps, see [Microsoft OneNote Class Notebook LTI(https://www.onenote.com/lti/integratelti).
```

2022-10-17 08:28 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-17 09:23 UTC, opbld33 commented
Learn Build status updates of commit _[2fff349](https://github.com/msbemba/microsoft-365-docs/commits/2fff349e36b389464d7c41bd4a90739631947a57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/lti/index.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1271/microsoft-365/lti/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210170918025320-9966/BuildReport?accessString=c93e43c3c099b0b0a4c017dce02635f2712d56404b3aee5d8b058800e669d8e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 10:17 UTC, JohanFreelancer9 approved these changes

2022-10-17 11:47 UTC, yogkumgit commented
@DaniEASmith Please merge this PR. Thanks

2022-10-18 13:17 UTC, opbld31 commented
Learn Build status updates of commit _[ac2f19c](https://github.com/msbemba/microsoft-365-docs/commits/ac2f19cc1a6603bbd9a64fc3ac81b1bcb887ec41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/lti/index.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1271/microsoft-365/lti/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210181315335402-9966/BuildReport?accessString=79842f3d0d99276e004c2a558b3f40d99985e348c1a1f144f3eef22580b62edf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 13:18 UTC, merged