Update set-scheduling-policies.md
MicrosoftDocs/microsoft-365-docs pull request #9979
Opened 2022-10-18 10:14 UTC by msbemba

updated the document to reflect the minimum lead time reflects regular hours

2022-10-18 10:14 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-10-18 10:14 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9964

2022-10-18 10:16 UTC, opbld32 commented
Learn Build status updates of commit _[06774a7](https://github.com/msbemba/microsoft-365-docs/commits/06774a76e8fef1491b7abad7cdbfd6cfebac917a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/set-scheduling-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1278/microsoft-365/bookings/set-scheduling-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210181014264968-9979/BuildReport?accessString=3d2b07b3f7dff818aa62ffb7cf0c9aa51ef5805a99308dc69b0e13cf47eb7943).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-18 13:34 UTC, JohanFreelancer9 commented on microsoft-365/bookings/set-scheduling-policies.md
> +| Lead time in hours | You build your staffing plan based on the appointments that are scheduled so it's important to know in advance how many customers are coming in for service on any particular da
```suggestion
| Lead time in hours | You build your staffing plan based on the appointments that are scheduled so it's important to know in advance how many customers are coming in for service on any particular day. The lead time policy enables you to specify the number of hours in advance that customers must book or cancel an appointment. The minimum lead time is based on regular hours and not business hours.|
```

2022-10-18 13:35 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-19 08:52 UTC, yogkumgit commented
@msbemba

2022-10-20 12:21 UTC, yogkumgit commented
@msbemba gentle reminder

2022-10-23 01:23 UTC, opbld32 commented
Learn Build status updates of commit _[a00fcb9](https://github.com/msbemba/microsoft-365-docs/commits/a00fcb98a200b8f1c323674aa547826a195bfbd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/set-scheduling-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1278/microsoft-365/bookings/set-scheduling-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210230121291596-9979/BuildReport?accessString=d07ad19321daba6528846fa3d09a3e1522408e9b43b926a2efa7a3b7c02f8a1a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 05:04 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-24 05:04 UTC, yogkumgit commented
@kwekuako Pease merge this PR. Thanks

2022-10-24 13:59 UTC, JohanFreelancer9 approved these changes

2022-11-01 10:47 UTC, yogkumgit commented
@kwekuako Gentle reminder

2022-11-02 19:05 UTC, opbld32 commented
Learn Build status updates of commit _[331bbf7](https://github.com/msbemba/microsoft-365-docs/commits/331bbf77d686e1f91aeabb06d567762e43f39d41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/set-scheduling-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1278/microsoft-365/bookings/set-scheduling-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211021900067420-9979/BuildReport?accessString=1f1987e3f3f4bbda8db7f71f1aaf7860ff8157d1e79389f4a3a77582eb1666f5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-02 19:07 UTC, opbld33 commented
Learn Build status updates of commit _[7b2b431](https://github.com/msbemba/microsoft-365-docs/commits/7b2b431055360289bd4d5d799339b2889558d605)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/bookings/set-scheduling-policies.md](https://github.com/msbemba/microsoft-365-docs/blob/patch-1278/microsoft-365/bookings/set-scheduling-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202211021905037195-9979/BuildReport?accessString=68e62ddfaabb3c1b75f362cd6d6ccf6f4e364e5cac3e70b897c9efe90feb8edf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-02 19:43 UTC, merged