Update whats-new-in-defender-for-office-365.md
MicrosoftDocs/microsoft-365-docs pull request #9982
Opened 2022-10-18 16:31 UTC by ajaj-shaikh

Added URL click alerts enhancement as part of Oct'22 updates

2022-10-18 16:33 UTC, opbld32 commented
Learn Build status updates of commit _[f262a1d](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/f262a1d443fff80a719cf1c3506cc78a4a021f0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210181631210558-9982/BuildReport?accessString=09eb147172373a3b6b1d546a4261d8c0d56fd2afef93ba9355ea58181e8e681d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 05:52 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md
> +  - With the new lookback scenario, "A potentially malicious URL click was detected" alert will now include any clicks in the **past 48 hours** (for emails) from the time the malicious URL verdict is
```suggestion
- **Enhancement in URL click alerts:**
  - With the new lookback scenario, the "A potentially malicious URL click was detected" alert will now include any clicks in the **past 48 hours** (for emails) from the time the malicious URL verdict is identified. 
```

2022-10-19 05:55 UTC, JohanFreelancer9 requested changes
Copy review - @ajaj-shaikh, kindly commit the suggested changes. Many thanks.

2022-10-19 07:24 UTC, opbld30 commented
Learn Build status updates of commit _[f8a33ea](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/f8a33eac441adff8926ce25317dead5ebb51b848)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210190722219405-9982/BuildReport?accessString=b359d1a041e5a9fde31fcd9545f87484c33e3f0d3e039d29fa8a3db79ecce090).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 07:25 UTC, ajaj-shaikh commented
@MSFTTracyP can you please merge this PR?

2022-10-20 12:21 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-20 14:21 UTC, opbld30 commented
Learn Build status updates of commit _[6735b91](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/6735b91438a470aca22aea1d368728508a9013f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210201419226421-9982/BuildReport?accessString=077f3c3d34d9ade7fb61e52df77fb206a9d6518c3aa61ba3ff625486d6ed485b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 05:03 UTC, JohanFreelancer9 commented
@yogkumgit - my suggested changes have not been implemented yet.

2022-10-21 06:12 UTC, opbld32 commented
Learn Build status updates of commit _[d535b34](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/d535b344ab1239058e4cb5efbdacec1f23ff9a90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210210610534347-9982/BuildReport?accessString=8497810d5b9a1d7f64d2e2f87b8b512e9e023eb46c6263be9bfdcab42d966b66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 06:14 UTC, opbld32 commented
Learn Build status updates of commit _[a93aa60](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/a93aa60f3c1b6ec95ae5c23c0cc65965f46505a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210210611071076-9982/BuildReport?accessString=be55a1659895e76d46d9c2b88e6a8f289878f55eb6760852a0a3e8fe69c469d0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 08:33 UTC, JohanFreelancer9 approved these changes

2022-10-21 11:38 UTC, yogkumgit commented
@MSFTTracyP Please merge this PR. Thanks

2022-10-21 14:28 UTC, opbld32 commented
Learn Build status updates of commit _[e310ceb](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/e310ceb3b304f8286b43bb95b819c1abdbccfa53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-5/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210211426335505-9982/BuildReport?accessString=c79d70e2dc8fe444f48b463ad574e1b8065f5669b960589e4bd27e56aaa8df1a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 14:28 UTC, merged