Update whats-new-in-defender-for-office-365.md
MicrosoftDocs/microsoft-365-docs pull request #9983
Opened 2022-10-18 16:51 UTC by ajaj-shaikh

Added BCL details as part of Sept'22 updates

2022-10-18 16:53 UTC, opbld31 commented
Learn Build status updates of commit _[73b6f4e](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/73b6f4e65941cd51849679d996662ba3a9b689c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-6/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210181651549028-9983/BuildReport?accessString=895e38ffcb203452bc721295cd493f06e4e051d684474d3cd80da5f69e2ecdcd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 06:06 UTC, JohanFreelancer9 commented on microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md
> +- **Bulk Complaint Level** is now available in EmailEvents table in Advanced Hunting with numeric BCL values from 0 to 9. A higher BCL score indicates that bulk message is more likely to generate com
```suggestion
- **Bulk Complaint Level** is now available in the EmailEvents table in Advanced Hunting with numeric BCL values from 0 to 9. A higher BCL score indicates that bulk message is more likely to generate complaints and is more likely to be spam.
```

2022-10-19 06:06 UTC, JohanFreelancer9 requested changes
Copy review - @ajaj-shaikh, kindly commit the suggested change. Many thanks.

2022-10-19 07:14 UTC, opbld33 commented
Learn Build status updates of commit _[7383dc1](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/7383dc124e41046c24d5829058134b26a14da197)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-6/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210190706479024-9983/BuildReport?accessString=24cd72a08ba17a635a13a1efafc33bdb3ac43619168eb09bd24c776ffcbbdfd6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 07:19 UTC, opbld31 commented
Learn Build status updates of commit _[40270ad](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/40270ad86a369c4327b4a8cf92a9e9449fba7908)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-6/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210190707204016-9983/BuildReport?accessString=49e5f1ccf1cd94741b37f8329f01f3bf5fa6719f5fb0b23b165d0cf01ffdbcb2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 07:21 UTC, ajaj-shaikh commented
@MSFTTracyP can you please merge this request?

2022-10-19 09:15 UTC, JohanFreelancer9 approved these changes

2022-10-20 14:22 UTC, opbld33 commented
Learn Build status updates of commit _[7b3e025](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/7b3e025f56944b0c910aa504c9d414b4b8c3a125)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-6/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210201420257231-9983/BuildReport?accessString=370345f4e51c05485567643dd137f01efd836993665a55494b6f2f8c2b4c91f4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 14:31 UTC, opbld30 commented
Learn Build status updates of commit _[6a0eb1e](https://github.com/ajaj-shaikh/microsoft-365-docs/commits/6a0eb1e4bd44662146c36f3f970c9d21444ef7b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/ajaj-shaikh/microsoft-365-docs/blob/patch-6/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/76d60323-5511-5963-adf9-59162c800b4a/202210211429312918-9983/BuildReport?accessString=0a0e8c13515d72428b20fc14d602a736aa0735ae6224d6fffec2b32c09269289).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/76d60323-5511-5963-adf9-59162c800b4a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 14:32 UTC, merged